### ISSUE TITLE
Bit Coin Wallet_ Contacts - Error on back press

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#100]
### Bitcoin Wallet 

-----

##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Al ingresar en la pantalla de contactos la aplicacion se pone lenta y se cuelga y aunque no muestra ningun error, se queda estatica, como se ve en la imagen, y debo salir por completo de la aplicacion, esto sucedio un par de veces.
![screenshot_2016-03-28-11-58-45](https://cloud.githubusercontent.com/assets/17274154/14110760/b2683938-f591-11e5-9582-32db2de3259b.png)
  .
   ------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4 
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc verificar estos problemas de cierres y demoras con la nueva version disponible

**Comment by maydiamc** [comment]
@nattyco en la ultima actualizacion se corrigio este error @MaviDavsa
