### ISSUE TITLE
Bitcoin Wallet_Graphic_ Boton Add Contacto - Superposicion de texto

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#102]
### Bitcoin Wallet 

------
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [x] Pop up de agregar un contacto 

##### Reporte de error: 

   * Al tener desplegado el pop up de agregar contactos y abrir el Navigation View, en vez de replegarse de nuevo se mantiene abierto y se superpone con el Navigation View y esto no permite buena visibilidad del texto.
![screenshot_2016-03-29-08-56-06](https://cloud.githubusercontent.com/assets/17274154/14111429/7d286d62-f594-11e5-8d90-779331cef92f.png)

   
   

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4 
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by maydiamc** [comment]
persiste el problema en la ultimaactualizacion

**Comment by MaviDavsa** [comment]
![fdgdfg](https://cloud.githubusercontent.com/assets/17273005/15131685/f17b9a48-161b-11e6-81c8-dca8c99937d7.JPG)

Dispositivo desde donde se realizo la prueba

Marca: Google Nexus
Modelo: 4
Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  Resuelto,el boton se oculta al abrir el menu.

**Comment by MaviDavsa** [comment]
Solucionado!
