### ISSUE TITLE
Graphic_Bitcoin Wallet_ Detalles de contacto

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#103]
### Bitcoin Wallet 

-----
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   * Al ingresar a cualquier contacto, automaticamente se despliega el teclado del telefono y al tratar de quitarlo este se queda en negro y debo presionar la pantalla nuevamente en cualquier lugar para que se vea el resto de la pantalla.

![screenshot_2016-03-29-08-59-16](https://cloud.githubusercontent.com/assets/17274154/14111674/77096b88-f595-11e5-9e38-22896ec34f2f.png)
   
   --------
#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4 
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  probar en la nueva version si el teclado dejo de aparecer, no debe dejarte poner el cursor sobre el nombre ya que no es editable.

**Comment by maydiamc** [comment]
@nattyco este error problema fue solucionado
