### ISSUE TITLE
Bit Coin Wallet_Performance Error (No Recibo BTC)

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#104]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Desde ayer solo recibo Payment Request, y puedo envíar BTC pero no recibo nada ni Payments ni BTC que me han enviado mis compañera el balance esta igual y no muestra por ningun lado haber recibido nada.

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Apex2
* Version de Android: 4.4.2

**Comment by adryx83** [comment]
@nattyco

**Comment by adryx83** [comment]
@nattyco cuando solicito BTC a las demas chicas y ellas aceptan no me llega nada, y si me envian btc tampoco llega, ahora los que pedi en el faucet si me llegaron normal

**Comment by adryx83** [comment]
@nattyco otra cosa lo que yo envío si me lo descuentan del balance

**Comment by nattyco** [comment]
@adryx83  Los btc que vos enviaste y se te descontaron les llegan a los otros? se te descontaron del book?

**Comment by adryx83** [comment]
@nattyco bueno ayer aparentemente llegaron pero hoy a nadie le llego

**Comment by nattyco** [comment]
@adryx83 sobre este caso comentame si seguis con problemas para enviar y recibir btc

**Comment by nattyco** [comment]
@adryx83  probar esto en la nueva version y comentar los resultados

**Comment by nattyco** [comment]
@MaviDavsa  verificar nuevamente este reporte

**Comment by maydiamc** [comment]
solucionado, cerrar @MaviDavsa @sanro14
