### ISSUE TITLE
Error_ Bitcoin Wallet_ No llegan las notificaciones

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#105]
### Bitcoin Wallet 

------
##### Settings

- [x] Pantalla de Setting

##### Reporte de error: 

   * Aunque las notificaciones estan activadas, no me llega ningun aviso de aceptacion de solicitud de contacto, sino que debo entrar a la crypto wallet constantemente para aceptar las solicitudes o que el contacto que me la envio me avise para revisar y aceptarlo .
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4 
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@furszy por lo que pude probar en el codigo en el punto donde tiene que ejecutar el publish no tiene el context.

**Comment by maydiamc** [comment]
En la ultima aplicacion se sluciono este problema! @nattyco
