### ISSUE TITLE
Bitcoin Wallet - Error al cargar la Aplicacion

### ISSUE THREAD

**Issue by yahdieli** [Fermat-ORG/beta-testing-program#106]
#### Nombre pantalla

Bitcoin Wallet

##### Reporte de error: 

   *Al abrir Fermat carga correctamente y salen las diferentes aplicaciones para escoger cual abrir pero al seleccionar la aplicación Bitcoin Wallet se queda trabada y queda un rato en pantalla negra, luego de un tiempo no carga mas y sale un mensaje de error. Este error me ha sucedido 5 veces seguidas y he reiniciado el emulador pero aún así persiste el problema, no deja ni siquiera entrar a la aplicación.

![image](https://cloud.githubusercontent.com/assets/17284821/14114859/9497c05c-f5a2-11e5-8b0b-1b3d2410b646.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: BlueStacks
* Modelo: 2.0
* Version de Android: 6.0

**Comment by yahdieli** [comment]
@nattyco

**Comment by nattyco** [comment]
@yahdieli  verificar estos problemas de cierres y demoras con la nueva version disponible

**Comment by yahdieli** [comment]
@nattyco He probado la nueva versión de Fermat subida el día de hoy y no me arroja mas ese problema, me esta corriendo muy bien en el emulador Bluestacks. Permite entrar de forma normal y rápida y también los problemas de antes que se quedaba pegada y era lenta en esta nueva versión ya no es así, es rápida.

**Comment by nattyco** [comment]
ok lo cerramos
