### ISSUE TITLE
Bitcoin Wallet - los BTC no son recibidos desde el faucet

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#107]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   * Los BTC fueron solicitados desde el faucet y van ya 24 horas y nunca se reflejaron ni en el book balance ni en el Available Balance, se verifico que el adress estuviera correcto y todo esta bien.

##### Capture del dia lunes
![screenshot_2016-03-28-11-54-51](https://cloud.githubusercontent.com/assets/17274154/14114768/324bdd16-f5a2-11e5-9689-59113f31d81f.png)

##### Capture del dia martes
![screenshot_2016-03-29-11-36-28](https://cloud.githubusercontent.com/assets/17274154/14114868/9d29a780-f5a2-11e5-8976-28492ea5545f.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy 
* Modelo del telefono: S4mini
* Version del android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@acostarodrigo  Yo tambien trate de pedir hoy al faucet externo y no llega la transacción. Se cambio algo?

**Comment by acostarodrigo** [comment]
Nada. Confirmame si se comienza a bajar el blockchain.
El download progress estara corregido hoy para poder ver eso desde la GUI

**Comment by nattyco** [comment]
@acostarodrigo  Puede ser que la red esta lenta para descargar los bloques? arranco hace mas de media hora en 
***CryptoNetwork*** Block downloaded on testnet. Pending blocks: 26000

Pero a la tester que reporto desde ayer que pidio y no le llegaron

**Comment by nattyco** [comment]
@maydiamc  verificar este caso con la nueva version de la app, tener en cuenta que la red de testnet es mas lenta, yo probe y tardo unos 15 min en llegar.

**Comment by acostarodrigo** [comment]
recuerden que tambien me pueden pedir bitcoins a mi, yo tengo un cliente en TestNet con muchos bitcoins y les mando con un fee alto asi lo procesan rapidos los nodos.

**Comment by acostarodrigo** [comment]
ademas, ya esta subida a develop la barra de progreso del blockchain para todos los tipos de network.
@nattyco creo que deberian hacer un nuevo apk para el equipo de Augusto.

**Comment by nattyco** [comment]
@maydiamc  probar esto en la nueva version y comentar los resultados

**Comment by maydiamc** [comment]
en la ultima actualizacion los btc del faucet se recibieron en al menos 15min @nattyco
