### ISSUE TITLE
Bit Coin Wallet_Performance ( App Muy Lenta)

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#108]
#### Nombre pantalla

Bit Coin Wallet 

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *La aplicación esta muy pesada, lenta para moverme del menú a otras pantallas y al realizar cualquier acción.

------

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo:Apex2
* Version de Android: 4.4.2

**Comment by adryx83** [comment]
@nattyco

**Comment by nattyco** [comment]
@furszy

**Comment by adryx83** [comment]
he visto mejora en cuanto a la velocidad de la aplicación en la ultima actualización @nattyco
