### ISSUE TITLE
Bitcoin Wallet - error de redireccionamiento en las notificaciones

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#110]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Me llega la notificación de la nueva versión de hoy 30/03/2016, pero no esta redirigiendo como antes se hacia. 

#### Dispositivo desde donde se realizo la prueba

* Marca:CANAIMA 
* Modelo:TR10RS1
* Version de Android: 4.4.4

**Comment by nattyco** [comment]
@furszy

**Comment by furszy** [comment]
Necesito más información por favor, que es " no esta redirigiendo como antes se hacia". 
Notificación que sale, a donde llevaba, a donde lleva ahora, etc.

**Comment by sanro14** [comment]
@furszy lo que sucede es que sale la notificación de que llego una solicitud de contacto, y cuando le doy click para entrar a esa notificación se queda estática,  no me redirige automáticamente a la crypto wallet user como lo hacia antes.. no se si me explico..

**Comment by sanro14** [comment]
@furszy ya lo puedes cerrar

**Comment by furszy** [comment]
Perfecto.
