### ISSUE TITLE
Error_Bitcoin Wallet_ aplicacion da error y muy lenta

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#112]
### Bitcoin Wallet 

-----

En la ultima actualizacion la aplicacion en general esta muy lenta y dio error en diferentes pantallas y en distintas ocasiones
![screenshot_2016-03-30-10-33-43](https://cloud.githubusercontent.com/assets/17274154/14177368/c8e46ea4-f71f-11e5-9837-6f5c87725007.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@furszy

**Comment by furszy** [comment]
Hola, te digo algunas cosas para que tengas en cuenta, No esperes demasiada velocidad en un samsung S4 mini, no es un bug que el teléfono tenga poca memoria RAM, las optimizaciones en cuanto a velocidad son temas a mejorar en todo momento pero no cuentan como bugs si no que reportes de performance.
El cuanto al fallo, por favor detalla me más el contexto, que hiciste para que eso ocurra, de donde a donde querías ir, que tocaste, etc.
Gracias.

**Comment by maydiamc** [comment]
Estaba en home y abri el navigation view.! Pero no solo es mi telefono las chicas han tenido el mismo problema y ellas usan emulador algunas y la otra tiene otro telegono distinto al mio.! Creo que el problema es la aplicacion xq hay actualizaciones que corren perfecto.!

**Comment by maydiamc** [comment]
Y augusto nos dijo que cuando la aplicacion falla o se detiene y se sale lo comentaramos como error, por eso lo hice de ese modo, hablare con el mañana para preguntarle exactamente de que se trata performance y bug @furszy

**Comment by furszy** [comment]
Anotalas esas también por favor, si ves que la actualización mejora anotalo así tenemos parámetros de que puede ser, por ejemplo yo en esta actualización mandé otras plataformas encendidas que antes no lo estaban.
@nattyco chequea este error que está dentro de la bitcoin wallet y avisame.

**Comment by furszy** [comment]
Dale, si la app va más lento que previas actualizaciones avisame, al igual que si va más rápido. Tu comparación tiene que ser así y no con otros dispositivos con más memoria RAM,núcleos,etc.

**Comment by maydiamc** [comment]
Ok en cada actualizacion te subire la fecha y como va comportandose la app, yo entiendo pero te comparo con  otros dispositivos, para que veas que no solo es mi dispositivo el que tiene el problema.! Pero sere mas detallada con los issues de este tipo en cuanto a detalles de las actualizaciones para que se guien bien.!

**Comment by furszy** [comment]
gracias!

**Comment by nattyco** [comment]
@maydiamc  verifica este caso con la nueva version y comentame como resulta.

**Comment by maydiamc** [comment]
@nattyco problema resuelto en la actualizacion del 04/04/16
