### ISSUE TITLE
Graphic_Bitcoin Wallet_ Duplicacion de seleccion de contacto

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#113]
### Bitcoin Wallet 

-----

##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo
- [x] Add Fermat user

##### Reporte de error: 

   * En la pantalla de seleccionar los contactos de fermat para agregarlos a la lista de contactos, en el momento de tildar un contacto este no se marca sino que se duplica y esto crea confusion.
![screenshot_2016-03-31-10-30-31](https://cloud.githubusercontent.com/assets/17274154/14181805/6c7d8282-f732-11e5-846f-749f7b08d240.png)

   
   -------
#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  tenias un solo nombre en la lista y cuando lo tocas aparece otro? al desmarcarlo desaparecio?

**Comment by nattyco** [comment]
@maydiamc  probar esto con la nueva version de la app

**Comment by maydiamc** [comment]
se soluciono este problema en la ultima actualizaciom @nattyco
