### ISSUE TITLE
BitcoinWallet_error cuando intento abrir la wallet

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#114]
### Bitcoin Wallet 

Cuando voy a abrir el wallet me sale este error y no me permite abrirlo. lo he intentado varias veces. Lo volví a instalar y sale lo mismo

#### Dispositivo desde donde se realizo la prueba

* Marca:CANAIMA
* Modelo:TR10RS1
* Version de Android:4.4.4

 
![screenshot_2016-03-31-11-08-37](https://cloud.githubusercontent.com/assets/5313324/14182011/447416ce-f733-11e5-8fb8-d178db16bb83.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Buenos días Maria, 
El mismo error ( no permite ingresar a la Bitcoin Wallet)
Emulador Genymotion- samsung Galaxy S6 Android 6.0.0

**Comment by nattyco** [comment]
@furszy  veo que en ocaciones da error al querer entrar en la wallet, en el log se ve esto

Exception Number: 1
04-04 11:40:20.237    4518-4518/org.fermat W/System.err﹕ Exception Type: class java.lang.NullPointerException
04-04 11:40:20.237    4518-4518/org.fermat W/System.err﹕ Exception Message: Attempt to invoke virtual method 'com.bitdubai.fermat_api.layer.all_definition.navigation_structure.TabStrip com.bitdubai.fermat_api.layer.all_definition.navigation_structure.Activity.getTabStrip()' on a null object reference
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ Exception Possible Cause: N/A
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ Exception Context:
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ N/A
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ Exception Stack Trace:
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ Class: com.bitdubai.android_core.app.AppActivity - Line: 255
04-04 11:40:20.238    4518-4518/org.fermat W/System.err﹕ Class: com.bitdubai.android_core.app.AppActivity - Line: 63

**Comment by nattyco** [comment]
@sanro14 probar esto en la nueva version y comentar los resultados

**Comment by sanro14** [comment]
@nattyco el error ya no me ha salido. Cerrar

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

El error 156:
Al entrar en la pantalla de la Crypto Wallet user los usuarios no aparecen.

   - Marca:ZTE
   - Modelo:Kis II Max
   - Version de Android:4.4.2


En prueba de hoy 14-04-16 con la nueva apk, aparecen ya los cryto user, te
adjunto una foto, puedes cerrar el caso.
En espera de tus indicaciones
Saludos

2016-04-07 12:42 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @sanro14 <https://github.com/sanro14> probar esto en la nueva version y
> comentar los resultados
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/114#issuecomment-206998584>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

En el caso 134:
Estando en el Home, al hacer click en el botón de retroceso, este se ve por
debajo (esta
solapado)

   - Marca:ZTE
   - Modelo:Kiss II Max
   - Version de Android: 4.4.2


En prueba de hoy 14-04-16 con la nueva apk, aparece el mismo
error gráfico , te adjunto una foto.
En espera de tus indicaciones
Saludos

El 14 de abril de 2016, 13:03, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Buenas tardes Natalia Cortes
>
> El error 156:
> Al entrar en la pantalla de la Crypto Wallet user los usuarios no aparecen.
>
>    - Marca:ZTE
>    - Modelo:Kis II Max
>    - Version de Android:4.4.2
>
>
> En prueba de hoy 14-04-16 con la nueva apk, aparecen ya los cryto user, te
> adjunto una foto, puedes cerrar el caso.
> En espera de tus indicaciones
> Saludos
>
> 2016-04-07 12:42 GMT-04:30 Natalia Cortez <notifications@github.com>:
>
>> @sanro14 <https://github.com/sanro14> probar esto en la nueva version y
>> comentar los resultados
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/114#issuecomment-206998584>
>>
>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> 0426-9811123
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

El error 156:
Al entrar en la pantalla de la Crypto Wallet user los usuarios no aparecen.

   - Marca:ZTE
   - Modelo:Kis II Max
   - Version de Android:4.4.2


En prueba de hoy 18-04-16 con la nueva apk, (viernes 15-04-16) aparecen ya
los cryto user, te adjunto una foto, puedes cerrar el caso.
En espera de tus indicaciones.
Saludos

El 14 de abril de 2016, 13:03, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Buenas tardes Natalia Cortes
>
> El error 156:
> Al entrar en la pantalla de la Crypto Wallet user los usuarios no aparecen.
>
>    - Marca:ZTE
>    - Modelo:Kis II Max
>    - Version de Android:4.4.2
>
>
> En prueba de hoy 14-04-16 con la nueva apk, aparecen ya los cryto user, te
> adjunto una foto, puedes cerrar el caso.
> En espera de tus indicaciones
> Saludos
>
> 2016-04-07 12:42 GMT-04:30 Natalia Cortez <notifications@github.com>:
>
>> @sanro14 <https://github.com/sanro14> probar esto en la nueva version y
>> comentar los resultados
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/114#issuecomment-206998584>
>>
>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> 0426-9811123
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

En el caso 134:
Estando en el Home, al hacer click en el botón de retroceso, este se ve por
debajo (esta
solapado)

   - Marca:ZTE
   - Modelo:Kiss II Max
   - Version de Android: 4.4.2


En prueba de hoy 18-04-16 con la nueva apk,
(viernes 15-05-16)aparece el mismo error gráfico , te adjunto una foto.

El 14 de abril de 2016, 13:13, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Buenas tardes Natalia Cortes
>
> En el caso 134:
> Estando en el Home, al hacer click en el botón de retroceso, este se ve
> por debajo (esta
> solapado)
>
>    - Marca:ZTE
>    - Modelo:Kiss II Max
>    - Version de Android: 4.4.2
>
>
> En prueba de hoy 14-04-16 con la nueva apk, aparece el mismo
> error gráfico , te adjunto una foto.
> En espera de tus indicaciones
> Saludos
>
> El 14 de abril de 2016, 13:03, Yolanda Yancel<yyancel47@gmail.com>
> escribió:
>
>> Buenas tardes Natalia Cortes
>>
>> El error 156:
>> Al entrar en la pantalla de la Crypto Wallet user los usuarios no
>> aparecen.
>>
>>    - Marca:ZTE
>>    - Modelo:Kis II Max
>>    - Version de Android:4.4.2
>>
>>
>> En prueba de hoy 14-04-16 con la nueva apk, aparecen ya los cryto user,
>> te adjunto una foto, puedes cerrar el caso.
>> En espera de tus indicaciones
>> Saludos
>>
>> 2016-04-07 12:42 GMT-04:30 Natalia Cortez <notifications@github.com>:
>>
>>> @sanro14 <https://github.com/sanro14> probar esto en la nueva version y
>>> comentar los resultados
>>>
>>> —
>>> You are receiving this because you commented.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Fermat-ORG/beta-testing-program/issues/114#issuecomment-206998584>
>>>
>>
>>
>>
>> --
>> *Saludos cordiales*
>>
>> *Yolanda Yancel*
>> Lcda. Contaduría Pública
>> 0426-9811123
>> Email.yyancel47@gmail.com
>>
>>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> 0426-9811123
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

El error 156:.

   - Marca:ZTE
   - Modelo:Kis II Max
   - Version de Android:4.4.2


En prueba de ayer 18-04-16 con la nueva apk, (viernes 15-04-16) aparecen ya
los cryto user, te adjunto una foto, puedes cerrar el caso.
En espera de tus indicaciones.
Saludos

>
>

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

En el caso 134:
Estando en el Home, al hacer click en el botón de retroceso, este se ve por
debajo (esta
solapado)
Celular:

   - Marca: ZTE
   - Modelo: Kiss II Max
   - Versión de Android: 4.4.2


En prueba de hoy 21-04-16
Apk (20-04-2016), aparece el mismo error gráfico , te adjunto una foto.
En espera de nuevas indicaciones.


*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

En el caso 156:
Al entrar en la pantalla de la Crypto Wallet user los usuarios no aparecen.
Celular:

   - Marca: ZTE
   - Modelo: Kiss II Max
   - Versión de Android: 4.4.2


En prueba de hoy 14-04-16
Apk (12-04-2016),
Este error está corregido desde el 15-04-16, como te comente en esa
oportunidad por correo el caso hay que cerrarlo.
En espera de nuevas indicaciones.

-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas días Natalia Cortes

El error 160:
Estando en Home y piso el botón de contactos, aparece un recuadro con un
error que no permite ingresar al mismo..

   - Marca:ZTE
   - Modelo:Kis II Max
   - Version de Android:4.4.2


En prueba de hoy 21-04-16
Apk-21-04-16 ingresa a la pantalla de contactos sin problemas, se corrigió
el error.
Adjunto una foto, puedes cerrar el caso.
En espera de tus indicaciones
Saludos

*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes


   - El error 161:
   Estando en contactos y piso el botón de agrerar los Fermat User y
   aparece un recuadro, luego se sale de la Wallet
   - Marca:Emulador Genymotion
      - Modelo:Sansumg Galaxy S 6 ApI 22-1440x2560
      - Version de Android: 5.1

   En prueba de hoy 21-04-16
   Apk-21-04-16:Estando en contactos y piso el botón de agregar los
   Fermat User, ya no aparece el error.
   Adjunto una foto, puedes cerrar el caso.
   En espera de tus indicaciones


*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes


   - El error 168:

Estando en la pantalla de Request y pisar el botón de retroceso para ir al
Home, salio un error, no me permitió entrar. Tuve que cerrar la Bitcoin
Wallet.

   - Marca:Emulador Genymotion
   - Modelo:Sansumg Galaxy S 6 ApI 22-1440x2560
   - Version de Android: 5.1


En prueba de hoy 21-04-16
Apk-21-04-16:
Estando en la pantalla de Request y pisar el botón de retroceso para ir al
Home, ya no aparece el error.
Adjunto una foto, puedes cerrar el caso.
En espera de tus indicaciones

*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com
