### ISSUE TITLE
Bitcoin Wallet- Problemas con los Decimales y Numeros

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#116]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

Solicite BTC en la red RegTest y me llegaron 50.000.000 de BTC. Luego al solicitar BTC al contacto Natalia me paso lo siguiente, solicite 3.5 BTC y cuando mande la solicitud en la pantalla de Request me figura un numero enorme al así como 35000000 BTC. Lo mismo sucedió cuando le solicite 3 BTC y me paso lo mismo.

MONTO QUE ME LLEGO CUANDO SOLICITE LOS BTC MENOS DOS BTC QUE MANDE A NATY POR ESO ME APARECE 48.000.000 Y NO 50.000.000 COMO ERA EN UN PRINCIPIO CUANDO LOS RECIBI.
<img width="406" alt="captura de pantalla 2016-04-04 a las 12 39 31" src="https://cloud.githubusercontent.com/assets/15804433/14253550/5017d2f4-fa62-11e5-9f3b-70a64cac1151.png">

MOMENTO EN QUE SOLICITO LOS 3 BTC
<img width="403" alt="captura de pantalla 2016-04-04 a las 12 36 21" src="https://cloud.githubusercontent.com/assets/15804433/14253627/9c99e55e-fa62-11e5-9da4-a80763d74228.png">

ME APARECE ESTE NUMERO GRANDE EN VEZ DE SOLO LOS 3 BTC SOLICITADOS
<img width="402" alt="captura de pantalla 2016-04-04 a las 12 11 15" src="https://cloud.githubusercontent.com/assets/15804433/14253504/201a2e62-fa62-11e5-96a3-7309d3021bf5.png">

------

#### Dispositivo desde donde se realizo la prueba

<img width="408" alt="captura de pantalla 2016-04-04 a las 12 42 42" src="https://cloud.githubusercontent.com/assets/15804433/14253662/c746e662-fa62-11e5-9fe8-ca090191cb36.png">

**Comment by augusto-ponce** [comment]
@nattyco

**Comment by nattyco** [comment]
@augusto-ponce  No he podido reproducir este error, te fijaste que pasa en el balance si cambias entre book y available, y si tocas donde dice btc para ver el monto en bis. Es muy raro este error de formateo

**Comment by augusto-ponce** [comment]
Nati, al tocar y cambiar de btc a bis no pasa nada. Lo que hice después es cerrar la aplicación por completo y al volver a abrir la aplicación se soluciono !! lo numero habían cambiado a la normalidad, pero tuve que cerrarla.
