### ISSUE TITLE
bitcoin Wallet- Bitcoins recibidos no se reflejan en Transacciones Recibidas

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#117]
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

Este error surge cuando después de haber recibido en 3 oportunidades Btc de mi contacto Yahadiely1 no se ve reflejado los mismos en la pantalla de Home en el sector de RECEIVED. Solamente tengo reflejando ahí los Btc recibidos por mi contacto Maria en 3 oportunidades y mi contacto Mati Bitcoins que es de donde solicito los 50 btc.

PANTALLA EN DONDE SE PUEDE VER QUE NO FIGURA LOS BTC DE YADHIELI1. (si entraron los btc de esta persona en el Balance)

<img width="405" alt="captura de pantalla 2016-04-04 a las 13 53 51" src="https://cloud.githubusercontent.com/assets/15804433/14262037/e12bfd70-fa89-11e5-8118-4e94b8d4e9e5.png">

   PANTALLA DEL TELEFONO DE YAHADIELY1 corroborando el envío de los Btc los cuales he recibido a la perfeccion ! 

<img width="407" alt="captura de pantalla 2016-04-04 a las 13 51 53" src="https://cloud.githubusercontent.com/assets/15804433/14262079/16b99682-fa8a-11e5-837b-0df86bcd4685.png">

MUESTRO LA EXISTENCIA DEL CONTACTO YAHADHIELY1 EN MI TEL

<img width="403" alt="captura de pantalla 2016-04-04 a las 17 27 46" src="https://cloud.githubusercontent.com/assets/15804433/14262211/acb4a8ac-fa8a-11e5-85ff-2765aa89cc3a.png">

------
##### Reporte de error: 

------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="408" alt="captura de pantalla 2016-04-04 a las 12 42 42" src="https://cloud.githubusercontent.com/assets/15804433/14262150/63d8e8a0-fa8a-11e5-9848-0b7b4af12b37.png">

**Comment by augusto-ponce** [comment]
@nattyco

**Comment by nattyco** [comment]
@augusto-ponce  seguro que instalaste la ultima apk disponible a la fecha? porque veo que el listado de transacciones recibidas no se ve agrupado como lo ve Yahadiely1, en tu cas tendrias que ver lo que recibiste de Maria agrupado

**Comment by augusto-ponce** [comment]
Si Naty es la ultima, la instale hoy junto con el telefono que baje. Lo de Maria me figura perfecto lo que me mando ! El problema esta en el contacto Yahadiely que no aparece ahí pero si se me sumo en el book balance !

**Comment by nattyco** [comment]
Lo que te envio Yahediely te llego solo al book entonces?, porque las transacciones solo las vas a ver en el listado cuando pasen al available, y tene en cuenta que la red Regtest se suele saturar con muchos usuarios conectados y no se confirman los btc. Pero si te llegaron al book el proceso de envio de btc fue correcto, solo falta que se confirmen.

**Comment by augusto-ponce** [comment]
solucionado en el cel que estoy probando ahora
