### ISSUE TITLE
Sub App Community - No se ven los usuarios conectados

### ISSUE THREAD

**Issue by yahdieli** [Fermat-ORG/beta-testing-program#118]
##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *La lista de los usuarios en la red Fermat no aparece ni yo aparezco en la lista de contactos de los demás usuarios conectados. No es problema de Internet ya que la conexión es estable y rápida. Ya he abierto varias veces la aplicación y aún así no aparecen los contactos.
   
   
![final_bstsnapshot_75463](https://cloud.githubusercontent.com/assets/17284821/14287677/75be5698-fb1d-11e5-940e-90d9af72b0c0.jpg)

#### Dispositivo desde donde se realizo la prueba

* Marca: Bluestacks
* Modelo: 2.0
* Version de Android: 6.0

**Comment by yahdieli** [comment]
@nattyco

**Comment by nattyco** [comment]
@yahdieli   probar este caso con la nueva version de la app

**Comment by yahdieli** [comment]
En la nueva versión ya se pueden ver los usuarios conectados.
