### ISSUE TITLE
Graphic_Fermat Chat_ teclado superpuesto

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#119]
### Fermat Chat 

-----

##### Ventana de chat

- [x] Pantalla de chat con contacto

##### Reporte de error: 

   *En la ventana del chat al intentar escribir el texto el teclado se desplega y la linea de escritura de texto no se coloca a la vista, sobre el teclado del telefono, sino que queda detras y esto obliga a replegar el teclado para poder observar que se esta escribiendo
![screenshot_2016-04-05-11-17-55](https://cloud.githubusercontent.com/assets/17274154/14288756/ecfd151a-fb21-11e5-9249-8c02ac356bb3.png)

 

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Saludos aun estamos sacando el issuer, hicimos unos ajustes funciona en otros dispositvo pero en el mini s4 con esa version de android, sigue pasando que se monta el teclado en lo que se escribe, ya el ajuste del mensaje al escribir esta hecho.

**Comment by maydiamc** [comment]
se soluciono el problema.! @franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
me preguntas?, o me afirmas...

**Comment by maydiamc** [comment]
Afirmacion

**Comment by franklinmarcano1970** [comment]
o sea que ya esta resuelto, con el apk que subi?

**Comment by franklinmarcano1970** [comment]
Aun estamos revisando porque solo pasa en la version 4.4.2

**Comment by AdryCanonico** [comment]
@maydiamc @franklinmarcano1970 En la version 19.2 persiste el error. 


![screenshot_2016-07-04-14-48-29](https://cloud.githubusercontent.com/assets/18584168/16568992/0e6df682-41ff-11e6-9bed-d35975f391e9.png)


http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16569005/1c43afe0-41ff-11e6-845e-28a4779c9f99.png)

**Comment by AdryCanonico** [comment]
persiste en la version 19.5 de CBP

**Comment by Gabymorillo** [comment]
En el teléfono físico, en la versión 20.1 del Chat no sucede este error. 

![screenshot_2016-07-08-13-32-00](https://cloud.githubusercontent.com/assets/17262077/16696382/a1ee4630-4512-11e6-90f5-60254ef5d907.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16696392/aee1a3c8-4512-11e6-92f3-3e130caabea0.png)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #119
