### ISSUE TITLE
Chat - Cierre inesperado

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#120]
##### Reporte de error: 

   *Mientras estaba en el chat como tal la pantalla se congelo de la nada, y el Fermat se cerro! Posteriormente trate de meterme nuevamente en la aplicación y me dio el error mostrado en la foto... Tuve que salirme desde cero, reiniciar el emulador y poder entrar nuevamente para que me corriera bien! 
![error 1 chat](https://cloud.githubusercontent.com/assets/17273005/14288871/4d207dd8-fb22-11e5-8aca-90117e4ff404.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 9
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Cuando te pases de nuevo y puedas volver a entrar, enviame el report de error, hay una opcion de send report, enviamelo a franklinmarcano1970@gmail.com
