### ISSUE TITLE
bitcoin Wallet- error al correr la aplicación 

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#121]
###   Wallet 

Cuando minimizo la app para abrir otras aplicaciones como el navegador, al momento de intentar abrir de nuevo fermat me muestra un error en la parte inferior de la pantalla, sin embargo no logre hacerle capture a las tantas veces que me salio. si logro hacerla se las paso por aquí, también a ratos lo que hacia era que no corria simplemente se quedaba en blanco.  

* Marca:canaima
* Modelo:TR10RS1
* Version de Android: 4.4

**Comment by nattyco** [comment]
@sanro14  comenta sobre este reporte si el error persiste

**Comment by sanro14** [comment]
@nattyco cerrar.
