### ISSUE TITLE
Chat - Busqueda de Contactos

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#122]
### Chat FERMAT

-----

##### Reporte de error: 

   *Me creé este chat desde 0 para buscar personar, cuando fui a las opciones nunca me mostró la forma de buscar a nuevos contactos, en el otro teléfono me daba la opción de Add Contacts pero en este teléfono no me dio ninguna opción... Y cuando le daba al botón de Search no hacia absolutamente nada! 
   
![error 2 chat](https://cloud.githubusercontent.com/assets/17273005/14289078/27d927b8-fb23-11e5-949b-4736e9f95633.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 6
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Porque sino tienes entidades creadas wallet users no puedes hacer nada.

**Comment by MaviDavsa** [comment]
Pero si las tengo creadas! :) @franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Dale, ya reviso!!!!!!!

**Comment by josejcb** [comment]
No, eso viene en la version 2, esto no se ataco en la version 1, posiblemente en los ultimos cambios q ya veniamos haciendo se fue. esto no es parte del alcance de la version 1. @franklinmarcano1970 @MaviDavsa

**Comment by franklinmarcano1970** [comment]
Ok pero el problema que tenemos que resolver es quitar esa opcion y porque no sale Add Contacts, que si es de esta version @josejcb

**Comment by franklinmarcano1970** [comment]
Pero tu instalaste el apk de version 1, el que bajaste pareciera que ustas usando la version actual que bajaste de la play store, recuerda que si creas un emulador nuevo tienes que copiar es el apk en cuestion.

**Comment by franklinmarcano1970** [comment]
la version que estamos probando es la version 1 de chat, la que bajaste del link que te pasamos!!!!

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Hice lo mismoo que hice con la otra! Arrastre la misma APK que descargue cuando estabamos hablando! :)
