### ISSUE TITLE
Chat_Graphic_ Linea de escritura de chat

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#123]
### Fermat Chat
-----

##### Ventana de Chat

- [x] Pantalla de Chat con contacto

##### Reporte de error: 

   * Al escribir un texto largo de varias palabras, la linea de escritura de chat no se ajusta a la cantidad de palabras, o a un tamaño un poco mayor, sino que se mantiene igual y esto hace incomoda la lectura del texto que se enviara por el chat. 
![screenshot_2016-04-05-11-19-02](https://cloud.githubusercontent.com/assets/17274154/14289054/0ab92f98-fb23-11e5-83ce-ebdc0ca3efe8.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Esto ya esta resuelto, solo que no lo vas a ver hasta que no saquemos el detalle del teclado superpuesto!!!!...

**Comment by MaviDavsa** [comment]
Versión de Android Antigua para la funcionalidad del App!
