### ISSUE TITLE
Chat - Comando no funcionan

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#124]
### CHAT Fermat

-----

##### Reporte de error: 

   *En este caso cuando quería enviar los mensajes, el teléfono no quiso responder al botón de enviar y por ende no enviaba los mensajes, todo lo demás me dejaba hacerlo, ir atrás, borrar, escribir todo normalmente, menos enviar los mensajes 
   
![error 3 chat](https://cloud.githubusercontent.com/assets/17273005/14289350/343a7c5e-fb24-11e5-97fa-46ab63a0c525.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 6 
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Podrias pasarme el log, con la opcion send report, al correo franklinmarcano1970@gmail.com

**Comment by MaviDavsa** [comment]
@franklinmarcano1970  Este caso sería por lo mismo de los anteriores!? Lo de las versiones!?

**Comment by franklinmarcano1970** [comment]
Si correcto!!!!
