### ISSUE TITLE
Bitcoin Wallet-error al correr la App

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#125]
#### Nombre pantalla
Samsung Galaxy S6
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Estando en el celular del emulador piso la apk FERMATpara hacerla correr, comienza a abrir normal pero a los minutos aparece un error que aparece en la foto que adjunto; y al pusar WAIT, entra a la APK. y a los pocos segundos se queda en negra la pantalla y aparece nuevamente el recuadro con el error anterior, le piso OK y se sale de la APK.
------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador Genymotion
* Modelo:Samsung Galaxy S6
* Version de Android:5.1
![error al iniciar fermat](https://cloud.githubusercontent.com/assets/17283358/14289534/03ce605c-fb25-11e5-89c7-6b4abad98c44.png)

**Comment by nattyco** [comment]
@yolandayancel  por lo que veo tenes una pc chica y no podes correr dos emuladores juntos con android de version tan grande fiajte de instalar una version de android mas chica y usar un solo emulador para probar la bitcoin wallet

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

Estoy haciendo la prueba en un solo emulador y con una versión 5.1 y si
pude correr la apk. Solicite los Btc al faucet. Pero no me han llegado. En
contactos envíe a rosana 1 una solicitud.

Saludos Cordiales

**Comment by nattyco** [comment]
@yolandayancel  ok entonces en este issue reportaste dos cosas  no me queda claro, decime que paso con la apk en el Samsung Galaxy S6

**Comment by yolandayancel** [comment]
Te explico natty
En el Samsung S6 versión 5.1 al correr ka apk Fernat comienza a abrir pero
a los minutos apareció un recuadro  que decía: Fermat isnt respindibg. Do
you want to close it? Wait ir ok , pise wait, entro y a los picos segundos
se puso negra la pantalla y apareció el mismo error pise ok y se cerro la
apk.

**Comment by yolandayancel** [comment]
Te informo que ya me llegaron los Btc del foucet externo

**Comment by nattyco** [comment]
@yolandayancel  proba usar una dispositvo mas liviano como un motorola con android 4.4 o el nexus 5 ya que tenes una pc con poca memoria y comentame despues como te resulta

**Comment by yolandayancel** [comment]
Buenos días Natalia

Estoy descargando la apk para realizar la prueba en un ZTE Kis II Max
android 4.4.2
Sobre los casos 97 y 98 reportados con el emulador Bluestack 6.0 al
realizar la prueba no me aparece los cryto Wallet user dice: no tengo
usuarios disponibles.
Espero por tus indicaciones

**Comment by nattyco** [comment]
@yolandayancel  sobre lo que reportaste en los casos 97 y 98 el tema de que no podes acceder a la app se resolvio? si no te aparecen usuarios eso seria otra cosa para ver, cierro los otros casos entonces?

**Comment by yolandayancel** [comment]
Okey sigo ahora con la revisión del caso 125 y me sigo comunicando lo
observado por el Slack
Saludos


2016-04-06 9:15 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> sobre lo que reportaste
> en los casos 97 y 98 el tema de que no podes acceder a la app se resolvio?
> si no te aparecen usuarios eso seria otra cosa para ver, cierro los otros
> casos entonces?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/125#issuecomment-206379668>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by nattyco** [comment]
@yolandayancel  comentame sobre este caso si se resolvio,

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes

Sobre caso 125 error reportado:Estando en el celular del emulador piso la
apk FERMAT para hacerla correr, comienza a abrir normal pero a los minutos
aparece un error  y al pusar WAIT, entra a la APK. y a los pocos segundos
se queda en negra la pantalla y aparece nuevamente el recuadro con el error
anterior, le piso OK y se sale de la APK.


Prueba 13-04-2016
Reporto que la apk en este emulador no quiso correr sale un error, te subo
la foto.
En espera de tus nuevas indicaciones
Saludos

2016-04-13 8:36 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> comentame sobre este
> caso si se resolvio,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/125#issuecomment-209428775>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes

Sobre caso 134 error reportado:Estando en el Home, al hacer click en el
botón de retroceso, este se ve por debajo (esta
solapado) de la barra propia del celular, como se observa en la captura de
la pantalla.

Prueba 13-04-2016
Reporto que la apk en este celular  el error persiste, te subo la foto.
En espera de tus nuevas indicaciones
Saludo

2016-04-13 8:36 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> comentame sobre este
> caso si se resolvio,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/125#issuecomment-209428775>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes

En el caso 125
Error reportado con:
Sansumg Galaxy S6 5.1

Prueba de hoy 13-04-16
reporto que la apk corrió bien. Puedes cerrar el caso

En espera de nuevas indicaciones
Saludos

El 13 de abril de 2016, 08:59, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Buenos días Natalia Cortes
>
> Sobre caso 125 error reportado:Estando en el celular del emulador piso la
> apk FERMAT para hacerla correr, comienza a abrir normal pero a los minutos
> aparece un error  y al pusar WAIT, entra a la APK. y a los pocos segundos
> se queda en negra la pantalla y aparece nuevamente el recuadro con el error
> anterior, le piso OK y se sale de la APK.
>
>
> Prueba 13-04-2016
> Reporto que la apk en este emulador no quiso correr sale un error, te subo
> la foto.
> En espera de tus nuevas indicaciones
> Saludos
>
> 2016-04-13 8:36 GMT-04:30 Natalia Cortez <notifications@github.com>:
>
>> @yolandayancel <https://github.com/yolandayancel> comentame sobre este
>> caso si se resolvio,
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/125#issuecomment-209428775>
>>
>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> =426-9811123
> Tlf:  281-2 <281-2818262>676587
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com
