### ISSUE TITLE
Bit Coin Wallet_Transactions_ RECIVED

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#126]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El error está en que en las opciones de RECIVED no se contemplan todos los Bitcoins que me han enviado.  Yo tenia 46 btc porque yo le envié 4 a a una compañera. Es decir me quedaban 46 BTC... Augusto me envió 5 y me quedo en 51... Otra compañera me envió 0.01 y me quedo el saldo total en 51.01. El problema recae en que en el RECIVED no me salen reflejados los 5 btc que me envio Augusto ... Y esto no es normal, porque debería salir por lo menos Unknown. Ya que el me tiene agregada a mi pero yo no a el. 

![error 2](https://cloud.githubusercontent.com/assets/17273005/14323787/c6c1e414-fbeb-11e5-8128-384e6658baa0.JPG)

   
-------

#### Dispositivo desde donde se realizo la prueba

Marca: Google Nexus
Modelo: 5
Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  probar este caso con la nueva version de la app

**Comment by MaviDavsa** [comment]
Solucionado!
