### ISSUE TITLE
bitcoinwallet -Experiencia del usuario-add contacts

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#127]
En el add fermat cuando voy a seleccionar el contacto para agregarlo, no se marca dando click sobre el checkbox si no sobre la foto del usuario
#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: google nexus 5
* Version de Android: 4.4.4

**Comment by nattyco** [comment]
@sanro14   modificado en la nueva version

**Comment by sanro14** [comment]
@nattyco cerrar este issue
