### ISSUE TITLE
Bitcoin Wallet-error no aparecen los Cryto Wallet User

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#128]
### Bitcoin Wallet 

-----

##### Home

crypto Wallet User

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *
Al ingresar al Cryto Wallet User no aparecieron los Cryto Wallet User.
probe varias veces y no aparecieron. 
![screenshot_2016-04-06-09-50-49](https://cloud.githubusercontent.com/assets/17283358/14351911/cc300358-fc9b-11e5-84cb-9f647630b95a.png)

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:ZTE
* Modelo:Kiss II Max
* Version de Android: 5.1.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@yolandayancel    probar este caso con la nueva version de la app

**Comment by yolandayancel** [comment]
Recibido.
A la espera de la nueva Apk para hacer las pruebas

**Comment by yolandayancel** [comment]
Buenos dias reporto

Caso 129- experiencia del usuario
Prueba Samsun Galaxy S6 6.0 08-04-2016

1 Inicio la apk bien
2 Estando en add Fermat user, al agregar un contacto el recuadro,  donde
debe picar para agregar al contacto hoy si funciona.

En espera de nuevas indicaciones


El 7 de abril de 2016, 19:21, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Recibido.
> A la espera de la nueva Apk para hacer las pruebas
> El abr 7, 2016 7:20 PM, "Natalia Cortez" <notifications@github.com>
> escribió:
>
>> @yolandayancel <https://github.com/yolandayancel> probar este caso con
>> la nueva version de la app
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/128#issuecomment-207140486>
>>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by nattyco** [comment]
@yolandayancel  comenta sobre este reporte en particular

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes

Caso 128
Te comento que en prueba realizada el viernes 08-04-16 con la nueva apk, el
error  se corrigio

Prueba 08-04-16
Celular ZTE MissII Max
Android 4.4.2
 aparecen  los cryto wallet user


caso 134
Te comento que en prueba realizada el viernes 08-04-16 con la nueva apk, el
error  persiste:

Prueba 08-04-16
Celular ZTE MissII Max
Android 4.4.2
Estando en el Home, al hacer click en el botón de retroceso, este esta
 solapado con la barra propia del celular, como se observo  en la captura
de la pantalla.


2016-04-07 10:17 GMT-04:30 MaViDavsa <notifications@github.com>:

> Assigned #128
> <https://github.com/Fermat-ORG/beta-testing-program/issues/128> to
> @yolandayancel <https://github.com/yolandayancel>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/128#event-618610360>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

En prueba de la nueva apk de fecha 11-04-16

caso 134

Celular ZTE MissII Max
Android 4.4.2
Estando en el Home, al hacer click en el botón de retroceso, este esta
 solapado con la barra propia del celular, sigue el problema
Adjunto foto de hoy.
En espera de instrucciones

El 11 de abril de 2016, 08:45, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Buenos días Natalia Cortes
>
> Caso 128
> Te comento que en prueba realizada el viernes 08-04-16 con la nueva apk,
> el error  se corrigio
>
> Prueba 08-04-16
> Celular ZTE MissII Max
> Android 4.4.2
>  aparecen  los cryto wallet user
>
>
> caso 134
> Te comento que en prueba realizada el viernes 08-04-16 con la nueva apk,
> el error  persiste:
>
> Prueba 08-04-16
> Celular ZTE MissII Max
> Android 4.4.2
> Estando en el Home, al hacer click en el botón de retroceso, este esta
>  solapado con la barra propia del celular, como se observo  en la captura
> de la pantalla.
>
>
> 2016-04-07 10:17 GMT-04:30 MaViDavsa <notifications@github.com>:
>
>> Assigned #128
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/128> to
>> @yolandayancel <https://github.com/yolandayancel>.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/128#event-618610360>
>>
>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> =426-9811123
> Tlf:  281-2 <281-2818262>676587
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com
