### ISSUE TITLE
Graphic Issu-Bitcoin Wallet- Boton Add Fermat User

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#129]
#### Nombre pantalla

Add Fermat User
### Bitcoin Wallet 

-----
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Estando en  Add Fermat user, al agregar un contacto el recuadro donde se debe picar para agregarlo  no funciona hay que hacer clickr cerca  a la foto para que aparezca y poder agregar
![error grafico al anadir un contacto](https://cloud.githubusercontent.com/assets/17283358/14352892/74042448-fca0-11e5-88af-8336bb5e0800.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo:Samsun Galaxy S6
* Version de Android: 6.0

**Comment by nattyco** [comment]
@yolandayancel  modificado en la nueva version

**Comment by augusto-ponce** [comment]
Caso Cerrado, Yolanda probo que estaba solucionado
