### ISSUE TITLE
Bit Coin Wallet_Error  en Fechas del Tab RECIVED

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#130]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Como se puede detallar en la imagen en el área del SEND las fechas son las correspondientes, pero en las fechas del RECIVED salen fechas que ni siquiera se aproximan a la fecha real en la que el BTC fue enviado.
   
![error 2 wallet](https://cloud.githubusercontent.com/assets/17273005/14356580/452e47c0-fcaf-11e5-8543-0fe34aef4312.JPG)
![error 2b wallet](https://cloud.githubusercontent.com/assets/17273005/14356581/45651d40-fcaf-11e5-904f-58270c37f090.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 5
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  este reporte de error sobre las fechas se corrigio en  la nueva version de la app, verificar.

**Comment by MaviDavsa** [comment]
Solucionado

**Comment by MaviDavsa** [comment]
![error 3](https://cloud.githubusercontent.com/assets/17273005/14468419/5a7fac2e-00a9-11e6-80c2-dad0aa53d8b0.JPG)

Acabo de refrescar los recibidos y me salen fechas totalmente distintas! por lo cual debo decir que este issues aún no ha sido arreglado!  @nattyco

**Comment by nattyco** [comment]
@MaviDavsa  verifica este caso nuevamente con la ultima version de la app

**Comment by MaviDavsa** [comment]
@nattyco Por lo que se ve esta solucionado! De todas maneras si me vuelve a pasar te lo hago saber!
