### ISSUE TITLE
Bitcoin Wallet - error cuando estoy en el home y quiero ir a los otros menu

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#131]
Cuando recibo BTC y  estoy en el Home de la app pero quiero volver a cualquier menu de la aplicacion me lanza un error
![image](https://cloud.githubusercontent.com/assets/5313324/14356630/75287bda-fcaf-11e5-8e25-467ed07ee95c.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: genymotion
* Modelo: google nexus 5
* Version de Android: 4.4.4

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by sanro14** [comment]
@nattyco Cerrar,  he probado y no sale el error ..
