### ISSUE TITLE
Bit Coin Wallet_Transactions no tienen la fecha del dia

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#132]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *En esta oportunidad el error radica en que aparece que Yolanda me hizo una transferencia por 50 BTC, entonces o la transferencia la hizo y nunca llego ó esos 50 BTC deberían estar solamente en el de Mati BTC pero también lo atribuyeron a las transiciones de ella 
   
![error 1 wallet](https://cloud.githubusercontent.com/assets/17273005/14356724/d27b2ddc-fcaf-11e5-968c-c80d680acc44.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 5
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  probar este caso con la nueva version de la app

**Comment by MaviDavsa** [comment]
![error 3](https://cloud.githubusercontent.com/assets/17273005/14468248/ace2f15c-00a8-11e6-93a3-f10731549c83.JPG)

Prueba de hoy y el error persiste!

**Comment by nattyco** [comment]
@MaviDavsa  verifica este caso nuevamente con la ultima version de la app

**Comment by MaviDavsa** [comment]
@nattyco Por lo que se ve esta solucionado nena!
