### ISSUE TITLE
Bit Coin Wallet _Cripto Wallet User

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#133]
#### Nombre pantalla
Cripto Wallet users

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Al ingresar a la pantalla en ocasiones salen usuarios y en otras no sale nada como si estuviera vacio. Me ha pasado varias,veces el dia,de hoy, volvi a instalar el app pero el problema sigue.

#### Dispositivo desde donde se realizo la prueba

* Marca:zte
* Modelo:apex2
* Version de Android:4.4.2

**Comment by nattyco** [comment]
@adryx83  Verificar este problema con la nueva version de la app

**Comment by adryx83** [comment]
@nattyco ya este problema esta solucionado en la nueva version
