### ISSUE TITLE
Bitcoin Wallet_Grafic - Botón de retroceso 

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#134]
### Bitcoin Wallet 

-----

##### Home
Home
- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

  Estando en el Home, al hacer click en el botón de retroceso, este se ve por debajo (esta
 solapado) de la 
![boton retroceso solapado_2016-04-07-09-25-09](https://cloud.githubusercontent.com/assets/17283358/14357154/6ba66d2c-fcb1-11e5-8025-92f2028a618c.png)
 barra propia del celular, como se observa en la captura de la pantalla.

------

#### Dispositivo desde donde se realizo la prueba

* Marca:ZTE
* Modelo:Kiss II Max
* Version de Android: 4.4.2

**Comment by yolandayancel** [comment]
Buenas tardes Natalia Cortes

En el caso 134:
Estando en el Home, al hacer click en el botón de retroceso, este se ve por debajo (esta
solapado) 
Celular:
Marca: ZTE
Modelo: Kiss II Max
Versión de Android: 4.4.2

En prueba de hoy 21-04-16 
Apk (20-04-2016), aparece el mismo error gráfico 
![screenshot_2016-04-21-08-15-20](https://cloud.githubusercontent.com/assets/17283358/14710896/19d67b54-07a1-11e6-9863-e8a3a568715f.png)

**Comment by yolandayancel** [comment]
25-04-16
Buenas tardes Natalia Cortes

En el caso 134:
En prueba de hoy 25-04-16 
Apk Dap:
![screenshot_2016-04-25-14-41-14](https://cloud.githubusercontent.com/assets/17283358/14796063/492d58d0-0af5-11e6-824c-b595317710ea.png)
 aparece el mismo error gráfico

**Comment by MaviDavsa** [comment]
@nattyco nena este caso lo cerramos por el cambio de Android?

**Comment by yolandayancel** [comment]
Buenas tardes

Recibido

Saludos cordiales

2016-05-02 10:19 GMT-04:30 MaViDavsa <notifications@github.com>:

> @nattyco <https://github.com/nattyco> nena este caso lo cerramos por el
> cambio de Android?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/134#issuecomment-216255830>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by MaviDavsa** [comment]
Cambios de Android! :) @nattyco  Solucionado!
