### ISSUE TITLE
Bit Coin Wallet - Transactions - Fechas incoherentes

### ISSUE THREAD

**Issue by yahdieli** [Fermat-ORG/beta-testing-program#136]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   * En la pantalla de transacciones recibidas aparece una fecha que es muy diferente a la actual fecha en la que se enviaron los btc, en cambio en las enviadas si aparece la fecha normal.

![image](https://cloud.githubusercontent.com/assets/17284821/14357463/9b58aca0-fcb2-11e5-9591-d648c026c596.png)

![image](https://cloud.githubusercontent.com/assets/17284821/14357606/2aec6fc8-fcb3-11e5-9c0e-1772fa8e6f78.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Bluestacks
* Modelo: 2.0
* Version de Android: 6.0

**Comment by yahdieli** [comment]
@nattyco

**Comment by nattyco** [comment]
@yahdieli  este reporte se corrigio en la nueva version de la app, verificar.

**Comment by yahdieli** [comment]
Este error ya no aparece en la nueva versión de la apk
