### ISSUE TITLE
Fermat Chat_ No salen los mensajes

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#138]
#### Nombre pantalla
Chat Personal

### Chat Fermat

-----

##### Reporte de error: 

   *El error radica en que las dos personas estamos en linea y no envía los mensajes, nos hemos enviado mensajes en común tanto Augusto a mi como yo a el y nada que nos llegan los mensajes a ninguno de los dos. Posteriormente como vez hay un mensaje escrito en la linea de texto que nunca pude enviar, le daba al botón de enviar y no hacia absolutamente nada, todos los demás botones tenían sus funciones correctas menos ese (el de enviar) 
   
![error 1 chat](https://cloud.githubusercontent.com/assets/17273005/14358372/73a05a42-fcb6-11e5-84b8-fe4c01edf447.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus 
* Modelo: 6 
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Me puedes pasar el log dale send report, hay una opcion arriba en los puntitos y me envias el correo franklinmarcano1970@gmail.com

**Comment by MaviDavsa** [comment]
Solucionado!
