### ISSUE TITLE
Error_Bitcoin Wallet_ Balance congelado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#139]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   * Solicite los btc de matibitcoin dos veces y al llegar el balance se congelo y no puedo pasar de book a available, y lo presiono y no hace nada, ni se reflejan los btc enviados, esta congelado y reinicie la app y se mantiene en ese estado, estoy ubicada en la red regtest. 
![screenshot_2016-04-08-09-55-20](https://cloud.githubusercontent.com/assets/17274154/14387093/7f2df6f6-fd71-11e5-88e6-fea9fb282749.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by nattyco** [comment]
@maydiamc  volver a verificar esto con la nueva version

**Comment by maydiamc** [comment]
en la ultima actualizacion se congelo el balance de nuevo y al reiniciar la aplicacion el balance no aparecia y la aplicacion no funcionaba y debi reinstalar para poder utilizarla
![screenshot_2016-04-11-11-32-00](https://cloud.githubusercontent.com/assets/17274154/14481103/6e8ac92e-00f9-11e6-97dc-876b0a70b7ef.png)

![screenshot_2016-04-11-11-22-25](https://cloud.githubusercontent.com/assets/17274154/14481105/7a38e9cc-00f9-11e6-82e0-95f696e14358.png)

Marca: Samsung Galaxy
Modelo: mini s4
Version de Android: 4.4.2

**Comment by nattyco** [comment]
@maydiamc  verificar si esto sigue pasando en la nueva version de la app

**Comment by maydiamc** [comment]
@nattyco solucionado
