### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#140]
#### Nombre pantalla
Contactos

### Bitcoin Wallet 

-----

##### Reporte de error: 
Una vez creados los contactos, cuando le click al contacto con el cual quiero chatear, en este coso Adri Chat o Tomas 2 no me permite ingresar al chat, me sale un mensaje de error 

<img width="378" alt="captura de pantalla 2016-04-08 a las 12 14 29" src="https://cloud.githubusercontent.com/assets/15804433/14388287/cf9ebaf0-fd83-11e5-8c0c-c42c44ab9561.png">

<img width="392" alt="captura de pantalla 2016-04-08 a las 12 15 05" src="https://cloud.githubusercontent.com/assets/15804433/14388291/d2629cfc-fd83-11e5-8755-b951e834f07b.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba
<img width="400" alt="captura de pantalla 2016-04-08 a las 12 17 44" src="https://cloud.githubusercontent.com/assets/15804433/14388335/f8ca6dfc-fd83-11e5-8514-905decb7c505.png">

**Comment by augusto-ponce** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Ok podrias pasarme el log, en la app hay una opcion send report, colocas mi correo franklinmarcano1970@gmail.com, le das send, @augusto-ponce explicale como hacer, por favor...

**Comment by augusto-ponce** [comment]
ya fue enviado el report !!

**Comment by augusto-ponce** [comment]
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: WsCommunicationVPNClientManagerAgent - instance.vpnClientActiveCache.get(applicantNetworkServiceType).size() = 3
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: ---------------------CLAVE DISPONIBLES:[CHAT]------------------------------------
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: ---------------------CLAVES BUSCADA:046073208B0FE9E06BA6B8F6558CBE0B4B132AE0FC9B398E072D4D94171E2227A50D3E23417DF72498C6C3B1331859CEBA33A4F9E6788F93F5308063D2D3B6B9E1------------------------------------
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - started 
04-08 11:35:08.416 2157-2423/org.fermat I/System.out: WsCommunicationVPNClient - sendMessage
04-08 11:35:08.448 2157-2423/org.fermat I/System.out: SALIENDO DEL HANDLE NEW SENT MESSAGE NOTIFICATION
04-08 11:35:08.937 2157-2420/org.fermat I/System.out:  --------------------------------------------------------------------- 
04-08 11:35:08.937 2157-2420/org.fermat I/System.out:  WsCommunicationVPNClient - Starting method onClose
04-08 11:35:08.937 2157-2420/org.fermat I/System.out: Socket 260e1df7-fdba-4bdf-bbeb-4ee4ca17becf is disconnect! code = NORMAL_CLOSURE[1000] reason = The remote participant close the connection. Details: The cloud client close the connection, intentionally.
04-08 11:35:08.937 2157-2420/org.fermat I/System.out: WsCommunicationVPNClientManagerAgent - riseVpnConnectionCloseNotificationEvent
04-08 11:35:08.937 2157-2420/org.fermat I/System.out: WsCommunicationVPNClientManagerAgent - Raised Event = P2pEventType.VPN_CONNECTION_CLOSE
04-08 11:35:08.937 2157-2293/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - stopped 
04-08 11:35:08.937 2157-2424/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...  
04-08 11:35:08.938 2157-2423/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...

**Comment by josejcb** [comment]
@franklinmarcano1970 se le cerró la conexión

**Comment by franklinmarcano1970** [comment]
Si correcto por algun error en P2P, es lo que voy a conversar con Roberto!!!!

**Comment by augusto-ponce** [comment]
el error no me aparece mas en la nueva versión, probe con 2 telefono y aparentemente esta solucionado
