### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#141]
#### Nombre pantalla
CONTACTOS

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

Al estar en la pantalla de Add Conection y darle clik a un contacto para agregarlo como contacto me sale una pantalla que me pregunta si quiero agregar ese contacto a mi Contact List. Cuando le doy Yes veo que el contacto se agrega e inmediatamente me vuelve el sistema a hacer la misma pregunta sobre el mismo contacto, cuando le doy Yes nuevamente me sale que ese contacto ya existe. Por ende esto es un error, no debería hacerme de vuelta la pregunta 2 veces .

<img width="397" alt="captura de pantalla 2016-04-08 a las 12 13 55" src="https://cloud.githubusercontent.com/assets/15804433/14388503/d7a06874-fd84-11e5-96f3-d991fc78aa82.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba
<img width="400" alt="captura de pantalla 2016-04-08 a las 12 17 44" src="https://cloud.githubusercontent.com/assets/15804433/14388523/e9c5a6c2-fd84-11e5-926d-13c4fd646b33.png">

**Comment by augusto-ponce** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Estimado, Pienso que vuelve a preguntar porque le haces de nuevo click al contacto, el se queda en esa pantalla para seguir agregando otros contactos.

**Comment by augusto-ponce** [comment]
Luego de chequear de nuevo en el mismo dispositivo me doy cuenta que eso sucede cuando yo le doy doble click
