### ISSUE TITLE
Bitcoin Wallet_Communitty - Crypto Wallets Conectados

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#142]
### Template issue error report

Bit coin Wallet 
#### Nombre pantalla

Cripto Wallet Users

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Algunos contactos no aparecen, y algunos de los que aparecen no les llegan las solicitudes de contacto.

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE 
* Modelo: Apex 2
* Version de Android: 4.4.2

**Comment by MaviDavsa** [comment]
@nattyco Solucionado, ya escapa de su manos lo LENTO que pueda estar la red de Fermat en estos momentos!
