### ISSUE TITLE
Bitcoin Wallet- Error Info mostrada enTab Sent del Home

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#144]
### Bitcoin Wallet 

-----

##### Home
Home
- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Estando en el Home cliqueo en sent y me aparece Adry 1A como que le envie 3BTc y fue ella que me envio los 3BTC
![error en recived](https://cloud.githubusercontent.com/assets/17283358/14436378/2ebe5f22-ffe6-11e5-90c2-1f4c9ce3aad5.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo: Samsung Galaxy S6
* Version de Android: 6.0

**Comment by nattyco** [comment]
@yolandayancel  confirmaste con Adriana que ella no te habia enviado los btc?

**Comment by yolandayancel** [comment]
*Buenas tardes Natalia Cortes*

*Efectivamente como me indicaste **Adry* *envio**:*
 2 BTC

*[ <https://fermat-org.slack.com/archives/beta-testing/p1460391318000166>*
11:45 <https://fermat-org.slack.com/archives/beta-testing/p1460391318000166>*]
<https://fermat-org.slack.com/archives/beta-testing/p1460391318000166>*
y un payment por 3 btc

Puedes cerrar este caso
En espera de tu respuesta
Saludos

@yolandayancel <https://github.com/yolandayancel> confirmaste con Adriana
que ella no te habia enviado los btc?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Fermat-ORG/beta-testing-program/issues/144#issuecomment-208469970>
