### ISSUE TITLE
Chat - Mensajes Aleatorios 

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#145]
### Chat Fermat

-----

##### Reporte de error: 

   *El error consiste en que como se ve en la imagen los mensajes están aleatorios... El orden correcto debería ser Mavi: Holii, Si queremos hacer un grupo como lo hacemos? y posteriormente las respuestas de Augusto... Pero como se ve en la imagen las respuestas están antes y mis preguntas después.
   
![error chat 1](https://cloud.githubusercontent.com/assets/17273005/14465644/7abd20a4-009d-11e6-9a67-ad3b7c2ecddd.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus 
* Modelo: 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: WsCommunicationVPNClientManagerAgent - instance.vpnClientActiveCache.get(applicantNetworkServiceType).size() = 3
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: ---------------------CLAVE DISPONIBLES:[CHAT]------------------------------------
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: ---------------------CLAVES BUSCADA:046073208B0FE9E06BA6B8F6558CBE0B4B132AE0FC9B398E072D4D94171E2227A50D3E23417DF72498C6C3B1331859CEBA33A4F9E6788F93F5308063D2D3B6B9E1------------------------------------
04-08 11:35:08.413 2157-2294/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - started 
04-08 11:35:08.416 2157-2423/org.fermat I/System.out: WsCommunicationVPNClient - sendMessage
04-08 11:35:08.448 2157-2423/org.fermat I/System.out: SALIENDO DEL HANDLE NEW SENT MESSAGE NOTIFICATION
04-08 11:35:08.937 2157-2420/org.fermat I/System.out:  --------------------------------------------------------------------- 
04-08 11:35:08.937 2157-2420/org.fermat I/System.out:  WsCommunicationVPNClient - Starting method onClose
04-08 11:35:08.937 2157-2420/org.fermat I/System.out: Socket 260e1df7-fdba-4bdf-bbeb-4ee4ca17becf is disconnect! code = NORMAL_CLOSURE[1000] reason = The remote participant close the connection. Details: The cloud client close the connection, intentionally.
04-08 11:35:08.937 2157-2420/org.fermat I/System.out: WsCommunicationVPNClientManagerAgent - riseVpnConnectionCloseNotificationEvent
04-08 11:35:08.937 2157-2420/org.fermat I/System.out: WsCommunicationVPNClientManagerAgent - Raised Event = P2pEventType.VPN_CONNECTION_CLOSE
04-08 11:35:08.937 2157-2293/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - stopped 
04-08 11:35:08.937 2157-2424/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...  
04-08 11:35:08.938 2157-2423/org.fermat I/System.out: CommunicationNetworkServiceRemoteAgent - Thread Interrupted stopped ...

**Comment by augusto-ponce** [comment]
@franklinmarcano1970

**Comment by augusto-ponce** [comment]
en mi telefono no hubo ese problema, va la foto de la misma conversación 

<img width="488" alt="captura de pantalla 2016-04-12 a las 13 01 24" src="https://cloud.githubusercontent.com/assets/15804433/14466790/bd57b184-00ae-11e6-86cc-ce2493c1357f.png">


Caracteristica de mi tel

<img width="365" alt="captura de pantalla 2016-04-12 a las 13 02 52" src="https://cloud.githubusercontent.com/assets/15804433/14466825/eb244a14-00ae-11e6-875d-564f6b895af4.png">

**Comment by MaviDavsa** [comment]
Ahh bueno! No se si sea problema de conexión o emulador! Jajaja ustedes sabrán! :)

**Comment by franklinmarcano1970** [comment]
El problema paso en el dispositivo receptor cierto?

**Comment by franklinmarcano1970** [comment]
Ok manana probamos de nuevo con ese mismo emulador para ver si podemos duplicar ese detalle!!!!

**Comment by MaviDavsa** [comment]
Perfecto @franklinmarcano1970 ... Problema Resuelto en esta Apk!
