### ISSUE TITLE
Chat- Experiencia del usuario

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#147]
#### Nombre pantalla
Chat

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

 Seria muy bueno incorporar al chat lo siguiente: Cuando uno esta escribiendo la otra persona seria bueno que vea de alguna manera que la otra persona esta escribiendo para mandarle un mensaje, ya sea con un cartelito diciendo (escribiendo) como en el caso de Whatsaap o bien como unos puntitos moviendose como es el caso del chat de Facebook. Eso mejoraría muchísimo la experiencia del chat ya que en el caso de el chat de Fermat uno no sabe si la otra persona esta respondiendo y muchas veces los dos están escribiendo lo mismos al mismo tiempo y no esta bueno eso, se pierde uno en la conversación. 

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:
* Modelo:
* Version de Android:

**Comment by augusto-ponce** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Perfecto amigo @augusto-ponce ya esta previsto en la version que estamos por empezar!!!!!

**Comment by augusto-ponce** [comment]
excelente va a mejorar mucho la experiencia del Chat !!

**Comment by MaviDavsa** [comment]
@augusto-ponce Listo! Esto esta solucionado! :)
