### ISSUE TITLE
Chat - Notificaciones y sonidos

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#148]
#### Nombre pantalla

Chat 
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

  Seria muy bueno que la aplicación te avise cuando otra persona te ha enviado un mensaje mientras estas chateando con otra. Para poder ver si alguien te ha enviado un mje hay que volver al home de chat en donde ahí recién podemos ver si alguien nos ha enviado un mje. Eso a mi criterio hace que la experiencia de chatear no se fluida y pueda responder con prontitud a quien me esta escribiendo. También es incomodo estar volviendo todo el tiempo al home de chat para ver si alguien me ha escrito. Podría usarse notificaciones que aparezcan al alguna parte de la pantalla o bien sonidos, como los tiene whatsaap y otras aplicaciones de chat.
------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:
* Modelo:
* Version de Android:

**Comment by augusto-ponce** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Perfecto lo colocaremos como pendiente para proximas versiones!!!!!, lo de las notificaciones arriba de la app ya esta previsto en la version 2.

**Comment by augusto-ponce** [comment]
no se olviden de los sonidos también que podría ser una alternativa interesante !

**Comment by MaviDavsa** [comment]
Unido al #406
