### ISSUE TITLE
Bit Coin Wallet_ Send to contact

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#150]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El error radica en cuando voy a hacerle un Send a un contacto, en este caso Augusto... Me da el siguiente error y no me deja hacerle el Send

![error 2](https://cloud.githubusercontent.com/assets/17273005/14467534/91c491f8-00a5-11e6-88ec-924c0d2d5f79.JPG)

Sin embargo cuando me voy al Contact Detail... Tengo el Adrees completo

![error 2b](https://cloud.githubusercontent.com/assets/17273005/14467649/19ea518a-00a6-11e6-80fe-295daf584ea8.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 5 
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  este error es accediendo directamente al boton de send, o la opcion send del detalle del contacto?, si es desde el boton send buscaste el nombre del contacto o ya lo tenia seleccionado?

**Comment by MaviDavsa** [comment]
Desde el Send! Y probé de ambas formas dejándolo cuando ya me lo tenia seleccionado y cambiando las selecciones a ver si hacia algo y nada! @nattyco

**Comment by MaviDavsa** [comment]
Solucionado! :)
