### ISSUE TITLE
bitcoin Wallet- Bitcoins recibidos y no llegan las notificaciones

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#151]
#### Nombre pantalla

Home !
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

Rebibi Btc de dos contactos que tenia 
Caso 1: Al recibir Btc de mi contacto Maria después de haberle hecho un paytment request me llego una notificacion avisándome que Maria había aceptado y me había mandado los btc. Todo ok
Caso 2: Mi contacto Maydi me envío directamente los Btc y los mismos me entraron en mi book balance pero jamas he recibido notificación alguna.
------

------

#### Dispositivo desde donde se realizo la prueba
<img width="410" alt="captura de pantalla 2016-04-12 a las 13 29 30" src="https://cloud.githubusercontent.com/assets/15804433/14467637/a54646ba-00b2-11e6-8166-39ebf7cebbe3.png">

**Comment by augusto-ponce** [comment]
@nattyco

**Comment by nattyco** [comment]
@augusto-ponce  verificar este reporte con la nueva version de la app

**Comment by MaviDavsa** [comment]
@nattyco Solucionado!
