### ISSUE TITLE
bitcoin Wallet- No se pasan del Book al disponible

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#152]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

 Después de esperar casi 1 hora y media los Btc recibidos estan el Book Balance y nunca se pasan al disponible !  Tampoco nunca se reflejaron las 3 transacciones recibidas en el RECIVED

<img width="401" alt="captura de pantalla 2016-04-12 a las 13 41 31" src="https://cloud.githubusercontent.com/assets/15804433/14468005/4c8b6fb2-00b4-11e6-881a-5974fccb01fb.png">

<img width="398" alt="captura de pantalla 2016-04-12 a las 13 41 22" src="https://cloud.githubusercontent.com/assets/15804433/14468016/54612f1a-00b4-11e6-998d-bc12a0ab99e0.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:
* Modelo:
* Version de Android:

**Comment by augusto-ponce** [comment]
@nattyco

**Comment by nattyco** [comment]
@augusto-ponce  los btc no se confirmaron nunca o tardan en confirmarse, este es un tema de la red de bitcoin, tenes que consultarle a Rodrigo porque como dijo se suele saturar el servidor.

**Comment by MaviDavsa** [comment]
@nattyco Esto se ha solucionado
