### ISSUE TITLE
Bit Coin Wallet_ Send Request to contact

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#153]
#### Nombre pantalla
Send Request to contact

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Esto no se si es un error! Pero cada vez que quiero enviar un Request, me sale el nombre predeterminado de Augusto, me imagino que es por ser el primero en mi lista de contactos. Sin embargo esto deberia quedar en blanco para que la persona seleccione a quien quiere enviar y no tener que quitar y luego poner a la persona a la que le quiere enviar el request! 

![error 1](https://cloud.githubusercontent.com/assets/17273005/14473063/2a9546c4-00c0-11e6-9230-cae3a8ba33d4.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 5
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa esto se penso asi muestra el ultimo contacto al que le enviaste o el que tengas por defecto, puede ser algo a reveer en proximas versiones

**Comment by MaviDavsa** [comment]
@nattyco Bella... esto sigue en las versiones...

**Comment by IsbetVR** [comment]
En la versión 20.4 de CBP persiste este error, deja predeterminado en "send to contact"  (Pantalla 1) y "send request to contact" (Pantalla 2) al primer contacto que le hice envío.

#### Pantalla 1

![screenshot_8](https://cloud.githubusercontent.com/assets/19142276/16769978/d08e2970-4818-11e6-8087-dea4728c6e74.jpg)

#### Pantalla 2

![screenshot_9](https://cloud.githubusercontent.com/assets/19142276/16769980/d3f3031a-4818-11e6-8a58-722002558ddd.jpg)

-------

#### Dispositivo de prueba

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16770028/0605d3f0-4819-11e6-97bb-eb60d6012a0c.jpg)

**Comment by GeronimoVierma** [comment]
En la versión 20.7 de CBP no me sale el nombre predeterminado del primer contacto de mi lista ni tampoco de la ultima persona que le envié btc, el error fue corregido:

![tratratra](https://cloud.githubusercontent.com/assets/19883115/16891534/1ffa7e48-4ac9-11e6-9543-84507caa13b4.png)

 Emulador
![chi](https://cloud.githubusercontent.com/assets/19883115/16891536/318787f0-4ac9-11e6-8a92-8a4142c35c1d.png)

**Comment by IsbetVR** [comment]
En la versión 21.9 CBP está volviendo a salir un contacto predeterminado en el Send to Contact

![screenshot_9](https://cloud.githubusercontent.com/assets/19142276/17603857/05fe3d54-5fe1-11e6-9b56-cc4dd5c5df79.jpg)

#### Dispositivo de prueba
- [x] Emiulador

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/17603883/22333a4c-5fe1-11e6-8f4c-fa5c0c700a2a.jpg)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 153 CBP V 21.9 (BITCOINWALLET)
Sony Xperia S 4.1.1 16 api320dpi
ocurre lo reportado.
1 - Un contacto predeterminado al ingresar en el Sent to contacto:
![1](https://cloud.githubusercontent.com/assets/17283358/17603923/50205c64-5fe1-11e6-83e7-1f713bac9288.png)

2- Borro el contacto y salgo de la pantalla
![screenshot_13](https://cloud.githubusercontent.com/assets/17283358/17603960/7e39589e-5fe1-11e6-9550-d6f7d26ba22b.png)

3- Ingreso nuevamente a la pantalla y esta el contacto borrado..
![screenshot_14](https://cloud.githubusercontent.com/assets/17283358/17604028/daa04278-5fe1-11e6-81bd-830dceeeaaa5.png)

Emulador:
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17603990/ab3068f6-5fe1-11e6-8885-be01b2334dd9.png)

**Comment by IsbetVR** [comment]
@nattyco porfa chequea este caso, está sucediendo otra vez

**Comment by danielaporras** [comment]
Este error sigue repitiendose en la version 22.0

![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/17674617/5164bd98-62f4-11e6-9ab0-62c76e68d7e8.png)


![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17674623/5617dd66-62f4-11e6-8cb7-48739a1db0f9.png)

**Comment by danielaporras** [comment]
El error persiste en la version 22.1 de CBP
![screenshot_14](https://cloud.githubusercontent.com/assets/19656830/17710994/d5c33c4e-63bd-11e6-8812-4c7848ca1d6a.png)


![screenshot_12](https://cloud.githubusercontent.com/assets/19656830/17711000/dda5d2be-63bd-11e6-8adc-00154e1f8c13.png)

**Comment by yolandayancel** [comment]
Prueba 16-08-16
Caso 153 CBP 22.1
Sony xperia S 4.1.1
Ya no ocurre que el contacto queda predeterminado, entro y no hay nadie..
![screenshot_9](https://cloud.githubusercontent.com/assets/17283358/17711392/75e68612-63bf-11e6-8189-944fa6ffb3e5.png)

![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17711386/6d1ac340-63bf-11e6-928b-2445fe055305.png)

**Comment by nattyco** [comment]
@MaviDavsa  se quito la opcion que dejaba un contacto por default al hacer el envio, verificar en la version 22.2 de la apk

**Comment by yolandayancel** [comment]
Prueba 18-08-16
Caso 153 CBP 22.2 (Bitcoin Wallet)
Sony Xperia S 4.1.1 api 16 320dpi
No ocurre lo reportado(ingreso y no hay un contacto predeterminado)
![153](https://cloud.githubusercontent.com/assets/17283358/17776771/d913d740-652b-11e6-9574-2757d5e14954.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17776776/e03a74e8-652b-11e6-9e28-fe8948edc654.png)

**Comment by maydiamc** [comment]
en la version 22.2 este error se soluciono en el formulario  de send to contact, el nombre al ingresar se encuentra en blanco, pero no se pudo probar con send request to contac ya que el formulario no esta disponible

![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/17777864/0e6b79f8-6530-11e6-9b26-67be66c9b329.png)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17777880/16de0c04-6530-11e6-896c-95b761e008e5.png)

**Comment by Gabymorillo** [comment]
En la versión 22.2 de la CCP, desde el telefono fisico no sucede este error. 

![screenshot_2016-08-18-10-50-12_720](https://cloud.githubusercontent.com/assets/17262077/17778370/c9333a40-6531-11e6-968e-d60ba2fa86f7.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17778311/9feda990-6531-11e6-94b1-ce5f02d2cec0.png)

**Comment by arosiopr** [comment]
@AdryCanonico  solucionado se puede cerrar
