### ISSUE TITLE
Graphic_Bitcoin Wallet_ error de fechas de btc recibidos

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#154]
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   * Cuando se reciben btc de los contactos no aparece la fecha ni la hora actualizada en las transacciones sino que aparece la fecha january 17, 1970, 17:41hs

nota: en la imagen adjunta aparece la hora correcta y en la transaccion regtest_bitcoins esta la fecha correcta

![screenshot_2016-04-12-11-47-49](https://cloud.githubusercontent.com/assets/17274154/14481224/c0f93906-00fa-11e6-9f9c-00100a7d39c4.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsun Galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc este error se corrigio en la nueva version de la app, verificar.

**Comment by maydiamc** [comment]
Corregido en la ultima actualizacion.! @nattyco
