### ISSUE TITLE
Chat - Botón para enviar mensajes no aparece al estar visible el teclado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#155]
### fermat chat 

-----

##### Ventana de chat

- [x] Pantalla principal de chat

##### Reporte de error: 

   *En la pantalla principal de chatal escribir en la linea de escritura se desaparece el boton de enviar y se hace complicado enviar el texto.

![screenshot_2016-04-08-11-20-32](https://cloud.githubusercontent.com/assets/17274154/14481338/cc22bd6a-00fb-11e6-8591-6d245c9f4bcd.png)

-------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Ok podemos conversar mañana porque parecer que es comportamiento que pasa en esa versión de Android.

**Comment by MaviDavsa** [comment]
Versión de Android vieja

**Comment by AdryCanonico** [comment]
@maydiamc  @MaviDavsa  En la version 19.2 de CBP Sucede este error, después de escribir, el teclado sube y borra el botón para enviar.No aparece y no logro poder enviar el mensaje   Por favor reabrir el caso.

![screenshot_2016-07-04-14-48-44](https://cloud.githubusercontent.com/assets/18584168/16568955/86d9c6d8-41fe-11e6-9e06-6d4b60d48459.png)


http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16568977/d19995ae-41fe-11e6-93ff-fb1921c6e0eb.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 en la version 19.5 ya aparece el botón.

**Comment by AdryCanonico** [comment]
@franklinmarcano1970  en la version 19.5 persiste. Ahora se borra el boton;pero si le das donde debería estar el botón, envía el mensaje. 

![screenshot_2016-07-05-17-46-29](https://cloud.githubusercontent.com/assets/18584168/16603310/fe8fc264-42e8-11e6-86ee-47a9123cd7e1.png)

pero algunas veces al actualizar aparece el  botón.


![screenshot_2016-07-05-17-46-35](https://cloud.githubusercontent.com/assets/18584168/16603366/71ea5d46-42e9-11e6-83c8-cf8dbfeab53e.png)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de Chat, no se repite este error en mi emulador (Turno Tarde)

![boto](https://cloud.githubusercontent.com/assets/19353722/16697322/25be544c-4517-11e6-8db3-3b3393900d1d.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16697325/2ade81f4-4517-11e6-8e88-1714576fa6e9.png)

**Comment by Gabymorillo** [comment]
En la versión 20.1 no se ha probado este error por problemas en las conexiones.

**Comment by marielis-urbina** [comment]
En la versión 20.3 de Chat este error en mi emulador ya no sucede

![no s](https://cloud.githubusercontent.com/assets/19353722/16746921/af745ad6-478a-11e6-8fc3-7ea5b65afea0.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16746928/b571b0b4-478a-11e6-96da-fc2c3cc1cca4.png)

**Comment by sanro14** [comment]
Solucionado.

**Comment by danielaporras** [comment]
*En la version 1.9.1 de chat, el boton para enviar los mensajes no se muestra al tener visible el teclado.


1.Entro a una ventana de chat.
2.Pongo visible el teclado, el boton de para enviar no aparece. Capture 1
3.Le doy atras y puedo enviar el mensaje. Capture 2

- Capture 1
![screenshot_2016-09-13-16-26-53](https://cloud.githubusercontent.com/assets/19656830/18491393/40c58c1e-79d4-11e6-8303-dbde6fe56eaf.png)

- Capture 2
![screenshot_2016-09-13-16-26-56](https://cloud.githubusercontent.com/assets/19656830/18491400/469599b8-79d4-11e6-9590-0df43a52b2a9.png)

Huawei Ascend Y221
http://www.gsmarena.com/huawei_ascend_y221-6908.php
- [x] Teléfono Físico
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18491481/99ca4354-79d4-11e6-99d9-c0887ebfbf03.png)

Por favor reabrir el caso.
@MaviDavsa

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by danielaporras** [comment]
Lo reportado en el ultimo comentario de este error fue solucionado en la version 2.0 Chat.

![screenshot_2016-09-14-14-44-54](https://cloud.githubusercontent.com/assets/19656830/18525341/13746580-7a8a-11e6-8a49-ec24aeb0f454.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18525342/15f0d406-7a8a-11e6-9570-568d3628b7cf.png)
  Por favor cerrar el caso @MaviDavsa
