### ISSUE TITLE
Bit Coin Wallet_No llegan los BTC de Regtest ni BTC de otros contactos

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#157]
### Template issue error report

Bitcoin Wallet 
#### Nombre pantalla

Balance 

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *No llegan los btc de Regtest, ni llegan los payments request, ni BTC enviados por otros contactos, Solo me han llegado notificaciones vacías no se reflejan ni en el balance ni en los payments.

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: apex 2
* Version de Android: 4.4.2

**Comment by nattyco** [comment]
@adryx83  verificar este reporte con la nueva version de la apk y cometar los resultados

**Comment by sanro14** [comment]
@MaviDavsa cerrar
