### ISSUE TITLE
Bitcoin Wallet - Error al agregar contacto 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#162]
##### Reporte de error: 

  Entro a bitcoin wallet, me dirijo a contactos y luego a fermat user, cuando salgo de alli e intento volver a entrar a contactos se queda en negro.  

   
   
- [x] Pantalla del detalle del contacto

##### Reporte de error: 
![image](https://cloud.githubusercontent.com/assets/18452495/14623496/99c027f4-059c-11e6-9cde-677ba561c25b.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/14623645/ef20b73a-059d-11e6-8cb8-0a03f20cb0ec.png)

**Comment by andreagmarcano** [comment]
@nattyco

**Comment by nattyco** [comment]
@andreagmarcano  Te sugiero agregar al genymotion un celular con android 5 o 5.1 pero que no sea el custom porque no funciona muy bien, podes probar un Samsung o un Nexus.

**Comment by MaviDavsa** [comment]
@andreagmarcano Nena y como el emulador que estabas utilizando no es el adecuado vamos a cerrar este caso! :) De todas maneras estamos hablando por el Slack para explicarte mejor!
