### ISSUE TITLE
Bitcoin Wallet_ pantalla add contact help se sigue mostrando

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#163]
#### Reporte de error
 *Al ingresar a CONTACTOS tenemos la ventana de ADD CONTACT HELP, la cual nos da la opción: Don´t show this again, la activo y sin embargo sigue apareciendo cada vez que entro a contactos. 

![img-20160418-wa0016](https://cloud.githubusercontent.com/assets/18471856/14623832/47ff3a6a-059f-11e6-8df8-db6c362329c8.jpg)

#### Dispositivo desde donde se realizo la prueba

* Marca: Blu
* Modelo: Advance 4.0
* Version de Android: 4.2.2

**Comment by nattyco** [comment]
@fabianazabala  cuando te aparecio la primera vez elegiste alguna de las dos opciones que te dio? comentame los pasos que seguiste y que despues te la volvio a mostrar

**Comment by fabianazabala** [comment]
No tuve opción a elegir una de las dos alternativas, lo único que podía hacer era activarlo, desactivarlo o salirme al home. Lo que hacía que al volver a entrar a contactos, siguiera apareciendo la ayuda.

**Comment by nattyco** [comment]
@fabianazabala   verificar este error con la nueva version de la aplicacion.

**Comment by MaviDavsa** [comment]
@nattyco Solucionado...
