### ISSUE TITLE
Community_ No llegan las notificaciones

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#164]
##### Reporte de error: 

 No tengo notificaciones de contactos, a pesar de que me agregan, las notificaciones no llegan, haciendo imposible contactarme con las personas. 

![screenshot_2016-04-18-19-11-29](https://cloud.githubusercontent.com/assets/17262077/14623745/b1c923e4-059e-11e6-8a8c-b6932f9e1c61.png)

![screenshot_2016-04-15-16-20-17 1](https://cloud.githubusercontent.com/assets/17262077/14624035/af4f631a-05a0-11e6-8ac0-7d51c66cbe6d.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung 
* Modelo: GT-I9082L
* Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@Gabymorillo  Necesito mas especificaciones sobre este error, las conexiones entre personas se hacen en la sub app Community cuando te llega una notificacion de que alguien te agrega como conexion tenes que ir a la app community y aceptar ahi la conexion, despues de que tengas esa relacion podes desde la wallet agregar a ese fermat user como contact.

**Comment by Gabymorillo** [comment]
Buenos días! Cuando alguien me agregaba no me llegaba la solicitud y por
ende no podía aceptar. Pero, me acaba de llegar tu solicitud sin problemas.

**Comment by nattyco** [comment]
ok, podes hacer unas pruebas mas y comentar para cerrar este caso, las notificaciones las ves en el community, en la opcion notificaciones, lo que decis vos es que no te llegaban los mensajes en la barra superior del celular?

**Comment by Gabymorillo** [comment]
Exactamente, alguien me agregaba y no me llegaba la notificación. Ayer
agregué a alguien y todo bien.
