### ISSUE TITLE
Bitcoin Wallet_SubApp Community- Error al enviar solicitud de conexion

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#165]
##### Reporte de error: 

 Cuando hago para conectarme con un usuario me sale error. 

![image](https://cloud.githubusercontent.com/assets/18452495/14624502/12ec1f5e-05a5-11e6-8bad-36743d22653f.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/14624527/4c198bfe-05a5-11e6-822c-4d11ade96b00.png)

**Comment by andreagmarcano** [comment]
@nattyco

**Comment by nattyco** [comment]
@andreagmarcano  verificar este error con la nueva version de la aplicacion.

**Comment by andreagmarcano** [comment]
solucionado

**Comment by andreagmarcano** [comment]
ok natalia

2016-04-27 12:10 GMT-04:30 MaViDavsa <notifications@github.com>:
