### ISSUE TITLE
Bitcoin Wallet _ Error al intentar salir de la lista de contactos de Fermat User.

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#166]
##### Contactos

- [x] Pantalla de contactos (Lista)
- [ ] Pop up de ayuda
- [ ] Pop up de agregar un contacto externo

##### Reporte de error: 

 Al entrar a la opción de "Contacts", seguido de seleccionar el botón de Fermat User, aparece la lista de contactos pero al intentar salir de ella presionando el botón de atrás del teléfono... la pantalla queda completamente en negro por unos segundos para luego indicar que la app de Fermat se detuvo.

![screenshot_2016-04-18-19-28-47](https://cloud.githubusercontent.com/assets/17261437/14624666/786e0db4-05a6-11e6-9cc9-05c2e339028a.png)

![screenshot_2016-04-18-19-30-50](https://cloud.githubusercontent.com/assets/17261437/14624669/8490b678-05a6-11e6-97e6-f7242d8cc909.png)

![screenshot_2016-04-18-19-28-53](https://cloud.githubusercontent.com/assets/17261437/14624676/92df5d6a-05a6-11e6-8170-ff4f4021a4b8.png)

![screenshot_2016-04-18-19-29-35](https://cloud.githubusercontent.com/assets/17261437/14624681/a6328478-05a6-11e6-96e2-1336dd4c979b.png)

 

#### Dispositivo desde donde se realizó la prueba
![screenshot_2016-04-18-20-11-55](https://cloud.githubusercontent.com/assets/17261437/14624563/a54042b8-05a5-11e6-8036-f75e60750a94.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by sanro14** [comment]
@MaviDavsa cerrar..
