### ISSUE TITLE
Bitcoin Wallet-error al  salir de la pantalla de Request

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#168]
#### Nombre pantalla

Request

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Estando en la pantalla de Request y pisar el botón de retroceso para ir al Home, salio un error, no me permitió entrar. Tuve que cerrar la Bitcoin Wallet.
![error al salir de request](https://cloud.githubusercontent.com/assets/17283358/14646321/e3d0cc82-0622-11e6-8a9b-b14c6d5f3709.png)

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Samsung Galaxy S6
* Version de Android: 5.1

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes

El error 168:
Estando en la pantalla de Request y pisar el botón de retroceso para ir al Home, salio un error, no me permitió entrar. Tuve que cerrar la Bitcoin Wallet.
Marca:Emulador Genymotion
Modelo:Sansumg Galaxy S 6 ApI 22-1440x2560
Version de Android: 5.1

En prueba de hoy 21-04-16 
Apk-21-04-16:
Estando en la pantalla de Request y pisar el botón de retroceso para ir al Home, ya no aparece el error.
Adjunto una foto, puedes cerrar el caso.
En espera de tus indicaciones
![error 168 resuelto](https://cloud.githubusercontent.com/assets/17283358/14711301/a3a4010c-07a2-11e6-8b36-555f1ea7ae7e.png)
