### ISSUE TITLE
Sub App Community_ Cripto Wallet Users Notifications

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#169]
#### Nombre pantalla
Cripto Wallet Users - Notifications

### Bitcoin Wallet 

-----

##### Reporte de error: 

   * En esta oportunidad el error está en que me sale una notificación de que un nuevo contacto me agrego pero cuando voy a la Cripto Wallet no hay absolutamente nada, ni en las notificaciones, ni en las conexiones, ni en nada! 

![error 1](https://cloud.githubusercontent.com/assets/17273005/14675967/45a153ac-06d5-11e6-870e-7efa65ac7c40.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion 
* Modelo: Google Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  esto puede pasar cuando vos enviaste un request y el otro usuario te envio tambien entonces te llega la notificacion pero como la relacion se arma automaticamente no tenes notificaciones para aprobar, voy a ver de cambiar el mensaje.

**Comment by MaviDavsa** [comment]
@nattyco Pero si ese fuera el caso ya me aparecería automaticamente para agregarlo como contacto y eso no me sale tampoco!

**Comment by nattyco** [comment]
@MaviDavsa  verifica nuevamente esto con la nueva version de la apk a descarga de http://fermat.org/download/fermat-android-core-debug.apk

**Comment by MaviDavsa** [comment]
Solucinado @nattyco
