### ISSUE TITLE
SubApp Community- Error al enviar solicitud de conexion

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#170]
##### Reporte de error: 

Al intentar conectarme con un contacto me refleja error. 

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/14695127/e5a3a91e-0738-11e6-8cb2-7572f21dece2.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:
* Modelo:
* Version de Android:
![image](https://cloud.githubusercontent.com/assets/18452495/14695163/3ded7050-0739-11e6-8131-44f83b068f3e.png)

**Comment by nattyco** [comment]
Ya reportado en el caso #165
