### ISSUE TITLE
Bit Coin Wallet_ se cerró la aplicación

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#171]
Template issue error report

Nombre pantalla

Contacts

Bitcoin Wallet

Reporte de error:

**##Después de recibir btcs correctamente por fauce proseguí a agregar contactos, cuando estaba en eso la aplicación se cerró por completo. Intenté abrirla varias veces y no respondía. Forcé la detención y aún así la aplicación no respondió. Me tocó actualizarla... lo único que pude capturar fue esto:
**

![img-20160420-wa0025](https://cloud.githubusercontent.com/assets/18471856/14695706/876f37fe-073e-11e6-90b8-0badfcbc63cd.jpg)

Dispositivo desde donde se realizo la prueba

Marca: Samsung (S4)

![img-20160420-wa0026 1](https://cloud.githubusercontent.com/assets/18471856/14695726/c1288acc-073e-11e6-94db-5f872dd57902.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  comentar probando la ultima version si esta dando estos errores de cierre insperado

**Comment by MaviDavsa** [comment]
okay! @nattyco  En lo que lo haga te aviso! :D

**Comment by nattyco** [comment]
@MaviDavsa  este caso probarlo con la nueva version

**Comment by maydiamc** [comment]
este problema se soluciono @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Solucionado Entonces! :D
