### ISSUE TITLE
Chat - Mensajes cortados

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#174]
#### Nombre pantalla
Conversaciones

### Chat Fermat

-----

##### Reporte de error: 

   *Cuando me llegan los mensajes de alguien manualmente yo debía subirlo, porque no dejaba el ultimo mensaje al tope del lugar en donde corresponde escribir... Por ende era incomodo tener que subir a cada momento para observar el mensaje completo.

![error 5](https://cloud.githubusercontent.com/assets/17273005/14729090/440d953e-0804-11e6-9746-fc296417a8c9.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Motorola Moto X
* Version de Android: 4.4

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@MaviDavsa Puedes probar este mismo ejemplo con otro emulador que tenga un version superio a la 4, para descartar algunas cosas, porque creo que solo pasa en esa version!!!!!

**Comment by MaviDavsa** [comment]
Correcto! Solo me da el error en la versión 4.4

**Comment by franklinmarcano1970** [comment]
Si las versiones de android 4 tienen muchos problemas con fermat!!!!

**Comment by MaviDavsa** [comment]
Entonces este lo cerramos por no ser un Android compatible?

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
si casi siempre falla en esa version 4 pero es a nivel general de fermat!!!

**Comment by MaviDavsa** [comment]
okay
