### ISSUE TITLE
Chat- Mensajeria

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#175]
### Chat- Mensajes 

-----

##### Reporte de error: 

 Las burbujas de los mensajes están muy grandes en algunas respuestas.
Por ejemplo en el Hola y el bien y tu de esta imagen.
![captura de pantalla 114](https://cloud.githubusercontent.com/assets/18584168/14729133/b8b78c96-0804-11e6-8bb9-2d97a89ad1af.png)
 
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion

![captura de pantalla 113](https://cloud.githubusercontent.com/assets/18584168/14729167/08a08898-0805-11e6-8716-ac75fe5f1c44.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@AdryCanonico Ese caso parece que le diste enter y creo una linea en blanco, en ese chat. manana podemos probarlo de nuevo, pero creo que es eso!!!!

**Comment by AdryCanonico** [comment]
Ok @franklinmarcano1970 mañana lo probamos! Gracias!

**Comment by AdryCanonico** [comment]
Buenas tardes @MaviDavsa podrías cerrar este caso? Fue un error mio como lo comento @franklinmarcano1970 al agregar un enter antes de enviar el mensaje. Gracias!
