### ISSUE TITLE
Chat- Alarma avisando mensaje nuevo

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#176]
### Chat - Mensajes

-----

##### Reporte de error: 

 Dentro de los mensajes. Hay que salir de la conversación para recibir los mensajes nuevos (La persona no puede darse como enterada de los mensajes nuevos, al menos que salga de la conversación y se posicione en el listado de chat. Teniendo que ingresaar nuevamente a la conversación) . 
La conversación entre dos contactos no es fluida. 

![captura de pantalla 115](https://cloud.githubusercontent.com/assets/18584168/14729518/62d8ad42-0808-11e6-86f4-f09a8c9ea577.png)
![captura de pantalla 116](https://cloud.githubusercontent.com/assets/18584168/14729519/62dc3a0c-0808-11e6-9918-31a36755387d.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
![captura de pantalla 113](https://cloud.githubusercontent.com/assets/18584168/14729380/1d201066-0807-11e6-9e41-df61c2e82590.png)

* Modelo:Samsung Avant
* Version de Android:4.4.2

![screenshot_2016-04-20-23-43-08](https://cloud.githubusercontent.com/assets/18584168/14729461/e5ac152a-0807-11e6-8ac8-59b55c7fd520.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@AdryCanonico Hay que probar este issues!

**Comment by franklinmarcano1970** [comment]
Las notificaciones si revisan el documento no son partes del SCOPE.

**Comment by josejcb** [comment]
Unan estos issues https://github.com/Fermat-ORG/beta-testing-program/issues/406 estan repetidos.

**Comment by MaviDavsa** [comment]
Unido con el #406
