### ISSUE TITLE
Chat- Error Gráfico 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#178]
### Chat

-----

##### Reporte de error: 

El Status Bar se posiciona arriba del Accion Bar de la aplicacion Chat 

![screenshot_2016-04-21-22-06-29](https://cloud.githubusercontent.com/assets/18584168/14730139/be50dadc-080d-11e6-81b9-50fe0dff1912.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsumg
* Modelo:Avant

![screenshot_2016-04-20-23-43-08](https://cloud.githubusercontent.com/assets/18584168/14730140/c46d347e-080d-11e6-8c2a-5d49a5aea78d.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
Versión de Android vieja
