### ISSUE TITLE
Chat-Informe de entrega

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#179]
#### Nombre pantalla

Conversaciones

#### Error
 Cuando se envía un mensaje los informes de entrega no se marcan como debe, es decir por ejemplo marca los dos check grises y solo cambia a azules en algunos,  casos adjunto la imagen para que se observe.
![screenshot_2](https://cloud.githubusercontent.com/assets/5313324/14743927/17993e1c-086e-11e6-9b87-55b2e0c0541f.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/5313324/14743928/17bb5bfa-086e-11e6-92ba-6a0df3a10d02.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: google nexus 5
* Version de Android: 4.4

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
Versión de Android vieja
