### ISSUE TITLE
Chat - Error al salir y entrar de nuevo a la App.

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#181]
##### Reporte de error: 

   En repetidas ocasiones cuando me encontraba usando la app de Fermat y salía un momento a revisar otras aplicaciones como el Slack, cuando quería acceder de nuevo la pantalla estaba en negro y de inmediato me mostraba un mensaje indicando un error. Luego de esperar varios minutos la app seguía sin responder.

![screenshot_2016-04-22-19-26-07](https://cloud.githubusercontent.com/assets/17261437/14758013/ca3c1d6e-08c3-11e6-84de-f199de1929dc.png)

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-04-22-19-43-34](https://cloud.githubusercontent.com/assets/17261437/14757934/bbb5c69c-08c2-11e6-82ce-57aeafd05f5f.png)

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Pero eso no es un problema de chat sino de todo fermat!!!!

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Perfecto! Entonces este tipo de error no te los ponemos? Porque en los issues de la Bitcoin Wallet los comentamos y los montamos como Android Core o Performance! No se si aquí varía eso!

**Comment by gablup** [comment]
Si, por eso lo subo, porque lo habíamos comentado. Saludos!

**Comment by franklinmarcano1970** [comment]
Deberia!!!!

**Comment by MaviDavsa** [comment]
Entonces? Los dejamos!? o no? @franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Debes de cerrarlo!!!

**Comment by gablup** [comment]
Entendido! Gracias.
