### ISSUE TITLE
Chat Cajas de texto al final no se ven

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#182]
#### Nombre pantalla
Ventana Chat

### Chat

-----

##### Reporte de error: 

   *En la ventana de chat, las cajas de texto al llegar al final no se ven solo van saliendo cuando entran otros mensajes.

![2016-04-23 00 21 16](https://cloud.githubusercontent.com/assets/17273349/14758050/27cd1dca-08c4-11e6-8477-c7e51fc31e29.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Apex 2
* Version de Android: 4.4.2

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
Versión de Android vieja
