### ISSUE TITLE
Chat - Error en el orden de llegada de los mensajes

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#183]
##### Reporte de error: 

   Al enviarle un mensaje a un usuario, en este caso el de Adry, su respuesta aparece de primera a pesar de que en la hora de su mensaje se puede apreciar que fue enviado luego.
![screenshot_2016-04-22-20-13-52](https://cloud.githubusercontent.com/assets/17261437/14758368/e1adbc40-08c9-11e6-95fb-99258c6ba2e0.png)

#### Dispositivo desde donde se realizo la prueba
![screenshot_2016-04-22-19-43-34](https://cloud.githubusercontent.com/assets/17261437/14758324/ea783dce-08c8-11e6-876a-619f94a25aff.png)

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@AdryCanonico Debemos probar este caso en la nueva versión

**Comment by franklinmarcano1970** [comment]
Si eso esta solucionado debe probarlo.

**Comment by MaviDavsa** [comment]
Solucionado!
