### ISSUE TITLE
SubApp Community_ Connections

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#184]
#### Nombre pantalla
Connections

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El error radica en que en la Cripto Wallet tengo como contacto agregado a Yolanda 10, luego al ir a mis contactos no la tengo agregada, cuando voy a connections no me sale agregada y cuando me voy a notificaciones no me aparece para agregarla, en fin no puedo agregar este contacto a la Wallet porque en lineas generales ya debería estar agregada. 

![error 2](https://cloud.githubusercontent.com/assets/17273005/14788210/c3ffd9e0-0ad0-11e6-957e-1a5f60f9522a.JPG)

![error 2b](https://cloud.githubusercontent.com/assets/17273005/14788218/cc22af9e-0ad0-11e6-9713-cfe0bbacd930.JPG)

![error 2c](https://cloud.githubusercontent.com/assets/17273005/14788221/d079ffd4-0ad0-11e6-82ff-e5faf743d7ed.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa Aclarame un poco este caso, decis que en  la Cripto Wallet tengo como contacto agregado a Yolanda 10? como contacto o como conexion? ella te habia enviado una solicitud de conexion que vos habias aceptado? o vos le enviaste a ella? Puede ser que Yolanda te haya desconectado desde su app?

**Comment by MaviDavsa** [comment]
@nattyco Yo le envie a ella y ella acepto por ende se ve que en la Cripto Wallet se estableció una conexion, cuando la fui a buscar nada que me aparecía... Déjame verificar mañana con Yolanda a ver si ella me desconecto de su app, pero la verdad que no creo, porque todas trabajamos con el mismo usuario con el que habíamos trabajado el viernes, y el viernes yo le envié a ella BTC y todo, es decir yo la tenia en mis contactos y hoy no me salio.

**Comment by nattyco** [comment]
@MaviDavsa  verifica nuevamente esto con la nueva version de la apk a descarga de http://fermat.org/download/fermat-android-core-debug.apk

**Comment by MaviDavsa** [comment]
Solucionado @nattyco
