### ISSUE TITLE
DAP_Factory Wallet-Error al ingresar

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#186]
#### Nombre pantalla
Factory Wallet

### DAP

-----

##### Reporte de error: 

   *
Al hacer click sobre el botón FACTORY WALLET para ingresar,  se pone la pantalla negra y sale el siguente error

![error-factory wallet](https://cloud.githubusercontent.com/assets/17283358/14794744/34d2d4b0-0aef-11e6-86af-de80961d6071.png)

y se regresa a la pantalla de inicio.
-----

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Samsung Galaxy S 6 
* Version de Android: 6.0.0 API23-1440X2560

**Comment by MaviDavsa** [comment]
@acostarodrigo @nindriago

**Comment by acostarodrigo** [comment]
@MaviDavsa estan seguras de haber hecho la instalacion correcta del APK?

**Comment by MaviDavsa** [comment]
@acostarodrigo Si claro! La que les pase a las chicas es la que tu me enviaste! De todas maneras en la noche verifico!

**Comment by MaviDavsa** [comment]
Solucionado!
