### ISSUE TITLE
DAP_Error Asset Issuer

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#188]
#### Nombre pantalla
Asset Issuer

### DAP

-----

##### Reporte de error: 

   *El error está en que yo cree Asset en el Asset Factory y en teoría esos Asset creados tuvieron que ir automáticamente al Asset Issuer pero esto nunca paso, esperé un rato y mi billetera en el Asset Issuer siempre estuvo vacia. 

![error 3](https://cloud.githubusercontent.com/assets/17273005/14797241/8e168ac4-0afb-11e6-8bba-7a994aaa5dc6.JPG)

![error 3b](https://cloud.githubusercontent.com/assets/17273005/14797244/91920b74-0afb-11e6-9731-1f3b41c62157.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo:Google Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@acostarodrigo  @nindriago

**Comment by MaviDavsa** [comment]
Solucionado!

**Comment by acostarodrigo** [comment]
seguramente te faltaba hacer el publish.

**Comment by MaviDavsa** [comment]
Correcto! Pero en primera instancia no me salían los botones, por eso lo creamos como issues! :) @acostarodrigo

**Comment by MaviDavsa** [comment]
@acostarodrigo Aunque el hecho de que no me salieran los botones para publicar en ese emulador es un problema... Porque sin importar que teléfono sea los botones deben salirme!

**Comment by nindriago** [comment]
Comparte en que emulador estas realizando la prueba que te esta dando el problema?

**Comment by MaviDavsa** [comment]
Marca: Genymotion
Modelo:Google Nexus 4
Version de Android: 5.0

Allí me dio el problema!

**Comment by nindriago** [comment]
Muy raro, en ese modelo de equipo se realizan las pruebas de desarrollo todo el tiempo, por favor verifica nuevamente que estan realizandolo de manera adecuada y verificaremos por aca ese problema que mencionas

**Comment by MaviDavsa** [comment]
Si perfecto! Ya estamos trabajando pero son errores que no deben salir! No se si me explico! :) De todas maneras estamos probando en varios teléfonos...

**Comment by nindriago** [comment]
![captura de pantalla de 2016-04-26 11-40-52](https://cloud.githubusercontent.com/assets/13187461/14825442/d8066d54-0ba3-11e6-9898-38fcd3122368.png)

![captura de pantalla de 2016-04-26 11-43-21](https://cloud.githubusercontent.com/assets/13187461/14825527/1f1016c8-0ba4-11e6-9d41-d37bdcde1647.png)

Marca: Genymotion
Modelo:Google Nexus 4
Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nindriago Perfecto! Entonces lo cierro! :D
