### ISSUE TITLE
Chat- Freeze de Pantalla

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#189]
### Chat

-----

##### Reporte de error: 

  Cuando se esta conversando con otro contacto y se regresa al home de la aplicación da un freeze en la pantalla de varios segundos y en algunos casos se sale por completo de la aplicación de Fermat.
   

![screenshot_2016-04-25-19-59-47](https://cloud.githubusercontent.com/assets/18584168/14803384/d8b0472e-0b22-11e6-8ae0-4a509e6284f5.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsung
* Modelo:Avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/14803362/9d038150-0b22-11e6-96f6-be5d9628f9e7.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Lo mismo version de android!!!

**Comment by MaviDavsa** [comment]
Versión de Android vieja
