### ISSUE TITLE
Chat-Ordenar contactos

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#190]
##### Reporte de error: 

   Seria bueno una opcion que te permita poder ordenar los contactos alfabéticamente o por uso para tener una mejor búsqueda de ellos.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsung
* Modelo:Avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/14803500/d37551c2-0b23-11e6-9675-ca9ff1964107.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by AdryCanonico** [comment]
@RoyGF @jnonymous Seria bueno que en las próximas versiones se ordenaran los contactos alfabéticamente para tener un mejor orden,

**Comment by josejcb** [comment]
Listo, manana lo tienen

**Comment by AdryCanonico** [comment]
solucionado en la version 19.8 de cbp
