### ISSUE TITLE
Chat-Ficha para contact

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#191]
### Chat

-----

##### Reporte de error: 

   Seria bueno tener una opción para obtener mayor información del contacto que queramos visualizar. Algo así como una ficha de contacto o perfil. 
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsung
* Modelo:Avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/14803609/fc5aa9a6-0b24-11e6-9f5f-47dfec0b649f.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Es parte de los Profiles que seran manejados en la version 2

**Comment by MaviDavsa** [comment]
@AdryCanonico Hay que ver si en esta versión ya esta esto!

**Comment by franklinmarcano1970** [comment]
Bueno la información es la que se tiene en el profile solo su foto y su nombre, por ahora solo esta colocado lo aprobado en el bounty de la version 2.
Les recuerdo que nosotros trabajamos con proyecto aprobado,

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 perfecto! De todas maneras si no es en esta versión ya sabes que esta aquí como experiencia de usuario!

**Comment by franklinmarcano1970** [comment]
Perfecto, y sera tomado en cuenta en los proyectos venidero como SCOPE, para que sean aprobados!!!!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 @MaviDavsa En la versión 4 esta disponible la ficha. Se puede cerrar el caso.
