### ISSUE TITLE
Chat_Envios 

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#192]
#### Nombre pantalla
Home

### Chat 
-----

##### Reporte de error: 

   *El error radica que con algunos contactos, como en el caso de fabiana, ella me escribe y yo le respondí, pero en lineas generales en el home se debe de apreciar la respuesta que yo le di y no aun lo que ella me dice y no hace ese cambio nunca... Y aparte de este error también vemos otro que es que no cambia a azul las flechas una vez que ella ve el mensaje. 
   
![error 2b](https://cloud.githubusercontent.com/assets/17273005/14803760/484264fc-0b26-11e6-9a5e-44517824f69a.JPG)

![error 2](https://cloud.githubusercontent.com/assets/17273005/14803762/4d62ff46-0b26-11e6-85fb-5cf997b16d58.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion 
* Modelo: Google Nexus 7
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Porque el home se muestra el ultimo mensaje, bien sea el que se envia o se recibe!!!!

**Comment by MaviDavsa** [comment]
No mi amor! O sea el ultimo mensaje deberia ser el mio, el que dice "se te pone que? negro?" y no sale eso.. sale el de ella!

**Comment by franklinmarcano1970** [comment]
Listo entiendo!!!!

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Esto debo verificarlo cierto!

**Comment by franklinmarcano1970** [comment]
No esto era de esa version, aca no deber pasar,,

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Perfecto en lo que pueda lo pruebo!

**Comment by franklinmarcano1970** [comment]
@MaviDavsa Recuerde que te comente posiblemente cuando abres otra app en el emulador el broadcaster se rompe, entonces tenemos que darle force stop, para que se solucione, te lo comente en la reunion y lo vimos en vivo...creo que debes cerrar el caso

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Si pero en este caso yo no tenia ninguna otra aplicación abierta! :D ... Mañana verifico! Y veo si esta solucionado!

**Comment by MaviDavsa** [comment]
Solucionado!
