### ISSUE TITLE
Chat-Scroll Add Contact

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#193]
### Chat

-----

##### Reporte de error: 

  En el momento de la búsqueda de contactos para poder agregarlos, no se mueve el scroll simultaneo con los contactos en el desplazamiento. 

![screenshot_2016-04-25-20-48-58](https://cloud.githubusercontent.com/assets/18584168/14803947/4e0e88d2-0b28-11e6-9162-d13c4050139f.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsumg
* Modelo:Avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/14803950/5d800fac-0b28-11e6-8194-4a2679bdb6d9.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Ok en versiones superiores ya esa opcion para agregar contacto no existira esto fue una version de arranque para las versiones futuras!!!1

**Comment by MaviDavsa** [comment]
Versión de Android Antigua para la funcionalidad del App!
