### ISSUE TITLE
Chat - error del teclado

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#194]
##### Reporte de error: 

El teclado no deja ver lo que se escribe.

- [x] Pantalla de envio

![image](https://cloud.githubusercontent.com/assets/18452495/14803979/a098e656-0b28-11e6-8bbb-607cb461ccbf.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/14804017/0b34fdd8-0b29-11e6-8cb0-aa2f5cd2e790.png)

**Comment by andreagmarcano** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
Versión de Android Antigua para la funcionalidad del App!

**Comment by arosiopr** [comment]
@sanro14  este error no sucede en mi celular

![screenshot_2016-08-10-16-53-56](https://cloud.githubusercontent.com/assets/5313326/17570672/603b06c4-5f1b-11e6-9bfc-ea86726a7571.png)


![alcatel](https://cloud.githubusercontent.com/assets/5313326/17570515/bb969c28-5f1a-11e6-840a-edbc2bd36670.png)

**Comment by sanro14** [comment]
@AdryCanonico a ti te sigue sucediendo esto para reabrirlo?
