### ISSUE TITLE
CHAT - Notificaciones desordenadas 

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#195]
### Reporte de error: La mayoría de las veces no tengo ninguna notificación al recibir un mensaje, y cuando me llega la notificación debo abrir y cerrar la conversación varias veces para que ésta desaparezca, en algunos casos respondo y las notificaciones de los mensajes anteriores siguen allí. 

![img-20160425-wa0015 1](https://cloud.githubusercontent.com/assets/18471856/14803955/6f9fd6b8-0b28-11e6-96fc-b40d1f92f855.jpg)

### Dispositivo desde donde se realizo la prueba

Marca: Blu
Modelo: Advance 4.0
Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
Versión de Android Antigua para la funcionalidad del App!
