### ISSUE TITLE
Chat_Identities - Contenedor

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#196]
### Identities 

-----

##### Reporte de error: 

  Los nombres de las Identities se cortan y no se logran leer bien. 

![screenshot_2016-04-25-21-02-04](https://cloud.githubusercontent.com/assets/18584168/14804099/f0172aca-0b29-11e6-8414-2d2e94432c0c.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsung
* Modelo:Avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/14804093/e376e6fc-0b29-11e6-81b7-2d106a59896f.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Todo eso pasa porque no hay mucha compatibilidad con esa version de android

**Comment by MaviDavsa** [comment]
Versión de Android Antigua para la funcionalidad del App!
