### ISSUE TITLE
Chat_  Chat Tamaño del texto

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#197]
##### Reporte de error: 

  El texto en el chat es mas grande que la burbuja, quedando algunas letras por fuera. O en ocasiones,  el texto no está dentro de la burbuja del chat.  

![screenshot_2016-04-22-20-10-56](https://cloud.githubusercontent.com/assets/17262077/14804191/e63880ac-0b2a-11e6-86d5-8d3b90649442.png)
![screenshot_2016-04-25-20-34-58](https://cloud.githubusercontent.com/assets/17262077/14804194/ea9326b6-0b2a-11e6-87ad-2302f8080ba6.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Samsung
* Modelo: GT-I9082L
* Version de Android:4.2.2

**Comment by MaviDavsa** [comment]
@Gabymorillo Es posible que sea por el tipo de Android! Peroo.. que @franklinmarcano1970  lo diga! :)

**Comment by Gabymorillo** [comment]
Ok ;)

**Comment by franklinmarcano1970** [comment]
Si las versiones de android 4 tienen muchos problemas con fermat!!!!

**Comment by MaviDavsa** [comment]
Versión de Android Antigua para la funcionalidad del App!
