### ISSUE TITLE
DAP_Issuer Profile_ Se cierra

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#198]
#### Nombre pantalla
Issuer Profile

### DAP

-----

##### Reporte de error: 

   *El error radica en que cuando quiero agregar a esta persona a mis contactos desde la community para poder tenerlos en mis contactos me muestra este error y se me cierra la wallet
 
![error dap 1](https://cloud.githubusercontent.com/assets/17273005/14825059/29b1a508-0ba2-11e6-88c4-831b53ae5268.JPG)
  
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion 
* Modelo: Google Nexus 4
* Version de Android: 5.1.0

**Comment by MaviDavsa** [comment]
@acostarodrigo @nindriago

**Comment by nindriago** [comment]
mmmmm, por favor explica desde donde se realizo esta solicitud?? es decir que se intento realizar?

**Comment by MaviDavsa** [comment]
Yo soy Asset Issuer... Y me metí en la commnity de las mismas Asset Issuer a ver si conseguí a alguien y podía agregarlo, porque me metí en la Asser User y jamas pude agregar a Augusto ni el a mi... Entonces en lo que le di a agregar se me tranco y se reinicio la app...

**Comment by nindriago** [comment]
las conexiones en DAP no se realizan como en Community CCP, las conexiones validas para darse en DAP se realizan de la siguiente Manera.

Asset Issuer - Asset User / Asser User - Redeem Point / Redeem Point - Asset Issuer

Conexiones en DAP de otro tipo en este momento no estan permitidas...

**Comment by MaviDavsa** [comment]
Entonces debería salir algún mensaje en donde me explica eso!

**Comment by acostarodrigo** [comment]
Hola, por favor volvé a intentar los mismos pasos.
El error de que Fermat no responde puede no ser precisamente por algo de DAP, sino que el emulador está lento y quizás sea un problema de conexión.

Pudo ocurrir en cualquier momento.

**Comment by MaviDavsa** [comment]
Hola @acostarodrigo Si exactamente a eso me refiero, yo se que puede ser problema de red o emulador, pero este mismo paso lo hice como 5 veces y las 5 veces me lanzo el mismo error, por eso lo comente como issues... Que me pase una vez okay normal, pero varias veces haciendo el mismo procedimiento no es normal... No se si me explico!

**Comment by MaviDavsa** [comment]
@acostarodrigo Yo lo voy a volver a intentar, claro que si... Ese es mi trabajo, pero el hecho de que me salga algún error por muy mínimo que sea ya es mi trabajo notificarles, porque entonces esa versión esta dando algún problema... :)

**Comment by acostarodrigo** [comment]
Si perfecto, si lo has hecho 5 veces y siempre se reproduce entonces lo vamos a ver.
@nindriago si tienes claros los pasos por favor intenta reproducir para obtener el error.

**Comment by nindriago** [comment]
ya este Issue se puede cerrar @MaviDavsa
