### ISSUE TITLE
DAP-Error al crear un Asset

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#199]
### DAP

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

Cuando intento crear un Asset hago todos los paso, lleno todo los datos que se me solicita y cuando le doy click al botón Créate me arroja un error, intente varias veces el mismo proceso y el error se repite.

<img width="378" alt="captura de pantalla 2016-04-26 a las 13 11 07" src="https://cloud.githubusercontent.com/assets/15804433/14825467/7bb663f8-0bb0-11e6-985c-a9ba1e557f39.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="402" alt="captura de pantalla 2016-04-26 a las 13 13 18" src="https://cloud.githubusercontent.com/assets/15804433/14825523/ad135424-0bb0-11e6-9a14-14f54f00ad0c.png">

**Comment by augusto-ponce** [comment]
@nindriago @acostarodrigo

**Comment by nindriago** [comment]
Intente reproducir el error pero no lo consigo
![captura de pantalla de 2016-04-26 12-30-03](https://cloud.githubusercontent.com/assets/13187461/14827169/dd0ba3c6-0baa-11e6-9ac7-c8983780e1af.png)

![captura de pantalla de 2016-04-26 12-30-42](https://cloud.githubusercontent.com/assets/13187461/14827170/dd153486-0baa-11e6-90ed-e323d6e42344.png)

**Comment by nindriago** [comment]
por favor, se puede cerrar el issue @augusto-ponce @MaviDavsa

**Comment by MaviDavsa** [comment]
@augusto-ponce Este issues esta solucionado!

**Comment by augusto-ponce** [comment]
perfecto !! cerrado el caso entonces
