### ISSUE TITLE
Chat - Error al entrar al mensaje

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#200]
##### Reporte de error: 

   Cuando quise entrar  para escribir a un contacto, me dio este mensaje "Ooooops! recovering from system error" y no pude abrir el mensaje, en ambos emuladores. Para lograrlo tuve que salir de la aplicación completa y volver a entrar. 
   

![captura de pantalla 136](https://cloud.githubusercontent.com/assets/18584168/14838055/58dd9388-0be7-11e6-988e-ea3d37ba4d5f.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14838066/857570be-0be7-11e6-8437-6d3aa22b75da.png)
![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14838067/8579bcc8-0be7-11e6-89fd-a3365bcd31ef.png)

**Comment by MaviDavsa** [comment]
Versión problematica... Problema de fermat!

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Lo cerré porque me imagino que esto sale por el problema que nos comentaste!
