### ISSUE TITLE
Chat - Error para visualizar foto de contacto

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#201]
### Chat 

-----

##### Reporte de error: 
 Se cargo una foto en el perfil de Adry 1 Chat (Emulador, pantalla lado izquierdo).

No se visualiza la foto del perfil de contacto Adry 1 Chat en el contacto Adry 3 Chat  (Emulador, pantalla lado derecho). 

![captura de pantalla 137](https://cloud.githubusercontent.com/assets/18584168/14839253/26e9ac52-0bf3-11e6-930b-7a100d1ad97f.png)

   
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo:Emulador

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14839240/0d7af190-0bf3-11e6-9f5d-e191e0d8ee5f.png)
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14839241/0da14fde-0bf3-11e6-9331-f25437285fb3.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Porque cuando se creo el wallet users no se coloco la foto!!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 ,Buen día!!  No se veía la foto del perfil Adry 1 el emulador del S6 (Adry 3). El resto de las chicas si veían la foto de Adry 1.

**Comment by MaviDavsa** [comment]
@AdryCanonico Debemos probar esto.

**Comment by franklinmarcano1970** [comment]
@MaviDavsa @AdryCanonico en la version 2 esto esta solucionado!!!!

**Comment by MaviDavsa** [comment]
@AdryCanonico En mi Emulador ya se corrigió este problema, de todas maneras como el caso es tuyo pruebalo y me avisas!

**Comment by AdryCanonico** [comment]
Lo probare hoy en la versión 4, ya que en la versión 2 seguía persistiendo el error.

**Comment by franklinmarcano1970** [comment]
Ok revisaremos..

**Comment by franklinmarcano1970** [comment]
@AdryCanonico @MaviDavsa Esto ya esta resuelto, por favor revisar!!!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 en la versión 4 de chat no cambio la foto.

cuando hice el cambio se hizo en la community 

![pantalla 2](https://cloud.githubusercontent.com/assets/18584168/15594826/48c805a6-2383-11e6-8cdd-77241d2d17a5.png)



pero en chat cambio a la imagen predeterminada. 

![3](https://cloud.githubusercontent.com/assets/18584168/15594685/bb571bb8-2381-11e6-83cd-2ecb00482b67.png)


Cualquier cosa estoy a la orden si necesitan verificar.

**Comment by franklinmarcano1970** [comment]
@AdryCanonico Intenta darle actaulizar dandole swype en contactos, como te dije en la call..

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 @MaviDavsa ya se corrigió el error. Se pude cerrar el caso.

**Comment by MaviDavsa** [comment]
Perfecto!
