### ISSUE TITLE
Bitcoin Wallet - Montado los Tabs sobre el icono de "No Transactions" 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#203]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Se montan los Tabs sobre el icono de "No Transactions" y para poder lograr verlo completo hay que subir y bajar los Tabs.
   

![captura de pantalla 140](https://cloud.githubusercontent.com/assets/18584168/14873384/b89107be-0cbf-11e6-97ef-a0125652b26a.png)
![captura de pantalla 138](https://cloud.githubusercontent.com/assets/18584168/14873385/b897af74-0cbf-11e6-9dfd-a594d74a6600.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Primera Pantalla

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Segunda Pantalla

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@MaviDavsa En la prueba de hoy con la actualizacion de la apk. 

En el Emulador del Nexus 5, versión 5.1.0, Se arreglo el problema gráfico.

![captura de pantalla 164](https://cloud.githubusercontent.com/assets/18584168/14905755/e811a30e-0d7d-11e6-9304-ef5bfa9550be.png)

En el Samsung S6, versión 6.0.0 sigue persistiendo el problema gráfico


![captura de pantalla 165](https://cloud.githubusercontent.com/assets/18584168/14905791/3c33fe64-0d7e-11e6-83fc-8a40e2183ea0.png)

**Comment by MaviDavsa** [comment]
@nattyco bella que hacemos con este issues!!? porque el samsung siempre da ese error!

**Comment by AdryCanonico** [comment]
Sigue sucediendo el mismo caso en el S6

**Comment by MaviDavsa** [comment]
@nattyco Solucionado
