### ISSUE TITLE
Bitcoin Wallet - Tardanza en la llegada de Notificaciones de transacción 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#204]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *No llego la notificación de transacciones recibidas hasta que salí de la Bitcoin Wallet y volví a entrar. 
    Para que se viera reflejada. 

![captura de pantalla 147](https://cloud.githubusercontent.com/assets/18584168/14873564/e5521778-0cc1-11e6-82b4-69dfe14a1244.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genimotion
* Modelo:Emulador
:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873580/f2612ac6-0cc1-11e6-8566-bea81c4b6133.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico Verificar en la nueva version de la app

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa 

En la prueba de hoy la notificación llego con mejor tiempo y no tuve que actualizar para verificar la transacción.
