### ISSUE TITLE
Community - Cripto Wallet User contactos duplicados

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#205]
### Community 

-----

##### Reporte de error: 

   *Al entrar a la Cripto Wallet User se duplican los contactos y hay que actualizar para poder ver los que hay realmente. 
   
![captura de pantalla 142](https://cloud.githubusercontent.com/assets/18584168/14873783/aec2171a-0cc3-11e6-811e-d937e232933c.png)
![captura de pantalla 144](https://cloud.githubusercontent.com/assets/18584168/14873785/b6b8480e-0cc3-11e6-9278-989acb50afc1.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Primera Pantalla

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Segunda Pantalla

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  probar este reporte con la nueva version de la app

**Comment by AdryCanonico** [comment]
@nattyco Con la prueba de hoy persiste la duplicación de contactos en ambos emuladores. 

![captura de pantalla 156](https://cloud.githubusercontent.com/assets/18584168/14906099/9133c932-0d81-11e6-9d4d-6a12e1620aa9.png)
![captura de pantalla 157](https://cloud.githubusercontent.com/assets/18584168/14906100/9138ba82-0d81-11e6-97e6-8d6f0f9f971a.png)

**Comment by AdryCanonico** [comment]
@nattyco 
En la prueba de hoy con la red: TestNet.
Sigue persistiendo el error. Hay que actualizar para que los contactos no salgan duplicados.


![captura de pantalla 186](https://cloud.githubusercontent.com/assets/18584168/14932929/585032a4-0e49-11e6-8923-138b009c4846.png)

**Comment by nattyco** [comment]
@MaviDavsa  verificar este reporte con la nueva apk subida

**Comment by AdryCanonico** [comment]
@nattyco  En la versión 5 LPW, se duplican los contactos solo con el Nexus S. 240 dpi)

![duplicado de contacto](https://cloud.githubusercontent.com/assets/18584168/15581447/25d29f90-2336-11e6-8767-6ddcb64400e3.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico Debes probar la LPW 6!

**Comment by maydiamc** [comment]
En la version 6 de la LPW se esta presentando este error
Samsung galaxy S4 mini
4.4.2

![screenshot_2016-05-27-10-01-30](https://cloud.githubusercontent.com/assets/17274154/15611122/a7a05186-23f2-11e6-9913-72d79241f98f.png)

**Comment by AdryCanonico** [comment]
@ En la versión 6 LPW, sigue apareciendo el error como lo comento @maydiamc en todos los emuladores que utilizamos en la prueba.

**Comment by marielis-urbina** [comment]
En la nueva versión 12 de LPW siguen apareciendo duplicados los contactos

![se repite contacto](https://cloud.githubusercontent.com/assets/19353722/15765318/38147300-28fd-11e6-9efb-e72a92952fdb.png)

Dispositivo desde donde se realizo la prueba

Marca: Nexus 4
Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/15765335/96e41462-28fd-11e6-9185-ef7dae86bdc7.png)

**Comment by kmiloxvii** [comment]
En la versión 12 se están duplicando las connetions, se realizo la prueba entre dos usuarios:

1.  Los 2 usuarios se enviaron las invitaciones en Cripto Wallet User.
2. el primer usuario acepto la invitación por lo que se ambos usuarios se agregaron a connections  (se generaron 2 invitaciones por aparte).

![error_connections_one](https://cloud.githubusercontent.com/assets/2491042/15766211/d6abbbce-2905-11e6-9e3a-2e74580ba4a9.png)

3.En el menu de Notifications sigue la segunda invitación que se genero con el usuario que se acabo de agregar a connections.

![error_connections_two](https://cloud.githubusercontent.com/assets/2491042/15766235/283a6170-2906-11e6-9814-a1ab114b661c.png)


4. Al presionar esta aparece la notificación para aceptar la invitación aunque la persona ya esta agregada.

![error_connections_question](https://cloud.githubusercontent.com/assets/2491042/15766254/5dd2b184-2906-11e6-88c4-f40904999307.png)

5. Al aceptar la invitación, se crea una nueva connection con la misma persona, es decir se duplica  la connection

![error_connection](https://cloud.githubusercontent.com/assets/2491042/15766297/b2d57cf2-2906-11e6-84fb-890098cf2878.png)

Dispositivo
![test_phone](https://cloud.githubusercontent.com/assets/2491042/15766331/1061e2b6-2907-11e6-963b-6cc48f754db1.png)

**Comment by AdryCanonico** [comment]
@nattyco en la versión 15.2 de LPW sigue persistiendo el error.

**Comment by AdryCanonico** [comment]
@nattyco en la versión 16.2 de LPW sigue persistiendo el error

**Comment by maydiamc** [comment]
en la version 17, no sucede esto en mi dispositivo @nattyco 
@AdryCanonico 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025495/93a2d5b2-3191-11e6-8ebe-ec45fe868e0d.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version 18 de CBP sigue persistiendo el error.

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa  En la version 18.3 CBP no se presenta el error. Se puede cerrar el caso.

**Comment by LilianFlores** [comment]
En la versión 20.7 de CBP este error se presenta al buscar un contacto con el buscador. Por favor, reabrir el caso. 

![user](https://cloud.githubusercontent.com/assets/19652611/16890242/c72ea414-4aba-11e6-82b4-266aadac43bd.png)

**Dispositivo desde donde se realizo la prueba:**

![celular](https://cloud.githubusercontent.com/assets/19652611/16890311/40519a54-4abb-11e6-98f4-873822419b14.png)

**Comment by Hernandezsmanu** [comment]
Fecha: 18-07-2016
Version 20. 7
Persiste el error al momento de buscar.

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16920432/92197d94-4cdb-11e6-9cc3-9d52b3ab80d2.png)

**Comment by arosiopr** [comment]
en la versión 20.8 de CBP persiste el error

![screenshot_19](https://cloud.githubusercontent.com/assets/5313326/17002252/78de2d02-4e98-11e6-9db8-da02b0305d72.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/17002273/9047aa68-4e98-11e6-975c-f163527b3089.png)

**Comment by dorzar1989** [comment]
En la version 20.9.1 ya no sucede este error.

- Movil:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17035318/ab46c8dc-4f54-11e6-9a43-39c060c7b23a.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by dorzar1989** [comment]
En la Version 21.3 de la CBP persiste este error

- Screenshot:

![screenshot_140](https://cloud.githubusercontent.com/assets/19670319/17367122/acd92ea8-595c-11e6-9824-126848ff21b2.png)

![screenshot_139](https://cloud.githubusercontent.com/assets/19670319/17367123/aced8614-595c-11e6-8014-b223d360beb3.png)

- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17367125/b6755bee-595c-11e6-9b92-1d6f39ff620e.png)

**Comment by dorzar1989** [comment]
En la Version 21.7 de la CBP no me sucede este error

- Screenshot:

![screenshot_210](https://cloud.githubusercontent.com/assets/19670319/17527824/e5e92fb2-5e3a-11e6-9c81-aa9f41d4934c.png)

![screenshot_209](https://cloud.githubusercontent.com/assets/19670319/17527825/e5f4d43e-5e3a-11e6-8dfe-02f287201182.png)

- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17527837/ede5b9f6-5e3a-11e6-8b68-24baa6ebac3c.png)

**Comment by IsbetVR** [comment]
Closed #205
