### ISSUE TITLE
Community - Cripto Wallet User No llego la Notificacion para admitir contacto

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#207]
### Community

-----

##### Reporte de error: 

   *No llego la Notificación para admitir contacto

Ejemplo: Adry 1  (emulador de la izquierda) visualiza al contacto Adry 2 y envió una solicitud para ser agregado como contacto;pero Adry 2 (emulador de la derecha) no le llego la notificación para admitir al contacto Adry 1.
   

![captura de pantalla 148](https://cloud.githubusercontent.com/assets/18584168/14874248/fc55b0d2-0cc7-11e6-83b0-847146957a3a.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Derecha

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador izquierda

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
Cuanto tiempo esperaste para que te llegará la solicitud? @AdryCanonico

**Comment by nattyco** [comment]
Esto pasa porque uno de los emuladores no esta conectado a la red de fermat.

**Comment by AdryCanonico** [comment]
Hola @nattyco! Como estas? Me podrías explicar donde puedo verificar la conexión del emulador a la red de Fermat? Para verificar este caso.

**Comment by MaviDavsa** [comment]
en los settings! Verifica que los dos teléfonos estén en la misma red!

**Comment by AdryCanonico** [comment]
@MaviDavsa espere como una hora, hice varios intentos y no logre recibirla. Esto no solo me paso con mis emuladores sino también con otros contactos. Ya que solo pude visualizar a Alegnaire.

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco 

Después del cambio de red en ambos emuladores el día de hoy, siguen tardando mucho las notificaciones. En este caso espere una hora y no ha llegado. 


![captura de pantalla 171](https://cloud.githubusercontent.com/assets/18584168/14906876/8558c6a4-0d8a-11e6-87aa-0f923e4785b2.png)


![captura de pantalla 170](https://cloud.githubusercontent.com/assets/18584168/14906881/8aaddcca-0d8a-11e6-968a-6a84b4f2ffa0.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco 

En la prueba de hoy las notificaciones llegaron a buen tiempo. Sin demoras. 
Estamos trabajando con la red:TesNet
