### ISSUE TITLE
Bit Coin Wallet_ Home_ RECIVED

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#208]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *En esta oportunidad el error es que como ves tengo btc disponibles y en los RECIVED no me muestra absolutamente nada, refresco la imagen y nada pasa... No me muestra ni los mati btc que me enviaron ni los que me llegaron...

![fgdf](https://cloud.githubusercontent.com/assets/17273005/14890931/5436a372-0d2e-11e6-89c5-11ed453b84de.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  si vas a otra pantalla y volves ahi podes ver la transaccion de receive?

**Comment by MaviDavsa** [comment]
Ya lo hice mi amor... Y nada... @nattyco

**Comment by MaviDavsa** [comment]
@nattyco El error persiste! pero creo que el verdadero error es el botón de refrescar que no cumple con el trabajo que debería, me salgo al home, voy a contactos y regreso y se ven los recived, pero cuando refresco desparecen!

**Comment by MaviDavsa** [comment]
@nattyco Solucionado!
