### ISSUE TITLE
Bitcoin Wallet- error en el Book Balance

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#209]
#### Nombre pantalla

Home
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   **Estando en el home e ir a contactos se cerro la apk. Al ingresar de nuevo, todas las transacciones (BTC recibidos por la red regnet y los de mavi1 no aparecen. En el Book balance sale 0.00 BTC ). Los peyment (estan pero en el book balance no lo refleja.
![error en el home se borraron las transacciones](https://cloud.githubusercontent.com/assets/17283358/14892655/ac4e37a8-0d35-11e6-91ab-f439a89894ef.png)

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   

   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
* Modelo:
Nexus 4 Api 21 768x1280
* Version de Android:
5.0.0

**Comment by nattyco** [comment]
@yolandayancel  probar este error con la nueva version de la apk, el error es que se pierde el balance al cerrar el emulador y entrar de nuevo, o cuando la app se cierra por un error.

**Comment by nattyco** [comment]
@MaviDavsa  verificar este reporte con la nueva version de la apk

**Comment by yolandayancel** [comment]
Buenas María

Reviso el caso 209, con la apk de fecha 28-04-16?

2016-05-10 12:06 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @MaviDavsa <https://github.com/MaviDavsa> verificar este reporte con la
> nueva version de la apk
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/209#issuecomment-218215803>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by MaviDavsa** [comment]
@yolandayancel Conectate al Slack para que lo revisemos juntas! porque hay una nueva apk!

**Comment by yolandayancel** [comment]
okey


2016-05-10 16:27 GMT-04:30 MaViDavsa <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> Conectate al Slack para
> que lo revisemos juntas! porque hay una nueva apk!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/209#issuecomment-218289255>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by MaviDavsa** [comment]
Solucionado!
