### ISSUE TITLE
Bitcoin Wallet - Se monta el Botón sobre el Drawer

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#210]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El error se produce cuando se esta en contacts en la Bitcoin Wallet y se despliega el drawer. 
     (Queda el botón de (+) sobre el drawer)
   

![captura de pantalla 160](https://cloud.githubusercontent.com/assets/18584168/14907271/0215ef00-0d90-11e6-8f1e-9468a61681cb.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14907276/16320b7c-0d90-11e6-9171-fcd9a6cc9ab4.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
En la prueba de hoy sigue persistiendo el error

![captura de pantalla 185](https://cloud.githubusercontent.com/assets/18584168/14932666/d9acf4dc-0e43-11e6-9a8c-ebafa262a55a.png)

**Comment by nattyco** [comment]
@MaviDavsa  Resuelto,el boton se oculta al abrir el menu.

**Comment by MaviDavsa** [comment]
Solucionado!
