### ISSUE TITLE
Bitcoin Wallet - Se monta el Botón de la pantalla Request sobre el Drawer

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#211]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El error se produce cuando se esta en request en la Bitcoin Wallet y se despliega el drawer. 
(Queda el botón  inferior derecho sobre el drawer)

![captura de pantalla 177](https://cloud.githubusercontent.com/assets/18584168/14932990/b0f97c52-0e4a-11e6-88c3-6057cbdc15f2.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Pantalla Derecha

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  corregido en la nueva version se oculta el boton al abrir el menu

**Comment by MaviDavsa** [comment]
Solucionado
