### ISSUE TITLE
Bitcoin Wallet - Se monta el Botón de mas (+) arriba del scroll de contacts

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#212]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Se monta el Botón de mas (+) arriba del scroll de la derecha que contiene el orden alfabético de contacts. No deja utilizar las letras: W, X, Y, Z.

![captura de pantalla 188](https://cloud.githubusercontent.com/assets/18584168/14933105/ed610478-0e4d-11e6-95db-1e95bdd231c9.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Pantalla Derecha

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nattyco Este error persiste!

**Comment by nattyco** [comment]
@AdryCanonico Corregido verificar en la nueva version de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la version 5 de LPW se corrigió

![signo mas](https://cloud.githubusercontent.com/assets/18584168/15541226/465840e4-2255-11e6-9d5d-0f29404844dc.png)
. Se puede cerrar el caso.
