### ISSUE TITLE
Community - Botones de Ayuda se ven diferentes en los emuladores 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#214]
### Community

-----

##### Reporte de error: 

   *En ambos emuladores no se aprecia el mismo botón de ayuda.

![captura de pantalla 191](https://cloud.githubusercontent.com/assets/18584168/14933247/665428a2-0e52-11e6-8479-327739313d86.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Pantalla Derecha

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nattyco Esto es así por ser teléfonos diferentes o es un error?

**Comment by nattyco** [comment]
@AdryCanonico  Resuelto

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco Persiste el error en la versión 5 de LWP

![ayuda](https://cloud.githubusercontent.com/assets/18584168/15540977/f1d0b3cc-2253-11e6-8908-fb7b0e364c91.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Pantalla Derecha:

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15541009/1caedfc4-2254-11e6-825a-77c3c94d4bba.png)

**Comment by nattyco** [comment]
@AdryCanonico verificar en la version 7 de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la versión 7 están los botones de ayuda igual pero algo grandes en ambos emuladores. 

![ayuda](https://cloud.githubusercontent.com/assets/18584168/15649248/fe993630-2639-11e6-9846-09e4591edc01.png)

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 10 LPW, me parece que el icono de ayuda esta muy grande.

![ayuda grande](https://cloud.githubusercontent.com/assets/18584168/15711461/e8f2daa8-27d7-11e6-8d38-6a901b75bdfa.png)
