### ISSUE TITLE
Community - Mejorar Icono mensaje: You don´t have any notifications

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#215]
### Community 

-----

##### Reporte de error: 

   *Seria bueno encontrar un Icono mas amigables y que se apegue mas al mensaje: You don´t have any notifications yet. 

![captura de pantalla 190](https://cloud.githubusercontent.com/assets/18584168/14933294/8f55077a-0e53-11e6-96d7-10ce310dfcaf.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Pantalla Derecha

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by dorzar1989** [comment]
En la Version 20.1 de la CBP sigue la misma pantalla 

![screenshot_39](https://cloud.githubusercontent.com/assets/19670319/16688183/d095a0c8-44ea-11e6-9705-838808fdea88.png)

- MOVIL: Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16688193/de8fb7cc-44ea-11e6-85f8-d55e00a1e99d.png)

**Comment by nattyco** [comment]
@AdryCanonico  el diseño del community de CCP cambio por lo que esta pantalla ya no existe.

**Comment by IsbetVR** [comment]
Estas pantallas cambiaron en diseño. Solucionado en la versión 20.9 Bitcoin Wallet

![screenshot_3](https://cloud.githubusercontent.com/assets/19142276/16999696/50e7363c-4e8d-11e6-9ac2-c10371fc7c75.jpg)


#### Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16999699/570656f6-4e8d-11e6-99d3-db10c438f75d.jpg)

**Comment by IsbetVR** [comment]
Closed #215
