### ISSUE TITLE
Community - Mejorar Boton, Mensaje: Close

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#216]
### Community

-----

##### Reporte de error: 

   *Seria bueno encontrar un botón mas amigables o que se apegue mas al mensaje: Close.
Ya que se ve un poco exagerado de tamaño y no da armonía con el contenedor de las community.
 (La "X" que estaba anteriormente se veía mas acorde al diseño) 

![captura de pantalla 189](https://cloud.githubusercontent.com/assets/18584168/14933351/e04b3cde-0e54-11e6-8343-d17956cd65d4.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14873790/c76abd58-0cc3-11e6-8022-fad84ad97064.png)

Emulador Pantalla Derecha

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/14873789/c7646494-0cc3-11e6-87a0-502399dbfab6.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico Eso no esta especificamente dentro de la wallet! por ende no nos corresponde Testear aun! :)

**Comment by nattyco** [comment]
@AdryCanonico  en la nueva version se quito ese boton

**Comment by maydiamc** [comment]
en la version 11, se coloco una X que va acorde con el diseño de la apk, mejorado @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
@AdryCanonico Verifica por favor!

**Comment by AdryCanonico** [comment]
En la versión 11 de LPW se cambio el botón pero aun sigue saliendo en otras pruebas, no se si se utiliza otras community.

**Comment by nattyco** [comment]
@AdryCanonico donde se cambio es en la apk que manejamos nosotros en la plataforma de CCP, los otros grupos pueden no tener las mismas actualizaciones

**Comment by nattyco** [comment]
@MaviDavsa  verificar esto

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco ok Naty. Ya se corrigió. Se puede cerrar el caso.

**Comment by MaviDavsa** [comment]
Solucionado!
