### ISSUE TITLE
DAP_Deliver Assets_ Send Users 

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#217]
#### Nombre pantalla
Send Users

### DAP

-----

##### Reporte de error: 

   *En la parte de Agregar contactos para poder enviar los cupones deberían explicar como se pueden agregar los contactos, porque las personas se sienten en blanco, es decir una vez llegado a ese punto ya no se que hacer para seguir con la funcionalidad de la DAP 

![dfsdfsd](https://cloud.githubusercontent.com/assets/17273005/14958990/207f5cb4-1057-11e6-9718-6fc2ef31bc1d.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion 
* Modelo: Google Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nindriago  @acostarodrigo

**Comment by nindriago** [comment]
este issue se puede cerrar ya han realizado este escenario varias veces.
