### ISSUE TITLE
DAP- Asset User - Foto drawer Borroso

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#219]
##### Reporte de error: 

   *Se ve borroso la foto que identifica la Asset User en el Drawer. 
   

![captura de pantalla 202](https://cloud.githubusercontent.com/assets/18584168/14959780/cdb4eb26-105a-11e6-92d0-e41fdbd38041.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14959849/3fa30768-105b-11e6-89af-3526a10e9a00.png)

Emulador Pantalla Derecha

![s6 6 0](https://cloud.githubusercontent.com/assets/18584168/14959868/640b9642-105b-11e6-9325-a7c735dfb9ac.png)

**Comment by AdryCanonico** [comment]
@nindriago @acostarodrigo

**Comment by nindriago** [comment]
Esto no podemos manejarlo nosotros, ya esto es un problema general de todo fermat en el manejo de las imagenes que esta buscando como mejorar las imagenes

**Comment by MaviDavsa** [comment]
Genial, pero se dejan por aqui hasta que se puedan solucionar...

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa en la version 2 cuando subes una foto al perfil no se ve borroso. Se puede cerrar el caso.

Se sugiere cambiar la foto predeterminada mas amigable para el usuario.

![drawer user](https://cloud.githubusercontent.com/assets/18584168/15561546/ebc09b60-22c0-11e6-9a85-2647bf64b0b5.png)
