### ISSUE TITLE
DAP- Redeem Point -  Foto drawer Borroso

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#220]
### DAP

-----

##### Reporte de error: 

   *Se ve borroso la foto que identifica la Redeem Point en el Drawer

![captura de pantalla 203](https://cloud.githubusercontent.com/assets/18584168/14960033/78505cc2-105c-11e6-83a2-29c15dbb3728.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14959849/3fa30768-105b-11e6-89af-3526a10e9a00.png)

Emulador Pantalla Derecha

![s6 6 0](https://cloud.githubusercontent.com/assets/18584168/14959868/640b9642-105b-11e6-9325-a7c735dfb9ac.png)

**Comment by AdryCanonico** [comment]
@nindriago @acostarodrigo

**Comment by nindriago** [comment]
Esto no podemos manejarlo nosotros, ya esto es un problema general de todo fermat en el manejo de las imagenes que esta buscando como mejorar las imagenes

**Comment by MaviDavsa** [comment]
Genial, pero se dejan por aqui hasta que se puedan solucionar...

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa en la version 2 cuando subes una foto al perfil no se ve borroso. Se puede cerrar el caso.

Se sugiere cambiar la foto predeterminada mas amigable para el usuario.

![drawer redee](https://cloud.githubusercontent.com/assets/18584168/15561560/17272a1c-22c1-11e6-92f2-7ed14f7c1a1b.png)
