### ISSUE TITLE
DAP- Asset Iusser - Foto drawer Borroso

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#221]
##### Reporte de error: 

   *Se ve borroso la foto que identifica la Asset Iusser en el Drawer. 

![captura de pantalla 204](https://cloud.githubusercontent.com/assets/18584168/14960248/9bd9d96a-105d-11e6-9dec-f906e8b1476e.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14959849/3fa30768-105b-11e6-89af-3526a10e9a00.png)

Emulador Pantalla Derecha

![s6 6 0](https://cloud.githubusercontent.com/assets/18584168/14959868/640b9642-105b-11e6-9325-a7c735dfb9ac.png)

**Comment by AdryCanonico** [comment]
@nindriago @acostarodrigo

**Comment by nindriago** [comment]
Esto no podemos manejarlo nosotros, ya esto es un problema general de todo fermat en el manejo de las imagenes que esta buscando como mejorar las imagenes

**Comment by MaviDavsa** [comment]
Genial, pero se dejan por aqui hasta que se puedan solucionar...

**Comment by acostarodrigo** [comment]
Esto es general de toda la plataforma y lo va a corregir la gente de android.
Adjunto imagen en la bitcoin wallet y lo mismo ocurre con todas.

![image](https://cloud.githubusercontent.com/assets/9518556/14991010/c8c8363c-1135-11e6-865a-fcb1ba42ea74.png)

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa en la version 2 cuando subes una foto al perfil no se ve borroso. Se puede cerrar el caso. 

Se sugiere cambiar la foto predeterminada mas amigable para el usuario. 


![foto issuer](https://cloud.githubusercontent.com/assets/18584168/15561126/7cfeb4ae-22bc-11e6-864c-8a0be79554a1.png)
