### ISSUE TITLE
Communities - (X) Para cerrar no funciona

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#222]
### Communities

-----

##### Reporte de error: 

   * La (X) Para cerrar o salir de la Communities no funciona.

![captura de pantalla 206](https://cloud.githubusercontent.com/assets/18584168/14960426/640890ac-105e-11e6-9f4b-b4c4f490e044.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Pantalla Izquierda

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14959849/3fa30768-105b-11e6-89af-3526a10e9a00.png)

Emulador Pantalla Derecha

![s6 6 0](https://cloud.githubusercontent.com/assets/18584168/14959868/640b9642-105b-11e6-9325-a7c735dfb9ac.png)

**Comment by AdryCanonico** [comment]
@nindriago @acostarodrigo

**Comment by nindriago** [comment]
Esto no es un problema de DAP, esa vista de todas las communities ya fue renovada y actualmente funciona muy bien.

por favor, cerrar este issue

**Comment by MaviDavsa** [comment]
@AdryCanonico Está solucionado!?

**Comment by MaviDavsa** [comment]
@nattyco Okay natty! Aquí está un error de la Community pero lo encontramos en el APK de la DAP... No se si es valido que lo veamos a ver que ocurre...

**Comment by nindriago** [comment]
Corregido en nuevo APK por favor revisar...

**Comment by AdryCanonico** [comment]
En la prueba de anoche ya la (X) funciona. 
@MaviDavsa  plz, podrías cerrar el caso?
