### ISSUE TITLE
DAP - Bitcoin Wallet - error al pedir btc

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#224]
##### Reporte de error: 

se paralizo mientras esperaba los btc

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/14972311/53c47850-10a4-11e6-97da-673ce95919fa.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/14972326/9935b8e0-10a4-11e6-9dec-e81264aee7df.png)

**Comment by andreagmarcano** [comment]
@nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco Okay natty! Aquí está un error de la Wallet pero lo encontramos en el APK de la DAP... No se si es valido que lo veamos a ver que ocurre...

**Comment by AdryCanonico** [comment]
@MaviDavsa  en la versión 2 de Dap no ocurre este error.
