### ISSUE TITLE
DAP - ASSET FACTORY- Banner Welcome 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#225]
### DAP 

-----

##### Reporte de error: 

   **El banner de dialogo: Asset Factory se ve comprimido y no se aprecia bien: pero esto ocurre cuando se abre la aplicación por primera vez. 

![captura de pantalla 212](https://cloud.githubusercontent.com/assets/18584168/14987163/afc95534-1118-11e6-96ac-b025c038e675.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14987135/9b917902-1118-11e6-9416-201e6a59ee7e.png)

**Comment by AdryCanonico** [comment]
@nerio @acostarodrigo

**Comment by nindriago** [comment]
Buenos dias, ya eso no es un problema como tal de DAP, eso es un problema de la Imagen como tal y de las dimensiones del Equipo donde se realizo la prueba

**Comment by MaviDavsa** [comment]
@nindriago Pero no es a ella sola que le pase... En lineas generales debería ser un problema gráfico que no salga nítido en todos los tlf! :)

**Comment by AdryCanonico** [comment]
@nindriago Aun en la version 2. sigue presentando el error.

**Comment by nindriago** [comment]
Revisar en nueva version de APK

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa En la versión 3 se corrigió el banner. Se puede cerrar el caso.

Dispositivo Nexus 7

![banner factory](https://cloud.githubusercontent.com/assets/18584168/15675129/30f8bb52-270a-11e6-85d4-2317b2c98cde.png)
