### ISSUE TITLE
DAP - ASSET FACTORY- DRAFT ASSET

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#226]
### DAP 

-----

##### Reporte de error: 

   *Al momento de colocar una alta suma de BTC se montan los decimales arriba del texto. 

![captura de pantalla 209](https://cloud.githubusercontent.com/assets/18584168/14988420/84728aea-111d-11e6-9c4f-f9acf3cee2a4.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/14987135/9b917902-1118-11e6-9416-201e6a59ee7e.png)

**Comment by AdryCanonico** [comment]
@nindriago @acostarodrigo

**Comment by nindriago** [comment]
Corregido en nuevo APK por favor revisar...

**Comment by AdryCanonico** [comment]
@MaviDavsa  En la prueba de hoy se ve solucionado el error.

![captura de pantalla 221](https://cloud.githubusercontent.com/assets/18584168/15018160/46f8a99a-11e2-11e6-8805-d5b079999362.png)
