### ISSUE TITLE
DAP - Asset Factory 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#229]
##### Reporte de error: 

Cuando Cambio la cantidad y los paso a bitcoin y lo guardo y entro a editarlo y cambia el monto y los btc a satoshi 

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/15034275/a69ffda2-123d-11e6-9948-49fbe03d47c7.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/15034390/f7db9ac2-123e-11e6-8f41-6080ca67d2bf.png)

**Comment by MaviDavsa** [comment]
@nindriago  @acostarodrigo

**Comment by nindriago** [comment]
no comprendo el error aca?

**Comment by MaviDavsa** [comment]
Okay, el error es que ella hace su Asset y lo guarda, fino... Ahora cuando va y lo edita todo el monto que había puesto en btc es diferente al que ella había dejado y el terminal ella lo había dejado en BTC y ahora le aparecía SATOSHI... Es un error el hecho que no guarde los montos que ella ya había puesto

**Comment by nindriago** [comment]
mmmm, no puede considerarse error ya que cuando se vuelve abrir el ccomponente muestra en SATOSHI la misma cantidad estipulada en BTC y se puede apreciar en la cantidad previsualida en azul en la linea de abajo

**Comment by MaviDavsa** [comment]
mmmm esa no es la cantidad que ella dejo nerio... La app le cambia la cantidad y los términos (de btc a satoshi) cuando lo edita y no debería hacer eso... ella ya había puesto una cantidad en btc.

**Comment by nindriago** [comment]
la cantidad previsualizada en azul te muestra la cantidad real de lo que estas escribiendo en el campo ese, y 1 BTC = 100000000 SATOSHI ya que SATOSHI es la expresion minima del BTC

**Comment by MaviDavsa** [comment]
Entonces como te comentamos esto lo dejamos como Experiencia de Usuario...

**Comment by nindriago** [comment]
Revisar en nueva version de APK

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa En la versión 3 se mantiene la moneda salvada al editar el cupón.

Dispositivo Nexus 7

![cambio de moneda](https://cloud.githubusercontent.com/assets/18584168/15675220/a2a5a526-270a-11e6-9d83-732309ea623c.png)
