### ISSUE TITLE
Community - Error en Notificaciones

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#230]
### Community 

-----

##### Reporte de error: 

   *Da la alerta de notificación en el drawer pero no se visualiza en la ventana de Notifications.

![captura de pantalla 226](https://cloud.githubusercontent.com/assets/18584168/15034273/9fad6002-123d-11e6-975e-317f21d10a70.png)
![captura de pantalla 227](https://cloud.githubusercontent.com/assets/18584168/15034274/9fb3369e-123d-11e6-8c01-4d8ec396b799.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15034439/985dfa6c-123f-11e6-9bb2-a27e25cf2006.png)
id:

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  esta comunity no es mia Digital Assets- Asset User

**Comment by MaviDavsa** [comment]
@nindriago Aunque esta issues es viejo! En lo que comencemos el tester con la DAP, te digo si se mantiene o no!
