### ISSUE TITLE
DAP_Error al acceder a la Wallet Factory

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#232]
##### Reporte de error: 

   Después de que me llegaron los btc, me diriji a la Wallet Factory para seguir con las pruebas y al darle al botón inmediatamente la pantalla se colocó en negro y arrojó un error. Cerré la App de Fermat y volví a ingresar, repitiendo el proceso varias veces y sucedía lo mismo. Por lo que no pude ingresar en ningún momento a la Wallet Factory.

![screenshot_2016-05-05-11-44-18](https://cloud.githubusercontent.com/assets/17261437/15048976/b69270a0-12b5-11e6-87b1-e951c7b3dc96.png)

![screenshot_2016-05-05-11-44-21](https://cloud.githubusercontent.com/assets/17261437/15048984/c7ee2c22-12b5-11e6-8366-31f7a678960e.png)

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-05-05-11-57-12](https://cloud.githubusercontent.com/assets/17261437/15048766/b10cab38-12b4-11e6-97e3-22761c880d67.png)

**Comment by MaviDavsa** [comment]
@acostarodrigo @nindriago

**Comment by nindriago** [comment]
fue un equipo fisico verdad?

**Comment by MaviDavsa** [comment]
Si...

**Comment by nindriago** [comment]
mmmmm deja ver como podemos probar esto, ya que no hay Emulador de ningún Moto G o E, solo hay Moto X veré como funciona allí al menos...

**Comment by MaviDavsa** [comment]
okay!

**Comment by nindriago** [comment]
@MaviDavsa @gablup puedes realizar la prueba nuevamente desinstalando la App y volviendo a instalarla?

**Comment by sanro14** [comment]
@MaviDavsa @nindriago lo que pasa es que @gablup estaba entrando a la wallet factory no a la asset factory, por eso es el error.

**Comment by nindriago** [comment]
mmmmm ok. entiendo

**Comment by gablup** [comment]
Chevere!
