### ISSUE TITLE
Assert Factory- error en la pantalla al pisar signo más

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#233]
#### Nombre pantalla

Asset Factory

   *Estando en la pantalla de Asset Factory, cree un cupón para fabi y cuando quise pisar el botón del más para hacer otro cupón me salio un error. Pise retroceso, pise home y volvi a pisar nuevamente, salio el error nuevamente. Sali de la Asset factory.
![eror al queren hacer un nuevo draft](https://cloud.githubusercontent.com/assets/17283358/15060841/5f4aec9e-12f8-11e6-8eff-42375dbf831c.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
* Modelo:
Samsung Galaxy 6
* Version de Android:
5.1.0 API 22

**Comment by MaviDavsa** [comment]
@nindriago

**Comment by nindriago** [comment]
por favor, aclarar mas, porque no se entiende

**Comment by yolandayancel** [comment]
@nindriago 
Buenos días
Prueba 25-05-16
Caso 233-Resuelto
Al crear el segundo cupón lo realiza sin problemas
![resuelto caso 233](https://cloud.githubusercontent.com/assets/17283358/15539082/2ced6194-224a-11e6-8039-7c790d60532b.png)
