### ISSUE TITLE
DAP-Asset-Issuer-Asset Detail-Error

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#234]
#### Nombre pantalla
Asset Detail

### Asset Issuer

-----

##### Reporte de error: 
Al dar clic en la opción Delivery Asset del menú superior derecho salio el error "Oooops! recovering from system error" como se puede observar en la siguiente pantalla:
![captura de pantalla 2016-05-05 20 36 40](https://cloud.githubusercontent.com/assets/5313326/15061672/c4eac520-1301-11e6-8364-435a18c33d79.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nindriago

**Comment by AdryCanonico** [comment]
@MaviDavsa @nindriago en la version 2, en mi emulador no presenta este error

**Comment by arosiopr** [comment]
@MaviDavsa corregido se puede cerrar
