### ISSUE TITLE
DAP-Asset-Issuer-Asset Detail-Error

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#235]
### Asset Issuer

-----

##### Asset Detail
Al ingresar en la sección de Asset Detail en la parte inferior TRANSACTIONS sale en los usuarios como si el asset estuviese confirmado, y no es así. También dice PENDING, salen ambos estados a la vez, y se envio un solo asset a cada una. A las user no les llego nunca los assets a pesar de que en mi aplicación sale que ha sido confirmado.

![captura de pantalla 2016-05-06 11 25 29](https://cloud.githubusercontent.com/assets/5313326/15078109/6f037272-137b-11e6-9543-83c65f63b2e3.png)

  
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nindriago

**Comment by nindriago** [comment]
si entiendo bien lo que se explico allá arriba, la confirmación que sale allí es un Rollback del Asset osea un retorno del Asset que intento enviarse, pero no se pudo enviar, los PENDING claramente indican que los Assets están en proceso de envío, en lo que se logra apreciar allí no dice en ningún lado que el Asset se Entrego al User Satisfactoriamente aun...

**Comment by sanro14** [comment]
@nindriago cuando el estado del envió de assets le sale al issue "Confirmado" es porque ya salio el assets, por lo tanto debería llegarle al USSER, cosa que no sucedio en esa transacción, a issue se le descontó de su monedero la cantidad de cupones que envió y eso jamas llego al user, en el caso que exista un retorno del asset no debería descontarse y el estado debería mantenerse en pending..

**Comment by nindriago** [comment]
no veo nada de lo que me dices en las imagenes del Issue... 

Esta mal creado este issue con esa explicacion que estas dando...

Las Confirmaciones que se ven alli en ese Detail son de un envio de Asset que no se realizo satisfactoriamente...

**Comment by sanro14** [comment]
los envios que salen en verde nunca llegaron al user y se las descontaron al issue.. @nindriago

**Comment by nindriago** [comment]
Lamentablemente no hay ninguna forma de probar en eso que dices con lo que dice en la Imagen, como te comente, las transactions que salen en Verde alli Dicen que fueron Rollback por lo tanto esos asset NO LLEGARON al User ya que esos asset no salieron del Equipo del Issuer, dice que fue CONFIRMED porque el Asset Regreso al Issuer Satisfactoriamente, en esa imagen no se puede comprobar lo que dices, en esa imagen no hay ningun error visible, ya que dice que que los Assets que fueron enviados a los User (fabi, Rosana, Adry User) se Rollbackearon bien en el Issuer y ademas que esta PENDING 3 envios a los 3 Users nuevamente

**Comment by sanro14** [comment]
En el hipotético caso de que haya rebotado el envió, a Adriana se le tenia que reembolsar el dinero cosa que no sucedió, ella envió el asset y se le veia reflejado con éxito , pero al USER nunca le llego...no se si me explico @nindriago

**Comment by nindriago** [comment]
pues no se entiende lo que dices y en la imagen no sale reflejada tal cosa @sanro14

**Comment by sanro14** [comment]
Ah ok, Adriana acaba de revisar en los assets disponibles, y tiene 4 disponibles y 1 pendiente, perfecto.

**Comment by arosiopr** [comment]
@MaviDavsa reabrir por favor ahora sale que llego el Asset al contacto y no es así.

![cupones pendientes](https://cloud.githubusercontent.com/assets/5313326/15676527/5b56a05c-2710-11e6-992f-47644eeaaa95.png)

**Dispositivo de donde se realizó la prueba:**
![nexus 7](https://cloud.githubusercontent.com/assets/5313326/15676742/49c17870-2711-11e6-9958-b5b65f9a63a1.png)

**Comment by nindriago** [comment]
Falso, favor leer bien, dice alli Rollback, eso significa que el asset no salio del dispositivo y hubo problemas en el envio

**Comment by arosiopr** [comment]
ah si perdón no había visto el rollback
