### ISSUE TITLE
Communities - ASSET USER - Error al entrar en la ficha de contacto

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#236]
##### Reporte de error: 

   *Al querer entrar a la ficha del contacto da este error y no lo permite. Reinicie la apk 3 veces para poder acceder.
   
![captura de pantalla 239](https://cloud.githubusercontent.com/assets/18584168/15078545/80676cce-137d-11e6-8392-b409e237a1dc.png)
![captura de pantalla 240](https://cloud.githubusercontent.com/assets/18584168/15078546/806efdf4-137d-11e6-99bf-8c5cd1d37a50.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15078614/d228b194-137d-11e6-8857-7e6148792ee3.png)

**Comment by MaviDavsa** [comment]
@nindriago

**Comment by AdryCanonico** [comment]
@MaviDavsa  Ya este error no se presenta. Se puede cerrar el caso
