### ISSUE TITLE
DAP_Error en My Assets, pantalla del setting

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#237]
#### Nombre pantalla
Notificaciones

##### Reporte de error: 

Al entrar en notificaciones del Setting de my Assets, hago click al phone notificacions y lo activo, pero al salir e ingresar nuevamente se desactiva. Hice la prueba tres veces y siempre que ingreso esta desactivado.
![error al ingresar en setting en notificaciones](https://cloud.githubusercontent.com/assets/17283358/15080821/ab613890-1389-11e6-9666-c828e562647e.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:
GENYMOTION
* Modelo:
Nexus 5
* Version de Android:
5.1.0
![nexus 5](https://cloud.githubusercontent.com/assets/17283358/15080914/1312e02e-138a-11e6-845b-63436d5bf844.png)

**Comment by MaviDavsa** [comment]
@nindriago

**Comment by yolandayancel** [comment]
@nindriago 
Buenos días
Prueba 25-05-2016
Caso 237- Resuelto
Al ingresar en las notificaciones, esta se pueden activar y desactivar.
![caso 237-resuelto](https://cloud.githubusercontent.com/assets/17283358/15538560/ce0330bc-2246-11e6-9c29-cd42e324c1f8.png)
