### ISSUE TITLE
Error en la Asset Factory

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#238]
##### Reporte de error: 

Cuando presiono el cupón y le doy a la opción de "Publish", dice que mi fondo de bitcoins es insuficiente, a pesar de que en la Bitcoin Wallet aparece mi saldo actual correctamente.
   
![screenshot_2016-05-09-16-30-16](https://cloud.githubusercontent.com/assets/17261437/15131162/83e04f8c-1617-11e6-9c8f-a082a89cadf7.png)

![screenshot_2016-05-09-18-38-07](https://cloud.githubusercontent.com/assets/17261437/15131190/c2005c80-1617-11e6-8570-f6ddcede7523.png)

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-04-14-21-52-35](https://cloud.githubusercontent.com/assets/17261437/15131150/65f15930-1617-11e6-83cd-6f899a5733b4.png)

**Comment by MaviDavsa** [comment]
@nindriago

**Comment by AdryCanonico** [comment]
@MaviDavsa @nindriago En la versión 2, en mi emulador se corrigió este error.
