### ISSUE TITLE
CBP- CASH WALLET - ERROR EN LA FECHA DE EMICION DE LAS TRANSACCIONES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#239]
### CBP

-----

##### Reporte de error: 

   *Al momento de visualizar los datos de la transacción cambia la fecha de cuando se hizo, en la ficha.  
   

![captura de pantalla 264](https://cloud.githubusercontent.com/assets/18584168/15147054/549e6936-1688-11e6-949e-8aeb2132c3f0.png)
![captura de pantalla 265](https://cloud.githubusercontent.com/assets/18584168/15147055/54a70bea-1688-11e6-8bd3-223e96fec825.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15147076/71d7bdea-1688-11e6-801d-5804cf5881b8.png)

**Comment by MaviDavsa** [comment]
@nelsonalfo Trate de etiquetar a Alejandro pero no me dejo!

**Comment by abicelis** [comment]
Prueba. Se vera este comentario?

**Comment by MaviDavsa** [comment]
Si @abicelis

**Comment by abicelis** [comment]
Listo el fix. Cuando este el apk disponible para ustedes les avisare por aca.

**Comment by abicelis** [comment]
Fix aqui @AdryCanonico: https://www.dropbox.com/s/kngajw4mlfhsyq9/fermat_cbp_v3.apk?dl=0

Cualquier cosa avisame

**Comment by MaviDavsa** [comment]
@abicelis Esa es una nueva apk?

**Comment by AdryCanonico** [comment]
@MaviDavsa  @abicelis 

Listo! Arreglado el error! También da el tiempo transcurrido de cuando se hizo el deposito! 

![captura de pantalla 311](https://cloud.githubusercontent.com/assets/18584168/15186990/0b55e5d8-1769-11e6-8c0e-e98e9f2ebd36.png)
