### ISSUE TITLE
CBP-Bank Wallet-  Error en hora al desplegar detalles de la transacción 

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#240]
### CBP

-----

##### Reporte de error: 

   *Al momento de realizar la transacción y consultar los detalles la hora no coincide con la hora en que fue realizada

![imagen1](https://cloud.githubusercontent.com/assets/19142276/15147373/6d24ef4c-168e-11e6-8c33-b8c385ce524f.jpg)

 

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Emulador

![imagen2](https://cloud.githubusercontent.com/assets/19142276/15147575/4f30ac1e-168f-11e6-94ae-63588a6a2411.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by nelsonalfo** [comment]
@abicelis

**Comment by abicelis** [comment]
Listo el fix. Cuando este el apk disponible para ustedes les avisare por aca.

**Comment by abicelis** [comment]
Fix aqui @IsbetVR : https://www.dropbox.com/s/kngajw4mlfhsyq9/fermat_cbp_v3.apk?dl=0

Cualquier cosa avisame!

**Comment by IsbetVR** [comment]
@abicelis 

Solucionado el error. Se probó en dos emuladores y lleva actualizado el tiempo en que fue realizada la transacción en la cuenta

### Pantalla 1
![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/15190052/e908adf4-177b-11e6-8dfe-5eddfbfe938e.jpg)

#### Pantalla 2
![screenshot_2](https://cloud.githubusercontent.com/assets/19142276/15190069/fabf575a-177b-11e6-9346-bb45a1168324.jpg)

Revisé al rato, y si lleva el tiempo actualizado.

#### Pantalla 3 
![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/15190126/4df27088-177c-11e6-9f5e-8f1c33f6e048.jpg)

#### Pantalla 4
![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/15190137/57786d6a-177c-11e6-9237-3390db5d4604.jpg)


Fue probado en:
Google Nexus 4 Versión android 5.0.0 (pantalla 1 y 2) y 
Google Nexus 5 versión android 5.1.0 (pantalla 3 y 4)

**Comment by IsbetVR** [comment]
@MaviDavsa Listo, ya no ocurre el error. En el comentario anterior está la demostración con dos emuladores
