### ISSUE TITLE
Cash Wallet- error al hacer retiro 

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#241]
### Template issue error report

CBP
#### Nombre pantalla

Cash Wallet-Withdrawal

##### Reporte de error: 

   *Estando en la pantalla de la cash wallet y al pisar el signo más para hacer un retiro, se queda cargando por más de tres minutos hasta que te tengo que clickear para editar, al decirle que se borre el retiro, este no lo borra y lo descuenta de la cash wallet balance como lo muestro en las tres fotos que adjunto:

![cash wallet-withdrawal 1](https://cloud.githubusercontent.com/assets/17283358/15148016/4a075690-168d-11e6-9a7c-12b484fbe4b6.png)
![cash wallet-withdrawal 2](https://cloud.githubusercontent.com/assets/17283358/15148023/4ff54f12-168d-11e6-80a1-d174b4f7c048.png)
![cash wallet-withdrawal 3](https://cloud.githubusercontent.com/assets/17283358/15148028/549ccae0-168d-11e6-8c19-66221cff1420.png)

   

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotio
* Modelo:
Emulador

![emulador -nexus 5](https://cloud.githubusercontent.com/assets/17283358/15148212/137c8e5a-168e-11e6-9680-1615f5762e32.png)

**Comment by yolandayancel** [comment]
@nelsonalfo

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@yolandayancel intente e intente y no pude replicar este bug. Cuando haya chance nos reuniremos y me muestras como haces para realizarlo!

**Comment by yolandayancel** [comment]
Buenos días Alejandro

Te explico:
Cuando quiero hacer un retiro clikeo en el withdraw y comienza a cargar
(esto debería tardar creo que pocos segundos) pero se queda pegada allí
como cargando por más de dos minutos hasta que interrumpo.  le piso DELETE,
para borrar esa transacción y al ver el balance desconto el dinero a pesar
de que anule el retiro. Dos cosas se pueden observar de este caso:
1 se queda pegada cuando le ordenas hacer retiro
2 Al borrar un retiro en proceso no lo anula.

Avisame para si hacemos videollamada
Saludos

2016-05-10 22:05 GMT-04:30 Alejandro Bicelis <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> intente e intente y no
> pude replicar este bug. Cuando haya chance nos reuniremos y me muestras
> como haces para realizarlo!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/241#issuecomment-218346880>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
@abicelis 
Buenas noches Alejandro

Error corregido.
Prueba 12-05-16 07:50pm
El error no se repitió, le hice un retiro y a los pocos segundos lo hizo.
![se corrigio el error](https://cloud.githubusercontent.com/assets/17283358/15234011/0fde1422-1877-11e6-83d3-21f12242dbc6.png)

**Comment by abicelis** [comment]
Buenísimo @yolandayancel
