### ISSUE TITLE
BAKING WALLET- ERROR DUPLICADO DE FICHA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#242]
### CBP

-----

##### Reporte de error: 

   *Realice un deposito y cuando empezó a cargar, la ficha se duplico con un deposito y un retiro (El retiro no fue echo) dando el error. 

![captura de pantalla 267](https://cloud.githubusercontent.com/assets/18584168/15148533/67f4be5c-168f-11e6-812c-82d4fae9a6ab.png)

Duro así 16 minutos y para poder cargar el deposito, tuve que cerrar la aplicación y volver a entrar. 

![captura de pantalla 269](https://cloud.githubusercontent.com/assets/18584168/15148575/a45aec36-168f-11e6-83a0-42f4487be8f4.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15148591/b43b2904-168f-11e6-93b9-db2fa1d30caa.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico Intenta replicar esto con la version v6 del app que la tiene @MaviDavsa, presiento que el error fue por lo lenta que estaba el app, esta version tiene mejoras en la velocidad del UI, que deberia ser fluido.

Si logras replicarlo con la nueva version, nos reunimos en un hangout para estudiar mas este error.

**Comment by AdryCanonico** [comment]
@abicelis  Sigue apareciendo el error cargando el deposito y esta super lenta. No se ha concretado el deposito.

![captura de pantalla 360](https://cloud.githubusercontent.com/assets/18584168/15251788/d66410c4-18f4-11e6-90c6-9f13e3c8dad5.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)


Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by abicelis** [comment]
@AdryCanonico prueba esto en la version v9 plz!

**Comment by AdryCanonico** [comment]
@MaviDavsa  @abicelis  en la V9 se corrigió este error. se puede cerrar

![captura de pantalla 431](https://cloud.githubusercontent.com/assets/18584168/15413081/e61ea266-1df6-11e6-9471-cca102ed60a0.png)
