### ISSUE TITLE
BAKING WALLET- NO SE PUEDE BORRAR LAS CUENTAS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#243]
### CBP 

-----

##### Reporte de error: 

   *Seria bueno poder borrar o editar la cuenta agregada al Bank Wallet
   

![captura de pantalla 271](https://cloud.githubusercontent.com/assets/18584168/15148865/24819fee-1691-11e6-9a70-f42cad639e8e.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15148883/3b7e58a4-1691-11e6-97b2-d66d046d74b7.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by nelsonalfo** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico al crear una cuenta no se puede borrar. Esto es asi por diseno, ya que las cuentas en bank (y cash) estan ligadas con otros componentes en cbp (broker o customer wallet).
Lo que si se puede hacer es habilitar la edicion de la cuenta una vez creada (Poder cambiar el alias, el numero de cuenta y la imagen asociada), no se podra cambiar ni la moneda de la cuenta ni editar las transacciones hechas en ella.

v7 tendra este cambio, lo implemento y aviso por aca cuando este disponible para ser probado.

**Comment by abicelis** [comment]
@AdryCanonico  La version v7 la tendra @MaviDavsa prontamente, para probar la edicion de accounts (Poder cambiar el alias, el numero de cuenta y la imagen asociada)

**Comment by AdryCanonico** [comment]
@MaviDavsa En la version 7, ya se puede apreciar la edición de las cuentas. Se puede cerrar el caso.

![captura de pantalla 390](https://cloud.githubusercontent.com/assets/18584168/15323002/97840a68-1c09-11e6-97d4-acba60b31003.png)
![captura de pantalla 391](https://cloud.githubusercontent.com/assets/18584168/15323003/978785a8-1c09-11e6-89b4-f076e5a29c34.png)
