### ISSUE TITLE
Bank Wallet-Account Detail

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#244]
### Bank Wallet

-----

##### Reporte de error: 
Inicialmente cree una cuenta, realice un deposito por 50.

![captura de pantalla 2016-05-10 09 19 13](https://cloud.githubusercontent.com/assets/5313326/15148640/ff454178-168f-11e6-83e7-ea3b2bb8fd15.png)

luego entre a editarlo y al darle atrás sin guardar ni nada automáticamente me creo un retiro por el mismo monto.

![captura de pantalla 2016-05-10 09 37 54](https://cloud.githubusercontent.com/assets/5313326/15148698/399be39a-1690-11e6-9b5e-b5a5822545e0.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: GENYMOTION
* Modelo: GOOGLE NEXUS 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by arosiopr** [comment]
@MaviDavsa corregido en versión 6

**Comment by MaviDavsa** [comment]
Solucionado!
