### ISSUE TITLE
CBP- CASH WALLET - ERROR, BOTON DE WITHDRAWAL NO VISIBLE PERO TIENE FUNCION

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#245]
### CBP

-----

##### Reporte de error: 

   *En la pantalla de Home, en la Cash Wallet no se visualiza el boton de Withdrawl 

![captura de pantalla 282](https://cloud.githubusercontent.com/assets/18584168/15150462/19e1e7a0-1697-11e6-929f-ab575fe69397.png)

pero si se toca donde debería estar el boton (No se visualiza) emerge la ventana de Withdrawal

![captura de pantalla 281](https://cloud.githubusercontent.com/assets/18584168/15150492/38df741a-1697-11e6-8ecd-235a922603f3.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15150524/624bb368-1697-11e6-9d06-3bf0dd210a64.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by IsbetVR** [comment]
Sucedió lo mismo en otro teléfono de prueba, 

![imagen4](https://cloud.githubusercontent.com/assets/19142276/15153047/b6121a42-16a5-11e6-8b92-d2ad6e6c6cbe.jpg)

**Comment by abicelis** [comment]
Listo.
Fix aqui @AdryCanonico e @IsbetVR: https://www.dropbox.com/s/wlmig36w7mvwrkt/fermat_cbp_v4.apk?dl=0

Cualquier cosa avisame

**Comment by AdryCanonico** [comment]
@MaviDavsa  @abicelis 

Listo! Ya no ocurre el error.


![captura de pantalla 309](https://cloud.githubusercontent.com/assets/18584168/15186665/b345ece0-1767-11e6-88f2-4f835ceeb5a3.png)
