### ISSUE TITLE
Bank Wallet- error al crear una cuenta

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#246]
### Template issue error report

CBP
#### Nombre pantalla
Bank Wallet

######## Reporte de error:  
Estando en Bank Wallet y al crear una cuenta ( esta se creo bien) pero al intante de crearse  aparecio un banner de bienvenida que al hacer click en close aparecio un recuadro (Fermat isnt responding) le hice click en wait y espero como un minuto. Clickee el banner nuevamente y aparecio el recuadro nuevamente, pise ok y se salio de la CBP

![error en bank se congelo 1](https://cloud.githubusercontent.com/assets/17283358/15150474/259aa0c8-1697-11e6-8dea-bd0231c2be7c.png)
![error en bank se congelo 2](https://cloud.githubusercontent.com/assets/17283358/15150482/2c087f52-1697-11e6-9aec-e497ea8e3098.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
* Modelo:
Emulador
![emulador -nexus 5](https://cloud.githubusercontent.com/assets/17283358/15150513/54c08f3e-1697-11e6-9ae4-810b76751d11.png)

**Comment by yolandayancel** [comment]
@nelsonalfo

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by alegnaire** [comment]
Mismo error en Samsung Galaxy S6 6.0.0

**Comment by yolandayancel** [comment]
@abicelis
Alejandro, 
En prueba de fecha 12-05-16
Error reportado 246: ahora se puede crear las cuenta de manera muy lenta, aparece el recuadros (Fermat,s Isnt respond) pero al pisar wait no se queda congelada permite seguir crando otras cuentas.
![prueba del error 246](https://cloud.githubusercontent.com/assets/17283358/15217173/206bcee0-1824-11e6-8f72-56b6d54a2c98.png)

**Comment by yolandayancel** [comment]
@abicelis
Buenas noches Alejandro

Error corregido
Estando en Bank Wallet cree  una cuenta ( esta se creo bien) no aparecio el recuadro (Fermat isnt responding).

![error corregido](https://cloud.githubusercontent.com/assets/17283358/15234139/59a31278-1878-11e6-948d-7381443cf875.png)

**Comment by abicelis** [comment]
@yolandayancel great
