### ISSUE TITLE
CASH WALLET - TEXTO BOTON DEPOSIT

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#247]
### CBP

-----

##### Reporte de error: 

   *Seria bueno lograr que el texto "Deposit" del botón, se lea con mas claridad. Ya que no se logra apreciar bien.
   

![captura de pantalla 284](https://cloud.githubusercontent.com/assets/18584168/15151066/83cd2bd2-1699-11e6-9037-d35d11c7d48a.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emuador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15150744/4837b21e-1698-11e6-86e1-e5a585922dd1.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by nelsonalfo** [comment]
@abicelis

**Comment by abicelis** [comment]
Listo @Gabymorillo en la version v4 del app. @MaviDavsa la tiene.

**Comment by AdryCanonico** [comment]
Seria bueno algo un poco mas amigable. Todavía se sigue viendo como raro el fondo del texto cuando se visualiza con el fondo de la apk

![captura de pantalla 316](https://cloud.githubusercontent.com/assets/18584168/15215049/3c68a67c-181a-11e6-8f35-bd4a73382fbd.png)

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa La version v7 del app tiene mejoras en los labels de ambas (bank y cash) wallets

**Comment by AdryCanonico** [comment]
@MaviDavsa  En la versión 7, se ve mucho mas amigable el fondo del texto y el tamaño de las letras. También las mejoras de los botones hace que la vista a la aplicación se suavice y sea mas cómodo manejarla.


![captura de pantalla 394](https://cloud.githubusercontent.com/assets/18584168/15323420/c87d9132-1c0b-11e6-9c4e-c89d0e677083.png)

**Comment by abicelis** [comment]
@AdryCanonico great ! :)
