### ISSUE TITLE
CASH WALLET - TEXTO BOTON WITHDRAL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#248]
### CBP

-----

##### Reporte de error: 

   **Seria bueno lograr que el texto "Withdrawal" del botón, se lea con mas claridad. Ya que no se logra apreciar bien.
   

![captura de pantalla 285](https://cloud.githubusercontent.com/assets/18584168/15151029/622baa9e-1699-11e6-86ba-f108c2bbd0fc.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emuador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15150744/4837b21e-1698-11e6-86e1-e5a585922dd1.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by nelsonalfo** [comment]
@abicelis

**Comment by Gabymorillo** [comment]
Botón "deposit" tiene una fuente muy pequeña, que hace muy difícil leerlo.

![capture-20160510-191129](https://cloud.githubusercontent.com/assets/17262077/15165884/4d4af3ec-16e3-11e6-9a52-c9329be8c93a.png)


Modelo:
![capture-20160510-185851](https://cloud.githubusercontent.com/assets/17262077/15165888/50af89b2-16e3-11e6-98ca-327584b9b37f.png)

**Comment by abicelis** [comment]
Listo @AdryCanonico @Gabymorillo en la version v4 del app. @MaviDavsa la tiene.

**Comment by AdryCanonico** [comment]
Seria bueno algo un poco mas amigable. Todavía se sigue viendo como raro el fondo del texto cuando se visualiza con el fondo de la apk


![captura de pantalla 316](https://cloud.githubusercontent.com/assets/18584168/15215064/4af5e3b2-181a-11e6-9d11-e6ed757fe4e2.png)

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa La version v7 del app tiene mejoras en los labels de ambas (bank y cash) wallets

**Comment by AdryCanonico** [comment]
@MaviDavsa  En la versión 7, se ve mucho mas amigable el fondo del texto y el tamaño de las letras. También las mejoras de los botones hace que la vista a la aplicación se suavice y sea mas cómodo manejarla. Se puede cerrar el caso.


![captura de pantalla 394](https://cloud.githubusercontent.com/assets/18584168/15323420/c87d9132-1c0b-11e6-9c4e-c89d0e677083.png)
