### ISSUE TITLE
Bank Wallet- error al ingresar Bank

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#250]
### Template issue error report
CBP

#### Nombre pantalla

Bank Wallet

##### Reporte de error: 

   Después de lo ocurrido en el reporte anterior (se salio de la CBP), ingrese nuevamente en la CBP y cuando ingreso al Bank Wallet, no me permite, aparece un recuadro con el error(Recovering from system error) y se sale de la bank wallet. Ingrese varias veces y ocurrió lo mismo. Me fui a configuración del telefono, abri Fermat  y borre los datos. Ingrese nuevamente a la CBP y me permitió ingresar

![errror no ingresa en bank w 1](https://cloud.githubusercontent.com/assets/17283358/15151740/4ab45bce-169c-11e6-921d-64dafdcf5a2b.png)
![errror no ingresa en bank w 2](https://cloud.githubusercontent.com/assets/17283358/15151749/562dcd6e-169c-11e6-8d07-20e4c6c61dde.png)
![errror no ingresa en bank w 3](https://cloud.githubusercontent.com/assets/17283358/15151756/5d2b6126-169c-11e6-9aa4-d95591ea207b.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
* Modelo:
Emulador

![emulador -nexus 5](https://cloud.githubusercontent.com/assets/17283358/15151784/770a00f2-169c-11e6-88bb-89769ffc6e08.png)

**Comment by yolandayancel** [comment]
@abicelis

**Comment by alegnaire** [comment]
En Samsung Galaxy S6 6.0.0 emite el mensaje de error "Fermat isn't responding", ocurrió las dos primeras veces que se intento accesar a la aplicación, finalmente se logro accesar, cerrando la aplicación FERMAT e iniciando nuevamente.

**Comment by IsbetVR** [comment]
Ocurre el mismo error en Samsung Galaxy S6 versión 5.0.0, reinicio la apk, nuevamente sale el mismo error

![versionsamsung](https://cloud.githubusercontent.com/assets/19142276/15166180/4fa17d6c-16ea-11e6-9fe5-653c5e295655.jpg)


![errorgalaxy](https://cloud.githubusercontent.com/assets/19142276/15166183/58ecea6e-16ea-11e6-9245-e97ea676476d.jpg)

**Comment by camilavaleria** [comment]
buenas noches en el modelo nexus 5.51.0 ocurre lo mismo,emite el mensaje de error "recovering from system error despues de hacer depósitos y retiros.. no abrió mas,se cerro y abrio nuevamente la aplicación fermat y no aparece nada

**Comment by AdryCanonico** [comment]
El mismo error ocurre.

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15180494/d4c527da-174b-11e6-87cc-dec8a8cab8f1.png)

**Comment by yolandayancel** [comment]
@abicelis

Este error se corrigió, ahora puedo ingresar en la Banking Wallet

**Comment by AdryCanonico** [comment]
Se corrigió el error en el dispositivos

**Comment by IsbetVR** [comment]
Ya no me da el error en el dispositivo

**Comment by yolandayancel** [comment]
@estabilice
Buenas noches Alejandro

Este error ya no ocurrió
