### ISSUE TITLE
Bank Wallet - Error - Muestra el número de cuenta en notación científica

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#251]
##### Reporte de error: 

   *Al crear una cuenta con un número mayor a 10 dígitos, y luego ir a la pantalla donde aparece el listado donde están las demás creadas, el número lo muestra en notación científica. 

A continuación está el detalle de los datos cuando se está creando

![imagen5](https://cloud.githubusercontent.com/assets/19142276/15153554/9fb22646-16a7-11e6-83dd-58ff6e46d0eb.jpg)

Luego de darle "save" e ir atrás para ver el listado de las cuentas, muestra en notación científica el número

![imagen6](https://cloud.githubusercontent.com/assets/19142276/15153619/e20d1c08-16a7-11e6-8b22-fb851265ff90.jpg)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![imagen2](https://cloud.githubusercontent.com/assets/19142276/15153675/19b2b5d2-16a8-11e6-8239-71a5fef098b8.jpg)

**Comment by IsbetVR** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
Tambien en el momento de crear la cuenta permite colocar letras, no solo numeros. 

![captura de pantalla 290](https://cloud.githubusercontent.com/assets/18584168/15180410/49c30c2e-174b-11e6-8efd-a73fd3d3d8d3.png)

**Comment by Gabymorillo** [comment]
Reporte de error:

Al momento de crear una cuenta el número lo muestra en notación científica.

![capture-20160513-111333](https://cloud.githubusercontent.com/assets/17262077/15253755/7a345760-18fd-11e6-8395-17dfc429dc5f.png)
   
modelo donde se reporte: Google Nexus 4 -  5.1

**Comment by abicelis** [comment]
@IsbetVR @AdryCanonico @Gabymorillo @MaviDavsa En la app v7 se corrigio (espero) la bank al mostrar account numbers o aliases en notacion cientifica!
Nota: no me he metido con el available balance, este todavia tiene errores.

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa si, corregido! ya no muestra en notación científica el account number ni el alias. 
Con respecto a los que dice @AdryCanonico efectivamente todavía permite en el alias colocar números, letras y símbolos (Pantalla 1 y 2)

##### Pantalla 1
![image](https://cloud.githubusercontent.com/assets/19142276/15339621/545d2c02-1c53-11e6-9df6-c645fb8e41bb.png)

##### Pantalla 2
![image](https://cloud.githubusercontent.com/assets/19142276/15339716/bef0cb28-1c53-11e6-8277-3af73867b43b.png)


Datos del dispositvo de prueba. 
Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0.0

**Comment by abicelis** [comment]
@isbetVR si, en el alias te dejo ingresar lo que quieras. Que bueno que esta listo!

**Comment by MaviDavsa** [comment]
@abicelis Pero eso del Alias si esta bien cierto? o no debería!?

**Comment by abicelis** [comment]
@mavidavsa si, el alias puede ser cualquier cosa :)

**Comment by MaviDavsa** [comment]
Solucionado entonces!
