### ISSUE TITLE
Bank Wallet - Add Account

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#252]
### CBP

------
##### Reporte de error: 

   * Seria bueno que al momento de agregar una nueva cuenta saliera una opción para agregar una imagen, ya que no la hay como se puede observar:

![captura de pantalla 2016-05-10 13 33 39](https://cloud.githubusercontent.com/assets/5313326/15156869/d70133de-16b2-11e6-89dc-1ef94af5485e.png)

y no que se coloque por defecto como se observa a continuación en la cuenta que acabo de crear que es Adriana Provincial:

![captura de pantalla 2016-05-10 13 34 49](https://cloud.githubusercontent.com/assets/5313326/15156888/f59506e0-16b2-11e6-9fe3-d8b161f4b205.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@arosiopr @MaviDavsa la app v7 tiene mejoras aqui, al crear (o editar!) un account se puede seleccionar una de las fotos predeterminadas que trae el app (que son como 6)

Estoy discutiendo con mi team a ver si esto puede cambiar mas alla de lo que he implementado pues ya me aleje del diseno del app. De traer muchos problemas, estamos considerando eliminar estas imagenes.

**Comment by arosiopr** [comment]
@abicelis @MaviDavsa si permite elegir una de las que estan por defecto
