### ISSUE TITLE
CBP - settings APP filter 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#253]
##### Reporte de error: 

Se queda colgada y cuando vuelvo a entrar no guarda los cambios realizados, de alpha a dev

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/15164145/bf454b08-16d6-11e6-8900-687fe855f85e.png)

* Marca:
* Modelo:
* Version de Android:

![image](https://cloud.githubusercontent.com/assets/18452495/15164203/13ba8f22-16d7-11e6-8970-c94731f77693.png)

**Comment by MaviDavsa** [comment]
@abicelis Esto es algo más para nosotras! Nos puedes hacer el dos de que quede por Defaul en Dev! x.x

**Comment by abicelis** [comment]
@andreagmarcano ese codigo no es parte de nuestra plataforma, eso ya es el android-core. Lo reportare mas abajo a donde corresponde! Puedes cerrar este issue

@MaviDavsa ok, a partir de ahora les pondre a dev por default.

**Comment by abicelis** [comment]
@MaviDavsa @andreagmarcano  A partir de la v6 no tendran que usar el app filter para llegarle a cash o bank, esto sera temporal.

**Comment by MaviDavsa** [comment]
Perfecto Gracias! :) @abicelis

**Comment by AdryCanonico** [comment]
Ya esta solucionado en la version v6

![captura de pantalla 340](https://cloud.githubusercontent.com/assets/18584168/15248119/3265094a-18e2-11e6-8471-3fcdf4e94404.png)
