### ISSUE TITLE
CBP - Wallets - Error en pantalla de inicio al intentar ingresar al Cash Wallet

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#254]
##### Reporte de error: 

   *En el home del wallets al intentar ingresar al "Cash Wallet", sale un recuadro de alerta en la parte inferior de la pantalla del home "Recovering from system error", cierro la apk, vuelvo a ingresar y de igual manera mantiene la alerta al intentar ingresar al cash , cierro el emulador, lo vuelvo a correr y continua la alerta. Cabe destacar que al principio ya había ingresado al "Cash Wallet" e hice un depósito y luego un retiro y funcionó bien, el error empezó a salir luego de haber hecho las transacciones y salir del "Cash Wallet" hacia otras opciones en el home de la aplicación. 

![imagen7](https://cloud.githubusercontent.com/assets/19142276/15166377/2802a004-16ec-11e6-858c-56cdcb3ffcd5.jpg)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Samsung Galaxy S6
* Version de Android: 5.0.0

![versionsamsung](https://cloud.githubusercontent.com/assets/19142276/15166392/53e42616-16ec-11e6-91a7-d237774c43e3.jpg)

**Comment by IsbetVR** [comment]
@abicelis

**Comment by abicelis** [comment]
@IsbetVR estos errores no son especificos de ninguna wallet. Ocurren aleatoriamente con todas las wallets (bitcoin, bank, broker, asset wallets, etc) asi que no tiene que ver directamente con nuestra plataforma.

Cuando tengas chance nos reunimos para replicar el error y luego yo reportarlo mas abajo a la gente que desarrolla el core de fermat!

**Comment by MaviDavsa** [comment]
@abicelis Hasta ahora no ha salido tan repetitivamente...
