### ISSUE TITLE
BAKING WALLET- ERROR AL HACER DEPOSITO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#255]
### CBP

-----

##### Reporte de error: 

   *Realice el deposito en la cuenta creada, mientras cargaba se visualizo un retiro y no un deposito. 

![captura de pantalla 291](https://cloud.githubusercontent.com/assets/18584168/15180606/69d90f08-174c-11e6-913f-7ea1f76535f4.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15180611/75d78df2-174c-11e6-8211-0a974cb9fa58.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico haz pruebas plz a ver si puedes replicar este issue en la version v7 que acabo de sacar!

**Comment by AdryCanonico** [comment]
@abicelis El error persiste en esta versión. 
Ahora se hace un deposito y si entras al detalle del deposito mientras carga se vuelve un retiro.

![captura de pantalla 396](https://cloud.githubusercontent.com/assets/18584168/15324077/ba3516c4-1c0e-11e6-9638-358347394c85.png)
![captura de pantalla 397](https://cloud.githubusercontent.com/assets/18584168/15324078/ba3a01ca-1c0e-11e6-8ecd-049bc69a1007.png)
![captura de pantalla 398](https://cloud.githubusercontent.com/assets/18584168/15324079/ba3d4ccc-1c0e-11e6-806e-9d949de2dc12.png)

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa Super error corregido en la version v8!

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis En la V9 el error persiste. Excelente las funciones de los botones nuevos en la ficha.

![captura de pantalla 433](https://cloud.githubusercontent.com/assets/18584168/15410803/9ed339fa-1de5-11e6-9b72-c68a45f7b755.png)

![captura de pantalla 432](https://cloud.githubusercontent.com/assets/18584168/15410804/9ed8811c-1de5-11e6-9c8a-d53f009c1b51.png)

**Comment by abicelis** [comment]
@AdryCanonico Listo adry, corregido en la version v11!!

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11 se corrigió el error. Se puede cerrar el caso.
