### ISSUE TITLE
BAKING WALLET- ERROR AL HACER DEPOSITO NO APARECE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#256]
### CBP

-----

##### Reporte de error: 

   *Realice un deposito, costo mucho para que cargara y cuando volví a entrar no había registro del deposito.
   

![captura de pantalla 292](https://cloud.githubusercontent.com/assets/18584168/15180867/d85b5e3a-174d-11e6-8f95-0e989bf7e920.png)

------

#### Dispositivo desde donde se realizo la prueba

*Marca:Genymotion
*Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15180879/f23f4f46-174d-11e6-9af4-22ce2b7e71f5.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by Gabymorillo** [comment]
AL hacer deposito no se efectúa.

![capture-20160512-202539](https://cloud.githubusercontent.com/assets/17262077/15234929/d1b0a764-1880-11e6-919d-d6ad540a7aeb.png)


Modelo: Google Nexus 4 -  5.0.0

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa haz pruebas plz a ver si puedes replicar este issue en la version v7 que acabo de sacar!

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa ya no aparece este error en la versión 7, Se puede cerrar el caso
