### ISSUE TITLE
CASH WALLET - MEJORAS EN EL MANEJO DE MONEDA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#257]
### CBP
-----

##### Reporte de error: 

   *Seria bueno poder cambiar la moneda con que se trabaja, ya que solo se visualiza USD. 

![captura de pantalla 293](https://cloud.githubusercontent.com/assets/18584168/15181325/710bbb1e-1750-11e6-86fa-d08377502861.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15181351/850bc4d8-1750-11e6-9845-f7a7ee51826a.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico, la cash wallet tiene una pantalla inical en donde se selecciona la moneda de la wallet. Solo ahi puedes seleccionar con que moneda trabajar.

Esta pantalla:

![image](https://cloud.githubusercontent.com/assets/9850854/15182912/8f7b5700-1758-11e6-8c7c-6c7f752cb2bf.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico A ti te salio esa pantalla? porque a mi no! jajjaaja

**Comment by AdryCanonico** [comment]
@abicelis  aparece en la versión nueva de la apk, en la vieja no aparece, lo hace por defecto. 

Emulador derecho versión vieja
Emulador izquierdo versión nueva

![captura de pantalla 308](https://cloud.githubusercontent.com/assets/18584168/15186381/a2415610-1766-11e6-9bb4-f16d3a758b61.png)

**Comment by AdryCanonico** [comment]
@abicelis Pero de igual manera, si me equivoco al entrar y coloco la moneda que no es, no tengo opción para cambiarla o editar.

**Comment by abicelis** [comment]
Es asi por diseno, no tienes opcion de cambiar la moneda pues ella se integra a otras wallets (broker wallet y customer wallet).

Lo pondre como pendiente en una lista para una futura version, pues para cambiar eso hay tomar en cuenta muchas otras cosas en CBP.

**Comment by abicelis** [comment]
@MaviDavsa puedes cerrar este issue :)
