### ISSUE TITLE
CASH WALLET - ERROR BALANCE MUESTRA LA CANTIDAD EN NOTACION CIENTIFICA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#258]
### CBP

-----

##### Reporte de error: 

   *Produce el error cuando se deposita o retira con decimales con cantidades grandes y muestra en el balance la cantidad en anotación científica. 
   

![captura de pantalla 295](https://cloud.githubusercontent.com/assets/18584168/15183027/26320310-1759-11e6-8e64-074da52a826c.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15183019/16589404-1759-11e6-82a0-a451fffc2a11.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by sanro14** [comment]
@abicelis En el Nexus 4 Android 5.0 sucede exactamente igual
![imagen apollo issue adriana](https://cloud.githubusercontent.com/assets/5313324/15183680/f169b134-175b-11e6-95bf-8f0cae2c6995.png)

**Comment by camilavaleria** [comment]
En el modelo Nexus 5, 5.1.0 android el error que se genera es cuando se deposita o retira con decimales con cantidades grandes y la cantidad sale reflejada en el balance la cantidad en anotación científica.

![screenshot 8](https://cloud.githubusercontent.com/assets/18740418/15232134/00975018-1869-11e6-8464-fd4cb9fdd883.png)

**Comment by AdryCanonico** [comment]
Aun no se soluciona el problema V6

![captura de pantalla 342](https://cloud.githubusercontent.com/assets/18584168/15248439/033fa1f0-18e4-11e6-9896-717d2c659b37.png)


#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)


Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by AdryCanonico** [comment]
@abcelis

**Comment by abicelis** [comment]
@adrycanonico a medida que vaya corrigiendo issues iré comentando en ellos.  Este no lo he tocado

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa la version v7 tiene corregido este error.
Nota: solo la cash, la bank no la he tocado

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa  Se corrigió el error en la versión 7. Se puede cerrar el caso

![Uploading Captura de pantalla (400).png…]()
![Uploading Captura de pantalla (400).png…]()
