### ISSUE TITLE
CBP-error al iniciar la aplicación

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#259]
##### Reporte de error: 

   *Al iniciar la aplicación en los wizard que se muestran al principio, justo en el ultimo se queda pegado. La solución fue limpiar la data dos veces para que funcionara el botón.
![screenshot_1](https://cloud.githubusercontent.com/assets/5313324/15183343/6b7db8dc-175a-11e6-9671-a38bbdb32a1c.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0

**Comment by sanro14** [comment]
@abicelis

**Comment by abicelis** [comment]
@MaviDavsa  @sanro14 Esto no es parte de CBP, no entra en el alcance de nuestro proyecto.

**Comment by abicelis** [comment]
@MaviDavsa @sanro14 creo que hay que cerrar este issue

**Comment by MaviDavsa** [comment]
Creo que esto le incumbe a @nattyco No?

**Comment by abicelis** [comment]
Creo que si, creo que tambien a @furszy.

**Comment by sanro14** [comment]
@MaviDavsa no me ha vuelto a pasar no se si cerrarlo..

**Comment by MaviDavsa** [comment]
@sanro14 Vamos a cerrar si aparece de nuevo lo reabrimos!
