### ISSUE TITLE
BAKING WALLET- ERROR PERMITE RETIRAR CON FONDOS INSUFICIENTES 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#260]
### CBP

-----

##### Reporte de error: 

   *Intentando hacer un retiro mayor del que hay en el balance, me permite hacerlo. No lanza ningún mensaje como :AMOUNT IS LARGER THAN AVAILABLE como lo hace la Cash Wallet. 

![captura de pantalla 297](https://cloud.githubusercontent.com/assets/18584168/15183764/55609c20-175c-11e6-81d8-1f4612a79f92.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15180611/75d78df2-174c-11e6-8211-0a974cb9fa58.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by sanro14** [comment]
@abicelis sucede lo mismo en el Nexus 4 android 5.0 
![image](https://cloud.githubusercontent.com/assets/5313324/15185403/c9260be4-1762-11e6-815e-3a1289e8fe20.png)

**Comment by arosiopr** [comment]
sucede lo mismo en la versión 6 de la aplicación

![captura de pantalla 2016-05-12 18 47 03](https://cloud.githubusercontent.com/assets/5313326/15232886/03614be6-186e-11e6-8d83-b0c4d6f41422.png)

-----------------------------------------------------------------

**Dispositivo desde donde se realizo la prueba**
* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by abicelis** [comment]
@arosiopor, a medida que vaya corrigiendo errores los voy reportando en cada issue.  En v6 no toque nada de aquí.

**Comment by arosiopr** [comment]
@abicelis ok :)

**Comment by abicelis** [comment]
@AdryCanonico @sanro14 @arosiopr @MaviDavsa Corregido en la version v8, la aplicacion no deja retirar mas dinero del que existe en el available balance.

**Comment by arosiopr** [comment]
@MaviDavsa corregido en mi equipo:
* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis En la V9 se corrigio el error. Se puede cerrar el caso.

![captura de pantalla 434](https://cloud.githubusercontent.com/assets/18584168/15411232/5cea6948-1de8-11e6-8a51-54cb27ee645e.png)
