### ISSUE TITLE
Cash Wallet - Error en decimales en cifras grandes, omite decimales

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#261]
#### Cash Wallet - Balance 

-----

##### Reporte de error: 

   *Cuando se intenta depositar cifras con decimales, los omite cuando en el balance hay una cifra grande. En el caso #257 si muestra decimales, allí se manejó un balance de cifras bajas. 

Yo estaba manejando cifras mayores a 100mil y ya no salen decimales, aún así en el resumen de los depósitos si salen los decimales (Pantalla 2)

#### Pantalla 1

![imagen8](https://cloud.githubusercontent.com/assets/19142276/15183396/ed3b678a-175e-11e6-8a05-289f881e692b.jpg)

#### Pantalla 2

![imagen9](https://cloud.githubusercontent.com/assets/19142276/15183404/f5c81de4-175e-11e6-884e-b7964ed8ed4f.jpg)

#### Pantalla 3

![imagen10](https://cloud.githubusercontent.com/assets/19142276/15183408/fabe505c-175e-11e6-9745-1242412f7f47.jpg)

Aparentemente al sobrepasar las cifra de 10mil empieza a omitir los decimales (pantalla 4), antes de llegar a dicha cifra mostraba decimales

#### Pantalla 4

![captura de pantalla 296](https://cloud.githubusercontent.com/assets/19142276/15183419/071ef162-175f-11e6-8dbd-e9c94c7cdbed.png)

------

#### Dispositivo desde donde se realizó la prueba (Pantalla 1, 2 y 3)

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![versionnexus4](https://cloud.githubusercontent.com/assets/19142276/15183501/4d233a2e-175f-11e6-94ba-32d35850d429.jpg)

#### Dispositivo desde donde se realizó la prueba (Pantalla 4)

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15183536/77b43d24-175f-11e6-83ee-6cfac4084061.png)

.

**Comment by IsbetVR** [comment]
@abicelis

**Comment by IsbetVR** [comment]
@MaviDavsa @abicelis @sanro14 
En la versión 6 de la apk muestra un sólo decimal en el balance, y los está aproximando

![screenshot_11](https://cloud.githubusercontent.com/assets/19142276/15233938/a13e74cc-187a-11e6-8dee-635cd9e7ed1c.jpg)


![screenshot_12](https://cloud.githubusercontent.com/assets/19142276/15233944/a8febfd2-187a-11e6-9486-7aefaf95aa93.jpg)

**Comment by arosiopr** [comment]
A mi me sucede lo mismo se come los decimales en el balance, y el monto que sale no es correcto, debería ser 56942.91 y sale es 56950 esta redondeando muy por encima. versión 6 de la aplicación
![captura de pantalla 2016-05-12 19 47 29](https://cloud.githubusercontent.com/assets/5313326/15234088/bcaf7fba-1877-11e6-96a9-b134dfaac2d4.png)

____________________________________________
Dispositivo desde donde se realizó la prueba
* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by AdryCanonico** [comment]
Sigue pasando en la V6

![captura de pantalla 343](https://cloud.githubusercontent.com/assets/18584168/15248711/7678cf10-18e5-11e6-943a-34c49bcebaed.png)
![captura de pantalla 344](https://cloud.githubusercontent.com/assets/18584168/15248712/767dd050-18e5-11e6-9def-418bd522256d.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)

**Comment by abicelis** [comment]
@IsbetVR @arosiopr @AdryCanonico @MaviDavsa revisen este issue en la version nueva (v7) del app! Creo (espero) haber corregido esto

**Comment by arosiopr** [comment]
@MaviDavsa @abicelis corregido en mi dispositivo:
Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0.0

**Comment by IsbetVR** [comment]
Ya funciona bien! Muestra dos decimales y lleva el conteo de las transacciones bien al tener en el balance cifras altas @abicelis @MaviDavsa 

Probados en los dispositivos de los cuales hice el reporte:

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0.0
y
Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0
