### ISSUE TITLE
CBP- App filter del settings

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#262]
##### Reporte de error: 

   *Cuando le doy click al settings y me muestra la pantalla del App Filter, sería bueno que tenga un boton de "OK" o "ACCEPT" porque de hecho cuando doy click fuera de esa pantalla para que desaparezca tarda bastante para aceptar el cambio. 

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android:5.0

**Comment by MaviDavsa** [comment]
@abicelis Esto también seria algo personal... Un favor que nos hicieras a nosotras! jajaja

**Comment by MaviDavsa** [comment]
@sanro14 Ya hay un issues de esto bella!
