### ISSUE TITLE
Bank Wallet - Mejoras botón (+) 

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#263]
#### Banking Wallet - Bank Wallet - Account Detail 

-----

##### Reporte de error: 

   *Cuando una cuenta en el Bank Wallet está en cero, ya sea que acaba de ser creada o se ha retirado todo lo que había en el balance, sería ideal que al darle al botón (+), sólo despliegue la opción de depósito (Deposit) y no retiro (Withdraw), pues en el balance no hay nada y así evitarnos un error.

##### Pantalla 1

![imagen11](https://cloud.githubusercontent.com/assets/19142276/15185197/26707a34-1766-11e6-95d0-bb8fcc2fe4c9.jpg)

##### Pantalla 2

![imagen12](https://cloud.githubusercontent.com/assets/19142276/15185205/2f71d880-1766-11e6-9e5c-f50454c7218c.jpg)

##### Pantalla 3

![imagen13](https://cloud.githubusercontent.com/assets/19142276/15185217/3704a0b4-1766-11e6-8aa6-66edfd67bd5e.jpg)

#### Dispositivo desde donde se realizó la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![versionnexus4](https://cloud.githubusercontent.com/assets/19142276/15185257/61c99304-1766-11e6-9d0a-183bd8c6c188.jpg)

**Comment by IsbetVR** [comment]
@abicelis

**Comment by abicelis** [comment]
@IsbetVR la version v7 tiene este fix, no lo probe casi, prueba please y me dices :)

**Comment by IsbetVR** [comment]
@abicelis Al crear la cuenta y estar en "0" si! sólo da la opción para depositar. Pero... al hacerle transacciones (depósitos y retiros), y luego querer retirar todo lo que tengo para que me quede en "0" se queda pegada la aplicación intentando hacerlo (Según el detalle lleva 6 minutos), no sé si ya esté reportado este error, pero me está dando. Cancelo la transacción y la vuelvo a hacer, y se queda pegada

![screenshot_5](https://cloud.githubusercontent.com/assets/19142276/15344095/6fefce52-1c71-11e6-8888-66c8e3c8646f.jpg)

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/15344140/da1f6e90-1c71-11e6-9c27-31edcd2c447c.jpg)

**Comment by abicelis** [comment]
@isbetVR hmm, OK. Estoy rehaciendo toda esta parte del cálculo de available/book.  Te aviso cuando la tenga funcionando como csh

**Comment by IsbetVR** [comment]
Vale!!! @abicelis :)

**Comment by abicelis** [comment]
@IsbetVR la version v9 tiene rehecho todo el calculo del available, prueba y me avisas !

**Comment by IsbetVR** [comment]
@abicelis Vale!! Voy a probar y te aviso! ;)

**Comment by IsbetVR** [comment]
Listo! Funciona bien! @abicelis @MaviDavsa 

Dispositivo desde donde se realizó la prueba
Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0.0
