### ISSUE TITLE
CBP - Settings - No se mantiene la configuración asignada 

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#264]
### Settings

Cada vez que entro a la aplicación debo irme al setting y cambiar la configuración, no se mantiene el Dev.

![img-20160511-wa0010 1](https://cloud.githubusercontent.com/assets/18471856/15198114/30121f32-179f-11e6-85c5-114c8eeadc51.jpg)

Dispositivo desde donde se realizó la prueba

![modelo](https://cloud.githubusercontent.com/assets/18471856/15198130/4f9465ae-179f-11e6-8048-15092e3978b4.jpg)

![software](https://cloud.githubusercontent.com/assets/18471856/15198126/4367bc36-179f-11e6-9cb8-9627e26d0b75.jpg)

**Comment by sanro14** [comment]
@abicelis

**Comment by MaviDavsa** [comment]
@sanro14 @fabianazabala Ya esto no es un error... En su caso seria un favor que @abicelis nos va a hacer a nosotras! pero no es un issues como tal! :*
