### ISSUE TITLE
Bank Wallet - Tamaño de letra para las opciones "Withdraw" y "Deposit"

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#265]
### La letra de las opciones withdraw y deposit es muy pequeño, no llama mucho la atención, también interfiere visualmente que se superponga a "No Transactions". Pienso que si estas opciones son las más importantes de la bank wallet deberían verse más llamativas.

![img-20160510-wa0018](https://cloud.githubusercontent.com/assets/18471856/15198556/de1acc8a-17a1-11e6-8f7d-b7653dc217c2.jpg)

### Dispositivo desde donde se realizó la prueba

![modelo](https://cloud.githubusercontent.com/assets/18471856/15198567/ec0cc546-17a1-11e6-947d-0b764fc7b860.jpg)

![software](https://cloud.githubusercontent.com/assets/18471856/15198570/ef5c44e2-17a1-11e6-8124-53b09e5f6ad8.jpg)

**Comment by sanro14** [comment]
@abicelis

**Comment by abicelis** [comment]
@fabianazabala @sanro14 Revisen la version v6 del app, hay mejoras que afectan a este issue.

**Comment by abicelis** [comment]
@fabianazabala @sanro14 La version v7 tiene mejoras aqui tambien!

**Comment by abicelis** [comment]
@fabianazabala @sanro14 Les sirvio?

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11, se puede visualizar un texto mas amigable y legible. 

![7](https://cloud.githubusercontent.com/assets/18584168/15480357/f3a8989c-20ee-11e6-91b8-e546585e98ce.png)
