### ISSUE TITLE
Cash Wallet-Error en el calculo del monto disponible en la cuenta

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#266]
##### Reporte de error: 

   *Cuando realizo depósitos y retiros consecutivos, y agrego decimales a los valores, no me realiza bien los cálculos, el esta redondeando por arriba, el ejemplo se ve en las imágenes referenciadas.
![caso1](https://cloud.githubusercontent.com/assets/5313324/15199881/c5947c38-17ab-11e6-9ac5-e6116806a649.png)
![caso1-2](https://cloud.githubusercontent.com/assets/5313324/15199882/c6c8b2cc-17ab-11e6-9e92-1526bb9e9fc9.png)
El valor expresado en notación cientifica se arroja cuando deposito un numero con una longitud mayor a 7. 
#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@sanro14 Este se parece mucho al #261 bella!
