### ISSUE TITLE
Cash Wallet -Error en cantidades en la Cash Wallet

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#267]
##### Reporte de error: 

 Al intentar escribir la cantidad en decimales, sólo me permite utilizar el punto y no la coma.

![cash wallet 1](https://cloud.githubusercontent.com/assets/17261437/15199696/82da86a0-17ae-11e6-9696-d98a6171b4a3.PNG)

![cash wallet 2](https://cloud.githubusercontent.com/assets/17261437/15199938/7966404e-17b0-11e6-82d9-5957b0a9ca14.PNG)

#### Dispositivo desde donde se realizo la prueba

![acerca del emulador](https://cloud.githubusercontent.com/assets/17261437/15199644/0ed376d6-17ae-11e6-818a-ab221bf2d89c.PNG)

**Comment by sanro14** [comment]
@abicelis

**Comment by gablup** [comment]
Chequeando de nuevo el issue, es importante hacer una sugerencia al respecto. Seria ideal que el punto en las cantidades sea utilizado para separar las unidades de mil y la coma para los decimales, que fue lo que quise decir en este caso. ¡Saludos! @abicelis

**Comment by abicelis** [comment]
@gablup el único lenguaje instalado actualmente en las wallets es el inglés (eeuu) como habrás visto que esta todo. Su sistema usa un punto para separar decimales y comas para los miles. 
Cuando se decida soportar otro idioma, eso que dices vendrá automáticamente.

**Comment by MaviDavsa** [comment]
@abicelis perfecto por lo que entiendo esto es como un defauld en cuanto al idioma del programa que esta en ingles! Entonces procedemos a cerrarlo! :)
