### ISSUE TITLE
Banking Wallet -Al iniciar la BNK Wallet no responde

### ISSUE THREAD

**Issue by alegnaire** [Fermat-ORG/beta-testing-program#268]
### Template issue error report
Solo se logro iniciar la Banking Wallet 2 de 12 intentos, la primera vez que se logro accesar se crearon 2 cuentas, luego se colgó, mostrando el mensaje "Fermat isn't responding". después de 3 intentos seguidos fue necesario cerrar el emulador del teléfono y volver a iniciarlo, así me dio acceso y al intentar crear una nueva cuenta, nuevamente comenzó a mostrar el error "Fermat isn't responding".
Seguidamente se hicieron 8 intentos mas de accesar al Banking Wallet, pero la misma se queda en la pantalla violeta hasta que finalmente muestra el mensaje "Fermat isn't responding", al presionar el botón de retorno a la pantalla anterior.
![captura de pantalla 2016-05-11 a las 7 31 22 p m](https://cloud.githubusercontent.com/assets/18564248/15200456/cb08e1cc-17b0-11e6-99d8-87d95461f7ef.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung
* Modelo: S6
* Version de Android:6.0.0

**Comment by sanro14** [comment]
@alegnaire intenta editar el caso y explicar el problema que esta presentando la app ;)

**Comment by alegnaire** [comment]
@sanro14 Si Gracias, justo acabo de terminar de editarlo!!!

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@alegnaire @sanro14 En la version v6 del app hay mejoras sustanciales de rendimiento del bank wallet. Revisar y reportar aqui please :)

**Comment by sanro14** [comment]
ok @abicelis Gracias..

**Comment by alegnaire** [comment]
Se probo la v6 y se valido el acceso, el error reportado fue corregido. Se puede accesar a la aplicación satisfactoriamente y ejecutar transacciones.

**Comment by alegnaire** [comment]
@sanro14 Por favor cerrar!

**Comment by abicelis** [comment]
@alegnaire great!
