### ISSUE TITLE
Bank Wallet-No sale nombre de deposit o withdrawal

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#269]
### Bank Wallet
-----
##### Reporte de error: 

   *Al ingresar a la bank wallet e ir a realizar un deposit o withdrawal no se muestra al lado de las flechas el nombre de lo que significa cada una, como se puede observar en la siguiente figura:

![captura de pantalla 2016-05-11 19 31 22](https://cloud.githubusercontent.com/assets/5313326/15200358/d75c7836-17af-11e6-961a-2e220c0d32a0.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa @abicelis

**Comment by AdryCanonico** [comment]
![captura de pantalla 320](https://cloud.githubusercontent.com/assets/18584168/15217882/5016c9d0-1827-11e6-96d2-a9bbee916014.png)

**Comment by arosiopr** [comment]
@MaviDavsa error corregido en versión 6

**Comment by MaviDavsa** [comment]
SOLUCIONADO
