### ISSUE TITLE
Bank Wallet-Account Detail-Error calculo de available

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#270]
### Bank Wallet

-----

##### Reporte de error: 

   *El cálculo del dinero disponible (available) en la cuenta, no está tomando los decimales que tienen los depósitos y retiros realizados, muestra 99 USD y debería mostrar 99.91 USD como se puede observar en la siguiente figura:

![captura de pantalla 2016-05-11 19 33 42](https://cloud.githubusercontent.com/assets/5313326/15200502/5e599dae-17b1-11e6-8f71-259e314619c8.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa @abecelis

**Comment by AdryCanonico** [comment]
![captura de pantalla 318](https://cloud.githubusercontent.com/assets/18584168/15217932/83ad4418-1827-11e6-85b3-926e73c74053.png)


![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15217951/9192bf68-1827-11e6-95d2-a3f7a8b7da53.png)

**Comment by arosiopr** [comment]
@MaviDavsa continua el mismo error en la versión 6 de la aplicación

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@arosiopr @AdryCanonico @MaviDavsa. Listo, la version v8 tiene totalmente rehechos los calculos :), todo deberia calcularlo bien ahora.

**Comment by arosiopr** [comment]
@MaviDavsa corregido en versión 8. se puede cerrar
