### ISSUE TITLE
Banking Wallet - Al refrescar se congela

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#271]
### Banking Wallet

-----

##### Reporte de error: 

   *El problema radica en que cuando voy a refrescar la wallet se queda completamente congelada y no reacciona, la única manera de hacerla reaccionar de nuevo es entrando nuevamente desde 0.

![rwerw](https://cloud.githubusercontent.com/assets/17273005/15215967/d9ab9292-181e-11e6-9ba4-e59d1aafd51c.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@MaviDavsa En la version v6 del app hay mejoras sustanciales de rendimiento del bank wallet. Revisar y reportar aqui please :)

**Comment by abicelis** [comment]
@MaviDavsa En la version v7 hay mas optimizaciones de bank! Check and let me know please

**Comment by abicelis** [comment]
@MaviDavsa

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis En la versión 11 sigue persistiendo el error.

![8](https://cloud.githubusercontent.com/assets/18584168/15480565/1348566e-20f0-11e6-91fd-4abdb5d8a5cd.png)

Dispositivo:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15480586/29670e36-20f0-11e6-9d6b-40643f06f2cc.png)

**Comment by abicelis** [comment]
@MaviDavsa @AdryCanonico tienen razon :O, ya lo reviso y les aviso

**Comment by abicelis** [comment]
Listo @MaviDavsa @AdryCanonico, en la version v12 esta arreglado este error!

**Comment by MaviDavsa** [comment]
Perfecto mi amor... Solucionado
