### ISSUE TITLE
BAKING WALLET- ERROR EN CALCULO DEL BALANCE AL AGREGAR DECIMALES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#274]
### CBP

-----

##### Reporte de error: 

   *Si se realizan depósitos y retiros consecutivos, al agregar decimales a los valores, no se realiza bien el cálculo en el Balance. Lo redondea dando un monto incorrecto.

![captura de pantalla 319](https://cloud.githubusercontent.com/assets/18584168/15217532/b6c2a192-1825-11e6-86e8-112f1027be2d.png)
![captura de pantalla 318](https://cloud.githubusercontent.com/assets/18584168/15217533/b6c5fcca-1825-11e6-9840-13d3fa433939.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15217554/d2ade15a-1825-11e6-9aa4-f7e3bfc352a7.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by alegnaire** [comment]
Mismo Caso en Google Nexus 9 6.0.0

**Comment by yolandayancel** [comment]
mismo caso desde un Nexus 5 5.1.0

**Comment by abicelis** [comment]
@AdryCanonico @alegnaire @yolandayancel Listo en la version v8, revisen y me dicen!

**Comment by yolandayancel** [comment]
Buenas Alejandro.
Recibido.

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis  En la V9 se corrigio el error. Se puede cerrar el caso.

![captura de pantalla 428](https://cloud.githubusercontent.com/assets/18584168/15410424/725b3cbc-1de3-11e6-99b4-ea598c1278be.png)
