### ISSUE TITLE
Banking Wallet-error al hacer retiro

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#275]
#### Nombre pantalla

Banking Wallet

##### Reporte de error: 

   

Estando en el Banking Wallet para hacer un retiro, esta se queda cargándolo y no termina de hacerlo, pasan más de 5 minuto como verán en la foto y ella esta cargándolo todavía. Hay que interrumpirlo (hacerle click ). El retiro como tal si lo realiza después que lo interrumpimos. 

Foto 1 Solicitud de Retiro hora 10:08am

![error se queda cargando el retiro-banking 1](https://cloud.githubusercontent.com/assets/17283358/15218024/d25002c2-1827-11e6-853d-dfd1af608e45.png)

Foto 2 Sigue cargando el retiro hora: 10:13am

![error se queda cargando el retiro-banking 2](https://cloud.githubusercontent.com/assets/17283358/15218051/edcf6bf0-1827-11e6-9543-f51a5d24db2a.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
* Modelo:
Android

![emulador -nexus 5](https://cloud.githubusercontent.com/assets/17283358/15217984/affde298-1827-11e6-94d7-ed0c4802e2dd.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by yolandayancel** [comment]
@abicelis
Buenas noches Alejandro
Error corregido

Al hacer retiro no se queda cargando. lo hace rapido
![error se corrigio 1](https://cloud.githubusercontent.com/assets/17283358/15234253/94dd2e5e-1879-11e6-8415-06486b5cdf84.png)

**Comment by MaviDavsa** [comment]
SOLUCIONADO!
