### ISSUE TITLE
Cash Wallet - No hay limite de caracteres en la opción "Memo" de la Cash Wallet.

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#276]
##### Reporte de error: 

No existe limite de caracteres en la opción de "Memo" de la Cash Wallet. Es decir, se puede colocar infinita cantidad de letras o números sin ningún mensaje que detenga al usuario, aceptando de todos modos el depósito, en este caso. 
Se sugiere que se especifique para el usuario la cantidad de caracteres de la que se dispone, tanto para realizar un depósito, como un retiro, porque no aparece.

![issues 3](https://cloud.githubusercontent.com/assets/17261437/15219440/cd0f759a-1831-11e6-8f3c-355c3d557bbf.PNG)

![issue 3](https://cloud.githubusercontent.com/assets/17261437/15219447/d4955e42-1831-11e6-88e6-6e447dcfaf51.PNG)

Incluso, al entrar en los detalles de la transacción se puede ver claramente que permite al usuario escribir sin limite de caracteres.

![capissue 3](https://cloud.githubusercontent.com/assets/17261437/15219942/99aa70ae-1833-11e6-9a55-ed14a0ffb60a.PNG)

#### Dispositivo desde donde se realizo la prueba

![acerca del emulador](https://cloud.githubusercontent.com/assets/17261437/15219434/c33a8e24-1831-11e6-9b79-f2455685147a.PNG)

**Comment by AdryCanonico** [comment]
En mi caso se coloco una gran cantidad de caracteres (la misma cantidad en ambos emuladores) 

![captura de pantalla 327](https://cloud.githubusercontent.com/assets/18584168/15220570/ca713d96-1831-11e6-86a4-3568c0f309ff.png)


### deja realizar el deposito 

![captura de pantalla 328](https://cloud.githubusercontent.com/assets/18584168/15220615/ee5f1b06-1831-11e6-9b70-404f91296341.png)


pero en la pantalla Transaction  Details (emulador izquierdo) no me da opción de leerlo todo (no posee scroll la ficha). 
En el (emulador derecho) corta el mensaje, no permitiendo leer el memo con el texto que se abrió el deposito originalmente.

![captura de pantalla 330](https://cloud.githubusercontent.com/assets/18584168/15220644/feadd02e-1831-11e6-8fa2-951db2f02dd8.png)


#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)


Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
En la version V6 sigue persistiendo el error

![captura de pantalla 346](https://cloud.githubusercontent.com/assets/18584168/15249250/6cb5bc06-18e8-11e6-8b48-2bbef00a2e22.png)
![captura de pantalla 345](https://cloud.githubusercontent.com/assets/18584168/15249256/7085d79e-18e8-11e6-8a8c-d9567ca3a9b6.png)



#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)


Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by abicelis** [comment]
@adrycanonico no he tocado esto. A medida que vaya haciendo fixes lo reportare en cada issue, asi no tienen que chequear cada versión a ver si algún issue se arreglo. Yo les aviso!

**Comment by abicelis** [comment]
@AdryCanonico en la version v7 estan limitados los memo (bank y cash) a 100 caracteres!

**Comment by abicelis** [comment]
@AdryCanonico

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11 se corrigió el error. Se sugiere que se especifique para el usuario la cantidad de caracteres que dispone para realizar el memo. como cuando se crea la cuenta.

![2c](https://cloud.githubusercontent.com/assets/18584168/15480903/ad7747ee-20f1-11e6-8dbf-7f10622ef05d.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by gablup** [comment]
Pienso que podría cerrarse este issue, ya que efectivamente, está corregido en la versión 11 pero como sugerencia, coincido con @AdryCanonico, que debería especificarse al usuario la cantidad de caracteres que dispone para realizar el memo.
@MaviDavsa @abicelis

**Comment by abicelis** [comment]
Ok, en la version v12 esta la sugerencia de @AdryCanonico, aqui en la cash wallet y tambien en la bank!

**Comment by MaviDavsa** [comment]
Solucionado!
