### ISSUE TITLE
Cash Wallet - No hay límite de caracteres en la opción de "Memo" 

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#277]
##### Reporte de error: 

No existe límite de caracteres en la opción de "Memo" de la Cash Wallet en la parte de retiros tampoco.
Se sugiere que se especifique para el usuario la cantidad de caracteres de la que se dispone, tanto para realizar un depósito, como un retiro, porque no aparece.

![issues 4](https://cloud.githubusercontent.com/assets/17261437/15221021/b02d89ac-1837-11e6-97de-b67cac51bf56.PNG)

Y aún así permite el retiro 

![issue 4 c](https://cloud.githubusercontent.com/assets/17261437/15221142/3b189390-1838-11e6-9ec1-21b5d6a7a71b.PNG)

Aquì se puede apreciar claramente que no existe límite de caracteres.

![issue 4](https://cloud.githubusercontent.com/assets/17261437/15221026/b78f69c2-1837-11e6-9c24-61ca3cfb4a5e.PNG)

#### Dispositivo desde donde se realizo la prueba

![acerca del emulador](https://cloud.githubusercontent.com/assets/17261437/15221008/a4963684-1837-11e6-958f-c62d8e627a0a.PNG)

**Comment by AdryCanonico** [comment]
En mi caso se coloco una gran cantidad de caracteres (la misma cantidad en ambos emuladores) 

![captura de pantalla 333](https://cloud.githubusercontent.com/assets/18584168/15221327/cf0593b8-1834-11e6-9621-75f4c2568861.png)


### deja realizar el Retiro

![captura de pantalla 334](https://cloud.githubusercontent.com/assets/18584168/15221350/e3d915b2-1834-11e6-93ea-788804beafc6.png)


Pero en la pantalla Transaction  Details (emulador izquierdo) no me da opción de leer todo el memo (no posee scroll la ficha). 
En el (emulador derecho) corta el mensaje, no permitiendo leer el memo con el texto que se abrió el retiro originalmente.


![captura de pantalla 335](https://cloud.githubusercontent.com/assets/18584168/15221379/ffb24c4a-1834-11e6-9646-205636efc45f.png)


#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)


Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
Sigue persistiendo el error en la V6, con la diferencia que en el retiro del emulador de la derecha no corta el mensaje pero de igual manera no deja usar el scroll para visualizar todo el texto. 

![captura de pantalla 347](https://cloud.githubusercontent.com/assets/18584168/15249476/8ea7d7ee-18e9-11e6-9f3e-5e9b1c9eefe7.png)


![captura de pantalla 348](https://cloud.githubusercontent.com/assets/18584168/15249490/983f7cbc-18e9-11e6-9d0c-f0c366309139.png)


#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)


Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by abicelis** [comment]
@gablup @AdryCanonico @MaviDavsa la version v7 limita el texto de los memos (cash y bank, depositos y retiros) a 100 char max!

**Comment by abicelis** [comment]
@gablup @AdryCanonico @MaviDavsa

**Comment by gablup** [comment]
Puede cerrarse por la misma razón en este caso de retiros.  https://github.com/Fermat-ORG/beta-testing-program/issues/276#issuecomment-221373651 @MaviDavsa @abicelis
