### ISSUE TITLE
 Banking Wallet - No existe límite de caracteres en la opción"Memo" 

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#278]
##### Reporte de error: 

   Vemos nuevamente, como se repite el mismo error del límite de caracteres en la opción "Memo" de la Banking Wallet, en esta oportunidad. Pese a esto, deja al usuario realizar su depòsito sin problemas.

![image](https://cloud.githubusercontent.com/assets/17261437/15222634/a01b511e-183e-11e6-9405-2eef62c7aa3d.png)

Aquí se puede observar claramente que no existe límite de caracteres en esta opción.

![image](https://cloud.githubusercontent.com/assets/17261437/15222644/afaa6584-183e-11e6-872b-3f1b511c32cd.png)

Se sugiere que se especifique para el usuario la cantidad de caracteres que dispone para realizar este tipo de operaciones.
#### Dispositivo desde donde se realizo la prueba

Modelo: Nexus 5-5.1.0-API22-1080x1920
Versiòn: Android 5.1

**Comment by abicelis** [comment]
@gablup @MaviDavsa la version v7 limita el texto de los memos (cash y bank, depositos y retiros) a 100 char max!

**Comment by abicelis** [comment]
@gablup @MaviDavsa

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11 se corrigió el error. Se sugiere que se especifique para el usuario la cantidad de caracteres que dispone para realizar el memo. como cuando se crea la cuenta.


![6](https://cloud.githubusercontent.com/assets/18584168/15480469/8b2cc292-20ef-11e6-9a60-02eac2fb1e1b.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by gablup** [comment]
Favor cerrar ya que ha sido corregido en la versión 11 efectivamente. @MaviDavsa @abicelis
