### ISSUE TITLE
Banking Wallet- Falta un botón para cancelar depositos

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#279]
#### Nombre pantalla

Banking Wallet

##### Reporte de error: 

   *Estando en la Banking Wallet, al  hacer un deposito no encontramos con un solo botón DONE, no hay otra opción   si uno no quiere hacer el retiro. En la Cash Wallet tiene dos botones uno de Cancelar y el otro Deposit.
   
![falta un boton de cancelar](https://cloud.githubusercontent.com/assets/17283358/15231259/c92dc242-1863-11e6-9bdf-0e59eb4d1c16.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
* Modelo:
Nexus 5

![emulador -nexus 5](https://cloud.githubusercontent.com/assets/17283358/15231304/1d77c5d2-1864-11e6-8ddf-c9aa0feb3992.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by yolandayancel** [comment]
@abicelis
Buenas noches

En revisión de este reporte sigue en pie la recomendación anterior, falta un botón para cancelar un deposito
![prueba banking-boton cancelar](https://cloud.githubusercontent.com/assets/17283358/15234362/9e4ca41e-187a-11e6-8d48-f594590c39cc.png)

**Comment by yolandayancel** [comment]
@abicelis
Buen día Alejandro

Prueba caso 279
17-05-16
Banking Wallet, al hacer un deposito nos encontramos todavía con el 
![falta el boton cancelar](https://cloud.githubusercontent.com/assets/17283358/15322755/6448e318-1c08-11e6-9224-af67de119f77.png)
 botón DONE, no hay otra opción si uno no quiere hacer el retiro. En la Cash Wallet tiene dos botones uno de Cancelar y el otro Deposit.

**Comment by abicelis** [comment]
@yolandayancel no he tocado este issue, cuando lo arregle les aviso!

**Comment by abicelis** [comment]
@yolandayancel @MaviDavsa Listo en la version v8, las transacciones se pueden cancelar, el diseno de la ventana esta ahora estandarizado con la cash.

**Comment by yolandayancel** [comment]
Buenas Alejandro

Recibido

**Comment by yolandayancel** [comment]
@abicelis 

Buenos días Alejandro

Prueba de fecha 19-05-16- CBP V9
Caso 279: Falta un botón para cancelar depósitos
Ya aparece el botón
![prueba caso 279](https://cloud.githubusercontent.com/assets/17283358/15393305/69c9415e-1d96-11e6-88e6-986f7e17906a.png)
