### ISSUE TITLE
CBP - Bank Wallet - Sólo permite una entidad bancaria 

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#280]
##### Reporte de error: 

   *Al entrar por primera vez al "Banking Wallet" da la opción de ingresar el nombre del banco y la denominación de la moneda. Luego cuando se agrega una cuenta dando click al botón (+) en la parte superior derecha, sólo da opciones de ingresar el número de la cuenta, el alias (a mi interpretación los datos del cliente), y la denominación de moneda (pantalla 1). luego de haberla creado, yéndonos al resumen de cuentas (pantalla 2) podemos observar que sale el resumen de cada una de las que se ha creado pero hace referencia que todas pertenecen a un mismo banco (en mi caso MERCANTIL, que fue el nombre que coloqué al principio), debería dar opción de introducir que sea de otro banco, pues en la parte superior (pantalla 2) el nombre del banco que se introdujo la primera vez al ingresar al Banking pareciera que lo que se agrega con el botón (+) son cuentas de ese mismo banco.

##### Pantalla 1

![screenshot_9](https://cloud.githubusercontent.com/assets/19142276/15232048/9f53e646-186c-11e6-9599-966daf348aa7.jpg)

##### Pantalla 2

![screenshot_10](https://cloud.githubusercontent.com/assets/19142276/15232027/78b9bf9c-186c-11e6-8a42-0b746fff3085.jpg)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15232033/847a0184-186c-11e6-96b6-0a2a3d2c2484.jpg)

**Comment by IsbetVR** [comment]
@abicelis

**Comment by abicelis** [comment]
@isbetVR esto es así por diseño. Si se quisiera tener cuentas en otro banco, el usuario final instalaría otro bank wallet en su dispositivo Fermat. Un bank wallet por banco.

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by sanro14** [comment]
@abicelis pero seria una recomendación para una próxima versión, porque estaría limitando al usuario. Que pasa si yo tengo dos bancos con cuentas y quiero utilizarlos? son escenarios que se pueden dar.. no se si estas de acuerdo..

**Comment by IsbetVR** [comment]
@abicelis @sanro14 en mi opinión, obligar al usuario a instalar por cada banco una aplicación puede poner más lento el dispositivo, creo que poder manejar varios bancos y a su vez varias cuentas como se plantea en el diseño seria ideal, no les parece? en una misma aplicación. No sé que opinan.

**Comment by abicelis** [comment]
No pondría realmente más lento al dispositivo,  la aplicación no se estaría duplicando, solo habrían dos accesos al mismo código, mismos recursos.  

La decisión de tener una banking wallet por cada bank fue una qué se hizo en el diseño de la plataforma CBP, fue concebida por los que la diseñaron en su momento, junto a muchos otros componentes dentro de CBP. No es algo que se pudo cambiar,  ni si quiera en la etapa de desarrollo.

**Comment by MaviDavsa** [comment]
Okay!! @abicelis Entonces por lo que entiendo es algo que va a hacer así y jamas va a cambiar! Deben hacerse por dos cuentas diferentes en el bancking?

**Comment by abicelis** [comment]
si @MaviDavsa , de quererse dos bancos se tendria una instancia nueva de la banking wallet, que use los mismos recursos pero una base de datos distinta.

**Comment by MaviDavsa** [comment]
@sanro14 @IsbetVR ya vieron bella es una opción por defauld de la aplicación... Sin embargo @abicelis sería bueno algún pop de información que pueda decirle esto a los usuarios para evitar futuras confusiones!

**Comment by abicelis** [comment]
@MaviDavsa ok, lo hare, les aviso!

**Comment by IsbetVR** [comment]
@MaviDavsa si, entiendo que sería algo por defecto. @abicelis me parece excelente idea lo que dice María, que el usuario sepa y así no tener dudas al respecto, como en mi caso :P

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa En la version v11 sale en el wizard del bank wallet, la informacion de que es un bank wallet por bank :)

**Comment by IsbetVR** [comment]
Si! En el Wizard lo dice ;) @abicelis  @MaviDavsa ;) Verificado con la V11

**Comment by MaviDavsa** [comment]
Perfecto! Cerrado entonces!
