### ISSUE TITLE
CBP- Banking Wallet - Sin mensaje de alerta al intentar hacer un Withdrawal superior al monto disponible.

### ISSUE THREAD

**Issue by alegnaire** [Fermat-ORG/beta-testing-program#281]
##### Reporte de error:

Al intentar realizar un withdrawal superior al monto disponible en la cuenta, no emite ningún mensaje de alerta que indique que el monto a retirar es superior al existente, seguidamente la aplicación se queda colgada  intentando realizar el retiro (withdrawal).

![captura de pantalla 2016-05-12 a las 6 31 28 p m](https://cloud.githubusercontent.com/assets/18564248/15233662/3f8c08d0-1874-11e6-9586-14ca6d9a3998.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Google Nexus
* Modelo: 9
* Version de Android:6.0.0

**Comment by alegnaire** [comment]
Caso similar en Samsung Galaxy S6 6.0.0

![captura de pantalla 2016-05-12 a las 7 39 32 p m](https://cloud.githubusercontent.com/assets/18564248/15234257/9b8daaf8-1879-11e6-8502-33373f2f4bdf.png)

**Comment by Gabymorillo** [comment]
Caso similar

Modelo: Google Nexus 4-   5.0.0
![capture-20160512-195226](https://cloud.githubusercontent.com/assets/17262077/15234487/1a414dee-187c-11e6-82f4-5c38e98b2294.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@alegnaire @Gabymorillo  @MaviDavsa Corregido en la version v8, la aplicacion no deja retirar mas dinero del que existe en el available balance.

**Comment by alegnaire** [comment]
@abicelis Gracias, ya estoy descargando para hacer las pruebas!!

**Comment by alegnaire** [comment]
@abicelis @MaviDavsa @Gabymorillo Listo! Verificado la corrección del error, no permite retirar una cantidad mayor a la disponible y emite un mensaje de alerta indicando que el monto que se desea retirar es mayor al disponible.

**Comment by alegnaire** [comment]
@MaviDavsa Por Favor Cerrar!
