### ISSUE TITLE
Cash Wallet-Deposit-No deja ingresar mas de 7 dígitos en el monto

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#283]
### Cash Wallet 

-----

##### Reporte de error: 

   *Al momento de realizar un depósito no deja ingresar mas de 7 dígitos por por ejemplo si se van a depositar 10.000.000 no deja ingresar los 8 dígitos.

![captura de pantalla 2016-05-12 20 09 53](https://cloud.githubusercontent.com/assets/5313326/15234249/8ee56c14-1879-11e6-8362-2720fc8b77a3.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by yolandayancel** [comment]
Mismo error: no permite colocar más de 7 cifras a los depositos
 Emulador Genymotion
Samsung Galaxy 5.1.0 API22
![cash w-no permite mas de 7 cifras](https://cloud.githubusercontent.com/assets/17283358/15265146/88dd1c6c-1947-11e6-8fb6-2046b9f12838.png)

**Comment by abicelis** [comment]
@arosiopr @yolandayancel @MaviDavsa 
Imcremente el valor maximo de deposito en la cash a 99,999,999.99 unidades.
Coloque el de bank igual.

**Comment by yolandayancel** [comment]
Buenos días Alejandro

En prueba
17-05-16
En la Bank Wallet, ingrese esta cantidad 99.999.999,00 y me arrojo esto.
Te adjunto foto

2016-05-16 20:40 GMT-04:30 Alejandro Bicelis <notifications@github.com>:

> @arosiopr <https://github.com/arosiopr> @yolandayancel
> <https://github.com/yolandayancel> @MaviDavsa
> <https://github.com/MaviDavsa>
> Imcremente el valor maximo de deposito en la cash a 99,999,999.99 unidades.
> Coloque el de bank igual.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/283#issuecomment-219593454>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenos días Alejandro

En prueba
17-05-16
En la CashWallet, ingrese esta cantidad 99.999.999,00 y me arrojo esto.
Te adjunto foto


2016-05-17 8:08 GMT-04:30 Yolanda Yancel <yyancel47@gmail.com>:

> Buenos días Alejandro
>
> En prueba
> 17-05-16
> En la Bank Wallet, ingrese esta cantidad 99.999.999,00 y me arrojo esto.
> Te adjunto foto
>
> 2016-05-16 20:40 GMT-04:30 Alejandro Bicelis <notifications@github.com>:
>
>> @arosiopr <https://github.com/arosiopr> @yolandayancel
>> <https://github.com/yolandayancel> @MaviDavsa
>> <https://github.com/MaviDavsa>
>> Imcremente el valor maximo de deposito en la cash a 99,999,999.99
>> unidades.
>> Coloque el de bank igual.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/283#issuecomment-219593454>
>>
>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> 0426-9811123
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by arosiopr** [comment]
@yolandayancel no sale foto de la apk

**Comment by arosiopr** [comment]
@MaviDavsa @abicelis si ahora deja 8 cifras y 2 decimales

**Comment by yolandayancel** [comment]
Buenos días Adriana, Alejandro

Prueba 2 17-05-16
ocho (8) cifras y dos (2) decimales, me apareció esto

2016-05-17 8:22 GMT-04:30 Adriana del Rosio Porras Ramirez <
notifications@github.com>:

> @MaviDavsa <https://github.com/MaviDavsa> @abicelis
> <https://github.com/abicelis> si ahora deja 8 cifras y 2 decimales
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/283#issuecomment-219708006>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
El 17 de mayo de 2016, 08:40, Yolanda Yancel<yyancel47@gmail.com> escribió:

> Buenos días Adriana, Alejandro
>
> Prueba 2 17-05-16
> ocho (8) cifras y dos (2) decimales, me apareció esto
>
> 2016-05-17 8:22 GMT-04:30 Adriana del Rosio Porras Ramirez <
> notifications@github.com>:
>
>> @MaviDavsa <https://github.com/MaviDavsa> @abicelis
>> <https://github.com/abicelis> si ahora deja 8 cifras y 2 decimales
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Fermat-ORG/beta-testing-program/issues/283#issuecomment-219708006>
>>
>
>
>
> --
> *Saludos cordiales*
>
> *Yolanda Yancel*
> Lcda. Contaduría Pública
> 0426-9811123
> Email.yyancel47@gmail.com
>
>


-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by sanro14** [comment]
@yolandayancel revisa que subas la imagen.. porque no entiendo lo q estas queriendo decir.. no se muestra nada..

**Comment by yolandayancel** [comment]
No suben las imagenes?, voy a subirlas otra vez

Probé 8 cifras y dos decimales y paso esto.

2016-05-17 9:08 GMT-04:30 Rosana <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> revisa que subas la
> imagen.. porque no entiendo lo q estas queriendo decir.. no se muestra
> nada..
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/283#issuecomment-219719894>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by sanro14** [comment]
@yolandayancel es que no estas subiendo la imagen, dale antes de subir el issue en la pestaña que dice preview y asi ves como te va a quedar tu issue

**Comment by abicelis** [comment]
@arosiopr podria aumentarlo a un numero exageradamente alto, que numero seria suficientemente alto? 1000M ?

**Comment by arosiopr** [comment]
@abicelis si podria ser, creo yo no se hasta donde este el alcance en esa parte

**Comment by MaviDavsa** [comment]
@abicelis Realmente como esta a mi me parece un numero alto! Pero si consideras ese numero un numero limite! puede considerarse!

**Comment by abicelis** [comment]
@arosiopr eso no se definio en el alcance.. lo aumente a 999,999,999.99  por dejar un numero aleatoriamente gigantesco. En la version v8 esta este cambio.

**Comment by arosiopr** [comment]
@MaviDavsa corregido en versión 8. se puede cerrar.
