### ISSUE TITLE
Banking Wallet- ERROR DEPOSITO EN UNA CUENTA Y RETIRO AUTOMÁTICO SIN SOLICITARLO 

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#284]
### Template issue error report

Nombre pantalla 

ACCOUNT DETAIL

BANKING WALLET

##### Reporte de error: 

   *SE CREO UNA CUENTA, LUEGO SE HIZO UN DEPOSITO Y AUTOMÁTICAMENTE SIN SOLICITARLO SE HIZO UN RETIRO. ASÍ MISMO, LA APK SE QUEDO FRIZADA Y POSTERIORMENTE EL EMULADOR ARROJO ERROR EN EL PROGRAMA Y SE CERRO. CUANDO SE ABRIÓ NUEVAMENTE LA APLICACIÓN NO APARECIÓ NINGÚN RETIRO NI DEPOSITO EN LA CUENTA.
   
![image](https://cloud.githubusercontent.com/assets/18740418/15234338/56785a48-187a-11e6-9d92-193bcd1906b8.png)

![screenshot 10](https://cloud.githubusercontent.com/assets/18740418/15234350/6d535ae2-187a-11e6-85a3-ea8982ae16e7.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: GENYMOTION
* Modelo:EMULADOR

![screenshot 11](https://cloud.githubusercontent.com/assets/18740418/15234400/270cd8d2-187b-11e6-930b-d0cabff13a3d.png)

**Comment by camilavaleria** [comment]
@abicelis

**Comment by abicelis** [comment]
@camilavaleria @MaviDavsa  Listo, corregido en la version v8 de la aplicacion. Revisa y me dices.

**Comment by camilavaleria** [comment]
@MaviDavsa listo, revisado en la versión v9 de la aplicacion
