### ISSUE TITLE
Banking Wallet- ERROR AL REALIZAR UN RETIRO 

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#285]
#### Nombre pantalla

ACCOUNT DETAIL

BANKING WALLET

##### Reporte de error: 

   *SE REALIZO UN RETIRO EN UNAS DE LAS CUENTAS, EL CUAL SE REPITE PARALELAMENTE EN LAS DEMÁS CUENTAS CREADAS Y ADEMAS SE QUEDA GUINDADO EL EMULADOR SIN TERMINAR DE EFECTUAR LA OPERACIÓN.

![screenshot 13](https://cloud.githubusercontent.com/assets/18740418/15234854/db45cd28-187f-11e6-9131-ba187950c793.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/18740418/15234855/e08e9904-187f-11e6-86e4-66af4a3b62f3.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/18740418/15234858/e3b43454-187f-11e6-9e0d-7ac1c296624d.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: GENYMOTION
* Modelo: EMULADOR

![screenshot 11](https://cloud.githubusercontent.com/assets/18740418/15234879/2d392512-1880-11e6-91e2-1e427cf23012.png)

**Comment by camilavaleria** [comment]
@abicelis

**Comment by abicelis** [comment]
@camilavaleria @MaviDavsa Si... super error corregido en la version v8 de la aplicacion! Revisa @camilavaleria y me avisas :)

**Comment by camilavaleria** [comment]
@MaviDavsa listo, revisado en la versión v9 de la aplicacion
