### ISSUE TITLE
Banking Wallet- ERROR MIENTRAS SE CARGA UN DEPOSITO 

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#286]
#### Nombre pantalla

 ACCOUNT DETAIL

BANKING WALLET

##### Reporte de error: 

   *SE TRATO DE REALIZAR UN DEPOSITO EN UNAS DE LAS CUENTAS,Y MIENTRAS SE CARGABA SE REPITE PARALELAMENTE EN LAS DEMÁS CUENTAS CREADAS Y ADEMAS SE QUEDA GUINDADO EL EMULADOR SIN TERMINAR DE EFECTUAR LA OPERACIÓN. POSTERIORMENTE AL CERRA Y ABRIR LA APLICACION NO APARECEN.

![image](https://cloud.githubusercontent.com/assets/18740418/15249163/01a5f4a8-18e8-11e6-922f-0c670ddb2024.png)

![image](https://cloud.githubusercontent.com/assets/18740418/15249150/f7b8855a-18e7-11e6-8767-f19aeb06cf77.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: GENYMOTION
* Modelo:EMULADOR

![image](https://cloud.githubusercontent.com/assets/18740418/15249227/4e4ce9e2-18e8-11e6-96f5-50b6ae3bc309.png)

**Comment by camilavaleria** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
En mi caso pasa igual.

![captura de pantalla 357](https://cloud.githubusercontent.com/assets/18584168/15250758/1043805e-18f0-11e6-812a-a7591957d61e.png)
![captura de pantalla 356](https://cloud.githubusercontent.com/assets/18584168/15250759/1049a8d0-18f0-11e6-871c-516ae40042c6.png)


#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by abicelis** [comment]
@camilavaleria @AdryCanonico Prueben esto en la version v9, corregido el bug ahi!

**Comment by abicelis** [comment]
@camilavaleria @AdryCanonico bump

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11 se corrigió el error. Se puede cerrar el caso.

![3](https://cloud.githubusercontent.com/assets/18584168/15480056/44218b6e-20ed-11e6-84d2-ea0996dc87d0.png)
