### ISSUE TITLE
BANKING WALLET - ERROR REPETICIÓN DE NUMERO EN CUENTA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#287]
### BANKING WALLET

-----

##### Reporte de error: 

   *La apk permite abrir varias cuentas con el mismo account number y alias. 

![captura de pantalla 351](https://cloud.githubusercontent.com/assets/18584168/15250978/1fd2a738-18f1-11e6-971b-ee7c26a051c8.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador Izquierdo:
![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15220695/3321bca8-1832-11e6-908e-d1a6fb7fea1e.png)

Emulador Derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15220711/3f00d2b6-1832-11e6-8864-41fd6c3f0b57.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa la version v7 no permite ni crear ni editar cuentas para que tengan el mismo numero de cuenta (aliases iguales si son permitidos)

**Comment by AdryCanonico** [comment]
@MaviDavsa  @abicelis  En la V7 no permite crear cuentas iguales. Se puede cerrar el caso.

![captura de pantalla 401](https://cloud.githubusercontent.com/assets/18584168/15325001/9ab2b280-1c12-11e6-9877-53be2d9b85d1.png)
![captura de pantalla 391](https://cloud.githubusercontent.com/assets/18584168/15325002/9ab65606-1c12-11e6-9f56-90c910dff88e.png)
