### ISSUE TITLE
BANKING WALLET - ERROR - al crear cuentas, sigue apareciendo el deposito que no se efectuó 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#288]
##### Reporte de error: 

Cree una cuenta, hice un deposito el cual nunca se efectúo, cerré la aplicación, entre de nuevo y el deposito seguía cargándose (sin éxito). Cree dos cuentas mas y el deposito seguía apareciendo en las tres cuentas cargándose sin realizarse.   

![capture-20160513-112958](https://cloud.githubusercontent.com/assets/17262077/15255543/5dc8a47e-1906-11e6-876f-5e3c6ec7182f.png)
![capture-20160513-113038](https://cloud.githubusercontent.com/assets/17262077/15255545/5f6a0a2a-1906-11e6-8487-68baad42cc03.png)
![capture-20160513-120816](https://cloud.githubusercontent.com/assets/17262077/15255547/6126c5f6-1906-11e6-8413-c5b41ebe5e6f.png)
![capture-20160513-120847](https://cloud.githubusercontent.com/assets/17262077/15255550/638980ea-1906-11e6-9dff-ee4f5e215d41.png)

#### Dispositivo desde donde se realizo la prueba

![capture-20160513-121555](https://cloud.githubusercontent.com/assets/17262077/15255562/7696f442-1906-11e6-94a1-ae6262d49fd1.png)

* Marca:Genymotion
* Modelo:Google Nexus 4
* Version de Android: 5.1.0

**Comment by abicelis** [comment]
@Gabymorillo Hmmm... Intenta replicar este error en la version v8 please :). Me avisas. @MaviDavsa

**Comment by Gabymorillo** [comment]
Revisado en la versión 9, ya no presenta esos errores.
