### ISSUE TITLE
CBP - Bank Wallet - No permite operaciones de montos mayores a 7 cifras

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#289]
##### Reporte de error: 

   *Al momento de intentar hacer un depósito por una cantidad mayor a 7 dígitos (pantalla 1), no permite. Es decir una cantidad superior o igual a 10.000.000 no deja ingresarla. 

##### Pantalla 1

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/15263142/37ec3cfa-1935-11e6-9c9f-66cfaacc9939.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15263154/4e2da27e-1935-11e6-9a00-6bcd2354862f.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @sanro14

**Comment by MaviDavsa** [comment]
@IsbetVR Issues creado!

**Comment by MaviDavsa** [comment]
Issues Creado pero con la Cash! Error mio! :)

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa Incremente el valor maximo de deposito/retiro a 99,999,999.99

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa un pequeño detalle, está colocando las cifras en notación científica, si, aumentó el valor máximo de la transacción pero lo pasa a notación científica, y al hacerlo efectivo en el  balance trunca y aproxima

#### Pantalla 1
![screenshot_10](https://cloud.githubusercontent.com/assets/19142276/15344298/e1ca609e-1c73-11e6-8765-f1859399b175.jpg)

#### Pantalla 2
![screenshot_11](https://cloud.githubusercontent.com/assets/19142276/15344324/fbee26ae-1c73-11e6-8b28-b1398b816f7f.jpg)

#### Pantalla 3
![screenshot_12](https://cloud.githubusercontent.com/assets/19142276/15344401/9eaab740-1c74-11e6-9deb-a1082cd2aa50.jpg)


#### Pantalla 4
![screenshot_13](https://cloud.githubusercontent.com/assets/19142276/15344340/1a08e890-1c74-11e6-9e41-136cdc71cfa4.jpg)

**Comment by abicelis** [comment]
@IsbetVR probaste en la version v9? yo arregle esto en la v9!

**Comment by IsbetVR** [comment]
@abicelis Ya funciona bien! :) @MaviDavsa 
Ya no trunca decimales, ni aproxima cifras, y no sale notación científica ni en el detalle ni en el resumen de transacciones, lleva bien la suma así sean valores pequeños.
Probado en la versión 9

![image](https://cloud.githubusercontent.com/assets/19142276/15410208/8b336ffe-1de6-11e6-9220-a63b1ae46bbc.png)

Dispositivo desde donde se realizó la prueba

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0.0

También fue probado en el Google Nexus 5, versión de android 5.1.0
