### ISSUE TITLE
CBP - Bank Wallet - Mejoras a botones de consulta de detalle de transacción (Account Detail)

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#290]
##### Reporte de error: (Recomendación)

   *Cuando una transacción se ha hecho efectiva, sea depósito o retiro, al momento de consultar el detalle de ésta (Pantalla 1), en la pantalla que muestra los datos (monto, fecha, tipo...) los botones en la parte superior que dicen "Cancel" en el lado superior izquierdo y "SAVE" en el lado superior derecho, a mi parecer son innecesarios, ya que no se va a modificar nada de la transacción si ya se hizo efectiva. Creo que con un sólo botón que diga "Volver" o "Atrás" sería suficiente. Cabe destacar que los botones "Cancel" y "SAVE" poseen la misma función que es regresar al listado de cuentas. 

#### Pantalla 1

![screenshot_18](https://cloud.githubusercontent.com/assets/19142276/15263479/7973d072-1938-11e6-9f8c-6a095804960a.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15263488/87a874d6-1938-11e6-8e1a-d16ef441003c.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @sanro14

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa Rehice esta pantalla, ahora trabaja igualmente como trabaja la cash wallet! Revisa y me dices :)

**Comment by IsbetVR** [comment]
Si! @abicelis sólo quedó el botón "Cancel", y si se cambia la leyenda para que no diga "Cancel"? jajaj, que indique "Atrás" o "Volver" o como en la Cash que sale la flecha y dice "Transaction detalis".
(Asumo que "Cancel" es Cancelar y no vamos a cancelar nada, sólo estamos consultando detalles de la transacción :P )

**Comment by abicelis** [comment]
@isbetVR no subí eso?  Todavía dice cancel?  Oops.. Haha.  En la v10 saldrá "back" como esta ahora y se me olvido subir :)

**Comment by IsbetVR** [comment]
@abicelis ehhhh no! jejej Vale! ;)

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa En la version v11 saldra este cambio :)

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11 quedo el Back y una flecha. Yo creo que se ve mejor solo la flecha pero no me disgusta el Back.

![6](https://cloud.githubusercontent.com/assets/18584168/15480175/ee8d8774-20ed-11e6-9c96-3293b2f2b4fe.png)

**Comment by IsbetVR** [comment]
Si @AdryCanonico quedó el "Back" con la flecha, No me parece que se vea mal, al contrario, le indica el usuario que es para regresar, parecido al Cash. 
Ahora sí @abicelis sale el "Back" ;) Mucho mejor! 
@MaviDavsa Listo! :)
