### ISSUE TITLE
BANKING WALLET - SIN LIMITE DE CARACTERES EN ALIAS APERTURA DE CUENTA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#291]
### BANKING WALLET 

-----

##### Reporte de error: 

   *No hay limite de caracteres para el Alias, cuando se esta creando la cuenta y te permite apertura así tenga mil caracteres.

Seria bueno que diera un limite de caracteres para el alias. 

![captura de pantalla 362](https://cloud.githubusercontent.com/assets/18584168/15264470/32b92786-193d-11e6-8507-7ab3d7d676a8.png)
![captura de pantalla 363](https://cloud.githubusercontent.com/assets/18584168/15264469/32b365e4-193d-11e6-9e9d-275a103cf395.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15264487/52568aac-193d-11e6-83a5-e58f6ce6880f.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
@abicelis En la version 7. Se limita los caracteres en el alias pero al momento de crearlo; pero seria bueno saber con cuantos caracteres dispones para esto. Como es en el caso para escribir un mensaje en twitter.

**Comment by abicelis** [comment]
@AdryCanonico Implemente esto en la version v11 en las pantallas de add y edit accounts.

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la version11 se corrige el error y funciona la cantidad de caracteres.
Se puede cerrar el caso

![1](https://cloud.githubusercontent.com/assets/18584168/15478909/1a00ef60-20e7-11e6-91f8-92da52eac096.png)
