### ISSUE TITLE
CBP - Bank Wallet - Permite crear cuenta sin datos en el campo "Alias"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#292]
#### Banking Wallet - Bank Wallet - Botón (+)

------

##### Reporte de error: 

   *Al intentar crear una nueva cuenta en la Bank Wallet, y omitir el campo de "Alias", permite crearla sin problema; debería lanzar una alerta e indicarle al usuario que debe ingresar el "Alias" para poderla crear.

##### Pantalla 1

![screenshot_23](https://cloud.githubusercontent.com/assets/19142276/15264648/ad06d7da-1943-11e6-9a70-e73dea037ec6.jpg)

##### Pantalla 2

![screenshot_24](https://cloud.githubusercontent.com/assets/19142276/15264654/bdfed560-1943-11e6-9f3c-7f6c694a9d34.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15264665/d766f67c-1943-11e6-8f02-0cb6d0d6e430.jpg)

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa @sanro14

**Comment by abicelis** [comment]
@IsbetVR la version v7 tiene esto arreglado!

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa Solucionado! :) 

Probado también en el Google Nexus 4, Versión 5.0.0
