### ISSUE TITLE
CBP - Cash Wallet 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#293]
##### Reporte de error: 

Cuando subo un deposito u retiro, para que se cargue rápido tengo que hacer otra transacción. 

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/15264748/d8dbea92-1940-11e6-9a2e-be7a6df5c67c.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/15264765/07f4044a-1941-11e6-8df5-f5c44cad8ca8.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@andreagmarcano no entiendo este issue

**Comment by MaviDavsa** [comment]
@abicelis Ale.. Por lo que entendí es que para que un deposito o retiro te salga debes hacer otro porque sino se queda cargando eternamente! :)

**Comment by andreagmarcano** [comment]
@MaviDavsa exactamente.

**Comment by abicelis** [comment]
Ok @MaviDavsa. @andreagmarcano cuando haya un chance nos reunimos y me muestras como haces que ocurra ese error plz!

**Comment by MaviDavsa** [comment]
@andreagmarcano  @abicelis  Amores! Hay que ver que haremos con este bug!

**Comment by abicelis** [comment]
El error aqui es un problema del BroadcastManager, esto es en el android-api y esta fuera de la CashWallet.

@nelsonalfo @furszy si pueden echarle un ojo a esto seria bueno:
```

En la linea 92 de CashMoneyWalletModuleManagerImpl.java 
hago una llamada a broadcaster.publish()

A veces funciona (llama al onUpdateViewOnUIThread() dentro del 
HomeFragment.java en el CashWallet) y a veces no.

Cuando no funciona, noto que en la linea 173 del BroadcastManager.java,
 fermatActivity.get() es null, y no pasa de ahi.

```

Basta con hacer dos o tres depositos para que a mi me de la falla.

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis Este issues en que quedo bellezas?

**Comment by abicelis** [comment]
@MaviDavsa Dame a la version 16.7, voy a apicar algo distinto que no use el codigo que no me funciona del broadcaster. Les aviso

**Comment by MaviDavsa** [comment]
Okay!

**Comment by AdryCanonico** [comment]
@andreagmarcano en la version 17 de CBP no da este error.
