### ISSUE TITLE
CBP - Bank Wallet - Permite crear cuenta sin datos en el campo "Account Number"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#294]
#### Banking Wallet - Bank Wallet - Botón (+) 

-----

##### Reporte de error: 

   *Al intentar crear una nueva cuenta en la Bank Wallet, y omitir el campo de "Account Number", permite crearla sin problema; debería lanzar una alerta e indicarle al usuario que debe ingresar el "Account Number" para poderla crear.

##### Pantalla 1

![screenshot_25](https://cloud.githubusercontent.com/assets/19142276/15264837/0d2b5eb8-1946-11e6-8562-d1518b834d9e.jpg)

##### Pantalla 2

![screenshot_26](https://cloud.githubusercontent.com/assets/19142276/15264841/1d89b264-1946-11e6-957a-07881c53d504.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15264843/2974c23a-1946-11e6-9891-a649f481523f.jpg)

**Comment by IsbetVR** [comment]
@abicelis @sanro14 @MaviDavsa

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa Listo, en la version v7 no te permite hacer una cuenta sin datos en al account number y lo limita a 25 caracteres maximo, solo numeros y dashes (-)

**Comment by IsbetVR** [comment]
@abicelis si!! @MaviDavsa Listo!! Funciona! 

Probado también en el Google Nexus 4, Versión 5.0.0
