### ISSUE TITLE
Cash Wallet-error al hacer retiro con cifras decimales.

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#295]
#### Nombre pantalla
Cash Wallet

##### Reporte de error: 

   *Tenia depositado en la CASH WALLET, 4.999.500,00 y quise hacer un retiro por 50,50 y el monto debitido en el balance apareció en notación científica 4.99945E+6 cuando debió ser: 4.999.449,50

![cash w-error al hacer retiro en centimos](https://cloud.githubusercontent.com/assets/17283358/15265302/93e9b20c-194a-11e6-9460-f80d16740e42.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:
Genymotion
![samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15265350/c2dd086a-194b-11e6-9d0f-081200f2f03e.png)

SAmsung Galaxy S6
* Version de Android:
5.1.0 API 22

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@yolandayancel @MaviDavsa Listo, esto esta arreglado en la version v7 del app. Revisen please!

**Comment by yolandayancel** [comment]
@abicelis 
Buenos días Alejandro
Prueba caso 295
17-05-16
Hice un retiro con decimales y lo realizo bien. Resuelto.
![error corregido cash 2](https://cloud.githubusercontent.com/assets/17283358/15322619/b16565a0-1c07-11e6-9c2d-c87fd59f19f5.png)

**Comment by yolandayancel** [comment]
Recibido

2016-05-16 20:57 GMT-04:30 Alejandro Bicelis <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> @MaviDavsa
> <https://github.com/MaviDavsa> Listo, esto esta arreglado en la version
> v7 del app. Revisen please!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/295#issuecomment-219595750>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by abicelis** [comment]
@MaviDavsa creo que podemos cerrar este !

**Comment by yolandayancel** [comment]
@MaviDavsa 
Si este caso está resuelto.

Cerrar
