### ISSUE TITLE
BANKING WALLET - BANNER ESTIRADO EN EL WIZZAR

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#296]
### BANKING WALLET

-----

##### Reporte de error: 

   *En esta version del emulador se ve estirado el banner en el wizzar.

![captura de pantalla 370](https://cloud.githubusercontent.com/assets/18584168/15289717/ceb072dc-1b3d-11e6-9090-ae154dae3375.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15289668/922f80d2-1b3d-11e6-909d-c7f349555706.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by Gabymorillo** [comment]
En la versión 9 presenta el mismo caso.

![capture-20160519-081240](https://cloud.githubusercontent.com/assets/17262077/15394049/5acf18be-1d9a-11e6-912f-36bb04cf54b0.png)


Marca: Genymotion
Modelo: Google NExus 7  5.0

**Comment by abicelis** [comment]
Listo, en la version v11 se arreglo este error para *este y todos los wizards* en dispositivos hdpi-long, como el Nexus 7 que se probo aca.

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la versión 11 se corrigió el error. Se puede cerrar el caso.

![2](https://cloud.githubusercontent.com/assets/18584168/15479889/528c8560-20ec-11e6-88d1-b2b3e5fbee3c.png)
