### ISSUE TITLE
CASH WALLET- BANNER ESTIRADO EN EL WIZZAR

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#297]
### CASH WALLET

-----

##### Reporte de error: 

   *En esta version del emulador se ve estirado el banner en el wizzar.

![captura de pantalla 369](https://cloud.githubusercontent.com/assets/18584168/15289653/7f2f986e-1b3d-11e6-9135-9d4cfcc427cc.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15289668/922f80d2-1b3d-11e6-909d-c7f349555706.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by Gabymorillo** [comment]
En esta versión presenta el mismo caso.


![capture-20160519-080004](https://cloud.githubusercontent.com/assets/17262077/15393649/4a7df0fe-1d98-11e6-93de-6947b12c0a60.png)


Marca: Genymotion
Modelo: Google Nexus 7  5.0

**Comment by abicelis** [comment]
@AdryCanonico @Gabymorillo Este error es de la gente de android-core, desde CBP no puedo hacer nada por estos dialogs que son genericos a todas las apps..
Les enviare la info a ellos para que resuelvan!

**Comment by Gabymorillo** [comment]
Ok, gracias.

**Comment by abicelis** [comment]
Listo, en la version v11 se arreglo este error para *este y todos los wizards* en dispositivos hdpi-long, como el Nexus 7 que se probo aca.

**Comment by AdryCanonico** [comment]
@abicelis En la version 11 sigue el banner con el error.

![1 c](https://cloud.githubusercontent.com/assets/18584168/15480763/0020ab26-20f1-11e6-8947-dd4a9fb5ab6a.png)

**Comment by abicelis** [comment]
Listo esto en la version v12 @AdryCanonico @Gabymorillo, revisen y me avisan.

**Comment by IsbetVR** [comment]
@AdryCanonico @Gabymorillo @abicelis @MaviDavsa 
Probado en la v12, en.:
Google Nexus 9
Versión android 5.1 
y no sale estirado el banner! Se ve bien.

![image](https://cloud.githubusercontent.com/assets/19142276/15523209/cdc643ce-21e6-11e6-969b-e2936bbf7791.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico  Yo verifique esto! Y en definitiva Solucionado!
