### ISSUE TITLE
BANKING WALLET - ERROR EN EL BALANCE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#298]
### BANKING WALLET

-----

##### Reporte de error: 

   *Al hacer depósitos que incluyan decimales, no los suma; sino que hace un redondeo de estos y da un resultado equivocado en el balance. El resultado de ambos depósitos, debería ser: 1.000.013,32

 
![captura de pantalla 375](https://cloud.githubusercontent.com/assets/18584168/15290404/0e16aa00-1b42-11e6-86ea-228701b9445c.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador
  
Emulador Derecho:

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15290483/8125f7c6-1b42-11e6-9c14-fc013fa828c2.png)

Emulador Izquierdo:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15290497/9951f2b4-1b42-11e6-8ff5-87a04c898dcf.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
El mismo error lo da con los retiros.
![captura de pantalla 376](https://cloud.githubusercontent.com/assets/18584168/15290842/cd298352-1b44-11e6-9fd0-0c680ce657bc.png)

**Comment by abicelis** [comment]
@AdryCanonico La version v8 de la aplicacion deberia calcular todo sin errores de redondeo! @MaviDavsa

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis En la V9 se corrigio el error. Se puede cerrar el caso.

![captura de pantalla 430](https://cloud.githubusercontent.com/assets/18584168/15410583/556b2184-1de4-11e6-9afb-d41a56bcaa26.png)
