### ISSUE TITLE
BANKING WALLET - FONDO APK PEQUEÑO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#299]
### BANKING WALLET  

-----

##### Reporte de error: 

   *En esta versión del emulador se ve pequeño el fondo en toda la apk

![captura de pantalla 378](https://cloud.githubusercontent.com/assets/18584168/15291662/e1a0b874-1b48-11e6-8ef4-53c3382896d9.png)
   
![captura de pantalla 380](https://cloud.githubusercontent.com/assets/18584168/15291661/e19f8d82-1b48-11e6-949b-37719f9bf513.png)

![captura de pantalla 379](https://cloud.githubusercontent.com/assets/18584168/15291663/e1ac05ee-1b48-11e6-89a5-11676fdcbf20.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15289668/922f80d2-1b3d-11e6-909d-c7f349555706.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by MaviDavsa** [comment]
@adryCanonico Bella no entiendo bien el issues...

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa  Al usar un dispositivo con altisimos dpi se produce eso: Si estas emulando una tableta o algo grande en una pantalla de pc (pequena?), veras las letras pequenas. Podria aumentar el tamano pero eso aumentaria el tamano a todo el mundo, incluyendo las letras en dispositivos pequenos.

**Comment by AdryCanonico** [comment]
@abicelis Lo mismo pasa con el:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15325100/164a7e64-1c13-11e6-98c1-027b89d5a6b5.png)

Solo el error es con el fondo morado

![captura de pantalla 388](https://cloud.githubusercontent.com/assets/18584168/15325165/53b3e420-1c13-11e6-97a1-5f12fb97de3d.png)

En esta vista se ve una linea blanca muy fina sobresaliendo del lado derecho de la pantalla

![captura de pantalla 393](https://cloud.githubusercontent.com/assets/18584168/15325246/9c5b7094-1c13-11e6-89de-4bcd70dc5330.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa  @abicelis  en la V9 se corrigio el error en ambos emuladores. Se puede cerrar el caso.

![ale5](https://cloud.githubusercontent.com/assets/18584168/15434701/05d567f8-1e82-11e6-878d-1a290413d5e5.png)

![ale 7](https://cloud.githubusercontent.com/assets/18584168/15434702/05da7e78-1e82-11e6-9594-dafd8a3a508c.png)
