### ISSUE TITLE
BANKING WALLET - ERROR AL HACER UN RETIRO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#300]
### BANKING WALLET

-----

##### Reporte de error: 

   *Realice un retiro y este sale cargando

![captura de pantalla 381](https://cloud.githubusercontent.com/assets/18584168/15293750/48e73490-1b53-11e6-94fa-655c7d5a1cd8.png)

 mientras carga, entro a la ficha de retiro y dice que fue echo hace 14 minutos pero no se hizo efectivo 

![captura de pantalla 382](https://cloud.githubusercontent.com/assets/18584168/15293802/6c39608a-1b53-11e6-9590-03942eec5b66.png)
 

y borra el retiro que se había intentado realizar. Solo pasa con los retiros, con los depositos se logra la acción efectivamente. 

![captura de pantalla 383](https://cloud.githubusercontent.com/assets/18584168/15293880/b8ae4c82-1b53-11e6-9921-4ce4e235c4ce.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador
  
![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15290483/8125f7c6-1b42-11e6-9c14-fc013fa828c2.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico Adry, este error esta corregido en la version v8!, Revisa y me dices :) @MaviDavsa

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis En la V9 se corrigio el error. Se puede cerrar el caso.


![captura de pantalla 429](https://cloud.githubusercontent.com/assets/18584168/15410481/d04a155a-1de3-11e6-8ac7-bdd42692aa43.png)

![captura de pantalla 428](https://cloud.githubusercontent.com/assets/18584168/15410482/d04b7544-1de3-11e6-840b-331fcc13050f.png)
