### ISSUE TITLE
Banking Wallet- error: permite hacer retiro de una cuenta (tomando los datos de otra cuenta)

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#301]
#### Nombre pantalla
Bank Wallet

##### Reporte de error: 

   *Estando en la Bank Wallet: hice retiro en una segunda cuenta creada sin tener depositado (en VEF), esta realizo el retiro tomando los datos de la primera cuenta. (ARS)

![bank w-permite hacer retiros sin tener depositos 1](https://cloud.githubusercontent.com/assets/17283358/15294477/2f6f68cc-1b56-11e6-9cdd-1938ee62c29e.png)

Tomo los datos de la primera cuenta
![bank w-permite hacer retiros sin tener depositos 2](https://cloud.githubusercontent.com/assets/17283358/15294514/64dfc40c-1b56-11e6-8c50-403f7a658221.png)

------

#### Dispositivo desde donde se realizo la prueba
![samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15294570/9716ddde-1b56-11e6-96b1-425b682060bb.png)

**Comment by MaviDavsa** [comment]
@yolandayancel Plantea mejor este caso!

**Comment by yolandayancel** [comment]
Buenas tarde María

Recibido

2016-05-16 12:08 GMT-04:30 MaViDavsa <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> Plantea mejor este
> caso!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/301#issuecomment-219475345>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
0426-9811123
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
caso:
La Bank Wallet: permite hacer retiros de una segunda  cuenta, que no tenia depósitos realizados (cuenta en VEF )
 Ya no me permite recrear nuevamente lo ocurrido ahora al abrir la segunda cuenta esta toma los datos de la primera cuenta (el deposito y el retiro)

![bank w-toma los datos de otra cuenta](https://cloud.githubusercontent.com/assets/17283358/15298228/1917da34-1b68-11e6-9103-a218316eb020.png)

   tomo los datos de la primera cuenta. lo probé nuevamente y sigue tomando los datos de la primera cuenta.

**Comment by yolandayancel** [comment]
@abicelis
Buenos días Alejandro
Prueba fecha 17/05/16
Caso 301
Este error no se puede probar ya que ahora la Bank Wallet no permite que se cree una cuenta sin primero llenar los datos como: número de cuenta y alias del usuario. Como consecuencia cada cuenta tiene sus propios datos. Resuelto.
![error resuelto bank](https://cloud.githubusercontent.com/assets/17283358/15322344/042cef94-1c06-11e6-8109-de7b2ef92420.png)
