### ISSUE TITLE
LPW-Gráfica de la estadística en el Home

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#302]
#### Reporte de error: 

   *La gráfica de las estadísticas del home, no muestra un mensaje o un valor que a mi como usuario de la aplicación me de a entender algo, solo muestra la gráfica dibujada. 
   
   
![image](https://cloud.githubusercontent.com/assets/5313324/15306937/b31eaf7a-1b9c-11e6-88b0-ef35ad66e287.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by nattyco** [comment]
@sanro14 verificar en la nueva version de apk, se le agregaron puntos al grafico para marcar los valores de perdida o ganancia de dolares.

**Comment by arosiopr** [comment]
@nattyco Ya sale información en la gráfica pero el monto sale cortado como se puede observar en la siguiente captura:

![screenshot_33](https://cloud.githubusercontent.com/assets/5313326/15541366/f386aa30-2255-11e6-846d-89eb37388e2a.png)

**Comment by sanro14** [comment]
@nattyco sería ideal que muestre la hora cuando doy click sobre la gráfica, es decir junto con el monto muestre la hora de ese cambio.

**Comment by AdryCanonico** [comment]
si,la hora seria excelente para darle al usuario una mejor información.

**Comment by nattyco** [comment]
ok, vemos que se puede hacer

**Comment by maydiamc** [comment]
en la grafica solo se muestra informacion de precio del btc, pero se sigue mostrando cortada en el primer y ultimo punto de la grafica, mejorar la ubicacion @nattyco 
![screenshot_2016-05-26-10-55-23](https://cloud.githubusercontent.com/assets/17274154/15579042/ba93aa34-232c-11e6-8079-fdd0adbf2d38.png)
![screenshot_2016-05-26-10-58-09](https://cloud.githubusercontent.com/assets/17274154/15579050/c01e8794-232c-11e6-9905-1e507bdbaac5.png)

**Comment by AdryCanonico** [comment]
@nattyco En la version 7 sigue cortando el texto en el primer y ultimo punto de la grafica

**Comment by sanro14** [comment]
@nattyco sigue sucediendo lo mismo en la versión 8

**Comment by IsbetVR** [comment]
En la versión 8 de la aplicación sigue cortando la leyenda en la gráfica

![screenshot_40](https://cloud.githubusercontent.com/assets/19142276/15660076/a64b3184-26a4-11e6-8a38-bb143dc7d390.jpg)

Dispositivo:
HTC One X
Versión de android: 4.2.2

**Comment by nattyco** [comment]
@sanro14  @MaviDavsa  se cambio la grafica la de la LPW verificar como se ve ahora que tiene otro formato

**Comment by maydiamc** [comment]
@nattyco en la version nueva mejoro la grafica debido a que se muestra una ficha para la informacion, sin embargo es recomendable que el valor cero "0" se centre en la grafica para que se muestren los valores de perdida, otra recomendacion es que los puntos de ganancia y perdida sean de distinto color para distinguir la informacion de manera mas amigable para el usuario.

Marca: Samsung Galaxy 
Modelo: Mini S4
Android: 4.4.2

**Comment by sanro14** [comment]
@MaviDavsa cierra esto!

**Comment by MaviDavsa** [comment]
Perfecto!
