### ISSUE TITLE
Aplicacion- Reproducción de mensaje de bienvenida no deja entrar a la aplicación

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#303]
##### Reporte de error: 

Al  intentar entrar la aplicación el mensaje de bienvenida aparece constantemente impidiendo que se pueda entrar a la aplicación,  generando al final un error. 

![capture-20160516-194108](https://cloud.githubusercontent.com/assets/17262077/15308073/19c6a84e-1ba3-11e6-9a7d-4d075ca0efa6.png)

![capture-20160516-195336](https://cloud.githubusercontent.com/assets/17262077/15308076/1d19b6ee-1ba3-11e6-934a-33cefd4b03f2.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 7
* Version de Android: 5.0.0

**Comment by alegnaire** [comment]
Similar, al intentar entrar a LPW se reproduce mensaje de Bienvenida de Fermat. Se reinicio el emulador pero el error persiste!!

Marca: Samsung
Modelo: S6
Versión de Android: 6.0.0

**Comment by nattyco** [comment]
@Gabymorillo  @alegnaire  verificar este reporte con la nueva version de la apk

**Comment by MaviDavsa** [comment]
Solucionado!

**Comment by danielaporras** [comment]
En la versión 14 de LPW sigue sucediendo esto (se repite el mensaje de bienvenida).

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15842699/495a5ffa-2c25-11e6-8138-71d23a8835d5.png)

**Comment by nattyco** [comment]
@danielaporras  @MaviDavsa  Aclarar el error, el mensaje de bienvenida se repite despues de seleccionar el check de no mostrar e ingresar nuevamente a la aplicacion?

**Comment by MaviDavsa** [comment]
La intro de fermat se me repite varias veces antes de entrar a la Wallet como tal.

![sdfsdfs](https://cloud.githubusercontent.com/assets/17273005/15913024/a2ab5924-2da1-11e6-84ca-69622152e19e.JPG)


![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15913046/b1e5f6ce-2da1-11e6-8eec-4f7654cf42ec.jpg)

**Comment by MaviDavsa** [comment]
Cuando entro a la Wallet el mensaje de Fermat se repite varias veces antes de entrar a la Wallet! 

![sdfsdfs](https://cloud.githubusercontent.com/assets/17273005/15913086/d76acb86-2da1-11e6-9f69-abeaf49576ff.JPG)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15913111/f3cc506a-2da1-11e6-8893-2fe429b5c69b.jpg)

**Comment by danielaporras** [comment]
En la version 15.1 de LPW se sigue repitiendo este error.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15915239/74ae51b0-2db1-11e6-86f6-81f442885297.png)

**Comment by nattyco** [comment]
@furszy

**Comment by furszy** [comment]
Si vuelve a aparecer el mensaje puede ser por dos cosas, 
A) la app que abriste explotó 
B) nunca te abrió la app

Si la app que abriste explotó diganse lo al dueño de la app por favor

**Comment by MaviDavsa** [comment]
@nattyco En este caso has sido tu la dueña! :)

**Comment by MaviDavsa** [comment]
Natty! En la nueva versión corrio el mensaje solo una vez y todo fue normal!  En la ultima versión 15.2

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15929942/f10115fa-2e19-11e6-9595-044530e34736.jpg)

**Comment by arosiopr** [comment]
en la versión 16 de la LPW el mensaje de bienvenida se repite dos veces asi el check de no mostrar mas este seleccionado. A la tercera vez deja ingresar. solo una sola vez me ha dejado ingresar sin este error 

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/15964048/4ebadebc-2ee0-11e6-8af9-1f6b64aafed3.png)

**Comment by danielaporras** [comment]
En  la versión 16.1 se sigue repitiendo el mensaje de bienvenida.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15968371/76bca1b0-2ef5-11e6-849e-cf15316f8752.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by AdryCanonico** [comment]
@nattyco en la versión 17 sigue repitiéndose el dialogo de bienvenida

**Comment by maydiamc** [comment]
@nattyco persiste el problema en la version 17
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025531/cc1d0b88-3191-11e6-9f56-8726e3bfd46d.png)

**Comment by IsbetVR** [comment]
En la versión 19.8 de CBP persiste este problema, repite el mensaje de bienvenida 2 veces para dejar ingresar como tal a la aplicación.


![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16656879/59f58ff8-442e-11e6-8a6b-bb8de56a9cca.jpg)

**Comment by MaviDavsa** [comment]
En la versión 19.8 de CBP persiste este problema, repite el mensaje de bienvenida 2 veces para dejar ingresar como tal a la aplicación.

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16657186/87220d0c-442f-11e6-8a97-fe4026104175.jpg)

**Comment by sanro14** [comment]
en la versión 19.9 ya esta resuelto el error

**Comment by marielis-urbina** [comment]
En esta versión 20.1, en mi caso no me pasa

![samsung](https://cloud.githubusercontent.com/assets/19353722/16687092/52db05a2-44e4-11e6-8815-90543bb54b45.png)

**Comment by arosiopr** [comment]
en la version 20.1 de CBP sigue sucediendo estre error, se repite dos veces el aviso de entrada luego si entra.
![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16687179/f6503a0e-44e4-11e6-9a16-65bf13a47ed6.png)

**Comment by MaviDavsa** [comment]
Por lo menos en mi versión ya el mensaje de bienvenida sale una sola vez... Estoy desde un teléfono físico. 

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16687485/f0c698e2-44e6-11e6-9280-5f7d32ec29f4.jpg)

**Comment by Gabymorillo** [comment]
En la versión 20.1 en mi teléfono aparece dos veces el mensaje de bienvenida, a diferencia de que luego deja entrar a la aplicación. 

![screenshot_2016-07-08-07-55-35](https://cloud.githubusercontent.com/assets/17262077/16688128/76e0c490-44ea-11e6-95d0-7defdf623c41.png)

![screenshot_2016-07-08-07-56-02](https://cloud.githubusercontent.com/assets/17262077/16688079/365437ae-44ea-11e6-8c05-e3c4f1d71698.png)

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16688086/3e69ae6a-44ea-11e6-8407-77e624ec5904.png)

**Comment by maydiamc** [comment]
en la version 20.1 de CBP no se repite el mensaje en el emulador

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16688290/6a1020fc-44eb-11e6-81b0-079899bfc1fb.png)

**Comment by furszy** [comment]
Por favor alguna paseme el log

**Comment by arosiopr** [comment]
@furszy 
[Google Nexus 4 - 4.4.4 - API 19 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354301/Google.Nexus.4.-.4.4.4.-.API.19.-.768x1280-logcat.txt)

**Comment by furszy** [comment]
ahí subi algunos cambios, nada con respecto a este issue por el momento. Te quedaste sin conexión por un tiempo por lo visto.

**Comment by arosiopr** [comment]
a ok gracias @furszy

**Comment by Gabymorillo** [comment]
En la versión 20.4 en el teléfono físico aun se repite el mensaje 2 veces. 

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16770068/34040808-4819-11e6-819c-2063265aa2a9.png)

**Comment by dorzar1989** [comment]
En la Version 20.4 de la CBP  persiste este error.

Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16770142/8c748774-4819-11e6-8107-9efbda27a77c.png)

**Comment by Gabymorillo** [comment]
En la versión 20.6 en el teléfono físico, persiste el error. 

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16882762/b34fe452-4a8e-11e6-86ee-93d2783a83a1.png)

**Comment by AdryCanonico** [comment]
en la version 20.7 de cbp persiste el error en teléfono fisico

**Comment by dorzar1989** [comment]
En la version de 20.9 de la CBP se me repitio el mensaje de Bienvenida, pero si me dejo entrar a la APK

- Screenshot:

![screenshot_65](https://cloud.githubusercontent.com/assets/19670319/17066587/b9b4805a-5015-11e6-9523-c79c1f58eb89.png)

-Emulador: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17066586/b72034f6-5015-11e6-8fe4-36f6d5b2b5a6.png)

**Comment by Hernandezsmanu** [comment]
En la version 21.0, desde mi teléfono físico repitió el mensaje de bienvenida 2 veces pero si me dejo entrar a la aplicación. 

![screenshot_2016-07-28-13-46-10](https://cloud.githubusercontent.com/assets/5313335/17226975/168b0254-54da-11e6-8688-c660d40677d9.png)

**Comment by danielaporras** [comment]
En la version 21.0 se repite varias veces el mensaje de bienvenida no deja entrar a la apk.
Prueba realizada desde emulador.
![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/17233156/6e40e092-54fb-11e6-9063-ce90cd26ed6b.png)

**Comment by furszy** [comment]
Ya está resuelto, esperen a la otra versión.

**Comment by GeronimoVierma** [comment]
En la versión 21.1 no se repite el mensaje de bienvenida:

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17253029/f016f7b0-557c-11e6-8ae2-f0601ea4936e.png)

**Comment by Gabymorillo** [comment]
En la versión 21.1 de la CBP, desde el emulador aún muestra el mensaje 2 veces antes de poder entrar.

![capture-20160729-131845](https://cloud.githubusercontent.com/assets/17262077/17257320/8dda6c36-558f-11e6-8f32-52db8a1ee48d.png)

![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17257321/90dad25e-558f-11e6-8878-15d7cb3eccb2.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/391027/logcat.txt)

**Comment by Gabymorillo** [comment]
En la versión 21.3 de la CBP desde el emulador aún se repite el mensaje de bienvenida 2 veces antes de entrar.

![capture-20160802-150528](https://cloud.githubusercontent.com/assets/17262077/17341546/136b4178-58c3-11e6-8a69-b0bdca07450e.png)


![capture-20160721-175754](https://cloud.githubusercontent.com/assets/17262077/17341517/f1ac89ac-58c2-11e6-965f-e4203a9880e9.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/397908/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 03-08-16
Caso 303 CBP V21.3
Samsung S6 5.1.0 api22 640dpi
No ocurre lo reportado.. No se repite el mensaje  de Bienvenida..

**Comment by Gabymorillo** [comment]
En la versión 21.6 de CBP desde el emulador no sucede este error.

**Comment by gablup** [comment]
En la versión 21.6 de CBP probado desde un dispositivo físico ya no ocurre. 

![acerca del tlf](https://cloud.githubusercontent.com/assets/17261437/17446632/20441b20-5b18-11e6-8d00-9d1eff8f4596.png)

Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB.

**Comment by IsbetVR** [comment]
Closed #303
