### ISSUE TITLE
Chat- Fermat Chat-Las letras del fondo (no contacts) están muy claras

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#304]
#### Nombre pantalla
Fermat Chat- Contacts

##### Reporte de error: 

   *Estando en el Fermat Chat, el fondo está muy claro, casi no se puede leer

![error grafico- muy claro](https://cloud.githubusercontent.com/assets/17283358/15324137/08e26b78-1c0f-11e6-89b1-547dd441ac88.png)

   
------

#### Dispositivo desde donde se realizo la prueba
![samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15324154/1a583f36-1c0f-11e6-8e9a-18c6f86c27bd.png)

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@MaviDavsa Es parte del diseño aprobado por la parte de diseño grafico.

**Comment by MaviDavsa** [comment]
Perfecto! @yolandayancel Ya no se puede hacer nada en cuanto a eso! Sin embargo @franklinmarcano1970 lo voy a dejar como una experiencia de usuario, luego me dices si definitivamente se quedará así o si pueden hacerlo un poco mas visible!

**Comment by franklinmarcano1970** [comment]
@MaviDavsa Dale perfecto...

**Comment by franklinmarcano1970** [comment]
Otra cosa que no tomamos esta no es la version actual que le pasamos, por favor, revisen con que version estan trabajando!!!!!

**Comment by josejcb** [comment]
Si, porque ese no es el icono del buscador actual, ni el icono de ayuda actual, ni el icono de No chats... borren cualquier apk que tengan por alli antes de bajar el nuevo para que no se confundan al instalar.

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 @josejcb Pero si la versión que esta utilizando es el Android 5.1... Debe ser mas alto que ese? Y @josejcb Perfecto! Yo se lo recuerdo a las chicas!

**Comment by franklinmarcano1970** [comment]
No es la version de android es la version de la app instalada, proque ese fondo ya no existe en esta version de la app de chat!

**Comment by yolandayancel** [comment]
@franklinmarcano1970 
Prueba de fecha 18/05/2016
Verificación de lo ocurrido ayer Caso 304):
Fue un error en la descarga (se descargo la CBP V7) y era la CHAT-1
