### ISSUE TITLE
CHAT-Chat community-error al ingresar Go to Chat

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#305]
#### Nombre pantalla
Chat Comunity- Go to chat

##### Reporte de error: 

   *Estando en el Chat comunity y pisar el botón de retroceso para ir a GO TO CHAt sale el recuadro:

![error chat community 2](https://cloud.githubusercontent.com/assets/17283358/15326476/fb7fb536-1c17-11e6-9a40-ab12ca832219.png)

Luego se sale
![error chat community 3](https://cloud.githubusercontent.com/assets/17283358/15326577/558edcfa-1c18-11e6-8740-58a97d16b13f.png)

#### Dispositivo desde donde se realizo la prueba
![samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15326408/af503bc2-1c17-11e6-8757-66985fa3baf7.png)

**Comment by yolandayancel** [comment]
@abicelis
Alejandro 
En prueba 17-05-16 
caso #305
No aparece el Go to chat, no puedo replicar el error para probar
![error chat- no aparece go to chat](https://cloud.githubusercontent.com/assets/17283358/15327916/f2a587a6-1c1c-11e6-8eb6-b784fe6ff4c7.png)

**Comment by franklinmarcano1970** [comment]
@yolandayancel @MaviDavsa Porque no hay un boton Go To Chat, debes darles atras para que te lleve al icono en el desktop, podria ser una recomendacion para colocar en la siguiente version.

**Comment by franklinmarcano1970** [comment]
Otra cosa que no tomamos esta no es la version actual que le pasamos, por favor, revisen con que version estan trabajando!!!!!

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Pero esta versión es 5.1

**Comment by franklinmarcano1970** [comment]
Me refiero a la version de la app de chat que instalaron, no a la version de android, porque el boton GOO CHAT no existe en esa app.

**Comment by MaviDavsa** [comment]
okay @franklinmarcano1970 Entiendo! @yolandayancel Revisa bien por favor!

**Comment by yolandayancel** [comment]
@franklinmarcano1970 

Prueba de fecha 18/05/2016
Verificación de lo ocurrido ayer Caso 305):
Fue un error en la descarga (se descargo la CBP V7) y era la CHAT-1
