### ISSUE TITLE
CHAT - IMAGEN COMPRIMIDA EN PERFIL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#306]
### CHAT

-----

##### Reporte de error: 

   *Se ve comprimida la foto del perfil cuando se crea.
   

![captura de pantalla 404](https://cloud.githubusercontent.com/assets/18584168/15327872/c7420fe4-1c1c-11e6-82f4-88b3b05eecb1.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion
 

Emulador derecho:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15327887/d41143f2-1c1c-11e6-9937-e78a51806d51.png)

Emulador Izquierdo:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15327913/f0474bd4-1c1c-11e6-969a-a86e68776c39.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Issuer developer:
https://github.com/Fermat-ORG/fermat/issues/6201

**Comment by AdryCanonico** [comment]
@franklinmarcano1970  @MaviDavsa En la version 2 se corrige el error. Se puede cerrar el caso.

![imagen comprimida](https://cloud.githubusercontent.com/assets/18584168/15477700/e1c52762-20df-11e6-9939-13887839ba2a.png)
