### ISSUE TITLE
CHAT - ICONO DE AYUDA REPETIDO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#307]
### CHAT

-----

##### Reporte de error: 

   *Al momento de ingresar a la pestaña de Contacs se repite el icono de ayuda y tiene la misma info.

![captura de pantalla 406](https://cloud.githubusercontent.com/assets/18584168/15328767/d7b17452-1c1f-11e6-9bd0-bab83c28e603.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion
 

Emulador derecho:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15327913/f0474bd4-1c1c-11e6-969a-a86e68776c39.png)

Emulador Izquierdo:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15327887/d41143f2-1c1c-11e6-9937-e78a51806d51.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by fabianazabala** [comment]
Relacionado a este bug: al abrir cualquiera de esos dos íconos de ayuda, se debe presionar el botón de CLOSE dos veces para cerrar la ventana de ayuda. Con la ayuda que está en la sección de Chats esto no pasa.

**Comment by AdryCanonico** [comment]
@MaviDavsa @franklinmarcano1970 En a version 2 ya esta corregido el error y con un click cierra. Se puede cerrar el caso

![ayuda](https://cloud.githubusercontent.com/assets/18584168/15477651/9195a1b8-20df-11e6-8f5d-3e1e7c25d74b.png)
