### ISSUE TITLE
CHAT - DUPLICA FOTOS EN EL EMULADOR

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#309]
### CHAT

-----

##### Reporte de error: 

   *Si se utiliza el botón para girar la foto en la creación del perfil 

![captura de pantalla 413](https://cloud.githubusercontent.com/assets/18584168/15330338/473e2576-1c26-11e6-8327-727ad5252bf4.png)

![captura de pantalla 408](https://cloud.githubusercontent.com/assets/18584168/15330346/500aab66-1c26-11e6-9c6c-d8db5521fa2e.png)

este duplica la foto en el emulador (galería) tantas veces se gire la foto. Ocupando memoria en el dispositivo. 

![captura de pantalla 407](https://cloud.githubusercontent.com/assets/18584168/15330378/691b2a86-1c26-11e6-9cf6-6fc5015de5eb.png)
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion
 

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15327913/f0474bd4-1c1c-11e6-969a-a86e68776c39.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15327887/d41143f2-1c1c-11e6-9937-e78a51806d51.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
si es correcto porque asi funciona cada rotado que se le haga es una imagen nueva que se crea, ya que a la final tenemos que manejarlo de esa forma porque para android es una imagen diferente!!!!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970  Me podrías aclarar una duda? el botón de rotar es utilizado dentro de la aplicación como un editor de imágenes? como lo tiene Instagram, que cuando se le hacen cambios a la imagen en su editor se agrega una foto nueva a la galería de tu teléfono.

Porque si es un editor de imágenes, debería de tener opciones adicionales como: Cortar la foto, zoom...
o los cambios de rotar son solo dentro de la aplicación de chat como en el caso de Facebook?

**Comment by franklinmarcano1970** [comment]
@AdryCanonico no es editor de imagenes solo es un rotador de imagen.

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 Si es así no debería duplicar la foto tantas veces se gire sin antes salvar en el perfil.

**Comment by franklinmarcano1970** [comment]
@AdryCanonico Esto ya esta resuelto subiremos el apk en el transcurso de la mañana que estoy esperando por otros cambios!!!
