### ISSUE TITLE
CHAT - PERMITE BORRAR CHAT SIN CONVERSACIONES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#310]
### CHAT
-----

##### Reporte de error: 

   *Permite borrar todos los chat, sin haber mensajes en la bandeja.

![captura de pantalla 415](https://cloud.githubusercontent.com/assets/18584168/15331609/ee8e634a-1c2b-11e6-85f0-e38f19453a5a.png)

![captura de pantalla 411](https://cloud.githubusercontent.com/assets/18584168/15331628/03c9385c-1c2c-11e6-921e-348e7a92f9d5.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion
 

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15327913/f0474bd4-1c1c-11e6-969a-a86e68776c39.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15327887/d41143f2-1c1c-11e6-9937-e78a51806d51.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@AdryCanonico @MaviDavsa si se puede que te impide porque a la final lo que se quiere es borrar el chat...

**Comment by franklinmarcano1970** [comment]
Issuer developer:
https://github.com/Fermat-ORG/fermat/issues/6203

**Comment by AdryCanonico** [comment]
@franklinmarcano1970  si, sale el mensaje de confirmacion aunque no haya conversacion a borrar.

**Comment by AdryCanonico** [comment]
@MaviDavsa  @franklinmarcano1970 En la versión 2 ya se corrigió. Se puede cerrar el caso

![captura de pantalla 461](https://cloud.githubusercontent.com/assets/18584168/15474335/3b0108e4-20ce-11e6-84df-1b0e3af25e34.png)
