### ISSUE TITLE
LPW - Error en home 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#311]
##### Reporte de error: 

   No se refleja el tipo de cambio en tiempo real.

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/15341139/cf3b2174-1c56-11e6-9b2c-76e0e29de73d.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/15341168/fe3edb0a-1c56-11e6-9159-b34be64bf5ff.png)

**Comment by nattyco** [comment]
@andreagmarcano  no te mostro un mensaje al entrar al home? si no trae la cotizacion es un error de que no puede conectar con el proveedor.

**Comment by andreagmarcano** [comment]
No, hice el procedimiento, cambie la red y nada. @nattyco

**Comment by nattyco** [comment]
@andreagmarcano  verificar en la nueva version de la apk

**Comment by andreagmarcano** [comment]
@nattyco ya verifique y no me salio este error.
