### ISSUE TITLE
CHAT - Sin Límite de caracteres para crear el "User Name" en "Profiles"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#315]
##### Reporte de error: 

   *No hay limite de caracteres para el "User Name", cuando se está creando el perfil, permite apertura así tenga cientos de caracteres (Pantalla 1), al revisar "Communities", en Chat Community, y verificar el perfil (Pantalla 2) se puede observar que muestra los cientos de caracteres y en un cierto punto corta. En las pantallas 3 y 4, se puede observar como el otro usuario a través de "Communities" para establecer la conexión, puede observar el perfil que he creado con los cientos de caracteres.
Sería ideal que se estableciera un límite de caracteres.

------
#### Pantalla 1
![screenshot_14](https://cloud.githubusercontent.com/assets/19142276/15359399/1c70cf2c-1cd7-11e6-825a-dabcb8a4eb86.jpg)

#### Pantalla 2
![screenshot_15](https://cloud.githubusercontent.com/assets/19142276/15359474/8a29f930-1cd7-11e6-96fb-f8572f783a1d.jpg)

#### Pantalla 3
![captura de pantalla 417](https://cloud.githubusercontent.com/assets/19142276/15359887/56a882dc-1cd9-11e6-8c9b-63c678acdadd.png)

#### Pantalla 4
![captura de pantalla 418](https://cloud.githubusercontent.com/assets/19142276/15359879/50a88be8-1cd9-11e6-9c71-6db1b0c17279.png)

------

#### Dispositivo desde donde se realizó la prueba (Pantalla 1 y 2)

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15363157/c74a3100-1ce5-11e6-937b-c7ad39a24f19.jpg)

#### Dispositivo desde donde se realizó la prueba (Pantalla 3 y 4)

* Marca: Genymotion
* Modelo: Google Nexus 7
* Version de Android: 5.1.0

![captura de pantalla 419](https://cloud.githubusercontent.com/assets/19142276/15359867/476251c2-1cd9-11e6-991e-8ea611faf0fb.png)

**Comment by IsbetVR** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Si no hay limite, dejanos evaluar!!!1

**Comment by IsbetVR** [comment]
@franklinmarcano1970 creo que es innecesario tantos caracteres para el User Name", además ocupa mucho espacio en pantalla al ver detalles de perfil o hacer una solicitud a dicho usuario como se mostró en la Pantalla 4. Gráficamente no se ve agradable (Pantalla 2, 3 y 4)

**Comment by franklinmarcano1970** [comment]
@IsbetVR @MaviDavsa Bueno es cuestion de analizarlo y ponernos de acuerdo cuanto caracteres podemos colocar!!!!

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 Correcto! Algo como WhatsApp seria ideal! :)

**Comment by MaviDavsa** [comment]
@IsbetVR Este issues esta solucionado
