### ISSUE TITLE
CHAT-Chat community-error: los request sent se quedan pendientes de aceptar

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#316]
#### Nombre pantalla

Chat Community

##### Reporte de error: 

   *En el Chat comunity se enviaron dos solicitudes de connection, las cuales después de más de una hora todavía sigue apareciendo pendiente de respuesta ( a pesar de que loas conexiones fueron aceptadas). Cerramos emuladores y reiniciamos dos veces, pero igual sigue pendiente de aceptar.

![error -chat community- nunca llega la coneccion usuarios](https://cloud.githubusercontent.com/assets/17283358/15363247/e911775c-1ce1-11e6-84bb-4df472c6936f.png)

Este es uno de los request

![error -chat community- nunca llega la coneccion usuarios 1](https://cloud.githubusercontent.com/assets/17283358/15363336/3bbb8e16-1ce2-11e6-83e8-5915d2fc6d26.png)

   
------

#### Dispositivo desde donde se realizo la prueba
![samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15363404/7012503c-1ce2-11e6-8b7b-2973aadb0502.png)

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@MaviDavsa Si te fijas, te sale en amarillo es porque ya le envio la conexion al remoto, ahora desde el remoto tienes que ubicar la Notifacion para aceptarla, ahora sino te llega por algun problema de P2P, que no envio la solicitud de vuelta, vuelve a enviar la solicitud!.

**Comment by MaviDavsa** [comment]
@yolandayancel  En mi Emulador ya se corrigió este problema, de todas maneras como el caso es tuyo pruebalo y me avisas!

**Comment by yolandayancel** [comment]
@franklinmarcano1970 
Buenos días
Prueba 25-05-16

Caso 316
Error persiste
Explicación:
Cuando Adry 1 evió una solicitud, a los pocos minutos apareció en las notificaciones, pero sigue saliendo el contacto en amarillo ( Pending acceptance).
![error -chat- connection 1](https://cloud.githubusercontent.com/assets/17283358/15540646/589d6340-2252-11e6-9a32-6b34e2955b2d.png)
![error -chat- connection 2](https://cloud.githubusercontent.com/assets/17283358/15540649/5fcff13c-2252-11e6-8ecd-92b3e7fa866c.png)
![error -chat- connection 3](https://cloud.githubusercontent.com/assets/17283358/15540656/6679cd6e-2252-11e6-91e9-ff0d4dfae3ea.png)

Desde que recibí la notificación,  se sigue esperando el accept connectíon de Adry 
![error -chat- connection 4](https://cloud.githubusercontent.com/assets/17283358/15540796/1c229402-2253-11e6-8f8c-8fb9a56f69e5.png)

**Comment by yolandayancel** [comment]
@franklinmarcano1970 
Franklin
Cuando volvi a hacer la solicitud, inmediatamnete aparecio en verde Adry1 y la notificación ya no está
Saludos

**Comment by franklinmarcano1970** [comment]
@yolandayancel @MaviDavsa Si te fijas, te sale en amarillo es porque ya le envio la conexion al remoto, ahora desde el remoto tienes que ubicar la Notifacion para aceptarla, ahora sino te llega por algun problema de P2P, que no envio la solicitud de vuelta, vuelve a enviar la solicitud!, estamos atados a P2P, porque nucna llega al remoto la solictud, solo intenta eliminando y borrando data y probando...

**Comment by yolandayancel** [comment]
@franklinmarcano1970 
Prueba 04-07-16
Caso316 CHAT- CBP19.2
Samsung S6 5.1.0 api22 640dpi
Cerrar el caso. Ya se realizan las conenntion en la Community
![caso316](https://cloud.githubusercontent.com/assets/17283358/16568370/43da4af8-41f7-11e6-81de-1937a463932b.png)
[logcat316.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346748/logcat366.txt)
