### ISSUE TITLE
Communities - CHAT - No aparecen los usuarios que están "Offline" en "CHAT" para establecer la conexión a través de "Communities"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#317]
##### Reporte de error: 

   *Luego de establecer las conexiones con los usuarios a través de "Communities", sólo muestra en el "Chat Community"  (Pantalla 1) los usuarios que están "online" En el "CHAT", pese a que en "Contacts" (Pantalla 2) están todos los usuarios con los que he establecido conexión. Debería salir "Offline" si el usuario no se encuentra conectado en el "CHAT". Esto quiere decir, que si el usuario está creando su perfil, si no entra al "CHAT", los demás usuarios NO pueden saber de su existencia para establecer la conexión a través de la "Communities". Como se puede observar en la pantalla 3 y 4, el usuario "Adry5" ya no está "online" en "CHAT" (Pantalla 4) y no me aparece en la "Communities" (Pantalla 3) ni siquiera "Offline".

------
#### Pantalla 1

![screenshot_18](https://cloud.githubusercontent.com/assets/19142276/15362892/c995d320-1ce4-11e6-9f6c-48b16b7a6e3f.jpg)

#### Pantalla 2

![screenshot_19](https://cloud.githubusercontent.com/assets/19142276/15362908/d4b94282-1ce4-11e6-9d78-6b6045d55bd1.jpg)

#### Pantalla 3

![screenshot_20](https://cloud.githubusercontent.com/assets/19142276/15362939/edd1431e-1ce4-11e6-8f46-59c30be423f9.jpg)

#### Pantalla 4

![screenshot_21](https://cloud.githubusercontent.com/assets/19142276/15362951/f5e9a55a-1ce4-11e6-970c-0090a3ad0f6d.jpg)

------

#### Dispositivo desde donde se realizó la prueba

* Marca: Genymotion 
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15363206/f2726db6-1ce5-11e6-802c-e6c4b60c5cd2.jpg)

**Comment by IsbetVR** [comment]
@franklinmarcano1970 @MaviDavsa

**Comment by franklinmarcano1970** [comment]
Eso no es un error como vas a chatear con alguien que no esta en linea, porque recuerda que las comunidades son para poder conseguir a alguien, y conectarte una vez que ya esten conectados, se convierten en contactos de Chat, pero eso no significa que este en linea, por eso te muestra la ultima conexion que es parte del Bounty, por eso en la foto de la pantalla 4te muestra la ultima conexion.

**Comment by JDVilchez** [comment]
Una vez que el usuario se va offline, deja de aparecer en la community y solo puedes verlo en connections, es un comportamiento normal de las communities. Una vez que un usuario crea su perfil, aparecerá en la community siempre y cuando tenga fermat corriendo, y solo aparecerá en el chat de alguien una vez que se haya establecido una conexión entre ambos.

**Comment by franklinmarcano1970** [comment]
Este caso esta correcto, debemos de cerrarlo con la explicacion de @JDVilchez @MaviDavsa @IsbetVR

**Comment by franklinmarcano1970** [comment]
@MaviDavsa @IsbetVR Los que esten offline no van aparecer en la comunidad, la comunidad solo muestra lo que esten en linea, si tu quieres enviarle a alguien no online, solo enviale y cuando el se conecte le llegara el mensaje, asi de facil
