### ISSUE TITLE
CHAT - DUPLICA EL USER NAME EN LA FICHA DE CONTACTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#319]
### CHAT

-----

##### Reporte de error: 

   *Se duplica el user name en el contact profile

![captura de pantalla 423](https://cloud.githubusercontent.com/assets/18584168/15366610/f0e98426-1cee-11e6-8ba8-a069e47fe3c4.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Emulador
* Modelo:Genymotion

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15363671/43684ba8-1ce3-11e6-92ee-b111cc8ebb33.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15363672/436f8eb8-1ce3-11e6-8095-15abf88b464e.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@AdryCanonico En mi Emulador ya se corrigió este problema, de todas maneras como el caso es tuyo pruebalo y me avisas!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 en la versión 4 ya no se repite el name pero no se ve el user.

![4 ficha de contacto](https://cloud.githubusercontent.com/assets/18584168/15521621/82e4d59c-21d6-11e6-86a0-647aea5128bb.png)

**Comment by franklinmarcano1970** [comment]
Pero el user no es Roy?

**Comment by AdryCanonico** [comment]
disculpa @franklinmarcano1970  el status

**Comment by josejcb** [comment]
En esta pantalla no se pensaba mostrar el estatus de momento pero se puede hacer para una siguiente versión ya que se tiene pensado agregar mas información relacionada al usuario.
