### ISSUE TITLE
CBP-Broker- Grafica del Home

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#320]
##### Reporte de error: 

   *La gráfica del home, no especifica lo que quiere reflejar, no hay algo que me diga como usuario que esta refiriéndose a la variación del valor de la moneda según mi proveedor en una semana.. 

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android:5.0

**Comment by sanro14** [comment]
@vlzangel

**Comment by nelsonalfo** [comment]
yo @nelsonalfo tomaré esta tarea

**Comment by nelsonalfo** [comment]
si tienes alguna sugerencia de como pudiéramos solucionar el problema te lo agradeceríamos, ya que tu funges como el Usuario Final de la aplicación y tu opinión es valiosa en ese aspecto

**Comment by sanro14** [comment]
mi sugerencia es que cuando yo coloque el puntero del mouse sobre la gráfica en cierto punto, me muestre un ToolTip con el valor en ese momento junto con la hora, me explico que exprese algo, para que pueda yo interpretarlo y no tenga que intuir que es..

**Comment by sanro14** [comment]
@nelsonalfo

**Comment by IsbetVR** [comment]
@nelsonalfo estoy de acuerdo con @sanro14 en cuanto a la interpretación de la gráfica. Yo como usuario no sé que interpretación darle, no me transmite información alguna. No sé, mi pregunta sería que quieren reflejar allí? movimientos? porque si observo la gráfica que muestro en la capture de pantalla, estoy apenas configurando la Wallet del Broker, no se como interpretar lo que allí me muestra

![screenshot_69](https://cloud.githubusercontent.com/assets/19142276/15981348/2f0bc54c-2f42-11e6-8576-57c73e58bcca.jpg)

**Comment by abicelis** [comment]
@sanro14 @IsbetVR Decidimos eliminar la grafica del Broker Wallet temporalmente, hasta que consigamos una que se vea/refleje mejor la informacion que queremos mostrar.
Cerrar este issue please

**Comment by MaviDavsa** [comment]
@sanro14 Es cierto! Procederemos a Cerrarlo!
