### ISSUE TITLE
CBP-Broker-Duplicación de Información 

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#321]
##### Reporte de error: 

   *En el Broker cuando configuro my locations, a pesar de haber insertado una sola vez la información, se ve duplicada.
![issue2](https://cloud.githubusercontent.com/assets/5313324/15379772/673bc496-1d3e-11e6-97e7-2bee4a18a6da.png)

   
#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android:5.0

**Comment by sanro14** [comment]
@vlzangel

**Comment by nelsonalfo** [comment]
@vlzangel por favor encárgate de esta tarea

**Comment by nelsonalfo** [comment]
En la versión 10 del la app esta la corrección  de este bug

**Comment by nelsonalfo** [comment]
Se pudo probar nuevamente?

**Comment by sanro14** [comment]
@MaviDavsa Cerrar!
