### ISSUE TITLE
CBP-Broker-Valores Negativos

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#322]
##### Reporte de error: 

   *En el Stock Management, se muestran los valores de mis wallets negativos. Ver Figura Adjunta
![issue4](https://cloud.githubusercontent.com/assets/5313324/15379815/c2c0e65c-1d3e-11e6-9f31-9ddce1fd1b4f.png)

   
#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android: 5.0

**Comment by sanro14** [comment]
@vlzangel

**Comment by sanro14** [comment]
Adjunto dos imágenes mas donde se reflejan los valores.
![issue3](https://cloud.githubusercontent.com/assets/5313324/15380029/71d159c8-1d40-11e6-847c-12a6d768d471.png)
![7](https://cloud.githubusercontent.com/assets/5313324/15380030/7201bcda-1d40-11e6-81ba-965c67db1ba8.png)

**Comment by nelsonalfo** [comment]
necesitaríamos que nos digas exactamente que pasos seguiste para que se produjera el error, exactamente que valores agregaste y en que orden

**Comment by sanro14** [comment]
@nelsonalfo este valor negativo aparece cuando trabajo cantidades grandes.

**Comment by nelsonalfo** [comment]
en la versión actual de la app (versión 9) no veo que se produzca el error:
![captura de pantalla de 2016-05-20 17 42 40](https://cloud.githubusercontent.com/assets/1823627/15442922/1a169a58-1eae-11e6-972e-99674bbe7265.png)

**Comment by nelsonalfo** [comment]
Me puede confirmar si el error persiste?

**Comment by abicelis** [comment]
Que ha pasado con este issue?

**Comment by sanro14** [comment]
@abicelis lo iba a probar el la versión nueva pero no me deja hacer nada me da error creando el perfil..

**Comment by sanro14** [comment]
@MaviDavsa cerrar este

**Comment by MaviDavsa** [comment]
Solucionado!
