### ISSUE TITLE
CBP-Broker-No muestra valor de mi balance

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#323]
##### Reporte de error: 

   *En el Stock Management el campo de la bank no se muestra, salen dos " -- " ver figura adjunta.
![issue4](https://cloud.githubusercontent.com/assets/5313324/15379936/ac2399e8-1d3f-11e6-960b-ad90892e20be.png)
![issue6](https://cloud.githubusercontent.com/assets/5313324/15379941/b34073c2-1d3f-11e6-8b9c-60a5cf2472fe.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android: 5.0

**Comment by sanro14** [comment]
@vlzangel

**Comment by nelsonalfo** [comment]
yo @nelsonalfo tomaré esta tarea

**Comment by nelsonalfo** [comment]
Me puedes indicar paso a paso que fue lo que hiciste para que se diera ese error? porque no consigo reproducirlo

**Comment by nelsonalfo** [comment]
El error sigue apareciendo? porque no he podido reproducir el error

**Comment by MaviDavsa** [comment]
@sanro14

**Comment by sanro14** [comment]
@nelsonalfo estaba a punto de probarlo, pero no pude seguir después de que le di crear mi perfil me dio un error de recovery system..

**Comment by MaviDavsa** [comment]
@nelsonalfo Ese error no dejo hacer nada a las chicas hoy en la mañana!

**Comment by nelsonalfo** [comment]
por favor verifiquen si se puede cerrar este Issue

**Comment by sanro14** [comment]
@MaviDavsa esto ya se soluciono..
