### ISSUE TITLE
CBP-Broker-Ventana modal de transacciones en stock management permite valores infinitos

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#324]
##### Reporte de error: 

   *La ventana modal que se mustra cuando quiero modificar mi stock acepta valores infinitos, como se muestra en la figura adjunta.
![6](https://cloud.githubusercontent.com/assets/5313324/15380007/379c8ef8-1d40-11e6-91d4-0e495cd97c57.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo: Nexus 4
* Version de Android: 5.0

**Comment by sanro14** [comment]
@vlzangel

**Comment by nelsonalfo** [comment]
yo @nelsonalfo tomaré esta tarea

**Comment by nelsonalfo** [comment]
En la versión 10 del la app esta la corrección  de este bug

**Comment by nelsonalfo** [comment]
Se volvió a probar esto con los cambios de la versión 10?

**Comment by sanro14** [comment]
@MaviDavsa Cerrar!
