### ISSUE TITLE
CHAT - Problema en la actualización de las conversaciones.

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#325]
#### Nombre pantalla
CONVERSATION/CHATS

### CHAT 

-----

##### Reporte de error: 

En una conversación, al tenerla abierta no se actualiza el estado de los mensajes enviados, ni los mensajes nuevos automáticamente. Debo salir de la conversación (a la lista de chats) y volver a entrar para verlos actualizados.

Tampoco se actualiza el estado de la otra persona (de Online a Typing... y viceversa) mientras se está en la conversación.

Este mismo problema se ve replicado en la lista de Chats, al estar situados en esta pantalla ningún estado de la conversación (Typing..., un mensaje nuevo, una actualización de mensaje) se ve reflejada en el "preview" de la conversación hasta no entrar a la misma.

Dentro de la conversación, el último mensaje fue enviado y su estado no se actualiza.
![conversation_bug_mavi](https://cloud.githubusercontent.com/assets/18471856/15395799/01089aa4-1da3-11e6-82a8-35f7026bbfac.png)

Al retornar a la pantalla anterior, inmediatamente el estado se ve actualizado a visto.
![conversation_mavi_2](https://cloud.githubusercontent.com/assets/18471856/15395794/fd1fcba6-1da2-11e6-9c02-dec68387f13d.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0 (API 22)

**Comment by fabianazabala** [comment]
@franklinmarcano1970

**Comment by AdryCanonico** [comment]
@MaviDavsa  @franklinmarcano1970 En la version 2 en mis emuladores no ocurre este error. 

![13](https://cloud.githubusercontent.com/assets/18584168/15475917/3372e158-20d6-11e6-88ff-06d97e5e510c.png)

![13chat](https://cloud.githubusercontent.com/assets/18584168/15475939/51eb3400-20d6-11e6-972d-8746f24b328e.png)
