### ISSUE TITLE
CHAT - Demasiado lento al escoger una foto de perfil.

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#326]
#### Nombre pantalla
Galería de la Identity

### CHAT

-----

##### Reporte de error: 
En la Identity de Chat, al escoger una foto de perfil. La galería carga excesivamente lento las imágenes y se desliza con lentitud.
Esto al tener pocas imágenes no sucede, o no es perceptible. Pero al momento de realizar la prueba (con más de 600 imágenes, lo cual es una cantidad de imágenes normal) se hizo demasiado difícil seleccionar una.
Para descartar problemas de mi computadora, hice la misma prueba con la galería de WhatsApp para seleccionar una foto de perfil y no se presentó el problema, cargaron las imágenes rápidamente y se deslizaba a la normalidad. 
El issue es replicable el 100% de las veces, aún después de dejar cargar todas las imágenes.

![galeria](https://cloud.githubusercontent.com/assets/18471856/15396057/353b6c42-1da4-11e6-80a5-c39e7a841c4a.png)
_En la foto, galería de chat cargando las imágenes..._

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0 (API 22)

**Comment by fabianazabala** [comment]
@franklinmarcano1970

**Comment by Lozadaa** [comment]
Estoy seguro que el problema no esta en nuestras manos. Nosotros hacemos un llamado a la galeria y la mostramos, nosotros no programamos el cargado de imagenes ni nada por el estilo eso es lo estandar de android por así decirlo nosotros solo hacemos el llamado y lo mostramos. La lentitud debe ser causada por algo externo a nosotros.

**Comment by josejcb** [comment]
Saludos, estamos revisando este caso para darle una respuesta tecnica de lo que esta sucediendo.

**Comment by josejcb** [comment]
Hemos revisado en nuestros teléfonos y la velocidad galería-fermat es similar, sin embargo, fermat maneja mas procesos que whatsapp debido a la cantidad de plataformas que corren en ella, lo cual hace que al llamar a otro proceso como la galería reaccione un poco mas lento que en otra aplicación que se solo haga un cosa, pero la diferencia sigue sin ser sustancial. También como en cualquier aplicación mientras mejor hardware se tenga, menos diferencia en la ejecución de la aplicación se va a notar respecto a otros teléfonos.

**Comment by MaviDavsa** [comment]
@fabianazabala Necesito que le respondas a los chicos! :)

**Comment by fabianazabala** [comment]
Disculpen que no había visto esto, 16gb de ram y 4 núcleos
