### ISSUE TITLE
CHAT - Notificaciones 

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#327]
#### Nombre pantalla
Notificaciones

### CHAT

-----

##### Reporte de error: 

   *En este caso es necesario, sumamente necesario que se activen actualizaciones en la versión si no pueden ser auditivas por lo menos visuales, en la communities estaban las solicitudes de Yolanda y Gaby pero no me di cuenta hasta un rato después ya que cuando refrescaba mi home ellas nunca aparecían, pero cuando fui a las notificaciones allí estaban las de ella! Entonces es sumamente necesario que aunque sea una notificación visual exista. 
   
![chat](https://cloud.githubusercontent.com/assets/17273005/15396863/c3b28dcc-1da7-11e6-9fdd-ffacba75d70e.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 7
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@MaviDavsa como puedes ver en el documento del SCOPE, eso no fue previsto, sabemos que hace falta, pero en su momento tenian detalles y se prefirio dejarlo por fuera de ese proyecto, en el siguiente ya fue aprobado su implementacion.

**Comment by MaviDavsa** [comment]
Bueno! Lo dejo por acá hasta que se haga @franklinmarcano1970 Porque de verdad hace demasiadaaaaaaaaa falta! Es algo importante!

**Comment by franklinmarcano1970** [comment]
Si dale pero recuerda no puedes etiquetarlo como bug, entonces ya que no es un error!!!!

**Comment by MaviDavsa** [comment]
Esto me paso hoy! Me llego una notificación visual de que alguien conecto conmigo! Entonces SOLUCIONADO!
