### ISSUE TITLE
CBP- Dentro de la Customer no hay botón "atrás" 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#328]
##### Reporte de error: 

Al crear el perfil dentro de la customer no hay un botón de "atrás", lo que genera usar el botón de atrás del emulador. 

![capture-20160519-102131](https://cloud.githubusercontent.com/assets/17262077/15399326/ffea0ee2-1db0-11e6-80f9-293713558eb9.png)

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion 
* Modelo: Google Nexus 7
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by nelsonalfo** [comment]
Esto es asi por diseño, porque estas en el home de la subapp, asi como es en las subapps de las otras plataformas

**Comment by MaviDavsa** [comment]
@nelsonalfo Este es un issues que le hemos hecho a todas las subapps! Jajajaja por eso las ponemos como Experiencia de Usuario! Porque a nuestro agrado se vería mejor como lo comenta @Gabymorillo

**Comment by Gabymorillo** [comment]
Exactamente, sería mucho mas cómodo para el usuario. @nelsonalfo @MaviDavsa

**Comment by nelsonalfo** [comment]
bueno ya le digo a @vlzangel que se encargue de esto

**Comment by nelsonalfo** [comment]
En la versión 10 del la app esta apliacdo este cambio

**Comment by nelsonalfo** [comment]
Se puedo probar esto?

**Comment by sanro14** [comment]
@Gabymorillo revisa por favor

**Comment by Gabymorillo** [comment]
Revisado y solucionado
