### ISSUE TITLE
CHAT - Funciona incorrectamente al utilizar comillas.

### ISSUE THREAD

**Issue by fabianazabala** [Fermat-ORG/beta-testing-program#329]
#### Nombre pantalla
Conversación

### CHAT

-----
##### Reporte de error: 

En una conversación, al intentar usar comillas a veces deja de funcionar el botón de enviar, intento presionarlo pero nunca se envía el mensaje. Con el emoticón ":')" esto sucede el 100% de las veces.

![comilla](https://cloud.githubusercontent.com/assets/18471856/15399656/5c3f442c-1db2-11e6-86ac-0af7346e079c.png)
_En la imagen, no me permite enviar el emoticón por contener una comilla_

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0 (API 22)

**Comment by fabianazabala** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@fabianazabala @MaviDavsa Los emuladores no aceptan caracteres especiales, por esos nos te los deja enviar, porque no los reconoce!!!!!!!!

**Comment by fabianazabala** [comment]
Justo arriba envié uno si ves bien, es con cierta combinación de caracteres que no deja.

**Comment by franklinmarcano1970** [comment]
Por eso es problema del emulador que no deja ciertas combinaciones por temas de seguridad..

**Comment by fabianazabala** [comment]
No deja en dónde, en Fermat? En WhatsApp y en el chat de Facebook me permite enviarlos.

**Comment by franklinmarcano1970** [comment]
Porque esas combinaciones de teclas son validadas por la plataforma, y recuerda que no manejamos emoticones, y ese conjunto de teclas tiene relacion a veces a los emoticones al funciones especiales de cada aplicacion que nosotros no manejamos, si me explico!!!!!..

**Comment by franklinmarcano1970** [comment]
Por eso tenemos que diferenciar que es un Bug para poder etiquetarlo como tal, en ese caso pudiese ser una recomendacion de mejoras en la funcionalidad!!!!!!

**Comment by JDVilchez** [comment]
Este error es por sql Injection. Ya lo vamos a revisar.

**Comment by MaviDavsa** [comment]
Ya esto funciona! :D
