### ISSUE TITLE
Bit Coin Wallet_ Home_Solicitud de Bitcoins

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#331]
#### Nombre pantalla
HOME 

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *En esta oportunidad el error esta en que una vez que deje de tocar la pantalla para solicitar los bitcoins esta no se detuvo y la rueda siguio y siguio y siguio sin darme ningunos bitcoins. 

![img-20160519-wa0053](https://cloud.githubusercontent.com/assets/17273005/15412385/e2c64b56-1df0-11e6-8b84-f3522bfe9335.jpg)

------

##### Dispositivo desde donde se realizo la prueba

Marca: ZTE
Modelo: Nubia Z5
Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by maydiamc** [comment]
este error se repite en la version 11, la rueda no se detiene sino que sigue hasta el final, a pesar de dejarla de presionar @nattyco @MaviDavsa

**Comment by AdryCanonico** [comment]
@MaviDavsa  en la versión 16.2 se corrigió este error.

**Comment by MaviDavsa** [comment]
Solucionado!
