### ISSUE TITLE
LPW - No permite cambiar perfil

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#332]
##### Reporte de error: 

  No permite cambiar el nombre para diferenciar a cada usuario.

- [x] Pantalla del detalle del contacto

![image](https://cloud.githubusercontent.com/assets/18452495/15412412/11ff09d0-1df1-11e6-9e1b-8d94fa61f756.png)

![image](https://cloud.githubusercontent.com/assets/18452495/15412340/858f1cd8-1df0-11e6-8fca-d4a14e5ddd3f.png)

   
   

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/15412378/d5c0cf9e-1df0-11e6-82a9-c36923d10502.png)

**Comment by MaviDavsa** [comment]
@nattyco Yo les explique a ellas! Sin embargo el punto de ellas tambien es cierto! debe haber un pop o algo por el estilo que haga saber que deben crearse el perfil en la wallet user para poder tener un perfil en los LPW!

**Comment by andreagmarcano** [comment]
Se puede cambiar el nombre a través de "Profiles / Wallet Users", pero es tedioso salir y entrar de cada una de las aplicaciones, ya que lo usuarios no saben todo el procedimiento, no es obvio a simple vista, al menos deberia redireccionar desde "Loss Protected Wallet" para poderlo hacer desde "Profiles"

**Comment by nattyco** [comment]
@andreagmarcano  Corregido verificar en nueva version de la apk

**Comment by andreagmarcano** [comment]
Ya verifique, y no tuve problemas para cambiar el perfil @MaviDavsa @nattyco
