### ISSUE TITLE
Identity - Sin Límite de caracteres para crear el "Username"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#333]
##### Reporte de error: 

   *No hay limite de caracteres para el "Username", cuando se está creando el perfil a través de "Profiles", permite la apertura así tenga cientos de caracteres (Pantalla 1), al revisar el perfil que muestra al desplegar el menú en "Loss Protected Wallet" (Pantalla 2) se puede observar que muestra todos los caracteres que se han colocado y en un cierto punto corta. Gráficamente no se ve agradable 

Sería ideal que se estableciera un límite de caracteres.

------

#### Pantalla 1
![screenshot_52](https://cloud.githubusercontent.com/assets/19142276/15412617/08a52620-1df7-11e6-85fe-cf68aa2b1eca.jpg)

Pantalla 2
![screenshot_53](https://cloud.githubusercontent.com/assets/19142276/15412619/0ec397da-1df7-11e6-9c53-d998000d9131.jpg)

------

#### Dispositivo desde donde se realizó la prueba

* Marca:Genymotion
* Modelo:Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15412634/27c009f8-1df7-11e6-8d61-c0aabb9e5e75.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@IsbetVR  Corregido verificar en la proxima version de la app.

**Comment by IsbetVR** [comment]
@nattyco @MaviDavsa si! Corregido en la v4! 

Probado en:
Google Nexus 5
Versión android: 5.1.0

y también en:
Google Nexus 5
Versión android: 4.4
