### ISSUE TITLE
Bitcoin Wallet_ MENU Profile Image not show

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#334]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Una vez creado el Perfil, cuando me voy al Menú de la Bitcoin Wallet me da este error en el contacto. 
   
![img-20160519-wa0054](https://cloud.githubusercontent.com/assets/17273005/15412656/27118648-1df3-11e6-8f23-17fa5970611e.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Nubia Z5
* Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa Corregido verificar en la proxima version de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco en la versión 5 LPW se corrigió el error 

![imagen](https://cloud.githubusercontent.com/assets/18584168/15541392/0f15ab66-2256-11e6-8cc2-79acd1f173f0.png)

**Comment by MaviDavsa** [comment]
Solucionado!
