### ISSUE TITLE
Bit Coin Wallet_ Home_ RECIVED AND SEND

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#335]
#### Nombre pantalla
Home

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Me muestra saldo disponible pero no muestra ninguna de las transacciones que he hecho ni en recived ni en send! 
   
![img-20160519-wa0074](https://cloud.githubusercontent.com/assets/17273005/15412945/bc44dd62-1df5-11e6-9477-92f62fa53e12.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Nubia Z5
* Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa Verificar esto en la version  7 de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la versión 7 Se corrigió el problema!! 


![1](https://cloud.githubusercontent.com/assets/18584168/15650325/85f58cc6-2641-11e6-8aae-35a46cdcd7ea.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco  En la version 19.2 no se visualiza quien envió o a quien le envié. Por favor reabrir el caso

![screenshot_2016-07-04-13-36-29](https://cloud.githubusercontent.com/assets/18584168/16567935/523ca4c4-41f2-11e6-844c-aa1f0babd715.png)

Alogcat:

[alogcat.2016-07-04-13-55-30-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346724/alogcat.2016-07-04-13-55-30-0430.txt)


Teléfono: 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16567952/6fd86dd8-41f2-11e6-8cad-867b3dd3dc04.png)

**Comment by nattyco** [comment]
@AdryCanonico  si refrescas no te muestra las transacciones? habias enviado y se habia confirmado ya?

**Comment by AdryCanonico** [comment]
@nattyco si había refrescado pero no sucedía nada. En la version 19.5 ya no ocurre el error.

**Comment by camilavaleria** [comment]
En la version 19.5 persiste el error.. por favor reabrir el caso

![image](https://cloud.githubusercontent.com/assets/18740418/16603637/8e675c74-42eb-11e6-93d1-a5f917941b4a.png)

Alogcat:

[logcat 2.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348859/logcat.2.txt)

Dispositivo de prueba;

![emulador 4 5 0](https://cloud.githubusercontent.com/assets/18740418/16603928/1a015f9e-42ee-11e6-8732-7c8b61f9f61d.png)

**Comment by camilavaleria** [comment]
Fue necesario reiniciar el emulador para q se actualizara la patalla del home y apareciera el sent y el received:

![image](https://cloud.githubusercontent.com/assets/18740418/16604182/a9f7f5c0-42f0-11e6-9a17-61978ec037e8.png)

**Comment by hcampos1984** [comment]
![image](https://cloud.githubusercontent.com/assets/20233469/16751383/f730b074-47a6-11e6-84e2-59d08a4ba2fb.png)
![image](https://cloud.githubusercontent.com/assets/20233469/16751389/0bcb43aa-47a7-11e6-9f40-79bedd6f0507.png)

el error persiste en la version 20.4, espere 30 min. y no recibi los bitcoins, incluso procese la solicitud por medio del "TestNet" y el "Regtest"

**Comment by arosiopr** [comment]
@MaviDavsa @IsbetVR @sanro14 @AdryCanonico  chicas este no es el mismo 631?

**Comment by IsbetVR** [comment]
Referido al caso #631

**Comment by IsbetVR** [comment]
Closed #335

**Comment by camilavaleria** [comment]
En la version 20.6 no se pudo probar este caso en vista de que no se pudo aceptar en los contactos de la bitcoin wallet uno de los usuarios,  tal como se indica a continuacion;


![image](https://cloud.githubusercontent.com/assets/18740418/16858945/b3ea08ca-49f8-11e6-9d3d-3f52ab92c252.png)

**Comment by camilavaleria** [comment]
En la version 20.7 persiste el error, se desaparecen las transacciones del send y del received tal y como se indican a continuacion;

![image](https://cloud.githubusercontent.com/assets/18740418/16874922/520683dc-4a6a-11e6-9cbe-bd54d63426c6.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16874933/5df7a8ba-4a6a-11e6-8c79-683610677904.png)

Emulador de prueba;


![image](https://cloud.githubusercontent.com/assets/18740418/16874947/759b9832-4a6a-11e6-86c5-fc4b38378e7e.png)

**Comment by hcampos1984** [comment]
desde que la version 20.5 no he recibido btc en mi wallet por lo que no me permite hacer pruebas @MaviDavsa @AdryCanonico @IsbetVR 

![image](https://cloud.githubusercontent.com/assets/20233469/16890512/61d66ff4-4abd-11e6-873e-7e900cc77612.png)
![image](https://cloud.githubusercontent.com/assets/20233469/16890520/707436ae-4abd-11e6-9802-f066cd19864b.png)
