### ISSUE TITLE
Bit Coin Wallet_ Home_Pop de Entrada

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#336]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Una vez que presiono la opcion de no volver a ver este mensaje de nuevo no reconoce la opción! por ende cada vez que abro la apk me sale el mismo mensaje y debo cerrarlo cada vez que la abro! 
   
![img-20160519-wa0072](https://cloud.githubusercontent.com/assets/17273005/15413037/8fd40ec8-1df6-11e6-8ed1-ccc17ede7cd9.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE 
* Modelo: Nubia Z5
* Version de Android: 4.2.2

**Comment by nattyco** [comment]
@MaviDavsa  verificar esto en la version 10 de la apk

**Comment by maydiamc** [comment]
solucionado en la verion 11 @MaviDavsa @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!

**Comment by maydiamc** [comment]
En la version 15.2 de la apk, se esta mostrando este error de nuevo, por favor @MaviDavsa reabrir el caso @nattyco 

![screenshot_2016-06-09-11-51-36](https://cloud.githubusercontent.com/assets/17274154/15936784/13519488-2e36-11e6-8e42-6286c9da73d9.png)

Dispositivo
-Samsung Galaxy
-Mini S4
-4.4.2

**Comment by maydiamc** [comment]
En la actualizacion 18 de la CBP, en la bitcoin wallet se sigue mostrando este problema @nattyco 

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16231245/3e1f9b26-378f-11e6-8b86-e5bcc743d8ae.png)

**Comment by maydiamc** [comment]
el error persiste en la version18.3 de CBP @nattyco

**Comment by marielis-urbina** [comment]
En este versión 18.8 no sucede este error @nattyco 

![samsung](https://cloud.githubusercontent.com/assets/19353722/16523515/aafcc03a-3f6d-11e6-972d-33e0e552432a.png)

**Comment by maydiamc** [comment]
en mi emulador sigue el error con la version 18.8 CBP 
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16530418/d410d65e-3f91-11e6-99b1-451217ddb4cb.png)

**Comment by maydiamc** [comment]
en la version 20.1 cbp no sucedio el error

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16692436/ca508e8a-44fe-11e6-887e-2a9c4e004e93.png)

**Comment by Gabymorillo** [comment]
En la versión 20.1 en el teléfono físico no presenta ese error. 

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16692474/f39e754a-44fe-11e6-8b04-15dcc39131f9.png)

**Comment by MaviDavsa** [comment]
Perfecto!!! Solucionado! :)
