### ISSUE TITLE
Communities - No refresca los users

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#337]
##### Reporte de error: 

   *Cuando voy a revisar los users con los que puedo establecer una conexión, se queda cargando mucho tiempo y no actualiza (Pantalla 1), me salgo de la aplicación y vuelvo a entrar y nada, continúa sin refrescar los users.

------
#### Pantalla 1 

![screenshot_54](https://cloud.githubusercontent.com/assets/19142276/15413108/35750ed2-1dfb-11e6-8c1c-6c160e97f31e.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15413113/42482414-1dfb-11e6-98e2-e185903c3a4b.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by arosiopr** [comment]
sucede lo mismo en 
* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

![screenshot_11](https://cloud.githubusercontent.com/assets/5313326/15413274/5b783472-1df8-11e6-9e44-654c86a08d0c.png)

**Comment by arosiopr** [comment]
Al entrar a la Crypto Wallet Users no salen contactos para agregar, ni actualizando.

**Dispositivo desde donde se realizo la prueba**

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

![screenshot_34](https://cloud.githubusercontent.com/assets/5313326/15544160/8d1bdc64-2261-11e6-9c45-8cf3a9efd43d.png)

**Comment by sanro14** [comment]
A mi me sucede lo mismo @nattyco tal cual..

**Comment by maydiamc** [comment]
a mi me sucede los mismo @nattyco 
samsung galaxy
mini s4
4.4.2

**Comment by nattyco** [comment]
Probar con la nueva version de la apk para ver si este error mejoro.

**Comment by maydiamc** [comment]
el error mejoro, pero en algunas ocasiones sigue sucediendo y no se muestran contactos o se queda cargando
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 8 de la apk

**Comment by andreagmarcano** [comment]
Sigue tardando mucho tiempo, y no actualiza. 

Nexus 5.1

**Comment by IsbetVR** [comment]
En la versión 8 continua el problema, no refresca los contactos, dura muchisimo. Hay que cerrar el emulador y volverlo a iniciar.

Dispositivo:
HTC One X
Versión: 4.2.2

**Comment by marielis-urbina** [comment]
Cuando voy a ver los usuarios se tarda mucho en mostrarlos y después de hacerlo cuando ya mande la solicitud queda largo rato la pantalla en negro 

![captur](https://cloud.githubusercontent.com/assets/19353722/15660044/904ec094-269f-11e6-8bc7-65d2f9419a8e.png)

**Comment by sanro14** [comment]
@nattyco sucede lo mismo en la versión 8

**Comment by marielis-urbina** [comment]
En la versión 12 de la LPW, continua el problema, no refresca los contactos y se sigue quedando la pantalla en negro por largo rato

Dispositivo:

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/15765671/33492132-2901-11e6-83b0-951755171ba8.png)

**Comment by maydiamc** [comment]
en la version 17 esto no sucedia al principio, pero luego de usar la app por un rato, esta sucediendo @nattyco 

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16027214/02b4e196-319e-11e6-9d7e-7cab88f080e9.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @IsbetVR  En la versión 18.3 CBP ya no se ve el error
