### ISSUE TITLE
Bitcoin Wallet - Pantalla de home congelada

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#338]
##### Reporte de error: 

Al entrar a la Bitcoin Wallet se queda congelada en el home, al cerrar y abrir de nuevo la aplicación persiste el problema. 

![screenshot_2016-05-19-19-52-52](https://cloud.githubusercontent.com/assets/17262077/15413394/91d7babe-1df9-11e6-8d2a-f846e4de1595.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy 
* Modelo: GT-I9082L
* Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@Gabymorillo verificar en la proxima version de la apk

**Comment by Gabymorillo** [comment]
Ok!

**Comment by maydiamc** [comment]
solucionado, cerrar @MaviDavsa @sanro14
