### ISSUE TITLE
Bit Coin Wallet_ Performance

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#339]
#### Nombre pantalla
HOME

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Esto sucede muy a menudo en la aplicación una vez que paso del home a contactos se me queda la pantalla congelada y se me sale a la pantalla principal de la aplicación, arrogando el siguiente error. 
   
![img-20160519-wa0073](https://cloud.githubusercontent.com/assets/17273005/15413398/9f48b22a-1df9-11e6-9870-85dd16716cdb.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Nubia Z5
* Version de Android: 4.2.2

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@furszy

**Comment by furszy** [comment]
@MaviDavsa hablame por slack para detectar el error.

**Comment by MaviDavsa** [comment]
@furszy  Matti...! Cuando este me conecto y te busco... ! Pero... Es de repente que se congela y me sale el error! :(... Sin importar lo que este haciendo...

**Comment by nattyco** [comment]
@MaviDavsa  Verificar nuevamente este reporte

**Comment by MaviDavsa** [comment]
Persiste @nattyco

**Comment by furszy** [comment]
@MaviDavsa a la noche hacemos una prueba juntos así me mostras esto.

**Comment by MaviDavsa** [comment]
@furszy Perfecto! la cosa es que eso es tlf no emulador!!! :( Como hacemos allí!?

**Comment by maydiamc** [comment]
este problema no se esta presentando en la version 11 @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Perfecto!
