### ISSUE TITLE
LPW - Payment requests - Error al intentar aceptar un requests 

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#340]
##### Reporte de error: 

   *Cuando me llega un Request (Pantalla 1) y le doy click en "Accept", no me deja, me lanza inmediatamente un "Warning" (Pantalla 2) y no me da otra opción. Y tengo disponible en el "Available balance" para poder aceptar el requests (Pantalla 3)

------
#### Pantalla 1
![screenshot_59](https://cloud.githubusercontent.com/assets/19142276/15413867/8d899cf8-1e02-11e6-879b-fd7eb1bae95b.jpg)

#### Pantalla 2
![screenshot_60](https://cloud.githubusercontent.com/assets/19142276/15413870/997ea850-1e02-11e6-8fbb-94377bb2a8ed.jpg)

#### Pantalla 3
![screenshot_58](https://cloud.githubusercontent.com/assets/19142276/15413872/a27260dc-1e02-11e6-8b9f-b05918bbd740.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15413891/dcb355ee-1e02-11e6-9677-1aafeb030cbe.jpg)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by nattyco** [comment]
@IsbetVR  Corregido, verificar en la proxima version de la app

**Comment by andreagmarcano** [comment]
No tuve problemas al recibir un request @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Perfecto! Entonces Solucionado! :D
