### ISSUE TITLE
BITCOIN WALLET - ERROR AL EDITAR CONTACTO PARA ENVIAR BTC

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#343]
### BITCOIN WALLET

-----

##### Reporte de error: 

   *Al momento de querer editar el nombre  para enviar BTC queda la foto del contacto que se agrego anteriormente. Hay que salir y volver a entrar a la wallet para que se corrija el error. 

![captura de pantalla 451](https://cloud.githubusercontent.com/assets/18584168/15416366/5793875a-1e14-11e6-8893-3c3725c4a836.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15416401/da05b172-1e14-11e6-88b5-17d3102fac52.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  verificar esto en la version 10 de la apk

**Comment by AdryCanonico** [comment]
@nattyco persiste el error en la version 13.

![screenshot_3](https://cloud.githubusercontent.com/assets/18584168/15795842/3a0404ce-29bf-11e6-8dbc-aa04c7b1783a.png)

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la version 18 de CBP se corrigio el error. Se puede cerrar el caso
