### ISSUE TITLE
BITCOIN WALLET - TEXTO MONTADO 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#344]
### BITCOIN WALLET

-----

##### Reporte de error: 

   *Se monta el texto de btc sobre los números del contador de BTC
   
![captura de pantalla 439](https://cloud.githubusercontent.com/assets/18584168/15416688/04ce5a14-1e18-11e6-9c9c-8cb98169cee1.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15416784/de27c84a-1e18-11e6-81b2-ae0785938fb9.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico corregido en la version 7 de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco  en la versión 7 se corrigió el error. Se puede cerrar el caso.

![btc no hay](https://cloud.githubusercontent.com/assets/18584168/15651534/1231b068-264a-11e6-9464-490be376cfe5.png)
