### ISSUE TITLE
BITCOIN WALLET - BOTON FERMAT USER GRANDE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#345]
### BITCOIN WALLET

-----

##### Reporte de error: 

   *El botón de Fermat User esta muy grande en la pantalla. 

   
![captura de pantalla 441](https://cloud.githubusercontent.com/assets/18584168/15416867/ac6d0d3c-1e19-11e6-9262-74449031cdec.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15416784/de27c84a-1e18-11e6-81b2-ae0785938fb9.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico Corregido verificar en la nueva version de la apk

**Comment by AdryCanonico** [comment]
@nattyco  en la versión 5 los iconos están grande.

![fondo texto mas amigable](https://cloud.githubusercontent.com/assets/18584168/15544584/1031a2ae-2263-11e6-813d-92b92ab9a2bc.png)

**Comment by MaviDavsa** [comment]
@nattyco Y la broma esa negra en Contact Name! No va! :)

**Comment by maydiamc** [comment]
solucionado cerrar @MaviDavsa @sanro14

**Comment by AdryCanonico** [comment]
@MaviDavsa Este caso hay que probarlo en una versión especifica ya que solo da el error en versiones bajas.

**Comment by MaviDavsa** [comment]
@AdryCanonico   May probo con una 4.4
