### ISSUE TITLE
BITCOIN WALLET - BOTON EXTERNAL USER GRANDE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#346]
### Bitcoin Wallet 

-----

##### Reporte de error: 

 *El botón de External User esta muy grande en la pantalla. 
 
![captura de pantalla 441](https://cloud.githubusercontent.com/assets/18584168/15416867/ac6d0d3c-1e19-11e6-9262-74449031cdec.png)

  
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15416784/de27c84a-1e18-11e6-81b2-ae0785938fb9.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico Corregido verificar en la nueva version de la apk

**Comment by AdryCanonico** [comment]
@nattyco  en la version 5 sigue saliendo grandes 

![fondo texto mas amigable](https://cloud.githubusercontent.com/assets/18584168/15545092/e1b9f29e-2264-11e6-94f3-ea5cb0ca3930.png)

**Comment by maydiamc** [comment]
solucionado cerrar @MaviDavsa  @sanro14

**Comment by AdryCanonico** [comment]
@MaviDavsa Este caso hay que probarlo en una versión especifica ya que solo da el error en versiones bajas.

**Comment by MaviDavsa** [comment]
@AdryCanonico   May probo con una 4.4

**Comment by AdryCanonico** [comment]
@MaviDavsa se puede cerrar el caso
