### ISSUE TITLE
BITCOIN WALLET - BARRA PARA BUSCAR CONTACTO EN NEGRO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#347]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *La barra para buscar los contactos se ve de color negro.

![captura de pantalla 444](https://cloud.githubusercontent.com/assets/18584168/15417005/270cfb00-1e1b-11e6-8942-145eff01435a.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador derecho:
![nexus s](https://cloud.githubusercontent.com/assets/18584168/15416784/de27c84a-1e18-11e6-81b2-ae0785938fb9.png)

Emulador izquierdo:

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15417026/63401530-1e1b-11e6-80dc-3034bf81d136.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 7 se corrigió el error. Pero en el emulador Nexus S falta la linea que divide "Contacts" con el buscador

![barra arreglada](https://cloud.githubusercontent.com/assets/18584168/15650647/e4f9139e-2643-11e6-8da2-47f192a7fb0c.png)

**Comment by maydiamc** [comment]
no se presento este error en la version 11, solucionado @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
@maydiamc Y la linea que separa a los contactos aparece!?

**Comment by AdryCanonico** [comment]
@MaviDavsa sigue sin aparecer la linea en la versión 11

**Comment by nattyco** [comment]
@MaviDavsa  esa linea es el tool bar de la app, y no me parece que sea algo muy relevante que se vea o no la sombra.

**Comment by AdryCanonico** [comment]
@nattyco en la version 18 de CBP  la linea que divide "Contacts" con el buscador no se ve en 4.1 de android. Seria bueno estandarizar si va a existir la linea o no va a existir.

**Comment by AdryCanonico** [comment]
@nattyco en la version 18.2 de CBP sigue persistiendo la falta de la linea es el tool bar de la app en las versiones 4.1. Natty por favor podrías estandarizar esto? Ya que las app tienen que verse igual en todas las versiones de Android.

**Comment by nattyco** [comment]
@AdryCanonico  no encuentro cual es el problema por el cual no muestra esa division en esa version de android, por eso no se ha corregido

**Comment by AdryCanonico** [comment]
@nattyco ok, yo te iba a preguntar lo mismo. Si abría otro. Ya lo abro y te mando el numero. Gracias.
@MaviDavsa Se puede cerrar el caso

**Comment by maydiamc** [comment]
en la version 21.8 CBP se esta presentando el error, reabrir el caso

![screenshot_9](https://cloud.githubusercontent.com/assets/17274154/17566631/36345134-5f0a-11e6-8c4e-272928344cee.png)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17566639/3dd67ac0-5f0a-11e6-82de-4a72e9075ad5.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by IsbetVR** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Prueba 10-08-16
Caso 724 CBP V21.8
Sony Xperia S 16api 320dpi
Persiste lo reportado..
![screenshot_17](https://cloud.githubusercontent.com/assets/17283358/17566812/e18b2dd2-5f0a-11e6-84b0-f95d1cc2a427.png)

**Comment by arosiopr** [comment]
el error persiste en la versión 21.9 de CBP 
Teléfono Físico
![alcatel](https://cloud.githubusercontent.com/assets/5313326/17621872/869e5416-6064-11e6-913d-8a4f7b1f4208.png)

**Comment by marielis-urbina** [comment]
En la versión 21.9 de CBP, este error persiste en mi emulador

![negro](https://cloud.githubusercontent.com/assets/19353722/17622049/efeb49aa-6065-11e6-8ad9-9c7822c7e363.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17622054/f543406a-6065-11e6-82c9-a8d9de218d86.png)

**Comment by Gabymorillo** [comment]
Desde el telefono fisico en la versión 21.9 no sucede lo reportado. 

![screenshot_2016-08-12-08-23-48_720](https://cloud.githubusercontent.com/assets/17262077/17622184/be86881a-6066-11e6-84a8-30763599e18a.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17622186/bf8c77ce-6066-11e6-8891-bdf3aa021946.png)

**Comment by yolandayancel** [comment]
Prueba 12-08-16
Caso CBP V21.9 (BITCOIN WALLET)
Sony Xperia S 4.1.1 16api 320dpi
Ocurre lo reportado(Barra en negro en  contacts)
![7](https://cloud.githubusercontent.com/assets/17283358/17623134/85294142-606c-11e6-8a01-ec877001fc4e.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17623139/8ae90ff4-606c-11e6-8f29-9aca9f36ff98.png)

**Comment by GeronimoVierma** [comment]
En la versión 22.0 de CBP persiste el error:

![screenshot_4](https://cloud.githubusercontent.com/assets/19883115/17672992/145c34b4-62ed-11e6-95bb-27f1b4562aeb.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17673028/3d292154-62ed-11e6-8d5f-0ff6a97f726b.png)

**Comment by maydiamc** [comment]
persiste el error en la 22.0 de CBP

![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17674954/b19820b4-62f5-11e6-977c-32dbc7c8f462.png)

**Comment by nattyco** [comment]
@MaviDavsa  corregido en la version 22.1 de la apk

**Comment by maydiamc** [comment]
en la version 22.1 se sigue viendo la barra de color negro

![screenshot_35](https://cloud.githubusercontent.com/assets/17274154/17708665/f66ccde8-63b3-11e6-9b96-1728a5ea5669.png)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17708674/fe275d96-63b3-11e6-9f8d-29bd80cc75a4.png)

**Comment by AdryCanonico** [comment]
ya no sucede el error version 22.1

**Comment by arosiopr** [comment]
@AdryCanonico   solucionado en la versión 22.1 de la apk
