### ISSUE TITLE
LPW-Requests-Error no deja aceptar requests

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#348]
### Loss Protected Wallet

-----

##### Reporte de error: 

   *Al ingresar a Requests Received e intentar aceptar la solicitud de maydi a1 que es por 2 BTC se presenta el siguiente error:

![screenshot_21](https://cloud.githubusercontent.com/assets/5313326/15429570/516c1fde-1e6b-11e6-9421-5d77fba3cde6.png)

Y tengo disponible los btc, mas de los que están solicitando como se puede observar:

![screenshot_23](https://cloud.githubusercontent.com/assets/5313326/15429646/ba9b8c7e-1e6b-11e6-8075-988f164c35c5.png)

![screenshot_22](https://cloud.githubusercontent.com/assets/5313326/15429649/c16cf4de-1e6b-11e6-84d1-8530d31e4737.png)

Y tengo desactivado el Loss Protected en Settings porque pensé que podría ser eso, pero no. Igual sigue saliendo el mismo error
![screenshot_24](https://cloud.githubusercontent.com/assets/5313326/15429763/2d014ede-1e6c-11e6-8be8-ae0b8a3ace7d.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by AdryCanonico** [comment]
tambien sucede lo mismo con esta version  de emulador:

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15431834/6552bf30-1e75-11e6-9aff-f014dcd46a4e.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15431835/6553ab16-1e75-11e6-9801-0520a63738ba.png)

**Comment by nattyco** [comment]
@arosiopr corregido verificar en la proxima version de la app

**Comment by arosiopr** [comment]
@MaviDavsa corregido, se puede cerrar
