### ISSUE TITLE
LPW- Error en el home 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#349]
##### Reporte de error: 

 Cada vez que se entra al home marca: recovering from system error In Graphic.  
  
![screenshot_2016-05-20-09-40-43](https://cloud.githubusercontent.com/assets/17262077/15429739/14d0dadc-1e6c-11e6-8aff-3e5d49ea022c.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung
* Modelo: GT-I9082L
* Version de Android: 4.2.2

**Comment by Gabymorillo** [comment]
@nattyco

**Comment by nattyco** [comment]
@Gabymorillo verificar si esto sigue pasando en la nueva apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco en la version 5 en el caso de mi emulador no se presento este error.

**Comment by maydiamc** [comment]
solucionado @MaviDavsa @sanro14

**Comment by danielaporras** [comment]
Dispositivo: 
Marca: Genymotion
Modelo: google Nexus 5
Version:5.0
 En la version 13 de la LPW, sigue saliendo este error.
![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/15794387/39d53d8e-29b4-11e6-8278-6f173507545d.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  verificar si esto pasa de nuevo en la version 15 de apk

**Comment by AdryCanonico** [comment]
@nattyco En la version 15 sigue persistiendo el error. 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15894907/55d6bc00-2d52-11e6-867e-14184f489478.png)

**Comment by nattyco** [comment]
@AdryCanonico  pasame captura del error.

**Comment by AdryCanonico** [comment]
@nattyco  Aqui te mando la capture del dispositivo, 

![screenshot_2016-06-08-08-48-46](https://cloud.githubusercontent.com/assets/18584168/15897598/f204845c-2d5e-11e6-8b95-080c5a9fffd7.png)

**Comment by nattyco** [comment]
@MaviDavsa @AdryCanonico  decime cual es el error si es el mismo que mostraba cuando se abrio este caso o es otro, porque en esa pantalla no veo ningun cartel.

**Comment by AdryCanonico** [comment]
@nattyco Cada vez que se entra al home marca: recovering from system error In Graphic

**Comment by MaviDavsa** [comment]
@nattyco Simplemente que ella esta del teléfono Naty! Y por eso no pudo hacer la capture! :(

**Comment by RubenSem** [comment]
@nattyco Esto me pasa en la version 15, sale recovering from system error.
![screenshot_7](https://cloud.githubusercontent.com/assets/19676223/15898762/497e421e-2d63-11e6-95a4-3d949cbfeb28.jpg)
![screenshot_6](https://cloud.githubusercontent.com/assets/19676223/15898763/499b4738-2d63-11e6-88cc-5b1addeaece5.jpg)

Especificacione:
![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/15898774/52710e6a-2d63-11e6-9999-17d53358dd71.jpg)

**Comment by AdryCanonico** [comment]
@nattyco  Aqui esta la capture :satisfied:

![screenshot_2016-06-08-08-57-24](https://cloud.githubusercontent.com/assets/18584168/15900085/ec3a960c-2d67-11e6-83ef-d2d7a395f4f9.png)

**Comment by nattyco** [comment]
@AdryCanonico  ok gracias, es otro error este, lo voy a verificar.

**Comment by danielaporras** [comment]
El error persiste en la version 15 de LPW

![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/15900853/ca04f9a8-2d6a-11e6-940e-9af77bec61a3.png)

Dispositivo desde donde se realizo la prueba
Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0

@nattyco

**Comment by AdryCanonico** [comment]
@nattyco Disculpa, no puedo colocarte la capture con el mensaje recovering from system error In Graphic ya que no puedo capturarla con el cell pero es uno de los errores que me ha dado hoy la app en la version 15.

**Comment by danielaporras** [comment]
En la version 15.1 se repite el error.
![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15915458/4084e32a-2db3-11e6-92f9-db260de2cab3.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0

@MaviDavsa

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 15.2  de la apk

**Comment by maydiamc** [comment]
en mi dispositivo no sucede este error.! @nattyco 

samsung galaxy 
mini s4
4.4.2

**Comment by MaviDavsa** [comment]
En mi dispositivo ya no sucede este error! 
![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15932884/424efae6-2e27-11e6-9214-ff51a2bc9267.jpg)

**Comment by sanro14** [comment]
@nattyco este aun no ha salido.. no se si a @danielaporras le sale en la versión 16

**Comment by danielaporras** [comment]
@MaviDavsa    Ya puedes cerrar este caso lo probé en 2 emuladores y no ya no sale.

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 16.2 de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa  eN LA VERSIÓN 16.2 NO ME OCURRE EL EROR.

**Comment by Gabymorillo** [comment]
En la versión 16.2 no ocurre este error.
