### ISSUE TITLE
Community- Navigation Drawer Profile Image

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#350]
##### Reporte de error: 

   *En el menú de Contactos, me sale mi identidad como unknown y no muestra mi foto, ver imagen adjunta.
![issue1](https://cloud.githubusercontent.com/assets/5313324/15430199/3d482500-1e72-11e6-81ba-c252a8d711f0.png)

Debería salir mi identidad tal cual se ve en el menú:

![image](https://cloud.githubusercontent.com/assets/5313324/15430224/5db13660-1e72-11e6-8c62-cd574f1caed0.png)

------
#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android: 5.0

**Comment by sanro14** [comment]
@nattyco

**Comment by nattyco** [comment]
@sanro14  Corregido verificar en la proxima version de la apk

**Comment by sanro14** [comment]
@MaviDavsa cerrar

**Comment by RubenSem** [comment]
Vuelve aparecer el mismo error, Ya creado el perfil sale mi identidad como unknown y no muestra mi foto.
![screenshot_9](https://cloud.githubusercontent.com/assets/19676223/15841947/c63b3fbe-2c1e-11e6-97ca-d03957d06bdb.jpg)

Probado en:

![screenshot_7](https://cloud.githubusercontent.com/assets/19676223/15841953/ccffad80-2c1e-11e6-9cd9-42e86af1cb25.jpg)

**Comment by nattyco** [comment]
@MaviDavsa  esa pantalla es de Crypto Brokers no de la Crypto Wallet
