### ISSUE TITLE
LPW_contacts_ texto superpuesto y mal ubicado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#351]
#### Nombre pantalla

------
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [x] Pop up de agregar un contacto

##### Reporte de error: 

   *En el momento de desplegar el boton mas(+), al salir las opciones de fermat user y external user el texto se superpone con el del fondo de los contactos o se junta demasiado y esto dificulta la lectura.
      
![screenshot_2016-05-20-10-00-43](https://cloud.githubusercontent.com/assets/17274154/15431431/a636cbce-1e73-11e6-8377-8baba18b4cba.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by arosiopr** [comment]
también se presenta en:
* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

![screenshot_35](https://cloud.githubusercontent.com/assets/5313326/15544078/3e4e69da-2261-11e6-9c16-6e853b7811b7.png)


![screenshot_39](https://cloud.githubusercontent.com/assets/5313326/15544018/fde41e9e-2260-11e6-885b-2048084dc76c.png)

**Comment by nattyco** [comment]
@arosiopr @maydiamc verificar como se ve en la ultima apk version 6

**Comment by maydiamc** [comment]
en este caso se detallan mejor las letras de external user y fermat user debido al fondo negro que se le coloco, pero se mantiene el error de los contactos con diferentes tamaños

![jnininns](https://cloud.githubusercontent.com/assets/17274154/15577416/45b65b72-2326-11e6-9d61-8bdb46869f38.png)

**Comment by maydiamc** [comment]
@nattyco se recomienda que el fondo negro de las letras external user y fermat user tenga forma un poco mas redondeada para que concuerde con el estilo grafico de la app

**Comment by nattyco** [comment]
@maydiamc Si se va a mejorar el fondo del texto, los iconos se van a seguir poniendo sobre los contactos en esta version, hasta que se implemente otra libreria.

**Comment by maydiamc** [comment]
ok excelente, me supuse que era necesario de que sucediera asi, y como es un menù desplegable es comprensible, porque se puede volver a ocultar si dificulta la visibilidad. @nattyco

**Comment by nattyco** [comment]
@MaviDavsa evaluar este caso para cerrarlo

**Comment by MaviDavsa** [comment]
@nattyco Esto lo vamos a dejar como experiencia de usuario nena para que en las próximas versiones las tengas presente... Otra opción puede ser que cuando se presione el más, la lista de contactos se ponga un poco oscura y los dos iconos de fermat user y external user sobresalgan! no se si me explico.?
