### ISSUE TITLE
LPW - MOVIMIENTO DE TEXTO 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#352]
### LPW

-----

##### Reporte de error: 

   *Se puede subir y bajar el texto: Enter name here y Notes para arriba y abajo.
   

![screenshot_6](https://cloud.githubusercontent.com/assets/18584168/15431489/025e76c2-1e74-11e6-862b-95f003be1450.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15431651/a9923e56-1e74-11e6-81c6-f37716c494f0.png)
![nexus s](https://cloud.githubusercontent.com/assets/18584168/15431652/a9c4f878-1e74-11e6-9414-d7f65cfa634e.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  a que te refeires con esto? como se reproduce?

**Comment by sanro14** [comment]
@nattyco lo que ella quiere decir es que cuando sitúa el puntero del mouse sobre el textarea del notes el texto bien sea el por defecto "notes" o lo que el usuario copie, se mueve hacia arriba y hacia abajo... no se si me explico...

**Comment by nattyco** [comment]
@AdryCanonico  @sanro14  Corregido, verificar en la proxima version de la app.

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la versión 5 se corrigió el error. Se puede cerrar el caso.
