### ISSUE TITLE
LPW_navigation view_imagen y nombre de usuario

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#353]
#### Nombre pantalla

------
##### Reporte de error: 

   *En algunas ocasiones, independientemente en que pantalla este ubicada, la imagen y el nombre de usuario no se pueden apreciar .
   
![screenshot_2016-05-20-09-41-47](https://cloud.githubusercontent.com/assets/17274154/15431764/1f010a0a-1e75-11e6-81c3-aff913d4bf94.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by IsbetVR** [comment]
Sucede lo mismo en el dispositivo:
Google Nexus 5
Versión de Android 5.1.0

**Comment by nattyco** [comment]
@maydiamc  @IsbetVR Corregido verificar en la proxima version de la apk

**Comment by maydiamc** [comment]
solucionado en la ultima actualizacion
