### ISSUE TITLE
LPW-Transactions Received-Error no se ve quien me envio BTC

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#354]
### Loss Protected Wallet

-----

##### Reporte de error: 

   *Al ingresar en Transactions Received y observar los btc recibidos no puedo ver quien me los envió, solo sale en algunos casos como en el primero que diany envió 1.00 BTC

![screenshot_25](https://cloud.githubusercontent.com/assets/5313326/15432214/12130f30-1e77-11e6-86f1-4c9367a257b8.png)

Pienso que debería salir quien te los envió en todos los casos como en el caso de los requests, ya que son usuarios Fermat.

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@arosiopr  Corregido, verificar en la nueva version de la apk

**Comment by arosiopr** [comment]
@nattyco perfecto revisare

**Comment by AdryCanonico** [comment]
@nattyco en la version 5, Adriporras la tenia agregada a contactos pero en received no me aparece el nombre de quien lo envio.


![transaccion](https://cloud.githubusercontent.com/assets/18584168/15545596/bbb473a6-2266-11e6-908a-b423f846dd96.png)

**Comment by nattyco** [comment]
@arosiopr  verificar con la nueva version de la apk no es necesario que elimines la data

**Comment by arosiopr** [comment]
@nattyco ok

**Comment by andreagmarcano** [comment]
Verificado y no tuve problemas, pude ver quien enviaba los btc @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Entonces Solucionado!
