### ISSUE TITLE
LPW_send to contac y send request to contact - Suggestion

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#355]
#### Reporte de error

 Tanto en la pantalla de send contact, como en la de sent request to contac, al comenzar a escribir el nombre del contacto para que se muestre en la barra desplegable, en algunas ocasiones, o se despliega de color negro o muy finito y no permite, ni seleccionar ni ver el nombre completo del contacto para poder terminar el formulario y realizar el envio.

![screenshot_2016-05-20-09-15-06](https://cloud.githubusercontent.com/assets/17274154/15432326/98999cae-1e77-11e6-8551-a7a29aedc136.png)
![screenshot_2016-05-20-11-02-20](https://cloud.githubusercontent.com/assets/17274154/15432329/9b4b09a6-1e77-11e6-9146-d382f6e9e68a.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by maydiamc** [comment]
el problema continua presente en la ultima actualizacion

**Comment by nattyco** [comment]
@maydiamc  verificar con la ultima apk disponible

**Comment by maydiamc** [comment]
no lo he podido probar por problemas en la crypto wallet user, ver caso #337

**Comment by nattyco** [comment]
@maydiamc  probar con la nueva version de la apk para ver si el erro del caso 337 tambien mejoro.

**Comment by maydiamc** [comment]
el problema sigue intermitente, sucede en algunas ocasiones con contactos al azar, no se ha solucionado @nattyco

**Comment by AdryCanonico** [comment]
@maydiamc @nattyco @MaviDavsa En la versión 7, en el emulador nexus 5 y nexus S se ve el nombre pero no completo.

![nombre completo](https://cloud.githubusercontent.com/assets/18584168/15652013/1c14c130-264d-11e6-9055-a2089761ca53.png)

**Comment by MaviDavsa** [comment]
Yo presento el mismo error @nattyco 

![screenshot_2016-05-30-10-26-18](https://cloud.githubusercontent.com/assets/17273005/15652105/9fdb2acc-264d-11e6-95e3-bb0e469204f7.jpg)

![screenshot_2016-05-30-10-31-49](https://cloud.githubusercontent.com/assets/17273005/15652109/a76359c2-264d-11e6-93fb-399554800a28.jpg)

**Comment by nattyco** [comment]
@MaviDavsa  @maydiamc  verificar en la version 8 de la apk

**Comment by maydiamc** [comment]
error corregido en la version 8 @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Ya lo voy a probar yo...

**Comment by MaviDavsa** [comment]
Corregido...
