### ISSUE TITLE
LPW - IMAGEN DE CONTACTOS CON TAMAÑO DIFERENTES 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#356]
### LPW

-----

##### Reporte de error: 

   *Los contactos se les ve la imagen unas mas grandes que otras y desordenados en los textos.

![screenshot_7](https://cloud.githubusercontent.com/assets/18584168/15432205/088d8742-1e77-11e6-8a97-2ee60cb67fd7.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15432247/3fd05b12-1e77-11e6-85ea-99ea8be1c6ae.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15432248/3fd535d8-1e77-11e6-9da2-3164936e879c.png)

**Comment by maydiamc** [comment]
a mi se me presenta el mismo error
Marca: Samsung Galaxy 
Modelo: S4 mini 
Version: 4.4.2

**Comment by sanro14** [comment]
@nattyco este no se puede verificar porque la community no nos deja ver contactos para agregarlos..

**Comment by maydiamc** [comment]
en la ultima actualizacion sigue presentandose el mismo problema @nattyco 
![jnininns](https://cloud.githubusercontent.com/assets/17274154/15578077/dd907be2-2328-11e6-8ee9-c16c8c276645.png)

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la version 6 ya los contactos no se ven desordenados pero no se puede subir y bajar. el texto del botón External User o los botones en si, cubren los contactos impidiendo poder visualizarlos. 


![1](https://cloud.githubusercontent.com/assets/18584168/15610828/19f99578-23f1-11e6-8c62-f4d3c1ec3569.png)

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  verificar en la version 14 de la apk

**Comment by AdryCanonico** [comment]
@nattyco en la version 15 no se ven de diferentes tamaños pero las imágenes están muy pegadas a la linea que los separa. Se visualiza mejor cuando te fijas en la franja naranja de Contact name.

![screenshot_2016-06-08-09-52-42](https://cloud.githubusercontent.com/assets/18584168/15896678/1b6e7d6a-2d5b-11e6-8b1c-80196e503975.png)

DISPISITIVO;

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15896740/5abac33e-2d5b-11e6-806f-6b19363b4c6c.png)

**Comment by maydiamc** [comment]
en mi dispositivo sucede lo mismo @nattyco 

![screenshot_2016-06-08-10-15-26](https://cloud.githubusercontent.com/assets/17274154/15897392/195c1fac-2d5e-11e6-8314-9bbaad246685.png)

Samsung Galaxy 
Mini S4
4.4.2

**Comment by MaviDavsa** [comment]
Mismo error en mi tlf... En cuanto al centrado de los contactos, ya que están muy pegado a la linea. 

![screenshot_2016-06-08-19-38-16](https://cloud.githubusercontent.com/assets/17273005/15917308/37adaa22-2dc5-11e6-83ce-294f421aec7d.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15917312/4278c07c-2dc5-11e6-8e89-2664511138a4.jpg)

**Comment by maydiamc** [comment]
en la version 16.1 se ven igual de pegados con mi dispositivo @nattyco 
![screenshot_2016-06-07-11-03-21](https://cloud.githubusercontent.com/assets/17274154/15965520/402956fa-2ee8-11e6-8541-95720c5edfb6.png)

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  se corrigio el listado de Contactos en la version 16.3  de la apk

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco  En la versión 17 ya están los contactos ordenados y del mismo tamaño. Se puede cerrar el caso.


![tamano de fotos](https://cloud.githubusercontent.com/assets/18584168/16009200/7806b9c8-3145-11e6-8409-e1bbcfdfe8a4.png)
