### ISSUE TITLE
CHAT -  MENSAJES Y CONTACTOS NO VISUALIZADOS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#358]
### CHAT

-----

##### Reporte de error: 

   *No se ve el contacto agregado, los mensajes que envió el otro contacto Adry2 en el emulador 1
   
![adri chat3](https://cloud.githubusercontent.com/assets/18584168/15433226/4609174a-1e7b-11e6-84ce-94f673a8e18e.PNG)

![adri chat 4](https://cloud.githubusercontent.com/assets/18584168/15433227/460f0830-1e7b-11e6-9487-9d6829cd203b.PNG)

pero en el otro emulador 2 (Adry 2) ya fue enviado y puede ser visualizado el contacto (Gablup- Emulador 1).

![gg2](https://cloud.githubusercontent.com/assets/18584168/15433305/9ed7e3ba-1e7b-11e6-9016-97589927004f.png)

![gg1](https://cloud.githubusercontent.com/assets/18584168/15433306/9eddd89c-1e7b-11e6-8e22-724b9cf53664.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador 1:

![acerca del emulador](https://cloud.githubusercontent.com/assets/18584168/15433323/b33bbbf6-1e7b-11e6-8446-a6b2831c3dfa.PNG)

Emulador 2:

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15433364/e1f5a7f4-1e7b-11e6-8c8e-f485219728cd.png)

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Saludos porque lo que le explique ayer la confirmación de la aceptación nunca llego, por eso para el remoto hasta que no llegues dicha confirmación no saldrá como un contacto registrado.

**Comment by MaviDavsa** [comment]
@AdryCanonico

**Comment by franklinmarcano1970** [comment]
@AdryCanonico @MaviDavsa no se ve el contacto agregado porq no le llego la confirmacion de aceptacion, se quedo en el mundo oscuro de la red.

**Comment by josejcb** [comment]
Posiblemente entraste a chat antes de que te llegara la confirmacion. Hastta ahora nos ha llegado, avisanos si te vuelve a ocurrir en la siguiente  prueba.

**Comment by MaviDavsa** [comment]
@AdryCanonico  Necesito que probemos esto!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 @MaviDavsa En la versión 4 se corrigio el error. Se puede cerrar el caso
