### ISSUE TITLE
LPW - BOTON FERMAT USER GRANDE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#361]
### LPW

-----

##### Reporte de error: 

   *El botón de External User esta muy grande en la pantalla.

![4](https://cloud.githubusercontent.com/assets/18584168/15434898/1f6c2cb4-1e83-11e6-9cf4-2ce66a46c6c5.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15416784/de27c84a-1e18-11e6-81b2-ae0785938fb9.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by maydiamc** [comment]
solucionado cerrar @MaviDavsa

**Comment by AdryCanonico** [comment]
@MaviDavsa Este caso hay que probarlo en una versión especifica ya que solo da el error en versiones bajas.

**Comment by MaviDavsa** [comment]
@AdryCanonico bueno @maydiamc lo probo en un 4.4 creo!

**Comment by maydiamc** [comment]
Exactamente lo probe en 4.4.2, y me funciono perfectl sin ningun problema @MaviDavsa

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco hay que reabrir el caso ya que persiste el error en el Nexus S  240 dpi.

![botones grandes contactos](https://cloud.githubusercontent.com/assets/18584168/15609285/fc3d1990-23e8-11e6-8ce6-009a9e607592.png)

**Comment by nattyco** [comment]
@MaviDavsa  en esta version los botones salen en ese tamaño, ya que hay que hacer una implementacion nueva, que se hara en proximas mejoras.

**Comment by MaviDavsa** [comment]
@AdryCanonico En mi tlf salen en tamaño estándar, sin embargo prueba en la tuya a ver!

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la versión 8 se corrigió. Se puede cerrar el caso.

![botones](https://cloud.githubusercontent.com/assets/18584168/15674151/03d70534-2705-11e6-9a74-8805844b084b.png)
