### ISSUE TITLE
COMMUNITIES - CHAT COMMUNITY 

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#362]
##### Reporte de error: 

A entrar a Communities, especificamente en la parte de Chat Comunity, para buscar a los contactos en linea para enviar una solicitud... El contacto "Adry2" se visualiza en línea, incluso, me deja enviarle una solicitud para comunicarme con ella perfectamente pero

![captura](https://cloud.githubusercontent.com/assets/17261437/15433704/74226798-1e81-11e6-87a8-846d34ccef8c.PNG)

a pesar de que Adry2 ya me había aceptado (imagen proveniente del emulador de Adry2 para verificar)
![issue gaby chat](https://cloud.githubusercontent.com/assets/17261437/15433799/d1fe9bc0-1e81-11e6-9f21-01a54821a197.PNG)

Nunca pude apreciarla en mi lista de contactos.

![adri chat3](https://cloud.githubusercontent.com/assets/17261437/15433823/eb886f80-1e81-11e6-85ed-b1472e760c6c.PNG)

Incluso reenviándole la invitación, no había diferencia
![chat issue](https://cloud.githubusercontent.com/assets/17261437/15433739/91ab7340-1e81-11e6-8f33-c44b2b0e8a1f.PNG)

#### Dispositivo desde donde se realizo la prueba
![acerca del emulador](https://cloud.githubusercontent.com/assets/17261437/15433452/7469ea56-1e80-11e6-9cbb-4e864dad612d.PNG)

**Comment by gablup** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Porque el mismo problema que a veces no llega la respuesta de conexion y por ende en el remoto no sale como contacto...

**Comment by MaviDavsa** [comment]
@gablup Hay que verificar esto!

**Comment by MaviDavsa** [comment]
Solucionado! Y en la ultima versión las conexiones están más rápidas!
