### ISSUE TITLE
LPW-Send request to contact.- al buscar un contacto aparece un recuadro negro

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#363]
#### Nombre pantalla
Send Request to contact

##### Reporte de error: 

   *Estando en Send request to contacto y tratar de colocar el nombre de Iss1,  al escribir las dos primeras letras aparece un recuadro negro.

![no aparece el contacto 1](https://cloud.githubusercontent.com/assets/17283358/15445683/b111d930-1ecd-11e6-9c69-d30dbd5cbb05.png)

Borro esas letras, y  al escribir las dos primeras nuevamente, ahora una sombra gris aparece debajo.
![no aparece el contacto2](https://cloud.githubusercontent.com/assets/17283358/15445690/e1c26766-1ecd-11e6-97ae-19434805d69e.png)

Salgo de la Send request to contact e ingreso nuevamente y el nombre esta escrito sin que yo lo escribiera, lo borre y cuando probé nuevamente escribir, volvio a ocurrir lo mismo. (aparece el recuadro negro)
![no aparece el contacto3](https://cloud.githubusercontent.com/assets/17283358/15445771/411113c8-1ed0-11e6-9c39-80eace864c70.png)

(solo ocurre con este contacto, lo probé con otro y si me permitió enviar el send r.)

#### Dispositivo desde donde se realizo la prueba

![nexus 4- 5 0 0](https://cloud.githubusercontent.com/assets/17283358/15445735/4f5d8638-1ecf-11e6-88f5-40683f2f1e2c.png)

**Comment by yolandayancel** [comment]
@nattyco

**Comment by nattyco** [comment]
@yolandayancel verificar nuevamente con la nueva apk

**Comment by MaviDavsa** [comment]
@nattyco La nueva apk no las deja hacer mucho! Se queda pegada en las communities y no reacciona!

**Comment by nattyco** [comment]
@MaviDavsa  @yolandayancel  ya el problema de la community quedo resuelto

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 25-05-16
Resuelto
Estando en Send to contact, se escribe el nombre y ya no aparece el recuadro negro.
![resuelto caso lpw](https://cloud.githubusercontent.com/assets/17283358/15548211/351e4ed8-2271-11e6-86b4-3e208ce5c069.png)
