### ISSUE TITLE
CHAT - ERROR VISULIZACION FICHAS DE CONTACTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#364]
### CHAT

-----

##### Reporte de error: 

   *Al querer entrar a la ficha del contacto se visualiza nada en ella

![7 ficha perfil](https://cloud.githubusercontent.com/assets/18584168/15474757/24df154a-20d0-11e6-9753-d88239a2ae79.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15474782/3cc0b2c2-20d0-11e6-889a-dbce243774f2.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15474781/3c514da6-20d0-11e6-9fd7-de107c977f29.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@AdryCanonico En mi Emulador ya se corrigió este problema, de todas maneras como el caso es tuyo pruebalo y me avisas!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 @MaviDavsa En la versión 4 esta disponible la ficha. Se puede cerrar el caso

![4 ficha de contacto](https://cloud.githubusercontent.com/assets/18584168/15519902/802ea8ea-21cd-11e6-8c40-07f01247f014.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico Pero tenemos el problema del status no?

**Comment by AdryCanonico** [comment]
@MaviDavsa  si, como se menciono en el caso #319

**Comment by MaviDavsa** [comment]
Como ya se menciono en el caso #319 Vamos a cerrar este!
