### ISSUE TITLE
CHAT -  NO SE VE EL CAMBIO DE FOTOS EN EL PERFIL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#365]
### CHAT

-----

##### Reporte de error: 

   *Cuando un contacto hace cambio de foto en su perfil, los otros contactos no pueden ver el cambio.
   
![cambio de foto](https://cloud.githubusercontent.com/assets/18584168/15477368/fcdad120-20dd-11e6-9944-058d6c866c65.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15474782/3cc0b2c2-20d0-11e6-889a-dbce243774f2.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15474781/3c514da6-20d0-11e6-9fd7-de107c977f29.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico Hay que verificar esto!

**Comment by AdryCanonico** [comment]
@MaviDavsa  por favor cerrar este caso ya que esta repetido en el  #201
