### ISSUE TITLE
CHAT - TAMAÑOS DIFERENTES EN FOTO DE PERFL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#366]
### CHAT

-----

##### Reporte de error: 

   *Cuando se realizan cortes en la foto del perfil, dependiendo del corte da un tamaño y forma diferente.
Seria bueno que el corte sea uniforme o estándar (cuadrado) para que se pueda visualizar las fotos iguales. 
   
Corte Rectangular:

![17 forma de foto](https://cloud.githubusercontent.com/assets/18584168/15477949/56d8d746-20e1-11e6-8ee5-d031d0835060.png)

Corte Cuadrado:

![18 forma de toto](https://cloud.githubusercontent.com/assets/18584168/15477948/56d5515c-20e1-11e6-9453-0530dbeaa950.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15474782/3cc0b2c2-20d0-11e6-889a-dbce243774f2.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15474781/3c514da6-20d0-11e6-9fd7-de107c977f29.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Bueno etiquetemos esto como una experiencia de usuario ya que no es un bug!!!

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 @MaviDavsa en la versión 4 se corrigió el error. Se puede cerrar el caso
