### ISSUE TITLE
CHAT - NO SE VISUALIZA EL CHECK DE LOS MENSAJES AL BORRAR TODOS LOS CHAT

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#367]
### CHAT

-----

##### Reporte de error: 

   *Cuando un contacto limpia todo el chat (Delete all chats) 

![all chats](https://cloud.githubusercontent.com/assets/18584168/15478335/6f9035d4-20e3-11e6-9249-1b16bd314a4c.png)

y vuelve establecer conversación con otros contactos o los mismos que tenia antes de borrar, este no le aparecen los check de confirmación en las conversaciones (Doble check gris y azul). 

![5 chat](https://cloud.githubusercontent.com/assets/18584168/15478499/6709af98-20e4-11e6-9bb9-a8ccdd35e4c9.png)

Para que salgan reflejados los doble check en gris o azul, ambos contactos deben borrar todos los chats (como se muestra en la primera capture)
   

![10 chat](https://cloud.githubusercontent.com/assets/18584168/15478538/c126aab2-20e4-11e6-8f76-8e06da5254a6.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15474782/3cc0b2c2-20d0-11e6-889a-dbce243774f2.png)

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15474781/3c514da6-20d0-11e6-9fd7-de107c977f29.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@AdryCanonico Verifica esto bella!

**Comment by AdryCanonico** [comment]
@MaviDavsa @franklinmarcano1970 en la versión 4 se corrigió el error. Se puede cerrar el caso.

![2 chek](https://cloud.githubusercontent.com/assets/18584168/15519411/2c052962-21cb-11e6-9fbc-cd9b239e3e1f.png)
