### ISSUE TITLE
CBP - Broker Wallet - Permite cualquier caracter en el "Account Number" configurando el Bank

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#369]
##### Reporte de error: 

Al momento de configurar la "Bank" (Pantalla 1), en el "Account Number" (Pantalla 2) permite introducir cualquier cosa (números, letras, símbolos), Debería sólo permitir introducir números y "-"

------

#### Pantalla 1

![screenshot_75](https://cloud.githubusercontent.com/assets/19142276/15487263/d6385736-2119-11e6-991f-d79b3fcdc0ec.jpg)

#### Pantalla 2

![screenshot_76](https://cloud.githubusercontent.com/assets/19142276/15487267/deca7bc2-2119-11e6-999a-9b5d063d060d.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15487273/ef413dd8-2119-11e6-855a-454a8c542f23.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @sanro14

**Comment by IsbetVR** [comment]
@nelsonalfo

**Comment by abicelis** [comment]
@IsbetVR yo agarro este bug! Te aviso cuando este listo

**Comment by MaviDavsa** [comment]
El error consiste en que no hay limites de caracteres en estos campos... Si la persona quiere poner 10000 puede hacerlo y esto se ve mal esteticamente y por otra parte una vez que se llena la pantalla completa no se pueden ver los otros campos.

![erdsfj](https://cloud.githubusercontent.com/assets/17273005/15558626/1d2bc056-22a5-11e6-9fc8-9892ce747df2.JPG)

La unica opcion con la que se pueden ver estos campos que se borre información puesta arriba y de esta forma se puede ver que continua en la pantalla.

![dsfs](https://cloud.githubusercontent.com/assets/17273005/15558639/35e5867c-22a5-11e6-8f09-f88a859bf851.JPG)

Pero no hay una opción para bajar y ver el resto de los campos a llenar, por ende es necesario que se limite la cantidad de caracteres a un numero determinado y se lo hagas saber a las personas, aparte de eso que pueda existir la opción de bajar sin ningún problema.

**Comment by abicelis** [comment]
Listo @MaviDavsa @IsbetVR,  en v13 los campos tienen limites de entrada, asi como en la bank wallet:
Bank name  10max
Alias 10max
Bank number 25max
Ademas, en bank number solo se pueden agregar numeros y dashes (-)

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa Ignoren la v13 para este issue, en la v14 estan limitados los campos (Nota: Bank Name son 15 max, no 10 como dije antes!) y ademas estan los textwatchers de @AdryCanonico

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa Lista la v14! Prueben y me avisan.

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa 

Probado en la v16.2 de CBP

Dispositivo: Google Nexus 4
Versión de android: 5.0.0

@MaviDavsa porfa revisa si a ti también te funciona por el comentario que hiciste ;)

corregido el error! Limita el "Bank name" a 15 caracteres, y el "account" también, sólo a números y "-"

![screenshot_59](https://cloud.githubusercontent.com/assets/19142276/15716406/2b018832-27f0-11e6-8521-b8f4bc06f20a.jpg)
