### ISSUE TITLE
CBP-Crypto Broker-Stock Management-Error Balance

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#370]
### Crypto Broker

-----

##### Reporte de error: 

   *Al ingresar en Stock Management se puede observar en el balance del Cash que el monto se divide en dos lineas, el cual no debería verse así, además no señala los separadores de miles, solo muestra los de decimales.

![screenshot_29](https://cloud.githubusercontent.com/assets/5313326/15488717/f26a1fda-2122-11e6-90ed-3c3944ec42b1.png)
 

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

**Comment by arosiopr** [comment]
@nelsonalfo

**Comment by yalayn** [comment]
Yo @yalayn estaré trabajando en este issue.

**Comment by yalayn** [comment]
@arosiopr, @MaviDavsa, @nelsonalfo. Se corrigió el problema, se amplio el espacio para evitar el salto de linea y se agrego el separador de mil. Estará disponible en la próxima versión de la app.
![stockmanagement2](https://cloud.githubusercontent.com/assets/4664287/15563237/74c2514c-22d0-11e6-9ea3-b189469d5f16.png)

**Comment by arosiopr** [comment]
@MaviDavsa corregido se puede cerrar
