### ISSUE TITLE
CBP - Crypto Customer y Broker - Aplicación se cuelga al entrar a las comunidades

### ISSUE THREAD

**Issue by alegnaire** [Fermat-ORG/beta-testing-program#371]
##### Reporte de error:

La aplicación se cuelga al accesar a CRYPTO CUSTOMER USERS desde Communities. 

Muestra el mensaje “Please waiting…” y de allí ya no responde, colgando el emulador, es necesario cerrar el player y volver a iniciarlo.

#### Dispositivo desde donde se realizo la prueba
![captura de pantalla 2016-05-23 a las 7 58 02 p m](https://cloud.githubusercontent.com/assets/18564248/15488778/a36cbba8-2123-11e6-92ea-e0f8fd551b22.png)

* Marca: SAMSUMG
* Modelo: S6
* Version de Android: 6.0.0

**Comment by IsbetVR** [comment]
Sucede lo mismo en:
Google Nexus 5
Versión android 5.1.0
Debo cerrar el emulador y volver a abrir.

**Comment by abicelis** [comment]
@alegnaire @IsbetVR Hmm... por casualidad les ha pasado en la Broker community tambien? O solo aqui?

**Comment by alegnaire** [comment]
@abicelis @IsbetVR Corregido en v12 de CBP. Se puede accesar a la sección Customer Community sin inconvenientes.
![captura de pantalla 2016-05-25 a las 9 02 37 p m](https://cloud.githubusercontent.com/assets/18564248/15560708/f80e7dfa-22b7-11e6-8af8-e513a1d84f9c.png)

**Comment by alegnaire** [comment]
@MaviDavsa Problema corregido, favor cerrar.

**Comment by GeronimoVierma** [comment]
Tambien me ocurre lo mismo, se queda cargando y nunca termina de cargar. Hay que cerrar la aplicación para salir de esa pantalla.

![screenshot_2](https://cloud.githubusercontent.com/assets/19883115/16062534/78c8a600-325d-11e6-8b45-def50fe00dde.png)

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16062562/bda868f0-325d-11e6-9f58-340ba36aa894.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/315124/logcat.txt)

**Comment by JeanFranco498** [comment]
El error persiste 
![image](https://cloud.githubusercontent.com/assets/19807906/16062782/7520b744-3263-11e6-8c91-221cc98f9c57.png)
![image](https://cloud.githubusercontent.com/assets/19807906/16062794/89ee48b2-3263-11e6-8d38-45f0f6b87a5b.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/315130/logcat.txt)

**Comment by LilianFlores** [comment]
En la versión 16.6 me sucedió este error pero en la Crypto Broker Users. 

![screenshot_2016-06-14-20-04-37](https://cloud.githubusercontent.com/assets/19652611/16064959/ea6cf0c4-326f-11e6-9a20-dd836c901ecb.png)

**Dispositivo desde donde se realizo la prueba**

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16064965/ff4d383c-326f-11e6-8400-6e4a471e093d.png)

**Comment by GeronimoVierma** [comment]
Aparte del emulador (como ya comente antes), este error también me ocurre con el teléfono físico

![screenshot_2016-06-14-20-54-02 1](https://cloud.githubusercontent.com/assets/19883115/16064972/0e64c510-3270-11e6-9bf9-3bdb311cf31a.png)

Dispositivo:
![screenshot_2016-06-13-09-03-54](https://cloud.githubusercontent.com/assets/19883115/16064991/336e48c2-3270-11e6-9cf9-cf29a701540f.png)


.

**Comment by danielaporras** [comment]
En la versión 17, persiste el error.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/16084602/41fc7738-32e3-11e6-85ff-6b867707bf39.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.2.2

@nattyco

**Comment by AdryCanonico** [comment]
@nattyco @abicelis En la versión 17 CBP cuando intento entrar a la community se queda en espera,  así cierre y abra la app no veo a nadie. Los pocos usuarios que me logran ver no me llegan sus notificaciones. 

![screenshot_2016-06-15-10-17-59](https://cloud.githubusercontent.com/assets/18584168/16084676/7218c034-32e3-11e6-9c8f-3776c7638ecd.png)


![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16084692/7fbb5594-32e3-11e6-8b5d-a5e659d59d8a.png)

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  371   CBP V 16.7
Nexus 5  5.1.0
En este emulador, al entrar a la comunnity la pantalla se veia negra y al clickear varias veces salió el siguente recuadro.
![caso 371](https://cloud.githubusercontent.com/assets/17283358/16084714/938d5e8c-32e3-11e6-8bd1-643200027e24.png)

**Comment by dorzar1989** [comment]
En el dispositivo que manejo con la version 17 de la CBP continua este error

![screenshot_3](https://cloud.githubusercontent.com/assets/19670319/16084697/81d321cc-32e3-11e6-8555-5db8527b5df7.png)


![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/16084705/853decde-32e3-11e6-8686-b31be01ee844.png)

**Comment by GeronimoVierma** [comment]
En la versión CBP-V17 siendo yo Broker no me carga la Community Customer ni la Community Broker, en la versión 16.6 almenos si me abría la pantalla Community Broker, no así la Community Customer como notifique en comentarios anteriores.

![comentario1](https://cloud.githubusercontent.com/assets/19883115/16084700/83617a7a-32e3-11e6-87d5-62126fe484ce.png)


![comentario2](https://cloud.githubusercontent.com/assets/19883115/16084709/8d524ad2-32e3-11e6-9bc0-457c2871de57.png)

![issues](https://cloud.githubusercontent.com/assets/19883115/16084739/a7e611ee-32e3-11e6-85fa-35a88c66a2f4.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/316375/logcat.txt)

**Comment by maydiamc** [comment]
@nelsonalfo en la version 17, se me muestra la broker community, pero tarda demasiado tiempo en cargar, y lo hace (recarga) cada vez que ingreso en un usuario a enviiar la solicitud, asi que se ha echo bastante tedioso enviarle la solicitud a varios usuarios.

![screenshot_2016-06-15-10-57-03](https://cloud.githubusercontent.com/assets/17274154/16085064/a1f3839c-32e4-11e6-8bc0-74b1394512ee.png)


![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16085033/916ea100-32e4-11e6-8fb5-ec41a170dede.png)

**Comment by Gabymorillo** [comment]
En la version 17 de la CBP al entrar a las communitis de los Broker solo aparece "please wait" por un largo rato, al salir y entrar de nuevo sucede lo mismo, haciendo imposible establecer conexión con los Broker. 

![screenshot_2016-06-15-10-22-11](https://cloud.githubusercontent.com/assets/17262077/16084930/47083f86-32e4-11e6-9d43-f9b00cb1e53f.png)

![screenshot_2016-06-15-10-59-46 1](https://cloud.githubusercontent.com/assets/17262077/16085200/1669d8ac-32e5-11e6-83f8-cd458fe26874.png)

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  371   CBP V 16.7
Nexus 4  5.0.0
En este emulador, si ocurre lo reportado.
Foto
![caso 371](https://cloud.githubusercontent.com/assets/17283358/16086328/f66cfcec-32e8-11e6-8c06-b625acb751a0.png)
Logcat
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/316488/logcat.txt)

**Comment by nelsonalfo** [comment]
Ya reportamos el error a @furszy y se esta resolviendo

**Comment by marielis-urbina** [comment]
En la version 17 de la CBP al entrar a las communitis de los Broker siendo Custome o viceversa solo aparece "please wait" por un largo rato, al salir y entrar de nuevo sucede lo mismo, no se puede establecer conexión con la Broker.

![colgado](https://cloud.githubusercontent.com/assets/19353722/16101459/b5788dcc-332f-11e6-856b-5882427f126b.png)

Dispositivo desde donde se realizo la prueba

![samsung](https://cloud.githubusercontent.com/assets/19353722/16101462/bf1e35ca-332f-11e6-9ecb-4b1a95b21be4.png)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/317415/logcat.txt)

**Comment by AdryCanonico** [comment]
@abicelis en la version 17 de CBP sigue persistiendo este error.

**Comment by nelsonalfo** [comment]
revisen la version 17.1 y avisan

**Comment by GeronimoVierma** [comment]
He estado probando con la 17.1 como broker y hasta ahora esta entrando a las 2 pantallas sin problema.

![issues](https://cloud.githubusercontent.com/assets/19883115/16120941/217663e8-33ab-11e6-80e7-ba7c05d5facd.png)

**Comment by MaviDavsa** [comment]
@IsbetVR @GeronimoVierma @LilianFlores @danielaporras @AdryCanonico @yolandayancel @maydiamc @dorzar1989 @Gabymorillo @marielis-urbina Chicosss!! Necesito que revisen este issues plis!

**Comment by AdryCanonico** [comment]
@alegnaire En la version 18.4 no sucede este error.

**Comment by MaviDavsa** [comment]
Solucionado!!!
