### ISSUE TITLE
CHAT - No elimina contactos 

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#372]
#### Nombre pantalla
CHAT

### CHAT

-----

##### Reporte de error: 

   *El error radica en que le doy a eliminar el chat pero no me lo elimina, lo que hace es limpiarlo, pero no eliminarlo. 

![error2](https://cloud.githubusercontent.com/assets/17273005/15507214/7161b82c-2194-11e6-9e55-ceae6d7a4263.JPG)

![error1](https://cloud.githubusercontent.com/assets/17273005/15507210/6bb252f6-2194-11e6-888e-dea5931c4066.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.1

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by AdryCanonico** [comment]
@MaviDavsa  en mi caso. la versión 4 borra un chat determinado. 

![7 borrar chat](https://cloud.githubusercontent.com/assets/18584168/15522229/d8834278-21da-11e6-82bd-600caa5d31f0.png)

![8 borrar chat](https://cloud.githubusercontent.com/assets/18584168/15522231/d9864ad0-21da-11e6-8b3e-55d87a64ef70.png)

**Comment by MaviDavsa** [comment]
Si listo! Yo también lo Probé! :)
