### ISSUE TITLE
Chat - Linea de texto sube mucho

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#373]
#### Nombre pantalla
Chat 

### CHAT

-----

##### Reporte de error: 

   *En este caso el error radica en que normalmente tengo mi texto o mi pantalla de chat de la siguiente manera...

![error 3](https://cloud.githubusercontent.com/assets/17273005/15509405/41a2d13a-219d-11e6-83e9-274388ffc750.JPG)

Y cuando quiero escribir un mensaje muy largo la linea del texto se extiende demasiado por ende esto hace que los mensajes de arriba se oculten , lo cual dificulta saber que es lo que se escribió en el ultimo mensaje y a la vista no es agradable

![error 2](https://cloud.githubusercontent.com/assets/17273005/15509448/6daacc74-219d-11e6-9514-ed466b276665.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.1.0

**Comment by MaviDavsa** [comment]
@franklinmarcano1970

**Comment by eorono** [comment]
en el espacio para escribir el mensaje se muestran 5 lineas de texto despues de 5 se activa un scroll para no ocupar toda la pantalla con el mensaje que se esta redactando, igual ocurre en wasap y en otras plataformas de mensajeria instantanea, no es un bug

**Comment by RoyGF** [comment]
Si, entiendo, Mavi cuál es el problema que ves. Pero, pues se hizo así porque se ha demostrado que eso funciona de manera eficiente en otros chats: como whastapp, facebook (que incluso tiene un scroll), skype, slack, hangouts y así... Ya que así el usuario puede tener una mejor visibilidad de la conversación, por si le llegan otros mensajes, etc. Es muy útil, de hecho :)

**Comment by MaviDavsa** [comment]
No chicoss!! No me entienden! Yo no hablo de las 5 líneas! Eso esta muy biennn!!! Tal vez un poco exagerado! Creo que con 3 estaría bien! pero yo me refiero a que, mientras tu linea de texto se hace mas grande, los mensajes que ya has enviado se deberían de desplazar para arriba, en cambio el chat lo que hace es taparlos... Tapo el ultimo mensaje de Jajajaja okay! Que yo había enviado! @eorono  @RoyGF

**Comment by RoyGF** [comment]
ahhhh ya te entendí. Claro, Mavi. Lo reporto y lo corregimso

**Comment by MaviDavsa** [comment]
@RoyGF @eorono Ya se mueve el texto pero lo hace muy lento! por ende hace que se vean feos los movimientos en vez de que todo sea en armonía!

**Comment by AdryCanonico** [comment]
@RoyGF persiste el error en la version 19.5 de CBP

**Comment by maydiamc** [comment]
en la version 20.1 no se pudo revisar este caso por problemas de conexion, qued pendiente para la proxima version

**Comment by RoyGF** [comment]
tmbn voy a revisar este, denme chance

**Comment by josejcb** [comment]
Ya este detalle grafico fue solventado en la version 20.4 o 20.3 de testing

**Comment by josejcb** [comment]
Esto fue solventado en la version 20.3 o 20.4 de cbp testing. Chequeenlo, y en dicho caso, cerramos este tema.

**Comment by Hernandezsmanu** [comment]
En la version 20.4 persiste este error.

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16773759/22ba330c-4827-11e6-9c81-8a54f537cb37.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16773800/4d557158-4827-11e6-8e68-c8066aaeca31.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.4 continua el error.

![chatii](https://cloud.githubusercontent.com/assets/19883115/16773883/9e9b6054-4827-11e6-9c2e-91a4118a7529.png)


![chi](https://cloud.githubusercontent.com/assets/19883115/16773888/a3bc6786-4827-11e6-8dce-d174fd0d0d0d.png)

**Comment by yolandayancel** [comment]
Prueba 13-07-16
Caso 373 CBP 20.5
Nexus   api 21 480dpi
Logcat 01:54pm
[logcat13-07-16.zip](https://github.com/Fermat-ORG/beta-testing-program/files/362117/logcat13-07-16.zip)
Persiste el error
![373](https://cloud.githubusercontent.com/assets/17283358/16814071/43f4cce0-4902-11e6-82d8-a323dd57706a.png)

**Comment by marielis-urbina** [comment]
En la versión 20.6 de Chat persiste el mismo error en mi emulador

![chat](https://cloud.githubusercontent.com/assets/19353722/16857079/b94c2da0-49eb-11e6-8586-9c23293d2e54.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16857084/c028d81c-49eb-11e6-9353-e2a98a7fc69b.png)

**Comment by dorzar1989** [comment]
En la Version 20.7 de la CBP persiste este error.

- Screenshots:

![screenshot_56](https://cloud.githubusercontent.com/assets/19670319/16889806/31f7089e-4ab7-11e6-9b0f-3a9ecaafa7a2.png)


- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/366905/logcat.txt)


- Movil:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16889801/2b5de5b6-4ab7-11e6-8850-67d52bd49c14.png)

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP, persiste el error hoy 18/7/16

![prueba](https://cloud.githubusercontent.com/assets/19353722/16919369/61ac80b0-4cd7-11e6-8680-26f0cff5ffc6.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16919375/65253bf6-4cd7-11e6-958c-1c83c85e2247.png)

**Comment by LilianFlores** [comment]
En la versión 20.8, este error continúa. 

![dd](https://cloud.githubusercontent.com/assets/19652611/17005758/e8c6a23c-4ea9-11e6-922d-709ae066a293.png)

![jsjsjs](https://cloud.githubusercontent.com/assets/19652611/17005767/f34b4e38-4ea9-11e6-805a-aa547ae85ed5.png)

![celular](https://cloud.githubusercontent.com/assets/19652611/17005847/a81d0fae-4eaa-11e6-8dd6-2862c6677eaa.png)

**Comment by RoyGF** [comment]
Este issue lo ando trabajando, yo les aviso cuando esté resuelto. ;)

**Comment by MaviDavsa** [comment]
Este problema sigue en la versión 21.0 CBP

![image](https://cloud.githubusercontent.com/assets/17273005/17143800/959fc390-5322-11e6-8d38-2d2d3d50d494.png)
![image](https://cloud.githubusercontent.com/assets/17273005/17143857/cdbc066c-5322-11e6-8fea-e3bbff4276be.png)

Teléfono donde se realizo la prueba.

![image](https://cloud.githubusercontent.com/assets/17273005/17143884/e8f00fc8-5322-11e6-85d4-5152e5ca913d.png)

**Comment by hcampos1984** [comment]
el error se mantiene en la version 21.1 
![image](https://cloud.githubusercontent.com/assets/20233469/17266730/fe6bfa3e-55c9-11e6-9c82-e8630e14796a.png)
![image](https://cloud.githubusercontent.com/assets/20233469/17266739/155dfbde-55ca-11e6-96e0-89a93a8b4bff.png)

@MaviDavsa

**Comment by Hernandezsmanu** [comment]
En la version 21.6 persiste el error.

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/17444939/a44afacc-5b10-11e6-8336-e365671cba08.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/17444963/b8257fcc-5b10-11e6-9e7f-56268d2e7129.png)

**Comment by dorzar1989** [comment]
En la version 21.6 de la CBP no persiste este error

- Screenshot: 

![screenshot_182](https://cloud.githubusercontent.com/assets/19670319/17445991/45846b9a-5b15-11e6-88fb-1cc51e79772e.png)

![screenshot_183](https://cloud.githubusercontent.com/assets/19670319/17445992/45915f62-5b15-11e6-810e-410dd475cba1.png)

![screenshot_184](https://cloud.githubusercontent.com/assets/19670319/17445993/459a0a4a-5b15-11e6-96e7-7a63bd4c654f.png)

- Emulador: 


![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17445980/3a09b982-5b15-11e6-8878-8ed318d14376.png)

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 373 CBP 21.6 (CHAT)
Sony Xperia  S 4.1.1 16api 320dpi
Ocurre lo reportado.
![373](https://cloud.githubusercontent.com/assets/17283358/17446680/58e583c4-5b18-11e6-95d2-11ff62c58a21.png)

**Comment by RoyGF** [comment]
Chicos, este issue estará hasta la próxma versión de chat ya que de. ;) Yo les comento cuando esté listo.

**Comment by IsbetVR** [comment]
Este error persiste en la versión 21.7 de CBP

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/17494859/934604ee-5d84-11e6-903b-df0e221a9ada.jpg)

![screenshot_18](https://cloud.githubusercontent.com/assets/19142276/17494866/9960cb2a-5d84-11e6-89b8-23a4eb1099e8.jpg)


#### Dispositivo de prueba
- [x] Emulador

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/17494881/a84bd814-5d84-11e6-9e26-6bffb689a8db.jpg)

**Comment by dorzar1989** [comment]
En la Version 21.8 de la CBP aun persiste el error:

- Screenshot:

![screenshot_253](https://cloud.githubusercontent.com/assets/19670319/17569787/c9a2ddac-5f17-11e6-95fe-640f8d1b6f32.png)

![screenshot_254](https://cloud.githubusercontent.com/assets/19670319/17569788/c9aa1fe0-5f17-11e6-9079-92b3bea608ae.png)


- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17569801/d2be1be0-5f17-11e6-8661-b017434d242e.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 373 CBP 21.9
Sony Xperia S 4.1.1 16 api 320dpi

Ya no ocurre lo reportado..
![screenshot_5](https://cloud.githubusercontent.com/assets/17283358/17598566/174dfc7e-5fc9-11e6-815f-0fb94441759e.png)

**Comment by marielis-urbina** [comment]
En la versión 22.0 de CBP, en mi emulador persiste el error

![chat](https://cloud.githubusercontent.com/assets/19353722/17699760/89319b1e-6390-11e6-9d57-4d02a785a8e1.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17699763/8c810bd8-6390-11e6-95b6-65958d0ec4cf.png)

**Comment by yolandayancel** [comment]
Prueba 16-08-16
Caso 373 CBP 22.0
Sony Xperia S 4.1.1 16 api 320dpi
Se monta el texto..
![screenshot_2](https://cloud.githubusercontent.com/assets/17283358/17701966/ff2e2d88-6399-11e6-862c-91888d553db9.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17283358/17701977/067652dc-639a-11e6-8071-acc0533cded3.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17702035/3fab111e-639a-11e6-8dff-eb8d99149fe5.png)

**Comment by GeronimoVierma** [comment]
En la versión 22.3 persiste el error del texto montándose en los últimos mensajes :

![chat 1](https://cloud.githubusercontent.com/assets/19883115/17819326/5a75f612-6615-11e6-8ed1-d40ceb452ade.png)

![chat](https://cloud.githubusercontent.com/assets/19883115/17819339/618d90e0-6615-11e6-8345-9affb96a827e.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17819346/691ec87e-6615-11e6-949b-abdde496fb65.png)

**Comment by wendyduran90** [comment]
En la versión 22.3 persiste el error el texto se expande demasiado y oculta los mensajes. Esta prueba se realizo desde un teléfono móvil con versión de android 4.4.4 marca BLU modelo life one 2015 Tamaño	720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop)

![screenshot_2016-08-22-09-22-15](https://cloud.githubusercontent.com/assets/20212920/17856306/d499c658-684a-11e6-9f20-490910bc373d.jpg)

**Comment by GeronimoVierma** [comment]
Versión 22.3 
Persiste el error del texto montándose en los últimos mensajes :


![screenshot_14](https://cloud.githubusercontent.com/assets/19883115/17856203/5196df52-684a-11e6-97d4-fa46b64f9eb5.png)

![screenshot_13](https://cloud.githubusercontent.com/assets/19883115/17856194/4a12b828-684a-11e6-9a1e-340f4362e9fd.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17856237/78772ec4-684a-11e6-9870-ea036950242d.png)

**Comment by arosiopr** [comment]
El error reportado persiste en la versión 22.4 de CBP

![screenshot_2016-08-23-09-04-04](https://cloud.githubusercontent.com/assets/5313326/17892829/334ad77a-6911-11e6-8820-396ba9409791.png)

Teléfono Físico 

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17892840/3a046298-6911-11e6-9630-9122c00d4b6f.png)

**Comment by arosiopr** [comment]
En la versión 22.5 de CBP persiste el error reportado, aun se monta un poco en la nube del mensaje que me envió el contacto.

![screenshot_2016-08-23-14-29-19](https://cloud.githubusercontent.com/assets/5313326/17904657/30b119de-693e-11e6-8cf7-3f266157e494.png)

Teléfono Físico

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17904634/16631cee-693e-11e6-826b-261db1004d8b.png)

**Comment by yolandayancel** [comment]
Prueba 23-08-16
Caso 373
versión 22.5 de CBP 
En este emulador el error  reportado no ocurre (no se monta los textos)
![373 2](https://cloud.githubusercontent.com/assets/17283358/17904908/2ceded4e-693f-11e6-8b29-6d576404d6f9.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/17283358/17905073/c32d287e-693f-11e6-98fd-64364f485aa2.png)

**Comment by marielis-urbina** [comment]
En la versión 1.2 de Chat, este error no sucede en mi emulador 

![samsung](https://cloud.githubusercontent.com/assets/19353722/18288742/b478b8dc-744a-11e6-975a-658319559223.png)

**Comment by AdryCanonico** [comment]
No sucede en el telñefono fisico con la version 1.2 de chat en el nuevo nodo
