### ISSUE TITLE
LPW_contacts_ pantalla en blanco y botones desubicados

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#374]
### LPW 

-----
##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [x] Pop up de agregar un contacto

##### Reporte de error: 

   * Al ingresar a la pantalla de contactos esta aparece en blanco y no se muestran los contactos agregados, ademas  al precionar el boton de agregar contactos los iconos de, add fermat user y external user, no aparecen en el lugar correcto, sino que se amontonan en la esquina superior izquierda haciendo imposible la visibilidad de estos
   
   ![screenshot_2016-05-24-17-54-30](https://cloud.githubusercontent.com/assets/17274154/15522470/7297c77a-21dc-11e6-82b1-3613447b380f.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: s4 mini
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@maydiamc  Corregido verificar en la nueva version de la apk

**Comment by maydiamc** [comment]
solucionado el error en la ultima apk @MaviDavsa @nattyco
