### ISSUE TITLE
Bitcoin Wallet_ home_ el balance no aparece

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#375]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   * En algunas ocasiones al pasar de una pantalla a otra, al ingrear al menu home, no se muestra el balance solo las transacciones enviadas y recibidas, para verlo hay que entrar a otra pantalla cualquiera y volver al home, esto sucede solo en algunas ocasiones y desde cualquier lugar. 

![screenshot_2016-05-24-18-35-23](https://cloud.githubusercontent.com/assets/17274154/15522688/083a6340-21de-11e6-953a-07eb15625f7c.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@MaviDavsa @nattyco

**Comment by IsbetVR** [comment]
Ocurrió lo mismo en el:
Google Nexus 5
Versión Android 5.1
Estando en otra parte de la aplicación y al darle click al "Home" no lo muestra. Se queda en la pantalla de las transacciones. Tuve que salir y volver a entrar para que apareciera el "Home"

![screenshot_80](https://cloud.githubusercontent.com/assets/19142276/15523269/3de9ae7a-21e7-11e6-876c-f299244e34ac.jpg)

**Comment by maydiamc** [comment]
se soluciono este problema en la ultima actualizacion @MaviDavsa @nattyco

**Comment by sanro14** [comment]
@IsbetVR revisa tu para ver si en tu dispositivo se solucionó y proceder a cerrarlo

**Comment by nattyco** [comment]
@sanro14 verificar en la version 7 de la apk

**Comment by IsbetVR** [comment]
Ya no me da el error @sanro14, verificado en la v10

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco en la versión 15.2 de LPW aun persiste este error. Me llegaron los Btc pero no se ve reflejado en RECEIVED. Por favor reabrir el caso. 

![screenshot_1](https://cloud.githubusercontent.com/assets/18584168/15940812/8c023f7a-2e47-11e6-9e40-5d7f53469510.png)

DISPOSITIVO:

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15940820/98437074-2e47-11e6-82c6-de497122281b.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco en la versión 16.2 de LPW  Se corrigió el error. Se puede cerrar el caso
