### ISSUE TITLE
LPW- ERROR AL ENTRAR A LA APLICACIÓN 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#376]
##### Reporte de error: 

Cuando trate de entrar a la LPW marcó "recovering from system error", seguidamente se cerró y mostró mensaje de bienvenida. Al cerrar el emulador y entrar de nuevo persistía el error.
  
![capture-20160525-082319](https://cloud.githubusercontent.com/assets/17262077/15541214/3b52e71c-2255-11e6-927e-44b57bd428ef.png)

![capture-20160525-082343](https://cloud.githubusercontent.com/assets/17262077/15541221/417b0d18-2255-11e6-8430-b8bbe8308a7d.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 7
* Version de Android: 5.0.0

**Comment by Gabymorillo** [comment]
@nattyco

**Comment by maydiamc** [comment]
este error no se presento en la ultima  actualizacion @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
