### ISSUE TITLE
CHAT- community- Banner de bienvenida no se quiere activar.

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#377]
#### Nombre pantalla

Chat community

##### Reporte de error: 

   *Estando en el Chat community, el banner de bienvenida no se activa, clikeo sobre el simbolo de la interrogación (?) para que aparezca y tiene configurado (tildado-dont show this again) se la quito, salgo e ingreso y sigue tildado. Por eso el banner no aparece.
![error- chat conmunity -banner](https://cloud.githubusercontent.com/assets/17283358/15541391/0d9f78f2-2256-11e6-8068-462744ba28fc.png)

![error- chat conmunity -banner 1](https://cloud.githubusercontent.com/assets/17283358/15541397/177c2af0-2256-11e6-86d1-3038e8760e10.png)
![error- chat conmunity -banner 2](https://cloud.githubusercontent.com/assets/17283358/15541454/5bb43032-2256-11e6-9a59-bbfc8673e707.png)

------

#### Dispositivo desde donde se realizo la prueba

![emulador genymotion -samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15541490/86eafdf8-2256-11e6-8d0e-47fd3fdd92c9.png)

**Comment by MaviDavsa** [comment]
@yolandayancel Explica mejor este Issues!

**Comment by eorono** [comment]
Esto es un mensaje de ayuda, solo deberia aparecer una vez y es cuando entras a las comunidades por primera vez, el mensaje sale y se repite solamente cuando entras a las comunidades sin tener identity y saldra tantas veces entres a las comunidades sin tener identidad creada

**Comment by MaviDavsa** [comment]
Entiendo tu punto amigo! @eorono Pero creo que una vez que se dice que no se quiere volver a ver este mensaje no debería de aparecer! Sino, no des la opción a la persona de no mostrar otra vez el mensaje! No se si me explico!?

**Comment by franklinmarcano1970** [comment]
@MaviDavsa @yolandayancel  Pero siempre te va salir solo en ese caso a cada momento, porque no tiene identidad creada, ya una vez que tengas la identidad creada, ya no te saldra mas y solo te sale si le das al presionar el boton de ayudar, pero si aun asi le quitas el check de que no aparezca mas, pero aun no tiene identidad creada, esa logica lo tomara en cuenta porque a la final lo que se quiere es que el usuario sepa que no tiene identidad creada.

**Comment by MaviDavsa** [comment]
Entiendo... Ahora @yolandayancel Teniasssss identidad creada o no!?

**Comment by yolandayancel** [comment]
Si Maria lastima no tengo luz aquí. Pero yo les explicó detallado mañana.
En este caso el banner no aparece. Esta tildado para que no aparezca.

**Comment by yolandayancel** [comment]
Si tenía identidad

**Comment by yolandayancel** [comment]
@franklinmarcano1970 

Buenos días
Caso 377
![caso 377 verificacion sigue preconfigurado para que no aparezca](https://cloud.githubusercontent.com/assets/17283358/15574437/226390d6-2317-11e6-882a-f3bb63bf977e.png)

Explicación de lo observado
Estando en el Chat community, revisando los contactos, pude observar que en Banner no aparecía ( te sale  a cada momento). Clikee en el símbolo de interrogación y donde se ve pre configurado para que no salga. Como me di cuenta quitando la tilde en Dont show again, saliendo y entrando nuevamente.  Tenía identidad creada.
Prueba 26-05-16
1 Borre la data en setting
2 ingrese a la community sin usuario, para probar lo que me comentaste ayer y salir todos de la duda sobre el banner.
 3 Ingrese en Identity para verificar  que no tenga identidad
4 Ingresé a la Community: entre en contactos, en notificaciones y en el Home, espere un rato y el Banner no apareció.
5 Ingrese en el Símbolo de Ayuda: Como les indique está preconfigurado (tildado para que no aparezca).
Conclusión: En la prueba se demuestra que el Banner no aparece, tenga Identidad o no.
Saludos

**Comment by yolandayancel** [comment]
Prueba 04-07-16
Caso 317 Chat-CBP 19.2
Samsung S6 5.1.0
Cerrar este caso. Como tal esto esta configurado para que no salga.(Chat community, el banner de bienvenida no se activa)
![317](https://cloud.githubusercontent.com/assets/17283358/16568465/7fbc6730-41f8-11e6-8362-ac2d93c7ed22.png)
