### ISSUE TITLE
Sub App Identity - Error al agregar foto de perfil

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#378]
##### Reporte de error: 

   *Cuando intento cambiar la imagen del perfil me saca de la aplicación y empieza a abrirse de nuevo.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Lg
* Modelo: l5
* Version de Android: 4.2

**Comment by nattyco** [comment]
@sanro14  desde que opcion quisiste cambiar la imagen, camara o galeria?

**Comment by sanro14** [comment]
@nattyco  desde Galeria..

**Comment by sanro14** [comment]
@MaviDavsa Cierralo! esta resuelto
