### ISSUE TITLE
Sub App Identity-No deja crear mi identidad

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#379]
##### Reporte de error: 

   *Cuando intento crear mi identidad dice creado con éxito, y cuando voy a entrar al comunity para revisar mis solicitudes, sale el wizard de seleccionar si es mujer u hombre, le doy seleccionar y me saca del comunity, cuando voy a revisar mi perfil, no aparece creado, pero le salgo a los otros usuarios. (Observación: Como los errores salieron rapido, no pude tomar capture, pero lo he intentado reiteradas veces y continua sucediendo lo mismo)
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Lg
* Modelo: L5
* Version de Android: 4.2

**Comment by sanro14** [comment]
@nattyco

**Comment by sanro14** [comment]
@nattyco en el emulador no me da ese error, da en el Lg l5 la versión es 4.2, es extraño..

**Comment by maydiamc** [comment]
este error no se muestra en la version 11 @MaviDavsa @nattyco

**Comment by MaviDavsa** [comment]
Solucionado

**Comment by RubenSem** [comment]
@MaviDavsa @nattyco Creo el usuario y cuando intento meterme en Crypto wallet user sale el wizard de seleccionar si es mujer u hombre, le doy seleccionar y me saca del comunity.
![screenshot_8](https://cloud.githubusercontent.com/assets/19676223/15780983/ef3df61c-296d-11e6-9659-ed6c3263a3d5.jpg)
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/15780992/fed6d346-296d-11e6-97f6-201639162dba.jpg)

**Comment by LilianFlores** [comment]
Cuando creo el usuario y entro en Crypto Customer, se muestra el wizard(pantalla 1). Al seleccionar, simplemente me dice que Fermat no responde(pantalla 2), doy clic en "Wait" y se quita, pero cuando doy para ir atrás y salir del Crypto vuelve a aparecer que Fermat no responde. No me saca de ahí a menos que salga del app presionando para ir a Home. @nattyco @MaviDavsa 

![070616erroor](https://cloud.githubusercontent.com/assets/19652611/15878405/85ac708c-2ce4-11e6-81c1-4157b9586f55.png)

![fminrerror](https://cloud.githubusercontent.com/assets/19652611/15878447/d07ae530-2ce4-11e6-8493-16686b6bd430.png)


**Dispositivo desde donde se realizo la prueba**

![phone](https://cloud.githubusercontent.com/assets/19652611/15878339/fa386e2a-2ce3-11e6-9568-cb5d2cb5ef6f.png)

**Comment by nattyco** [comment]
@MaviDavsa  verificar si este error se sigue presentando

**Comment by RubenSem** [comment]
Solucionado en la nueva version, por favor cerrar caso. @nattyco
