### ISSUE TITLE
LPW-Transactions Sent-Error no sale lo que envie

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#380]
### Loss Protected Wallet 

-----

##### Reporte de error: 

   *Al entrar en la sección de transacciones enviadas "Transactions Sent" sale todo en blanco, no sale lo que le envié a Adry que fue 1,1234 BTC

![screenshot_37](https://cloud.githubusercontent.com/assets/5313326/15544539/eb2fac30-2262-11e6-87c3-6c664436736a.png)

A ella si le llegó lo que le envié y le sale en received normal. Pantalla del oro usuario @AdryCanonico 

![transaccion](https://cloud.githubusercontent.com/assets/5313326/15545134/0b22c39a-2265-11e6-81e7-0996f8bcc6bd.png)

Dispositivo del otro usuario:

![nexus 5](https://cloud.githubusercontent.com/assets/5313326/15545159/26768b36-2265-11e6-91a0-e991b884fedc.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@arosiopr este error es constante o es aleatorio?

**Comment by arosiopr** [comment]
@nattyco constante reinicie en varias ocasiones y siguio saliendo

**Comment by nattyco** [comment]
@arosiopr probaste con la nueva version de la apk?

**Comment by MaviDavsa** [comment]
@nattyco Si! Ella esta trabajando con la nueva apk!

**Comment by nattyco** [comment]
Borraron los datos para empezar de nuevo?

**Comment by MaviDavsa** [comment]
@nattyco Ajam! De todas maneras ella en la noche revisa de nuevo!

**Comment by arosiopr** [comment]
@MaviDavsa corregido, se puede cerrar
