### ISSUE TITLE
Application-Tiempo de inicio es muy largo

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#382]
##### Reporte de error: 

   *Cuando intento abrir la aplicación dura aproximadamente 30 minutos (o mas) para entrar, y en el Nexus Android 5 no pude lograr iniciar la aplicación.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genimotion
* Modelo: probado en nexus 4 y nexus 5
* Version de Android: probado 4.4 y 5.0

**Comment by nattyco** [comment]
@furszy

**Comment by furszy** [comment]
@sanro14 30 minutos enserio? la dejaste prendida todo ese tiempo y corrió?.

**Comment by sanro14** [comment]
@furszy yo diría que duro mas.. a mi me abrió a una de las chicas no le abrió mas..

**Comment by sanro14** [comment]
Otra cosa, planteo lo que sucedió hoy, entré a la aplicación (tardo mucho en entrar pero entro) cuando estaba ya con mi perfil creado, tenia btc disponibles,  me enviaron una solicitud, cerré la aplicación, cuando intente entrar de nuevo no me dejo entrar, queda cargando, luego se queda el logo pegado en el inicio y nunca entra, lo intente 3 veces y nada, procedí a limpiar data, intente entrar, de nuevo tardo pero entró, hice el mismo proceso anterior, cerré la aplicación con data, intente abrirla y nada, no entra. Realice la misma secuencia de pasos y sucede lo mismo. esto paso en el Nexus 5 android 4.4.4, en el Nexus 4 Android 5 no me abre, queda cargando el logo..

**Comment by sanro14** [comment]
@nattyco

**Comment by furszy** [comment]
Testeas en emuladores no?

**Comment by sanro14** [comment]
@furszy si, claro..

**Comment by arosiopr** [comment]
Me sucedió lo mismo se quedó en el logo cargando, no abrió, limpie data, me dejo entrar, cree mi perfil realice operaciones, la cerré porque se quedo pegada en contactos, la volví a abrir y se quedo cargando en el logo de fermat, espere como 15 min, nada no entraba, volvi a limpiar data y ahí si dejo entrar.

**Dispositivo desde donde se realizo la prueba:**

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by Gabymorillo** [comment]
En mi caso no me dejó entrar a la aplicación, se quedó cargando  por un largo rato, al final se quedaba pegado con el logo de fermat y en otro se quedó la pantalla en blanco. Se probó en 3 emuladores diferentes. Estas pruebas se realizaron bajo las indicaciones que fueron sugeridas: trabajar en la pc (con una memoria ram de 4GB) solo con el emulador y el skype para las videollamadas, sin utilizar ningún navegador u otro programa. 

![capture-20160606-184745](https://cloud.githubusercontent.com/assets/17262077/15842119/101fcb44-2c20-11e6-9eb3-d616ab420474.png)

![capture-20160606-191556](https://cloud.githubusercontent.com/assets/17262077/15842120/102b6968-2c20-11e6-89b7-a9d5e2d1168e.png)

![capture-20160606-193935](https://cloud.githubusercontent.com/assets/17262077/15842121/102db812-2c20-11e6-9e5a-e78316cb0104.png)

Dispositivos desde donde se realizaron las pruebas:

Marca: Genymotion (primera imagen)
Modelo: Google Nexus 4
Version de Android: 5.1.0

Marca: Genymotion (segunda imagen)
Modelo: Google Nexus 5
Version de Android: 6.0.0

Marca: Genymotion (tercera imagen)
Modelo: Google Nexus 6
Version de Android: 5.0.0

**Comment by gablup** [comment]
Me sucedió lo mismo, del logo de Fermat congelado, al momento de cargar para entrar en el emulador Nexus 7 y no respondió más a pesar de intentarlo en varias oportunidades y siguiendo las mismas indicaciones que fueron sugeridas: trabajar en la pc (con una memoria ram de 4GB) solo con el emulador y el skype para las videollamadas, sin utilizar ningún navegador u otro programa.

![Uploading error inicio de fermat.PNG…]()

**Comment by gablup** [comment]
Me sucedió lo mismo, del logo de Fermat congelado mientras cargaba, para iniciar la apk. Utilice Nexus 7 y no respondió más, a pesar de intentarlo en varias oportunidades y siguiendo las mismas indicaciones que fueron sugeridas: trabajar en la pc (con una memoria ram de 4GB) solo con el emulador y el skype para las videollamadas, sin utilizar ningún navegador u otro programa.

![error inicio de fermat](https://cloud.githubusercontent.com/assets/17261437/15842327/00198496-2c26-11e6-9b66-3e0d2a7b331c.PNG)

Por otra parte, me arrojó un error distinto con esta misma apk en el emulador Nexus 4, que no me permitía acceder, igualmente antes de iniciar Fermat y al darle a la opción "ok" cerraba inmediatamente.


![error fermat inicio](https://cloud.githubusercontent.com/assets/17261437/15842398/bc94013c-2c26-11e6-927e-5672861a34f7.PNG)

Dispositivos desde donde se realizaron las pruebas:

![acerca del emulador](https://cloud.githubusercontent.com/assets/17261437/15842421/df8f5e70-2c26-11e6-9126-ad803909c098.PNG)
 (Primer error)


![acerca del emulador nexus 4](https://cloud.githubusercontent.com/assets/17261437/15842525/b3042eca-2c27-11e6-8ed6-3f9fe7c4ae72.PNG)

(Segundo error)

**Comment by LilianFlores** [comment]
No me deja entrar a la aplicación, dura mucho tiempo cargando y luego se queda congelado en el logo de Fermat. En otras oportunidades, se queda en blanco completamente o en negro y no entra tras esperar un período de tiempo considerable.  

Las pruebas se realizaron bajo las indicaciones que fueron sugeridas: trabajar en la pc (con una memoria ram de 4GB) solo con el emulador y el skype para las videollamadas, sin utilizar ningún navegador u otro programa.

![screenshot_5](https://cloud.githubusercontent.com/assets/19652611/15879005/e0af7d26-2ce9-11e6-82b0-5712bc1cd4ee.png)

**Dispositivo desde donde se realizo la prueba:**

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0

**Comment by LilianFlores** [comment]
En la versión 15.1 de LPW persiste este error al querer entrar a la aplicación. En este caso, no pude entrar de ninguna forma y el tiempo de espera fue bastante largo. Al final, o se quedaba en negro salía el mensaje de "Fermat isn't responding"(pantalla 1) o se congelaba y marcaba el mismo mensaje(pantalla 2). En ambos casos no reaccionaba al presionar "wait". 

![080616](https://cloud.githubusercontent.com/assets/19652611/15915693/60209a1a-2db5-11e6-90a8-f5c643e27a9d.png)

![fir](https://cloud.githubusercontent.com/assets/19652611/15915702/6d7c7378-2db5-11e6-8cdc-be872ceab458.png)

**Dispositivo desde donde se realizo la prueba:**

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0

**Comment by AdryCanonico** [comment]
@nattyco @furszy en la versión 16.2 me ocurre lo mismo en mi teléfono físico. Tarda mucho o se cierra la app. Tuve que hacer varios intentos para poder utilizarla. 


![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15969033/e920d3aa-2ef7-11e6-9e3e-f80357535934.png)
