### ISSUE TITLE
CHAT- BANNER ESTIRADO 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#384]
### CHAT

-----

##### Reporte de error: 

   *El banner del wizzar se ve muy estirado. Esto pasa solo en el Nexus 7, 213 dpi
   
![banner estirado chat fer](https://cloud.githubusercontent.com/assets/18584168/15547555/16b975ba-226e-11e6-8fcd-41c5d0ca2d82.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15547428/928a4af8-226d-11e6-880a-222c32428e5c.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
Persiste!! 

![error 1-2](https://cloud.githubusercontent.com/assets/17273005/15580023/de54c1f2-2330-11e6-93e4-cccf9cc118a0.JPG)

**Comment by IsbetVR** [comment]
En la Versión 7 del Chat persiste tanto cuando se va a crear el perfil a través de "profiles" y cuando entro a "Communities", los banners están muy estirados

Dispositivo:
Google Nexus 9 (320 dpi)
Versión 5.1.0

**Comment by Gabymorillo** [comment]
Periste el banners estirado dentro del chat. 

![capture-20160527-075002](https://cloud.githubusercontent.com/assets/17262077/15609139/133dc5aa-23e8-11e6-9207-c320c28ef1b7.png)

Dispositivo:
Google Nexus 7
Versión 5.0.0
