### ISSUE TITLE
CHAT - ERROR AL BORRAR CONTACTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#386]
### CHAT

-----

##### Home

-----

##### Reporte de error: 

   *Cuando se borra un contacto en la community. Este no es borrado automáticamente del chat. 

![3](https://cloud.githubusercontent.com/assets/18584168/15548213/35bb52be-2271-11e6-8096-b3c200c5d452.png)

hay que actualizar los contactos en chat para que este sea borrado.

pero si tienes mensajes abiertos con el contacto borrado, 

![sigue el chat](https://cloud.githubusercontent.com/assets/18584168/15548342/c13e846e-2271-11e6-8a22-d6f61d44f638.png)

puedes enviar mensajes aunque no le llegaran.

![7](https://cloud.githubusercontent.com/assets/18584168/15548322/a3f0d060-2271-11e6-8fcf-2d9f69b80113.png)

Este mensaje desapareció al momento de salir de el.

![8](https://cloud.githubusercontent.com/assets/18584168/15548371/dcbf1316-2271-11e6-9913-b527dcc8d292.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15548604/fe6a907a-2272-11e6-85a0-f286acbeaa04.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15548605/fe6e5606-2272-11e6-8955-bd96c806c123.png)

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 seria bueno que cuando quede el mensaje del chat (cuando se borra el contacto) este de un mensaje como whatsapp, para que el usuario sepa que tiene que agregar al contacto nuevamente para lograr comunicarse.

**Comment by franklinmarcano1970** [comment]
@AdryCanonico @MaviDavsa Debemos de probar porque cuando se desconecta a alguien y le llega el mensaje de confirmacion de desconexion al remoto, no te debe aparecer mas en chat ni en contactos, pero que pueda pasar que no le haya llegado la confirmacion y aun sigas viendolo...pero en resumen hay que probarlo porque no debe de pasar......

**Comment by AdryCanonico** [comment]
@franklinmarcano1970 @MaviDavsa  En la versión 6 se corrigió el error. Se puede cerrar el caso.

**Comment by franklinmarcano1970** [comment]
@AdryCanonico @MaviDavsa Listo solucionado cerrar el caso...
