### ISSUE TITLE
LPW- PANTALLA DE HOME PIXELADA

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#387]
##### Reporte de error: 

Cuando vemos la pantalla del Home podemos notar que esta completamente estirada y pixelada.
   

![capture-20160525-175704](https://cloud.githubusercontent.com/assets/17262077/15558568/b0292bd8-22a4-11e6-9816-d62b90cc1ecb.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 7
* Version de Android: 5.0.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by maydiamc** [comment]
este error no se presento en la ultima actualizacion @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Solucionado!
