### ISSUE TITLE
LPW- ERROR EN EL MONTO DE BTC

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#389]
##### Reporte de error: 

 Al pedir los btc a la LPW llega la cantidad de 50000000

![capture-20160525-182718](https://cloud.githubusercontent.com/assets/17262077/15558881/62343d52-22a7-11e6-9404-feb84134f559.png)

  
#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 7
* Version de Android: 5.0.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@Gabymorillo  eso te paso al cambiar el balance desde el touch to change?

**Comment by maydiamc** [comment]
no se presenta este error, solucionado @MaviDavsa @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
