### ISSUE TITLE
CBP - FALTAN CUENTAS 

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#390]
#### Nombre pantalla
SELECT STOCK WALLETS

### CRYTO BROKER
-----

##### Reporte de error: 

   * Bueno en este caso se puede ver que existen 3 cuentas agregadas a las wallets asociadas. 
![dfsadsafs](https://cloud.githubusercontent.com/assets/17273005/15559901/fe2266d2-22af-11e6-8df1-6b756f3f110b.JPG)

Sin embargo cuando vamos a la ventana de "assig a wallet to each item" Solo me aprece disponible un item o una tasa de cambio, lo cual esta mal, tomando en cuanta que desde el principio se metieron 3 cuentas lo ideal es que me aparezcan 3 cambios de monedas o 3 item diferentes... Uno para la bitcoin wallet, otro para el cash y otro para la banking

![esdfgsdf](https://cloud.githubusercontent.com/assets/17273005/15559903/01afabca-22b0-11e6-8cf8-5c10ff22fd17.JPG)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion 
* Modelo: Google Nexus 4
* Version de Android: 5.1.0

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by yalayn** [comment]
Hola @MaviDavsa. No necesariamente el numero de wallet asociadas en el paso **"SELECT STOCK WALLETS"**, debe coincidir con el numero de ítem del siguiente paso el **"SELECT EARNING WALLET"**. Dado que los ítem que allí aparecen están relacionados a las monedas que representa cada wallet. Ya que el objetivo de ese paso es indicar cual sera la wallet a donde se destinaran las ganancias por cada par de moneda . Es decir si se adicionan una **Crypto Wallet** con **BTC**, una **Cash Wallet** y una **Bank Wallet** con la misma moneda, por ejemplo **ARS**, solo se mostrara un ítem el **BTC/ARS** y luego al pulsar sobre ese par se mostrara un dialogo con las 3 wallets indicadas en el paso anterior, la que se seleccione sera la wallet de ganancia para dicho par.

**Comment by MaviDavsa** [comment]
Así tiene medio sentido! Pero en todas las wallets tengo monedas diferentes! :) @yalayn .... Entonces me deberían salir monedas diferentes!

**Comment by yalayn** [comment]
Hola @MaviDavsa. Si de ser monedas diferentes si deberían aparecer mas ítem en total 3. Ayer antes de responderte hice varias pruebas y me daban las combinaciones correctas. Voy a trabajar en eso en seguir probando. Porfa si puedes hacer otra prueba para también confirmar que este pasando te lo agradecería mucho :). También voy a trabajar en mostrar la moneda que maneja cada wallet en el "SELECT STOCK WALLETS" y así poder ver mejor las combinaciones que se darán en el "SELECT EARNING WALLET". Saludos.

**Comment by MaviDavsa** [comment]
@yalayn Perfecto! Eso seria genial! :) ... Y vale déjame ver como lo puedo ver!

**Comment by yalayn** [comment]
Buenas noches @MaviDavsa. Hice las modificaciones que te había mencionado de agregar la moneda asociada a la wallet en el paso SELECT STOCK WALLETS. Ahora se podrá apreciar mejor si ocurre el bug. En las pruebas que hice el día de hoy no me ocurrió. Para la próxima versión de la app debería estar disponible esta modificación, porfa cuando este disponible realiza algunas pruebas y nos cuentas como te fue :). Anexo dos imágenes donde se puede visualizar lo que te comentaba anteriormente. En el ANEXO1 se indican en dos wallets la misma moneda. En el ANEXO2 todas las wallets tienen diferentes monedas. 
Saludos. Feliz noche.

**ANEXO1**
![selectearningwallets_1](https://cloud.githubusercontent.com/assets/4664287/15593803/53805c3c-2379-11e6-8883-fafea7be589e.png)

**ANEXO2**
![selectearningwallets_3](https://cloud.githubusercontent.com/assets/4664287/15593844/9c93e952-2379-11e6-872b-c1bc18cd8578.png)

**Comment by nelsonalfo** [comment]
Se puede cerrar este Issue?

**Comment by MaviDavsa** [comment]
Solucionado!
