### ISSUE TITLE
CBP-Crypto Customer - Customer Wallet: Sin limite de caracteres en campos de registros de entrada.

### ISSUE THREAD

**Issue by alegnaire** [Fermat-ORG/beta-testing-program#391]
##### Reporte de error:

En la sección Create Location no se tienen limites de caracteres en los campos de registro “Location", "Zip/Postal Code", "State/Province”," Address line 1" y "Address line 2".

![captura de pantalla 2016-05-25 a las 8 11 53 p m](https://cloud.githubusercontent.com/assets/18564248/15560154/9a484eee-22b2-11e6-8c6a-fb7716d03e7c.png)

Mismo caso ocurre en la sección Create Bank Account:
![captura de pantalla 2016-05-25 a las 8 33 34 p m](https://cloud.githubusercontent.com/assets/18564248/15560324/4d0c1e38-22b4-11e6-9a84-848dce9e415f.png)

Es necesario la definición los dichos limites permitidos en cada campo de registro, de acuerdo al espacio de visualización especificada.

#### Dispositivo desde donde se realizo la prueba

* Marca: SAMSUMG
* Modelo: S6
* Version de Android: 6.0.0

**Comment by abicelis** [comment]
Yo agarro este issue

**Comment by abicelis** [comment]
@alegnaire En la version v13 del app se limitaron los campos a lo siguiente:
Zip max 15 char, numeros solamente
State max 30
City max 30
Address 1 max 100
Address 2 max 100

**Comment by abicelis** [comment]
@MaviDavsa @alegnaire en la version v14 del app estan limitados todos los campos de ambas pantallas (create location, create bank account) que muestras en este issue. Ademas ambas tienen los textwatchers de @AdryCanonico. Revisala y me dices!

**Comment by nelsonalfo** [comment]
Se puede cerrar este Issue?

**Comment by MaviDavsa** [comment]
Solucionado!
