### ISSUE TITLE
CBP - Crypto Broker 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#392]
##### Reporte de error: 

No debería dejar avanzar ya que necesito dos billeteras para poder pasar al siguiente paso, en este caso el error radica en que en lineas generales no debería dejar avanzar. Ya que, solo hay una billetera y la misma aplicación me dice que necesito dos para pasar al siguiente paso, por ende lo que hace es darme un error mas adelante y no dejarme crear la billetera. 

![image](https://cloud.githubusercontent.com/assets/18452495/15559996/f38720a4-22b0-11e6-92ce-9f681a6f5381.png)

![image](https://cloud.githubusercontent.com/assets/18452495/15560014/2d0539a6-22b1-11e6-930a-8d6d7e4c5653.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18452495/15560054/93297698-22b1-11e6-82da-3168dc89c4ce.png)

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by abicelis** [comment]
@andreagmarcano @MaviDavsa es cierto, yo agarro este issue!

**Comment by abicelis** [comment]
@andreagmarcano 
Listo, en la version v13 esta este fix!

**Comment by nelsonalfo** [comment]
Se puede cerrar este Issue?

**Comment by MaviDavsa** [comment]
Este Si esta Solucionado ya!
