### ISSUE TITLE
DAP  -  ERROR AL CARGAR LA IMAGEN EN TRANSACTIONS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#393]
### DAP

-----

##### Reporte de error: 

   * En Transactions se se corta la imagen de los asset.

![8](https://cloud.githubusercontent.com/assets/18584168/15561401/3b1672d6-22bf-11e6-9fbc-0776db530da8.png)

![7](https://cloud.githubusercontent.com/assets/18584168/15561403/3ed54104-22bf-11e6-9d84-05337a8037a8.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion 
* Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15561413/6367ec1a-22bf-11e6-91f7-bbc909b4061f.png)

**Comment by AdryCanonico** [comment]
@nindriago

**Comment by nindriago** [comment]
buenas noches, @MaviDavsa quitale la label de BUG por favor, ya que no es un bug como tal, pero si es un ISSUE GRAPHIC

**Comment by nindriago** [comment]
Revisar en nueva version de APK

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa En la versión 3 se corrigió la carga de cupones. Se puede cerrar el caso.

Dispositivo Nexus 7

![cuponestodostodos](https://cloud.githubusercontent.com/assets/18584168/15675726/0f51ffc4-270d-11e6-89bc-6cd2e47a8fd8.png)
