### ISSUE TITLE
Communities - Crypto Customer - No se visualiza botones en el Wizzar

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#394]
#### Communities - Crypto Customer

-----

##### Reporte de error: 

   *En la versión v12 de la CBP, al entrar al "Communities / Crypto Customer" (Pantalla 1), el Wizzar sale cortado en la parte de abajo, y no permite bajar con el scroll, haciendo difícil utilizar los botones.

------

##### Pantalla 1
![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/15576117/4b32c48e-2324-11e6-95cc-aa5fc89148d5.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5, 480 dpi
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15576139/663fdf96-2324-11e6-996f-60fabbd6e069.jpg)

**Comment by IsbetVR** [comment]
@nattyco @MaviDavsa

**Comment by nelsonalfo** [comment]
@abicelis toma este Issue para resolverlo por favor

**Comment by abicelis** [comment]
Este es mio, cuando lo resuelva les aviso @IsbetVR @MaviDavsa

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa este fix esta en la version v15!

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa Corregido.
En la CBP v16.5 ya no sale este error... 


![screenshot_70](https://cloud.githubusercontent.com/assets/19142276/15982205/ad6b9cde-2f4f-11e6-8794-229d3ab91f72.jpg)
