### ISSUE TITLE
Bitcoin Wallet_contacts_ botones mal ubicados y amontonados

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#395]
### Bitcoin Wallet 

------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   * en la pantalla contactos, al ingresar y desplegar el boton de agregar, los botones del menu desplegable, fermat user y external user, aparece mal ubicados y amontonados en la esquina superior izquierda
![screenshot_2016-05-26-11-06-41](https://cloud.githubusercontent.com/assets/17274154/15579423/5e63e60a-232e-11e6-8978-33533f940c15.png)

------
#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by nattyco** [comment]
@maydiamc verificar esto en la version  de la apk

**Comment by nattyco** [comment]
@MaviDavsa  verificar este caso que hace varias versiones que esta corregido

**Comment by maydiamc** [comment]
solucionado el error en la version 11 @nattyco  @MaviDavsa

**Comment by MaviDavsa** [comment]
Solucionado!
