### ISSUE TITLE
BITCOIN WALLET - WELCOME POPUP LOS CHECK MONTADOS SOBRE EL TEXTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#396]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El check del wizzar se ve montado sobre el texto y no permite quitarlo. (Esto solo pasa con el Nexus S. 240 dpi)

![wizzar chec montado ns](https://cloud.githubusercontent.com/assets/18584168/15580003/cdb2eef0-2330-11e6-9300-ca927313ef94.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15580244/bba0a864-2331-11e6-84fc-5c7bcbdb1009.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  verificar en la version 10 de la apk

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la version 13 se corrigió. se puede cerrar el caso

**Comment by MaviDavsa** [comment]
Perfecto Solucionado!
