### ISSUE TITLE
CBP - Customer Wallets - Permite introducir muchos números en "Create Bank Account"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#397]
#### Customer Wallets - Create Bank Account (Configuración)

-----

##### Reporte de error: 

   *Permite en la configuración del "Bank Account" a través de "Customer Wallet", introducir una gran cantidad de números (Pantalla 1) y al ver los detalles desde el Home, en el "Bank Account List" (Pantalla 2) se ve una parte de la cantidad que introduje. Debería haber un límite.

------

#### Pantalla 1

![screenshot_5](https://cloud.githubusercontent.com/assets/19142276/15581085/ff0c49f8-2338-11e6-94cf-57d422353205.jpg)

#### Pantalla 2

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/15581099/0ace66cc-2339-11e6-8f9d-d1c5aba593eb.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5, 480 dpi
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15581169/3f78b0e4-2339-11e6-9e22-008125268f5e.jpg)

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa @nelsonalfo

**Comment by MaviDavsa** [comment]
@abicelis Tu acomodaste esto cierto!?

**Comment by abicelis** [comment]
@MaviDavsa nop, y ya agarre este issue!
En una proxima version les aviso cuando este aplicado el fix

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa En la v14 en ambas pantallas hay fixes de limites de campos, textwatchers de @AdryCanonico , mejoras en el layout en donde se ve montada una x debajo del texto, y otras cosas.
Cualquier cosa que vean diganme!

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa en la version CBP 16.2 este error esta corregido. Quedaron muy bien los campos 
@IsbetVR  no se si es un error especifico de tu emulador.

**Comment by MaviDavsa** [comment]
@IsbetVR Revisa y me avisas! por favor!

**Comment by dorzar1989** [comment]
En la Version CBP 16.4 este error ya esta corregido. 
![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/15825509/0b433be0-2bd2-11e6-89e5-88da264730b4.png)

**Comment by MaviDavsa** [comment]
Correcto! Ya lo verificamos! Solucionado!
