### ISSUE TITLE
COMMUNITY -  WIZZAR LOS CHECK MONTADOS SOBRE EL TEXTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#398]
### COMMUNITY

-----

##### Reporte de error: 

   *El check del wizzar se ve montado sobre el texto y no permite quitarlo. (Esto solo pasa con el Nexus S. 240 dpi)
   
![1 check wizzar montado perfil btc](https://cloud.githubusercontent.com/assets/18584168/15581224/47784696-2335-11e6-9080-b2753612d17d.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15580244/bba0a864-2331-11e6-84fc-5c7bcbdb1009.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by arosiopr** [comment]
en mi dispositivo también sale mal

![screenshot_2016-06-09-16-51-14](https://cloud.githubusercontent.com/assets/5313326/15949604/9eb064e6-2e72-11e6-947e-bce0939f4d25.png)

![screenshot_2016-06-08-19-21-55](https://cloud.githubusercontent.com/assets/5313326/15949619/b5c45944-2e72-11e6-9b08-54ae00f1474f.png)

**Comment by arosiopr** [comment]
en la version 16.2 de la apk sigue saliendo el check box montado en mi celular

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/15967983/d6e61a0a-2ef3-11e6-8f21-c8059e685703.png)

**Comment by marielis-urbina** [comment]
En la versión de la CBP 18.8, no ocurre este error

![ident](https://cloud.githubusercontent.com/assets/19353722/16524235/2551d142-3f71-11e6-8238-5bb1df50dd34.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/16524281/72473e24-3f71-11e6-82ab-6ce18b9b1c4b.png)
