### ISSUE TITLE
COMMUNITY - ERROR EN LA FOTO DE CONTACTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#400]
### COMMUNITY 

-----

##### Reporte de error: 

   *Al visualizar la foto del contacto en la community en el dispositivo se ve con un borde gris a la derecha que no es parte de la foto. 

*Esto pasa solo en el Nexus 7, 213 dpi

![cambio de nombre](https://cloud.githubusercontent.com/assets/18584168/15590466/c5ad7884-2361-11e6-914f-58cd3fe2408d.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15547428/928a4af8-226d-11e6-880a-222c32428e5c.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by camilavaleria** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico @camilavaleria @MaviDavsa yo agarro este issue! Cuando este listo les aviso.

**Comment by abicelis** [comment]
@AdryCanonico @camilavaleria @MaviDavsa En la version v15 vendra este fix!

**Comment by abicelis** [comment]
@camilavaleria @AdryCanonico pudieron revisar este bug?

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis en la versión 16.2 de CBP este error esta corregido. 

![screenshot_2](https://cloud.githubusercontent.com/assets/18584168/15796291/3dba630a-29c5-11e6-8be9-58839341edda.png)

**Comment by MaviDavsa** [comment]
Solucionado!
