### ISSUE TITLE
LPW-Send to contact-Error al enviar BTC

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#401]
### Loss Protected Wallet 

-----

##### Reporte de error: 

   *al ingresar para enviar btc, en el monto deja colocar muchos decimales y sale el siguiente error al dar clic en el botón Send. 

![screenshot_47](https://cloud.githubusercontent.com/assets/5313326/15592570/a3f6c79c-236e-11e6-822e-b2bce2946a7e.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by AdryCanonico** [comment]
@nattyco  En la version 6. Se produjo este mensajes deja ingresar gran cantidad de decimales.

![ooops](https://cloud.githubusercontent.com/assets/18584168/15610138/92081c82-23ed-11e6-881a-d0946242d695.png)

**Comment by nattyco** [comment]
@AdryCanonico  @arosiopr se limito la cantidad de caracteres en la version 7 verificar

**Comment by arosiopr** [comment]
@nattyco ok

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 7 se corrigió el error.
Seria bueno una cantidad mayor de decimales para el usuario.

![dec](https://cloud.githubusercontent.com/assets/18584168/15649201/9f597bda-2639-11e6-8be1-7af419f4ed93.png)
