### ISSUE TITLE
LPW-Send to contact- Decimales en el monto

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#402]
### Loss Protected Wallet 

-----

##### Reporte de error: 

   *Al ingresar a enviar btc deja ingresar varios decimales.

![screenshot_49](https://cloud.githubusercontent.com/assets/5313326/15592886/3281b3da-2371-11e6-9d94-0cff40a83d58.png)

pero cuando voy a Transactions SENT regalo4 que es el que acabo de enviar lo recorta a 4 decimales. Si el máximo de decimales es 4, no debería dejar ingresar mas de 4 al momento de realizar el envio.

![screenshot_50](https://cloud.githubusercontent.com/assets/5313326/15592890/3c03cace-2371-11e6-8cfc-332a2495fc7f.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@MaviDavsa  @arosiopr  vamos a reveer el formateo de los nros, el tema es que las transacciones en btc pueden tener muchos decimales, pero para poder mostrarlos mejor en las pantallas los redondeamos en 4

**Comment by MaviDavsa** [comment]
@nattyco Perfecto! En cual versión?

**Comment by nattyco** [comment]
@MaviDavsa @arosiopr  en la version 7 le puse que formatee hasta 8 decimales

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa E la versión 7 solo salen 4 decimales. Se corrigió el error.Pero considero que los decimales deberían de ser mayores. 

![dec](https://cloud.githubusercontent.com/assets/18584168/15649692/369bc90a-263d-11e6-9c2c-75a6f2673c7f.png)

**Comment by nattyco** [comment]
@AdryCanonico  si los decimales van a ser 8 ya lo cambie para la proxima version

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 30-05-16
Nexus 4 5.0.0 API 21
320 dpi
ocurre lo mismo, deja colocar 8 decimales después de la coma al enviarle un send a un contacto, luegoal ir a  Transactions lo que envie se registraron solo 4 decimales.
![caso 402](https://cloud.githubusercontent.com/assets/17283358/15660254/8c6c7c92-26a3-11e6-87d2-fe34110a4ea6.png)

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la versión 10 se ven los 8 decimales en la transacción.

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 01-06-16
Caso 402
Nexus 4 5.0.0 API 21 320 dpi
Deja colocar 8 decimales después de la coma al enviarle un send a un contacto y  luego al ir a Transactions sale lo mismo 8
![caso 402](https://cloud.githubusercontent.com/assets/17283358/15714545/beb13ec6-27e4-11e6-97bd-3975aa29b66b.png)
 decimales.

**Comment by IsbetVR** [comment]
@nattyco @MaviDavsa 

En la v10 de LPW permite introducir 8 decimales y en las transacciones también muestra los 8 decimales. 

![screenshot_55](https://cloud.githubusercontent.com/assets/19142276/15714952/a8667162-27ea-11e6-9045-6714f276ac88.jpg)


![screenshot_56](https://cloud.githubusercontent.com/assets/19142276/15714956/ab565a7c-27ea-11e6-96d4-04253fc09b18.jpg)


Probado en:
HTX One X
Versión: 4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15714967/b392b050-27ea-11e6-970b-4f95e5bddcb6.jpg)

**Comment by MaviDavsa** [comment]
Solucionado entonces!
