### ISSUE TITLE
LPW-Send to contact - Nombre contacto cortado

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#403]
##### Reporte de error: 

   *Cuando escribo el nombre del contacto lo muestra cortado. Ver figura adjunta
![issue4](https://cloud.githubusercontent.com/assets/5313324/15593598/adb82f1a-2377-11e6-98b2-dd6228b74f11.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo: nexus 5
* Version de Android: 4.4

**Comment by sanro14** [comment]
@nattyco

**Comment by nattyco** [comment]
@sanro14  @MaviDavsa  verificar en la version 8 de la apk

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 403
Nexus 4 5.0.0 API 21
320 dpi
Escribe todo el nombre completo.

![caso 403](https://cloud.githubusercontent.com/assets/17283358/15660483/efaa7252-26a6-11e6-8ae2-394ace8c26a2.png)

**Comment by MaviDavsa** [comment]
Solucionado!
