### ISSUE TITLE
LPW- alertas del send to contact

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#404]
##### Reporte de error: 

   *Cuando voy a enviar una cantidad mayor a la que tengo en mi billetera, muestra el alert con el mensaje de fondos insuficientes pero de igual forma muestra un sending. Ver figura Adjunta
![issue5](https://cloud.githubusercontent.com/assets/5313324/15593665/3abb2afc-2378-11e6-87ce-010a3b95cab0.png)
![issue5-1](https://cloud.githubusercontent.com/assets/5313324/15593664/3a807056-2378-11e6-804d-a8bb07f101b6.png)

@nattyco 
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: nexus 5
* Version de Android: 4.4

**Comment by nattyco** [comment]
@sanro14 Se hiso el Send de todas formas? o solo te muestra el mensaje? Te mostro un popup con un mensaje de Alerta de Perdida?

**Comment by nattyco** [comment]
@sanro14 corregido en la version 7 verificar

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco E la versión 7 se corrigió el error pero el fondo del texto del mensaje es diferente en ambos emuladores


![6](https://cloud.githubusercontent.com/assets/18584168/15649750/ad2c79de-263d-11e6-9d57-ba9a04b61b90.png)

**Comment by MaviDavsa** [comment]
SOLUCIONADO ESTE!
