### ISSUE TITLE
CRYPTO BROKER- ERROR AL TRATAR DE INGRESAR

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#405]
### Template issue error report

Nombre pantalla: CRIPTO BROKER

CRIPTO BROKER

##### Reporte de error: 

   *LUEGO DE CREAR EL PROFILE DE BROKERS QUE SE TRATA DE INGRESAR A LA CRIPTO BROKER APARECE DE INMEDIATO "RECOVERING FROM SYSTEM ERROR" EN LA PANTALLA Y LUEGO RETORNA LA APLICACIÓN AL INICIO, TAL Y COMO SE SEÑALA A CONTINUACIÓN:
   
![image](https://cloud.githubusercontent.com/assets/18740418/15594644/42f8f2ea-2381-11e6-89f6-f6647b77eceb.png)

![image](https://cloud.githubusercontent.com/assets/18740418/15594661/654a8958-2381-11e6-9c48-75542ed0ba9f.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: GENYMOTION
* Modelo: EMULADOR

![image](https://cloud.githubusercontent.com/assets/18740418/15594671/7bcd7d0c-2381-11e6-9730-56535a75f452.png)

**Comment by camilavaleria** [comment]
@MaviDavsa

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by nelsonalfo** [comment]
Es un problema de la plataforma que afecta a todas las wallets y subapss, es algo medio aleatorio ya que no sucede todo el tiempo y no siempre sobre la misma wallet o subapp. De igual forma ya se informó al encargado de esto sobre el error y se esta trabajando para resolverlo

**Comment by MaviDavsa** [comment]
Perfecto! @nelsonalfo Vamos a ver que tal se puede manejar hoy en la nueva versión y lo cerramos! :D

**Comment by IsbetVR** [comment]
Sucede lo mismo en la versión 14, cuando intento entrar a "Broker Wallet" no deja. Muestra inmediatamente el "Welcome to Fermat"

![screenshot_15](https://cloud.githubusercontent.com/assets/19142276/15611691/90ab6ba8-23f9-11e6-8564-13b00523d062.jpg)

![screenshot_16](https://cloud.githubusercontent.com/assets/19142276/15611696/943c6ace-23f9-11e6-99cf-0f744764d681.jpg)

![nexus 9](https://cloud.githubusercontent.com/assets/19142276/15611724/b4d582de-23f9-11e6-902e-3bcc5cc475a3.jpg)

**Comment by nelsonalfo** [comment]
Se puede cerrar este Issue?

**Comment by AdryCanonico** [comment]
@nelsonalfo Sucede lo mismo en la versión 16.4 

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15940605/8ef84540-2e46-11e6-9e00-9fe7788d492d.png)

**Comment by nelsonalfo** [comment]
por favor verifiquen si se puede cerrar este Issue

**Comment by AdryCanonico** [comment]
@nelsonalfo en la Versión 16.5 sigue persistiendo este error

**Comment by camilavaleria** [comment]
este error no sucedió mas!!
