### ISSUE TITLE
Chat - Mostrar ventana emergente

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#406]
### Chat

--- 

##### Reporte de error: 

   * Seria importante que el momento en que estemos chateando con un contacto, apareciera un mensaje emergente avisando que tenemos otro  y no tener que devolver la pantalla para revisar los otros mensajes recibidos.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Emulador
* Version de Android:

![android 5 1](https://cloud.githubusercontent.com/assets/19353722/15594695/d2d9590e-2381-11e6-9172-61201555dd93.png)

**Comment by marielis-urbina** [comment]
@franklinmarcano1970

**Comment by MaviDavsa** [comment]
@marielis-urbina Explica un poco mejor este caso! :D

**Comment by franklinmarcano1970** [comment]
@marielis-urbina Entiendo como una notificacion que no esta implementado en esta version, ya eso lo hemos discutido que sera una mejora para sigueintes versiones!!!

**Comment by marielis-urbina** [comment]
Ok, gracias @franklinmarcano1970

**Comment by marielis-urbina** [comment]
En la versión 19.5, ya aparece el mensaje emergente que tienes otra conexión, a un que al darle click, te direcciona a las community y no al P2p Chat.

**Comment by wendyduran90** [comment]
En la versión 19.5 , aparece la notificación de chat y de nueva solicitud de chat en mi teléfono móvil; después de de revisar estas notificaciones el símbolo de notificación permanece ahí ,cuando en realidad debería eliminarse. @RoyGF
Dispositivo 
Marca: BLU
Modelo: life one 2015
Versión de android: 4.4.4

**Comment by RubenSem** [comment]
Esta recomendación no esta implementada aun en esta versión de cbp 20.1, por favor al estar implementada si podrían avisarnos mucho mejor. @franklinmarcano1970 saludos.

**Comment by dorzar1989** [comment]
En la Version 20.7 de la CBP esta implementada una Notificación cada vez que te escriben, pero el detalle es que a veces Llega y a veces no, y cuando llega se da Click sobre ella y no lleva hacia donde debería, normalmente lleva a las Communities, ya sean de Broker, Customer, Wallet o Chat. Pero pues eso ya es otro caso.

- Fecha 18/07/2016

**Comment by LilianFlores** [comment]
En la versión 20.8 de la CBP, se muestra una notificación al tener un nuevo mensaje. Sin embargo, debería desaparecer cuando se ingresa al chat indiferentemente si se ingresa o no por la notificación, pero solo desaparece si se presiona sobre ella. 

- Fecha: 20|07|2016

**Comment by hcampos1984** [comment]
en la version 21.1 se visualizo la ventana notificacion emergente donde se observa que llego un nuevo mensaje pero cuando estas dentro de alguna aplicacion, sea broker, customer, chat o wallet de resto no logras verla, adicionalmente no desaparece sie estas dentro del chat 

![image](https://cloud.githubusercontent.com/assets/20233469/17266631/712e8db8-55c8-11e6-9ac2-cfd10798189a.png)

![image](https://cloud.githubusercontent.com/assets/20233469/17266625/633b1ad2-55c8-11e6-8178-c982950d5637.png)

![image](https://cloud.githubusercontent.com/assets/20233469/17266634/9f1408ca-55c8-11e6-82ed-680715d2aa46.png)

**Comment by marielis-urbina** [comment]
En la versión 22.0 de CBP, este error no sucede en mi emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17699889/658a03a8-6391-11e6-8f19-0b44edbc2c35.png)

**Comment by camilavaleria** [comment]
En la versión 22.0 de la CBP, se muestra una notificación al tener un nuevo mensaje de chat. Sin embargo, al presionar para entrar se queda estatica, no lleva al chat correspondiente, ni a otro lado, tampoco desaparece,

![image](https://cloud.githubusercontent.com/assets/18740418/17701546/40be9ff0-6398-11e6-959c-823fd85f4912.png)

emulador de prueba:

![image](https://cloud.githubusercontent.com/assets/18740418/17701574/5b9a3b04-6398-11e6-83e6-157e24ef47dc.png)

**Comment by camilavaleria** [comment]
En la version 22.3, este error no sucede en mi emulador, al presionar  la ventana de notification me envia al destino correspondiente: chat, browser, etc..

EMULADOR DE PRUEBA:

![image](https://cloud.githubusercontent.com/assets/18740418/17822543/b91915b8-6625-11e6-8b0f-54878c3b057d.png)
