### ISSUE TITLE
App_ error de cierre inesperado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#407]
#### Error de cierre inesperado

Cuando estoy en la aplicacion y salgo de ella para revisar cualquier cosa en mi telefono, dejando la aplicacion en segundo plano, al volver a ingresar a la aplicacion esta da un cierre inesperado y se reinicia automaticamente. 

![screenshot_2016-05-26-18-13-56](https://cloud.githubusercontent.com/assets/17274154/15608988/1dfae17c-23e7-11e6-90ca-deb4d6def36f.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung glaxy
* Modelo: s4 mini
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
@furszy

**Comment by maydiamc** [comment]
problema solucionado @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
Perfecto!

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la version 15 cuando minimizo la aplicación de fermat en el teléfono y utilizo otra aplicación. Ejemplo Whatsapp, galeria... vuelvo a entrar la aplicación de fermat se reinicia. 


![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15912570/f90be9da-2d9e-11e6-8bf1-9014c560077f.png)

**Comment by maydiamc** [comment]
en la version 17 de la apk, al haer la prueba la aplicacion se quedo colgada, no salio el erro pero quedo colagada y solo se veia el fondo de pantalla, fue necesario reiniciarla para que funcionara de nuevo @nattyco 
![screenshot_2016-06-13-17-59-12](https://cloud.githubusercontent.com/assets/17274154/16024671/e74bb148-318c-11e6-81e8-ab4e2229c54a.png)

![screenshot_2016-06-07-11-03-21](https://cloud.githubusercontent.com/assets/17274154/16024668/e1922138-318c-11e6-908f-74afe50ee2da.png)

**Comment by maydiamc** [comment]
solucionado en la version 19.4 de CBP
