### ISSUE TITLE
LPW_boton de comunity no funciona

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#408]
#### Nombre pantalla

-----
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo
- [x] add fermat user

##### Reporte de error: 

   *el boton que lleva a la comunity, en la pantalla de agregar fermat user, no funciona y no permite ingresar a la crypto wallet user.

NOTA: en la imagen se muestra el boton que no esta funcionando
   
![screenshot_2016-05-26-18-08-53](https://cloud.githubusercontent.com/assets/17274154/15610088/4ddeb08e-23ed-11e6-934b-bb778181cad1.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
version 6 de apk @nattyco @MaviDavsa

**Comment by nattyco** [comment]
@maydiamc  a que te referis con que no funciona, no hace la accion el boton? lo estoy probando en varias versiones  y me lleva al community.

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco @maydiamc En la versión 7 hace la función pero con el nexus S y el Nexus 5.  Es un caso propio del teléfono de @maydiamc.

**Comment by maydiamc** [comment]
solucionado el error en la version 8 @nattyco @sanro14

**Comment by maydiamc** [comment]
@MaviDavsa reabrir el caso porque se esta presentando en la version 11

**Comment by nattyco** [comment]
@MaviDavsa  @maydiamc  en la version que tenes parece que no funciona pero es porque tarda en cambiar de aplicacion, no es un problema de la wallet

**Comment by maydiamc** [comment]
@nattyco explicate mejor, no entendi.!

**Comment by nattyco** [comment]
Tarda en ejecutar la accion, por un tema de la plataforma de aplicaciones

**Comment by nattyco** [comment]
@MaviDavsa  verifiquen esto en otras versiones y dispositivos

**Comment by maydiamc** [comment]
es que no esta tardando, simplemente no funciona.! no se si en los de las chicas suceda, pero a mi me presenta el problema nuevamente en esta version

**Comment by nattyco** [comment]
No se cambie nada ahi, no es que en una version funciono y en la otra no

**Comment by maydiamc** [comment]
ahh ok ok.! entendido @nattyco

**Comment by AdryCanonico** [comment]
@nattyco en la versión 11 al momento de querer usar el boton de la community da error y me saca. Esto sucede en ambos emuladores.

![error boton community](https://cloud.githubusercontent.com/assets/18584168/15747199/6acaceb6-28a3-11e6-98c4-641298abbd11.png)


dispositivos:

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15747295/e7647ee0-28a3-11e6-80b1-7237429f6403.png)

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15747296/e76882ec-28a3-11e6-9ab4-c3ab2a52c054.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba Caso 408 LPW V11
Nexus 4 5.0.0 Api 21 320dpi
El boton que lleva a la comunity,desde la pantalla de los contactos para agregar fermat user,funciona   permite ingresar a la crypto wallet user en este emulador.
![caso 408](https://cloud.githubusercontent.com/assets/17283358/15757328/e48ef09e-28ce-11e6-8a2e-8dabda610f10.png)


NOTA: en la imagen se muestra el boton que no esta funcionando

**Comment by maydiamc** [comment]
en la version 14 se soluciono el problema @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!

**Comment by AdryCanonico** [comment]
@maydiamc @nattyco En la version 15 el botón para acceder a la community pierde la función,
Esto me esta ocurriendo en mi teléfono. Por favor reabrir el caso.

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15895742/be98dbc0-2d56-11e6-85a1-a296fcdfd7a7.png)

**Comment by maydiamc** [comment]
en la version 15.2 el error sucede en repetidas ocasiones, aunque a veces si me deja entrar a la community @nattyco 

Samsung Galxy 
mini s4
4.4.2

**Comment by AdryCanonico** [comment]
@nattyco en la versión 15.2 el error sucede en mi teléfono físico,  no todo el tiempo y se cierra la aplicación

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15940653/cec32a6e-2e46-11e6-89e9-70aaa6e3aa11.png)
.

**Comment by AdryCanonico** [comment]
@maydiamc @nattyco En la version 16.2 el botón para acceder a la community pierde la función en algunas ocaciones y para que agarre la funcion hay que abrir y cerrar la LPW.
Esto me esta ocurriendo en mi teléfono. Por favor reabrir el caso.


![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15969211/d8068438-2ef8-11e6-8585-1c964c15b8e1.png)

**Comment by maydiamc** [comment]
en la version 17 de la apk se soluciono este problema @nattyco 
![screenshot_2016-06-07-11-03-21](https://cloud.githubusercontent.com/assets/17274154/16024046/7effc51e-3189-11e6-967d-c219ce44c22e.png)

**Comment by MaviDavsa** [comment]
Solucionado!
