### ISSUE TITLE
LPW_ error en pantalla de add fermat user

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#409]
#### Nombre pantalla

-----
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo
- [x] Pantalla de add fermat user

##### Reporte de error: 

 Cada vez que ingreso a la pantalla de agregar contacto fermat, esta no me muestra los contactos que ya tengo agregados, sino que se muestra en blanco y me aparece un error que automaticamente me saca de la LPW 
   
   ![screenshot_2016-05-27-10-13-17](https://cloud.githubusercontent.com/assets/17274154/15610712/77c8a410-23f0-11e6-8d89-6b65151201b0.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
version 6 de apk @nattyco @MaviDavsa

**Comment by nattyco** [comment]
@maydiamc @MaviDavsa verificar en la version 8 de la apk como se comporta

**Comment by maydiamc** [comment]
se corrigio el problema en la version 8 @MaviDavsa @nattyco
