### ISSUE TITLE
Communities - No permite entrar, muestra pantalla de bienvenida "Welcome to Fermat"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#410]
### Pantalla principal de la aplicación

-----

##### Reporte de error: 

   *Estando en la pantalla principal de la aplicación (Pantalla 1), intento entrar a "communities" y me muestra "Recovering from system error" e inmediantamente me vuelve a salir la pantalla de bienvenida "Welcome to Fermat" (Pantalla 2). Salgo de la aplicación, la vuelvo a iniciar y continúa pasando. Debo cerrar el emulador completamente y volverlo a iniciar para que pueda entrar a "Communities" sin problemas.

------
#### Pantalla 1

![screenshot_12](https://cloud.githubusercontent.com/assets/19142276/15611292/c1759eea-23f7-11e6-8ffd-a2dcaf895f4c.jpg)

#### Pantalla 2

![screenshot_14](https://cloud.githubusercontent.com/assets/19142276/15611306/ccf0b0de-23f7-11e6-8d1f-068c885e3800.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 9, 320 dpi
* Version de Android: 5.1.0

![nexus 9](https://cloud.githubusercontent.com/assets/19142276/15611376/1090e07a-23f8-11e6-84d8-bca72875b2cd.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by abicelis** [comment]
Si @IsbetVR , como dice @nelsonalfo en https://github.com/Fermat-ORG/beta-testing-program/issues/405#issuecomment-222052410. Estos errores son lamentablemente de la plataforma y fuera de CBP :/

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by Gabymorillo** [comment]
Al tratar de entrar a la aplicación se queda colgada con el logo de fermat, al cerrar el emulador y abrir de nuevo despues de un largo rato cargando, la pantalla se queda en negro o blanco.

![capture-20160530-201359](https://cloud.githubusercontent.com/assets/17262077/15690949/e69f415c-274f-11e6-9e02-c109ff116b32.png)
![capture-20160530-194716](https://cloud.githubusercontent.com/assets/17262077/15690954/e90ce502-274f-11e6-8ce5-82a8afe99475.png)
![capture-20160530-202239](https://cloud.githubusercontent.com/assets/17262077/15690959/ec4cbff8-274f-11e6-8378-9b61bf9c5c48.png)


Dispositivo de prueba:
Google Nexus 4
Versión de android: 5.1.0

**Comment by AdryCanonico** [comment]
@IsbetVR este error ya no sucede en la version 18.4.
