### ISSUE TITLE
Community- LPW- Cripto Wallet user no aparecen 

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#411]
#### Nombre pantalla

Cripto Wallet User

##### Reporte de error: 

   *Estando en la community en la pantalla del CRIPTO Wallet User, los contactos no aparecieron
![no aparecen los cripto wallet user 1](https://cloud.githubusercontent.com/assets/17283358/15611530/81b5fb5e-23f4-11e6-9f9d-e480275eaec2.png)

Salgo de la apk y no aparecen, ya tengo agregada a varios contactos

   
------

#### Dispositivo desde donde se realizo la prueba

![nexus 4- 5 0 0](https://cloud.githubusercontent.com/assets/17283358/15611767/c06687fa-23f5-11e6-9e0e-4a5f9a86a2fa.png)

**Comment by AdryCanonico** [comment]
@nattyco El mismo error pasa en la versión 6, con el Nexus S aunque no se ven los contactos llegan las notificaciones de estos.

![no se ven los contactos](https://cloud.githubusercontent.com/assets/18584168/15612775/f2e630b4-23f9-11e6-98e9-432290ee8fee.png)


![nexus s](https://cloud.githubusercontent.com/assets/18584168/15612777/f67ecab0-23f9-11e6-8dea-674394c3481f.png)

**Comment by nattyco** [comment]
@yolandayancel verificar nuevamente en la version 7 de la apk

**Comment by yolandayancel** [comment]
@nattyco 
Buenas tardes
Prueba 30-05-2016
Caso 411
Resuelto: Los cryto Wallet  user aparecen

![resuelto caso 411](https://cloud.githubusercontent.com/assets/17283358/15658767/7843fe16-268a-11e6-83e1-b76db7fb16b0.png)

**Comment by maydiamc** [comment]
en la version 11 se presenta este problema, reabrir el caso @MaviDavsa @nattyco 
samsung galaxy mini s4, 4.4.2
![screenshot_2016-06-01-19-37-00](https://cloud.githubusercontent.com/assets/17274154/15730264/f02a67fc-2834-11e6-9640-6020e001d1f3.png)

**Comment by danielaporras** [comment]
En la versión 14 de LPW al entrar en la community en la pantalla del CRIPTO Wallet User, sigue este mismo problema.
@MaviDavsa  @nattyco 

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.4.4

![screenshot_8](https://cloud.githubusercontent.com/assets/19656830/15860832/6e9fb73c-2c94-11e6-9bbf-46285b9200bc.png)

**Comment by yolandayancel** [comment]
@nattyco
Buenas tardes
Prueba 07-06-2016
Caso 411
Los cryto Wallet user no aparecen a pesar de que los veia en un momento pero al entrar a contactos y volver a la Cripto Wallet user desaparecieron.
![caso 411](https://cloud.githubusercontent.com/assets/17283358/15860988/008ee406-2c95-11e6-96a0-caf6dd7729db.png)
Nexus 4  5.0.0 Api 21
320dpi

**Comment by marielis-urbina** [comment]
En la versión 14 de la LPW persiste el error en la community en la pantalla del CRIPTO Wallet User, los contactos no aparecen.

![cwu](https://cloud.githubusercontent.com/assets/19353722/15877046/1e14dbc0-2cdb-11e6-8138-a6f82857a392.png)

**Dispositivo desde donde se realizo la prueba**

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/15877073/4e2456b0-2cdb-11e6-947f-bfab8849c291.png)

**Comment by maydiamc** [comment]
@nattyco 
en la version 15 de la lpw, no se muestran los contactos de la community, sino que se muestra un error, esto sucede  la mayoria de las veces que se accesa a la community, pero en algunas ocasiones si muestra los contactos por unos minutos, pero luego al entrar al contacto para enviar la notificacion de agregar, al retroceder a la community, vuelve a suceder el problema y ya no se muestra ningun usuario sino que aparece de nuevo el error

Samsung Galaxy
Mini S4
4.4.2

![screenshot_2016-06-08-08-51-06](https://cloud.githubusercontent.com/assets/17274154/15896265/4bd127de-2d59-11e6-8fcf-20436f8c5a69.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 08-06-2016
Caso 411 LPW V15
Nexus 4 5.0.0 320dpi
Al ingresar a la community, no aparecen los cripto wallet user.
![caso 411](https://cloud.githubusercontent.com/assets/17283358/15897442/496cfa04-2d5e-11e6-8022-9c73b4302483.png)

**Comment by RubenSem** [comment]
En la version 15 LPW, me pasa que no muestra los contactos y me muestra un error.
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/15897656/2abdb00c-2d5f-11e6-9171-518ad6057e1f.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/19676223/15897657/2ac46b40-2d5f-11e6-9711-0105ccf7f0de.jpg)

Especificaciones:
![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/15897680/3ab49b56-2d5f-11e6-8fef-e73a444c85ab.jpg)

**Comment by Gabymorillo** [comment]
Caso similar, en la versión 15 al entrar a la community no aparecen los contactos, a pesar de refrescar la pantalla varias veces y salir y entrar de nuevo persiste el error. 


![2ac46b40-2d5f-11e6-9711-0105ccf7f0de](https://cloud.githubusercontent.com/assets/17262077/15898379/ea9a8cc2-2d61-11e6-9285-098bee7a2432.jpg)


Google Nexus 4

Versión: 5.1.0

**Comment by danielaporras** [comment]
En la version 15 de LPW persiste este error.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15898427/19f17d32-2d62-11e6-856d-681ea98f2eb5.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.4.4
 
@MaviDavsa

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 08-06-16
Caso 411 LPW V 15.1
Nexus 4 y Nexus 5  5.0.0
Al agregar un contacto se queda cargando y hay que cerrar el emulador.
![se queda cargando despues de hacer connection con un user](https://cloud.githubusercontent.com/assets/17283358/15914395/602dfcce-2daa-11e6-91cb-13f711f7f29f.png)

**Comment by nattyco** [comment]
@MaviDavsa  verificar esto en la version 17 de la apk y comentar como se comporta

**Comment by MaviDavsa** [comment]
@yolandayancel Bella vamos a verificar esto! :D

**Comment by AdryCanonico** [comment]
@nattyco En la version 17 la community se ven los contactos aunque tardo un poco en cargar. Solo había problemas al momento de ir de LPW a la community.

**Comment by maydiamc** [comment]
en mi dispositivo esto se soluciono con la version17 @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025221/e0c9a5e8-318f-11e6-8fb8-f20a22ff7ce1.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @yolandayancel En la versión 18.3 CBP ya no se ve el error

**Comment by yolandayancel** [comment]
Prueba 27-06-16
Caso 411 LPW- (CBP V 18.3)
Nexus 4 y 5 5.0.0
En los emuladores ya no pasa el error ( Se ven los user)
![caso 411](https://cloud.githubusercontent.com/assets/17283358/16381475/9e62a300-3c46-11e6-9084-0727ca78c843.png)
[logcatCaso 411 Nexus 4.txt](https://github.com/Fermat-ORG/beta-testing-program/files/334959/logcatCaso.411.Nexus.4.txt)
[logcatcaso 411 Nexus 5.txt](https://github.com/Fermat-ORG/beta-testing-program/files/334961/logcatcaso.411.Nexus.5.txt)
