### ISSUE TITLE
LPW - BOTONES SETTINGS DIFERENTES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#412]
### LPW 

-----

##### Reporte de error: 

   *Los botones se ven diferente en el Nexus S. 

![no se ve exchange](https://cloud.githubusercontent.com/assets/18584168/15611881/3a33fedc-23f6-11e6-8d5c-23ce7f5dec39.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador derecho: 240 dpi

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15611694/610d1788-23f5-11e6-8516-35fc2db2dc86.png)

Emulador izquierdo:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15611702/6ba661f4-23f5-11e6-9f29-ac65ca7d777a.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico esto ya depende de la version de android

**Comment by AdryCanonico** [comment]
@nattyco  Seria bueno en este caso un botón mas amigable que maneje android  y sino algo mas pequeño. Ya que se en muy exagerados en la pantalla al momento de visualizarlos.
