### ISSUE TITLE
LPW - EXCHANGE RATE PROVIDERS  NO APARECE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#413]
### LPW

-----

##### Reporte de error: 

   *En el settings Nexus S se ve EXCHANGE RATE PROVIDERS pero en el nexus 5 no.

![no se ve exchange](https://cloud.githubusercontent.com/assets/18584168/15612138/63df92c2-23f7-11e6-89d4-cb8cbf5eaba2.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador derecho: 240 dpi

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15611694/610d1788-23f5-11e6-8516-35fc2db2dc86.png)

Emulador izquierdo:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15611702/6ba661f4-23f5-11e6-9f29-ac65ca7d777a.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  verificar en la version  de la apk

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión  7 de LPW se corrigió el error. Se puede cerrar el caso.

![1](https://cloud.githubusercontent.com/assets/18584168/15648642/a1bc8c18-2635-11e6-90d5-cb19cd033aa9.png)
