### ISSUE TITLE
LPW - Fondo de diferente color

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#414]
### LPW

-----

##### Reporte de error: 

   *El fondo del menu se ve diferente en el Nexus S. El gris es mas oscuro.

![no se ve exchange](https://cloud.githubusercontent.com/assets/18584168/15611630/1695100c-23f5-11e6-9a9b-4d4915953d2f.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

Emulador derecho: 240 dpi

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15611694/610d1788-23f5-11e6-8516-35fc2db2dc86.png)

Emulador izquierdo:

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15611702/6ba661f4-23f5-11e6-9f29-ac65ca7d777a.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la versión 7 el fondo se ve aun mas oscuro.

![1](https://cloud.githubusercontent.com/assets/18584168/15648664/d4bd0980-2635-11e6-9f8a-789f43901384.png)

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  se igualo el color de la pantalla a blanco. Verificar

**Comment by MaviDavsa** [comment]
@nattyco En una nueva apk? En la V7?

**Comment by nattyco** [comment]
@MaviDavsa  version 8

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la version 8 se coorigio el fondo. Se puede cerrar el caso.

![fondo](https://cloud.githubusercontent.com/assets/18584168/15674041/639e3dc6-2704-11e6-9a0a-be5aab69e050.png)
