### ISSUE TITLE
LPW - no llegan btc

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#415]
### LPW

-----

##### Reporte de error: 

   *Pedi BTC desde las 8:30 am y a las 11:30 am no habian llegado. Esto solo pasa en el Nexus S.

![btc](https://cloud.githubusercontent.com/assets/18584168/15612669/8f43843a-23f9-11e6-84c5-e60907b6edb9.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15612685/a15628da-23f9-11e6-86e2-d8536a8aa114.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  pediste a la regtest? puede que no funcione la red, eso no depende de la LPW

**Comment by AdryCanonico** [comment]
Si @nattyco lo pedí pero no me llegaba ninguna transacción a ese nexus S. Estaba trabajando paralelo con otro y llego todo super bien y rápido....Solo es para que lo tomen en cuenta con esta versión ya que tiene muchos errores con el 4.1.1.
