### ISSUE TITLE
LPW - NO TIENE FUNCION EL BOTON DE FERMAT USER

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#417]
### LPW

-----

##### Reporte de error: 

   *Cuando intento utilizar el boton, este no tiene funcion o se me cierra la aplicacion. Esto solo pasa con el Nexus S.

![botones no sirven](https://cloud.githubusercontent.com/assets/18584168/15612920/9b221c48-23fa-11e6-893f-858a531093f8.png)

   
![boton no sirve](https://cloud.githubusercontent.com/assets/18584168/15612926/a057a6e2-23fa-11e6-9e9d-229564dc74ca.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15612938/b07ceafa-23fa-11e6-95a2-ed640daf64ba.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  verificar en la version 8 de la apk

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la versión 8 se corrigió. Se puede cerrar el caso.
