### ISSUE TITLE
LPW-Transactions Received-Error en note

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#418]
### Loss Protected Wallet 

-----

##### Reporte de error: 

   *Al ingresar en transactions received se puede ver que en el campo note sale la palabra "null" creo que eso no se debería salir, en dado caso que la persona no llene ese campo debería simplemente salir vacio.

*En el segundo note sale demasiada información, eso se debería limitar a cierta cantidad máxima de caracteres.

![screenshot_51](https://cloud.githubusercontent.com/assets/5313326/15621141/a2bf203a-2428-11e6-8340-bf80bd43d871.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@arosiopr se limito la cantidad de caracteres verificar en la version 7 de la apk

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 418
Nexus 4 5.0.0 API 21
320dpi

En el note se se limitó la cantidad de caracteres a 26
![caso 418](https://cloud.githubusercontent.com/assets/17283358/15660417/d4fe94de-26a5-11e6-9913-c8980537d00c.png)

**Comment by MaviDavsa** [comment]
Solucionado!
