### ISSUE TITLE
DAP - Banner muy estirado al entrar a "Profiles"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#419]
#### Profiles

------

##### Reporte de error: 

   *El banner del wizzar se ve muy estirado cuando entro a "Profiles" para crear el usuario.
   
------

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/15621925/734d6172-2432-11e6-88d5-c894214b69e1.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 9 , 320 dpi
* Version de Android: 5.1.0
![nexus 9](https://cloud.githubusercontent.com/assets/19142276/15621933/840f4458-2432-11e6-82c5-d2e7f5569cfe.jpg)

**Comment by IsbetVR** [comment]
@sanro14 @MaviDavsa

**Comment by IsbetVR** [comment]
Sucede lo mismo cuando entro a "Communities", el banner está muy estirado

![screenshot_18](https://cloud.githubusercontent.com/assets/19142276/15622005/28b95994-2433-11e6-9a50-ff2ea25f62c8.jpg)

**Comment by sanro14** [comment]
@nindriago

**Comment by nindriago** [comment]
aca no puedo ayudar en nada, esto simplemente pasa porque el Emulador es un Nexus 9 y las dimensiones del equipo son muy grandes...

**Comment by sanro14** [comment]
@nindriago y no debería ser una aplicación responsive? y que en todos los dispositivos se vea igual?? te pongo el ejemplo de facebook, o twitter o simplemente instagram...  si mi tlf es mas grande las dimensiones yo voy a ver las imágenes o los iconos mal y distorcionados??? no creo.. tal vez no sea de DAP pero si es un error gráfico que se debería arreglar.

**Comment by nindriago** [comment]
correcto no es un error grafico de DAP, es algo que sucede en general en todo Fermat, revisen otros APK y seguramente veran esta misma pantalla de community de la misma forma

**Comment by IsbetVR** [comment]
Exacto! no debería tener nada que ver con el dispositivo, debería ser "agradable" visualmente para cualquier usuario. No limitarlo a unos dispositivos en específicos. En otras aplicaciones ha sucedido lo mismo y lo han solucionado.

**Comment by MaviDavsa** [comment]
@nindriago  Es algo por lo que tu te tienes que preocupar por lo que el Equipo de Diseño cambie... Lo mismo pasaba con la APK de la CBP y ellos se preocuparon por arreglarlo! Si ellos pudieron! TODOS pueden... :)... La idea es que sea perfecta en cuanto a diseño y en cuanto a funcionalidad!

**Comment by nindriago** [comment]
Revisar en nueva version de APK

**Comment by AdryCanonico** [comment]
@MaviDavsa @nindriago En la version 3 se puede ver el banner corregido. Esta prueba la hice en el nexus 7. 

@IsbetVR No se si en el tuyo se arreglo.

![banner user](https://cloud.githubusercontent.com/assets/18584168/15676522/53fdea40-2710-11e6-97a9-fcd53a036b6d.png)
