### ISSUE TITLE
DAP-Error cuando cambio la imagen del asset

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#422]
##### Reporte de error: 

   * Cuando intento cambiar la imagen del issue buscando y seleccionándola de la galería, me saca de la aplicación mostrando el error de la imagen adjunta. (probado 3 veces y genera el mismo resultado)
![issue-2](https://cloud.githubusercontent.com/assets/5313324/15623261/7eb09d00-243b-11e6-8e54-1f3c64f093b2.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 5
* Version de Android: 5.0

**Comment by sanro14** [comment]
@nindriago

**Comment by nindriago** [comment]
mmmm imagen donde? haciendo que??? mas detalles por favor

**Comment by sanro14** [comment]
@nindriago cuando le voy a asignar una imagen al cupon.. ahora lo reviso en la versión nueva para ver si da el mismo error

**Comment by nindriago** [comment]
Revisar en nueva version de APK

**Comment by AdryCanonico** [comment]
@nindriago @MaviDavsa En la versión 3 se puede cargar la imagen de gallery sin problemas. 

Dispositivo Nexus 7
