### ISSUE TITLE
Community Error al cambiar el perfil

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#424]
##### 

- **Reporte de error:**

Al comenzar a utilizar la aplicacion como figura Reddin Poin, entre a la Community sin a ver creado mi perfil y por defecto coloco el predeterminado, al ir a la pantalla aparecia de esta manera

![pantalla reddin poin](https://cloud.githubusercontent.com/assets/19353722/15624253/b659fa24-244c-11e6-970e-ee7b6a850096.png)

Al darme cuenta cree mi nuevo perfil

![perfil actual](https://cloud.githubusercontent.com/assets/19353722/15624261/e972b18a-244c-11e6-9dc4-ace464e9e30d.png)

- Posteriormente, cerré mi simulador porque a pesar de que era el mismo usuario, seguía apareciendo la que por defecto me había dado en la community al cambiar mi perfil , al volver a la pantalla nunca apareció el nuevo perfil,no debería aparecer automáticamente este?

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Android
* Modelo: 5.1
* Version de Android:

![android 5 1](https://cloud.githubusercontent.com/assets/19353722/15624280/9b620378-244d-11e6-89f0-43c4eb369a82.png)

**Comment by marielis-urbina** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nattyco Olvidalo! Error del team! :( lo siento!
