### ISSUE TITLE
LPW - CASILLA PARA EL CHECK NO APARECE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#425]
### LPW

-----

##### Reporte de error: 

   *La casilla para poder ingresa los check he ingresar el contacto de fermat no aparece al menos que se le de click al contacto.

Esto solo pasa en en el Nexus S,

![check](https://cloud.githubusercontent.com/assets/18584168/15648845/e73509ae-2636-11e6-94c2-b2cc2f756d30.png)

![3](https://cloud.githubusercontent.com/assets/18584168/15648942/7eb92aee-2637-11e6-8405-4df0d567b4c7.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15648857/fa872db6-2636-11e6-9425-0bee7d73890d.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@nattyco en la versión 13 no aparece el check en ningún emulador. Quisiera saber si debería aparecer al pulsar el contacto o inmediatamente al ver el contacto para agregarlo?

**Comment by MaviDavsa** [comment]
@nattyco Y si es así como dice @AdryCanonico Deben estructurarlos todos para que en todas las apk esa función sea igual!

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  se corrigio para las versiones mas chicas de android en la version 14 de la apk para que se vea si tener que tocar el registro.

**Comment by marielis-urbina** [comment]
En la versión 14 de la LPW ya aparecen los cuadros para colocar check 

![listo](https://cloud.githubusercontent.com/assets/19353722/15840497/f985e9ba-2c13-11e6-85f2-1c112bee5de2.png)

Dispositivo desde donde se realizo la prueba

Marca:Genymotion
Modelo:Emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/15840523/1f2644b2-2c14-11e6-838c-3049d30f7d37.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version 15 aparecen las casillas para los check. Se puede cerrar el caso.:+1:

![screenshot_2016-06-08-09-19-21](https://cloud.githubusercontent.com/assets/18584168/15897325/dd2a20ce-2d5d-11e6-8167-411199ac906f.png)
