### ISSUE TITLE
LPW - FONDO EN LOS TEXTOS DIFERENTE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#426]
### LPW

-----

##### Reporte de error: 

   *La forma del fondo de los texto en toda la APP es diferente. En el Nexus S es diferente. 

![sed mayor](https://cloud.githubusercontent.com/assets/18584168/15649813/1bb7c124-263e-11e6-884a-d7c0fa7e2dca.png)

![6](https://cloud.githubusercontent.com/assets/18584168/15649814/1bf1a84e-263e-11e6-8848-addcbaca91d1.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15649819/2c34003a-263e-11e6-84c9-bda76144bb2a.png)

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15649820/2c37db9c-263e-11e6-81bf-24df2b97d3f2.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  esto no es un error es por la version de android

**Comment by AdryCanonico** [comment]
@MaviDavsa por favor cerrar el caso
