### ISSUE TITLE
LPW - BOTON BARCODE SCANNER CORTADO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#428]
### LPW 

-----

##### Reporte de error: 

   *No se visualiza el botón completo, esta cortado. Solo pasa en el Nexus S.

![externalcon](https://cloud.githubusercontent.com/assets/18584168/15652834/d6484202-2652-11e6-9af6-a48a7f85df14.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emuador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15652851/ea12beb6-2652-11e6-9ba1-171e2412ab76.png)

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15652852/ea17a67e-2652-11e6-8745-adf5e5a4d94e.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@nattyco en el caso del nexus 7 queda un espacio libre.

![code largo](https://cloud.githubusercontent.com/assets/18584168/15681601/a3bac5f4-2723-11e6-8ace-30bba88faf85.png)


![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15681604/a6af0f7c-2723-11e6-8fc0-8e64bfb704a7.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 428 LPW V11
Nexus 4 5.0.0 Api 21 320dpi
El botón SAVE, esta cortado. 
![caso 428](https://cloud.githubusercontent.com/assets/17283358/15756944/4262dd0e-28cd-11e6-83fe-4fcc24e3aa6d.png)

**Comment by AdryCanonico** [comment]
@nattyco  en la versión 13 persiste el error.

![code](https://cloud.githubusercontent.com/assets/18584168/15794977/d8afd442-29b8-11e6-9b9e-93a670c4cbe9.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version 15.2 no se ve cortado pero seria bueno no dejar tanto espacio en blanco del lado derecho.


![external](https://cloud.githubusercontent.com/assets/18584168/15934510/a4f390f2-2e2d-11e6-8c54-2709c550264a.png)

**Comment by Hernandezsmanu** [comment]
En la version 15.2 queda un espacio en blanco del lado derecho en los botones, a mi parecer deberían estar centrados o completarse el espacio. @nattyco 

![screenshot_5](https://cloud.githubusercontent.com/assets/5313335/15934639/1c8c13a0-2e2e-11e6-950f-ef3732aac860.png)

**Dispositivo de donde se realizo la prueba:**

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/15934616/06afc220-2e2e-11e6-8f73-0806072ba8fe.png)

**Comment by AdryCanonico** [comment]
En la version 16.2 queda un espacio en blanco del lado derecho en los botones, seria bueno que este centrada o completarse el espacio. @nattyco

**Comment by AdryCanonico** [comment]
@nattyco en la version 17 no se ve cortado pero seria bueno no dejar tanto espacio en blanco del lado derecho

**Comment by maydiamc** [comment]
en mi dispositivo sucede lo mismo, se ve descuadrado con respecto al lado izquierdo @nattyco 
version 17
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025299/58efd92a-3190-11e6-9a30-ba69ae3f809c.png)

**Comment by nattyco** [comment]
@AdryCanonico  verificar este caso

**Comment by marielis-urbina** [comment]
En la versión 3.5 no sucede este error en mi emulador

![image](https://cloud.githubusercontent.com/assets/19353722/18931574/c38e5492-859a-11e6-8c4b-3fafd3283d24.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/18931585/cdd4cbca-859a-11e6-8954-5d28a7b82d4b.png)

**Comment by yolandayancel** [comment]
CCP 3.4.4 LPW

Caso 428
En la versión 3.5 no sucede este error 

![screenshot_2016-09-28-16-38-02](https://cloud.githubusercontent.com/assets/17283358/18931709/5445eaf4-859b-11e6-9469-2e0ffd8b2b4e.png)

**Comment by IsbetVR** [comment]
Closed #428
