### ISSUE TITLE
LPW - FOTOS DE CONTACTOS COMPRIMIDAS O ESTIRADAS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#430]
### LPW

-----

##### Reporte de error: 

   *En la lista de contactos las fotos de los perfiles se visualizan, comprimidas o estiradas, dependiendo de las fotos colocadas en el perfil. 
   
![fotos contac](https://cloud.githubusercontent.com/assets/18584168/15653323/25387e06-2656-11e6-8551-19a576c39e70.png)

![13231](https://cloud.githubusercontent.com/assets/18584168/15653324/282e8448-2656-11e6-8aff-32376894c77a.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15653334/3a478d0a-2656-11e6-88b6-375eac95a6f7.png)

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15653335/3a4d2e40-2656-11e6-839c-ea439ae2b67b.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by yolandayancel** [comment]
@nattyco 
Prueba Caso 430 LPW V11
Nexus 4 5.0.0 Api 21 320dpi
En la lista de contactos las fotos de los perfiles se visualizan bien.
![caso 430](https://cloud.githubusercontent.com/assets/17283358/15754407/d8372fe4-28c1-11e6-9c49-9ea820192721.png)

**Comment by AdryCanonico** [comment]
@nattyco en la versión 12 sigue persistiendo el error en las fotos de contacto.

**Comment by AdryCanonico** [comment]
@nattyco en la versión 13 mejoro pero sigue viéndose un poco estirada la foto.

**Comment by MaviDavsa** [comment]
@AdryCanonico Pon una capture por favor!

**Comment by AdryCanonico** [comment]
*En los contact se ven las fotos de los contactos comprimida o con fondo negro. 

![screenshot_2016-06-08-11-04-01](https://cloud.githubusercontent.com/assets/18584168/15899334/3a2a24c0-2d65-11e6-8be5-92d2e200b049.png)


![screenshot_2016-06-08-09-52-42](https://cloud.githubusercontent.com/assets/18584168/15898498/60255832-2d62-11e6-84d9-66a5eaa8458f.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:SAMSUNG

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15898562/a1292e58-2d62-11e6-85aa-f1384cadab53.png)

**Comment by maydiamc** [comment]
@nattyco en mi dispositivo sucede lo mismo

![screenshot_2016-06-08-11-09-32](https://cloud.githubusercontent.com/assets/17274154/15899900/305e6a3a-2d67-11e6-9349-3b5751cb6891.png)

Samsung Galaxy 
Mini s4
4.4.2

**Comment by AdryCanonico** [comment]
@nattyco Persiste el error en la versión 17 LPW 

![screenshot_2016-06-13-09-43-55 - copia](https://cloud.githubusercontent.com/assets/18584168/16009752/e1bbf0fc-3147-11e6-855e-5db31c9e72cc.png)

![fotos comprimidas - copia](https://cloud.githubusercontent.com/assets/18584168/16009751/e1bb118c-3147-11e6-8b86-a6ae10c9bf07.png)

**Comment by maydiamc** [comment]
en la version 17 persiste este problema @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025252/12305e42-3190-11e6-9a6a-2dc666410f7c.png)

**Comment by danielaporras** [comment]
CCP v3.5 este error fue solucionado.
![screenshot_2016-09-29-09-01-07](https://cloud.githubusercontent.com/assets/19656830/18955000/72b99c14-8623-11e6-82d7-3190f2fcdff4.png)

Por favor cerrar el caso, @sanro14
