### ISSUE TITLE
LPW - NO TIENE FUNCION EL BOTON DE COPIAR DIRECCION DE CONTACTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#431]
### LPW

-----

##### Reporte de error: 

   *La función para copiar la dirección del contacto no tiene no esta activa. Se actualizo la app 

![13231](https://cloud.githubusercontent.com/assets/18584168/15653538/724fe93a-2657-11e6-8f8c-d9abba86c2c5.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15653562/8f0f3b34-2657-11e6-87df-3d1a67f29e12.png)

![nexus s](https://cloud.githubusercontent.com/assets/18584168/15653563/8f170b3e-2657-11e6-856f-328da4490e4b.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  Corregido verificar en la version 8 de la apk

**Comment by andreagmarcano** [comment]
La función para copiar la dirección sigue sin funcionar.

**Comment by yolandayancel** [comment]
@nattyco 
La función de copiar la dirección no funciona
Nexus 4 5.0.0 Api 21 
320dpi

**Comment by MaviDavsa** [comment]
Corregido! ;D

**Comment by AdryCanonico** [comment]
@MaviDavsa este caso funciona en el:

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15679609/512aa9e6-271c-11e6-9c7f-b04531f554b2.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15679610/512bf134-271c-11e6-9e90-228b7a918958.png)
