### ISSUE TITLE
App_Inicio_error al abrir la aplicacion por primera ver

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#432]
#### Nombre pantalla

Al ingresar por primera vez a la version 8, esta sale con el fondo blanco y no se ven los botones inferiores, es necesario ingresar a una de las aplicaciones que este visible y retroceder para que esta vuelva a la normalidad.

![screenshot_2016-05-30-18-16-47 1](https://cloud.githubusercontent.com/assets/17274154/15659202/e6e1b10a-2690-11e6-81c8-eb7bb68b80a5.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by nattyco** [comment]
@furszy

**Comment by furszy** [comment]
Necesito más detalles, @nattyco fíjate si podés duplicarlo en tu teléfono y pasarme el stacktrace.

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 9 - LPW de la app sigue persistiendo el error. Tuve que cerrar y abrir la aplicación 3 veces para que abriera completa. 

![fondo blanco](https://cloud.githubusercontent.com/assets/18584168/15678415/13adda10-2718-11e6-8e5d-dcc2df128aad.png)

Dispositivos:

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15678512/6a7624a6-2718-11e6-9752-bde98c453deb.png)

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15678513/6a7a4446-2718-11e6-95e0-9462c0c95d48.png)

**Comment by maydiamc** [comment]
en la version 11 se mostro el mismo problema @nattyco @MaviDavsa 
![screenshot_2016-06-01-17-32-18](https://cloud.githubusercontent.com/assets/17274154/15730180/3dd09c3e-2834-11e6-8d10-c247f5dd2a10.png)

**Comment by RubenSem** [comment]
En la version 12 Muestra el mismo problema @nattyco @MaviDavsa 
![13adda10-2718-11e6-8e5d-dcc2df128aad](https://cloud.githubusercontent.com/assets/19676223/15779897/d0cf3236-2968-11e6-8db3-5d8a0c9eb8e6.png)

**Comment by danielaporras** [comment]
Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0
 En LPW v.13 sigue saliendo este mismo error 
![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15794514/173abb36-29b5-11e6-8dad-0937556c31be.png)

**Comment by LilianFlores** [comment]
En la versión 16.4 de CBP muestra el mismo problema @nattyco @MaviDavsa 

![070616error](https://cloud.githubusercontent.com/assets/19652611/15878232/282d0f12-2ce3-11e6-94f5-95cf4a031f8b.png)

**Dispositivo desde donde se realizo la prueba**

Marca: Genymotion
Modelo: Google Nexus 5
Versión de Android: 5.0.0

**Comment by maydiamc** [comment]
en la version 15.2 no sucedio este problema @nattyco

**Comment by AdryCanonico** [comment]
@MaviDavsa EN LA VERSIÓN 16.2 NO SE PRODUCE EL ERROR

**Comment by RubenSem** [comment]
En la versión 16.5 vuelve a ocurrir este error. aclaro que solo es cuando inicio por primera vez la aplicación. por favor reabrir caso. @nattyco @MaviDavsa 
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/15981352/0daf31a8-2f3e-11e6-9a22-440487774c2f.jpg)

Especificaciones del tlf:

![screenshot_5](https://cloud.githubusercontent.com/assets/19676223/15981360/2e338cc6-2f3e-11e6-87bd-91393ecb8a5e.jpg)

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 432 CBP V 16.5
Nexus 5  5.1.0
Ocurre lo mismo que se reportó.

![caso 432](https://cloud.githubusercontent.com/assets/17283358/15982021/ef80b86e-2f47-11e6-8607-c46c64a00840.png)

**Comment by AdryCanonico** [comment]
@nattyco En la Version 16.5 de CBP Ocurre este error. 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987255/fb02ae28-2feb-11e6-9515-e8436167840e.png)

![5 0 delio](https://cloud.githubusercontent.com/assets/18584168/15987270/742f21c8-2fec-11e6-83e2-938075dfdcd8.jpg)
