### ISSUE TITLE
CBP - No permite crear identidades en Profiles para Broker y Customer

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#433]
##### Reporte de error: 

   *Cuando quiero crear una identidad a través de "profiles" (Pantalla 1) como "Broker" o "Customer" (Se ha intentado con los dos en diferentes dispositivos), aparentemente crea el perfil (Pantalla 2), pero inmediatamente vuelve a mostrar la pantalla de bienvenida (Pantalla 3) y dice que no hay identidades creadas y vuelve a sugerir crear una nueva identidad (Pantalla 4). Borro data, vuelvo a correr la aplicación y continúa el mismo error. En muchas ocasiones sale el mensaje de "Fermat isn't responding" (Pantalla 5)

------

#### Pantalla 1

![screenshot_33](https://cloud.githubusercontent.com/assets/19142276/15659391/e24f9e0c-2697-11e6-999f-816a6c90f2bf.jpg)

#### Pantalla 2

![screenshot_28](https://cloud.githubusercontent.com/assets/19142276/15659403/022864e8-2698-11e6-948a-d53198fd4fb9.jpg)

#### Pantalla 3

![screenshot_29](https://cloud.githubusercontent.com/assets/19142276/15659411/14112942-2698-11e6-9301-a8ef06a29dcf.jpg)

#### Pantalla 4

![screenshot_30](https://cloud.githubusercontent.com/assets/19142276/15659417/3097f44c-2698-11e6-9c74-8b66f443a08c.jpg)

##### Pantalla 5

![screenshot_32](https://cloud.githubusercontent.com/assets/19142276/15659421/5b57a7d6-2698-11e6-847f-e12aa0ed2ede.jpg)

------

#### Dispositivo desde donde se realizó la prueba (Pantalla 2, 3 y 4)

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15659443/886726ca-2698-11e6-807a-ddb772dd275d.jpg)

#### Dispositivo desde donde se realizó la prueba (Pantalla 1 y 5)

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15659445/8d328776-2698-11e6-98b0-2d4ea2c6267e.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @abicelis

**Comment by marielis-urbina** [comment]
A mi también me pasa. Al principio cuando quiero crear mi identidad "Broker" o "Customer" la pantalla en dos ocasiones se coloco en negro y no respondía la tercera vez que volví a borrar data,  la aplicación me dejo montar con foto y todo mi perfil pero al darle al botón crear, no la graba y vuelve a la pantalla como si nunca lo hubiese hecho 

![modelo](https://cloud.githubusercontent.com/assets/19353722/15659564/6adb9480-2696-11e6-9e9b-d298096cb688.png)

**Comment by vlzangel** [comment]
Ok @marielis-urbina @MaviDavsa @IsbetVR de esto me encargo yo.

**Comment by marielis-urbina** [comment]
En la nueva versión de la APK 16.3, persiste el error al querer crear el perfil de "Broker o "Customer", no lo guarda y aparece en negro, después el siguiente aviso y la pantalla no responde

![fermat no responde](https://cloud.githubusercontent.com/assets/19353722/15795488/bc75e9a8-29bb-11e6-889e-b6d3daa64dd3.png)

Dispositivo desde donde se realizó la prueba (Pantalla 1 y 5)

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.1.0

![android 5 1](https://cloud.githubusercontent.com/assets/19353722/15795500/d36dbcc6-29bb-11e6-9808-60a46d155223.png)

**Comment by AdryCanonico** [comment]
@vlzangel En la versión 16,3 persiste el error y cuando se usan los predeterminados a veces se sale de la community.

**Comment by IsbetVR** [comment]
En la versión 16.4 persiste el error.

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 433 CBP V16.5
Nexus 5 5.1.0 480dpi
En este emulador no deja usar la camara, pero deja agregar la foto de galeria para crear el Broker. pero aparece un recuadro se se sale de la apk. Pero si permite crear el perfil como customer con la foto de galería.
Como Broker
![no deja crear el perfil 1](https://cloud.githubusercontent.com/assets/17283358/15982148/9f3323e4-2f4a-11e6-84b2-9323d695394c.png)
Como Customer
![no deja crear el perfil 2- broker](https://cloud.githubusercontent.com/assets/17283358/15982164/b4507e34-2f4a-11e6-802f-e2433a40a609.png)

**Comment by AdryCanonico** [comment]
@vlzangel En la version 16.5 de CBP Esta ocurriendo el mismo error en la broker y en la Customer. Esto me sucedió en teléfonos físicos. @MaviDavsa Por fa revisa el caso #483 ya que son muy parecidos. 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987456/21b42022-2ff3-11e6-8d26-cc5232e8c715.png)

![5 0 delio](https://cloud.githubusercontent.com/assets/18584168/15987457/21b49d86-2ff3-11e6-8f96-fb225e0f2ae4.jpg)

**Comment by andreagmarcano** [comment]
Cuando estoy en el procedimiento para crear una identidad y le doy a guardar los cambios realizados, me muestra "Fermat no responde" y me saca de la aplicacion. 

![image](https://cloud.githubusercontent.com/assets/18452495/16025841/d0946128-3193-11e6-8755-6aa85928178e.png)

![image](https://cloud.githubusercontent.com/assets/18452495/16025864/f0ac2856-3193-11e6-93f5-887f1845ead3.png)

**Comment by danielaporras** [comment]
En la version 16.5 de CBP al intentar crear el perfil de broker, con la opcion imagen desde camara del emulador me aparece el error de recovering from system y me lleva al menu principal de fermat, y al tratar de poner foto desde la galeria me saca por completo de la aplicacion.

![screenshot_7](https://cloud.githubusercontent.com/assets/19656830/16044421/32f19208-320e-11e6-91db-e9c7df66f7f0.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/19656830/16044689/4ed210f0-320f-11e6-8785-156cf4f009e7.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0

@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by nelsonalfo** [comment]
ha probado este issue con la version 16.6?

**Comment by Gabymorillo** [comment]
En la versión 16.6 no se presentó ese error en mi dispositivo. 
![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16063308/4991b1d8-3262-11e6-89ca-0fed1586d6a9.png)

**Comment by GeronimoVierma** [comment]
Probé la versión 16.6 y me permitió crear el perfil sin problemas.

![issues](https://cloud.githubusercontent.com/assets/19883115/16063522/a13e13da-3263-11e6-86c1-978f756a597f.png)

**Comment by JeanFranco498** [comment]
En la version 16.6 el error no existe 
![image](https://cloud.githubusercontent.com/assets/19807906/16063621/7e03b0d2-3268-11e6-8db5-91cc627e0733.png)

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  433   CBP V 16.6
Nexus 5  5.1.0
En este emulador, no permite tomar la foto, ni para customer, ni para Broker
![caso](https://cloud.githubusercontent.com/assets/17283358/16083328/62ef3f52-32de-11e6-93cd-9df7d4305bd1.png)

**Comment by nelsonalfo** [comment]
No tienes la camara activa en el emulador, debes activarla así como hiciste con el GPS

**Comment by yolandayancel** [comment]
@nelsonalfo 
Cos respecto a tu indicación, en la foto veras que está activado el GPS.
Realice nuevamente la prueba para descartar.Resulta que ahora si funciona la cámara. Pero no deja crear el perfil.
![caso 433](https://cloud.githubusercontent.com/assets/17283358/16084333/38a6c57c-32e2-11e6-8979-fd11d51142df.png)

**Comment by nelsonalfo** [comment]
por favor agrega el archivo **logcat.txt** a este Issue cuando te suceda ese error para tener mayor detalle de cual pudiera ser el problema

**Comment by yolandayancel** [comment]
@nelsonalfo 
Nexus 5 5.1.0
Logcat de lo reportado
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/316524/logcat.txt)

**Comment by nelsonalfo** [comment]
cuando le diste al boton CREATE fue cuando te dio el error?

**Comment by AdryCanonico** [comment]
@nelsonalfo en la version 17 en mi teléfono físico puedo crear perfil en ambos sin problemas.

**Comment by nelsonalfo** [comment]
en la version 17.1 deberia estar resuelto

**Comment by danielaporras** [comment]
En la versión 17.3 no permite crear el perfil en nexus 5, al seleccionar la opción (foto desde cámara del emulador) se cierra la aplicación y aparece el siguiente error "Recovering from system error"  (Pantalla 1). En la opción de galería se repite el mismo error (Pantalla 2) y se va al menu principal de Fermat (Pantalla 3).
Cabe destacar que el GPS esta activo.

Pantalla 1

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/16135139/5aa3f424-33eb-11e6-9181-1bdef8e727af.png)

Pantalla 2

![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/16135140/5e1fd370-33eb-11e6-8def-2c31f3848997.png)

Pantalla 3

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/16135143/63bb3018-33eb-11e6-8376-59f62a128784.png)

Dispositivo desde donde se realizo la prueba:

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/319443/logcat.txt)


@nelsonalfo

**Comment by IsbetVR** [comment]
@nelsonalfo 
En la versión 17.4 de CBP no me generó problemas al crear los perfiles y colocarles imagen.
Me los dejó crear sin problema.

Los demás que reportaron el error por favor verificar si ya no tienen inconvenientes.

Dispositivo de prueba
- [x] Emulador
- Google Nexus 4
- Versión de android: 5.0.0
- 320 dpi
- API 21 768x1280
