### ISSUE TITLE
App_Inicio_no aparecian las aplicaciones wallet

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#434]
#### Nombre pantalla

Al cerrar la aplicacion y volver a ingresar, no se podian visualizar las aplicacionesde la pantalla wallet en el menu principal
Version 8 de LPW
![screenshot_2016-05-30-19-31-21](https://cloud.githubusercontent.com/assets/17274154/15659742/382d741e-269a-11e6-9418-37d0edf94c85.png)

![screenshot_2016-05-30-19-31-24](https://cloud.githubusercontent.com/assets/17274154/15659743/419f450e-269a-11e6-990a-5fc86b0174ef.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by nattyco** [comment]
@furszy

**Comment by danielaporras** [comment]
Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0

En LPW v.13 aun sigue este error

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15794952/b0219074-29b8-11e6-9662-7b156e3ddf08.png)

**Comment by furszy** [comment]
Necesitaría saber en qué situación ocurre esto, si es cuando lo abrís, cuando lo dejas abierto y lo minimizas, dejame más detalles por favor

**Comment by MaviDavsa** [comment]
@furszy A mi personalmente me llego a pasar cuando lo abri! No se como le paso a las chicas! @maydiamc @danielaporras

**Comment by maydiamc** [comment]
Cuando lo abri me sucedio a mi tambien.! Lo coloque en el issues @furszy

**Comment by MaviDavsa** [comment]
Pero bella a lo que @furszy se refiere es que si fue dese 0, por lo menos en mi caso fue desde 0, en cambio si lees tu issues, lo que da a entender es que lo minimizaste o cerraste y al abrirlo estaba así pero ya habías estado dentro de el! No se si me explico!?

**Comment by maydiamc** [comment]
Bella yo la cerre, no la minimice, la cerre y la volvi a abrir y sucefio este problema, no fue desde 0, yo la estaba usando normal y la cerre xq me dio un problema y cuando la abri paso esto.!

**Comment by danielaporras** [comment]
En la versión 14 de LPW sigue sucediendo esto.
@MaviDavsa  @sanro14 

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0.

![screenshot_6](https://cloud.githubusercontent.com/assets/19656830/15842864/97756a6c-2c26-11e6-86af-0fad943a44d4.png)

**Comment by maydiamc** [comment]
en la version 16 se presento este error @nattyco 

![screenshot_2016-06-09-18-48-48](https://cloud.githubusercontent.com/assets/17274154/15949255/f8a99b28-2e6f-11e6-9e15-b54c67b3a0cd.png)

samsung galaxy 
mini s4
4.4.2

**Comment by danielaporras** [comment]
En la versión 16 se sigue repitiendo el error.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15964593/20fcabe2-2ee3-11e6-8e0c-518dfa4d3ad3.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0

@MaviDavsa

**Comment by danielaporras** [comment]
En la versión 16.1 persiste el error.

![screenshot_8](https://cloud.githubusercontent.com/assets/19656830/15967339/0cdf0a66-2ef1-11e6-8473-772ac9be62a3.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by maydiamc** [comment]
en la version 17 de la apk esto se soluciono @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
