### ISSUE TITLE
CommunityWallet - Me borro los contactos

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#435]
#### Nombre pantalla
Community Wallet 

### LPW

-----

##### Reporte de error: 

   * El error comienza cuando voy a la community a ver un request de contactos que me habian enviado, en lo que llego a la community me sale este error.

![screenshot_2016-05-30-19-20-59](https://cloud.githubusercontent.com/assets/17273005/15659831/9f0efada-269b-11e6-86d2-4fee085489d8.jpg)

Después al ir a contactos me doy cuenta de que me elimino todos los contactos que ya tenia

![screenshot_2016-05-30-19-21-12](https://cloud.githubusercontent.com/assets/17273005/15659835/afea5796-269b-11e6-9683-d5a6c072b4e3.jpg)

Y para concluir vuelvo a la community para intentar hacer conexiones con las personas que antes tenia y la pantalla se me queda congelada aquí

![screenshot_2016-05-30-19-31-08](https://cloud.githubusercontent.com/assets/17273005/15659841/ca68058c-269b-11e6-9588-036e8be55d3e.jpg)

Debo cerrar la apk desde 0 y volverla abrir para que me funcione, pero en la apk se conservan los btc más no los contactos. 
   
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-05-30-10-31-49](https://cloud.githubusercontent.com/assets/17273005/15659870/35e7aace-269c-11e6-823a-9b09cbeae3ef.jpg)

**Comment by MaviDavsa** [comment]
@nattyco Hay que ver como hacer con estos tipos de versiones!

**Comment by nattyco** [comment]
@MaviDavsa verificar en la version 10 de la apk

**Comment by yolandayancel** [comment]
@nattyco

Caso 435
Prueba 01-06-16
Nexus 4 5.0.0 API 21 320 dpi
 El error no ocurre: entro a la  community a ver un request de contactos y no me aparece ese error, salen los contactos.
![caso 435](https://cloud.githubusercontent.com/assets/17283358/15712829/a68cb304-27dd-11e6-8637-95e77145578d.png)
