### ISSUE TITLE
Cripto Wallet Users - Duplica los users

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#436]
### Contacts - Fermat User - Cripto Wallet Users 

-----

##### Reporte de error: 

   *Cuando entro a la "Cripto Wallet User" a través de "Contacts - Fermat User" en la LPW, los users salen duplicados.

------

##### Pantalla 1

![screenshot_34](https://cloud.githubusercontent.com/assets/19142276/15659951/f926da82-26a1-11e6-891a-1b51fb8dfe46.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo: HTC One X
* Version de Android: 4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15659953/0dbc6fac-26a2-11e6-9e8b-363afba1d7b0.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by arosiopr** [comment]
sigue pasando 

![se repiten contactos](https://cloud.githubusercontent.com/assets/5313326/15681678/fd76b292-2723-11e6-9f16-0996151a5961.png)

**Dispositivo desde donde se realizo la prueba**

    Marca:Genymotion
    Modelo: Google Nexus 5
    Version de Android: 5.0.0

**Comment by yolandayancel** [comment]
@nattyco
Prueba Caso 436 LPW V11
Nexus 5 5.0.0 Api 21 480 dpi
Cuando entro a la "Cripto Wallet User" a través de "Contacts - Fermat User" en la LPW, los users no 
![caso 436](https://cloud.githubusercontent.com/assets/17283358/15753870/48e64d7c-28bf-11e6-9e02-808b26079f38.png)
salen duplicados.
