### ISSUE TITLE
Cripto Wallet users-community: al enviar un Request Sent, desaparecen los user

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#437]
#### Nombre pantalla
Cripto Wallet User

##### Reporte de error: 

   * 1- Estando en la pantalla de CRIPTO WALLET USER
![al agregar un contacto desaparesen los crypto user 1](https://cloud.githubusercontent.com/assets/17283358/15659955/e17230de-269d-11e6-8ac1-db2ac32f46e2.png)

 2- y al clikear sobre ISBERT- user,  para enviarles un  Requet Sent, este lo envía bien,
![al agregar un contacto desaparesen los crypto user 2](https://cloud.githubusercontent.com/assets/17283358/15659978/52a3416c-269e-11e6-9bed-d164b932a34c.png)

 3- Pero al volver al la cripto wallet user, desaparecieron los user.
![al agregar un contacto desaparesen los crypto user 3](https://cloud.githubusercontent.com/assets/17283358/15660004/c55f7144-269e-11e6-9b56-0a41624bde65.png)

4- tuve que cerrar el emulador para poder nuevamente ver los Cripto wallet user de la community
![al agregar un contacto desaparesen los crypto user 5](https://cloud.githubusercontent.com/assets/17283358/15660094/dd8d88ee-26a0-11e6-9587-c1b66135b16e.png)

y volvi a probar con otro user  (Dianei), y volvió a ocurrir el mismo.

#### Dispositivo desde donde se realizo la prueba
320dpi
![nexus 4- 5 0 0](https://cloud.githubusercontent.com/assets/17283358/15660115/30f6c0a4-26a1-11e6-9628-866d878293b1.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la version 9 - LPW, sigue persistiendo el error. Tambien en el nexus 7. No solo como se habia comentado en los 4.1....


![community vacio](https://cloud.githubusercontent.com/assets/18584168/15679161/b1ba64ce-271a-11e6-911c-429fe233d0fd.png)

dispositivo:

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15679187/bf3084a8-271a-11e6-9a8e-b24be250949a.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 437- Resuelto
01-06-16
Nexus 4 5.0.0 Api 21 320 dpi
Se envia la connection request bien y al volver al la cripto wallet user, estan los user.

![caso 437](https://cloud.githubusercontent.com/assets/17283358/15714804/d5df7f4e-27e5-11e6-9e47-e9c7fd8805ba.png)

![caso 437 1](https://cloud.githubusercontent.com/assets/17283358/15714874/25d6aa36-27e6-11e6-8dc1-de367bfc896d.png)
