### ISSUE TITLE
LPW_home_aplicacion colgada

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#438]
#### Nombre pantalla

-----

##### Home

- [x] Pantalla principal

##### Reporte de error: 

   *Al estar probando la aplicacion, al encontrarme en el menu home, este se colgo de repente y no hacia click en ninguno de los botones, solo desplegabla el navigation view, pero no accesaba a ninguna de las otras pantalla, pero al seguir apretando en varios lugares para tratar de hacer reaccionar la aplicacion, esta empeoro, y ya ni si quiera desplegaba el navigation view, ni retrocedia, ni hacia nada, hasta que el telefono arrojo un mensaje para cerrar la aplicacion, porque esta no respondia. 

![screenshot_2016-05-30-19-30-45](https://cloud.githubusercontent.com/assets/17274154/15660212/d5c517c4-26a2-11e6-85e6-06693d0eba18.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
version 8 de la apk @nattyco @MaviDavsa

**Comment by IsbetVR** [comment]
a mi me sucede cuanto estoy en la community para buscar los users con los que quiero establecer la conexión, se queda "cargando" demasiado tiempo (más de 15min) y si le doy a otra opción para salirme de ahí, más no de la aplicación, se "cuelga" y me obliga a salir de la aplicación.

Dispositivo de prueba:
HTC One X
Versión de android: 4.2.2

**Comment by Gabymorillo** [comment]
Al tratar de entrar a la aplicación se queda colgada con el logo de fermat, al cerrar el emulador y abrir de nuevo despues de un largo rato cargando, la pantalla se queda en negro o blanco.

![capture-20160530-201359](https://cloud.githubusercontent.com/assets/17262077/15660383/3d9e627c-26a5-11e6-8c90-d689b02cbd1b.png)
![capture-20160530-202239](https://cloud.githubusercontent.com/assets/17262077/15660387/3fcd9478-26a5-11e6-8326-900d07425696.png)
![capture-20160530-194716](https://cloud.githubusercontent.com/assets/17262077/15660388/41404d1e-26a5-11e6-85d7-c77dc7feedc8.png)


Dispositivo de prueba:
Google Nexus 4
Versión de android: 5.1.0

**Comment by andreagmarcano** [comment]
Cuando entro en contacto me sale en blanco teniendo personas agregadas, también cuando voy a agregar un contacto dura mucho tiempo cargandose y no me muestra nada. 
![image](https://cloud.githubusercontent.com/assets/18452495/15660419/f284111e-26a5-11e6-9c86-65ed8e12fbd6.png)

Nexus 5.1

**Comment by camilavaleria** [comment]
En mi caso se colgó la aplicación cuando de la pantalla de HOME salí para ir a los contactos y realizar un request, quedo así:

![image](https://cloud.githubusercontent.com/assets/18740418/15660457/8f412dac-26a6-11e6-8a5b-57ca9c271276.png)

Dispositivo de prueba:

![image](https://cloud.githubusercontent.com/assets/18740418/15660471/c668dfc8-26a6-11e6-9235-900e6b9ee64e.png)

**Comment by nattyco** [comment]
@Gabymorillo @MaviDavsa tu reporte tiene que ser en un issue nuevo ya que es algo del start de la app y no de la LPW , y creo que ya existe ese reporte

**Comment by MaviDavsa** [comment]
@Gabymorillo Creo que lo podrías redireccionar a este caso #410

**Comment by Gabymorillo** [comment]
Ok!

2016-05-31 8:13 GMT-04:30 MaViDavsa <notifications@github.com>:

**Comment by maydiamc** [comment]
el errorel error se esta presentando en la version 11 @MaviDavsa @nattyco

**Comment by yolandayancel** [comment]
@nattyco 
Prueba Caso 438 LPW V11
Nexus 4 5.0.0 Api21 320dpi
Deja ingresar al  menu home.
![caso 438](https://cloud.githubusercontent.com/assets/17283358/15753482/0c5c6316-28bd-11e6-82f9-1048e7e02881.png)

**Comment by maydiamc** [comment]
en la version 12 de la apk sucede lo mismo
@nattyco 
![screenshot_2016-06-03-11-32-57](https://cloud.githubusercontent.com/assets/17274154/15785689/5a525aba-2982-11e6-94d8-1c06f0838051.png)

**Comment by AdryCanonico** [comment]
@nattyco en la versión 13 persiste el error

**Comment by maydiamc** [comment]
en la version 16 de la apk esta presentandose este error.! @nattyco 

![screenshot_2016-06-09-18-47-04](https://cloud.githubusercontent.com/assets/17274154/15949217/9795a746-2e6f-11e6-8890-7170a13733f6.png)

Samsung galaxy
mini s4
4.4.2

**Comment by maydiamc** [comment]
este error se sigue mostrando en la version 16.2 @nattyco

**Comment by maydiamc** [comment]
esto se soluciono en la version 17 de laapk @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
