### ISSUE TITLE
LPW - Error en Send Request to Contact - Advertencia con monto pequeño en valor

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#439]
#### Payment requests - Request - Send Request To Contact

-----

##### Reporte de error: 

   *Sucede cuando estoy tratando de enviar un "Request" con un valor muy pequeño en el monto, me sale un mensaje de advertencia errado (Pantalla 1), como si el monto que estuviese introduciendo en el campo "amount" fuese mayor al que me dice la advertencia, y por ende no deja hacer el request. 

------
#### Pantalla 1

![screenshot_42](https://cloud.githubusercontent.com/assets/19142276/15660213/06cc4e88-26a7-11e6-8862-1555762b2dc6.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: HTC One X
* Version de Android: 4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15660216/14402044-26a7-11e6-8a6d-8109da5fcd8f.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by nattyco** [comment]
@MaviDavsa  @IsbetVR  corregido, verificar en la version 9 de la apk

**Comment by AdryCanonico** [comment]
@IsbetVR @nattyco @MaviDavsa En la version 9 sigue el error.

![ivalido monto](https://cloud.githubusercontent.com/assets/18584168/15680256/d49417f2-271e-11e6-96b1-48250645a4ae.png)

y al ingresar 0.00000543 da este mensaje.

![543](https://cloud.githubusercontent.com/assets/18584168/15680263/dbe0df36-271e-11e6-9594-13fee2093c20.png)

**Comment by AdryCanonico** [comment]
si se hace el cambio a Satoshis no deja hacer la acción. (Se le coloco el monto del mensaje)

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  el mensaje dice que el monto a enviar tiene que ser mayor a  0.00000543 btc, no se puede enviar menos ni igual a eso

**Comment by AdryCanonico** [comment]
con un monto mayor sale el error igual,

![9](https://cloud.githubusercontent.com/assets/18584168/15682019/85a6af90-2725-11e6-9a37-21e179150136.png)

**Comment by nattyco** [comment]
@AdryCanonico @MaviDavsa corregido en la version 10 de la apk. Tener en cuenta que el minimo es
0.0000543 btc
0.00000600 btc es menor a ese valor
Todas las pruebas que reportaron el monto es menor porque tiene 5 ceros despues de la coma. Asi que este caso se tendria que haber cerrado cuando el mensaje se mostro correctamente.

**Comment by IsbetVR** [comment]
@nattyco @MaviDavsa 
Corregido en la v10 de la apk LPW, establece en el mensaje que el monto debe ser mayor a "0.0000543", y efectivamente probé enviar un request de "0.0000544" y funcionó bien.


![screenshot_53](https://cloud.githubusercontent.com/assets/19142276/15712649/2c2b2470-27e1-11e6-9ed4-d4af904ba73b.jpg)
