### ISSUE TITLE
LPW - POP BANNER ESTIRADO 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#440]
### LPW

-----

##### Reporte de error: 

   *El banner de bienvenida se ve muy estirado. Esto pasa solo en el Nexus 7, 213 dpi

![banner estirado](https://cloud.githubusercontent.com/assets/18584168/15678627/ddc595e0-2718-11e6-870f-08d7140f4f70.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15678613/c8b99ea8-2718-11e6-8e57-c5126a49279e.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by yolandayancel** [comment]
@nattyco 
Prueba Caso 440 LPW V11
Nexus 4 5.0.0 Api 21 320dpi
*El banner de bienvenida se ve bien
![caso 440](https://cloud.githubusercontent.com/assets/17283358/15753328/452d520a-28bc-11e6-8f81-7a578a373edd.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa este caso hay que re-abrirlo ya que el banner se sigue viendo estirado. 
Esto es un error que solo da  en versiones como nexus 7, nexus 9, etc. Tiene que ser probado en estos dispositivos, ya que en otros emuladores el problema con el gráfico no aparece. 

![banner](https://cloud.githubusercontent.com/assets/18584168/15793656/4abec48a-29af-11e6-8391-2a22ff29b98e.png)

**Comment by AdryCanonico** [comment]
@nattyco En la version 13 se ve estirado y l boton de CLose algo grande en todos los emuladores. 
Seria algo bueno un boton un poco mas delicado o amigable para el usuario.


![banner](https://cloud.githubusercontent.com/assets/18584168/15795740/683bf8ac-29be-11e6-9597-8727d25988e0.png)

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  los popus no estan optimizados para tablets, asi que todo lo que probes en esas versiones de veran asi

**Comment by AdryCanonico** [comment]
@nattyco seria bueno arreglar este tipo de errores tambien en las tablets ya que se busca que se vea bien en todas las versiones.Se ven diferentes tamaños o las cosas no están bien centradas

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa  En la versión 14 de LPW, al pop le falta el boton de cerrar.  (Solo en el Nexus 7 o tablets)

![pop nexus 7](https://cloud.githubusercontent.com/assets/18584168/15862080/50033688-2c98-11e6-84ca-70e52027e671.png)

**Comment by MaviDavsa** [comment]
@AdryCanonico Esto por ser el mismo caso que te comente de Tablets lo vamos a cerrar por los momentos!
