### ISSUE TITLE
LPW - NO APARECE NOMBRE DE CONTACTO EN LA LISTA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#441]
### LPW

-----

##### Reporte de error: 

   *En la lista de contactos no se visualizan los nombres de los contactos agregados. para poder acceder a la ficha del contacto se tuvo que cerrar y volver abrir la app. (Esto solo pasa en el Galaxy nexus 4.2.2 320 dpi)

![no aparece nombre del contacto](https://cloud.githubusercontent.com/assets/18584168/15679461/bcf1ed70-271b-11e6-8b73-34ef95f44c96.png)

![imagen data](https://cloud.githubusercontent.com/assets/18584168/15680634/422b9c76-2720-11e6-93bd-23bfda8a9c7b.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15679466/cc66c62c-271b-11e6-9e3c-d4bb97bfd22a.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15679467/cc67349a-271b-11e6-8588-e7abd7e89e5a.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  este error se produce porque el nombre de un contacto empieza con un guion y lo toma mal para ordenar,se limitara el nombre de las identidades solo a numero y letras.

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 01-06-16
Caso 441
Nexus 4  5.0.0 API21 320 dpi
En la lista de contactos si se visualizan los nombres de los contactos agregados.
![caso 441 comentario](https://cloud.githubusercontent.com/assets/17283358/15712176/27ab3350-27db-11e6-9735-43f77c2db536.png)

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la versión 10 ya se visualizan los contactos pero no se puede colocar al nombre ni status en Mayusculas caso #445 . Se puede cerrar el caso.
