### ISSUE TITLE
LPW - DRAWER DIFERENTES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#442]
### LPW

-----

##### Reporte de error: 

   *El drawer en el nexus 7 se ve diferente al momento de iniciar en la app. Se tuvo que cerrar y volver abrir para que cargara correctamente.

![drawer diferente](https://cloud.githubusercontent.com/assets/18584168/15679817/0c770898-271d-11e6-9c1a-d7905462583a.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15679827/1ac4c67e-271d-11e6-9d18-9687c9789097.png)

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15679828/1ac8bc84-271d-11e6-8a81-1a9a094cd6a6.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco en la versión 13 se corrigió. se puede cerrar el caso

**Comment by MaviDavsa** [comment]
Solucionado!
