### ISSUE TITLE
LPW- reinicio de la aplicación cuando intento entrar a Fermat users

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#444]
###Reporte de error: 

   *Cuando estoy en la pantalla de contactos y quiero entrar a los de fermat user, al darle click me saca de la aplicación. 
   
![image](https://cloud.githubusercontent.com/assets/5313324/15682159/2e8bb29a-2726-11e6-84f7-42fb3797aa71.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 5
* Version de Android: 5.0

**Comment by sanro14** [comment]
@nattyco ;)

**Comment by nattyco** [comment]
@MaviDavsa  @sanro14  no pude reproducir este error verificar en varios dispositivos con la version 9 de la apk

**Comment by AdryCanonico** [comment]
@nattyco Este es el error que nos paso esta mañana a todas. Cuando se entra te saca de la aplicacion, En mi caso tuve que limpiar data para poder acceder y siempre se cierra dando estos dos errores. 


![intentar entrar a la community](https://cloud.githubusercontent.com/assets/18584168/15690620/349dd82a-274e-11e6-962b-bc173f52c5d8.png)


![mensaje de error snc](https://cloud.githubusercontent.com/assets/18584168/15690621/34a5e9a2-274e-11e6-9f87-49fbc1596dbb.png)

Dispositivo;

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15690644/4d2f7e02-274e-11e6-8fb8-fa247bca9afd.png)

**Comment by MaviDavsa** [comment]
@nattyco De todas maneras ya estan probando con la Versión 10 a ver que pasa!

**Comment by nattyco** [comment]
@MaviDavsa  lo que vi es que en algunas versiones tarda en cambiar de aplicacion, se queda como un rato pensando, eso es porque Fermat va consumiendo mucho CPU del celular.

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 10, sigue el error.

**Comment by nattyco** [comment]
@MaviDavsa  prueben varias y me dicen bien que es lo que pasa en esa pantalla, si es cuando quieren ver el listado de fermat users que ya tienen como conexiones, o es cuando queiren ir al community desde esa pantalla

**Comment by AdryCanonico** [comment]
cuando se esta en la LPW y se intenta agregar un contacto desde ahi pasa y cuando entras directo desde las community tambien @nattyco

**Comment by nattyco** [comment]
@MaviDavsa  veamos este error porque es algo del core de la app, no es un error de la wallet, no lo he podido reproducir.

**Comment by maydiamc** [comment]
@MaviDavsa @nattyco el error no se esta presentando en la version 11

**Comment by MaviDavsa** [comment]
Perfecto! Cerramos entonces!
