### ISSUE TITLE
Identity - Profiles - no deja introducir mayúsculas para crear el username ni en el status

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#445]
#### Profiles - Wallet User

-----

##### Reporte de error: 

   *No permite introducir mayúsculas en el username ni en el status cuando quiero crear la identidad para LPW a través de Profiles. 

------
#### Pantalla 1

![screenshot_52](https://cloud.githubusercontent.com/assets/19142276/15711794/a3b2b994-27dd-11e6-90a4-50de1e7667bf.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: HTC One X
* Version de Android:  4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15711834/d45354f0-27dd-11e6-966f-4fa2050f237f.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @sanro14

**Comment by nattyco** [comment]
@IsbetVR  corregido en la version 11 de la apk

**Comment by maydiamc** [comment]
listo y solucionado el error @nattyco

**Comment by MaviDavsa** [comment]
Perfecto!
