### ISSUE TITLE
LPW - ERROR FORMA VISUALIZACION DE IMAGEN DE CONTACTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#446]
### LPW

-----

##### Reporte de error: 

   *Se visualiza la foto del contacto cuadrada, no redonda como muestra cuando se va a selecionar.

![pantalla antes del cambio](https://cloud.githubusercontent.com/assets/18584168/15713830/da8a3132-27e1-11e6-9d7d-3c2917c3fd9e.png)

![despues del cambio](https://cloud.githubusercontent.com/assets/18584168/15713877/fc6c3138-27e1-11e6-82b8-9c5dea4f182a.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15713927/42871598-27e2-11e6-919d-4a57c41d2237.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15713928/428f8fc0-27e2-11e6-9f25-859b23eff831.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by yolandayancel** [comment]
@nattyco
Prueba Caso 446 LPW V11
Nexus 4 5.0.0 .api 21 320dpi

Al entrar a Send to contact y se escribe un nombre este aparece en redondo y luego se pone en cuadrado al seleccionar. 
![caso446](https://cloud.githubusercontent.com/assets/17283358/15752918/27a0162a-28ba-11e6-989b-50e5c58aaa88.png)

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  verificar con la version 13 de la apk

**Comment by AdryCanonico** [comment]
@nattyco apenas la tenga te comento el caso. Gracias Natty

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa en la version 13 se visualiza bien la imagen. Se puede cerrar el caso

**Comment by MaviDavsa** [comment]
Listo... Solucionado!
