### ISSUE TITLE
Bitcoin Wallet - balance en bits sale montado

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#447]
#### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Cuando me llegaron los BTC y le di click al balance para que me mostrara en bits, sale montado el valor. 

------
#### Pantalla 1

![screenshot_58](https://cloud.githubusercontent.com/assets/19142276/15716016/b42eb906-27ee-11e6-9c3c-efd5967be978.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4, 320 dpi
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15716072/e7ac8740-27ee-11e6-9cc9-ee63dff7ec9c.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @sanro14

**Comment by MaviDavsa** [comment]
@nattyco Yo no se si es porque la CBP no tiene la ultima actualización de la BitcoinWallet!

**Comment by nattyco** [comment]
@MaviDavsa  esto ya esta corregido en la version de la apk de CCP, estas cosas de la Bitcon Wallet las manejo yo.

**Comment by IsbetVR** [comment]
@nattyco @MaviDavsa 
En la versión v16.5 de la CBP ya no sale montado el balance en bits de la "Bitcoin Wallet"

![screenshot_68](https://cloud.githubusercontent.com/assets/19142276/15979134/23c79718-2f30-11e6-8747-5f32cff32381.jpg)

Probado en:
* [x] Emulador
* Google Nexus 4
* Versión android: 5.0.0

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo Chicos traten de actualizar el apk de la Bitcoin Wallet en la apk de la CBP!
