### ISSUE TITLE
CBP - BROKERS - ERROR EN LA VISUALIZACION DE LA FOTO DEL PERFIL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#448]
### CBP 

-----

##### Reporte de error: 

   *Al momento de crear el perfil se le agrego una foto de la galería y luego se intento colocar una foto tomada del emulado;pero no se visualiza al momento de crearlo.

![broker foto1](https://cloud.githubusercontent.com/assets/18584168/15716053/adceb20e-27ea-11e6-934d-2503bf825ae9.png)

   
pero cuando se salva sale la foto tomada del emulador.

![broker dsalvado](https://cloud.githubusercontent.com/assets/18584168/15716127/e75a604a-27ea-11e6-8098-12aca754e5f6.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15715713/52b35ac4-27e9-11e6-9d12-92013c111e26.png)

**Comment by AdryCanonico** [comment]
@vlzangel

**Comment by vlzangel** [comment]
OK @AdryCanonico  ya veo eso.

**Comment by abicelis** [comment]
@AdryCanonico voy a revisar esto, lo incluyo en la version proxima (16.7), te aviso en todo caso.

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa Este error ya esta corregido en la version 17. Se puede cerrar el caso
