### ISSUE TITLE
CBP-Bitcoin Wallet-no permite ingresar

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#449]
#### Nombre pantalla
Bitcoin Wallet
   
##### Reporte de error: 

   1-Al hacer click en la BITCOIN WALLET, sale un recuadro con un error
![error -al ingresar a la wallet](https://cloud.githubusercontent.com/assets/17283358/15716619/d8156920-27ec-11e6-9e58-81e70e3fd897.png)

   2- Y se va a la pantalla del Welcome de Fermat.
![error -al ingresar a la wallet 1](https://cloud.githubusercontent.com/assets/17283358/15716640/f226174c-27ec-11e6-82ac-2d8eff91881d.png)

   
#### Dispositivo desde donde se realizo la prueba
640dpi
![emulador genymotion -samsung galaxy s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/15716675/178b209a-27ed-11e6-8a75-de9cabd2e2c0.png)

**Comment by MaviDavsa** [comment]
@nelsonalfo Te etiqueto a ti para que en una futura versión se actualice la BitcoinWallet... Y @nattyco No se si este error persiste o no en la Wallet!

**Comment by yolandayancel** [comment]
@abicelis
Buenas tarde Alejandro
Revisa este caso:
 El  error me da al ingresar tanto a la Bitcoin Wallet como a las otros botones: cash, banking, crypto customer o los brokers. 
Avisame si  este caso no vá.

Saludos

**Comment by abicelis** [comment]
@yolandayancel Este error no es particular a ninguna de esas wallets, es un error que se origina en todas las apps, por un tema del FileSystem. No tengo mas informacion sobre eso solo que @furszy esta en eso.

**Comment by abicelis** [comment]
De paso, la bitcoin wallet no es de CBP, es de CCP. Digo pq el milestone y el titulo de este issue apuntan a CBP

**Comment by yolandayancel** [comment]
@nelsonalfo
Prueba 10-06-16
Caso 449 CBP V 16.5
Samsung S6  5.1.0
Resuelto. permite entrar para pedir los BTC

![caso 449](https://cloud.githubusercontent.com/assets/17283358/15982426/c98f9086-2f50-11e6-9324-98fd7e1b951f.png)
. Cerrar el caso
