### ISSUE TITLE
Bitcon Wallet - Settings - Error se cierra la aplicación

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#45]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
------
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Detalle del contacto

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Formulario de envio

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Formulario de pedido de pago

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Requerimientos de pago

- [] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

Al ingresar en la sección settings y dar en la opción de Enabled Notifications salió el siguiente error "Crash occurs, the problems were reported!. Thanks for the help." como se puede observar en la siguiente captura:
![captura de pantalla 2016-03-01 10 54 12](https://cloud.githubusercontent.com/assets/5313324/13431653/750c9fb2-df9c-11e5-9564-291f05324bc9.png)

y después se cerro por completo la aplicación, luego volví a ingresar y paso lo mismo. Vuelvo a ingresar a la aplicación y al intentar ingresar en cualquier sección sale el error "Oooops! recovering from system error" como se observa en la siguiente captura.
![captura de pantalla 2016-03-01 10 34 00](https://cloud.githubusercontent.com/assets/5313324/13431364/560f3468-df9b-11e5-8004-e74ca3874107.png)

   
------

**Comment by augusto-ponce** [comment]
@furszy @acostarodrigo empezamos con los errores, estamos abiertos a sugerencias sobre como exponer los errores para que ustedes puedan interpretarlos de la mejor forma posible

**Comment by furszy** [comment]
Ok bien, vamos a ir puliendo esto para ser lo más precisos posibles,
 @nattyco dale una revisada al error.

**Comment by nattyco** [comment]
Fixed, Error al seleccionar notificación en la wallet

**Comment by Luis-Fernando-Molina** [comment]
@furzy no debiera haber crash bajo ninguna circunstancia. El core lo debe atrapar y recuperarse,  como mucho cerrar la Wallet pero nunca caerse por. Completo.  Si la Wallet debe ser cerrada un hermoso pop up debe aparecer y explicar en un correcto inglés qué tuvimos un problema y que la APP se tuvo que cerrar,  pedir disculpas y decir que el problema se reportó automáticamente. Me sorprende que todavía esto no se maneje.

**Comment by sanro14** [comment]
La activación de notificación ya funciona perfecto
