### ISSUE TITLE
CBP - CUSTOMER - ERROR EN LA VISUALIZACION DE LA FOTO DEL PERFIL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#450]
### CBP

-----

##### Reporte de error: 

   *Al momento de crear el perfil se le agrego una foto de la galería y luego se intento colocar una foto tomada del emulado;pero no se visualiza al momento de crearlo.

![foto1](https://cloud.githubusercontent.com/assets/18584168/15717558/56498782-27f1-11e6-8734-433948591c17.png)

pero cuando se salva sale la foto tomada del emulador.

![psalvado](https://cloud.githubusercontent.com/assets/18584168/15717568/6267dde8-27f1-11e6-9192-6769f381b284.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/18584168/15715713/52b35ac4-27e9-11e6-9d12-92013c111e26.png)

**Comment by AdryCanonico** [comment]
@vlzangel

**Comment by MaviDavsa** [comment]
En mi caso pasa lo mismo! 

![sdfsdf](https://cloud.githubusercontent.com/assets/17273005/15729867/b3fd0b66-2831-11e6-8495-9107ff6b1edd.JPG)

Y posteriormente cuando se va a observar sale ovalado

![sfdsdf](https://cloud.githubusercontent.com/assets/17273005/15729870/bf4581c4-2831-11e6-8fed-4b5379046a08.JPG)

![google nexus 5 0](https://cloud.githubusercontent.com/assets/17273005/15729923/19571786-2832-11e6-9135-a4497e40e265.JPG)

**Comment by vlzangel** [comment]
Ok @AdryCanonico @MaviDavsa de esto me encargo yo.

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa Al igual que el issue #448, esto para la proxima version 16.7

**Comment by AdryCanonico** [comment]
@MaviDavsa @abicelis Se corrigió el error en la version 17 de CBP. Se puede cerrar el caso
