### ISSUE TITLE
LPW - LA GRAFICA NO TIENE FUNCION

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#451]
### LPW 

-----

##### Reporte de error: 

   *La gráfica no tiene función en la version 10, específicamente en el nexus 7. No se ve movimiento de la gráfica. 
   
![grafica](https://cloud.githubusercontent.com/assets/18584168/15728168/af9fde3e-2824-11e6-9581-dba7caefc933.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15728186/c66bc02e-2824-11e6-8a52-2c8aa5a67bcd.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  a que te referis con movimiento de la grafica?

**Comment by yolandayancel** [comment]
@nattyco 
Caso 451-  LPW 
![caso 451](https://cloud.githubusercontent.com/assets/17283358/15752599/aa546b36-28b8-11e6-8781-a0bbb771cf6e.png)
 V11
Nexus 4 5.0.0 .api 21 320 dpi
La gráfica se va moviendo a medida que se realizan las transacciones (si se gana o se pierde dinero)

**Comment by MaviDavsa** [comment]
@AdryCanonico Como queda este caso?

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 12 sigue ocurriendo el mismo error en el nexus 7. 

![grafica data](https://cloud.githubusercontent.com/assets/18584168/15793369/42aa3d44-29ad-11e6-9c6d-057aa529717d.png)


Como se puede ver en la capture no sale data en el emulador nexus 7(Emulador derecho), ni se ve movimiento, no sale punto tampoco.

**Comment by nattyco** [comment]
@AdryCanonico  en el nexus enviaste btc? cuanta ganancia obtuviste?

**Comment by nattyco** [comment]
@MaviDavsa  se cambio la grafica de la loss protected verificar como se ve ahora

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa En la versión 14de LPW a gráfica tiene animación, en el nexus 7. Se puede cerrar el caso.

![grafica nexus 7](https://cloud.githubusercontent.com/assets/18584168/15861558/7fdc45f4-2c96-11e6-95ef-049e0e2c1344.png)
