### ISSUE TITLE
Bitcoin Wallet_contacts_barra de buscar contacto muy grande

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#452]
### Bitcoin Wallet 

------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   * En la version 11, al ubicarme en la barra de buscar contacto para escribir un nombre, esta se pone de tamaño exagerado que no concuerda con el tamaño de la barra cuando no se da click en ella.
   
   ![screenshot_2016-06-01-20-13-43](https://cloud.githubusercontent.com/assets/17274154/15730340/8bfede7e-2835-11e6-9d93-15de0ca94d23.png)

![screenshot_2016-06-01-20-46-10](https://cloud.githubusercontent.com/assets/17274154/15730368/e5867740-2835-11e6-8eff-d2f4ae3cd09a.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by maydiamc** [comment]
este error  persiste en la version 15.2 @nattyco

**Comment by maydiamc** [comment]
persiste en laversion 17 @nattyco

**Comment by maydiamc** [comment]
persiste en la version 19.4 de CBP

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16588816/98cbd50c-429e-11e6-9445-54e7fc184b0c.png)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de la Bitcoin Wallet, este error no aparece en mi emulador

![cont](https://cloud.githubusercontent.com/assets/19353722/16698815/474830a4-451e-11e6-9da1-a277b13a94cc.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16698826/5234bf14-451e-11e6-86e5-becf50c6e68d.png)

**Comment by maydiamc** [comment]
se presenta el mismo problema en la version 20.1

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16699508/94bf1baa-4522-11e6-8559-182f501f229c.png)

**Comment by hcampos1984** [comment]
![image](https://cloud.githubusercontent.com/assets/20233469/16751555/9f544de6-47a8-11e6-8843-784e63879aa4.png)
![image](https://cloud.githubusercontent.com/assets/20233469/16751563/af14ddea-47a8-11e6-86dd-9cd9090062f3.png)


el error continua en la v20.4, el buscador cambia su tamaño al colocar algún caracter

**Comment by maydiamc** [comment]
este problema persiste en la version 20.5

**Comment by aabreu1** [comment]
resulto

**Comment by RubenSem** [comment]
En la versión 20.6 esta resuelto.
