### ISSUE TITLE
BROKER WALLET - SALE CORTADA LA PANTALLA DEL HOME

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#453]
##### Reporte de error: 

Al entrar al home de la broker se ve que la pantalla sale cortada.

![capture-20160601-184550](https://cloud.githubusercontent.com/assets/17262077/15730265/f10b17f2-2834-11e6-9fec-94f4125cadf8.png)

![capture-20160601-184621](https://cloud.githubusercontent.com/assets/17262077/15730267/f3082806-2834-11e6-845c-ef96d0d4c220.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.1.0

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by nelsonalfo** [comment]
No esta cortada, es que la parte de arriba cubre ese espacio. Si haces swipe hacia arriba se oculta parte de lo de arriba para mostrar completamente las pestañas

**Comment by abicelis** [comment]
@Gabymorillo @MaviDavsa Si, ese comportamiento es asi por diseno.

La idea es que uno pueda hacer swipe hacia arriba y se oculta el header (la grafica). Pruebenlo y cierren este issue que no es un issue :P

**Comment by MaviDavsa** [comment]
Cierto! @abicelis Pensé que ya lo había cerrado! :(
