### ISSUE TITLE
LPW - NO SE PUEDE ENTRAR EN LAS OPCIONES DEL MENU

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#454]
### LPW

-----

##### Reporte de error: 

   *Al momento de entrar en una opcion del menu no puedo utilizar otra opción. Pierden la funcion las otras opciones. La unica manera es cerrar la app de LPW y volver a entrar.

![drawer](https://cloud.githubusercontent.com/assets/18584168/15746545/d523bf28-28a0-11e6-831b-0c24bf60f91c.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Emulador

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15746598/07a6d23c-28a1-11e6-9a60-8088a51d7649.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15746599/07fda210-28a1-11e6-81a8-296ee3ba1296.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by yolandayancel** [comment]
@nattyco
Prueba caso 454 LPW V11
Nexus4 5.0.0 .api  21 320dpi
Al  entrar al Settings,  si  puedo utilizar las opciones.
![caso 454](https://cloud.githubusercontent.com/assets/17283358/15752409/be271f56-28b7-11e6-97d5-58a54f4b63b2.png)

**Comment by AdryCanonico** [comment]
@nattyco en la versión 13 persiste el error.

**Comment by AdryCanonico** [comment]
@nattyco en la version 15 se soluciono el error. :+1:
