### ISSUE TITLE
LPW_ Error Send to contact

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#455]
#### Nombre pantalla

------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Al intentar enviar BTC a un contacto me aparecio un error, y ya el contacto tenia el adress cargado, y esto no me permitio enviar los BTC y fue necesario retroceder y volver a entrar al formulario para poder enviar los BTC.
   
![screenshot_2016-06-02-11-50-24](https://cloud.githubusercontent.com/assets/17274154/15751948/d0f568ba-28b5-11e6-816c-7b7e4828fc62.png)

-------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini S4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
version 11 de la apk @nattyco @MaviDavsa

**Comment by nattyco** [comment]
@maydiamc  entraste a enviar los btc directamente desde el formulario o elegiste al contacto desde la lista de contactos?

**Comment by maydiamc** [comment]
Directamente desde el formulario

**Comment by nattyco** [comment]
@maydiamc y antes de ir a formulario de Send te fijaste que ya tenias el address?

**Comment by maydiamc** [comment]
si ya tenia el adress

**Comment by nattyco** [comment]
@maydiamc @MaviDavsa  verificar con la version 13 de la apk

**Comment by maydiamc** [comment]
solucionado este problema.! @nattyco

**Comment by MaviDavsa** [comment]
Perfecto Solucionado!
