### ISSUE TITLE
Community-Crypto Broker-Error no sale nombre de usuario

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#460]
### Connections y Notifications

-----

##### 

##### Reporte de error: 

   *Al ingresar a la community de crypto broker y dar clic en el menu sale el nombre de usuario y la foto normal como se puede observar:

![screenshot_78](https://cloud.githubusercontent.com/assets/5313326/15765820/dadc53a0-2902-11e6-8559-354e55a44ef2.png)

Pero al ingresar bien sea a la pantalla de connections o notifications no sale el nombre del usuario ni la foto, como se puede observar en las siguientes imagenes:

Connections:

![screenshot_79](https://cloud.githubusercontent.com/assets/5313326/15765867/5329ac2c-2903-11e6-9fc1-60d9c0857344.png)

Notifications:

![screenshot_77](https://cloud.githubusercontent.com/assets/5313326/15765877/68beac5e-2903-11e6-9b92-13926c9906cc.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5 
* Version de Android: 5.1.0

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  yo no manejo esta community

**Comment by MaviDavsa** [comment]
@nattyco Pensé que manejabas en General todas las Community's bella... Bueno @nelsonalfo

**Comment by IsbetVR** [comment]
En la versión 16.4 de CBP, en ninguna pantalla me sale identificado el perfil que he creado.
Google Nexus 5
Versión 5.1.0

![image](https://cloud.githubusercontent.com/assets/19142276/15828874/1a19e4a4-2bdf-11e6-961c-f287ca2ca6ba.png)

**Comment by Hernandezsmanu** [comment]
En mi caso ocurre lo mismo de @arosiopr, solo me muestra la foto de perfil en el crypto broker y en las otras pantallas muestra la imagen por defecto y no muestra el nombre.

Nexus 4
Android 5.0

**Comment by danielaporras** [comment]
El error persiste.

![screenshot_9](https://cloud.githubusercontent.com/assets/19656830/16048262/34d6b13e-321d-11e6-9460-0daa3b477d1a.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0

@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by AdryCanonico** [comment]
@abicelis en la version 17 CBP Persiste este error

**Comment by nelsonalfo** [comment]
en la version 17.2 se solvento ese problema

**Comment by arosiopr** [comment]
@MaviDavsa @sanro14 solucionado se puede cerrar

**Comment by nelsonalfo** [comment]
por favor cerrar el Issue

**Comment by yalayn** [comment]
Hola @MaviDavsa porfa ciérranos este issue :)
