### ISSUE TITLE
Identity-La imagen de perfil tomada por cámara no aparece

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#461]
##### Reporte de error: 

   *En LPW teniendo activa la camara de genymotion, al elegir como opción imagen desde "camara"  y ponerla, la imagen de perfil sale en blanco, es decir, no aparece y cuando le doy guardar me manda a la pantalla principal.

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/15780050/9527ab4a-2969-11e6-80b2-ecbad8db6770.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo:Google Nexus 5
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by maydiamc** [comment]
en mi dispositivo sucede el mismo error @nattyco 
Samsung Galaxy mini s4, version: 4.4.2

**Comment by RubenSem** [comment]
Cuando intento meterme en la cámara Me saca de la aplicación.

![screenshot_3](https://cloud.githubusercontent.com/assets/19676223/15782334/aaeb0288-2973-11e6-9dac-a2725bb66c1e.jpg)

**Comment by Hernandezsmanu** [comment]
Mi error es similar, al tratar de entrar a la galería para seleccionar la foto sale el siguiente aviso " Fermat isn't respondnig" y al seleccionar Ok o wait me saca de la aplicación. @nattyco 

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/15782667/fb492132-2974-11e6-8e09-1584146cf353.png)

**Comment by nattyco** [comment]
@RubenSem  @Hernandezsmanu  especifiquen la version de android en la cual les dio error.

**Comment by RubenSem** [comment]
Listo @nattyco subi el captured.

**Comment by danielaporras** [comment]
En la  version 15.1 de LPW persiste el error, no guarda la imagen tomada de cámara y se sale de la aplicación.

![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/15915084/2029f140-2db0-11e6-8526-774254ab7168.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/15915087/24de36e2-2db0-11e6-82c1-3183d852d6ae.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/15915088/296976ea-2db0-11e6-96ba-1310b75f2b45.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/15915089/2db56344-2db0-11e6-9169-36407ef0427d.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0

@MaviDavsa 
@nattyco

**Comment by danielaporras** [comment]
Version 16.1 aun sale el error.

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/15967861/4c97e234-2ef3-11e6-86a7-f32459de4d1c.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/15967864/54540b1a-2ef3-11e6-90d9-4eda4137afde.png)


Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 461 LPW V16.2
Nexus 4 5.0.0 320dpi
Ocurre lo mismo no deja usar la camara.
![caso 461](https://cloud.githubusercontent.com/assets/17283358/15969878/c5805e12-2efb-11e6-9820-e0a3c77c7f00.png)

**Comment by maydiamc** [comment]
en mi dispositivo, con la version 17, tampoco coloca la foto de la camara e inmediatamente se me congela la apk y debo reiniciarla para seguir usandola @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025808/9053018c-3193-11e6-9634-1163a6fd8813.png)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de CBP no sucede este error

![ft](https://cloud.githubusercontent.com/assets/19353722/16687563/66b3b5c6-44e7-11e6-850a-cc867b308306.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16687570/70e0c9b2-44e7-11e6-8e49-69c07edb245a.png)

**Comment by MaviDavsa** [comment]
Se soluciono, el error desde mi teléfono físico... 

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16688527/74a8ec6e-44ec-11e6-9c04-b6b5e84d4ca5.jpg)

**Comment by sanro14** [comment]
Solucionado.
