### ISSUE TITLE
LPW- La aplicación se detiene

### ISSUE THREAD

**Issue by RubenSem** [Fermat-ORG/beta-testing-program#462]
### Template issue error report

LPW- Se Detiene la aplicación

-----

##### Reporte de error: 

  Me creo el perfil, Trato de meterme en LPW y la aplicación se detiene mas sin embargo puedo usar la aplicación unos segundos y luego fermat no responde.

![screenshot_2](https://cloud.githubusercontent.com/assets/19676223/15780483/b31ec1d6-296b-11e6-9bf4-b0460fe9281a.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/19676223/15780484/b3251482-296b-11e6-98b2-529e5063201c.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/15780486/b33a3862-296b-11e6-81a5-b63fb746caac.jpg)

------

#### Dispositivo desde donde se realizo la prueba

![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/15780341/06dbf678-296b-11e6-8524-5ee062112d1f.jpg)

**Comment by RubenSem** [comment]
@nattyco @MaviDavsa

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 07-06-2016
Caso 462 LPW V14
Nexus 4 5.0.0 Api 21 320dpi
En este emulador no ocurre lo mismo. Puedo  entrar  en la  LPW y la aplicación no se  detiene.
![caso 462](https://cloud.githubusercontent.com/assets/17283358/15866143/405e7ce2-2ca7-11e6-8000-c6ae754fff15.png)

**Comment by yolandayancel** [comment]
Prueba 10-06-2016
Caso 462 LPW V16.2
Nexus 4 5.0.0 Api 21 320dpi
En este emulador no ocurre lo mismo. Puedo entrar en la LPW.

**Comment by maydiamc** [comment]
en mi dispositivo, con la version  17, esto no sucede @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16026761/918f62d2-319a-11e6-969b-990d294522e8.png)

**Comment by RubenSem** [comment]
Solucionado en la nueva versión por favor cerrar caso @MaviDavsa

**Comment by MaviDavsa** [comment]
Solucionado!
