### ISSUE TITLE
CBP-Cryto Broker User- Negotiation Detail- no funciona botón de (SEND) enviar

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#463]
#### Nombre pantalla
Negotiation Details

##### Reporte de error: 

   *1- Estando en la pantalla de Negotiation Details aceptamos cada uno de los items de la negociación
![error no deja enviar la negociacion 1](https://cloud.githubusercontent.com/assets/17283358/15784226/64671592-297b-11e6-9e07-6dba3ef3dd34.png)

   2- Al terminar de aceptarlas todas pise el botón de SEND pero no funciona.
![error no deja enviar la negociacion 2](https://cloud.githubusercontent.com/assets/17283358/15784280/a3a948d8-297b-11e6-9c4e-a4a53db073de.png)

   3- Despues de intentar varias veces sale este cuadro
![error no deja enviar la negociacion 3](https://cloud.githubusercontent.com/assets/17283358/15784460/623ecee4-297c-11e6-81ec-01616c04ee8a.png)

  4- Se sale de la apk y hay que ingresar nuevamente y al entrar nuevamente a la Crypto Broker e ingreso a la negociación realizo nuevamente los pasos anteriores y ocurre lo mismo.
![error no deja enviar la negociacion 4](https://cloud.githubusercontent.com/assets/17283358/15784564/de96d5fe-297c-11e6-83a9-a67d6c297066.png)
  5-Se sale de la apk.
![error no deja enviar la negociacion 5](https://cloud.githubusercontent.com/assets/17283358/15784876/46f466c4-297e-11e6-8fa2-8678cd6d597b.png)

CBP Versión 16.2 03-06-2016

#### Dispositivo desde donde se realizo la prueba

480dpi
![nexus](https://cloud.githubusercontent.com/assets/17283358/15784741/aa84f38a-297d-11e6-94d3-1734a29565cd.png)

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by yalayn** [comment]
Hola @yolandayancel y @MaviDavsa. Yo @yalayn revisare este issue.

**Comment by yolandayancel** [comment]
@nelsonalfo 
Prueba 10-06-16
Caso 463 CBP V 16.5
Nexus 5 5.0.0
Resuelto. permite enviar la negociación. Cerrar el caso
![caso 463](https://cloud.githubusercontent.com/assets/17283358/15982310/f04fdf3a-2f4d-11e6-83d8-c80e5ff4c7c2.png)

**Comment by maydiamc** [comment]
en la version 17.1, al realizar una negociacion el boton send funciono, pero al presionarlo me saco automaticamente de la aplicacion y dio el erro de Recovering from System Error, pero al entrar a revisar la negociacion esta se habia enviado @nelsonalfo 
nota: no me dio tiempo de tomar el capture de pantalla del error

dispositivo fisico
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16120717/56d96234-33aa-11e6-86db-e3b92567752d.png)

**Comment by yolandayancel** [comment]
@IsbetVR 
Prueba 29-06-2016
Caso      CBP V 18.4
Nexus 5 5.0.0
Solucionado lo del boton SEND
En prueba de hoy se usó el botón del send el cual funcionó. No pude tomar captura( no hemos podido realizar otra negociación)pero les dejo el logcat

![caso 463](https://cloud.githubusercontent.com/assets/17283358/16455243/693397fa-3ddd-11e6-8e29-3205b7611e8b.png)
[logcatcaso 463.txt](https://github.com/Fermat-ORG/beta-testing-program/files/339439/logcatcaso.463.txt)
