### ISSUE TITLE
LPW -  Error de hora y hora desorganizada.

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#464]
No ordena las transacciones por hora en que fueron realizadas y en algunos casos muestra la hora incorrecta.

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/15785213/0b5491aa-2980-11e6-9496-1557eb44d1dc.png)

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by nattyco** [comment]
@maydiamc @Hernandezsmanu  como es lo de que muestra la hora incorrecta?

**Comment by MaviDavsa** [comment]
@nattyco Me imagino que es incorrecta! porque no es la hora que tiene el emulador! O no se si me equivoco! Y lo de que lo ordena mal pues si!

**Comment by AdryCanonico** [comment]
@nattyco En mi caso en ambos emuladores con la version 13 da la hora incorrecta
Da la misma hora que cuando llegaron la BTC.

![hora mensaje](https://cloud.githubusercontent.com/assets/18584168/15795377/c490dfe0-29ba-11e6-95d0-73119ed3a3d9.png)

Dispositivo;

![nexus 4 1 1](https://cloud.githubusercontent.com/assets/18584168/15795382/cf46e1e6-29ba-11e6-9065-780b66211410.png)

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15795381/cf45fb0a-29ba-11e6-9b84-2e4079bc7143.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 07-06-2016
Caso 464 LPW V14
Nexus 4 5.0.0 Api 21 320dpi
En este emulador ocurre lo mismo: No ordena las transacciones por hora en que fueron realizadas
![caso 464](https://cloud.githubusercontent.com/assets/17283358/15865941/8c161132-2ca6-11e6-9370-cf2cb70399cf.png)

**Comment by MaviDavsa** [comment]
En mi tlf este error persiste!!! No ordena las transacciones en el orden en el que fueron realizadas

![screenshot_2016-06-08-21-07-17](https://cloud.githubusercontent.com/assets/17273005/15917246/bbd67028-2dc4-11e6-8f2e-90cb1d241519.jpg)
![screenshot_2016-06-08-21-07-20](https://cloud.githubusercontent.com/assets/17273005/15917247/bbd98894-2dc4-11e6-99be-758383f6b969.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15917257/d581c720-2dc4-11e6-9829-41df8c6deb7a.jpg)

**Comment by nattyco** [comment]
@MaviDavsa  @Hernandezsmanu corregido en la version 15.2 de la apk

**Comment by maydiamc** [comment]
corregido este problema en la version 15.2 @nattyco 

Samung Galaxy 
mini s4
4.4.2

![screenshot_2016-06-09-10-05-59](https://cloud.githubusercontent.com/assets/17274154/15932481/bcb8e118-2e25-11e6-9bfe-57d5a68c7f04.png)

**Comment by MaviDavsa** [comment]
En mi teléfono esta más corregido... 

![screenshot_2016-06-09-10-04-38](https://cloud.githubusercontent.com/assets/17273005/15932634/4bf0f00a-2e26-11e6-83a6-93d82de3ed30.jpg)
![screenshot_2016-06-09-10-04-31](https://cloud.githubusercontent.com/assets/17273005/15932635/4c08dcba-2e26-11e6-8cbc-c1bc3c664538.jpg)

Dispositivo...

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15932668/66b9bb6a-2e26-11e6-9689-2382b81fa605.jpg)

**Comment by Hernandezsmanu** [comment]
En la version 15.2 ya se corrigio, porfavor cerrar el caso. @MaviDavsa @nattyco 

![screenshot_7](https://cloud.githubusercontent.com/assets/5313335/15936019/42829db8-2e33-11e6-9dc4-5c64c887aedf.png)

**Dispositivo donde se realizo la prueba:**

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/15936072/69b74848-2e33-11e6-9ade-f6f81a8c72d5.png)

**Comment by MaviDavsa** [comment]
Solucionado
