### ISSUE TITLE
LPW_error en el menu transactions

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#465]
##### Reporte de error: 

   * En el menu transactions, en las pantallas de sent y received, se mostraban las transaciones realizadas y recibidas, al pasar de cuatro transacciones cada una, esta se pusieron en blanco y ya no se vio ninguna, ni las 4 primeras, ni las nuevas que llegaban.
   
![screenshot_2016-06-03-11-31-18](https://cloud.githubusercontent.com/assets/17274154/15785594/e7ff5c60-2981-11e6-999f-88833370e12b.png)
![screenshot_2016-06-03-11-31-09](https://cloud.githubusercontent.com/assets/17274154/15785595/ed13907c-2981-11e6-9547-d56d58cfd2c4.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa version 12 de la apk

**Comment by maydiamc** [comment]
solucionado este error.! @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!

**Comment by maydiamc** [comment]
reabrir el caso @MaviDavsa en la version 15 esta sucediendo este error @nattyco

**Comment by MaviDavsa** [comment]
En mi caso este Issues esta arreglado, todo se veia bien! 

![screenshot_2016-06-08-19-52-59](https://cloud.githubusercontent.com/assets/17273005/15917225/82f7c0cc-2dc4-11e6-8a38-10f378a8225b.jpg)
![screenshot_2016-06-08-19-52-26](https://cloud.githubusercontent.com/assets/17273005/15917226/831d4fcc-2dc4-11e6-92eb-add30945c713.jpg)


![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15917233/9cb8dd84-2dc4-11e6-820a-5aa0ea68f5b7.jpg)

**Comment by maydiamc** [comment]
solucionado este problema.! @MaviDavsa  @nattyco

**Comment by maydiamc** [comment]
Reabrir el caso ya que este error se mostro luego de un rato de usar la aplicacion, al principio funciono bien y comente el caso para cerrarlo, pero hace unos minutos volvio a mostrar el error @nattyco @MaviDavsa 

![screenshot_2016-06-09-11-18-28](https://cloud.githubusercontent.com/assets/17274154/15935349/b27abb1c-2e30-11e6-8608-f7504413423e.png)

Samsung Galaxy 
Mini s4
4.4.2

**Comment by IsbetVR** [comment]
En la LPW versión v16 está sucediendo lo siguiente: realicé un envío y no me lo registró en "transactions" (Pantalla 1) 

##### Pantalla 1

![screenshot_64](https://cloud.githubusercontent.com/assets/19142276/15949602/cf05cb14-2e76-11e6-8ed8-5deb32184ab3.jpg)




##### Dispositivo de prueba:

* [x] Emulador
* HTC One X
* Versión de android 4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15949624/f5eda7c4-2e76-11e6-8585-717407089bc0.jpg)

**Comment by maydiamc** [comment]
persiste el error en la version 16.2 @nattyco

**Comment by yolandayancel** [comment]
Prueba 10-06-2016
Caso 465 LPW V16.2
Nexus 5 5.0.0 480dpi
En la versión, no ocurre este error.

**Comment by maydiamc** [comment]
en la version 17 se soluciono este error @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
