### ISSUE TITLE
LPW_ error en add fermat user

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#466]
##### Reporte de error: 

   * en la pantalla de add fermat user, al seleccionar e intentar agregar un contacto que me habia enviado la solicitud, este me arrojaba un error (intentelo mas tarde)  y no me permitia agregarlo, fue necesario reiniciar la aplicacion para poder hacerlo.
   
![screenshot_2016-06-03-10-59-39](https://cloud.githubusercontent.com/assets/17274154/15785753/c2085a4c-2982-11e6-853f-a0fcf02fd6ce.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: samsung galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa version 12 de la apk

**Comment by nattyco** [comment]
@maydiamc  cuando tocaste el registro no te aparecio el icono para hacer el add?

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 07-06-16
Caso 466 LPW V14
Nexus 4 5.0.0 Api21 320dpi
En la pantalla de add fermat user, no ocurre lo mismo que reportaron. En este emulador  se  selecciona y agrega  un contacto que  ha  enviado la solicitud.
![caso 466](https://cloud.githubusercontent.com/assets/17283358/15865669/7c2d9ad4-2ca5-11e6-8b80-12d556f8665b.png)

**Comment by MaviDavsa** [comment]
Solucionado!
