### ISSUE TITLE
LPW . BOTONES DE POP ADD CONTACT HELP NO ESTAN CENTRADOS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#467]
### LPW

-----

##### Reporte de error: 

   *En el nexus 7 no se ven centrados los botones; 

![botones](https://cloud.githubusercontent.com/assets/18584168/15795651/63573460-29bd-11e6-8bf7-d7f3ada23468.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 7](https://cloud.githubusercontent.com/assets/18584168/15795653/71b73dca-29bd-11e6-8cf2-a0987d82d933.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 467
LPW V14  07-06-16
Nexus 4 5.0.0 Api 21 320dpi
*Se ven centrados los botones
![caso 467](https://cloud.githubusercontent.com/assets/17283358/15863923/b3a51124-2c9e-11e6-8d93-296c990792ee.png)

**Comment by MaviDavsa** [comment]
@nattyco Mi amor a mi me parece mucho mejor! Lo único que le cambiaría es que los cuadros naranja y azul están muy cuadrados, yo creo que si lo pones un poco curvo se ve más estilizado...

**Comment by MaviDavsa** [comment]
@AdryCanonico Esto por ser Tablets lo vamos a cerrar, como te había comentado!
