### ISSUE TITLE
LPW . BOTONES DE POP ADD CONTACT HELP MUY GRANDES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#468]
### LPW

-----

##### Reporte de error: 

   *los botones en la versión 4.1, 4.2 de Android se ven muy grandes.

![boto2](https://cloud.githubusercontent.com/assets/18584168/15795687/bf165538-29bd-11e6-8b1e-b377f0479c7a.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4 1 1](https://cloud.githubusercontent.com/assets/18584168/15795693/d0ca00f4-29bd-11e6-90c6-ffbe8a6e77e2.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  @MaviDavsa  la pantalla que pusiste se ve bien para mi, solo la pantalla de la tablet hay que ajustar (que no corresponde a este reporte)

**Comment by MaviDavsa** [comment]
Si en el tlf yo creo que se ve bien también! @AdryCanonico Facilitame las versiones en la que hay mayores errores gráficos en cuanto a este apk por favor!

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco yo no opino lo mismo, los botones se ven muy grandes en el teléfono.
Las versiones que mas errores gráficos tienen son 4.1, 4.2 y las tablets. 

Me parece que la aplicación debería de verse uniforme en todas las versiones.

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 468
LPWV14 07-06-16
Nexus 4 5.0.0 Api 21 320dpi
Ocurre lo mismo. los botones se ven grande.
![caso 468](https://cloud.githubusercontent.com/assets/17283358/15862879/de917d5e-2c9a-11e6-934a-4a76817b0752.png)

**Comment by MaviDavsa** [comment]
@nattyco Mi amor a mi me parece mucho mejor! Lo único que le cambiaría es que los cuadros naranja y azul están muy cuadrados, yo creo que si lo pones un poco curvo se ve más estilizado...

**Comment by arosiopr** [comment]
se sigue montando el checkbox sobre el texto en la versión 16 de la apk

![screenshot_2016-06-09-16-56-48](https://cloud.githubusercontent.com/assets/5313326/15949831/2754c05c-2e74-11e6-933d-f89852bd1431.png)

## **Dispositivo**

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/15949840/3484be26-2e74-11e6-9e69-b8e843b8cb31.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version de CBP 18.3 quedo muy bien eliminar el add de los botones. En el caso de probarlo en el Telefono samsung 4.4.2 se ve bien 

![screenshot_2016-06-25-19-22-21](https://cloud.githubusercontent.com/assets/18584168/16385267/ea9c0e14-3c55-11e6-8042-ed95b444360b.png)


Pero en el Nexus 4.   5.1 , 320 dpi. El texto dentro de los botones esta muy grande y paga a los bordes. 


![screenshot_1](https://cloud.githubusercontent.com/assets/18584168/16385343/3859c420-3c56-11e6-8879-c2d8bff6f193.png)

**Comment by Gabymorillo** [comment]
En la versión 18.8 no presenta ese error.
 
![screenshot_2016-07-01-11-02-22](https://cloud.githubusercontent.com/assets/17262077/16525666/486a879a-3f77-11e6-91b1-1be3b4af9e9a.png)

**Comment by nattyco** [comment]
@AdryCanonico verificar este caso nuevamente
