### ISSUE TITLE
CBP-Crypto Broker - Sin limite de caracteres en campos de Create Location

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#469]
### CBP

-----

##### Reporte de error: 

   *En la sección Create Location no se tienen limites de caracteres en los campos de registro “Location", "Zip/Postal Code", "State/Province”," Address line 1" y "Address line 2".

![none](https://cloud.githubusercontent.com/assets/18584168/15796069/c92479ca-29c1-11e6-86e2-841b8ca3b252.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15796079/dfa9e6b2-29c1-11e6-999d-7d4d7c8bebb3.png)

**Comment by AdryCanonico** [comment]
@ABICELIS

**Comment by yalayn** [comment]
Yo @yalayn Corregí este issue. Se aplicaron las mismas correcciones que al formulario del Setting Location de la Customer Wallet. Debe estar disponible para la próxima versión de la app.
![captura de pantalla de 2016-06-04 17 49 03](https://cloud.githubusercontent.com/assets/4664287/15802383/e86cf164-2a79-11e6-96af-425661e4c7fe.png)

**Comment by AdryCanonico** [comment]
@yalayn Gracias! Estoy al pendiente para probar los cambios.

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  469   CBP V 16.7
Nexus 4 5.0.0
En este emulador, NO ocurre lo reportado , hay un limite como lo muestra la foto
![caso 469](https://cloud.githubusercontent.com/assets/17283358/16101081/b50235da-332c-11e6-9257-7b427f9963c2.png)

[logcat caso  469.txt](https://github.com/Fermat-ORG/beta-testing-program/files/317391/logcat.caso.469.txt)

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa  En la version 17 CBP ya esta corregido, Se puede cerrar el caso. :+1:
