### ISSUE TITLE
Bit Coin Wallet_Back desde el Identity Manager

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#47]
### Template issue error report

Bit Coin Wallet

#### Nombre pantalla

Identity Manager

### Bitcoin Wallet 

-----

##### Home

-  Pantalla de Transacciones recibidas (Es la de la derecha)
-  Pantalla de Transacciones enviadas (Es la de la izquierda)
-  Balance (es la circunferencia con la cantidad de bitcoin)
-  Pop up de bienvenida
-  Pop up de ayuda

##### Reporte de error: 

   *En la pantalla de Identity Manager al salvar los cambios de los datos no me regresa al menú o a la pantalla de inicio, la única manera de salir de **Identity Manager** es salir de la aplicación **Bit Coin Wallet**, también la imagen del usuario cuando la cambio, salgo de la aplicación y al regresar no sale la imagen, como si no la hubiese cambiado nunca.

![screenshot_2016-03-01-10-56-13](https://cloud.githubusercontent.com/assets/17273349/13431659/7c8c3c0c-df9c-11e5-8296-3386d1235e15.png)

------
##### Settings

-  Pantalla de envio
-  Pantalla de recibiento

##### Reporte de error: 

   *En la pantalla Settings en la opción Select Network luego de ver las opciones desplegadas en el pop up, al regresar o salir del pop up, el teclado de mi telefono se despliega y no lo puedo cerrar, solo desplegando el menú baja el teclado o saliendo de la aplicación.

![screenshot_2016-03-01-11-16-57](https://cloud.githubusercontent.com/assets/17273349/13432583/79387012-dfa0-11e5-8090-b3df6667ecb4.png)

   
------

**Comment by augusto-ponce** [comment]
@furszy @acostarodrigo

**Comment by adryx83** [comment]
Permanecen los mismos errores de la pantalla de identity manager todavia no se devuelve al home o al menu, y en settings sigue desplegando el teclado. Probado con Android 4.4.2

**Comment by nattyco** [comment]
@adryx83  @augusto-ponce  Sobre la sub app identity y lo que reportaron de volver al punto desde la cual se la llamo, para cambiar los datos del usuario, en esta version no existe esa funcionalidad.
Cuando desde la wallet se vaya a cambiar los datos de la identidad al volver atras para salir volvera al desktop.

**Comment by Luis-Fernando-Molina** [comment]
>Reporte de error:

En la pantalla de Identity Manager al salvar los cambios de los datos no me regresa al menú o a la pantalla de inicio, la única manera de salir de *Identity Manager** es salir de la aplicación Bit Coin Wallet, también la imagen del usuario cuando la cambio, salgo de la aplicación y al regresar no sale la imagen, como si no la hubiese cambiado nunca.

>Reporte de error:

*En la pantalla Settings en la opción Select Network luego de ver las opciones desplegadas en el pop up, al regresar o salir del pop up, el teclado de mi telefono se despliega y no lo puedo cerrar, solo desplegando el menú baja el teclado o saliendo de la aplicación.



@augusto-ponce por cada error encontrado se debe hacer un Issue nuevo, no un nuevo comentario en un issue. Fijate de que sea así por favor.

>@adryx83 @augusto-ponce Sobre la sub app identity y lo que reportaron de volver al punto desde la cual se la llamo, para cambiar los datos del usuario, en esta version no existe esa funcionalidad.
Cuando desde la wallet se vaya a cambiar los datos de la identidad al volver atras para salir volvera al desktop.

@nattyco que no esté así ahora en esta versión no quiere decir que esté bien. En general el comportamiento de las aplicaciones moviles es como lo describe @adryx83 , con lo cual hay que hacer que funcione igual que como la gente está acostubrada en las aplicaciones móviles. Gracias.

**Comment by Luis-Fernando-Molina** [comment]
Ante la duda de como deben funcionar o estar organizada las APPs por favor referirse a los criterios de diseño de app androir en http://developer.android.com/design/get-started/principles.html

@augusto-ponce por favor compartí esa pagina con el resto de la gente haciendo el testing.

**Comment by augusto-ponce** [comment]
@Luis-Fernando-Molina ya comparti el articulo con el grupo Beta Testin muy interesante. 
Con respecto al tema de generar un nuevo Issue para cada caso me parece bien, lo único que les dije a las chicas del equipo es que sigan sus Issues para ver si se resuelven y en caso de no haber sido resueltos que no generen un nuevo Issue sobre ese problema sino mas bien que comenten dentro de ese mismo Issue ( que no se resolvió, que sigue arrojando ese problema la aplicación ). 
Espero haber sido claro

**Comment by augusto-ponce** [comment]
@adryx83  Aquí en este Issue hay dos reportes, uno que es experiencia de usuario y otros que son bag. Me interesa saber si los  bags estan resueltos.
Te copio tus reportes y lo que a mi entender son bags y lo que es experiencia del usuario.
Espero tu respuesta

Reporte de error:
BAG
*En la pantalla Settings en la opción Select Network luego de ver las opciones desplegadas en el pop up, al regresar o salir del pop up, el teclado de mi telefono se despliega y no lo puedo cerrar, solo desplegando el menú baja el teclado o saliendo de la aplicación.

BAG
también la imagen del usuario cuando la cambio, salgo de la aplicación y al regresar no sale la imagen, como si no la hubiese cambiado nunca.

EXPERIENCIA DEL USUARIO
En la pantalla de Identity Manager al salvar los cambios de los datos no me regresa al menú o a la pantalla de inicio, la única manera de salir de *Identity Manager** es salir de la aplicación Bit Coin Wallet

**Comment by adryx83** [comment]
@augusto-ponce Según leo el único de los casos que describí allí que esta solucionado es este: 

BAG
también la imagen del usuario cuando la cambio, salgo de la aplicación y al regresar no sale la imagen, como si no la hubiese cambiado nunca.

De resto los otros casos siguen aún sin resolver aunque me parecen mas de Experiencia de Usuario que errores de la App,

**Comment by augusto-ponce** [comment]
Bueno Adri, cuando puedas entonces lo que vamos a hacer es desglosar este caso en los dos casos que quedaran abiertos ! Por una cuestion de orden . Este issue lo vamos a cerrar una vez que voy hayas  hecho eso. Creo que es un error el hecho que no te permita poner tu foto y no una experiencia del usuario, de todas formas lo desglosemos y después discutimos bien a donde queda.

**Comment by adryx83** [comment]
Ok entiendo el de la foto lo puedes cerrar quedarían los otros dos entonces

**Comment by MaviDavsa** [comment]
@nattyco Este lo voy a dejar porque aun no esta el botón de regresar al menú sin que te saque de la plataforma de la Bitcoin Wallet!
