### ISSUE TITLE
CBP-Crypto Broker - Create Location sin pais

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#470]
### CBP

-----

##### Reporte de error: 

   *Cuando se va agregar el pais de ubicacion aparece la palabra NONE

![none](https://cloud.githubusercontent.com/assets/18584168/15796128/a4bad286-29c2-11e6-9519-525dd740e403.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/18584168/15796129/a4bfaa72-29c2-11e6-95fc-0e47cbe82e63.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15796135/baeec454-29c2-11e6-9bbc-b480326611ff.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by abicelis** [comment]
@AdryCanonico en la version 16.7 estara este fix!
 PD: no la 16.6 de ahorita, la 16.7!

**Comment by JeanFranco498** [comment]
De igual forma a mi me permite crear location sin elegir pais
en la V16.6
![image](https://cloud.githubusercontent.com/assets/19807906/16064198/f6696ac2-326c-11e6-9d70-98ecde188dd2.png)

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  470   CBP V 16.7
Nexus 4  5.0.0
En este emulador al crear la localización no aparece como pais el NONE. Como dato curioso al abrir está colocado Argentina como país, se lo dejo y no relleno los campo y le doy a SAVE y crea la localización.
![caso 470](https://cloud.githubusercontent.com/assets/17283358/16100802/b99a3a0e-332a-11e6-97d5-d49a4db53d40.png)

[logcat caso 470..txt](https://github.com/Fermat-ORG/beta-testing-program/files/317381/logcat.caso.470.txt)

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la version 17 ya se corrigio. Se puede cerrar el caso :+1: 

![location](https://cloud.githubusercontent.com/assets/18584168/16121181/1ac0eeb4-33ac-11e6-960b-25f14baa2d53.png)
