### ISSUE TITLE
CBP - NEGOTIATON DETAILS SIN LIMITES DE CARACTERES

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#471]
### CBP

-----

##### Reporte de error: 

   *Al momento de agregar caracteres al user note este no muestra limites 

![boton user notes](https://cloud.githubusercontent.com/assets/18584168/15796228/41893ef8-29c4-11e6-8a01-45efb92aaa33.png)

y si se agregan muchos se pierden los botones de cancel y accept

![user note](https://cloud.githubusercontent.com/assets/18584168/15796243/82a043d2-29c4-11e6-86fb-1f3018d8c573.png)

 y al momento de aceptar corta el mensaje

![fotos negotiation detais](https://cloud.githubusercontent.com/assets/18584168/15796270/ef90870e-29c4-11e6-82e4-5bc8f229ec6c.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15796240/6db23a02-29c4-11e6-89b9-ead464275715.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by MaviDavsa** [comment]
@AdryCanonico Este por ser el lugar de notas en el que los custumer van a establecer x acuerdo no creo que debería llevar un limite como tal... @abicelis trata de imaginar un mensaje estandar... No lo se 200 o 300 caracteres!?

**Comment by AdryCanonico** [comment]
@MaviDavsa yo opino máximo 200 por el espacio de la aplicación.

**Comment by yalayn** [comment]
Yo @yalayn estaré trabajando en este issue.

**Comment by yalayn** [comment]
Hola  @AdryCanonico y @MaviDavsa. Se aplico un limite de 300 caracteres y un contador al pie del text que muestra cuantos caracteres restan. Se puede modificar la cantidad limite a los 200. A continuación les muestro dos anexos con las modificaciones aplicadas. Esto debería estar disponible para la próxima versión de la app.
![errornote1](https://cloud.githubusercontent.com/assets/4664287/15833939/bca55d8a-2bf2-11e6-9342-c828472eda1c.png)
![errornotecustomer2](https://cloud.githubusercontent.com/assets/4664287/15833957/cfb6604a-2bf2-11e6-835b-e66fba07cd12.png)

**Comment by AdryCanonico** [comment]
Gracias @yalayn estoy al pendiente de cuando la tengas para verificar el caso.

**Comment by yalayn** [comment]
Ok @AdryCanonico chevere, estamos a la orden ;) 
Saludos..

**Comment by yalayn** [comment]
Hola @AdryCanonico, en la versión 16.5 esta la corrección de este bug. Saludos.

**Comment by AdryCanonico** [comment]
@yalayn @MaviDavsa  en la version 17 CBP se corrigió. Quedo super bien! :+1:  Se puede cerrar el caso. 

![screenshot_1](https://cloud.githubusercontent.com/assets/18584168/16121254/69a2f8c4-33ac-11e6-92b2-72389fd4c452.png)

**Comment by yalayn** [comment]
Fino @AdryCanonico 😉 . Saludos.
