### ISSUE TITLE
Bitcoin Wallet- Setting-send to Loss Protected Wallet

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#472]
##### Reporte de error: 

   *Desde "Bitcoin Wallet" para enviar dinero a "Loss Protected Wallet" al poner la cantidad de BTC a enviar deja poner 79 dígitos. 
   

#### Dispositivo desde donde se realizo la prueba
![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/15796353/178176be-29c6-11e6-8dd7-05d0ba1a297f.png)

* Marca:Genymotion
* Modelo:Google nexus 4
* Version de Android: 4.4.4

**Comment by danielaporras** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@danielaporras Y te deja hacer el envió o te sale algún error!?  @nattyco

**Comment by danielaporras** [comment]
@MaviDavsa No hace el envio y sale este error.

![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/15796486/309e8d4c-29c8-11e6-8d38-84678cfc9dcc.png)

**Comment by MaviDavsa** [comment]
@nattyco Okay si te deja meter tantos dígitos debería haber un pop en donde diga que no se puede hacer el envió porque obviamente no tienes fondos suficientes! Aunque esa cantidad de dígitos me parece alta bella!

**Comment by nattyco** [comment]
@danielaporras  @MaviDavsa Corregido en la version 14 de la apk, se limitaron los caracteres

**Comment by maydiamc** [comment]
solucionado este error, se limitaron los caracteres a 11 y ya no muestra el error.! @nattyco

**Comment by MaviDavsa** [comment]
Perfecto Solucionado!
