### ISSUE TITLE
Bitcoin Wallet-Settings-Send Bitcoins To Loss Protected Wallet-Error al enviar BTC

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#473]
### Bitcoin Wallet 

------
##### Reporte de error: 

   *Al ingresar en settings en la opcion Send Bitcoins To Loss Protected Wallet y dar clic en el boton send salio el siguiente error, y tenia 50 BTC disponibles:

![screenshot_80](https://cloud.githubusercontent.com/assets/5313326/15796284/2d912040-29c5-11e6-885c-a898b5757ecc.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by arosiopr** [comment]
@nattyco

**Comment by danielaporras** [comment]
Sucede lo mismo.
Dispositivo desde donde se realizo la prueba
![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15796451/7f243062-29c7-11e6-86ab-3388c01a6a7c.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/15796453/88784d42-29c7-11e6-9d6e-09674fedda29.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/15796457/94599ba2-29c7-11e6-95d4-ddc035bb45f0.png)


Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.4.4

**Comment by kmiloxvii** [comment]
Presento el mismo error 
Dispositivo de prueba

![phone](https://cloud.githubusercontent.com/assets/2491042/15796485/bbfe32f0-29d4-11e6-9f65-2fd02fa24e5b.png)

**Comment by maydiamc** [comment]
este error fue solucionado.! @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
