### ISSUE TITLE
CBP - CRYPTO BROKER - FOTOS CON FORMA DIFERENTES EN NEGOTIATION DETAILS 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#474]
### CBP

-----

##### Reporte de error: 

   *Se visualizan fotos de diferentes formas en la pantalla de negotiation details.
estas cambian si son tomadas de galeria: 

![foto redonda de la ficha](https://cloud.githubusercontent.com/assets/18584168/15796473/ce7ea0a2-29c7-11e6-9eb9-81ff9363726c.png)

o de la Cam del Emulador:

![foto de la ficha](https://cloud.githubusercontent.com/assets/18584168/15796475/e0a84b2a-29c7-11e6-875d-8db2dfbacca4.png)
   

![grafica](https://cloud.githubusercontent.com/assets/18584168/15796491/4c472720-29c8-11e6-88b7-6e2e7f6142e0.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15796489/43887b70-29c8-11e6-88d3-ef568d8880c8.png)

**Comment by AdryCanonico** [comment]
@vlzangel

**Comment by vlzangel** [comment]
Yo @vlzangel me encargo de esto.

**Comment by yalayn** [comment]
Hola @AdryCanonico, Ya se corrigió este issue. Debe estar disponible en las próximas versiones.
Saludos.

**Comment by yalayn** [comment]
Buenas tardes, Se acaba de subir la versión 17.4, que tiene disponible esta corrección. Si no se las han facilitado pronto lo estarán haciendo.
Saludos.

**Comment by MaviDavsa** [comment]
@AdryCanonico Esto tambien bella!

**Comment by AdryCanonico** [comment]
@vlzangel @MaviDavsa en la versión 18 CBP se corrigió el error. Se puede cerrar el caso. :+1:
