### ISSUE TITLE
CBP - MEJORAS EN LA GRAFICA

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#475]
### CBP

-----

##### Reporte de error: 

   *Seria bueno una gráfica un poco mas amigable para el usuario, con datos, fechas y algo mas de diseño. 

No se puede apreciar bien su significado. 

![grafica](https://cloud.githubusercontent.com/assets/18584168/15796577/cc83b95c-29c9-11e6-82f3-04a5546bf5e6.png)
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15796489/43887b70-29c8-11e6-88d3-ef568d8880c8.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo @abicelis

**Comment by abicelis** [comment]
@MaviDavsa @AdryCanonico Hasta que consigamos una mejor forma de mostrar esta data, decidimos eliminar la grafica, dejando solo la informacion de arriba. Esto a partir de la v16.6

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa En la version 17.3 ya la gráfica no esta, Creo que si, no se va a usar se debería cerrar el caso.
