### ISSUE TITLE
CBP - CRYPTO CUSTOMER - FORMA DE LAS IMAGENES DIFERENTE BROKER LIST 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#476]
### CBP

-----

##### Reporte de error: 

   *Se visualiza en las fichas las fotos de forma cuadrada y no redonda. Seria bueno estandarizar la forma de las fotos. 

![repetidos los broker](https://cloud.githubusercontent.com/assets/18584168/15796623/9d8c4ece-29ca-11e6-816d-409139427d4b.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:GENYMOTION
* Modelo:EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/15796489/43887b70-29c8-11e6-88d3-ef568d8880c8.png)

**Comment by AdryCanonico** [comment]
@yalayn

**Comment by vlzangel** [comment]
Yo @vlzangel me encargo de esto.

**Comment by yalayn** [comment]
Yo @yalayn Corregí este issue. Debe estar disponible pronto. Les estaré avisando por acá. A continuación adjunto una imagen con la modificación.
Saludos.
![captura de pantalla de 2016-06-16 14 31 56](https://cloud.githubusercontent.com/assets/4664287/16128862/31abc8cc-33cc-11e6-929d-df7fceac9b1d.png)

**Comment by yalayn** [comment]
Buenas tardes, Se acaba de subir la versión 17.4, que tiene disponible esta corrección. Si no se las han facilitado pronto lo estarán haciendo.
Saludos.

**Comment by MaviDavsa** [comment]
@AdryCanonico Bella chequea esto!

**Comment by AdryCanonico** [comment]
@vlzangel @MaviDavsa En la versión 18 CBP se estandarizo la forma de las fotos. Seria bueno colocarla un poco mas pequeñas para que sea mas agradable el diseño.  

![broker list 1](https://cloud.githubusercontent.com/assets/18584168/16236201/4cb7028e-37a1-11e6-9710-6229c5ab70bc.png)

**Comment by yalayn** [comment]
Ok chevere @AdryCanonico. Lo colocaré un poco más pequeño.

**Comment by yalayn** [comment]
Listo @AdryCanonico ya coloque la imagen un poco mas pequeña.
![captura de pantalla de 2016-06-23 22 00 26](https://cloud.githubusercontent.com/assets/4664287/16325758/adb1d146-398a-11e6-96ed-480138085b8c.png)

**Comment by AdryCanonico** [comment]
@yalayn  Excelente!! :+1: Se puede cerrar el caso
