### ISSUE TITLE
CBP - Broker Wallet - Los datos de Bank Accounts salen montados en el detalle

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#477]
#### Broker Wallet - Settings - Bank Accounts

-----

##### Reporte de error: 

   *Cuando me voy al Settings para revisar el detalle de la cuenta que ingresé al momento de configurar el bank, salen montados los datos de la cuenta con el nombre del banco

------
#### Pantalla 1

![screenshot_4](https://cloud.githubusercontent.com/assets/19142276/15827124/43ac36c0-2bd8-11e6-8b85-396f07599c7a.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/15827147/594ced6c-2bd8-11e6-88e6-8fb4cd5ff2da.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo @vlzangel

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa Arreglado en la version 16.6!

**Comment by Hernandezsmanu** [comment]
Solucionado v. 16.6

![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/16046924/eadad588-3217-11e6-9a7b-5ed35ddc9bf4.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/5313335/16046928/f00e19a2-3217-11e6-8f2d-cc0432948a6a.png)

**Comment by MaviDavsa** [comment]
Solucionado!
