### ISSUE TITLE
CBP - Brokers y Customers - Caracteres en profile ilimitados

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#478]
Al momento de crear el perfil en Brokers y Customers en el campo "Enter name or alias" no esta limitado la cantidad de caracteres. @vlzangel

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/15827705/061fa7a8-2bd6-11e6-85e1-520fccf69b87.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/15827708/0bbaf67c-2bd6-11e6-8acd-9643d7e17af8.png)

Modelo de Telf:
* Marca: Nexus
* Modelo: 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@vlzangel

**Comment by vlzangel** [comment]
Yo @vlzangel me encargo de esto.

**Comment by danielaporras** [comment]
Este error aun sigue en la versión 16.6

![screenshot_11](https://cloud.githubusercontent.com/assets/19656830/16047983/267221d8-321c-11e6-9529-93d994a5f08e.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0
@MaviDavsa

**Comment by yalayn** [comment]
Yo @yalayn trabajare en este issue

**Comment by yalayn** [comment]
Hola @Hernandezsmanu, @MaviDavsa, @danielaporras, ya se corrigió el issue, debe estar disponible en la próxima versión de la app. Les estaré informado.
Saludos.
![captura de pantalla de 2016-06-21 00 53 42](https://cloud.githubusercontent.com/assets/4664287/16218507/5d71561e-3748-11e6-9198-f25ff3f76898.png)

**Comment by sanro14** [comment]
@yalayn esto continua sucediendo en la V18

**Comment by yalayn** [comment]
Hola @sanro14. Estos cambios no están en la versión 18. Deben estar en la próxima.

**Comment by AdryCanonico** [comment]
@Hernandezsmanu En la version 18.4 de CBP ya esta limitada la cantidad de caracteres.

**Comment by abicelis** [comment]
Creo que hay que cerrar este issue :D
