### ISSUE TITLE
TKY-ART - Se pixela la imagen en el perfil de las identidades de TKY

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#479]
#### Profiles - Tokenly Fan/Tokenly Artist

-----

##### Reporte de error: 

   *El error sucede luego de crear la identidad (Fan/Artist) en Tokenly, Inicialmente introduzco los datos para el usuario que voy a crear y le coloco una imagen (Pantalla 1), guardo los datos (save changes) y me saca inmediatamente de la pantalla del perfil, pero al volver a entrar al perfil que he creado, la imagen que seleccioné parar la identidad, sale muy pixelada (Pantalla 2) 

------
#### Pantalla 1

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/15838295/46274916-2c0b-11e6-8b7c-112d2edae044.jpg)

#### Pantalla 2

![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/15838301/4eff3bc0-2c0b-11e6-8740-dc694588aebb.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15838319/69a15cd8-2c0b-11e6-83dc-08a43b4dbedc.jpg)

**Comment by IsbetVR** [comment]
@darkestpriest @sanro14

**Comment by darkestpriest** [comment]
Please, check this @juanaso

**Comment by alexanderejm** [comment]
este issue devio haberse resuelto en la ultima version de la apk entregada v1u2, por favor verifica con esa version

**Comment by IsbetVR** [comment]
@MaviDavsa 
Si, corregido en la versión v1u2. Ya no se pixela la imagen del perfil.
