### ISSUE TITLE
TKY-ART - Se pixela la imagen en el perfil de las identidades de ART

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#480]
#### Profiles - Artist Identity / Art Fan Identity

-----

##### Reporte de error: 

   *El error sucede luego de crear la identidad (Fan/Artist) en ART, Inicialmente introduzco los datos para el usuario que voy a crear y le coloco una imagen (Pantalla 1), guardo los datos (save) y me saca inmediatamente de la pantalla del perfil, pero al volver a entrar al perfil que he creado, la imagen que seleccioné parar la identidad, sale muy pixelada (Pantalla 2)

------
#### Pantalla 1

![screenshot_8](https://cloud.githubusercontent.com/assets/19142276/15838678/61801448-2c0d-11e6-958a-c9d6167e40e8.jpg)

#### Pantalla 2

![screenshot_9](https://cloud.githubusercontent.com/assets/19142276/15838683/6b4e38a6-2c0d-11e6-8aca-f850c404dadf.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4 (320 dpi)
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15838691/7fc44f64-2c0d-11e6-814d-cdda98552b8b.jpg)

**Comment by IsbetVR** [comment]
@darkestpriest @sanro14

**Comment by alexanderejm** [comment]
este issue devio haberse resuelto en la ultima version de la apk entregada v1u2, por favor verifica con esa version

**Comment by IsbetVR** [comment]
@MaviDavsa 
Si, corregido en la versión v1u2. Ya no se pixela la imagen del perfil.
