### ISSUE TITLE
CBP- Checkbox no cumple con su funcion.

### ISSUE THREAD

**Issue by RubenSem** [Fermat-ORG/beta-testing-program#482]
### Template issue error report

Todas las ventanas.

##### Reporte de error: 

   En cada ventana donde salen Pequeños Wizard con información o consejos para el usuario, al querer quitarlo de forma permanente dándole al checkbox no funciona, sigue saliendo en cada aplicación dentro de fermat.

![screenshot_12](https://cloud.githubusercontent.com/assets/19676223/15842491/4e4e789a-2c23-11e6-9782-9ea999cf620f.jpg)
![screenshot_13](https://cloud.githubusercontent.com/assets/19676223/15842492/4e53ed84-2c23-11e6-9d45-c52018cf741b.jpg)
![screenshot_14](https://cloud.githubusercontent.com/assets/19676223/15842493/4e5a8e78-2c23-11e6-912f-3c461eb84afe.jpg)

#### Dispositivo desde donde se realizo la prueba

![screenshot_7](https://cloud.githubusercontent.com/assets/19676223/15842498/551b3d98-2c23-11e6-9829-73c1f8a29897.jpg)

**Comment by RubenSem** [comment]
@vlzangel @MaviDavsa

**Comment by danielaporras** [comment]
Sucede esto mismo en la versión 16.5 

![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/16026164/2a49a99c-3196-11e6-8b55-33db9f33ac13.png)


![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/16026168/330954e2-3196-11e6-9e6b-e1322a7c404b.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0

@MaviDavsa

**Comment by abicelis** [comment]
@RubenSem @danielaporras Corregido esto en la version 16.6, revisen y me avisan.

**Comment by RubenSem** [comment]
@abicelis sigue pasando el mismo error.

**Comment by nelsonalfo** [comment]
Por favor verificar esto nuevamente

**Comment by danielaporras** [comment]
En mi dispositivo ya no aparece este error @sanro14

**Comment by MaviDavsa** [comment]
@RubenSem Necesito que me revises esto por favor!

**Comment by RubenSem** [comment]
Error solucionado @MaviDavsa
