### ISSUE TITLE
CPB- La aplicacion no responde en Identidies

### ISSUE THREAD

**Issue by RubenSem** [Fermat-ORG/beta-testing-program#483]
#### Nombre pantalla
 Pantalla de profiles

##### Reporte de error: 

  Al tratar de crear Profiles la aplicación no responde y se reinicia.

![img_06062016_205005](https://cloud.githubusercontent.com/assets/19676223/15842794/077fdf6e-2c26-11e6-9962-5d04347d087c.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/15842862/91c3fc1e-2c26-11e6-82a7-cdf9ec53ffab.jpg)

------

#### Dispositivo desde donde se realizo la prueba

![dsfsfsddsf](https://cloud.githubusercontent.com/assets/19676223/15842796/0aaf5598-2c26-11e6-92e8-118f181a7117.png)

**Comment by RubenSem** [comment]
@MaviDavsa @abicelis

**Comment by abicelis** [comment]
@RubenSem El titulo de este issue dice "communities" pero creo que se refiere a identities. Este error es conocido y tiene que ver con la plataforma, no ocurre en todos los dispositivos y no tiene que ver directamente con CBP, ademas, no sabemos exactamente que es.

Mientras se corrija sugiero que usen otro dispositivo. Otro emulador.

**Comment by RubenSem** [comment]
ok @abicelis intentare probar con otros emuladores, con otros dispositivos a ver como me va y te comento.

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 483 CBP V16.5
Nexus 5 5.0.0
Ocurre lo reportado. No permite crear el perfil. Este caso es parecido al  (caso 433) yo le hice un comentario tambíen.
![no deja crear el perfil 1](https://cloud.githubusercontent.com/assets/17283358/15982246/aac8e5e8-2f4c-11e6-994e-a0887c3f1ed5.png)

**Comment by AdryCanonico** [comment]
@vlzangel En la version 16.5 de CBP Esta ocurriendo el mismo error en la broker y en la Customer. Esto me sucedió en teléfonos físicos. @MaviDavsa Por fa revisa el caso #433 ya que son muy parecidos. 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987456/21b42022-2ff3-11e6-8d26-cc5232e8c715.png)

![5 0 delio](https://cloud.githubusercontent.com/assets/18584168/15987457/21b49d86-2ff3-11e6-8f96-fb225e0f2ae4.jpg)

**Comment by MaviDavsa** [comment]
@RubenSem Adriana tiene razon vamos a pasar este caso al #433 ya que son muy parecidos. Vamos a cerrar este y vamos a dejar el otro! :D
