### ISSUE TITLE
LPW-Problemas con la grafica: No muestra las variaciones de las ganancias en USD

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#484]
#### Nombre pantalla
Loss Protected Walllet
##### Reporte de error: 

   1- Revisando simultaneamente el emulador de Adrana y el del grupo noté:
![no aparece boton](https://cloud.githubusercontent.com/assets/17283358/15859615/a908d11a-2c8f-11e6-9644-82f609213853.png)

   2- Que en mi emulador en la parte de los USD ganados no lo refleja como podran notar en la siguente foto:
![no aparece boton 1](https://cloud.githubusercontent.com/assets/17283358/15859667/e4dffe66-2c8f-11e6-93b6-0f1d5ef3010a.png)
  3- Pero el recuadro indica que se ganaron 10USD:
![no aparece boton 2](https://cloud.githubusercontent.com/assets/17283358/15859736/1e670f4e-2c90-11e6-825a-66ecd8cc045b.png)
  4- Realice otra tansacción u aparece igual:
![no aparece boton 3](https://cloud.githubusercontent.com/assets/17283358/15859802/60f09506-2c90-11e6-887f-aadf50430216.png)

LPW V14  07-06-2016
#### Dispositivo desde donde se realizo la prueba
320dpi
![nexus 4 5 0 0](https://cloud.githubusercontent.com/assets/17283358/15859948/f2d2780e-2c90-11e6-8587-d036d94f0da3.png)

**Comment by maydiamc** [comment]
a mi me sucede lo mismo @nattyco 
Samsung Galaxy, Mini s4, 4.4.2
![screenshot_2016-06-07-09-03-53](https://cloud.githubusercontent.com/assets/17274154/15860686/e04592fe-2c93-11e6-8f72-5661798fc098.png)

**Comment by marielis-urbina** [comment]
En la versión 14 de LPW, se repite el error a pesar de a ver realizado transacciones, el gráfico no tiene ni altas ni bajas

![grafica](https://cloud.githubusercontent.com/assets/19353722/15879392/99dca406-2ced-11e6-98dd-6add7efcd1ce.png)

Dispositivo desde donde se realizo la prueba

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/15879400/b86a71c8-2ced-11e6-97af-ef35e8fbbd7a.png)

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 15 de la apk, se corrigieron los datos que muetra el popup y en la grafica si tenes valores de ganancia o perdida muy cercanos a 0 los va a mostrar sobre ese linea por ejemplo 0.12, -0.023, y la linea se tiene que mover si los valores varian por mas cantidad, probar cambiando de Proveedor de exchange rate en las settings para tener distintos montos de cotizacion.

**Comment by maydiamc** [comment]
en la version 15 no sucede el error en mi samsung galaxy mini s4, 4.4.2, ya muestra las ganancias o perdidas.! @yolandayancel revisar esto para ver si se cierra el caso, @nattyco

**Comment by AdryCanonico** [comment]
@yolandayancel  @nattyco en la version 15 si se muestra los cambios de ganancia pero la hora esta incorrecta.

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 08-06-2016
Caso 484 LPW V15.1
Nexus 4
Este error se corrigió. Aparecen las Variaciones.
![caso 484](https://cloud.githubusercontent.com/assets/17283358/15911473/d36254a8-2d99-11e6-8d55-260aef1f9107.png)

**Comment by MaviDavsa** [comment]
Perfecto! Cerrado!
