### ISSUE TITLE
LPW_problemas con la grafica: No actualiza datos en la ficha

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#485]
#### Nombre pantalla
-----

##### Home

- [x] Grafica

##### Reporte de error: 

   * en la ficha de informacion de la grafica la hora de cada punto de la grafica es incorrecta, ademas de que no actualiza la ganancia y la perdida, sino que en todos los puntos se muestran los mismos datos.. 

![screenshot_2016-06-07-09-03-53](https://cloud.githubusercontent.com/assets/17274154/15861337/ee29e9ea-2c95-11e6-8444-7f788abf3064.png)
![screenshot_2016-06-07-09-13-29](https://cloud.githubusercontent.com/assets/17274154/15861357/f853e402-2c95-11e6-9d87-4fdb10608cb9.png)
![screenshot_2016-06-07-09-19-47](https://cloud.githubusercontent.com/assets/17274154/15861366/005554ba-2c96-11e6-8bf7-f1c3bae662d9.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy 
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa version 14 de apk

**Comment by yolandayancel** [comment]
@nattyco 
Prueba caso 485
LPW V14 07-06-2016
Nexus 4 5.0.0 Api 21
320dpi
Es este emulador actualiza la hora en  la grafica.  No actualiza la ganancia y la perdida. 
![caso 485](https://cloud.githubusercontent.com/assets/17283358/15862219/c9f80d1a-2c98-11e6-853d-fa9e6e0b23f9.png)

**Comment by marielis-urbina** [comment]
En la versión 14 de la LPW sigue el mismo error en la ficha de informacion de la grafica la hora de cada punto de la grafica es incorrecta, ademas de que no actualiza la ganancia y la perdida, sino que en todos los puntos se muestran los mismos datos.

![ni altos ni bajos](https://cloud.githubusercontent.com/assets/19353722/15879459/2f895116-2cee-11e6-91c9-790fa5ef389d.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/15879465/394053bc-2cee-11e6-8489-25a3f6ca6cbc.png)

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 15 de la apk, se corrigieron los datos que muetra el popup y en la grafica si tenes valores de ganancia o perdida muy cercanos a 0 los va a mostrar sobre ese linea por ejemplo 0.12, -0.023, y la linea se tiene que mover si los valores varian por mas cantidad, probar cambiando de Proveedor de exchange rate en las settings para tener distintos montos de cotizacion.

**Comment by maydiamc** [comment]
en la version 15, la ficha, al pulsar los puntos de las diferentes transacciones, actualiza el monto de perdida o ganancia de cada una, pero persiste el error de la hora incorrecta. @nattyco 

Samsung galaxy
Mini s4
4.4.2

![screenshot_2016-06-08-09-04-05](https://cloud.githubusercontent.com/assets/17274154/15895402/ec38a1f2-2d54-11e6-9593-e11173d4e098.png)
![screenshot_2016-06-08-09-02-25](https://cloud.githubusercontent.com/assets/17274154/15895407/f38063d2-2d54-11e6-9954-8034caa72ee2.png)

**Comment by AdryCanonico** [comment]
@nattyco En la version 15 da errores en la hora, no muestra la secuencia de horas que debe dar. o se adelanta a la hora actual o se atrasa. También no es consecutiva con la gráfica al momento de las transacciones, 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15896062/5cf26628-2d58-11e6-8894-14075bb460e9.png)

**Comment by MaviDavsa** [comment]
En cuanto a mi tlf, todo rueda bien... Se ve la utilización del botón de descripción, se ven las perdidas y ganancias en tal como vaya pasando, y las fichas me las actualiza y pone en orden. 

![screenshot_2016-06-08-19-58-54](https://cloud.githubusercontent.com/assets/17273005/15915114/682f6380-2db0-11e6-90ff-edbd76ca55e3.jpg)

Esta es la foto que se muestra al presionar el primer punto.

![screenshot_2016-06-08-19-58-59](https://cloud.githubusercontent.com/assets/17273005/15915140/92cc8398-2db0-11e6-837b-a82c978dfe07.jpg)

Y en el el punto que tiene mayor tiempo, ubicado al final de la gráfica se encuentra este.

![screenshot_2016-06-08-19-59-04](https://cloud.githubusercontent.com/assets/17273005/15915190/f55b2e2e-2db0-11e6-8f16-7f686ec8a853.jpg)

Telefono de prueba

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15915198/0f368b5e-2db1-11e6-8781-c1d7fc8cb27e.jpg)

**Comment by maydiamc** [comment]
solucionado este problema.! cerrar el caso @MaviDavsa @nattyco
