### ISSUE TITLE
CBP - Broker - Error al intentar cambiar los campos de la negociación

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#486]
#### Broker Wallet - Negotiation Details 
-----

##### Reporte de error: 

   *El error sucede cuando el "Customer" me ha enviado (Tengo perfil de Broker) una negociación. Al abrirla, y ver los detalles de ésta, se supoone que yo como broker, puedo modificar algunos campos a fin de establecer una negociación de acuerdo a lo que el customer me ha enviado, no me deja modificar nada. Cuando le doy click al campo para poderlo editar (por ejemplo el tipo de cambio, o el valor del monto), inmediatamente se cuelga la aplicación y me sale el mensaje de "Fermat isn't responding". (Pantalla 1)

------
#### Pantalla 1

![screenshot_11](https://cloud.githubusercontent.com/assets/19142276/15864925/e274edf0-2ca6-11e6-80f3-865ba2df74d9.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4, 320 dpi
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15865017/2e3e97f4-2ca7-11e6-9509-0128d373d360.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by yalayn** [comment]
Hola @IsbetVR el día de ayer trabajando en corregir otro bug me percate de esto y lo corregí. Debería estar disponible para la próxima versión de la app.

**Comment by yalayn** [comment]
Hola @IsbetVR en la version 16.5 se corrigio este bug. 
Saludos.

**Comment by MaviDavsa** [comment]
@IsbetVR Que paso con esto bella!?

**Comment by IsbetVR** [comment]
@MaviDavsa @yalayn bien! En la Versión v18 permite hacer las modificaciones sin problemas.
