### ISSUE TITLE
CBP- Profile Image en crypto brokers users y customer

### ISSUE THREAD

**Issue by RubenSem** [Fermat-ORG/beta-testing-program#487]
#### Nombre pantalla
Crypto brokers users

##### Reporte de error: 

Ya creado el perfil sale mi identidad como unknown y no muestra mi foto, aclaro que antes si me dio la opción de elegir mi user y cargo normalmente.
![c63b3fbe-2c1e-11e6-97ca-d03957d06bdb](https://cloud.githubusercontent.com/assets/19676223/15865085/347899ca-2ca3-11e6-8bdd-018bf078b6ce.jpg)

#### Dispositivo desde donde se realizo la prueba

![ccffad80-2c1e-11e6-9cd9-42e86af1cb25](https://cloud.githubusercontent.com/assets/19676223/15865068/28c1c6b0-2ca3-11e6-9e78-1156a5fa9aa1.jpg)

**Comment by RubenSem** [comment]
@MaviDavsa @nattyco

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 487 CBP V16.5
Nexus 5 5.0.0
Ocurre lo reportado.
![caso 487](https://cloud.githubusercontent.com/assets/17283358/15982209/a10676f2-2f4b-11e6-83d8-a43f0fc5686e.png)

**Comment by abicelis** [comment]
@RubenSem @yolandayancel Ok, voy a revisar esto. Les aviso!

**Comment by LilianFlores** [comment]
En la versión 16.6 se presenta este error tal cual como se explica, pero con una identidad de customer.

![screenshot_2016-06-14-19-48-26](https://cloud.githubusercontent.com/assets/19652611/16063976/1a6f1288-3267-11e6-9534-f1603f4306d2.png)

**Dispositivo desde donde se realizo la prueba**

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16063983/2c4d59ec-3267-11e6-95b6-bda0a553fce3.png)

**Comment by LilianFlores** [comment]
En la versión 16.6 este error persiste. Creé mi identidad como customer y me dio la opción de elegir mi user la primera vez, pero luego me apareció de esta forma. 

![screenshot_2016-06-14-19-48-26](https://cloud.githubusercontent.com/assets/19652611/16064012/67c845cc-3267-11e6-9bd6-d59415833e6a.png)

**Dispositivo desde donde se realizo la prueba**

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16064043/a5f8ce02-3267-11e6-9e42-8f56f9432dcf.png)

**Comment by LilianFlores** [comment]
En la versión 16.6 este error persiste cuando estoy en el Crypto Customer y voy a mi perfil, me aparece mi identidad como unknown. Si me salgo y vuelvo a entrar, sale mi perfil bien, pero si actualizo vuelve a aparecer de la misma forma (unknown)

![screenshot_2016-06-14-20-42-03](https://cloud.githubusercontent.com/assets/19652611/16064862/c350bd6e-326e-11e6-912e-69f716f15954.png)


**Dispositivo desde donde se realizo la prueba**

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16064832/76c66ba6-326e-11e6-8996-39df1b820fa2.png)

**Comment by nelsonalfo** [comment]
gracias por la info @LilianFlores pero eso que reportas seria otro Issue, porque aquí se esta reportando lo que pasa en la Customer Community y en la Broker Community

**Comment by AdryCanonico** [comment]
@RubenSem @nelsonalfo En mi telefono en la version 17.3 se corrigió el error.

**Comment by RubenSem** [comment]
Error solucionado, por favor cerrar caso. @MaviDavsa
