### ISSUE TITLE
CBP - Broker - Error con el "Delivery Date" en la Negociación

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#488]
#### Broker Wallet - Negotiation Detalis

-----

##### Reporte de error: 

   *Tengo el perfil de Broker, cuando el customer me envía una negociación, revisando los detalles, hay unas secciones en la negociación que hacen referencia a la fecha y la hora "Customer Delivery Date" y "Broker Delivery Date", si la hora que aparece en estos campos es "menor" a la hora del emulador no me deja confirmar, inmediatamente me arroja un error diferente en cada caso, en el caso del "Customer Delivery Date" el error lo muestro en la "Pantalla 1", y para el caso del "Broker Delivery Date" el error lo muestro en la "Pantalla 2". Es importante mencionar que era necesario configurar la hora de estos campos de acuerdo a la hora del emulador (Pantalla 3), y así no me generaba ningún error, configurándola igual o mayor a la que tiene el emulador. Pero si la hora del "Broker Delivery Date" la configuraba mayor a la del "Customer Delivery Date" (Pantalla 4) igualmente me arrojaba error (Pantalla 5). 

------
#### Pantalla 1

![screenshot_13](https://cloud.githubusercontent.com/assets/19142276/15865592/66bad3a2-2ca9-11e6-9e69-d9d0bcae7a24.jpg)

#### Pantalla 2

![screenshot_14](https://cloud.githubusercontent.com/assets/19142276/15865614/7561a980-2ca9-11e6-9e6b-fb74ea851a8e.jpg)

#### Pantalla 3

![screenshot_16](https://cloud.githubusercontent.com/assets/19142276/15865632/88f77164-2ca9-11e6-8221-25fd0f8e1d62.jpg)

#### Pantalla 4

![screenshot_18](https://cloud.githubusercontent.com/assets/19142276/15865668/aaee5594-2ca9-11e6-97f5-5e8653acc8a1.jpg)

#### Pantalla 5

![screenshot_19](https://cloud.githubusercontent.com/assets/19142276/15865678/b575008a-2ca9-11e6-9f2e-01333ef990ad.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 4, 320 dpi
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15865730/df067de8-2ca9-11e6-9006-edfaf986f5ac.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by nelsonalfo** [comment]
No es un error sino una precaución para que el usuario tome las fechas de forma correcta. Por ejemplo: no puedes decir que vas a recibir la mercancía antes de que realices el pago, asi mi mismo, no puedes colocar una fecha de entrega menor a la fecha y hora actual, y el toma como la fecha y hora actual la del telefono, es decir, el emulador

**Comment by MaviDavsa** [comment]
Correcto! Pero si es el caso de una persona que va a hacer eso por tranferencia? lo va a hacer en el momento o no? Y si la personas viven en lugares diferentes? No les cambia la hora? por la diferencia de horarios? De ser así que pasaría?

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by nelsonalfo** [comment]
si va a ser por transferencia el pago tienes que colocar una fecha mayor. Esos campos son editables, pero se les coloca por defecto la fecha y hora actual para que el usuario la cambie. Con respecto a lo de vivir en diferentes lugares, la app se pensó para realizar negociaciones dentro de una misma localidad, por lo que la hora debería ser la misma.

**Comment by MaviDavsa** [comment]
@nelsonalfo Perfecto Nelson! Ya te comprendo realmente esas son las 2 cosas por las que vimos los errores pero entonces dame chance a que las chicas puedan ver si efectivamente las deja editar! De ser así los cerramos! @IsbetVR Encárgate de esto por favor!

**Comment by MaviDavsa** [comment]
Perfecto ya entiendo @nelsonalfo De ser así, deja que @IsbetVR Revise todo y te aviso!

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa pudieron revisar este issue?

**Comment by MaviDavsa** [comment]
@abicelis Si mi amor! Pero lo de las horas es una locura! :(

**Comment by MaviDavsa** [comment]
@IsbetVR Hay que revisar esto!

**Comment by IsbetVR** [comment]
@abicelis @MaviDavsa en la versión 18 de CBP tenemos problemas con lo de las horas, es una locura. 
Sea de los emuladores o teléfonos físicos cambia las horas. Así sea el Broker o Customer el que actualice en cada paso de la negociación la hora, la cambia totalmente cuando le llega al otro (Broker o Customer)

**Comment by marielis-urbina** [comment]
En la versión 18 de la CBP cuando haces negociaciones y lo mandas a una hora al vendedor y llega con otra hora y otra fecha al comprador y viceversa,

**Comment by nelsonalfo** [comment]
Esto es algo que hablamos ayer durante una reunión con varios de los integrantes de beta testing, por favor comuniquense con ellos para mas información

**Comment by sanro14** [comment]
si, se va a tomar la hora en el cual se realice la negociación chic@s
