### ISSUE TITLE
CBP Broker - Cancelación del contrato

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#489]
#### Broker Wallet - Contracts History - Contract Details

-----

##### Reporte de error: 

   *Teniendo el perfil de broker, el customer me envió una negociación, y de acuerdo a los pasos que se siguen para establecer la negociación, aparentemente se establece el contrato con el customer, pero al pasar unos minutos llega la notificación que el contrato fue cancelado y cuando reviso los detalles de contratos (Pantalla 1), me sale que fue cancelado por algo referente a la fecha. Realmente aún no entiendo que tiene que ver las fechas con respecto a las negociaciones, pues como se reportó en el caso número 488, hay unos errores en la configuración de la hora al momento de hacer las negociaciones, no se si tendrá algo que ver para que se cancele la negociación luego de haber llegado la notificación que si se hizo el contrato.

------
#### Pantalla 1

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/15866212/b5385566-2cab-11e6-9736-4f17be35b54d.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:Genymotion
* Modelo: Google Nexus 4, 320 dpi
* Version de Android: 5.0.0

![nexus 4](https://cloud.githubusercontent.com/assets/19142276/15866220/c13adf1e-2cab-11e6-8101-e6e9700b5523.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by nelsonalfo** [comment]
el contrato se cancelo porque se no realizaste el pago en la fecha acordada, no es un error. Tu en el contrato defines las fechas limite en las que vas a pagar y en las que vas a recibir el dinero, por lo que si se pasa esa fecha y hora de pago y no has realizado el pago se cancela el contrato; lo mismo pasa con la fecha y hora de entrega de la mercancia, sino no la entregas antes de la fecha y hora establecidas entonces se cancela el contrato porque lo estas incumplendo

**Comment by MaviDavsa** [comment]
@nelsonalfo Este también por fa! Déjame revisarlo el hecho de cambiar la hora y cuadrar, si efectivamente hace todo bien lo cerramos! @IsbetVR

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa pudieron revisar este issue?

**Comment by MaviDavsa** [comment]
@abicelis Las comunidades no nos han dejado llegar hasta alli! Pero en lo que sepamos, te avisamos de seguro!

**Comment by yolandayancel** [comment]
Prueba 22-06-2016
Caso 489 CBP 18
Samsumg S6 5.1.0
Ocurre algo parecido, se realizan los pasos de la negociación pero estas expiran y luego desaparecen del home las que tenía allí esperando por que el customer respondiera.
![screenshot_4](https://cloud.githubusercontent.com/assets/17283358/16288227/84b7d0b0-38b3-11e6-9d88-b6585724992a.png)
[logcat caso 489.txt](https://github.com/Fermat-ORG/beta-testing-program/files/328978/logcat.caso.489.txt)

**Comment by sanro14** [comment]
Se Solucionó
