### ISSUE TITLE
Bitcoin Wallet_Sent Bitcoin_NavigationView_Formulario de envio

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#49]
#### Nombre pantalla

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *Luego de enviar Bitcoins, me quede en la pantalla de "Send" y antes de salir reflejada la notificacion del envio de bitcoins la aplicacion se reinicio y fue necesario volver a entrar a la aplicacion para visualizar dicha notificacion 

------
##### Reporte de error: 

   *Probando la aplicacion, abri el "navigationview" y al precionar cualquier boton de este, me salio un error y se reinicio la aplicacion, al ingresar de nuevo esto no volvio a ocurrir
![screenshot_2016-03-02-11-09-17](https://cloud.githubusercontent.com/assets/17274154/13465450/f43a4250-e067-11e5-8875-5fb4acc7be49.png)

------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Llene el formulario para el envio de Bitcoin y al momento de presionar "send" para realizar la transaccion, se mostro un error (contact don´t have an address please wait 2 minutes) luego de esperar los dos minutos realice los mismos pasos y la aplicacion arrojo el mismo error de nuevo. 
![screenshot_2016-03-02-11-05-48](https://cloud.githubusercontent.com/assets/17274154/13465684/f820769a-e068-11e5-8bb5-50775876ec71.png)

Modelo de telefono: Samsung Galaxy MiniS4
Version de Android: 4.4.2 Kit Kat

**Comment by augusto-ponce** [comment]
@nattyco @furszy

**Comment by nattyco** [comment]
@augusto-ponce @maydiamc Sobre el tema de la direccion del contacto, no se obtiene ese dato inmediatamente, tarda en llegar porque tiene que conectarse con el otro dispositivo. Hay que ver si el otro usuario esta conectado a la red de Fermat para poder retornar su dirección. Y si el dispositivo desde el cual se esta solicitando la direccion tambien lo esta y tiene buena conexion a internet.

Si la dirección del contacto nunca llega, aun cuando el otro dispositivo estaba conectado a la red, lo tomaremos como un error a revisar.

**Comment by nattyco** [comment]
@maydiamc probar cuando tengan la nueva version si se soluciono el error al presionar en las opciones del menu deplegable.

**Comment by maydiamc** [comment]
@augusto-ponce Gracias por la aclaracion, entonces el error de "Send bitcoins" no existe, ya que no es posible enviar Bitcoins al usuario Mati_bitcoin. 
Saludos.!

**Comment by maydiamc** [comment]
Solucionados los errores en la nueva actualizacion 
Modelo del telefono: Samgung galaxy miniS4
numero de version: Android 4.4.2 kit kat
