### ISSUE TITLE
Idendity Manager - BITCOIN WALLET - ERROR AL USAR LA CAM EN EL PERFIL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#490]
### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Al momento de querer colocar la foto con la camara del telefono la aplicacion se cierra totalmente y se reincia,

![untitled-1](https://cloud.githubusercontent.com/assets/18584168/15894623/a4313d64-2d50-11e6-95a6-1f274a90f3df.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Marca:SANSUNG

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15894490/edcc32fe-2d4f-11e6-8761-4f5a106ec554.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by maydiamc** [comment]
@nattyco  en la version 15 de la apk,, al intentar colocar la foto que tome de la camara se coloca toda la pantalla en negro y debo reiniciar la apk para poder seguir usandola

Samsung Galaxy
Mini s4
4.4.2

**Comment by RubenSem** [comment]
@nattyco Me pasa Justamente lo mismo, al tratar de tomar la foto se cierra la aplicacion y se reinicia  pero en una versión de android diferente, usando el emulador.
Versión del apk 15. 
![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/15896832/c0cd1bd6-2d5b-11e6-8a84-37a4aa710014.jpg)

**Comment by AdryCanonico** [comment]
@nattyco sigue persistiendo el error en la versión 16.2 lpw

**Comment by maydiamc** [comment]
en la version 17, con mi dispositivo, no e deja colocar la foto y se cuelga la app, debo reiniciarla para que funcione @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16026801/dc8c031c-319a-11e6-95ac-5924b7df9906.png)

**Comment by AdryCanonico** [comment]
@nattyco En la version 18.2 de CBP persiste el error. No toma la foto de la cámara y coloca un predeterminado. 

![screenshot_2016-06-24-08-30-53](https://cloud.githubusercontent.com/assets/18584168/16339062/69fcff9c-39ea-11e6-831f-3f074405de70.png)

![screenshot_2016-06-24-08-41-41](https://cloud.githubusercontent.com/assets/18584168/16339063/6a004f76-39ea-11e6-821f-6f265ce6c47e.png)

Teléfono físico:

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16339637/99519f20-39ed-11e6-8136-f5da5cad56d8.png)

**Comment by AdryCanonico** [comment]
@nattyco ya se puede usar la cam en la version 19.2 de CBP
