### ISSUE TITLE
CBP - Connections - Error en Pantalla

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#491]
#### Nombre pantalla
Connections

##### Reporte de error: 

Al momento de ingresar en la pantalla Connections me muestra este error a continuacion...

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 5 
* Version de Android: 5.0

![screenshot_7](https://cloud.githubusercontent.com/assets/19670319/15895954/c2a2c194-2d57-11e6-917b-199d38e536fd.png)

**Comment by dorzar1989** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by yolandayancel** [comment]
Prueba 10-06-16 CBP V 16.5
Nexus 5  5.1.0
No ocurre el error.Se ingresa a connectión y se visualiza el user agregado.
