### ISSUE TITLE
LPW-No se refleja Available balance

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#493]
##### Reporte de error: 

   *En LPW version 15 en el Home no deja cambiar del Real Balance a Available balance.
   

![e89befb2f66a97700c65e222801eb0d48e2e707c75615fe62d pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/19656830/15896869/f181c9de-2d5b-11e6-8201-d89d0101aa67.png)
------

#### Dispositivo desde donde se realizo la prueba

![511ac84f3f64d3bab1688d23232f8a0a98a1af44c6fe8c3a5d pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17273005/15897638/1870cea2-2d5f-11e6-90f0-1bc0519f7e95.png)

@MaviDavsa

**Comment by AdryCanonico** [comment]
@nattyco El mismo problema esta sucediendo en mi teléfono con la version 15 y a veces cuando lo presiono se me sale de la aplicación. 

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15897035/95005bd4-2d5c-11e6-991b-7fb8ab074d7e.png)

**Comment by maydiamc** [comment]
@nattyco 
en mi dispositivo sucede lo mismo

Samsung galaxy
Mini s4
4.4.2

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 08-06-2016
Caso 493 LPW V15.1
Nexus 5  5.0.0 480dpi
En el Home si  deja cambiar del Real Balance a Available balance.
![caso 493](https://cloud.githubusercontent.com/assets/17283358/15912699/b390a8a4-2d9f-11e6-86f1-0663b2402de9.png)

**Comment by AdryCanonico** [comment]
@danielaporras en el mio ya hace el cambio
@MaviDavsa En la version 15.1 ya hace el cambio Available balance. 


![screenshot_2016-06-08-18-22-09](https://cloud.githubusercontent.com/assets/18584168/15913295/df859570-2da2-11e6-8293-ed55595355d7.png)

**Comment by MaviDavsa** [comment]
@danielaporras Por tener el mismo android de @AdryCanonico voy a cerrar el caso belleza!

**Comment by maydiamc** [comment]
reabrir el caso, el error se esta reflejando en la version 15.2 de la apk @nattyco @MaviDavsa

**Comment by MaviDavsa** [comment]
En esta nueva versión no funciona bella...
![screenshot_2016-06-09-09-18-43](https://cloud.githubusercontent.com/assets/17273005/15931232/a4242900-2e20-11e6-8abf-411c170d506c.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15931276/e13cf308-2e20-11e6-8125-ffcd197e5fc5.jpg)

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 16 de la apk

**Comment by arosiopr** [comment]
@MaviDavsa en la version 16 se soluciono este error

**Comment by sanro14** [comment]
@MaviDavsa cierra este caso

**Comment by danielaporras** [comment]
@MaviDavsa  ya puede cerrar este caso
