### ISSUE TITLE
LPW - LAS FOTOS DE LOS CONTACTOS SE VEN COMPRIMIDAS O CON FONDO NEGRO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#494]
### LPW

-----

##### Reporte de error: 

   *En los contact se ven las fotos de los contactos comprimida o con fondo negro. 

![screenshot_2016-06-08-09-52-42](https://cloud.githubusercontent.com/assets/18584168/15898498/60255832-2d62-11e6-84d9-66a5eaa8458f.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:SAMSUNG

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15898562/a1292e58-2d62-11e6-85aa-f1384cadab53.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by maydiamc** [comment]
en mi dispositivo sucede lo mismo, la imagen se ve comprimida @nattyco 
![screenshot_2016-06-08-11-09-32](https://cloud.githubusercontent.com/assets/17274154/15899426/77d62d82-2d65-11e6-9f9f-a86e7b5882dd.png)

Samsung Galaxy 
Mini S4 
4.4.2
