### ISSUE TITLE
CBP - Community - Falla al establecer conexión con un broker

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#495]
##### Reporte de error: 

   Al entrar en la community de los brokers no me deja establecer conexión, es decir, al broker nunca le llego mi solicitud y a lo que trato de cancelarla el botón  "Cancel" no hace nada. @nelsonalfo 

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/15899294/168a78ee-2d65-11e6-8b48-2403961bf413.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Nexus 4
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by yolandayancel** [comment]
@nelsonalfo
Prueba 10-06-16 CBP V 16.5
Nexus 5 5.0.0 
No ocurre el error.Se estableció conección con el Broker.

**Comment by marielis-urbina** [comment]
Me sucede lo mismo en la versión 16.5 de CBP mande mi solicitud y nunca les llego al brokers

![brok](https://cloud.githubusercontent.com/assets/19353722/15980824/39ceb228-2f38-11e6-80bb-bdca55fd0e32.png)

Dispositivo desde donde se realizo la prueba

![android 5 1](https://cloud.githubusercontent.com/assets/19353722/15980833/51358176-2f38-11e6-96f9-74911d0cb0a6.png)

**Comment by yalayn** [comment]
Buenas noches. Ya estamos trabajando en mejorar la comunicación entre los actores. En la versión 16.5 se hicieron unos cambios destinados a eso y estamos evaluando que tal se comporta en las pruebas.
Saludos.

**Comment by Hernandezsmanu** [comment]
Solucionado.
