### ISSUE TITLE
CBP- Broker Wallet: las letras quedan por debajo del menu

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#496]
#### Nombre pantalla
Broker Wallet

##### Reporte de error: 
CBP V 16.4
   *Al ingrsar en Broker Wallet  las letras estan por debajo del menu y no se pueden leer
![broker walet-montada las letras 1](https://cloud.githubusercontent.com/assets/17283358/15899798/c22fad4e-2d66-11e6-973b-c09573d58686.png)

   
------

#### Dispositivo desde donde se realizo la prueba
213dpi
![nexus 7](https://cloud.githubusercontent.com/assets/17283358/15899893/2cc1b7ec-2d67-11e6-8d3e-3c6d95cc125c.png)

**Comment by MaviDavsa** [comment]
Error de la Testear! :)
