### ISSUE TITLE
LPW_Texto sin funcionalidad en la grafica

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#497]
##### Home

- [x] Grafica

##### Reporte de error: 

   *En la version 15 de la LPW, en la zona inferior derecha de la grafica, aparece una palabra "Description", que esta mal ubicada, no tiene ninguna funcionalidad y no describe nada. 

![screenshot_2016-06-08-09-45-03](https://cloud.githubusercontent.com/assets/17274154/15900589/d36881dc-2d69-11e6-9871-0b65386d2756.png)

------
#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 08-06-2016
Caso 497 LPW V15.1
Nexus 4 5.0.0 320 dpi
En la zona inferior derecha de la grafica, aparece una palabra "Description": al clickear sobre ella despliega el siguente cuadro: 
![caso 497](https://cloud.githubusercontent.com/assets/17283358/15912471/4b691712-2d9e-11e6-9a0d-785533c1bd8f.png)

**Comment by MaviDavsa** [comment]
![screenshot_2016-06-08-19-59-04](https://cloud.githubusercontent.com/assets/17273005/15915301/11e2e4d2-2db2-11e6-9c23-b77254e01276.jpg)

En mi caso cuando pulso el boton, me muestra las perdidas que he tenido... @nattyco 

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15915324/3cd85ff0-2db2-11e6-9def-c1de35305695.jpg)

**Comment by maydiamc** [comment]
se mantiene el problema.! el texto no tiene funcionalidad ni explicacion, se ve desubicado y extraño, xq no va de acuerdo con el diseño grafico de la aplicacion @nattyco @MaviDavsa

**Comment by maydiamc** [comment]
Aclaro que es probable que el pop up de la ficha que les sale a las chicas @MaviDavsa @yolandayancel  se muestra al presionar cualquier lugar de la grafica y no al presionar el "boton" description, porque luego de realizar varias pruebas con ellas, se comprobo que el boton, efectivamente, no tiene ninguna funcionalidad.! @nattyco

**Comment by yolandayancel** [comment]
@maydiamc 
Tienes razón se hace click en cualquier parte de la grafica y aparece el recuadro. ese botón no tiene una función.

**Comment by sanro14** [comment]
En la versión 16 cuando doy click sobre cualquier parte del plano de la grafica me muestra el alert con la información. @nattyco

**Comment by nattyco** [comment]
Se quito la palabra Description que no correspondia.
