### ISSUE TITLE
TKY ART- Pantalla de la fan wallet

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#498]
##### Reporte de error: 
 
 Donde debería ver la caratula de la canción no se ve agradable al usuario, sería bueno que se mostrara solo la opción de refrescar la pantalla para que sea mas sencillo, pues la imagen se podría ver distorsionada o estirada.

![dfgdf](https://cloud.githubusercontent.com/assets/17273005/15901411/f8e2067e-2d6c-11e6-9729-6fca1bbbc724.JPG)

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: nexus 5
* Version de Android: 5.0

**Comment by sanro14** [comment]
@darkestpriest

**Comment by darkestpriest** [comment]
@lostwood, por favor, chequea lo del banner. Eso ya se había solucionado. ¿que versión del apk estás usando @sanro14 ?

**Comment by lostwood** [comment]
Hola @sanro14 en la ultima version de la app se quito el header
