### ISSUE TITLE
Bitcoin Wallet -Add Fermat User- Contact Detail

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#50]
### Bitcoin Wallet 

-----

##### Reporte de error: 

Al Ingresar en contactos, dar click en add farmat user me lleva a Crypto wallet users,
Al dar click en Adriana Molina para aceptar una solicitud el botón aparece desactivado, no me deja aceptar la solicitud como se muestra en la siguiente captura:
![captura de pantalla 2016-03-02 10 52 31](https://cloud.githubusercontent.com/assets/5313324/13465101/55a0f9d2-e066-11e5-801b-aabc9ca485eb.png)

Pude aceptar las solicitudes fue por la opción de Notifications.

Por otra parte sale el mismo usuario repetido, me envió 3 solicitudes y para que dejaran de salir di aceptar a todas y se agrego repetidas veces como se puede observar:
![captura de pantalla 2016-03-02 11 10 31](https://cloud.githubusercontent.com/assets/5313324/13465499/286ec1c2-e068-11e5-93a5-99e81f4c89cb.png)

Al dar atrás sale a las wallets, debería regresar a la pantalla de agregar contactos de Bitcoin Wallet que fue por la que accedí.

------

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
------
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

La dirección del contacto sale cargando y se queda allí:
![captura de pantalla 2016-03-02 11 42 55](https://cloud.githubusercontent.com/assets/5313324/13466457/2da6cc62-e06c-11e5-9cfd-d62bffa2341b.png)

   
   
------
##### Formulario de envio

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Formulario de pedido de pago

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

Al intentar enviar bits sale el siguiente mensaje: "We can't find an address for the contact yet" como se puede observar en la siguiente captura.
![captura de pantalla 2016-03-02 11 25 13](https://cloud.githubusercontent.com/assets/5313324/13466232/4564389a-e06b-11e5-96c8-224381d6189b.png)
   
   
------
##### Settings

- [] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
------

**Emulador Genymotion Custom Phone Android 4.4.4. API 19**

**Comment by nattyco** [comment]
@augusto-ponce @sanro14  Sobre el tema de la direccion del contacto, no se obtiene ese dato inmediatamente, tarda en llegar porque tiene que conectarse con el otro dispositivo. Hay que ver si el otro usuario esta conectado a la red de Fermat para poder retornar su dirección.

Si la dirección del contacto nunca llega, aun cuando el otro dispositivo estaba conectado a la red, lo tomaremos como un error a revisar.

**Comment by sanro14** [comment]
@nattyco ok, verificare eso

**Comment by nattyco** [comment]
@sanro14  @augusto-ponce  Add Fermat User Error Fixed, se corrigio el error que no dejaba presionar el boton para aceptar la solicitud de contacto.

**Comment by sanro14** [comment]
@augusto-ponce si solucionado lo del botón. con respecto a lo de la dirección, en efecto la dirección sale cuando el usuario está conectado como dijo @nattyco. Así que este caso se puede dar por resuelto.
