### ISSUE TITLE
TKY-ART - Error en la Fan Wallet.

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#500]
TKY-ART - Error en la FAN WALLET.

TKY-ART

##### Reporte de error: 

Una vez creadas las identidades de Tokenly Fan y Tokenly Artist, cuando me dirijo a la Fan Wallet, inmediatamente al ingresar, me sale el siguiente error: 

![fan error](https://cloud.githubusercontent.com/assets/17261437/15900723/848e59e2-2d6e-11e6-8b18-bb45601a8d05.png)

Por lo que, evidentemente, al revisar mi lista de canciones disponibles, no se inicia la descarga automática de esas canciones y no me permite avanzar en las pruebas, ya que sucede lo mismo, incluso limpiando la data.

![fan wallet](https://cloud.githubusercontent.com/assets/17261437/15900759/a0c806d0-2d6e-11e6-96bc-e22c05b98b53.png)

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/17261437/15899845/210c1ace-2d6b-11e6-801d-fd0d2735900e.png)

**Comment by gablup** [comment]
@alexanderejm

**Comment by darkestpriest** [comment]
Saludos, para que la fan wallet funcione debes tener el dispositivo conectado a internet, en la barra de estado de tu emulador se nota que el dispositivo tiene las conexiones 3G y Wi-Fi apagados.

**Comment by alexanderejm** [comment]
tambien, la fan wallet, para funcionar, requiere una identidad de ART fan(que por lo que dices, no creaste), esta identidad deve estar conectada con una identidad de TKY fan

**Comment by gablup** [comment]
Buenas tardes, necesito aclarar algunas cosas, para evitar confusiones, No estaba usando ningún emulador, ya que se me pidió que probara esta apk desde mi celular, ya que posee un android de 5.1 @darkestpriest y si estaba conectada a Internet, en todo momento. 

Y bueno, seguí todos los pasos indicados en el video inductivo sobre la aplicación y fui creando absolutamente todos los perfiles, solo que mencioné esos dos. @alexanderejm 

¡Saludos!

**Comment by darkestpriest** [comment]
Te comento @gablup la única forma que ese toast indicando problemas con el API de Tokenly es que no tengas conexión a internet, ya que eso es producto de capturar una excepción de un plugin que se conecta con tokenly. Cuando se intenta conectar a Tokenly y existe algun error, el API de Tokenly envía mensajes distintos, esos mensajes son capturados por la app y se le coloca un texto que se pueda entender. El texto que se muestra solo se dispara **si no hay conexión a internet**, si existiera otro tipo de error, se mostrara en dicho toast, pero, ese, en específico, indica que no hay conexión a internet.

**Comment by MaviDavsa** [comment]
@gablup Vuelvelo a intentar, vete a un sitio donde la red te agarre en su totalidad! Y en ese momento haces la prueba, de volverte a dar el error lo vuelves a comentar... Porque efectivamente pasa algo por lo que las conexiones no se están dando de manera optima!

**Comment by alexanderejm** [comment]
algun update sobre este issue referente a lo que comento @MaviDavsa ?

**Comment by IsbetVR** [comment]
@MaviDavsa En la versión v1u2. de la apk, a mi no me está dando este error. Pero con respecto a lo que mencionó @alexanderejm referente a que se requiere una identidad Art Fan para que funcione la "Fan Wallet", no, no la requiere, hice las pruebas creando usuario por usuario para ver si era necesario que estuviese creada la identidad en Art Fan, y no. La única identidad necesaria para que funcione la Fan Wallet es la identidad de "Tokenly Fan". 

@gablup no se si tu has podido probar a ver si no te ha dado este error con la versión v11u2.

Las pruebas las hice en Emulador:
Google Nexus 4
Versión de Android 5.0.0

**Comment by IsbetVR** [comment]
@MaviDavsa Este error no sale en la versión v1u2

**Comment by lostwood** [comment]
gracias por confirmar @IsbetVR si lo pueden cerrar @MaviDavsa te agrezco
