### ISSUE TITLE
LPW - Error en el home

### ISSUE THREAD

**Issue by RubenSem** [Fermat-ORG/beta-testing-program#501]
#### Nombre pantalla

Loss Protected wallet

##### Reporte de error: 

 Intento meterme en Loss protected wallet y al entrar me lanza el error recovering from system error, Esto me pasa en la version 15 de la lpw.

![screenshot_7](https://cloud.githubusercontent.com/assets/19676223/15901307/95c10b80-2d6c-11e6-903a-642d695ded2f.jpg)
![screenshot_6](https://cloud.githubusercontent.com/assets/19676223/15901320/a37a501a-2d6c-11e6-8613-be58c7554721.jpg)

   

#### Dispositivo desde donde se realizo la prueba

![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/15901327/ab3141d8-2d6c-11e6-8147-9bf3c74adf2d.jpg)

**Comment by RubenSem** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@nattyco  en la version 15 tambien me dio el error Oooops! recovering from system error no tengo la capture y este tambien.


![screenshot_2016-06-08-08-57-27](https://cloud.githubusercontent.com/assets/18584168/15901636/e398a8bc-2d6d-11e6-8b10-5eba7323fdc0.png)

DISPOSITIVO;

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15901661/fbb9bf1c-2d6d-11e6-84fa-ad4f55b23079.png)

**Comment by MaviDavsa** [comment]
En mi caso, me daba el error y me sacaba al home de la apk! 

![screenshot_2016-06-08-19-51-19](https://cloud.githubusercontent.com/assets/17273005/15917278/f8b033bc-2dc4-11e6-856c-825bc3863b54.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15917291/0e319fdc-2dc5-11e6-92d4-d7736d5d3ec6.jpg)

**Comment by nattyco** [comment]
@MaviDavsa @AdryCanonico   veriicar en la version 15.2 de la apk

**Comment by maydiamc** [comment]
en mi dispositivo, con la version 15.2, no se muestra este error, @RubenSem revisar este caso para ver si en tu disposivo a ver como funciona @nattyco 

Samsung galaxy
mini s4
4.4.2

**Comment by MaviDavsa** [comment]
A mi me llego solo una vez..!!

**Comment by AdryCanonico** [comment]
@nattyco en la versión 15.2 sigue sucediendo el error, sobre todo cuando intento entrar en la ayuda.

![recovering fom system errpr](https://cloud.githubusercontent.com/assets/18584168/15935975/1a482ade-2e33-11e6-80ea-51cad4c14e87.png)

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15936008/3661270c-2e33-11e6-8a57-a397f678466e.png)

**Comment by RubenSem** [comment]
ok probare con otros dispositivos. @maydiamc

**Comment by nattyco** [comment]
@MaviDavsa verificar en la version 16 de la apk

**Comment by RubenSem** [comment]
En la version 16 de la apk, al parecer ah sido solucionado.
![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/15947042/52ca1f9a-2e63-11e6-9b22-3266f21259d0.jpg)

Dispositivo donde fue probado:

![ab3141d8-2d6c-11e6-8147-9bf3c74adf2d](https://cloud.githubusercontent.com/assets/19676223/15947072/7ba9c15e-2e63-11e6-94a6-a9c47ec93993.jpg)

**Comment by danielaporras** [comment]
@MaviDavsa  Este error ya no sale al entrar al home, puedes cerrarlo

**Comment by danielaporras** [comment]
Al intentar entrar al Home de Loss Protected Wallet aparece este error, versión 16.1

![screenshot_7](https://cloud.githubusercontent.com/assets/19656830/15967990/e0619fbe-2ef3-11e6-972f-449282139d1b.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0 

@MaviDavsa

**Comment by sanro14** [comment]
@RubenSem revisa esto, a mi no me da ya ese error, confirma

**Comment by RubenSem** [comment]
Listo error solucionado @MaviDavsa @nattyco por favor cerrar caso.

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattyco En la versión 17 persiste el error pero al querer entrar en la community 

![recovering from system error](https://cloud.githubusercontent.com/assets/18584168/16012278/90d97a14-3152-11e6-8bc3-f250f3133e34.png)

**Comment by kmiloxvii** [comment]
A mi no me sucede este error en la version 17

**Comment by maydiamc** [comment]
no me sucede en la version 17 @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16026879/6f4018f6-319b-11e6-83cb-9c977d872e5c.png)

**Comment by nattyco** [comment]
@AdryCanonico si te da error en la pantalla de add fermat user seria otro error

**Comment by RubenSem** [comment]
Solucionado el error en la nueva versión, por favor cerrar caso @MaviDavsa

**Comment by MaviDavsa** [comment]
Solucionado!
