### ISSUE TITLE
TKY-ART - Error en la visualización de los usuarios en la Artist Community.

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#502]
TKY-ART - Error en la visualización de los usuarios en la Artist Community.

##### Reporte de error: 

Después de crear los perfiles de "Artist Identitity" y "Art Fan Identity", cuando entro a las Communities, específicamente en el botón de "Artist Community", para aceptar las conexiones y verificar datos... me salen los perfiles que ya había creado anteriormente en la "Artist Identitity" y "Art Fan Identity" con normalidad pero cuando selecciono uno me dice que los usuarios no están disponibles, a pesar de que al entrar se visualizaban perfectamente.

![error artist user](https://cloud.githubusercontent.com/assets/17261437/15901877/3377874a-2d73-11e6-9656-4f27f642bea9.png)

![artist user](https://cloud.githubusercontent.com/assets/17261437/15901886/40f93864-2d73-11e6-9b85-22541c5631d2.png)

Cabe destacar, que al salir y volver a entrar, ni siquiera se visualizan los usuarios como en la primera vez de haber ingresado, sino que arroja el error de inmediato.

#### Dispositivo desde donde se realizo la prueba

![acerca del tlf](https://cloud.githubusercontent.com/assets/17261437/15901659/2becce8c-2d72-11e6-8efd-c396b07761a9.png)

**Comment by gablup** [comment]
@alexanderejm

**Comment by darkestpriest** [comment]
Saludos, la primera pantalla muestra la selección de identities disponibles para ser usadas en la community, luego de eso, la app te lleva a la pantalla donde están los otros usuarios que etán **en línea**, si esa pantalla dice "there are not user available" es porque no hay ningún usuario en línea para mostrar. Para probar las communities es necesario tener otro usario conectado. En mi caso, yo abro dos emuladores para realizar esa prueba o me pongo de acuerdo con otra persona para probar este componente.

**Comment by alexanderejm** [comment]
la aplicacion funciona con normalidad, no te aparecen usuarios disponibles por que no hay usuarios disponibles, tendria que existir otro usuario(en este caso un usuario artista) conectado para que aparezca en la community.

tampoco aparece denuevo el menu para seleccionar la identidad por que existe una parte del menu que cumple esa funcionalidad que se llama "your identity".

**Comment by gablup** [comment]
Es que el usuario llamado "gablup" era el usuario artista en ese caso. Esa
es la cuestión o al menos lo que note que no estaba bien.

**Comment by darkestpriest** [comment]
Como dice @alexanderejm la aplicación funciona bien, debes tener otro usuario en línea para poderlo visualizar.

**Comment by MaviDavsa** [comment]
@gablup Perfecto bella vamos a probar mañana esto ambas! Y vemos si realmente es problema en comunidades o si fue que se te paso algún paso!

**Comment by sanro14** [comment]
es que las community estaban fallando esta mañana

**Comment by MaviDavsa** [comment]
@sanro14 Pero tu estabas conectada!???

**Comment by alexanderejm** [comment]
lograron hacer pruebas desde 2 telefonos/emluadores con las communitys?

**Comment by Hernandezsmanu** [comment]
Ya se realizo la prueba con dos usuarios más y si salen.

![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/16200281/7943f1ca-36d6-11e6-8ff8-1e2935e906d3.png)

**Comment by MaviDavsa** [comment]
@gablup Como hacemos esto?

**Comment by gablup** [comment]
Ayer estuvimos realizando las pruebas y efectivamente ya se logra visualizar. Favor cerrar caso @MaviDavsa
