### ISSUE TITLE
LPW- Transactions: Esta en Blanco, los send enviados no aparecen

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#504]
#### Nombre pantalla
Transactions

##### Reporte de error: 

   1- Realice varias transacciones como se puede ver en la grafica:
![las transacciones no aparecen 2](https://cloud.githubusercontent.com/assets/17283358/15913571/997417e4-2da4-11e6-9fdc-43e759c6df0f.png)
   2- Pero al ingresar en las transacciones en el Sent, no aparece.
![as transacciones no aparecen 1](https://cloud.githubusercontent.com/assets/17283358/15913598/bddf0508-2da4-11e6-979e-7d57fd6df9a5.png)

LPW V15.1
   
------

#### Dispositivo desde donde se realizo la prueba
320dpi
![nexus 4](https://cloud.githubusercontent.com/assets/17283358/15913691/4f986534-2da5-11e6-897c-297340ef9b69.png)

**Comment by MaviDavsa** [comment]
@yolandayancel Ya este issues fue creado y cerrado... Es el caso #465

**Comment by yolandayancel** [comment]
@MaviDavsa 
Si está repetido. Hay que cerrarlo.
