### ISSUE TITLE
 LPW- Loss Protected wallet- Mensajes de Error Can't get balance exception

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#505]
Template issue error report

1. Ingresar a loss protected wallet.
2. Una vez en loss protected wallet ir a settings.
3. Se regreso al home de loss protected wallet por medio del boton de "atras" del telefono-
4. Al regresar a home la aplicaciòn mostró los siguientes mensajes.

![mensaje 1](https://cloud.githubusercontent.com/assets/2491042/15914347/93eb19a0-2db6-11e6-9075-cac69fb5f3d1.png)
![mensaje 2](https://cloud.githubusercontent.com/assets/2491042/15914350/9b38231a-2db6-11e6-96e1-54c430fa1ac4.png)

Modelo de telefono

![phone blu](https://cloud.githubusercontent.com/assets/2491042/15914364/b0a4a980-2db6-11e6-99ed-64179eea2d6a.png)

**Comment by arosiopr** [comment]
sucede lo mismo en mi celular

![screenshot_2016-06-08-19-20-18](https://cloud.githubusercontent.com/assets/5313326/15914510/562c94f0-2dab-11e6-927e-3294a13e13cc.png)

![screenshot_2016-06-08-19-20-34](https://cloud.githubusercontent.com/assets/5313326/15914523/5d428970-2dab-11e6-9ab0-b5753852f017.png)

**Dispositivo**

![screenshot_2016-06-08-19-21-55](https://cloud.githubusercontent.com/assets/5313326/15914538/7b1fd3bc-2dab-11e6-823a-38b23cc5f641.png)

**Comment by andreagmarcano** [comment]
Me pasa lo mismo en mi celular. 

![image](https://cloud.githubusercontent.com/assets/18452495/15914853/15266244-2dae-11e6-84fb-55161296ef8e.png)

![image](https://cloud.githubusercontent.com/assets/18452495/15914865/3a3e9fba-2dae-11e6-8eb5-22a97be9bb1b.png)

![image](https://cloud.githubusercontent.com/assets/18452495/15914897/88b825a8-2dae-11e6-9a3b-3b10f66f1e28.png)

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la version 15.2 de la apk

**Comment by MaviDavsa** [comment]
En mi caso continua...

![screenshot_2016-06-09-09-24-31 1](https://cloud.githubusercontent.com/assets/17273005/15932205/9ce4691c-2e24-11e6-9104-c72d972433cd.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15932227/a95126a4-2e24-11e6-9a10-5b3be2c8a38b.jpg)

**Comment by maydiamc** [comment]
en mi dispositivo no sucede este problema, con la version 15.2 de la apk

samsung galaxy
mini s4
4.4.2

**Comment by AdryCanonico** [comment]
@nattycoen en mi emulador no sucede este problema, con la versión 15.2 de la apk 

![screenshot_2](https://cloud.githubusercontent.com/assets/18584168/15932714/83b79610-2e26-11e6-8f2b-a27fccf6ebeb.png)

dispositivo;

![nexus 4 2 2](https://cloud.githubusercontent.com/assets/18584168/15932734/971bbd94-2e26-11e6-9bb2-e49cf67af68d.png)

**Comment by dorzar1989** [comment]
En mi emulador con la versión 15.2 de la Apk continua este error 

![screenshot_9](https://cloud.githubusercontent.com/assets/19670319/15934603/fbfbba14-2e2d-11e6-9927-54c363c995b2.png)

Dispositivo

![screenshot_10](https://cloud.githubusercontent.com/assets/19670319/15934618/076dc374-2e2e-11e6-9998-c5ff9a0755d8.png)

**Comment by dorzar1989** [comment]
@MaviDavsa  @nattyco

**Comment by nattyco** [comment]
@MaviDavsa verificar en la version 16 de la apk

**Comment by arosiopr** [comment]
@sanro14 en mi dispositivo ya no sale este error

**Comment by danielaporras** [comment]
En la versión 16.1 sigue el error.

![screenshot_15](https://cloud.githubusercontent.com/assets/19656830/15967759/c34734ee-2ef2-11e6-9d0a-e1f2d52459f5.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by yolandayancel** [comment]
@nattyco
Prueba 10-06-16
Caso 505 LPW V16.2
Nexus 5- 5.0.0 480dpi
No ocurre el error

**Comment by AdryCanonico** [comment]
@MaviDavsa @nattycoen en mi telefono no sucede este problema, con la versión 16.2 de la apk

**Comment by nattyco** [comment]
@MaviDavsa   verificar en la nueva version de la apk

**Comment by kmiloxvii** [comment]
En la version 17  ya no me sucede este error @MaviDavsa  puedes cerrar ese issue

**Comment by MaviDavsa** [comment]
Solucionado!
