### ISSUE TITLE
LPW - Chunk Value no muestra detalles

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#506]
#### Nombre pantalla
Chunk Value

### LPW

-----

##### Reporte de error: 

   * El error radica en que cuando voy al Chunk Value para ver los details de la transacción esta me sale completamente en blanco, sin especificar nada.

![screenshot_2016-06-08-19-12-25](https://cloud.githubusercontent.com/assets/17273005/15914374/33c6e240-2daa-11e6-837a-041c77c43fcc.jpg)

Y entro y aún no especifica nada

![screenshot_2016-06-08-19-12-33](https://cloud.githubusercontent.com/assets/17273005/15914377/3ca60d50-2daa-11e6-817d-43612a509e31.jpg)

   
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15914381/43646d58-2daa-11e6-8ded-dc84772e3b98.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  corregido en la version 15.2 de la apk

**Comment by MaviDavsa** [comment]
Solucionado

![screenshot_2016-06-09-09-07-58](https://cloud.githubusercontent.com/assets/17273005/15932106/30f0d43e-2e24-11e6-9928-fb319f127613.jpg)
