### ISSUE TITLE
LPW - Payment Request - Received

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#507]
Template issue error report

Nombre pantalla Setting

Loss Protected Wallet - Payment Request - Received

Al entrar al menu payment request a la sección recieved se listan las transacciones como deberia pero al momento de existir varias, el boton con forma de avion de papel se monta sobre el boton de aceptar la transacciòn y esta no se puede recibir como muestra la siguiente imagen:

![solapa](https://cloud.githubusercontent.com/assets/2491042/15915673/c1117b94-2dc1-11e6-9254-2998ceee682b.png)

![phone blu](https://cloud.githubusercontent.com/assets/2491042/15915699/f7a3d4c2-2dc1-11e6-8e45-fd98dc833fed.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-16
Caso 507 LPW V16
Nexus 5 5.0.0
![montado el boton de send request 2](https://cloud.githubusercontent.com/assets/17283358/15949907/81cc5cfc-2e74-11e6-9ac2-eaa59424f523.png)

Estando en la pantalla de REQUESTS de la Loss Protect Wallet, se observa como el botón para enviar los request esta montado sobre las letras. Moví la pantalla hacia arriba

**Comment by yolandayancel** [comment]
@nattyco
Prueba 10-06-16
Caso 507 LPW V16.2
Nexus 5- 5.0.0 480dpi
Persiste el error. Sigue montado sobre las letras.

**Comment by kmiloxvii** [comment]
sigue persistiendo este error, cuando hay tres items en la lista, cuando hay mas si se puede procesar por el scroll pero cuando hay tres el boton se monta sobre aceptar 

![error_again](https://cloud.githubusercontent.com/assets/2491042/16025241/90290d6a-319c-11e6-8ab5-8195504bb2bc.png)

![phone](https://cloud.githubusercontent.com/assets/2491042/16025249/9f9b2d46-319c-11e6-9aff-48829a665335.png)

**Comment by nattyco** [comment]
@IsbetVR  en la nueva version 3.5 se quito el flotante y el boton de new request esta ahora en el toolbar

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en la version 3.5 de CCP el boton paso a la parte superior del toolbar
![screenshot_2016-09-28-15-42-26](https://cloud.githubusercontent.com/assets/5313326/18929345/1f12bdf2-8592-11e6-9539-938049288453.png)

**Comment by IsbetVR** [comment]
Solucionado
Closed #507
