### ISSUE TITLE
LPW-COMMUNITIES- ERROR AL CARGAR CRIPTO WALLET USERS

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#508]
### Template issue error report

Nombre pantalla

CRIPTO WALLET USERS

COMMUNITIES

##### Reporte de error: 

   *LUEGO DE CREAR EL USERS EN LA WALLET Y TRATAR DE INGRESAR  A LA COMMUNITIES LA APLICACION SE QUEDA PEGADA Y APARECE EL SIGUIENTE ERROR;
------

![image](https://cloud.githubusercontent.com/assets/18740418/15915754/c6fb194a-2db5-11e6-9d01-8b5d0b27ad24.png)

 POSTERIORMENTE SE REINICIA LA APLICACIÓN Y SIGUE APARECIENDO LO MISMO, SE CIERRA EL EMULADOR, SE HACE EL PROCESO Y SIGUE IGUAL

#### Dispositivo desde donde se realizo la prueba

* Marca: GENYMOTION
* Modelo: EMULADOR

![image](https://cloud.githubusercontent.com/assets/18740418/15915797/2b27f690-2db6-11e6-9b09-bc3826789af1.png)

**Comment by danielaporras** [comment]
Me sucede exactamente lo mismo.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/15915884/f7971c24-2db6-11e6-9c25-273e855d1f01.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0.0

@MaviDavsa

**Comment by marielis-urbina** [comment]
De igual forma en la versión 15.1, me pasa lo mismo no me permite ver los contactos y no permite hacer mas nada hay que cerrar el emulador

Dispositivo desde donde se realizo la prueba

![android 5 1](https://cloud.githubusercontent.com/assets/19353722/15915918/3cdd7c42-2db7-11e6-8b8b-928353e09fd4.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by andreagmarcano** [comment]
Sigue repitiéndose el error

![image](https://cloud.githubusercontent.com/assets/18452495/15949402/fdd3e134-2e70-11e6-8ccd-f8c52bb0e447.png)

![image](https://cloud.githubusercontent.com/assets/18452495/15949420/2d4dbf70-2e71-11e6-86c6-5a5077ec343d.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-16
Caso 508 LPW V16
Nexus 5 5.0.0 480dpi
No ocurre lo mismo. Ingresa en la Cripto Wallet user.
![caso 508](https://cloud.githubusercontent.com/assets/17283358/15949776/d0cffb48-2e73-11e6-9bf5-22e063eade6f.png)

**Comment by yolandayancel** [comment]
@nattyco
Prueba 10-06-16
Caso 511 LPW V16.2
Nexus 5- 5.0.0 480dpi
No aparecen los user. Se refresca la pantalla, pero no aparecen.

**Comment by danielaporras** [comment]
En la versión 16.1 persiste el error.

![screenshot_6](https://cloud.githubusercontent.com/assets/19656830/15968612/510f35ee-2ef6-11e6-8ac6-7bfb66af9bb9.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by nattyco** [comment]
@MaviDavsa Verificar como se comporta la app en la version 17 de la apk

**Comment by kmiloxvii** [comment]
Sigue sucediendo en la versión 17 
![screenshot_2016-06-13-17-58-15](https://cloud.githubusercontent.com/assets/2491042/16024577/13183ba0-3199-11e6-8d9b-634eedcd0d96.png)

![phone](https://cloud.githubusercontent.com/assets/2491042/16024587/1ac0e8c0-3199-11e6-8bb1-94aea81b1049.png)

**Comment by AdryCanonico** [comment]
@camilavaleria @MaviDavsa En la versión 18.3 CBP ya no se ve el error

**Comment by camilavaleria** [comment]
caso solucionado
