### ISSUE TITLE
LPW-Transactions Received-Error muestra request enviado

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#509]
### Loss Protected Wallet

-----

##### Reporte de error: 

1. Realice un Request al usuario MariDavsa
2. Ella lo nego, como se puede observar en la siguiente imagen:

![screenshot_2016-06-08-20-00-22](https://cloud.githubusercontent.com/assets/5313326/15915778/fff8370a-2db5-11e6-969e-5b3481782c3b.png)

3.Al ingresar en transactions received sale los btc entrantes como si MariDavsa hubiese aceptado el request y no es así

![screenshot_2016-06-08-19-57-22](https://cloud.githubusercontent.com/assets/5313326/15915773/f2bd562e-2db5-11e6-91b0-9634e3319af1.png)

------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-06-08-19-21-55](https://cloud.githubusercontent.com/assets/5313326/15916111/0ebf12b0-2db9-11e6-8555-b0b59b4e57e1.png)

**Comment by arosiopr** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@arosiopr @MaviDavsa verificar en la version 16 de la apk

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-2016
Caso 509 LPW V16
Nexus 5 5.0.0 480dpi
Este error no ocurre. Los reques que se rechazan lo registra. No se puede ver porque el botón de sen lo tapa.
![caso 509](https://cloud.githubusercontent.com/assets/17283358/15949230/a60a54f2-2e6f-11e6-9736-565ee46fac8f.png)

**Comment by arosiopr** [comment]
@MaviDavsa solucionado
