### ISSUE TITLE
Bit Coins_Wallet

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#51]
### Template issue error report

Bit Coins Wallet

#### Nombre pantalla

Balance

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- Pop up de bienvenida
- Pop up de ayuda

##### Reporte de error: 

   *Tarda mucho en general la carga, intente varias veces hasta que llego la transferencia de lo bitcoins

![screenshot_2016-03-02-11-35-42](https://cloud.githubusercontent.com/assets/17273349/13466517/7138692c-e06c-11e5-91dd-6cff39ea6f69.png)

![screenshot_2016-03-02-11-37-23](https://cloud.githubusercontent.com/assets/17273349/13466613/dfb1bf48-e06c-11e5-9f3f-70f33bc9f525.png)

Android version: 4.4.2

**Comment by nattyco** [comment]
@furszy @augusto-ponce @adryx83  Los bitcoins van a tardar en llegar ya que hay que conectarse a una red que los genera y los confirma, por lo que hay que tener en cuenta el tiempo en que tarda en confirmar, y la conexion a internet del dispositivo y si esta conectado a la red de Fermat tambien.

Cuando se presiona el text Available Balance por unos segundos y se ve el carte que dice "Mati Bitcoins!" hay que esperar a que llegue la Notificacion de que se recibieron los Btc, cada vez que se presione en el text se genera un pedido nuevo de btc.

Solo lo tomaremos con error a revisar si los btc nunca llegan en en trascurso de una hora por ejemplo.

**Comment by adryx83** [comment]
Ok entendido gracias por la aclaratoria!

**Comment by augusto-ponce** [comment]
Gracias por la aclaración @nattyco, no voy a procesarlo como bag
