### ISSUE TITLE
LPW -  Request - Pantalla congelada

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#510]
#### Nombre pantalla
Request

### LPW

-----

##### Reporte de error: 

   *En esta oportunidad el error radica en que cuando te llega un Request, Al Negarlo todo el procedimiento se hace rapido, pero si lo aceptas pasa lo siguiente... 
Da el pop que Dice Request Aceptado

![screenshot_2016-06-08-19-38-27](https://cloud.githubusercontent.com/assets/17273005/15917363/c5829e02-2dc5-11e6-8242-fc5985e950fa.jpg)

Luego dice Enviando
![screenshot_2016-06-08-19-38-30](https://cloud.githubusercontent.com/assets/17273005/15917364/c584bc28-2dc5-11e6-8b4b-e9a9c8bdb216.jpg)

Y luego se me queda así la pantalla, como si nunca se hubiera enviando nada.
![screenshot_2016-06-08-19-38-40](https://cloud.githubusercontent.com/assets/17273005/15917365/c58a1e98-2dc5-11e6-9642-0e7cbf226172.jpg)

Esto es muy molesto ya que como no se va de una al Home del Request, las personas no saben realmente si se hizo el pago o no y les puede pasar como efectivamente me paso a mi, que por no salirse de esa ventana, se hace el pago varias veces, pensando que la primera vez no lo hizo. 
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15917368/cce3a196-2dc5-11e6-9f68-25fcdf5c8f17.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa verificar en la version 16 de la apk

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-2016
Caso 510 LPW V16
Nexus 5 5.0.0 480dpi
![caso 510](https://cloud.githubusercontent.com/assets/17283358/15948745/6372f8c2-2e6c-11e6-84d8-2776d6f3ee65.png)

El error no ocurre. Los Request se aceptan sin problemas.

**Comment by MaviDavsa** [comment]
Solucionado!
