### ISSUE TITLE
App Menú -  Menú de las apk sin nada

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#511]
#### Nombre pantalla
Bitcoin Wallet, Communitys. LPW

### LPW

-----

##### Reporte de error: 

   *En este error vemos como por problemas de Android Core, el menú de diferentes apk no funciona como debería, en lineas generales debemos salir de la Apk desde 0 para que el menú salga.
   
LPW

![screenshot_2016-06-09-08-56-14](https://cloud.githubusercontent.com/assets/17273005/15931517/e2852d38-2e21-11e6-8295-4b3314584b7f.jpg)

Communitys

![screenshot_2016-06-09-08-54-16](https://cloud.githubusercontent.com/assets/17273005/15931518/e28d3a82-2e21-11e6-8038-8acdc609eed3.jpg)

Bitcoin Wallet

![screenshot_2016-06-09-08-52-51](https://cloud.githubusercontent.com/assets/17273005/15931519/e28e76d6-2e21-11e6-8420-6cae6496f459.jpg)

------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15931562/11654994-2e22-11e6-8b33-f72b19884a8b.jpg)

**Comment by Hernandezsmanu** [comment]
En mi caso ocurre lo mismo en esas pantallas y debo salir de la aplicación y volver a entrar para que salga el menu.

![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/15931763/de245b78-2e22-11e6-9462-af2ba389d48b.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/15931776/e94ed7b2-2e22-11e6-9c44-8f3e463e2bf2.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/15931792/f5c35428-2e22-11e6-8eb3-01c13b772dd3.png)

**Dispositivo donde se realizo la prueba:**

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/15931816/10138096-2e23-11e6-8c2d-40b70f0ec754.png)

**Comment by maydiamc** [comment]
en mi dispositivo, en la version 15.2, se muestra el mismo problema
@nattyco 

samsung galaxy
mini s4
4.4.2

![screenshot_2016-06-09-08-53-56](https://cloud.githubusercontent.com/assets/17274154/15932148/5f68193a-2e24-11e6-91f9-bc23e37d2191.png)

**Comment by AdryCanonico** [comment]
@nattyco en mi teléfono fisico, en la versión 15.2, se muestra el mismo problema

![screenshot_2016-06-09-10-47-38](https://cloud.githubusercontent.com/assets/18584168/15934119/1fbc7ae4-2e2c-11e6-80ce-2042b1462f96.png)


![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15934024/ca5a828a-2e2b-11e6-9aaf-92b7a0650dd8.png)

**Comment by AdryCanonico** [comment]
@nattyco EN LA VERSIÓN 16.2 SIGUE PERSISTIENDO EL ERROR

![screenshot_2016-06-10-09-58-15](https://cloud.githubusercontent.com/assets/18584168/15966815/9248b204-2eee-11e6-9449-2e1c03458dbe.png)

**Comment by Gabymorillo** [comment]
En la versión 16.2  presenta el mismo error.

![screenshot_2016-06-10-09-47-32](https://cloud.githubusercontent.com/assets/17262077/15966886/dc2b14a2-2eee-11e6-900f-2c54e650f94d.png)

![screenshot_2016-06-10-10-04-42](https://cloud.githubusercontent.com/assets/17262077/15967048/a7e69f8a-2eef-11e6-8e21-63dce046870f.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 10-06-16
Caso 511 LPW V16.2
Nexus 5- 5.0.0 480dpi
Este error no ocurre en este emulador. Ingresa a los menus sin problemas.

**Comment by danielaporras** [comment]
En mi dispositivo también sale este error.

![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/15968198/c02dfdea-2ef4-11e6-9266-40dfd4b25604.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

**Comment by arosiopr** [comment]
sucede lo mismo en mi dispositivo con la version 16.2 de la apk

![screenshot_7](https://cloud.githubusercontent.com/assets/5313326/15968714/baed4c76-2ef6-11e6-860a-69c853327fea.png)


 **Dispositivo desde donde se realizo la prueba**

* Marca: Genymotion
* Modelo: Google Nexus 4
* Version de Android: 4.4.4

**Comment by MaviDavsa** [comment]
![screenshot_2016-06-10-10-06-25](https://cloud.githubusercontent.com/assets/17273005/15969077/1d1032fa-2ef8-11e6-9376-e078d506c4f8.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15969082/2358960c-2ef8-11e6-9cc5-fae273155c21.jpg)

**Comment by IsbetVR** [comment]
En el dispositivo del emulador que usé para probar la aplicación  (LPW v16.1) persiste este error.
* [x] Emulador 
* HTC One X
* Versión de android: 4.2.2

![screenshot_67](https://cloud.githubusercontent.com/assets/19142276/15976996/1d4514bc-2f24-11e6-8145-2b26411875bf.jpg)

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15976998/22e5f6ca-2f24-11e6-910d-66243b66b24d.jpg)

**Comment by AdryCanonico** [comment]
@nattyco En la versión 17 sigue persistiendo el error

![drawer en blnco](https://cloud.githubusercontent.com/assets/18584168/16011993/59827a62-3151-11e6-8bee-34313e8c18c0.png)

**Comment by kmiloxvii** [comment]
Persiste el error versiòn 17 
![blanco](https://cloud.githubusercontent.com/assets/2491042/16025066/943d7df6-319b-11e6-87ab-6f333e76905b.png)
![phone](https://cloud.githubusercontent.com/assets/2491042/16025072/98a6e774-319b-11e6-8788-39ec692dd0c1.png)

**Comment by maydiamc** [comment]
en mi dispositivo esto no sucede con la version 17 @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025181/a289509e-318f-11e6-8e9e-89a800f93efd.png)

**Comment by AdryCanonico** [comment]
en la version 18.3 de CBP persiste el error.

**Comment by Gabymorillo** [comment]
En la versión 18.8 está solucionado ese error
