### ISSUE TITLE
LPW_puntos de la grafica de diferentes colores

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#512]
##### Home

- [x] grafica

##### Reporte de error: 

   * Se recomienda colocar diferencia de colores en los puntos de la grafica, para identificar si son pèrdida o ganancia, y que sea mejor la visibilidad de las transacciones realizadas y el entendimiento de estas. 

En la imagen se muestra que los puntos de la gràfica son todos iguales, a pesar de que algunos son ganacias y otro pèrdida.

![screenshot_2016-06-09-09-49-42](https://cloud.githubusercontent.com/assets/17274154/15933262/e2baeade-2e28-11e6-8524-593983b26d27.png)

------
#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-2016
Caso 512
En mi opinion personal como usuario, me pareciera que las perdidas deberían tener un color diferenta. O debería aparecer otra linea de un color diferente.

**Comment by nattyco** [comment]
@MaviDavsa @maydiamc  Se pusieron los puntos en dos colores distintos en la version 16.2

**Comment by maydiamc** [comment]
en la version 16.2, la recomendacion se tomo en cuenta y ya se distinguen bien los puntos.! @nattyco

**Comment by MaviDavsa** [comment]
Perfecto... Solucionado...
