### ISSUE TITLE
LPW - Error para agregar contactos

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#513]
#### Contacts - Botón (+)

-----

##### Reporte de error: 

   *El error sucede cuando ingreso a "Contacts" a través del menú, el botón para agregar (+) no tiene la funcionalidad que debería (Pantalla 1), no reacciona cuando le doy click. Le doy al menú para irme al "Home" no ingresa al home como debería (Pantalla 2) y se queda en la pantalla de "contactos" y ahí si despliega las opciones del botón (+) (Pantalla 3), pero no permite ingresar a otras opciones del menú. Debo salir totalmente de la aplicación y volver a entrar para que funcionen las opciones.
   
------

#### Pantalla 1

![screenshot_24](https://cloud.githubusercontent.com/assets/19142276/15947028/6b25a268-2e67-11e6-8927-3252cc68c498.jpg)

#### Pantalla 2

![screenshot_26](https://cloud.githubusercontent.com/assets/19142276/15947038/8001033a-2e67-11e6-8b91-937ff180c771.jpg)

#### Pantalla 3

![screenshot_25](https://cloud.githubusercontent.com/assets/19142276/15947048/8b99729a-2e67-11e6-88f4-28f18cf06bed.jpg)

------

Dispositivo donde se realizó la prueba:
Marca: Genymotion
Modelo: HTC ONE X
Versión de android: 4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15947089/c5b055ac-2e67-11e6-8d16-7255ff517c37.jpg)

**Comment by IsbetVR** [comment]
@nattyco @sanro14

**Comment by arosiopr** [comment]
en mi celular sucede lo mismo

![screenshot_2016-06-08-19-21-55](https://cloud.githubusercontent.com/assets/5313326/15947268/7c6c4e8a-2e64-11e6-9315-27868760c4eb.png)

**Comment by sanro14** [comment]
Sucede lo mismo en el Lg l5 android 4.2 el boton de (+) para agregar contactos no sirve.

**Comment by maydiamc** [comment]
en mi dispositivo sucede lo mismo, version 16 @nattyco 

Dispositivo
Samsung Galaxy
Mini s4
4.4.2

**Comment by IsbetVR** [comment]
@nattyco LPW v16
(Mismo dispositivo con el cual se realizó el reporte
HTC One X
4.2.2
)

Reinicio el emulador, vuelvo a cargar la aplicación y al entrar a "Contacts" no sale el botón (+)

![screenshot_27](https://cloud.githubusercontent.com/assets/19142276/15947563/2c5ed830-2e6a-11e6-9b8f-83b2c22b60a3.jpg)

Cierro y vuelvo abrir y si salió, pero no tiene funcionalidad

![screenshot_60](https://cloud.githubusercontent.com/assets/19142276/15947599/5fd2b42a-2e6a-11e6-87d0-a0b28134df8e.jpg)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-16
Caso 513 LPW V16
Nexus 5- 5.0.0 480dpi
Estando en contactos para agregar los user, el botón no aparece. Pise menu y salí de la Loss Protected Wallet  y regresa nuevamente a contactos el botón aparece pero no funciona.
![caso 513](https://cloud.githubusercontent.com/assets/17283358/15947638/691df516-2e66-11e6-8514-f8f9da6161e7.png)

**Comment by andreagmarcano** [comment]
El contactos de (+) para agregar un contactos no funciona 

![image](https://cloud.githubusercontent.com/assets/18452495/15949839/2de904c8-2e74-11e6-9821-2cca6ea517e9.png)
![image](https://cloud.githubusercontent.com/assets/18452495/15949922/9baa7302-2e74-11e6-8552-4f8fc75a6287.png)

**Comment by nattyco** [comment]
@MaviDavsa @IsbetVR  corregido en la version 16.2 de la apk

**Comment by maydiamc** [comment]
en mi dispositivo, con la version 16.2, si funciona el boton +
@nattyco 
![screenshot_2016-06-07-11-03-21](https://cloud.githubusercontent.com/assets/17274154/15966218/ffb92880-2eeb-11e6-8dfe-7fbcbb71325b.png)

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 513 LPW V16.1
Nexus 5- 5.0.0 480dpi
El boton si funciona.

**Comment by arosiopr** [comment]
en mi dispositivo funciona con la version 16.1 de la apk

**Comment by sanro14** [comment]
@nattyco a mi me funciona en la versión 16.3

**Comment by IsbetVR** [comment]
@nattyco @MaviDavsa ya funciona! 
LPW v16.3
Creo que se puede cerrar ;)
