### ISSUE TITLE
Community-Connectión: se quedo cargando los user agregados

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#514]
#### Nombre pantalla
Connectión

##### Reporte de error: 

   *Al ingresar a la Cripto Wallet usar para revisar las notificaciones, agregue a dos contactos y cuando entre a connctions se quedo cargando y no para de cargar. Hay que salir de la apk y al ingresar dejo de cargar. Vuelvo a agregar a  Runen por las notificaciones pero al entrar a contactos se queda congelado nuevamente. 
   
![se quedo cargando en contactos 1](https://cloud.githubusercontent.com/assets/17283358/15947954/0890325c-2e68-11e6-85e1-a86a1bbb6b84.png)

LPW V16
#### Dispositivo desde donde se realizo la prueba

![nexus 5](https://cloud.githubusercontent.com/assets/17283358/15948043/7245edea-2e68-11e6-934b-05c9030bc6ae.png)

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 514 LPW V16.1
Nexus 5- 5.0.0 480dpi
Persiste el error 
![caso 514](https://cloud.githubusercontent.com/assets/17283358/15965988/cbd77cac-2eea-11e6-83e6-616b6001356c.png)
 que se reportó.

**Comment by kmiloxvii** [comment]
en la versión 17 a mi ya no me sucede esto

Telefono de prueba 
![phone blu](https://cloud.githubusercontent.com/assets/2491042/16024435/39a2b7f6-3198-11e6-8a95-0a83dea07473.png)

**Comment by maydiamc** [comment]
no sucede en mi dispositivo en la version 17 @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025144/6df40dec-318f-11e6-8521-d5f63e824e01.png)

**Comment by dorzar1989** [comment]
En el dispositivo que manejo con la version 17 de la CBP continua este error

![screenshot_3](https://cloud.githubusercontent.com/assets/19670319/16084488/ce97d5d0-32e2-11e6-8485-4513e7a9c181.png)



![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/16084487/ce72fb66-32e2-11e6-9db2-b9e6af6f0a75.png)

**Comment by AdryCanonico** [comment]
@MaviDavsa @yolandayancel  En la versión 18.3 CBP ya no se ve el error

**Comment by yolandayancel** [comment]
Prueba 27-06-2016

Corregido el Error- Cerrar caso
Caso 514 LPW- (CBP V 18.3)
Nexus 5 5.0.0
En el emulador ya no se presenta el error. Ingresa a las notificacones.
![caso 514 cerrar](https://cloud.githubusercontent.com/assets/17283358/16380909/86c08350-3c43-11e6-820f-88014d37e1c3.png)
[logcat caso 514.txt](https://github.com/Fermat-ORG/beta-testing-program/files/334912/logcat.caso.514.txt)
