### ISSUE TITLE
LPW - No muestra nada en la pantalla del Chunk Value

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#515]
#### Chunk Value

-----

##### Reporte de error: 

   *Cuando voy a la opción de "Chunk Value" me sale el aviso de "Recovering from system error" (Pantalla 1) e inmediatamente se queda la pantalla en gris (Pantalla 2)
   
------
#### Pantalla 1

![screenshot_62](https://cloud.githubusercontent.com/assets/19142276/15949268/3f8b128e-2e74-11e6-9b2a-33608bd1f5a7.jpg)

#### Pantalla 2

![screenshot_63](https://cloud.githubusercontent.com/assets/19142276/15949271/480ac1ac-2e74-11e6-8cf9-51c7f5302adf.jpg)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

Modelo: HTC One X
Versión de android: 4.2.2

![htc one x](https://cloud.githubusercontent.com/assets/19142276/15949331/9f99781e-2e74-11e6-9616-9855a982e367.jpg)

**Comment by IsbetVR** [comment]
@nattyco @sanro14 @MaviDavsa

**Comment by IsbetVR** [comment]
Versión LPW v16

**Comment by kmiloxvii** [comment]
Me pasa lo mismo LPW 16 

![phone blu](https://cloud.githubusercontent.com/assets/2491042/15949448/f887b324-2e7d-11e6-93c0-e0e7fe6e926a.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-16
Caso 515 LPW V16
Nexus 5- 5.0.0 480dpi
Ocurre lo mismo que se reportó.
![caso 515](https://cloud.githubusercontent.com/assets/17283358/15949504/dd50b170-2e71-11e6-9191-cdcc7118e026.png)

**Comment by maydiamc** [comment]
en mi dispositivo fisico tambien sucede lo mismo y muestra un error
version 16 dela apk @nattyco 

![screenshot_2016-06-09-18-52-19](https://cloud.githubusercontent.com/assets/17274154/15949512/ed1695fc-2e71-11e6-8f6c-86c5c07c1695.png)

Dispositivo
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/15949523/03bf9b5a-2e72-11e6-8fc7-9c530229b431.png)

**Comment by arosiopr** [comment]
sucede lo mismo en mi dispositivo

![screenshot_2016-06-09-19-09-01](https://cloud.githubusercontent.com/assets/5313326/15949568/5724e69c-2e72-11e6-8ed0-224eb71923a7.png)

![screenshot_2016-06-08-19-21-55](https://cloud.githubusercontent.com/assets/5313326/15949576/6c8ddf2a-2e72-11e6-9f31-4c10ccf2549e.png)

**Comment by nattyco** [comment]
@IsbetVR   @MaviDavsa  verificar en la version 16.2 de la apk

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 515 LPW V16.1
Nexus 5- 5.0.0 480dpi
No ocurre lo mismo que se reportó.

**Comment by maydiamc** [comment]
en mi dispositivo, con la version 16.2, esto se soluciono @nattyco 
![screenshot_2016-06-07-11-03-21](https://cloud.githubusercontent.com/assets/17274154/15966039/03bb67b4-2eeb-11e6-9764-13e784be6b90.png)

**Comment by arosiopr** [comment]
en mi dispositivo funciona bien el chunk value en la version 16.2 de la apk

**Comment by sanro14** [comment]
@nattyco a mi si me sale la pantalla de chunk value

**Comment by kmiloxvii** [comment]
En mi dispositivo funciona correctamente

**Comment by IsbetVR** [comment]
@nattyco en la versión v16.3 de LPW ya no se refleja este error. Se ve bien el "Chunk Value"
@MaviDavsa creo que se puede cerrar este caso ;)
