### ISSUE TITLE
LPW-Loss Protect Wallet-Request: El botón del Sent esta montado.

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#516]
#### Nombre pantalla

Requests

##### Reporte de error: 

   *Estando en la pantalla de REQUESTS de la Loss Protect Wallet, se observa como el botón para enviar los request esta montado sobre las letras. Moví la pantalla hacia arriba
![montado el boton de send request 2](https://cloud.githubusercontent.com/assets/17283358/15949338/75d5dd82-2e70-11e6-9d1d-30ccc68e51d7.png)

 Hacia bajo. pero igual sigue montada sobre las letras.
![montado el boton de sent](https://cloud.githubusercontent.com/assets/17283358/15949368/b0d2b07c-2e70-11e6-9920-0012e0af96b5.png)

LPW V16

#### Dispositivo desde donde se realizo la prueba
![nexus 5](https://cloud.githubusercontent.com/assets/17283358/15949376/beb6d1aa-2e70-11e6-91a7-28eddedf5034.png)

**Comment by yolandayancel** [comment]
@MaviDavsa 
Este caso ya fué abierto es el 507. María por favor cierra este. Voy a comentar en ese.

**Comment by MaviDavsa** [comment]
Issues ya montado! :)
