### ISSUE TITLE
LPW_pantalla de contactos en blanco

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#517]
### Nombre de la Aplicación: LPW

-----

##### Reporte de error: 

   *En esta apk, al ingresar, se veia perfecta la pantalla de contacto, luego de usarla un rato, la pantalla de contacto quedo por completo en blanco y no se mostraba ningun contacto de los que ya tenia agregados, fue necesario reiniciar la apk un par de veces para que la pantalla volviera a la normalidad.
   
![screenshot_2016-06-09-18-33-16](https://cloud.githubusercontent.com/assets/17274154/15949435/495edc58-2e71-11e6-94f6-cbfe308dca3f.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/15949430/3aa68ed6-2e71-11e6-8186-7982143f16ae.png)

**Comment by maydiamc** [comment]
@nattyco version 16 de la apk

**Comment by arosiopr** [comment]
secede lo mismo en mi dispositivo

![screenshot_2016-06-09-18-24-13](https://cloud.githubusercontent.com/assets/5313326/15949526/06997e4a-2e72-11e6-9334-dc890e28b641.png)


![screenshot_2016-06-08-19-21-55](https://cloud.githubusercontent.com/assets/5313326/15949518/f6f483d6-2e71-11e6-8962-b6efc02ebea2.png)

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-16
Caso 517 LPW V16
Nexus 5 5.0.0 480dpi
Estando en contactos y lograr entrar a agregar los fermas user, estos aparecieron. Pero al retroceder e ingresar nuevamente en contacto la pantalla está en blanco.
![caso 517](https://cloud.githubusercontent.com/assets/17283358/15949673/106c1620-2e73-11e6-8b3d-945c7274ae41.png)

**Comment by yolandayancel** [comment]
Prueba 10-06-16
Caso 517 LPW V16.1
Nexus 5- 5.0.0 480dpi
Si muestra los contactos

**Comment by maydiamc** [comment]
en la version 16.2 sigue sucediendo este error.! @nattyco

**Comment by danielaporras** [comment]
En la versión 16.1 aun sigue saliendo este mismo error.

![screenshot_12](https://cloud.githubusercontent.com/assets/19656830/15968697/a8714476-2ef6-11e6-851c-e659de79db57.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by maydiamc** [comment]
en la version 17 esto se soluciono @nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
