### ISSUE TITLE
LPW_ error en sent request to contac

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#518]
### Nombre de la Aplicación: LPW

-----

##### Reporte de error: 

   *En la version 16 de la apk, al intentar enviar un request, desde el boton request, en la pantalla de detalle de contacto, la pantalla se coloca en gris, se muestra "oops recovering from system error" y solo sale el teclado, pero no se muestra el formulario
NOTA: no me dio tiempo de tomar el capture y que se viera el error 

![screenshot_2016-06-09-19-26-16](https://cloud.githubusercontent.com/assets/17274154/15949984/e6fd3e84-2e74-11e6-8357-ca2e29f6c107.png)

  *Mientras que si intento enviar un request desde el menu PAYMENT REQUEST, al presionar el boton de enviar (avioncito), este solo despliega el teclado y queda de fondo el menu, pero no aparece el formulario de envio
   
![screenshot_2016-06-09-19-17-23](https://cloud.githubusercontent.com/assets/17274154/15949987/f0571f90-2e74-11e6-985f-1d2b98eda988.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/15949992/fc6a0194-2e74-11e6-8a24-f653ef709d88.png)

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 09-06-16
Caso 515 LPW V16
Nexus 5- 5.0.0 480dpi
No ocurre lo mismo. Este deja enviar los request.
![caso 518](https://cloud.githubusercontent.com/assets/17283358/15950120/dc9ac280-2e75-11e6-9c79-e9d613a7aca2.png)

**Comment by nattyco** [comment]
@maydiamc  @MaviDavsa  verificar en la version 16.2 de la apk

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 10-06-16
Caso 518 LPW V16.1
Nexus 5- 5.0.0 480dpi
Si deja enviar los request.

**Comment by maydiamc** [comment]
se soluciono este problema en la version 16.2.! @nattyco

**Comment by MaviDavsa** [comment]
Perfecto.... Solucionado.
