### ISSUE TITLE
LPW-  ERROR AL SELECCIONAR CONTACTO

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#519]
##### Reporte de error: 

  
Al seleccionar un contacto aparece una raya blanca sobre el contacto.

![screenshot_2016-06-10-09-43-23](https://cloud.githubusercontent.com/assets/17262077/15967261/bcba39ca-2ef0-11e6-8960-5fbbc0be71e0.png)

Dispositivo donde se realizó la prueba:

![screenshot_2016-06-10-10-04-42](https://cloud.githubusercontent.com/assets/17262077/15967270/c255363c-2ef0-11e6-8cb9-4e10cd1fbaf3.png)

**Comment by MaviDavsa** [comment]
![screenshot_2016-06-10-11-10-21](https://cloud.githubusercontent.com/assets/17273005/15969631/aa92dee6-2efa-11e6-8c93-b78524b59ced.jpg)


![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/15969642/b0bfd9cc-2efa-11e6-8c3c-3eae5f315767.jpg)

**Comment by nattyco** [comment]
@Gabymorillo @MaviDavsa   verificar en la nueva version de la apk

**Comment by sanro14** [comment]
@Gabymorillo @MaviDavsa @Gabymorillo a mi no me sale ya ese error.. por favor revisen..

**Comment by kmiloxvii** [comment]
En mi dispositivo ya no sale este error

**Comment by Gabymorillo** [comment]
Solucionado @nattyco
