### ISSUE TITLE
Bitcoin Wallet

### ISSUE THREAD

**Issue by sadigarcia** [Fermat-ORG/beta-testing-program#52]
#### Nombre pantalla
Available Balance

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   Al darle a la opcion de "available balance" y dejarlo hundido por un momento me arroja de una vez la suma de 100bitcoins y no de 50bitcoins. Nose hasta que momento dejar hundido la pantalla del telefono para que solo me tome una sola cantidad
------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. 
   
------

Modelo de android: LG-E977 / Version:4.4.2

**Comment by nattyco** [comment]
@sadigarcia tienes que presionar unos segundos y soltar, vas a ver el cartel que dice Mati Bitcoins, si presionas y sueltas y presionas de nuevo va a generar otra transacción de solicitud de btc.

**Comment by sadigarcia** [comment]
ok natty, entendido
