### ISSUE TITLE
LPW- Add Fermat user-Checkbox con fondo negro

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#520]
##### Reporte de error: 

   *En LPW versión 16.1, en Loss Protected wallets  pantalla de Add Fermat user, salio el siguiente error en los Checkbox ( Dentro del cuadro azul aparece un cuadro negro y y al seleccionar el Checkbox sale en negro el fondo).

![screenshot_10](https://cloud.githubusercontent.com/assets/19656830/15969130/61b54b20-2ef8-11e6-96b8-2b3f384d9d2f.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/19656830/15969132/63f42474-2ef8-11e6-8fe5-923151a6ffa9.png)

   
------

#### Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

@MaviDavsa

**Comment by AdryCanonico** [comment]
@nattyco en mi emulador también surge este error. 

![screenshot_3](https://cloud.githubusercontent.com/assets/18584168/15969716/015878c6-2efb-11e6-8c16-d1360b580046.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/18584168/15969715/0147b1a8-2efb-11e6-91e0-b758c7142f3e.png)

DISPOSITIVO:

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/15969756/323fb3f0-2efb-11e6-8ea9-fc0e88ca951d.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version 17 sigue persistiendo el fondo en negro en los check

![chek en negro](https://cloud.githubusercontent.com/assets/18584168/16012129/dd708314-3151-11e6-8d47-6af67ed8512a.png)

![imagenes contctos](https://cloud.githubusercontent.com/assets/18584168/16012128/dd715e88-3151-11e6-9811-4cb984b22f61.png)

**Comment by Gabymorillo** [comment]
En la versión 18.8 no aparece ese error. 

![screenshot_2016-07-01-11-20-01](https://cloud.githubusercontent.com/assets/17262077/16526271/32713652-3f7a-11e6-99b5-ac908842b3e2.png)

![screenshot_2016-07-01-11-18-35](https://cloud.githubusercontent.com/assets/17262077/16526284/3d3d929c-3f7a-11e6-8ac1-02166c8f1580.png)
