### ISSUE TITLE
LPW-Home-Error

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#521]
##### Reporte de error: 

   *En LPW version 16.1 al entrar al Home de Loss Protected wallets aparece el siguiente error.

![screenshot_13](https://cloud.githubusercontent.com/assets/19656830/15969298/3eabeeb2-2ef9-11e6-9394-24a06926ded9.png)

   
------

#### Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0
 
@MaviDavsa

**Comment by nattyco** [comment]
@danielaporras  verificar en la nueva version de la apk

**Comment by sanro14** [comment]
@danielaporras revis este caso, a mi no me da el error en la nueva versión, pero revisa tu.

**Comment by kmiloxvii** [comment]
Este caso no me sucede en la version 17

**Comment by maydiamc** [comment]
no sucede en la version 17 en mi dipositivo @nattyco 
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16025076/0c8fdc2a-318f-11e6-9b68-2751bf31b7e8.png)

**Comment by kmiloxvii** [comment]
no sucede en la version 17 
![phone](https://cloud.githubusercontent.com/assets/2491042/16026853/c4147c08-31a7-11e6-96bc-26f812fe2fa3.png)

**Comment by MaviDavsa** [comment]
Solucionado!
