### ISSUE TITLE
LPW- NO TIENEN FUNCIÓN EL BOTÓN DE (+) ANARANJADO 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#522]
### Nombre de la Aplicación 

LPW
-----

##### Reporte de error: 

   *el boton de (+) que tiene cada contacto no tiene función al darle click y o me deja entrar a la ficha del contacto
   

![contacts](https://cloud.githubusercontent.com/assets/18584168/15969904/dd040bc4-2efb-11e6-94bd-6d96651cde22.png)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![samsung galaxy s6](https://cloud.githubusercontent.com/assets/18584168/15969920/e7cc2870-2efb-11e6-9978-46dbfab3e8eb.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  se le puso el evento de click a toda la fila lo voy a verificar

**Comment by AdryCanonico** [comment]
@nattyco  en la versión 17 ya los botones tienen función. Se puede cerrar el caso
