### ISSUE TITLE
CBP- Bicoin Wallet and Providers: no guarda los cambios configurados

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#523]
#### Nombre pantalla
Bitcoin Wallet and Providers

### Nombre de la Aplicación 

CBP V16.5
-----

##### Reporte de error: 

   1- Estando en la Crypto customer configurandola: Entro en la pantalla de la  Bitcoin Wallet and Providers y configuro los Provider:
![no guarda los cambios 1](https://cloud.githubusercontent.com/assets/17283358/15982935/af4f3bda-2f60-11e6-9781-feb7d97d37f7.png)

2- le doy a SAVE para guardar los cambios configurados y cuando ingreso nuevamente, no los guardo (los cambios):
![no guarda los cambios 2](https://cloud.githubusercontent.com/assets/17283358/15982941/04fcdf42-2f61-11e6-8b53-6c8fe244f59f.png)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![nexus 5](https://cloud.githubusercontent.com/assets/17283358/15982946/3d2907e2-2f61-11e6-8ac5-c32904adcd99.png)

**Comment by yalayn** [comment]
Hola @yolandayancel como estas?, veo en las dos imagenes el provider 
**BTC/ARS BITCOINVENEZUELA**. 
Por que dices que no se guardo el providers?. Por fa me podrias explicar mejor. Gracias.

**Comment by yolandayancel** [comment]
@yalayn 
Buenos días
Con respecto a tu pregunta, te explico lo que ocurre:
Cuando seleccionas en (YOUR PROVIDERS) foto 1 cualquier moneda, en este caso BTC y Pesos argentinos, escoges el Providers, salvas o guardas y te sales de la pantalla de la Bitcoin wallet and providers.
![caso 523 1](https://cloud.githubusercontent.com/assets/17283358/16006690/32702a46-3138-11e6-90aa-d32b85842b16.png)
 Al ingresar nuevamente, los cambión no se guardaron, vuelve a estar pesos argentinos y pesos argentinos.
![caso 523 2](https://cloud.githubusercontent.com/assets/17283358/16006742/7aded0ac-3138-11e6-92f8-4aa01af70bf9.png)
Saludos

**Comment by yalayn** [comment]
Buenos dias @yolandayancel como estas?
OK ahora si entiendo. Bueno en realidad esos valores no deberían guardarse ya que solo se utilizan para poder registrar los Providers que sean necesarios. Lo que si debería guardar bien y no desaparecer es el par que se crea cuando le das al botón PROVIDERS. El que aparece en la parte de abajo. Como el que tenias en las imágenes anteriores que decía:
**"BTC/ARS BITCOINVENEZUELA."**

**Comment by maydiamc** [comment]
en la version 16.6, se presento esta incognita, se hace la recomendacion de colocar un texto, o alo que indique que eso es un selec, porque confunde un poco al usuario @nelsonalfo

**Comment by abicelis** [comment]
@maydiamc En la version 17.4 se ve mejor explicado lo que hace el boton ("Add Provider" en vez de "Providers"), asi como un texto que explica como funciona esa seccion del wizard.

![image](https://cloud.githubusercontent.com/assets/9850854/16136554/68ad02ae-33f5-11e6-9e9e-a9702aef603b.png)

**Comment by MaviDavsa** [comment]
@maydiamc @yolandayancel Revisen esto por favor!!!

**Comment by yolandayancel** [comment]
@yalayn @abicelis 
Prueba 19-06-16
Caso 523 CBP V 17.4
Nexus 5 5.0.0
Alejandro ahora sale  mejor explicado lo que hace el boton ("Add Provider" ) y como explicaste, lo que debe quedar guardado son los provider y eso lo hace bien. Cerrar el caso
![caso 523](https://cloud.githubusercontent.com/assets/17283358/16193240/bc69d7fe-36b7-11e6-8eaa-4a50194bb5c3.png)
[logcat caso 523.txt](https://github.com/Fermat-ORG/beta-testing-program/files/323299/logcat.caso.523.txt)
