### ISSUE TITLE
BITCOIN WALLET - ERROR SE VISUALIZA EL TECLADO AL INTERACTUAR CON LA APP

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#524]
#### Nombre pantalla 
HOME, CONTACT

### Nombre de la Aplicación 
BITCOIN WALLET

-----

##### Reporte de error: 

   *En la Version 16.5 CBP. Cuando se entra alguna pantalla donde se utiliza el teclado y se cambia Ejemplo: al Home se despliega el teclado del teléfono. Hay que darle hacia atrás o cambiar la ubicación de la aplicación por el menú para que desaparezca. 

![screenshot_2016-06-11-15-55-49](https://cloud.githubusercontent.com/assets/18584168/15987327/6cb17b7e-2fee-11e6-872e-69f8ce1eb800.png)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987329/77398186-2fee-11e6-913f-51a6323217d5.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  estas usando la version de CBP que puede no coincidir con la version de Bitcoin Wallet que yo tengo.

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo Chicos necesito que me actualicen esta apk en su apk!

**Comment by AdryCanonico** [comment]
@nattyco  en la version 18 CBP persiste el error

**Comment by yalayn** [comment]
Hola @MaviDavsa la bitcoin wallet se esta actualizando tan seguido como es posible en las versiones de CBP.

**Comment by abicelis** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nattyco Esto me pasa pero al darle hacia atrás se va el teclado y me aparece el menú sin ningún problema! No se si a @AdryCanonico Le sale o no el menú!

**Comment by AdryCanonico** [comment]
@nattyco @MaviDavsa Donde estaba el teclado queda en negro algunas veces al darle para atrás.

**Comment by AdryCanonico** [comment]
@nattyco  este error no se ha podido verificar porque aun no se puede probar en telefonos físicos la app

**Comment by AdryCanonico** [comment]
en la version 20.7 de cbp mejoro la interacción del teclado pero aun persiste.

**Comment by andreagmarcano** [comment]
En la version 20.9.1 ya no sucede el error.
![image](https://cloud.githubusercontent.com/assets/18452495/17033036/2a2eebd0-4f4a-11e6-9284-0ba2caeae766.png)

![image](https://cloud.githubusercontent.com/assets/18452495/17033079/60270e2a-4f4a-11e6-89f5-5ffed5d7c52d.png)

@nattyco

**Comment by arosiopr** [comment]
en la versión 20.9.1 de la bitcoin wallet no se visualiza ese error teléfono Físico Alcatel OnetouchMpop android 4.1.1. @MaviDavsa

**Comment by MaviDavsa** [comment]
Solucionado
