### ISSUE TITLE
BITCOIN WALLET - MEJORAS EN EL BOTON DE LA COMMUNITY

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#525]
#### Nombre pantalla

ADD FERMAT USER

### Nombre de la Aplicación 

BITCOIN WALLET
-----

##### Reporte de error: 

   *Seria bueno mejorar el botón que nos dirige a la community ya que este se ve algo borroso y parece ser parte del fondo de la app no un botón. 
   
![screenshot_2016-06-11-15-54-32](https://cloud.githubusercontent.com/assets/18584168/15987359/1f60680c-2fef-11e6-9c75-7e3907932310.png)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987358/19472da2-2fef-11e6-833b-694b86949749.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis Chicos necesito las nuevas versiones de las apk dentro de las actualizaciones que me entreguen porque las chicas hacen las pruebas de forma integral.

**Comment by yalayn** [comment]
Hola @MaviDavsa la bitcoin wallet se esta actualizando tan seguido como es posible en las versiones de CBP.

**Comment by AdryCanonico** [comment]
@arnaldos

**Comment by arnaldos** [comment]
Este recurso fue enviado a @nattyco para ser aplicado en el action bar para que no tape a los futuros contactos.

Dejo referencia de como debe verse 

![image](https://cloud.githubusercontent.com/assets/13594347/16469091/f82d2062-3e18-11e6-9ca0-af48465fafd9.png)

**Comment by abicelis** [comment]
@nattyco

**Comment by marielis-urbina** [comment]
En la versión 20.1 de la Bitcoin Wallet, ya no sucede este error, el botón que nos dirige a la community ya no se ve borroso.

![boton](https://cloud.githubusercontent.com/assets/19353722/16699357/a5e7d314-4521-11e6-8a45-63a9378cbbc2.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16699370/b0d582d0-4521-11e6-9cf7-769374eac8f8.png)

**Comment by arosiopr** [comment]
en la version 20.4 de cbp persiste el error

![screenshot_97](https://cloud.githubusercontent.com/assets/5313326/16767298/b6ef974e-480c-11e6-8733-dc1a4895b957.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16767301/babc32ec-480c-11e6-8b59-b047fe1c14cb.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.5 el botón sigue borroso y es difícil intuir que efectivamente sea un botón:

![trr](https://cloud.githubusercontent.com/assets/19883115/16807456/7b079ecc-48e6-11e6-9651-48358b52b5a8.png)


![chi](https://cloud.githubusercontent.com/assets/19883115/16807465/87a85db0-48e6-11e6-9924-09460572fb40.png)

**Comment by sanro14** [comment]
@nattyco esta pantalla se va a mantener o se realizará el cambio a como el capture que colocó arnaldo?

**Comment by AdryCanonico** [comment]
En la version 20.5 cbp aun no se implementa la mejora

**Comment by nattyco** [comment]
@AdryCanonico  implemente el boton en el toolbar en la nueva version.

**Comment by marielis-urbina** [comment]
En la versión 20.6 de CBP,  ya este error esta corregido

![listo](https://cloud.githubusercontent.com/assets/19353722/16858364/59e0ae46-49f4-11e6-9c0c-dd579333a270.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16858365/5f9ce0d4-49f4-11e6-8670-c957256f20fb.png)
