### ISSUE TITLE
BITCOIN WALLET -  BOTONES SETTINGS TAPADOS POR EL TEXTO

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#526]
#### Nombre pantalla

SETTINGS

### Nombre de la Aplicación 

BITCOIN WALLET
-----

##### Reporte de error: 

   *En la Version 16.5 de CBP. El botón del Settings se ve muy grande, tanto que se ven como fondos del texto. 
Sugiero que para esta version de Android se busque un botón mas amigable,

![screenshot_2016-06-11-15-55-13](https://cloud.githubusercontent.com/assets/18584168/15987371/89402398-2fef-11e6-8d4f-8b9f581464fe.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987372/913eabb4-2fef-11e6-9dea-0c429041b6ed.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis Chicos necesito las nuevas versiones de las apk dentro de las actualizaciones que me entreguen porque las chicas hacen las pruebas de forma integral.

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 526 CPB V16.5
Nexus 5 5.0.0
En este emulador no ocurre lo reportado.
![caso 526](https://cloud.githubusercontent.com/assets/17283358/16042185/56246d96-3203-11e6-883c-ab7d3b854ae3.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version 18 de CBP Sigue persistiendo el error.

**Comment by abicelis** [comment]
@nattyco

**Comment by Gabymorillo** [comment]
En la versión 18.8 ya no aparece ese error. 

![screenshot_2016-07-01-11-26-37](https://cloud.githubusercontent.com/assets/17262077/16526398/eab33b5c-3f7a-11e6-8ec9-28408032e97c.png)

**Comment by AdryCanonico** [comment]
@nattyco en la version 19.2 aun persiste el error.

![screenshot_2016-07-04-13-44-41](https://cloud.githubusercontent.com/assets/18584168/16567717/a6938ee6-41ef-11e6-86b8-765c94fa167d.png)


Archivo Alogcat:

[alogcat.2016-07-04-13-55-30-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346704/alogcat.2016-07-04-13-55-30-0430.txt)


teléfono físico:

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16567724/badafe3e-41ef-11e6-8f04-600b0f209ca3.png)

**Comment by nelsondb** [comment]
En la versión 20.1 no aparece este error.

![screenshot_2](https://cloud.githubusercontent.com/assets/20217119/16699360/a7e0ac72-4521-11e6-9a98-c50e5a06c904.jpg)


![nexus 4 5 0](https://cloud.githubusercontent.com/assets/20217119/16699365/aa6d009e-4521-11e6-85e9-249056c2a694.jpg)

**Comment by AdryCanonico** [comment]
en la version 20.7 de cbp persiste el error

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP en mi emulador no persiste este error

![set](https://cloud.githubusercontent.com/assets/19353722/16919189/b1ccc556-4cd6-11e6-9e52-42484c9216f4.png)


![samsung](https://cloud.githubusercontent.com/assets/19353722/16919141/83f47ce6-4cd6-11e6-86e9-96d5cdf08ad8.png)

**Comment by GeronimoVierma** [comment]
En mi teléfono físico el error no persiste (Android 4.1.1):
(Probado desde la versión 20.7 de CBP )

![screenshot_2016-07-15-19-04-51](https://cloud.githubusercontent.com/assets/19883115/17028861/f5c4acda-4f36-11e6-8b27-5bd0ebc5ddc6.png)

Teléfono físico:
![screenshot_2016-07-14-18-31-45](https://cloud.githubusercontent.com/assets/19883115/17028870/fe333ae4-4f36-11e6-967d-2ad52c5d0b8d.png)

**Comment by yolandayancel** [comment]
Prueba 21-07-16
Caso 526 Versión 20.9
Nexus 5 5.0.0
Esto no ocurre:
![caso526](https://cloud.githubusercontent.com/assets/17283358/17029127/fd2e4e94-4f37-11e6-89f8-8c5134e53b42.png)

**Comment by arosiopr** [comment]
@sanro14 @AdryCanonico solucionado en mi teléfono personal Alcatel OnetouchMpop android 4.1.1.

![screenshot_2016-07-21-13-37-20](https://cloud.githubusercontent.com/assets/5313326/17032668/7fcaf176-4f48-11e6-87c6-795bc3adedce.png)

![screenshot_2016-07-21-13-38-46](https://cloud.githubusercontent.com/assets/5313326/17032674/841bbd82-4f48-11e6-8c57-5e895cff0627.png)
