### ISSUE TITLE
CBP - CASH WALLET - STATUS BAR SE POSICIONA ARRIBA DEL ACCION BAR

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#527]
#### Nombre pantalla

TODA LA APLICACION

### Nombre de la Aplicación 

CBP - CASH WALLET 

-----

##### Reporte de error: 

   *El Status Bar se posiciona arriba del Acción Bar de la app

![screenshot_2016-06-10-14-35-08](https://cloud.githubusercontent.com/assets/18584168/15987406/18783568-2ff1-11e6-9e21-f182b20de548.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![5 0 delio](https://cloud.githubusercontent.com/assets/18584168/15987408/24912aa8-2ff1-11e6-829d-11fd0c260382.jpg)

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987409/24980972-2ff1-11e6-87a5-a7f0f2e2869f.png)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 527 CPB V16.5
Nexus 5 5.0.0
En este emulador no ocurre lo reportado.
![caso 527](https://cloud.githubusercontent.com/assets/17283358/16042084/bc6459aa-3202-11e6-8b2d-c226ac9525ae.png)

**Comment by Gabymorillo** [comment]
En la versión 16.6 persiste. 

![screenshot_2016-06-14-19-57-41](https://cloud.githubusercontent.com/assets/17262077/16063984/3119db8a-3267-11e6-96a6-31fccd15aef7.png)

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16063988/33ea2f54-3267-11e6-805c-bb4490209054.png)

**Comment by abicelis** [comment]
@AdryCanonico no encuentro ninguna forma de arreglar ese error por ahora
@Gabymorillo no entiendo tu post, en tu screenshot no veo el error que indica @AdryCanonico 

Este error por ahora se quedara asi

**Comment by MaviDavsa** [comment]
@AdryCanonico Trata de ver si puedes descargar el programa para ver el txt. en los telefonos bella!

**Comment by AdryCanonico** [comment]
@MaviDavsa El programa ya lo tengo descargado. Puedo agregar al caso el txt si así lo necesitas.

**Comment by MaviDavsa** [comment]
@arnaldos

**Comment by abicelis** [comment]
@AdryCanonico @MaviDavsa @Gabymorillo @yolandayancel La gente de android-upgrade hizo mejoras sobre esto, plz revisen la version 19.1 y me avisan.

**Comment by AdryCanonico** [comment]
@abicelis  Persiste el error. Se reabre el caso. 

![Uploading Screenshot_2016-07-05-19-35-56.png…]()

**Comment by MaviDavsa** [comment]
![screenshot_2016-07-07-15-03-09](https://cloud.githubusercontent.com/assets/17273005/16669248/72e275b0-4462-11e6-9a3a-128d685f54e7.jpg)

Persiste el error! en la version 19.9 de la CBP

**Comment by nelsonalfo** [comment]
pueden revisar esto en la ultima versión que tienen actualmente?

**Comment by Gabymorillo** [comment]
En la versión 20.1 en el teléfono físico no presenta este error.

**Comment by dorzar1989** [comment]
En la version 20.1 de CBP no presenta este error.

![screenshot_40](https://cloud.githubusercontent.com/assets/19670319/16688576/a740f6da-44ec-11e6-8b1c-bfeec126d679.png)


- MOVIL: EMULADOR

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16688589/b46369ce-44ec-11e6-80ba-b7aee26c2118.png)

**Comment by sanro14** [comment]
Solucionado.
