### ISSUE TITLE
CBP - CRYPTO CUSTOMER - STATUS BAR SE POSICIONA ARRIBA DEL ACCION BAR 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#528]
#### Nombre pantalla

TODA LA APLICACIÓN

### Nombre de la Aplicación 

CBP - CRYPTO CUSTOMER
-----

##### Reporte de error: 

   *El Status Bar se posiciona arriba del Acción Bar de la app, impidiendo leer correctamente el texto.

![screenshot_2016-06-11-15-23-19](https://cloud.githubusercontent.com/assets/18584168/15987531/8a8bbd8e-2ff4-11e6-995a-5da3dc12971e.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987536/a6227ace-2ff4-11e6-814b-11d7f11782ad.png)

![5 0 delio](https://cloud.githubusercontent.com/assets/18584168/15987537/a627af94-2ff4-11e6-8025-9139c8390984.jpg)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 528 CPB V16.5
Nexus 5 5.0.0
En este emulador no ocurre lo reportado.
![caso 528](https://cloud.githubusercontent.com/assets/17283358/16042033/6d4c6420-3202-11e6-8c3e-4b8746083c53.png)

**Comment by abicelis** [comment]
@AdryCanonico igual que aqui: https://github.com/Fermat-ORG/beta-testing-program/issues/527#issuecomment-226606863, por ahora ni idea como resolver esto :/

**Comment by AdryCanonico** [comment]
ok @abicelis yo estoy al pendiente de este caso y el otro si me avisas que esta arreglado. :wink:

**Comment by abicelis** [comment]
@AdryCanonico @yolandayancel La gente de android-upgrade hizo mejoras sobre esto, plz revisen la version 19.1 y me avisan.

**Comment by yolandayancel** [comment]
@abicelis 
Prueba 04-07-16
Caso 528 CPB V19.2
Nexus 5 5.0.0
En este emulador no ocurre lo reportado.
![528](https://cloud.githubusercontent.com/assets/17283358/16560645/b33046e4-41c2-11e6-947d-3165ecde937d.png)
[logcat528.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346278/logcat528.txt)

**Comment by JeanFranco498** [comment]
En CBP 21.0 esta ocurriendo este error en la comunity solamente 
Emulador: Nexus 5
Android 4.4.4 


![comunity](https://cloud.githubusercontent.com/assets/19807906/17157580/5378e6e0-535e-11e6-9689-9e44d8380568.jpg)

**Comment by GeronimoVierma** [comment]
En la versión 21.1 no aparece el error:

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17254614/7cecc97a-5583-11e6-9568-57732cb5a03d.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17254631/8e1f3dd6-5583-11e6-9cc1-b0d6ef1de75f.png)

**Comment by yolandayancel** [comment]
Prueba 29-07-16
Caso 528 CBP 21.1
![screenshot_2016-07-29-14-41-40](https://cloud.githubusercontent.com/assets/17283358/17260048/3b8c8074-559c-11e6-98cc-c9154d9208ca.png)

Celular:
![screenshot_2016-07-29-14-50-29](https://cloud.githubusercontent.com/assets/17283358/17260058/47b4bee8-559c-11e6-8d62-3a6689fcd5a9.png)

**Comment by arosiopr** [comment]
en la versión 21.7 de CBP se soluciono el error en mi dispositivo @sanro14

**Comment by marielis-urbina** [comment]
En la versión 21.7 de CBP no sucede este error en mi emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17554786/989320f6-5eda-11e6-88fe-33784263dc21.png)
