### ISSUE TITLE
CBP - CRYPTO CUSTOMER - (X) TAPA EL TEXTO DE LOS PROVIDERS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#529]
#### Nombre pantalla

BITCOIN WALLET AND PROVIDERS

### Nombre de la Aplicación 

CBP - CRYPTO CUSTOMER
-----

##### Reporte de error: 

   *Cuando el nombre es muy largo en el Providers seleccionado la X se monta arriba del texto del nombre seleccionado. 

![screenshot_2016-06-11-15-24-10](https://cloud.githubusercontent.com/assets/18584168/15987609/80b013ca-2ff7-11e6-883a-8514917dfffc.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/15987613/893cf80a-2ff7-11e6-8a07-6603daeda8dd.png)

![5 0 delio](https://cloud.githubusercontent.com/assets/18584168/15987614/893df624-2ff7-11e6-816c-88492b41f3dd.jpg)

**Comment by AdryCanonico** [comment]
@abicelis

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 529 CPB V16.5
Nexus 5 5.0.0
En este emulador ocurre lo reportado (letras montadas)
![caso 529](https://cloud.githubusercontent.com/assets/17283358/16041892/d433d408-3201-11e6-8c60-7b05183f9c0c.png)

**Comment by arosiopr** [comment]
en mi celular sucede lo mismo

![screenshot_2016-06-14-17-43-22](https://cloud.githubusercontent.com/assets/5313326/16061766/d1864004-3258-11e6-9ec3-872e6c8db79c.png)

- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16061769/d6b870b0-3258-11e6-9b03-39c15fe8e885.png)

**Comment by yalayn** [comment]
Buenas noches. Se aplico una distribución semejante a la encontrada en el setting de My Locations. De modo que la X no se coloque sobre el nombre del Provider, quedando de la siguiente manera: 
![captura de pantalla de 2016-06-15 00 17 48](https://cloud.githubusercontent.com/assets/4664287/16067965/70d8ca28-328b-11e6-973f-69981a3b2a55.png)

**Comment by arosiopr** [comment]
en la versión 17 de la apk en mi celular sigue saliendo montada

![screenshot_2016-06-15-17-54-44](https://cloud.githubusercontent.com/assets/5313326/16100003/443115e4-3325-11e6-9382-1ffcc7e040b6.png)

#### Dispositivo desde donde se realizo la prueba
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16100013/52ecb1c4-3325-11e6-8d5e-1d91d95117d6.png)

**Comment by yalayn** [comment]
Buenas noches. Hola @arosiopr En la versión 17 no se encuentra disponible la corrección. Apenas este disponible les informo por acá.
Saludos.

**Comment by yalayn** [comment]
Buenas tardes. En la versión 17.3 se encuentra disponible esta corrección. 
Saludos.

**Comment by AdryCanonico** [comment]
@yalayn @MaviDavsa En la version 17.3 ya esta corregido. Se puede cerrar el caso :+1:
