### ISSUE TITLE
Bitcon Wallet_ Contact_External Contant

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#53]
### Template issue error report

Bit Coins Wallet
#### Nombre pantalla

Contact Detail
### Bitcoin Wallet 

------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

![issus](https://cloud.githubusercontent.com/assets/17273005/13499124/1f52632e-e12f-11e5-9289-fee12e930431.JPG)

Cuando voy a ver el Adress Código de la persona, no me sale el código alfanumérico . Simplemente me sale solo el Código de Barras pero absolutamente más nada.

Estoy utilizando el Emulador BlueStarks. 

@augusto-ponce

**Comment by maydiamc** [comment]
Mismo error en la panttalla de detalles de contacto.

Modelo de telefono: Samsung Galaxy MiniS4
Numero de Version: Android 4.4.2 Kit Kat

**Comment by maydiamc** [comment]
persiste el error en la nueva actualizacion

Modelo del telefono: Samsung Galaxy Mini S4
Numero de Version: Android 4.4.2 Kit Kat

**Comment by MaviDavsa** [comment]
Persiste el error en la nueva actualizacion

Emulador: BlueStarks
Numero de Version: Android 5.0

**Comment by MaviDavsa** [comment]
Persiste el error en la nueva actualizacion

Emulador: BlueStarks
Numero de Version: Android 5.0

**Comment by maydiamc** [comment]
persiste el error en la nueva actualizacion
Marca: Samsung Galaxy
Modelo: mini S4
Version de android: 4.4.2

**Comment by maydiamc** [comment]
persiste el error en la nueva actualizacion
Marca: Samsung Galaxy
Modelo: mini S4
Version de android: 4.4.2

**Comment by maydiamc** [comment]
Fue corregido y solucionado el error en la ultima actualizacion.
Marca: Samsung Galaxy
Modelo: mini S4
Version de android: 4.4.2
