### ISSUE TITLE
CBP - Customer - No se crea el Bank que configuro en Customer Wallet

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#530]
### CBP v16.5

-----

##### Reporte de error: 

   *El error sucede cuando tengo el perfil de "Customer" y estoy configurando la "Customer Wallet", en uno de los pasos me pide configurar el "Bank", introduzco los datos correspondientes y cuando me voy a revisar al "Settings", perfecto, me crea la cuenta aparentemente (Pantalla 1), pero, cuando me voy a la "Banking Wallet" no me ha creado ni configurado nada, pues me pide introducir los datos del banco tal cual entro a esa Wallet por primera vez (Pantalla 2). Ahora bien, si este proceso lo hace el con el broker, por qué con el Customer no?, ya que las cuentas yo las voy a utilizar para hacer las negociaciones no? o cuál sería la lógica de hacer la configuración por la "Customer Wallet" si no se conecta a la "Banking Wallet"?.
   
------
#### Pantalla 1

![screenshot_28](https://cloud.githubusercontent.com/assets/19142276/16013351/17b0b7b6-315b-11e6-9d68-c888ad3bdd80.jpg)

#### Pantalla 2

![screenshot_2](https://cloud.githubusercontent.com/assets/19142276/16013341/0eb6441e-315b-11e6-9519-ad6243d915b1.jpg)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 5
- Versión Android: 5.1.0

![nexus 5](https://cloud.githubusercontent.com/assets/19142276/16013378/30cff306-315b-11e6-9012-6b1a3f0c9bfd.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by nelsonalfo** [comment]
Esto no es un bug. La customer wallet no fue echa apra llevar balances de un customer, por lo que no se asocia ninguna wallet mas alla de la bitcoin wallet, para aprovechar la plataforma fermat al momento de hacer el envio de bitcoins a un broker. Los datos de locacion y cuentas bancarias son en este caso algo referencial para que el broker sepa por ejemplo a que cuenta bancaria va a enviar el dinero, pero esta no se asocia a ninguna bank wallet y no afecta ningun balance. 

La customer wallet se penso para un usuario que hace un uso casual de la app por lo que la customer wallet esta diseñada para proveer de lo mínimo necesario.

**Comment by MaviDavsa** [comment]
@nelsonalfo Entiendo pero si en el caso de broker está y sirve para darle hasta veracidad al broker al momento de hacer la venta no debería ser igual para el customer?

**Comment by IsbetVR** [comment]
@nelsonalfo ok entiendo tu punto, pero si yo veo la lógica de lo que se quiere establecer en una negociación: ambas partes reciben, el broker recibe de lo que vende y el customer lo que compra... si cuando configuro la wallet del broker me dice que la bank es donde va a recibir el dinero por las ventas que hace, tiene que ir a algún lado el dinero que va a recibir del customer por la neogicaicón... No sería ideal que se aplicara la misma metodología para el customer? es decir si el customer por ejemplo quiere comprar dólares, debería tener una cuenta en dólares a la cual le sea depositado lo que está negociando. Es decir, que las cuentas que está configurando a través de la Crypto Customer sean "reales" como en el caso del broker.

**Comment by nelsonalfo** [comment]
tiene sentido pero seria algo que iría para otra versión de CBP y habría que discutirlo con @Luis-Fernando-Molina porque fue el quien propuso esa visión para la customer wallet y con el se llego a esa decisión.

**Comment by Luis-Fernando-Molina** [comment]
El broker tiene la banking y Cash porque le ayuda a correr su negocio. El customer no vive de comprar y vender,  con lo cual no necesitaría esa funcionalidad, al menos no por ahora. Es solo un usuario casual que de vez en cuando compra o vende.
