### ISSUE TITLE
CBP - BROKER - Botón send no funciona

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#532]
### CBP 

-----

##### Reporte de error: 

   Luego de confirmar al presionar el boton "send" no envia, toca darle atras y volver a confirmar.

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16014134/b5a7d3de-3159-11e6-81fa-79016391dc07.png)

   
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16014141/bed2c536-3159-11e6-8dd4-cb39626edcc7.png)

**Comment by maydiamc** [comment]
en la version 17.1, al realizar una negociacion el boton send funciono, pero al presionarlo me saco automaticamente de la aplicacion y dio el erro de Recovering from System Error, pero al entrar a revisar la negociacion esta se habia enviado @nelsonalfo 
nota: no me dio tiempo de tomar el capture de pantalla del error

dispositivo fisico
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16120717/56d96234-33aa-11e6-86db-e3b92567752d.png)

**Comment by maydiamc** [comment]
este issue ya fue creado y tiene el numero #463 @MaviDavsa @Hernandezsmanu

**Comment by abicelis** [comment]
@MaviDavsa cierra este issue plz
