### ISSUE TITLE
TKY-ART - Se duplica el botón en Identidad de Art para conectar con identidad de TKY

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#534]
### TKY-ART (versión v1u2)

-----

##### Reporte de error: 

   *Cuando no tengo las identidades de TKY creadas, y me voy directamente a crear las de ART, cuando le doy click al botón que me permite seleccionar la identidad de TKY para la conexión desde el perfil, se duplica el botón de "Select an Identity..." (Pantalla 1) 

------
#### Pantalla 1

![screenshot_30](https://cloud.githubusercontent.com/assets/19142276/16027144/a61e2510-31a1-11e6-84c3-b6952cd5fd50.jpg)

------
#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 5
- Versión de Android: 5.0.0

![nexus 5 5 0](https://cloud.githubusercontent.com/assets/19142276/16028105/dc8959c8-31a9-11e6-9ab2-429bcb1d7abf.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@alexanderjm @darkestpriest

**Comment by darkestpriest** [comment]
Please @juanaso, check this

**Comment by juanaso** [comment]
cual es la resolucion de esa pantalla? @MaviDavsa .gracias

**Comment by MaviDavsa** [comment]
@juanaso Te refieres al emulador? De ser así es de creo que ese emulador es 1080 x 1920... @IsbetVR Verifica por favor!

**Comment by juanaso** [comment]
@IsbetVR  tambien dime los dpi, estos son muy importantes, gracias

**Comment by IsbetVR** [comment]
@juanaso 
Emulador:
Google Nexus 5	
Versión de Android: 5.0.0	
480 dpi	
API 21 1080x1920

**Comment by Hernandezsmanu** [comment]
Solucionado.

**Comment by IsbetVR** [comment]
Probado en versión v1u3. 
Solucionado. Ya no se duplica el botón.

![screenshot_4](https://cloud.githubusercontent.com/assets/19142276/16196672/d5e07516-36cc-11e6-9240-630d314d1f50.jpg)

- [x] Emulador
- Google Nexus 4
- Versión de Android 5.1.0
- 320 dpi
- API 22 768x1280
