### ISSUE TITLE
Communities - Artist - El mensaje de "No hay conexiones" sale con un reflejo

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#536]
### TKY-ART (versión v1u2)

-----

##### Reporte de error: 

   *Cuando estoy en las "Communitites" y me voy a la opción del menú donde veo las "Connections" y no he establecido conexión con ningún usuario todavía, el mensaje que muestra la pantalla haciendo referencia a que no hay conexiones sale con un reflejo en la parte inferior, tal como se muestra en la pantalla 1. 
   
------
#### Pantalla 1

![screenshot_31](https://cloud.githubusercontent.com/assets/19142276/16028015/01342b96-31a9-11e6-8aa3-6330d26aca85.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 5
- Versión de Android: 5.0.0

![nexus 5 5 0](https://cloud.githubusercontent.com/assets/19142276/16028088/99b04d50-31a9-11e6-9be0-e02c110ce176.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by juanaso** [comment]
@MaviDavsa ya lo soluciono gracias

**Comment by IsbetVR** [comment]
Solucionado en la versión v1u3. Ya no sale el reflejo

![screenshot_8](https://cloud.githubusercontent.com/assets/19142276/16199924/6ee16444-36d9-11e6-960c-edc48247358e.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa Por favor reabrir este caso. 
En la versión v1u6 está sucediendo otra vez el reflejo, tal como se muestra en la siguiente pantalla

![screenshot_61](https://cloud.githubusercontent.com/assets/19142276/16304930/a192a328-3925-11e6-90a4-2580d1e89c25.jpg)

Dispositivo de prueba:
- [x] Emulador
- Google Nesus 5
- Versión de Android: 5.0.0
- 480 dpi
- API 21 1080x1920

![google nexus 5 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16304963/c4e454c0-3925-11e6-86ae-d95d3fb10375.jpg)

**Comment by darkestpriest** [comment]
@juanaso ya habías trabajado con esto, por favor, échale un ojo.

**Comment by Hernandezsmanu** [comment]
En la version v1u7 persiste el reflejo.

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16422463/43564f98-3d22-11e6-9ce5-d47246a93be9.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/16422468/46d8f8b4-3d22-11e6-907f-e83696652cf0.png)

**Comment by lostwood** [comment]
ya se corrigio en la version 1v11 que esta en el channel @Hernandezsmanu

**Comment by IsbetVR** [comment]
Solucionado en la versión v1u11. Ya no sale el reflejo.
