### ISSUE TITLE
CBP - CBP Customer - Wizard Profile

### ISSUE THREAD

**Issue by LilianFlores** [Fermat-ORG/beta-testing-program#537]
#### Nombre pantalla

Crypto Customer Profile 

### Nombre de la Aplicación 

CBP
-----

##### Reporte de error: 

Al ingresar para crear una identidad como customer, en el pop-up de bienvenida no podía seleccionarse el cuadro para activar la opción "Don't show this again". Por lo tanto, al salir e ingresar de nuevo, el mensaje seguía apareciendo continuamente.

![screenshot_2016-06-13-20-36-04](https://cloud.githubusercontent.com/assets/19652611/16028087/661d3290-31a5-11e6-8ad0-ecefff2ff44c.png)
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16028062/38439bde-31a5-11e6-8245-7d1fa25031b0.png)

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 537 CPB V16.5
Nexus 5 5.0.0
En este emulador  ocurre lo reportado.
![caso 537](https://cloud.githubusercontent.com/assets/17283358/16041543/b751759a-31ff-11e6-8302-e4c5c3d3b52b.png)

**Comment by maydiamc** [comment]
en la version 16.5, esto sigue sucediendo, con la diferencia que en mi caso si puedo tildar la opcion de no mostrar de nuevo, pero a pesar de hacerlo, esto no funciona y el mensaje se sigue reproduciendo
@nelsonalfo 

![screenshot_2016-06-14-09-07-53](https://cloud.githubusercontent.com/assets/17274154/16044906/200091c4-3210-11e6-9d6a-c984dec68b8b.png)
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16044915/2486af26-3210-11e6-8c86-e2dde752b9e7.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by LilianFlores** [comment]
Ya este error no se presenta en la versión 17.3. Cerrar caso. @MaviDavsa

**Comment by maydiamc** [comment]
en laversion 19.8 sucedio esto! al ingresar sale, y luego de crear el perfil vuelve a aparecer

![screenshot_6](https://cloud.githubusercontent.com/assets/17274154/16655050/9996a208-4426-11e6-82d9-c7238bde92df.png)

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16655054/a1904ac2-4426-11e6-948a-aae6c015c300.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by arosiopr** [comment]
en a versión 19.9 de cbp a pesar de estar seleccionado que no se repita el mensaje. Se sigue repitiendo

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16665947/73154940-4453-11e6-8388-e80c4406d3ab.png)

**Comment by LilianFlores** [comment]
En la versión 20.0 de CBP, persiste este error. 

Nexus 4  5.0.0

**Comment by arosiopr** [comment]
En la versión 20.1 persiste el error

**Comment by MaviDavsa** [comment]
En la versión 20.1, desde el teléfono físico, persiste el error... 

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16687739/5ccac864-44e8-11e6-90b1-3e54b2d8ef1f.jpg)

**Comment by Gabymorillo** [comment]
En la versión 20.1 en el teléfono físico no presenta este error.

![screenshot_2016-07-08-07-56-43](https://cloud.githubusercontent.com/assets/17262077/16688244/2be6346a-44eb-11e6-82d4-bb39c0700600.png)

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16688252/36a28444-44eb-11e6-961a-e68902c9952b.png)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de CBP, en mi emulador no sucede este error

![samsung](https://cloud.githubusercontent.com/assets/19353722/16688985/b1981b16-44ee-11e6-9924-187d0a3507d9.png)

**Comment by maydiamc** [comment]
en la version 20.1 de cbp no sucede este error en el emulador

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16690335/5e61f3ac-44f5-11e6-9271-d644452c486a.png)

**Comment by sanro14** [comment]
Solucionado.

**Comment by LilianFlores** [comment]
En la versión 21.2 de CBP, sucede este error. 

![ccp](https://cloud.githubusercontent.com/assets/19652611/17339037/0cae6870-58b8-11e6-92b6-ceb452018ca6.png)

##### Pasos exactos para reproducir el error:

*Detallar paso a paso la forma en  la cual se logro el error.

  1. Ingresé a crear el perfil. Se mostró el pop up de bienvenida, marcado por defecto para no mostrarse de nuevo y se cerró para proseguir con la creación del user. 
  2. Se ingresó el nombre de usuario. 
  3. Luego se estableció una foto de perfil y mostró nuevamente el pop up de bienvenida. 
  4. Salí y volví a entrar para descartar, pero volvió a mostrarse. 
  5. Se probó nuevamente cambiando la foto de perfil y persistía cada que se agregaba una nueva img o se ingresaba al Crypto Customer Profile.

#### Archivo aLogcat

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/397777/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![celular](https://cloud.githubusercontent.com/assets/19652611/17339073/3cf6d04e-58b8-11e6-9ee2-6ed581169cc5.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by LilianFlores** [comment]
En la versión 21.2 de CBP, sucede este error. 

![ccp](https://cloud.githubusercontent.com/assets/19652611/17339037/0cae6870-58b8-11e6-92b6-ceb452018ca6.png)

##### Pasos exactos para reproducir el error:

*Detallar paso a paso la forma en  la cual se logro el error.

  1. Ingresé a crear el perfil. Se mostró el pop up de bienvenida, marcado por defecto para no mostrarse de nuevo y se cerró para proseguir con la creación del user. 
  2. Se ingresó el nombre de usuario. 
  3. Luego se estableció una foto de perfil y mostró nuevamente el pop up de bienvenida. 
  4. Salí y volví a entrar para descartar, pero volvió a mostrarse. 
  5. Se probó nuevamente cambiando la foto de perfil y persistía cada que se agregaba una nueva img o se ingresaba al Crypto Customer Profile.

#### Archivo aLogcat

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/397777/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![celular](https://cloud.githubusercontent.com/assets/19652611/17339073/3cf6d04e-58b8-11e6-9ee2-6ed581169cc5.png)

**Comment by dorzar1989** [comment]
En la Version 21.3 de la CBP no me sucede este error.

- Screenshot:

![screenshot_141](https://cloud.githubusercontent.com/assets/19670319/17367654/d8dacf1e-595e-11e6-920d-8efbb28dd46a.png)

- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17367647/d0613940-595e-11e6-8802-f692cca78802.png)

**Comment by LilianFlores** [comment]
En la versión 21.3 ya no sucede este error. Cerrar caso @IsbetVR

**Comment by IsbetVR** [comment]
Closed #537
