### ISSUE TITLE
CBP- HOME DE LA CRYPTO CUSTOMER SALE CORTADA 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#539]
#### Nombre pantalla

HOME CBP

### Nombre de la Aplicación 

CBP

-----

##### Reporte de error: 

Al entrar al home de la CBP se nota que en la parte de arriba sale cortado, (pantalla 1) es lo máximo que baja, si observamos en la pantalla 2, al subir no hay problemas. 
------

![screenshot_2016-06-13-20-48-18](https://cloud.githubusercontent.com/assets/17262077/16028270/814f1d24-31a7-11e6-9edc-cb72a4a676f0.png)

![screenshot_2016-06-13-20-49-58](https://cloud.githubusercontent.com/assets/17262077/16028275/8b864416-31a7-11e6-9ae8-d51614c83aaf.png)

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16028286/ac76841a-31a7-11e6-819f-98bca8e05107.png)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 539
![caso 539](https://cloud.githubusercontent.com/assets/17283358/16041412/f6c47264-31fe-11e6-915f-82ced9703e09.png)
 CPB V16.5
Nexus 5 5.0.0
En este emulador no ocurre lo reportado.

**Comment by maydiamc** [comment]
en la version 16.5 sucede este error @nelsonalfo @abicelis

![screenshot_2016-06-14-09-12-10](https://cloud.githubusercontent.com/assets/17274154/16044192/3e97c344-320d-11e6-9079-f8919743aaa3.png)

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16044207/4f5bb366-320d-11e6-8632-5273fee367af.png)

**Comment by arosiopr** [comment]
en mi celular sucede lo mismo sale cortado en la sección que dice buy y sell

![screenshot_2016-06-14-17-46-18](https://cloud.githubusercontent.com/assets/5313326/16061642/e2f5d652-3257-11e6-9804-f6d27a3fb9f3.png)

- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16061680/1cc57d4c-3258-11e6-9275-874608ed7536.png)

**Comment by Gabymorillo** [comment]
En la versión 16.6 persiste. 

![screenshot_2016-06-14-18-23-04](https://cloud.githubusercontent.com/assets/17262077/16061898/a4524924-3259-11e6-811b-fe140a6a9db9.png)


![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16061900/a96d4d96-3259-11e6-816a-c052afb621bc.png)

**Comment by LilianFlores** [comment]
En la versión 16.6 he presentado este error. 

![screenshot_2016-06-14-18-22-57](https://cloud.githubusercontent.com/assets/19652611/16062576/d59791ac-325d-11e6-90a5-a75ee1422f4b.png)

**Dispositivo desde donde se realizo la prueba**

[x]Teléfono Físico

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16062623/3ca05ffa-325e-11e6-85d6-f3730d270826.png)

**Comment by AdryCanonico** [comment]
@Gabymorillo  en mi teléfono ya no sale cortado el home y se puede visualizar bien el texto. 


![screenshot_2016-06-16-09-20-53](https://cloud.githubusercontent.com/assets/18584168/16119231/5ef75210-33a4-11e6-98bd-5261b8fd67ff.png)

Dispositivo:

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16119244/766a60c2-33a4-11e6-932e-20197d27f5a2.png)

**Comment by nelsonalfo** [comment]
si, esto se solvento en la version 17.1 del apk, espero confirmación de @Gabymorillo para cerrar el Issue

**Comment by Gabymorillo** [comment]
Solucionado!! @nelsonalfo
