### ISSUE TITLE
Bit Coin Wallet_Settings

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#54]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla

Settings

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *En la pantalla Settings, la opción de Enabled Notifications marco la opción Si, luego salgo y vuelvo a entrar y marca la opción No, así lo intente varias veces con el mismo resultado

Telefono: ZTE Apex 2 
Android: 4.4.2

![screenshot_2016-03-03-11-18-50](https://cloud.githubusercontent.com/assets/17273349/13499942/77978444-e132-11e5-900e-4c33883c4bd8.png)

**Comment by adryx83** [comment]
Después de la actualización del día de hoy el error continua.

**Comment by maydiamc** [comment]
persiste el error en la nueva actualizacion 

Modelo del telefono: Samsung Galaxy Mini S4
Numero de Version: Android 4.4.2 Kit Kat

**Comment by adryx83** [comment]
En la ultima actualización ya esta solucionado el error.

Telefono: ZTE Apex 2
Versión Android: 4.4.2
