### ISSUE TITLE
CBP- TEXTO MONTADO EN EL MENÚ DE LA CRYPTO CUSTOMER

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#540]
#### Nombre pantalla

HOME CUSTOMER

### Nombre de la Aplicación 

CBP
-----

##### Reporte de error: 

En la versión 16.5 se observa que al final del menú el texto está montado. 
------

![screenshot_2016-06-13-21-03-39](https://cloud.githubusercontent.com/assets/17262077/16028360/5e9da4f2-31a8-11e6-8624-0a2f8b910498.png)

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16028354/57f7d352-31a8-11e6-977b-3a70688a6edc.png)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by yolandayancel** [comment]
Prueba 14-06-16
Caso 540 CPB V16.5
Nexus 5  5.0.0
En este emulador no ocurre lo reportado.
![caso 540](https://cloud.githubusercontent.com/assets/17283358/16041230/0610d894-31fe-11e6-8eec-b96861db4c1d.png)

**Comment by Gabymorillo** [comment]
En la versión 16.6 persiste. 

![screenshot_2016-06-14-17-29-35](https://cloud.githubusercontent.com/assets/17262077/16061585/824f03aa-3257-11e6-976c-79e2b43a6b33.png)

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16061596/93e0626c-3257-11e6-992a-c1e55d4c1846.png)

**Comment by abicelis** [comment]
@Gabymorillo @yolandayancel @MaviDavsa @arosiopr Yo agarro este issue.

**Comment by abicelis** [comment]
@Gabymorillo @yolandayancel @MaviDavsa @arosiopr Prueben esto en la proxima version, la 17.4!
Cualquier cosa me dicen.

**Comment by Gabymorillo** [comment]
ok! esperamos la versión 17.4, porque en la 17.3 aun persiste. @abicelis

**Comment by yolandayancel** [comment]
Estaré pendiente alejandro

**Comment by Gabymorillo** [comment]
Solucionado en mi equipo. 

![screenshot_2016-06-17-19-10-45](https://cloud.githubusercontent.com/assets/17262077/16167250/888c18b8-34bc-11e6-950f-d4798e48cc58.png)

**Comment by LilianFlores** [comment]
En la versión 17.4, esto ya no ocurre en mi teléfono. 

![screenshot_2016-06-17-20-25-09](https://cloud.githubusercontent.com/assets/19652611/16167941/01d908c6-34c6-11e6-8fa6-b39ce21d940d.png)
