### ISSUE TITLE
CBP-ICONOS MONTADOS EN FOTO PERFIL 

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#541]
### Template issue error report

Nombre pantalla

CUSTOMERS NEW IDENTITY

Nombre de la Aplicación 

CBP

Reporte de error: 

   AL CREAR EL PERFIL EN COSTUMERS SE MONTAN LOS ICONOS DE GALERÍA Y CÁMARA ENCIMA DE LA FOTO, TAL Y COMO SE SEÑALA A CONTINUACIÓN:

![image](https://cloud.githubusercontent.com/assets/18740418/16043511/c520399a-3209-11e6-98b9-f62b9185dbd1.png)

Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

![image](https://cloud.githubusercontent.com/assets/18740418/16043553/003a7ad6-320a-11e6-8929-5707347a9308.png)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by abicelis** [comment]
@camilavaleria @MaviDavsa esto no tiene nada de malo :/
El diseno es exactamente asi. Dos botones separados 4dp del borde derecho, la imagen del usuario centrada en el view.

Cerrar este issue plz.

**Comment by MaviDavsa** [comment]
@camilavaleria Esta asi por diseño!
