### ISSUE TITLE
CBP - Customer Wallet - Foto de Perfil  

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#542]
#### Nombre pantalla
Customer Wallet

### Nombre de la Aplicación 
CBP 16.5

-----

##### Reporte de error: 

   *La Foto de perfil cuando es un usuario por emulador, sale de manera horizontal, mientras que cuando es un usuario de telefono sale de manera vertical.
   
![screenshot_20](https://cloud.githubusercontent.com/assets/19670319/16043964/1fb682fe-320c-11e6-9671-9870d84c25f0.png)

------

#### Dispositivo desde donde se realizo la prueba

Nexus 4
Version 5.0
Emulador

![screenshot_10](https://cloud.githubusercontent.com/assets/19670319/16043898/d62dee60-320b-11e6-8edf-19f480a4fbaf.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by abicelis** [comment]
@dorzar1989 @MaviDavsa a partir de la version 17.3, las nuevas identities crear o editadas el app obliga al usuario a hacer un crop (cuadrado) de ella (y asi evitar esos iconos ovalados que senalas aca), ademas te da la opcion de rotar imagenes.

Revisen y me avisan cualquier cosa!

Nota: Las imagenes de perfiles creados en versiones anteriores a la 17.3 se seguiran viendo mal, solo los perfiles nuevos (o editados) en la version 17.3 en adelante se veran bien.

**Comment by dorzar1989** [comment]
Buenas @abicelis y @MaviDavsa estoy al tanto de verificar este issue pero no lo he podido hacer ya que no he podido lograr una conexión ni una negociación por problemas con las communities. Pero si verifique que ya tenemos la ventaja de la edición de la imagen, tanto rotarla como cortarla. Gracias estoy al pendiente

**Comment by dorzar1989** [comment]
Buenos Dias @MaviDavsa y @abicelis Hoy logre verificar que en la versión 17.3 ya este issue no existe, o sea fue resuelto. A continuación monto una imagen de como se ve en este momento. Gracias.


![screenshot_21](https://cloud.githubusercontent.com/assets/19670319/16155091/901c0736-3477-11e6-9126-5f7c3e56dd86.png)
