### ISSUE TITLE
CBP-CREATE A BANK ACCOUNT

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#543]
#### Nombre pantalla
Create a Bank Account

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   *Al entrar en la pantalla de SELECT STOCK WALLETS y entrar a CREATE A BANK ACCOUNT en Account number dice que puede ingresar 25 digitos pero solo deja poner 10 
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.0

![screenshot_8](https://cloud.githubusercontent.com/assets/19656830/16045338/c90c4596-3211-11e6-9d91-492e2ce74194.png)
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by nelsonalfo** [comment]
Como se puede observar el error ya no persiste: 

![captura de pantalla de 2016-06-16 09 40 00](https://cloud.githubusercontent.com/assets/1823627/16118746/50ae4ae4-33a2-11e6-95e0-4cbe33364b18.png)

**Comment by abicelis** [comment]
@danielaporras @MaviDavsa Lo que dijo @nelsonalfo, en la version 17.3 esta disponible.

**Comment by danielaporras** [comment]
El error ya esta solucionado
