### ISSUE TITLE
CBP-My Locations-(X) sale entre el texto

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#544]
### Nombre de la Aplicación CBP

-----

##### Reporte de error: 

   *Al ingresar en My Locations se puede ver que la "x" sale confundida entre el texto de la location

![screenshot_2016-06-14-17-44-19](https://cloud.githubusercontent.com/assets/5313326/16062170/5831a524-325b-11e6-8e9a-5f818cb731f6.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16061874/6ef43f08-3259-11e6-941f-5c45414a8415.png)

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by yalayn** [comment]
Yo @yalayn trabajare en este issue

**Comment by yalayn** [comment]
Se movió la X a la parte del titulo, para que no se sobreponga en el texto de la locación. Quedando de la siguiente manera:
![captura de pantalla de 2016-06-14 20 05 59](https://cloud.githubusercontent.com/assets/4664287/16064283/8ac464c8-3269-11e6-80f1-3db7449694d1.png)

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  544   CBP V 16.7
Nexus 4 5.0.0
En este emulador, no ocurre lo mismo.
Foto
![caso 544](https://cloud.githubusercontent.com/assets/17283358/16087134/c1963774-32eb-11e6-89a4-335460906957.png)

[logcat caso 544.txt](https://github.com/Fermat-ORG/beta-testing-program/files/316562/logcat.caso.544.txt)

**Comment by MaviDavsa** [comment]
@yolandayancel Dame las especificaciones del emulador por favor!

**Comment by yolandayancel** [comment]
El emulador es Nexus 4 5.0.0 320 dpi

**Comment by arosiopr** [comment]
en la versión 17 de la apk sigue saliendo montada la X en mi celular

![screenshot_2016-06-15-17-56-49](https://cloud.githubusercontent.com/assets/5313326/16099887/98b40294-3324-11e6-9028-3382fa96c3cb.png)


#### Dispositivo desde donde se realizo la prueba


- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16099919/c0a3816c-3324-11e6-9aea-7547c33b6b95.png)

**Comment by yalayn** [comment]
Buenas noches. Hola @arosiopr En la versión 17 no se encuentra disponible la corrección. Apenas este disponible les informo por acá.
Saludos.

**Comment by nelsonalfo** [comment]
en la version 17.1 esta corregido este problema

**Comment by arosiopr** [comment]
@MaviDavsa @sanro14 solucionado, se puede cerrar
