### ISSUE TITLE
CBP - Crypto Broker Users - Error en profiles, fotos no se muestran correctamente

### ISSUE THREAD

**Issue by LilianFlores** [Fermat-ORG/beta-testing-program#546]
#### Nombre pantalla

Crypto Broker Profiles

### Nombre de la Aplicación 

CBP
-----

##### Reporte de error: 

   Cuando entro a la Crypto Broker Community me aparecen, en efecto, los crypto broker users visibles (pantalla 1). Sin embargo, cuando voy a revisar sus perfiles para enviarles la solicitud, las fotos de perfil salen estiradas (pantalla 2, 3 y 4). Esto solo sucede al entrar en perfiles. 

![screenshot_2016-06-14-18-27-51](https://cloud.githubusercontent.com/assets/19652611/16063095/5524013c-3261-11e6-815e-f65f765cb8db.png)

![screenshot_2016-06-14-18-25-55](https://cloud.githubusercontent.com/assets/19652611/16063198/bb53dfd6-3261-11e6-9c04-0e4673188f6b.png)

![screenshot_2016-06-14-18-26-40](https://cloud.githubusercontent.com/assets/19652611/16063210/c61506ca-3261-11e6-9ff6-2add5f28f777.png)

![screenshot_2016-06-14-18-28-16](https://cloud.githubusercontent.com/assets/19652611/16063224/e2705518-3261-11e6-89b1-8a1d445e968b.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16062898/0d5367e0-3260-11e6-9dc1-12187f0a22d0.png)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by yolandayancel** [comment]
Prueba 15-06-2016
Caso  546   CBP V 16.6
Nexus 5  5.1.0
Si ocurre lo reportado
![caso 546](https://cloud.githubusercontent.com/assets/17283358/16082096/2c131836-32da-11e6-9732-f004fa435f4f.png)

**Comment by abicelis** [comment]
@yolandayancel @MaviDavsa @LilianFlores En la apk 17.3 hay mejoras en ambas identities, de tal forma de que al crear/editar perfiles la app obliga al usuario a hacer un crop cuadrado.
Revisen a ver si eso les arregla este error que ven aca.

Nota: SOLO se veran correctamente las fotos de perfiles creados/editados en la app v > 17.3. Los perfiles viejos que esten por ahi seguiran estando mal hasta que se dejen de usar!

**Comment by LilianFlores** [comment]
En la versión 17.3, efectivamente, no se presenta este error. Cerrar caso. @MaviDavsa
