### ISSUE TITLE
CBP-Cripto Broker Community-Notificaciones-Se cuelga en esa pantalla.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#547]
#### Nombre pantalla

Notifications

### Nombre de la Aplicación 

CBP
-----

##### Reporte de error: 

   Al ingresar en la Cripto Broker Community, específicamente a la pantalla Notificaciones, al tratar de salir de esa pantalla no responde y luego sale un mensaje con 2 opciones,  "wait" o "ok", al pulsar wait y esperar un poco la pantalla no responde y luego vuelve a salir el mensaje antes mencionado, hay que pulsar "ok" para cerrar la aplicacion.

![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/16063231/e8c1a20a-3261-11e6-90cc-7cf5731547ee.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16063306/47625174-3262-11e6-9bef-9d72a161c363.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/315154/logcat.txt)

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis
