### ISSUE TITLE
CBP - Crypto Broker -  Profile - Boton de Status

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#548]
### Template issue error report
Crear Perfil Crypto Broker 

#### Nombre pantalla
Crypto Broker Profile

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

 En la pantalla para crear el perfil desde 0 en la parte del boton no visible tengo que darle dos veces para que pueda mostrarse mi perfil como visible 
   
![image](https://cloud.githubusercontent.com/assets/19807906/16063444/55cd9b74-3267-11e6-9c2f-c356daf6762e.png)
![image](https://cloud.githubusercontent.com/assets/19807906/16063449/5e5c817e-3267-11e6-892a-a62a63c42bf0.png)
![image](https://cloud.githubusercontent.com/assets/19807906/16063454/651e1efa-3267-11e6-8c89-bd1404cde2ef.png)
![image](https://cloud.githubusercontent.com/assets/19807906/16063462/6bdf4a48-3267-11e6-842e-23e3951b0d76.png)

------

#### Dispositivo desde donde se realizo la prueba
![image](https://cloud.githubusercontent.com/assets/19807906/16063492/a112de6e-3267-11e6-8ab6-c5cf5741f7d0.png)

- [x] Emulador

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/315160/logcat.txt)

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by IsbetVR** [comment]
en la versión v17 de CBP pasa lo mismo, hay que darle dos veces para que cambie el estatus a "visible". A pesar que al darle click por primera vez dice que lo ha actualizado.
Probado en:
- [x] Emulador
- Google Nexus 5
- Versión Android 5.0.0
- 480 dpi
- API 21 1080x1920

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa @JeanFranco498 Ok, revisare esto

**Comment by nelsonalfo** [comment]
Revisa esto en la version 17.2 en adelante porfa y me avisas

**Comment by IsbetVR** [comment]
@nelsonalfo @abicelis en la versión 17.4 de CBP al darle click la primera vez cambia el estatus.
Ya no hay que hacerlo dos veces.
@JeanFranco498 revisa a ver si te funciona. 

Dispositivo de prueba:
- [x] Emulador
- Google Nexus 4
- Versión Android: 5.0.0
- 320 dpi
- API 21 768x1280

**Comment by nelsonalfo** [comment]
por favor verificar esto para cerrarlo

**Comment by yalayn** [comment]
Buenas noches @IsbetVR @MaviDavsa @JeanFranco498. Porfa podrían confirmar si este issue ya fue corregido para que se solicite su cierre. Gracias. :)

**Comment by JeanFranco498** [comment]
El error ya fue corregido
