### ISSUE TITLE
Communities-Crypto Customer-mensaje de welcome cortado

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#549]
### Nombre de la Aplicación Communities crypto customer

-----

##### Reporte de error: 

   *al ingresar en la Communities crypto customer sale el aviso de welcome pero sale cortado, y no deja correr hacia abajo como en el de crypto broker

![screenshot_2016-06-14-18-05-30](https://cloud.githubusercontent.com/assets/5313326/16065147/b26733fe-3271-11e6-88ce-810f715ecf3b.png)
   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16064911/62a6ca16-326f-11e6-8485-ca445a415c7f.png)

**Comment by arosiopr** [comment]
@mavidavsa @abicelis

**Comment by abicelis** [comment]
@arosiopr Este PresentationDialog es parte de fermat-android-core. Este issue no es de CBP! 
Cambien los labels please

**Comment by arosiopr** [comment]
@sanro14 yo no coloco labels jeje

**Comment by MaviDavsa** [comment]
Redireccionado con el Issues #535

**Comment by MaviDavsa** [comment]
![screenshot_2016-07-06-08-48-23](https://cloud.githubusercontent.com/assets/17273005/16618810/4afd858a-4359-11e6-9c5b-cbb9e0dc23d8.jpg)


![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16618818/54d8469e-4359-11e6-9f09-5dadcc8a2fdb.jpg)

Solucionado!
