### ISSUE TITLE
CBP- CRYPTO CUSTOMER -  NO SE EFECTUAN LAS NEGOCIACIONES

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#550]
#### Nombre pantalla
Home Crypto Customer

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

Al establecer una negociación con el Broker, esperamos un lapso de 15min y no llegó a efectuarse, en este caso @AdryCanonico  (pantalla 1 broker) 

![ee9b6e479db4ec0972c6113cc2fc9d48d069e14657eaa79394 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17262077/16065292/446ee016-3273-11e6-8736-2aadb7061a27.jpg)

 En mi caso siendo el customer en el home se quedaba cargando con la pantalla en blanco las negociaciones sin ningún resultado y en contratos tampoco.

![screenshot_2016-06-14-20-36-06](https://cloud.githubusercontent.com/assets/17262077/16065338/93ba6e6a-3273-11e6-8355-bdb385b99976.png)

![screenshot_2016-06-14-20-58-21](https://cloud.githubusercontent.com/assets/17262077/16065340/99908de2-3273-11e6-816d-1397c70c22c9.png)
 
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16065343/a4e0bc12-3273-11e6-80d1-2df7dca778a6.png)

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by AdryCanonico** [comment]
@Gabymorillo  en la version 17.2 se había corregido este error.

**Comment by yalayn** [comment]
Buenos días @AdryCanonico, @Gabymorillo podrían por fa confirmar si esto caso ha ocurrido nuevamente? Gracias
Saludos.

**Comment by MaviDavsa** [comment]
Chicas! Hay que verificar esto!

**Comment by AdryCanonico** [comment]
@yalayn  Aun ocurre este error en la versión 18 cbp

**Comment by yalayn** [comment]
Ok, gracias @AdryCanonico. Puede que esté pasando lo que se comento en el chat del slack. Explico por acá para tener un dominio general del tema. Cuando ambos usuarios aceptan todas las cláusulas sin emitir modificaciones de alguna. La app procede automáticamente a cerrar la negociación de ambas partes. Luego se inicia el proceso de apertura del contrato y eso puede llevar un tiempo por que se sincroniza la información de ambas parte. En ese tiempo puede que no se vea la negociación ni el contrato y ese vacío puede estar generar la confusión de ser un fallo. Por eso se trabajará no dejar ese vacío.

**Comment by Gabymorillo** [comment]
En la versión 18, se pueden establecer las negociaciones. 

@MaviDavsa
