### ISSUE TITLE
CBP_exchange rate providers

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#551]
#### Nombre pantalla
exchange rate providers

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   Al ingresar a la pantalla de los provedores y querer cambiarlos, se abre la lista y se selecciona cualquier otro, que no sea el que aparece por defecto, y al apretar el boton save, salir de la pantalla y volver a ingresar, continuan los provedores por defecto (argentine peso) y no los que habia cambiado

![screenshot_2016-06-15-08-19-29](https://cloud.githubusercontent.com/assets/17274154/16080223/9092ba72-32d1-11e6-87aa-afc4f502e27e.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16080236/a25f8dca-32d1-11e6-8dab-8bbb60433684.png)

**Comment by maydiamc** [comment]
@nelsonalfo @sanro14 version 16.6

**Comment by MaviDavsa** [comment]
Caso Repetido!
