### ISSUE TITLE
CBP - Error en la Communities de la Crypto Broker

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#552]
##### Reporte de error: 

Una vez creado mi perfil de Customer cuando entro a las Communities en el botón Crypto Broker se queda cargando con el mensaje "please wait" y no responde, ni al presionar el botón de "back" del dispositivo.
  
![identity](https://cloud.githubusercontent.com/assets/17261437/16087830/6b8bf042-32f2-11e6-97ec-252816772d89.PNG)

![issue gaby](https://cloud.githubusercontent.com/assets/17261437/16087836/723b127e-32f2-11e6-89a9-b2ff1526a159.PNG)

El error persiste incluso borrando data y entrando nuevamente.

#### Dispositivo desde donde se realizo la prueba

![acerca del emulador](https://cloud.githubusercontent.com/assets/17261437/16087816/5fdf539c-32f2-11e6-82ef-e93da73f4e43.PNG)

**Comment by MaviDavsa** [comment]
Issues Creado!
