### ISSUE TITLE
CBP- Crypto Broker- Bank Accounts: no permite borrar una cuenta

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#553]
#### Nombre pantalla

Bank Accounts
### Nombre de la Aplicación 

CBP V 16.7
-----

##### Reporte de error: 

   1 Despues de creada una cuenta trato de borrarla, le clicleo en la X y entra: pregunta si deseo borrarla le doy a DELETE, pero no borra se queda allí
![no deja borrar una cuenta creada](https://cloud.githubusercontent.com/assets/17283358/16101996/2048effc-3335-11e6-809e-e687bf916b0e.png)
 2  sigo clikeando sobre el botón pero no funciona y luego aparece el recuadro siguente:
![no deja borrar una cuenta creada 1](https://cloud.githubusercontent.com/assets/17283358/16102035/796b0bec-3335-11e6-8709-82f7f835cc53.png)

------

#### Dispositivo desde donde se realizo la prueba
- [x] Emulador

![nexus 4 5 0 0](https://cloud.githubusercontent.com/assets/17283358/16102066/ed48a25e-3335-11e6-90bd-2b003d0b134c.png)

- [x] Logcat
[logcat no permite borrar cuenta.txt](https://github.com/Fermat-ORG/beta-testing-program/files/317447/logcat.no.permite.borrar.cuenta.txt)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by yalayn** [comment]
Yo @yalayn estare trabajando en este issue.

**Comment by yalayn** [comment]
Buenas noches. Ya se corrigió el error. Debería estar disponible para la próxima versión de la app.
Saludos.

**Comment by yolandayancel** [comment]
Prueba 17-06-16
Caso 553 CBP 17.3
Nexus 4 5.0.0 320dpi
Sigue ocurriendo lo reportado (botón para borrar cuenta no funciona.
![no deja borrar una cuenta creada 1 1](https://cloud.githubusercontent.com/assets/17283358/16150152/44f880c6-345f-11e6-8431-57421cb7d8c6.png)
[logcatCaso 553 17-06-16.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320415/logcatCaso.553.17-06-16.txt)

**Comment by yolandayancel** [comment]
@yalayn 
Recibido. Estaré pendiente para reportarte.
Saludos

**Comment by yolandayancel** [comment]
Recibido. Estaré pendiente de informarte
Saludos

**Comment by yalayn** [comment]
Buenas tardes, Se acaba de subir la versión 17.4, que tiene disponible esta corrección. Si no se las han facilitado pronto lo estarán haciendo.
Saludos.

**Comment by yolandayancel** [comment]
Okey al estar disponible para el grupo, lo reviso y te comento
Saludos

**Comment by yolandayancel** [comment]
@yalayn 
Prueba 19-06-16
Caso 553 CBP V 17.4
Creada una cuenta,le clicleo en la X para  borrarla (le doy a DELETE) el botón si funciona, borra la cuenta. CERRAR EL CASO.
![caso 553](https://cloud.githubusercontent.com/assets/17283358/16195155/178edf08-36c2-11e6-8e7c-073a234a49c0.png)
[logcat 553.txt](https://github.com/Fermat-ORG/beta-testing-program/files/323450/logcat.553.txt)
