### ISSUE TITLE
CBP_ configuracion de la cuenta cripto broker

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#554]
#### Nombre pantalla
Select stock wallet

### Nombre de la Aplicación 
CBP 

-----

##### Reporte de error: 

  Al ingresar por primera vez a la cripto broker y empezar a configurar la cuenta, en la pantalla de select stock wallets, seleccionar las cuentas y darle al boton save, se salio al menu principal de la aplicacion fermat y salio el error de Recovering From System Error.

Nota: No me dio tiempo de tomar la captura del error
   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16119418/31be57e8-33a5-11e6-9706-7819c6c2375a.png)

**Comment by maydiamc** [comment]
@nelsonalfo @sanro14 version 17.1

**Comment by nelsonalfo** [comment]
puedes enviar por favor el archivo **logcat.txt** del dispositivo donde se genero el error? para tener mas informacion

**Comment by maydiamc** [comment]
No se donde ubicar eso en mi telefono fisico.! Porq no estoy desde un emulador @nelsonalfo

**Comment by abicelis** [comment]
@maydiamc Sin mas informacion no podemos ayudarte aqui, busca replicar el error y capturalo en el logcat

Para obtener el logcat.txt desde un telefono puedes intentar usando [aLogcat](https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=en)

**Comment by yolandayancel** [comment]
Prueba 17-06-2016
Caso  554    CBP V 17.3
Nexus 4 5.0.0
En este emulador, no  ocurre lo reportado. Al pisar SAVE lo hace y guarda los cambios.
![caso 554](https://cloud.githubusercontent.com/assets/17283358/16154040/e0ba9c34-3472-11e6-84f2-017545660eed.png)
[logcat caso554.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320686/logcat.caso554.txt)

**Comment by maydiamc** [comment]
Intente reproducir el error, pero en la version 17.3 esto no ocurre.! @nelsonalfo cerrare el caso y de volver a ocurrir colocare el archivo logcat
@MaviDavsa cerrar el caso
