### ISSUE TITLE
CBP_notificaciones llevan a otro lugar

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#555]
### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   * Al llegarme una notificacion de solicitud de contacto customer y presionarla, esta me lleva a la bitcoin wallet y no a la crypto customer, esto sucede siempre que llega una notificacion de este tipo.
   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16119737/98b120f6-33a6-11e6-85ea-3eaa594e8ea5.png)

**Comment by maydiamc** [comment]
@nelsonalfo @sanro14 version 17.1

**Comment by abicelis** [comment]
@maydiamc como dije en https://github.com/Fermat-ORG/beta-testing-program/issues/557#issuecomment-226873719, estos errores son del android-core, si me entero de algo lo notifico aca.

**Comment by maydiamc** [comment]
sigue sucediendo en la version 18.3 de CBP, todas las notificacion de cualquier aplicacion, llevan a la bitcoin wallet @abicelis

**Comment by GeronimoVierma** [comment]
En la versión 18.5 de CBP al seleccionar una notificación de solicitud de contrato de un Custommer o cualquier notificación relacionada a un contrato ya existente  me envía directamente a  la "Crypto Customer Users" en vez de llevarme a la Broker Wallet.

**Comment by maydiamc** [comment]
solucionado este error en la version 18.8

**Comment by RubenSem** [comment]
Sigue sucediendo en la version 18.8 a algunos los envían a la bitcoin wallet y a otro los envia a la communities customer. por favor abrir caso.

![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/16531795/e69ad620-3f97-11e6-81a1-bb135e6bd6cd.jpg)

especificaciones del telefono:
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/16531674/5b9766a6-3f97-11e6-83dc-ef92f907888d.jpg)

**Comment by maydiamc** [comment]
en la CBP 19.4 se mantiene el problema

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16588763/5c2c3272-429e-11e6-9972-f4579d08d130.png)

**Comment by IsbetVR** [comment]
En la versión v19.5 de CBP persiste este error, las notificaciones llevan a otro destino.

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16618294/a152b20a-4356-11e6-85b5-668b96d12214.jpg)

**Comment by maydiamc** [comment]
en laversion 19.8 de cbp persiste el problema

**Comment by sanro14** [comment]
@abicelis en la versión 19.9 aún persiste el error..

**Comment by arosiopr** [comment]
En la version 20.1 de cbp persiste el error
Nexus 4
Android 4.4.4
Emulador

**Comment by RubenSem** [comment]
En la versión 20.2 de CBP sigue sucediendo este error.

Especificaciones:

Emulador: google nexus 5.1.0

**Comment by marielis-urbina** [comment]
En la versión 20.2 de CBP este error persiste 

Dispositivo desde donde se realizo la prueba

Emulador: Samsung Galaxy S3 4.2.2

**Comment by MaviDavsa** [comment]
En la versión 20.3 de CBP este error persiste

Dispositivo desde donde se realizo la prueba

Emulador: Google nexus 5 (Android 5.0)

**Comment by sanro14** [comment]
en la Versión 20.4 aun persiste el error @nelsonalfo

**Comment by marielis-urbina** [comment]
En la versión 20.4  de la CBP no se repite este error en mi emulador, te sale las notificaciones de conexión y te llevan directamente a la Broker Community.

 Dispositivo desde donde se realizo la prueba

Emulador: Samsung Galaxy S3 4.2.2

**Comment by GeronimoVierma** [comment]
En la versión 20.4 de CBP las notificaciones me llevan al lugar correcto, estando yo como Broker la notificación de conexión me lleva a la Customer Community, error solucionado.

![chi](https://cloud.githubusercontent.com/assets/19883115/16749215/94b0ea78-4796-11e6-94da-e264dba598b1.png)

**Comment by sanro14** [comment]
Solucionado.

**Comment by danielaporras** [comment]
En la version 20.4 se sigue repitiendo este error.


Dispositivo desde donde se realizo la prueba
Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.2.2

**Comment by AdryCanonico** [comment]
En la version 20.5 se sigue repitiendo este error.

**Comment by GeronimoVierma** [comment]
En la versión 20.6 persiste el error, al recibir una notificación de solicitud de contacto o de notificación de negociacion todas me llevan a la Bitcoin Wallet:  

![cumunist](https://cloud.githubusercontent.com/assets/19883115/16839645/2fcb865e-499e-11e6-8f2e-3b196dc07ce5.png)

![comuni2](https://cloud.githubusercontent.com/assets/19883115/16839647/3289fa10-499e-11e6-90c1-728897fe2c51.png)

**Comment by wendyduran90** [comment]
En la versión 20.7 persiste el error, las notificaciones de Chat y crypto customer, llevan a la Bitcoin Wallet.
Esta prueba se realizo desde un móvil con versión de android 4.4.4.

![screenshot_2016-07-18-09-04-32](https://cloud.githubusercontent.com/assets/20212920/16915951/65ef5990-4cc8-11e6-90dd-1802f95e6244.png)

![screenshot_2016-07-18-09-04-38](https://cloud.githubusercontent.com/assets/20212920/16915962/75bbc818-4cc8-11e6-9853-efddfae41dc2.png)

**Comment by Gabymorillo** [comment]
Prueba: 18/07/16

Desde el teléfono físico persiste este error en la versión 20.7

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16917786/0f59087a-4cd1-11e6-94b7-818516e30dee.png)

**Comment by dorzar1989** [comment]
En la version 20.7 de la CBP Persiste el error 

- Fecha: 18/07/20016

- Movil:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16919423/95b6ec60-4cd7-11e6-97f1-4e434d32221e.png)

**Comment by arosiopr** [comment]
en la versión 20.8 de CBP se soluciono este error en mi dispositivo.
Emulador
Google Nexus 4
Android 4.4.4

**Comment by wendyduran90** [comment]
En la versión 21.1 persiste el error las notificaciones llevan a la community de la wallet . Esta prueba se realizo desde un móvil con versión de android 4.4.4

**Comment by RubenSem** [comment]
En la version 21.1 se soluciono este error en mi dispositivo.
Emulador
Google nexus 4
Android 4.4.4

**Comment by nelsonalfo** [comment]
por favor cerrar este caso

**Comment by dorzar1989** [comment]
En la version 21.3 de la CBP esto ya no sucede, Cerrar Caso por favor :+1:

**Comment by IsbetVR** [comment]
Closed #555

**Comment by andreagmarcano** [comment]
En la version 21.3 de CBP ya no persiste el error.
