### ISSUE TITLE
CBP- Crypto Broker- Connections: mensaje al abrir pantalla.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#556]
#### Nombre pantalla

Connections

### Nombre de la Aplicación 

CBP V 17.1
-----

##### Reporte de error: 

Al entrar en la Community como broker, específicamente en Crypto Customers Users al tratar de abrir la pantalla Connections en vez de salirme la lista de contactos me aparece el siguiente mensaje el cual dura un par de segundos y luego desaparece:

![16-6](https://cloud.githubusercontent.com/assets/19883115/16120193/80b70b26-33a8-11e6-9250-1f37b10d942c.png)

   
------

#### Dispositivo desde donde se realizo la prueba 

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16120236/9cfa2a34-33a8-11e6-83f7-f345e4109575.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/318603/logcat.txt)

**Comment by abicelis** [comment]
@GeronimoVierma Prueba la version 17.3 ahora que salga mas tarde hoy, se hicieron mejoras con respecto a eso.

**Comment by GeronimoVierma** [comment]
@abicelis He estado probando con la 17.3 y no me ha vuelto a salir el mensaje.

**Comment by yolandayancel** [comment]
Prueba 17-06-2016
Caso    556   CBP V 17.3
Nexus 4 5.0.0
En este emulador, no ocurre lo reportado. 
![caso 556](https://cloud.githubusercontent.com/assets/17283358/16153209/2d0129ae-346f-11e6-9b20-4fe91e2704f3.png)
[logcatcaso 556.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320644/logcatcaso.556.txt)

**Comment by abicelis** [comment]
@GeronimoVierma @yolandayancel  No les saldra mas ese mensaje. Mientras se arreglen lo problemas que existen de p2p ocurriran cosas como que dejen de ver a usuarios conectados pero este error no saldra mas.

Creo que pueden cerrar esto, hay otros issues de p2p abiertos.

**Comment by AdryCanonico** [comment]
@abicelis @MaviDavsa  En la version 17.4 persiste el error. Por favor reabrir el caso. 

![screenshot_2016-06-20-09-01-53](https://cloud.githubusercontent.com/assets/18584168/16195441/677cb6d8-36c3-11e6-8d2b-4a985e5b521e.png)

[alogcat.2016-06-17-10-42-34-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/323484/alogcat.2016-06-17-10-42-34-0430.txt)

09:01 am

Dispositivo:

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16195974/c19243b6-36c5-11e6-8d64-01cd22da4e63.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by AdryCanonico** [comment]
@GeronimoVierma  En la version 18.4 no sale el error.

**Comment by GeronimoVierma** [comment]
En la versión 18.4 no me aparece el error.
