### ISSUE TITLE
CBP_Al presionar una notificacion se colgo la aplicacion

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#557]
#### Nombre pantalla
home Crypto Broker

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   * estaba en el menu home de la aplicacion y llego una notificacion de nueva negociacion, al presionarla, la aplicacion se colgo y salio el error de que fermat no responde y tuve que reiniciar la aplicacion y al ingresar no se veian los iconos de la pantalla Wallets de fermat, fue necesario reiniciarla de nuevo para poder verlos

![screenshot_2016-06-16-09-54-55](https://cloud.githubusercontent.com/assets/17274154/16120427/3e1c1e9a-33a9-11e6-92ac-5fed7ea2b41f.png)
![screenshot_2016-06-16-10-09-32](https://cloud.githubusercontent.com/assets/17274154/16120445/4a3f3ea0-33a9-11e6-9b17-566bfb569c0a.png)
![screenshot_2016-06-16-10-10-38](https://cloud.githubusercontent.com/assets/17274154/16120455/54b256ec-33a9-11e6-8375-87ea6ceaacf0.png)
![screenshot_2016-06-16-10-11-02](https://cloud.githubusercontent.com/assets/17274154/16120470/5b6258fc-33a9-11e6-88c0-73857443c723.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16120504/712dc6c6-33a9-11e6-93e3-f67ab9eaa039.png)

**Comment by maydiamc** [comment]
@nelsonalfo @sanro14 version 17.1

**Comment by yolandayancel** [comment]
Prueba 17-06-2016
Caso  557    CBP V 17.3
Nexus 4 5.0.0
En este emulador, si ocurre algo parecido a lo reportado pero en la notificación en la crypto Broker user:Al ingresar no se puede salir y sale el recuadro siguente
![al entrar a notificaciones no deja salir](https://cloud.githubusercontent.com/assets/17283358/16152980/19daeb7c-346e-11e6-9626-e7dcd8cb2597.png)
[logcat no sale de notificaciones.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320624/logcat.no.sale.de.notificaciones.txt)

**Comment by abicelis** [comment]
@maydiamc @yolandayancel Estoy aferiguando con la gente del android-core a ver que puede ser esto. El error parece no ser exactamente de CBP.

**Comment by yolandayancel** [comment]
Recibido.
Saludos

**Comment by AdryCanonico** [comment]
@abicelis  En la version 18.3 de CBP esta sucediendo el mismo error.

![screenshot_2016-06-27-08-33-25](https://cloud.githubusercontent.com/assets/18584168/16380116/ed46ebdc-3c3e-11e6-88a6-f1f5fc2618e0.png)

**Comment by nelsonalfo** [comment]
@AdryCanonico puedes pasar por favor el archivo `logcat.txt` de cuando se dio esa situación?

**Comment by AdryCanonico** [comment]
@nelsonalfo  hora 8:33am
[alogcat.2016-06-27-09-55-02-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/335011/alogcat.2016-06-27-09-55-02-0430.txt)

**Comment by maydiamc** [comment]
en la version 18.8 esto no sucede
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16531486/7e7e009a-3f96-11e6-81d5-1633af442b37.png)
