### ISSUE TITLE
CBP-LETRAS MONTADAS EN TEXTO BROKER LIST

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#558]
### Template issue error report

 Nombre pantalla

BROKER LIST

### Nombre de la Aplicación 

CBP- VERSION 17.1

Reporte de error: 

CUANDO ESTOY TRABAJANDO CON LA APLICACIÓN DESDE MI MÓVIL  PERSONAL, LAS LETRAS SALEN MONTADAS EN EL TEXTO QUE IDENTIFICAN A CADA UNO DE LOS BROKER EN LA LISTA, DENTRO DE LA CRIPTO CUSTOMER, TAL Y COMO SE SEÑALA A CONTINUACIÓN;

![image](https://cloud.githubusercontent.com/assets/18740418/16120663/1afb3878-33aa-11e6-8da2-e768efb28114.png)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [x] Teléfono Físico

![image](https://cloud.githubusercontent.com/assets/18740418/16120670/270e4cb8-33aa-11e6-864e-3186fe939e5a.png)

**Comment by camilavaleria** [comment]
@MaviDavsa ,@abicelis

**Comment by abicelis** [comment]
@camilavaleria @MaviDavsa Prueba la proxima version 17.3 y me dices como te fue.

**Comment by abicelis** [comment]
@camilavaleria Quise decir version 17.3!

**Comment by camilavaleria** [comment]
caso solucionado
