### ISSUE TITLE
CBP - Broker -  Al salir de la aplicación borra los datos del Stock Wallets

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#559]
#### Nombre pantalla

Select Stock Wallets

### Nombre de la Aplicación 

CBP

-----

##### Reporte de error: 

Al salir de la aplicación y volver a entrar borra los datos de las wallets que ya tenia configurados.
   
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16120793/a361015c-33aa-11e6-9c88-90aaccbbbb22.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16120804/a8ca6d40-33aa-11e6-9220-2f95eb3a1a05.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/318640/logcat.txt)

**Comment by nelsonalfo** [comment]
Lograste llegar al home de la wallet cuando cerraste la app?

**Comment by abicelis** [comment]
@Hernandezsmanu De no terminar el Wizard (y llegar al home de la broker o customer wallet), la wallet te obligara a hacer el wizard de nuevo.

**Comment by Hernandezsmanu** [comment]
Si efectivamente tenia ya todo configurado aquí, en el banking y en la cash pero al salir y volver a entrar me salia que debía configurar de nuevo, esto me ocurrió en 2 ocasiones. Sera cuestión de probar en la nueva versión a ver si ocurre lo mismo y les informo. @nelsonalfo @abicelis

**Comment by abicelis** [comment]
@Hernandezsmanu haz la prueba y **llega al home de la broker wallet!**
Si se repite de nuevo indagamos mas

**Comment by AdryCanonico** [comment]
@abicelis en la versión 18 sigue persistiendo el error.

**Comment by MaviDavsa** [comment]
@AdryCanonico @Hernandezsmanu Traten de entregar el archivo de Text. Traten!

**Comment by abicelis** [comment]
Que ha pasado con este issue? @Hernandezsmanu llegaste alguna vez a configurar la broker wallet, llegando al home?

**Comment by Hernandezsmanu** [comment]
Ya hice las pruebas en la versión 18.5 y no me sucedió mas.
