### ISSUE TITLE
CBP_La Community no muestra a los usuarios conectados

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#560]
#### Nombre pantalla
Community

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   *Al ingresar la community, bien sera broker o customer, esta no muestra ningun usuario, solo aparece brevemente pleas wait, e inmediatamente indica que no hay usuarios disponibles, a pesar que hay alrededor de 6 usuarios creados y conectados.
   
![screenshot_2016-06-16-18-53-36](https://cloud.githubusercontent.com/assets/17274154/16135873/3ece5668-33f0-11e6-9286-98de47760144.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16135892/4fbc6410-33f0-11e6-8781-1798e9ebe3a0.png)

**Comment by maydiamc** [comment]
@nelsonalfo @sanro14 version 17.3

**Comment by JeanFranco498** [comment]
Me pasa exactamente lo mismo, a pesar de que hay brokers creados no me aparece ninguno en mi caso soy customer 

![screenshot_10](https://cloud.githubusercontent.com/assets/19807906/16136055/755bd5e8-33f5-11e6-959c-a24edc4b9ec3.png)

![screenshot_11](https://cloud.githubusercontent.com/assets/19807906/16136059/7af19ed4-33f5-11e6-9769-a56b7040eac1.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/319492/logcat.txt)

**Comment by marielis-urbina** [comment]
A pesar de que estamos 7 contactos repartidos entre las Crypto Broker y la Crypto Customer al entrar a la pantalla aparece en blanco, indicando que no existen contactos, impidiendo continuar con el proceso de negociaciones.

![sin contactos](https://cloud.githubusercontent.com/assets/19353722/16135609/a09a029a-33ee-11e6-957a-de450b7fc817.png)

#### Dispositivo desde donde se realizo la prueba

![samsung](https://cloud.githubusercontent.com/assets/19353722/16135627/cb5cdcf0-33ee-11e6-94bd-6d74b22f9056.png)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/319499/logcat.txt)

**Comment by RubenSem** [comment]
Mismo problema.

![screenshot_2](https://cloud.githubusercontent.com/assets/19676223/16136078/7e6a986c-33f1-11e6-9e4b-5ff031e4553f.jpg)

Especificaciones: 

![screenshot_3](https://cloud.githubusercontent.com/assets/19676223/16136087/94269cfa-33f1-11e6-8258-93dd84ec899d.jpg)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/319507/logcat.txt)

**Comment by GeronimoVierma** [comment]
Mismo problema, tengo perfil Broker y entro a las Comunity y no puedo ver ni a los Broker ni a los Custommer.

![last](https://cloud.githubusercontent.com/assets/19883115/16136213/8b66daac-33f2-11e6-8930-a455d086a36d.png)

![issues](https://cloud.githubusercontent.com/assets/19883115/16136218/98474a5e-33f2-11e6-905c-a6898d4baae7.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/319508/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 17-06-2016
Caso  560    CBP V 17.3
Nexus 4 5.0.0
En este emulador, si ocurre lo reportado, pero explico: que se veian los crypto customer y los broker de la comunnity,  pero al cerrar el emulador y abrir nuevamente no se ven. Al ingresa a mis contactos en la crypto  customer  estan todos.
![caso desaparecieron los user en la customer](https://cloud.githubusercontent.com/assets/17283358/16154295/f4122d50-3473-11e6-8e90-8d01383dbd3b.png)
[logcat desaparecieron los user.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320701/logcat.desaparecieron.los.user.txt)

**Comment by abicelis** [comment]
@maydiamc @JeanFranco498 @RubenSem @marielis-urbina @GeronimoVierma @yolandayancel  Sip, hay problemas con P2P, ellos estan resolviendo, nosotros estamos ayudando.
Cuando se resuelva aquello les escribire aca.

**Comment by yolandayancel** [comment]
Recibido y pendiente Alejandro
Saludos

**Comment by yolandayancel** [comment]
Prueba 21-06-16
Caso 560 CBP V18
Nexus 4 5.0.0 320dpi
En este emulador aparecen los crypto broker user, pero el fondo de la pantalla está en blanco. Cierro el emulador y al abrir sigue el fondo en blanco.
![community blanco](https://cloud.githubusercontent.com/assets/17283358/16231487/3f0863aa-3790-11e6-883e-bf5433104a2c.png)
[logcat community.txt](https://github.com/Fermat-ORG/beta-testing-program/files/325685/logcat.community.txt)
