### ISSUE TITLE
TKY-ART - eliminó totalmente una canción de Fan Wallet

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#565]
### TKY - ART (versión v1u2)

-----

##### Reporte de error: 

   *De acuerdo a la explicación de la Fan Wallet, yo puedo "eliminar" una canción, pero me queda el registro, por decirlo así por si quiero volver a descargarla desde la Fan Wallet. En mi caso, probé eliminarla y efectivamente me la dejó eliminar del almacenamiento local pero me dejó el acceso en la Fan Wallet, el emulador se me cerró y cuando lo volví a abrir y me fui a la Fan Wallet, se desapareció (Pantalla 1), refresco la pantalla y nada, no me la vuelve a descargar.
   
------

#### Pantalla 1

![screenshot_41](https://cloud.githubusercontent.com/assets/19142276/16136321/91e6164a-33f7-11e6-9e20-799ef0000742.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Andriod: 5.0.0
- DPI: 320 dpi
- API 21 768x1280

![nexus 4 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16136356/d2d3dad4-33f7-11e6-803b-a6cb24dc68c6.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by IsbetVR** [comment]
@darkestpriest

**Comment by darkestpriest** [comment]
Chequea esto @lostwood

**Comment by lostwood** [comment]
Ya lo corregimos, en la proxima versión que subamos, lo podran probar @IsbetVR

**Comment by IsbetVR** [comment]
@MaviDavsa  Solucionado. Las elimina pero no las borra de la lista, permitiendo volver a descargarlas.
Versión v1u3.

- [x] Emulador
- Google Nexus 4
- Versión de Android: 5.1.0
- 320 dpi
- API 22 768x1280
