### ISSUE TITLE
TKY-ART - Voltea imagen de perfil ART

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#566]
#### Nombre pantalla

Artist Identity

### Nombre de la Aplicación 

TKY-ART (version v1u2)
-----

##### Reporte de error: 

   Coloque en el emulador una imagen desde mi computadora (foto tomada desde un samsung galaxy s4) y la voltea. Tamaño de imagen (Dimensiones 2322x4128)

![screenshot_6](https://cloud.githubusercontent.com/assets/5313335/16136386/d46271ac-33f3-11e6-885d-f21751845d46.png)

![screenshot_11](https://cloud.githubusercontent.com/assets/5313335/16136395/df478da0-33f3-11e6-80cc-2524aad5dba1.png)

   
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_9](https://cloud.githubusercontent.com/assets/5313335/16136407/e9f6a3c6-33f3-11e6-92a7-77d81c2dada6.png)

![screenshot_10](https://cloud.githubusercontent.com/assets/5313335/16136409/ecab0274-33f3-11e6-8df4-72f1bd4f22ba.png)

**Comment by Hernandezsmanu** [comment]
En la identidad de FAN ocurre lo mismo.

![screenshot_7](https://cloud.githubusercontent.com/assets/5313335/16136466/8893a114-33f4-11e6-9ea3-5b1a735c69e0.png)

**Comment by Hernandezsmanu** [comment]
@darkestpriest

**Comment by darkestpriest** [comment]
Saludos, ¿puedes indicar la dirección en la cual se tomó la imagen?

**Comment by Hernandezsmanu** [comment]
En dirección te refieres a horizontal/vertical ?

**Comment by darkestpriest** [comment]
Exacto, la app coloca la foto en la dirección en la cual se tomó originalmente, si se toma de forma vertical, en la app sale en esa forma. Si la foto fue tomada en esa dirección ¿por que se repota como un issue?

**Comment by darkestpriest** [comment]
¿probaste con otro foto, sucede todo el tiempo? ¿Es replicable en cada caso?

**Comment by Hernandezsmanu** [comment]
Si exacto, sucede con otras imágenes y están de la misma manera (en dirección vertical).

![screenshot_12](https://cloud.githubusercontent.com/assets/5313335/16137077/d09cb8ec-33f9-11e6-9eb3-908dd4bc2f3d.png)

**Comment by darkestpriest** [comment]
Pregunto nuevamente :

> Saludos, ¿puedes indicar la dirección en la cual se tomó la imagen?
Ese dato es importante antes de poder reportar esto como un issue, ya que no sería problema de la app, simplemente coloca la imagen que le es proporcionada.

**Comment by juanaso** [comment]
Hola! @Hernandezsmanu podrias hacerme un favor y enviarme esa imagen a este correo sulbaranja@gmail.com asi agilizamos esto gracias!

**Comment by Hernandezsmanu** [comment]
Ok @juanaso ya la envió.

**Comment by Hernandezsmanu** [comment]
Solucionado en la versión v1u7, por favor cerrar.
