### ISSUE TITLE
CBP Al querer cambiar la cuenta no me deja colocarla completa en la Customer 

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#567]
### Nombre de la Aplicación: CBP 
----
##### Reporte de error: 

Cuando quiero cambiar la cuenta del banco de donde voy hacer la negociación no me permite colocarla la cuenta completa solo 10 dígitos de ella.

![banco](https://cloud.githubusercontent.com/assets/19353722/16136453/51d922f2-33f4-11e6-8f06-28c483454858.png)

#### Dispositivo desde donde se realizo la prueba
![samsung](https://cloud.githubusercontent.com/assets/19353722/16136459/6335517e-33f4-11e6-99f7-f411a766bd4d.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/319529/logcat.txt)

**Comment by yalayn** [comment]
Yo @yalayn revisare este issue.

**Comment by yolandayancel** [comment]
Prueba 17-06-16
Caso 567 CBP V17.3
Nexus 4 5.0.0
Ocurre lo mismo reportado. El número de cuenta dice que acepta 100 número, pero solo acepta 10
![caso 567](https://cloud.githubusercontent.com/assets/17283358/16150995/480e923c-3464-11e6-85ed-dba9084ccd86.png)
[logcat 567.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320488/logcat.567.txt)

**Comment by yalayn** [comment]
Buenos días ya se corrigió el error. Debe estar disponible para la próxima versión de la app.
Saludos.
![captura de pantalla de 2016-06-17 08 59 43](https://cloud.githubusercontent.com/assets/4664287/16151323/35ad246c-3466-11e6-8b64-e6235dffd52b.png)

**Comment by yalayn** [comment]
Buenas tardes, Se acaba de subir la versión 17.4, que tiene disponible esta corrección. Si no se las han facilitado pronto lo estarán haciendo.
Saludos.

**Comment by marielis-urbina** [comment]
En la versión 17.4 de la CBP, puedes colocar completa la cuenta

**Comment by marielis-urbina** [comment]
@yalayn
