### ISSUE TITLE
CBP-Crypto Broker-checkbox con fondo negro

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#569]
### Nombre de la Aplicación: Crypto Broker

-----

##### Reporte de error: 

   *Al seleccionar el checkbox en la configuración de crypto broker el fondo sale negro, no se si hubo cambio de color en esta nueva versión, la 17.3

![screenshot_2016-06-16-20-03-21](https://cloud.githubusercontent.com/assets/5313326/16137830/edc3b7a2-3400-11e6-9cc2-a0bb6b79ba3f.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16137829/eb2c07e2-3400-11e6-9316-ea2f93d454c9.png)

**Comment by arosiopr** [comment]
@MaviDavsa @nelsonalfo

**Comment by abicelis** [comment]
Tu dispositivo es el que decide cambiarle el color al checkbox, pasa aqui igual que algunos samsung, donde equellos usan un tipo de letra distinto al programado.
No creo que se pueda hacer mucho por este alcatel @arosiopr :/

**Comment by arosiopr** [comment]
a ok @abicelis pense era la apk porque en versiones anteriores a la 17.3 salia el fondo gris, es mas solo en esa parte sale en negro, que loco, bueno supongo le dire a mavi que lo cierre :)

**Comment by arosiopr** [comment]
@MaviDavsa lo puedes cerrar :)
