### ISSUE TITLE
Bit Coin Wallet_Home

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#57]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla
Home

### Bitcoin Wallet 

-----
![dfgdf](https://cloud.githubusercontent.com/assets/17273005/13532262/b2f63b8c-e1fc-11e5-8224-75d3882bf207.JPG)

##### Reporte de error: Nuevas notificaciones de Fermat salen aproximadamente cada 15 min, sin ninguna información o notificación referente a la aplicación en si. Estas notificaciones salen en home, contacto, en cualquier parte pero salen y el problema esta en que no te están notificando realmente nada.

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: Android 5.0

**Comment by nattyco** [comment]
@MaviDavsa  verificar con la nueva version que descargues si el error persiste.

**Comment by MaviDavsa** [comment]
@nattyco Si persiste! :((

**Comment by nattyco** [comment]
@MaviDavsa Se verfico que estas notificaciones sin datos las esta generando un robot de pruebas que envia request de conexion con el usuario "actorintrauser"

**Comment by MaviDavsa** [comment]
@nattyco No nena no dice eso! Las notificaciones dicen New Notification! Pero no tiene nada de nada!

**Comment by nattyco** [comment]
@MaviDavsa verificar si con la nueva version sigue pasando esto.
