### ISSUE TITLE
CBP-Customer Wallet-Texto montado en el Home Negotiations

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#570]
### Nombre de la Aplicación Crypto Customer

-----

##### Reporte de error: 

   *Como se puede observar en la siguiente imagen todos los datos de la negociación salen montados

![screenshot_2016-06-17-09-31-34](https://cloud.githubusercontent.com/assets/5313326/16152191/6c4dc3c4-346a-11e6-8fd1-1e7eb70ef734.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16152197/75b3440c-346a-11e6-881c-62537c3c716c.png)

**Comment by arosiopr** [comment]
@MaviDavsa @abicelis

**Comment by abicelis** [comment]
@arosiopr Okay, me encargo de esto

**Comment by abicelis** [comment]
@arosiopr En la version 17.5 esta este fix, revisa y me dices si cuadra todo plz

**Comment by nelsonalfo** [comment]
en la version 18 esta esta correccion

**Comment by arosiopr** [comment]
no la he podido probar, no sale para agregar la cuenta

**Comment by arosiopr** [comment]
@MaviDavsa  solucionado. Se puede cerrar
