### ISSUE TITLE
CBP-Customer Wallet-Negotiation Details-Texto montado

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#571]
### Nombre de la Aplicación : Customer Wallet

-----

##### Reporte de error: 

  * Al ingresar a Negotiation Details en la parte nro 6 el texto se monta sobre el número

![screenshot_2016-06-17-09-06-56](https://cloud.githubusercontent.com/assets/5313326/16152610/8e5d642c-346c-11e6-85af-1ded931696b4.png)

* En la parte nro 1 Exchange Rate Reference se monta los textos

![screenshot_2016-06-17-10-02-22](https://cloud.githubusercontent.com/assets/5313326/16153046/6faa50f6-346e-11e6-9e15-11576b467f29.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16152619/98500174-346c-11e6-812f-636ea8353f2a.png)

**Comment by arosiopr** [comment]
@MaviDavsa @abicelis

**Comment by abicelis** [comment]
@arosiopr Es dificil probar este dispositivo, es demasiado pequeno y reporta mal su tamano a android.... Alcatel no good.
Revisa la version v17.4 a ver como se te ve y me dices.

**Comment by arosiopr** [comment]
@MaviDavsa  solucionado. Se puede cerrar
