### ISSUE TITLE
Bitcoin Wallet-texto de historial de transacción borroso y sobre montado.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#572]
#### Nombre pantalla

Bitcoin Wallet

### Nombre de la Aplicación 

Bitcoin Wallet (CBP-17.3)
-----

##### Reporte de error: 

En la versión 17.3 de CBP ocurre que luego de finalizar un contrato como Broker y al entrar a la Bitcoin Wallet a ver los btc enviados salen unas letras borrosas y mal ubicadas en esa pantalla.

![letras](https://cloud.githubusercontent.com/assets/19883115/16154151/60d01390-3473-11e6-94ee-2c4ecdfbbe4c.png)
 
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16154256/d298236e-3473-11e6-917c-2956c353f908.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/320702/logcat.txt)

**Comment by GeronimoVierma** [comment]
@nattyco

**Comment by nelsonalfo** [comment]
Este es un mensaje que enviamos a la wallet para indicar que se realizo un pago y se muestra el ID del contrato asociado a ese ingreso de bitcoins. @nattyco debería corregir que cuando sean mensajes largos estos se muestren de forma adecuada

**Comment by nattyco** [comment]
@nelson lo voy a revisar, habiamos limitado la cantidad de la nota a 25 caracteres, para el caso de estas trnasacciones necesitas mostrar todos esos datos? porque sino tendrias que limitar la nota.

**Comment by nelsonalfo** [comment]
Si se puede reducir el mensaje, hacerlo mas corto

**Comment by GeronimoVierma** [comment]
Luego de completar un contrato en la CBP-18 me sale la información de la transacción de esta forma:

![contrato](https://cloud.githubusercontent.com/assets/19883115/16234952/e1675ee2-379c-11e6-8a2f-20e8fe283a85.png)

![issues](https://cloud.githubusercontent.com/assets/19883115/16235059/43ea5d12-379d-11e6-9026-2beb42b90683.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/325925/logcat.txt)

**Comment by GeronimoVierma** [comment]
Al culminar un contrato de forma exitosa (estando como broker)  en la versión 19.2 CBP, al entrar a la Bitcoin Wallet a ver los BTC enviados siguen saliendo las letras del record mal ubicadas (imagen 1):

![chu](https://cloud.githubusercontent.com/assets/19883115/16565133/45b76496-41d9-11e6-9ec7-a4ddef4c98f0.png)

También al pasar BTC a mi stock en Stock Management y luego ir a la Bitcoin Wallet a ver el record de la transaccion aparece ese registro mal ubicado en las ultimas letras (imagen2):

![chu1](https://cloud.githubusercontent.com/assets/19883115/16565322/871f5fc8-41da-11e6-8bc8-f65fd235e125.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16565586/51e052f2-41dc-11e6-8c36-275f147a2435.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346569/logcat.txt)

**Comment by IsbetVR** [comment]
@nelsonalfo 
En la versión de CBP 19.2, al hacer las transacciones desde Crypto Broker para el Stock con la bitcoin Wallet, se montan las letras de la leyenda en la Bitcoin Wallet 

![screenshot_24](https://cloud.githubusercontent.com/assets/19142276/16568526/616c07bc-41f9-11e6-8fc7-e1dd15ac5b49.jpg)

#### Dispositivo de prueba

- [x] Emulador
- Google Nexus 4
- Versión de android: 5.0.0
- 320 dpi
- API 21 768x1280

**Comment by yolandayancel** [comment]
Prueba 05-07-2016
Caso      CBP V 19.5
Nexus 5 5.0.0
Hora 3.:25PM
[logcat gero.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348466/logcat.gero.txt)

En este emulador, si ocurre lo reportado por Geronimo. Despues de la negociación,  en la Bitcoin Wallet aparece lo recibido las letras y fechas amontonadas. Se puede observar que las fechas están correctas.
 
![gero](https://cloud.githubusercontent.com/assets/17283358/16597229/d1c2a74c-42c5-11e6-9bc5-307fabad0728.png)

**Comment by arosiopr** [comment]
en la version 20.4 de CBP persiste el error se sigue montando el texto en el caso cuando se descuenta hacia la broker wallet

![screenshot_105](https://cloud.githubusercontent.com/assets/5313326/16769940/b4202266-4818-11e6-87ec-17820a6d3d82.png)



![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16769879/7f520c5c-4818-11e6-9dbb-42fb5be12f1e.png)

**Comment by arosiopr** [comment]
en la version 20.6 de CBP persiste el error

![screenshot_119](https://cloud.githubusercontent.com/assets/5313326/16843258/85ca6056-49ae-11e6-88af-a942fd2bfc9e.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16843286/99d71e7c-49ae-11e6-8093-8577372e473a.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.7  de CBP persiste el error grafico:


![1807](https://cloud.githubusercontent.com/assets/19883115/16916542/55be3eb2-4ccb-11e6-8902-1059764b2be4.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16916585/84f1c906-4ccb-11e6-946f-5dcbf40e95f8.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.8 de CBP se puede ver que la transacción esta bien ubicada en la casilla "Send" (imagen 1) y "Received"(imagen 2):

![chal](https://cloud.githubusercontent.com/assets/19883115/16967383/ae7af55c-4dd6-11e6-8af5-277dc2de253b.png)

![calli](https://cloud.githubusercontent.com/assets/19883115/16967451/f8ad1902-4dd6-11e6-8c71-84a21ddc88ce.png)

**Comment by marielis-urbina** [comment]
En la versión 21.0 de CBP esto no sucede en mi emulador

![contratooooooooooooooooooooooo](https://cloud.githubusercontent.com/assets/19353722/17145333/be7f7b02-5327-11e6-8556-e03a314025d0.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17145294/a484a722-5327-11e6-9d22-81ba6e11c3e9.png)

**Comment by GeronimoVierma** [comment]
En la versión 21.0 de CBP pude verificar un recibo de pago desde la Crypto Broker por parte de un Customer en un contrato, como se puede ver en la imagen 1 el error gráfico esta solucionado:

Casilla "Broker Wallet"
![ss](https://cloud.githubusercontent.com/assets/19883115/17179356/e4b72a30-53e6-11e6-8073-aefa520c1894.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17179403/1a31159a-53e7-11e6-8c40-a356bfc3fba6.png)

**Comment by IsbetVR** [comment]
Solucionado en la versión 21.0 CBP

**Comment by IsbetVR** [comment]
Closed #572
