### ISSUE TITLE
CBP_Crypto Customer: error en la aplicacion al pasar de negociacion a contrato

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#573]
#### Nombre pantalla
Home

### Nombre de la Aplicación 
Crypto Customer

-----

##### Reporte de error: 

   *Estaba realizando una negociacion con un usuario, en el instante en que se realizo el ultimo paso y esta paso a la pestaña de contratos, la aplicacion se colgo e inmediatamente llego una notificacion de que el contrato habia expirado, espere unos segundos pero la aplicacion seguia colgada, pase a reiniciar la aplicacion y al ingresar, en la pantalla de wallet y P2P, no se mostraban los iconos, reicie la aplicacion unas 4 veces y no salia el logo de fermat sino que entraba como si la tuviera en segundo plano, osea directo a la pantalla de wallet, fue necesario reiniciar el dispositivo para que la aplicacion funcionara normalmente, al ingresar a la crypto customer la pestaña de negociaciones aparecia en blanco (tenia otra negociacion con el usuario pero en otra moneda) no se veia ninguna negociacion, igual que la pantalla de contratos, sino que aparecian ambas expiradas en la pantalla de contracts history.

Nota : no se pudieron tomar muchas capture, pero a continuacion muestro imagenes de mi dispositivo y una del dispositivo del usuario que hizo la transaccion conmigo para mostrar mas o menos un orden de echos

![b52527a8eb22ed3a70bab2bd8c53dbc5078e8b32747887ca36 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17274154/16160202/a35851ba-3490-11e6-99a5-124ebbaddf15.png)
![screenshot_2016-06-17-08-59-39](https://cloud.githubusercontent.com/assets/17274154/16160210/b0b7359c-3490-11e6-8453-6b311714e53a.png)
![screenshot_2016-06-17-09-07-30](https://cloud.githubusercontent.com/assets/17274154/16160213/b78cdf0c-3490-11e6-9294-326d472c93cf.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16160266/07e1ad70-3491-11e6-8766-4583d51a3760.png)

**Comment by maydiamc** [comment]
@nelsonalfo version 17.3
@furszy sucedio el problema del caso #568

**Comment by yalayn** [comment]
Hola @maydiamc. En cuanto a la negociación lo que ocurrió que se cancelo por vencimiento en la fecha de entrega. Allí no debería haber problema por que la app esta programada para eso. Seria un problema si la fecha que indicaste era diferente a la fecha de expiración.

**Comment by maydiamc** [comment]
@yalayn si las fechas eran diferentes, osea las fechas que se colocaron tenian tiempo suficiente aun como para que el contrato no se venciera en ese momento, ademas aclaro que la aplicacion no envio ningun aviso de expiracion con anterioridad, simplemente sucedio de buenas a primeras, disculpa sino aclare ese detalle en el issue

**Comment by yalayn** [comment]
Hola @maydiamc, eso puede estar sucediendo por un problema en las fechas a la hora de recibirlas, estamos trabajando en corregir eso y así luego verificar si es eso lo que esta haciendo vencer el contrato antes de la fecha indicada.

**Comment by maydiamc** [comment]
en la version 19.2 de la CBP se pudo concretar un contrato, no hubo problema con las horas, tudo fue fluido, claro aclaro estoy haciendo la prueba desde un emulador y con android 5.1

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16565083/0052eeca-41d9-11e6-90f3-1f7e7426aa92.png)
