### ISSUE TITLE
CBP - Broker - Stock Management en notación científica

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#574]
### CBP (Versión 17.4) 

-----

##### Reporte de error: 

   *Cuando tengo las Wallets configuradas en el Stock Management, al pasarle montos muy grandes a las Wallets los coloca en notación científica y corta la parte inferior, pues lo está colocando abajo al tener muchas cifras. 
   
------
#### Pantalla 1

![screenshot_3](https://cloud.githubusercontent.com/assets/19142276/16168087/8938be0a-34cc-11e6-96ca-90f6fe3806c8.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Android 5.0.0
- 320 dpi

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16168110/d36bfbea-34cc-11e6-99fe-2ad3d1d4cd2c.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @abicelis

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by abicelis** [comment]
@IsbetVR @MaviDavsa prueben la version 18.1 y me avisan plz

**Comment by maydiamc** [comment]
en la version 18.1 no coloca el numero en notacion cientifica, pero si el monto es muy grande se corren los cuadros y se ve cortado el ultimo @abicelis 
![screenshot_2016-06-23-11-29-12](https://cloud.githubusercontent.com/assets/17274154/16309324/227a8634-3932-11e6-92a2-a407d88ad593.png)
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16309336/2c6fffd4-3932-11e6-8d88-939b05377a24.png)

**Comment by nelsonalfo** [comment]
Esos cuadros son una lista en la que se puede hacer scrool horizontalmente, por lo que puedes moverlo hacia la izquierda para ver el resto del contenido de esa lista

**Comment by maydiamc** [comment]
@nelsonalfo no se ve bien graficamente, mi recomendacion es que lo coloquen verticalmente para poder colocar montos grandes y que no afecte la visibilidad de la pantalla.

**Comment by IsbetVR** [comment]
@abicelis En la versión V18.1 de la CBP no está pasando el monto a la parte inferior del cuadro azul, lo coloca al lado de la denominación de la moneda, pero el cuadro de la tercera wallet lo corta y no permite hacer scroll horizontalmente @nelsonalfo, yo lo estoy probando en emulador.

![screenshot_62](https://cloud.githubusercontent.com/assets/19142276/16321596/ce02aea8-396b-11e6-9d66-b425a7d52848.jpg)

Dispositivo de prueba:

- [x] Emulador
- Google Nexus 4
- Versión de Android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16321687/5187e04a-396c-11e6-82f2-5fbe0863c972.jpg)

**Comment by maydiamc** [comment]
mi dispositivo es un telefono fisico, con la version 18.1
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16321754/7b7ee69a-3968-11e6-82c8-7ab47dec48fc.png)

**Comment by abicelis** [comment]
@IsbetVR deberia poder hacer scroll horizontal, y de esa forma poder ver todos los montos, sin embargo, es cierto @maydiamc que podria verse mejor.

@nelsonalfo estoy cambiando esa pantalla para presentar mejor esa informacion. Cuando tenga algo les aviso

**Comment by maydiamc** [comment]
@abicelis excelente, esperaremos tu cambio.!

**Comment by abicelis** [comment]
@IsbetVR @maydiamc la versión 18.2 tiene algunas mejoras, sin embargo todavía me falta un par de cosas.

**Comment by abicelis** [comment]
@IsbetVR @maydiamc Prueben la version 18.4 y me dicen!

**Comment by yolandayancel** [comment]
Prueba 29-06-2016
Caso      CBP V 18.4
Nexus 5 5.0.0
En este emulador, no ocurre lo reportado
![caso 574](https://cloud.githubusercontent.com/assets/17283358/16454665/679dc84a-3ddb-11e6-98ab-1e0d80c2980e.png)

[logcat caso 574.txt](https://github.com/Fermat-ORG/beta-testing-program/files/339405/logcat.caso.574.txt)

**Comment by IsbetVR** [comment]
Ya no está pasando el error reportado. 
Solucionado @abicelis
