### ISSUE TITLE
CBP-No se visualizan los contactos en la Broker List 

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#575]
#### Nombre pantalla
Customer Wallet

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   *Hice conexión con varios Broker y al entrar a la pantalla de customer Wallet y darle en la opción de broker list no me aparece ningún contacto, sali y entre varia veces a ver si aparecían los contactos y luego de eso sale el siguiente error "Recovering from system" y se salio a la pantalla principal de Fermat.
 Version: 17.4
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

Marca: Genymotion
Modelo: Google Nexus 5
Version de Android: 5.1.0

![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/16167848/61e655fe-34c4-11e6-8a05-6abd2a2c8ac4.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/16167846/5e3552e8-34c4-11e6-968d-833e571d41d3.png)

@MaviDavsa

**Comment by Gabymorillo** [comment]
Hice las conexiones con los Broker y al irme a la Broker List para hacer las negociaciones la lista sale vacía. 

![screenshot_2016-06-17-19-16-05](https://cloud.githubusercontent.com/assets/17262077/16168157/a8b0b632-34c9-11e6-8f38-665489394e58.png)

![screenshot_2016-06-17-20-18-38](https://cloud.githubusercontent.com/assets/17262077/16168159/b0d83d44-34c9-11e6-9097-610ae689d840.png)

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16168164/bea55ee8-34c9-11e6-8c84-cd39b1877d8e.png)

**Comment by marielis-urbina** [comment]
Con la versión 17.4 de la CBP, logre crear los dos perfiles como Customer y como Broker  haciendo varias conexiones tanto como custome, como de broker, al entrar a la customer Wallet y revisar la Broker List, nunca vi ningún contacto.

![vacio](https://cloud.githubusercontent.com/assets/19353722/16168187/3384e08a-34ca-11e6-9fb6-7d24c0ad8898.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16168191/3ec13750-34ca-11e6-8421-2c454d4053b5.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/321493/logcat.txt)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by danielaporras** [comment]
En la versión 18.5 sigue la falla @nelsonalfo

**Comment by IsbetVR** [comment]
En la versión 19.5 de CBP persisten ambos errores reportados:

1. Las conexiones establecidas con los brokers, no todas salen en la broker list, en algunos casos ni una conexión se refleja en la broker list.
2. El recovering from system error continua saliendo a cada rato, nos interrumpe el proceso constantemente.

**Comment by arosiopr** [comment]
En la Versión 19.9 de CBP persisten los errores:

Las conexiones establecidas con los brokers, no todas salen en la broker list, en algunos casos ni una conexión se refleja en la broker list.

El recovering from system error continua saliendo a cada rato, nos interrumpe el proceso constantemente.

**Comment by arosiopr** [comment]
En la Versión 20.1 de CBP persisten los errores:

Las conexiones establecidas con los brokers, salen en la broker list en la version 20.1 de CBP
tengo conexion con dos brokers y ambos salen en broker list.  El recovering from system error ha salido una sola vez en lo que va de mañana.

Conexion con Manu Broker e Isbet Varela
![screenshot_66](https://cloud.githubusercontent.com/assets/5313326/16689616/c0c23344-44f1-11e6-9b17-84b2af7dc98c.png)

![screenshot_67](https://cloud.githubusercontent.com/assets/5313326/16689622/c82311c6-44f1-11e6-91b3-75831feccf76.png)

Broker List:  Manu Broker e Isbet Varela
![screenshot_68](https://cloud.githubusercontent.com/assets/5313326/16689628/cfea58ce-44f1-11e6-92e0-87bf280db776.png)

**Comment by IsbetVR** [comment]
Persiste el error del "recovering" en la versión 20.1 de CBP (me ha saido un par de veces)


##### Logcat.txt

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354380/logcat.txt)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de CBP persisten el error reportado:

Las conexiones establecidas con los brokers, no todas salen en la broker list, en algunos casos a pesar de tener varias conexiones se refleja solo una y el error de "recovering" nunca me sucedio.

![bc](https://cloud.githubusercontent.com/assets/19353722/16689922/4278b358-44f3-11e6-9c90-de2ba9a87e96.png)
![bc1](https://cloud.githubusercontent.com/assets/19353722/16689923/4a971840-44f3-11e6-95e1-05982c810491.png)
![bc2](https://cloud.githubusercontent.com/assets/19353722/16689935/5a1f8234-44f3-11e6-9449-63963610339d.png)

![bl](https://cloud.githubusercontent.com/assets/19353722/16689938/65b28e02-44f3-11e6-91bb-658736141533.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16690002/b25b87ea-44f3-11e6-8f65-8a3a9cac2e54.png)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354398/logcat.txt)

**Comment by maydiamc** [comment]
en la version 20.1 de cbp cuando se hacen las conexiones, solo algunos usuarios aparecen en la broker list

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16690233/f53a97f8-44f4-11e6-8478-978f5ffc7e49.png)

**Comment by arosiopr** [comment]
En la versión 20.2 persiste el error se establece la conexion, pero no sale en la broker list

**Comment by arosiopr** [comment]
en la version 20.3 se soluciono este error en mi dispositivo sale en broker list todos los brokers con los que tengo conexion @IsbetVR

**Comment by yolandayancel** [comment]
Prueba 11-07-16
Caso 575 CBP V20.3
Nexus 5 5.0.0 api 21 480dpi
Hora del losgat: 02:32pm
[575.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357804/575.txt)

Tengo varias conexión con varios Broker y al entrar a la crypto  customer Wallet y darle en la opción de broker list no me aparece ningún contacto.
![575](https://cloud.githubusercontent.com/assets/17283358/16742324/2ef809e4-4775-11e6-89c9-2a963c058c7c.png)

**Comment by marielis-urbina** [comment]
En la versión 20.4 de la CBP este error no se repite en mi emulador. (Noche 11-6)

![cap](https://cloud.githubusercontent.com/assets/19353722/16748830/7768ec4c-4794-11e6-8d5e-e5369646ba54.png)

![cap2](https://cloud.githubusercontent.com/assets/19353722/16748833/7a6f4bc0-4794-11e6-90c1-53bb083ee0b2.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16748845/87d7e682-4794-11e6-982d-d860655f9d04.png)

**Comment by sanro14** [comment]
Solucionado en la versión 20.4
