### ISSUE TITLE
CBP_NEGOTIATION_NO HACE ENVIOS EN LA NEGOCIACION

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#576]
1. El customer  inicia la negociacion con el broker.

2. El broker recibe y modifica la negociación y la devuelve al customer.

3.El customer recibe la negociación con las nuevas condiciones y se procede a aceptar, aparece el mensaje "negotation sent" pero el estado de la negociación no se actualiza y allí queda.

El estado de la negociación no se completa para el broker queda con la siguiente pantalla:

![broker](https://cloud.githubusercontent.com/assets/2491042/16168090/fc63a284-34d4-11e6-946e-ed11b6a45ebb.png)

El estado de la negociación para el customer queda esperando respuesta a pesar de ya haberla aceptado:

![customer](https://cloud.githubusercontent.com/assets/2491042/16168113/4b611b82-34d5-11e6-987d-4064a2479996.png)

![sent](https://cloud.githubusercontent.com/assets/2491042/16168126/7739cd8a-34d5-11e6-8690-223a8bd3d9f1.png)

Verisión 17.4

![phone blu](https://cloud.githubusercontent.com/assets/2491042/16168130/cc1a5fd6-34d5-11e6-9eeb-8dd76986c74f.png)

**Comment by LilianFlores** [comment]
Es correcto. Yo acepto la negociación luego de que él envía para confirmar, se muestra "Negotiation sent" pero sigue como si no la hubiese aceptado. Esto no cambia aún cuando actualizo, ni siquiera cuando salgo y vuelvo a entrar. Varias veces acepté y siempre me salió el mismo mensaje sin ningún cambio.

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16168333/63819690-34cd-11e6-94e5-fca0a14a5a04.png)

**Comment by sanro14** [comment]
Chicos podrían subir el archivo logcat.txt que esta en la carpeta genymotion/employed/ por favor .. recuerden anexar este archivo a sus misses

**Comment by MaviDavsa** [comment]
@nelsonalfo @abicelis

**Comment by yolandayancel** [comment]
Prueba 21-06-2016
Caso 576 CBP V 18
Nexus 4 5.0.0
La negociación se concretó, 
![caso 1](https://cloud.githubusercontent.com/assets/17283358/16233825/75140d24-3799-11e6-8f9c-6a30f7cf585b.png)

pero las horas pudimos observar que no se actualizan.
No tomamos captura pero dejo el logcat para que puedar revisar lo ocurrido.
[logcat caso horas customer nego..txt](https://github.com/Fermat-ORG/beta-testing-program/files/325857/logcat.caso.horas.customer.nego.txt)

**Comment by yalayn** [comment]
Porfa si a alguien le ocurre de nuevo este error, adjunte el **log** para poder revisarlo mejor el caso.

**Comment by IsbetVR** [comment]
@yalayn  
En la versión v18.3 de CBP sucedió lo mismo. Quedó en el Customer la negociación a pesar que le da al SEND y confirma las claúsulas en cada proceso. (Adjunto el logcat.txt) 3 veces probé enviar y se queda ahí.

#### Pantalla 1

![screenshot_79](https://cloud.githubusercontent.com/assets/19142276/16385533/39dc8ce2-3c5b-11e6-9ad3-51c028d53d64.jpg)

#### Pantalla 2

![screenshot_80](https://cloud.githubusercontent.com/assets/19142276/16385550/4a92a6ac-3c5b-11e6-9e38-d419d81991ca.jpg)

- [x] Emulador
- Google Nexus 4
- Versión de android: 5.0.
- 320 dpi
- API 21 768x1280


#### Archivo Logcat.txt

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/335172/logcat.txt)

**Comment by yalayn** [comment]
Buenas tardes @MaviDavsa, @sanro14 , @IsbetVR, @yolandayancel,  en la versión 18.5 de la app. Se corrigió e error. Por favor confirmar si esta funcionando correctamente. Gracias :)

**Comment by abicelis** [comment]
@IsbetVR @yolandayancel @MaviDavsa @sanro14 @LilianFlores @kmiloxvii 
que ha pasado con este issue que @yalayn resolvio?

**Comment by yolandayancel** [comment]
Prueba 01-07-16
Caso 576 CBP 18.8
Nexus 4 5.0.0
En la prueba de hoy no se ha podido establecer connctions con los brokers.
![576 1](https://cloud.githubusercontent.com/assets/17283358/16532396/82dfff08-3f9b-11e6-91c9-ffb5253a9824.png)
[logcat576-1.txt](https://github.com/Fermat-ORG/beta-testing-program/files/344048/logcat576-1.txt)

Nexus 5 5.0.0
En la prueba de hoy se estableció conecctions pero la negociacion no se puede entrar.
![576-2](https://cloud.githubusercontent.com/assets/17283358/16532609/cac27bd8-3f9c-11e6-8978-f509222f2736.png)
[logcat576-2.txt](https://github.com/Fermat-ORG/beta-testing-program/files/344061/logcat576-2.txt)
