### ISSUE TITLE
BITCOIN WALLET-Request Sent-Sin información la ficha

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#577]
### Nombre de la Aplicación Bitcoin Wallet

-----

##### Reporte de error:

* en request en la sección de sent me sale como si me hubiese llegado un request, pero no sale quien fue, esto sucede cada vez que envio un request.

![screenshot_2016-06-20-09-23-44](https://cloud.githubusercontent.com/assets/5313326/16197480/06f783ac-36cc-11e6-904d-6b61558215a3.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16197468/f80e1324-36cb-11e6-92de-20066042e913.png)

**Comment by arosiopr** [comment]
@mavidavsa

**Comment by yolandayancel** [comment]
@nattyco 
Prueba 19-06-16
Caso 577 CBP V 17.4
Nexus 5 5.0.0
Ocurre lo mismo que reportaron: se envían los reques pero no aparece ni el nombre, ni el monto enviado.
![caso 577](https://cloud.githubusercontent.com/assets/17283358/16198556/223952b8-36d0-11e6-9b49-298f829af31b.png)
[logcat 577.txt](https://github.com/Fermat-ORG/beta-testing-program/files/323667/logcat.577.txt)

**Comment by MaviDavsa** [comment]
@nattyco bella esta es en la version 17.4 de la CBP

**Comment by nattyco** [comment]
@MaviDavsa  @nelsonalfo corregi esto en la nueva version de CCP

**Comment by nelsonalfo** [comment]
Lo ultimo de @nattyco viene en la versión 18 de la apk, que si no la publicamos hoy, mañana en la mañana lo hacemos

**Comment by arosiopr** [comment]
@MaviDavsa corregido. Se puede cerrar
