### ISSUE TITLE
Bitcoin Wallet- Send to Contact: Mensaje de exception.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#578]
#### Nombre pantalla

Send to Contact

### Nombre de la Aplicación 

Bitcoin Wallet 
-----

##### Reporte de error: 

En la Bitcoin Wallet al seleccionar un contacto para hacerle un envío de btc inmediatamente al abrir esa pantalla aparece el siguiente mensaje de exception:

![20-6-16](https://cloud.githubusercontent.com/assets/19883115/16197106/91292bf4-36ca-11e6-96ff-4726d139c952.png)
  
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16197170/d2eac804-36ca-11e6-8c4c-cf48e65f0d4a.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/323571/logcat.txt)

**Comment by GeronimoVierma** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nattyco Esta en la Version de la CBP la 17.4

**Comment by nattyco** [comment]
@MaviDavsa  @nelsonalfo corregi esto en la nueva version de CCP

**Comment by nelsonalfo** [comment]
Lo ultimo de @nattyco viene en la versión 18 de la apk, que si no la publicamos hoy, mañana en la mañana lo hacemos

**Comment by abicelis** [comment]
@MaviDavsa Mavi, el milestone de este issue dice que es de la banking wllet

**Comment by MaviDavsa** [comment]
@abicelis Lo sientoooo Ale! :(

**Comment by GeronimoVierma** [comment]
En la version 18.3 ya no se presenta el error. Cerrar caso. @MaviDavsa
