### ISSUE TITLE
CBP-BANKING WALLET-Add Account-restante de caracteres sale uno debajo del otro

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#579]
### Nombre de la Aplicación Banking Wallet

-----

##### Reporte de error: 

   *Al Ingresar a añadir una cuenta en la baking wallet, se puede observar a la derecha que sale un numero debajo del otro en la parte donde se muestra la camtidad de caracteres que quedan, ademas no deja correr hacia abajo para seleccionar la imagen

![screenshot_2016-06-20-09-50-52](https://cloud.githubusercontent.com/assets/5313326/16199820/e76c57a2-36d4-11e6-89db-31e9bdc9aa0d.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16199816/e2aad7e8-36d4-11e6-80a8-6c25d957d150.png)

**Comment by arosiopr** [comment]
versión 17.4 de la CBP @MaviDavsa @abicelis

**Comment by abicelis** [comment]
Listo @arosiopr en la version 17.5 estara el fix, avisame si hay algo que haya quedado mal plz

**Comment by arosiopr** [comment]
@abicelis la tengo presente. pero no la he podido probar porque no sale para agregar cuenta :s

**Comment by abicelis** [comment]
@arosiopr Si, disculpa. Prueba la version 18.1 ahora que salga plz!

**Comment by maydiamc** [comment]
en la version 18.1 esto se soluciono @arosiopr @abicelis

**Comment by Gabymorillo** [comment]
Solucionado

**Comment by arosiopr** [comment]
@MaviDavsa Solucionado. Se puede cerrar.
