### ISSUE TITLE
Bit Coin Wallet_Menu Contacts

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#58]
### Template issue error report

Bit Coin Wallet

#### Nombre pantalla

Contacts

##### Reporte de error: 

   *En la pantalla Contacts, el Menú desplegable, el texto tropieza o se mezcla con el texto de abajo en este caso los contactos, lo que hace que no sea legible, y al desplegar el menú principal, el menú de Contacts no se repliega o retrocede sino que queda encima haciendo difícil la lectura e incomodo el uso del menú.

* Marca: ZTE
* Modelo: Apex 2
* Version de Android: 4.4.2

![screenshot_2016-03-04-11-17-17](https://cloud.githubusercontent.com/assets/17273349/13532389/74c8d288-e1fd-11e5-8923-d6f5d449e354.png)

![screenshot_2016-03-04-11-17-34](https://cloud.githubusercontent.com/assets/17273349/13532392/77797ac8-e1fd-11e5-86f8-2438c1e62550.png)

**Comment by maydiamc** [comment]
en mi telefono se genera el mismo error

Modelo del telefono: Samsung Galaxy Mini S4
Numero de Version: Android 4.4.2 Kit Kat

**Comment by nattyco** [comment]
@maydiamc verificar como se ve en la nueva version de la app

**Comment by adryx83** [comment]
Esto continua en la versión que estoy probando en este momento.

**Comment by MaviDavsa** [comment]
@nattyco Solucionado!
