### ISSUE TITLE
Communities - No muestra el botón para hacer conexión cuando el nombre es muy largo

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#580]
### TKY-ART (versión v1u3)

-----

##### Reporte de error: 

   *El error sucede cuando a través de las "Communities - Artist Community" quiero establecer conexión con un "Artist" y tiene el nombre muy extenso (Pantalla 1), al darle "Connect", me muestra el "Connection Request" (Pantalla 2), pero no me deja bajar con el scroll para ver el botón de "YES", por tanto no puedo enviar la solicitud de conexión.
   
------

#### Pantalla 1
![screenshot_9](https://cloud.githubusercontent.com/assets/19142276/16200874/19bed880-36dd-11e6-8427-5551797fa534.jpg)

#### Pantalla 2
![screenshot_10](https://cloud.githubusercontent.com/assets/19142276/16200879/20b4eddc-36dd-11e6-938b-d838312960b4.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión Android: 5.1.0
- 320 dpi
- API 22 768x1280

![google nexus 4 - 5 1 0](https://cloud.githubusercontent.com/assets/19142276/16200908/43e46814-36dd-11e6-8136-ecb63027917e.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@darkestpriest

**Comment by darkestpriest** [comment]
@juanaso ¿puedes encargarte de esto?

**Comment by lostwood** [comment]
ya este se arreglo con la version 1v10

**Comment by IsbetVR** [comment]
En la versión v1u11 al estar limitado la cantidad de caracteres para el alias, no hay errores para enviar la conexión.
Solucionado.
