### ISSUE TITLE
CBP- Broker identity- error al modificar nombre del perfil.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#581]
#### Nombre pantalla

Edit Identity

### Nombre de la Aplicación 

CBP V 17.4
-----

##### Reporte de error: 
Estando en Edit Identity tratando de modificar el nombre de mi perfil ocurre que al cambiar el nombre y luego seleccionar UPDATE me sale el mensaje de la imagen, al seleccionar Wait desaparece el mensaje y en un par de segundos vuelve a aparecer, así que  debo seleccionar OK para cerrar la aplicación.

![issue](https://cloud.githubusercontent.com/assets/19883115/16201098/e73d6faa-36d9-11e6-9cc4-1b358ca81f72.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16201161/1f5a3a26-36da-11e6-8adc-3fc255876631.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/323806/logcat.txt)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by nelsonalfo** [comment]
Por lo que puedo ver del **logcat.txt** fue un problema con tu camara:

```
06-20 11:42:58.767 W/MessageQueue( 2541): java.lang.IllegalStateException: Handler (android.os.Handler) {135d4b60} sending message to a Handler on a dead thread

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.os.Handler.enqueueMessage(Handler.java:631)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.os.Handler.sendMessageAtFrontOfQueue(Handler.java:623)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.hardware.camera2.legacy.RequestThreadManager.quit(RequestThreadManager.java:941)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.hardware.camera2.legacy.LegacyCameraDevice.close(LegacyCameraDevice.java:444)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.hardware.camera2.legacy.CameraDeviceUserShim.disconnect(CameraDeviceUserShim.java:365)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at java.lang.reflect.Method.invoke(Native Method)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at java.lang.reflect.Method.invoke(Method.java:372)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:80)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at $Proxy1.disconnect(Unknown Source)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.hardware.camera2.impl.CameraDeviceImpl.close(CameraDeviceImpl.java:758)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at android.hardware.camera2.impl.CameraDeviceImpl.finalize(CameraDeviceImpl.java:781)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)

06-20 11:42:58.767 W/MessageQueue( 2541): 	at java.lang.Thread.run(Thread.java:818)
```

Fijate las lineas que dicen **android.hardware.camera2.legacy.RequestThreadManager** 

Por favor vuelve a probar con exactamente los mismos pasos para ver si vuelve a suceder el error

**Comment by GeronimoVierma** [comment]
He estado probando con la CBP-V18 y me sale el mismo mensaje al pulsar Update (quiero aclarar que es solo cuando modifico el nombre del perfil sin modificar nada mas):

![last2](https://cloud.githubusercontent.com/assets/19883115/16237020/56b00562-37a4-11e6-9fc1-6b5b1d533940.png)

![issues](https://cloud.githubusercontent.com/assets/19883115/16237032/667141a0-37a4-11e6-81b6-eb2be794687a.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/326029/logcat.txt)

**Comment by abicelis** [comment]
@GeronimoVierma en el ultimo logcat no sale ningun error
Puedes intentar replicar esto con otra copa del mismo emulador?

(En Genymotion, dale a + y anade otra copia del mismo emulador Nexus 5 5.0.0 API 21 y prueba)

Yo usando el mismo emulador no logro replicar el problema, puedo editar nombres sin problema.

**Comment by GeronimoVierma** [comment]
Seguí los pasos indicados y añadí una copia  del Nexus 5 5.0.0 API 21, al entrar y modificar el nombre del perfil y luego pulsar Update lo cambio sin problemas, inmediatamente lo volví a modificar al nombre que tenia antes y al darle Update volvió a ocurrir el error:

![23-06](https://cloud.githubusercontent.com/assets/19883115/16305299/ff5a98ba-3922-11e6-95db-ec5ced4f6c0a.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/330079/logcat.txt)

**Comment by GeronimoVierma** [comment]
En la versión 18.4 no me aparece el error.
