### ISSUE TITLE
CBP- Banking Wallet- Bank Wallet no tiene un botón para configurar cuenta

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#582]
#### Nombre pantalla

Bank Wallet

### Nombre de la Aplicación 
CBP V 18
21-06-16

##### Reporte de error: 

   *Estando en la Bank Wallet no permite crear cuentas,  no aparece el signo más para para registrar una.
![no tiene para configurar banco](https://cloud.githubusercontent.com/assets/17283358/16230820/2b70cd62-378d-11e6-8fc2-c40a652c5b86.png)
[logcat no cong. banco.txt](https://github.com/Fermat-ORG/beta-testing-program/files/325644/logcat.no.cong.banco.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![nexus 4 5 0 0](https://cloud.githubusercontent.com/assets/17283358/16230844/457fd40a-378d-11e6-985b-3e83fc4c69c0.png)

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by abicelis** [comment]
@yolandayancel @MaviDavsa en la version 18.1 esta este fix!

**Comment by maydiamc** [comment]
en la version 18.1 este caso esta solucionado @yolandayancel @abicelis

**Comment by Gabymorillo** [comment]
En la versión 18.1 ya no presenta este error.

**Comment by yolandayancel** [comment]
Prueba 24-06-2016
Caso      CBP V 18.2
Nexus 4 5.0.0
En este emulador, ya aparece el botón de (+ ) para configurar las cuentas. CERRAR EL CASO
![caso 582](https://cloud.githubusercontent.com/assets/17283358/16350356/10812d56-3a28-11e6-9047-3594c9fcbd97.png)

**Comment by yolandayancel** [comment]
Caso 582 (Closed)  

Prueba 04-08-2016
Caso 582 CBP V 21.4 
Sony Xperia  4.1.1 Api 16 320dpi
Logcat:
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/402724/logcat.txt)

En este emulador,Ocurrió lo reportado en CBP V 18.2     Reabrir..
![screenshot_17](https://cloud.githubusercontent.com/assets/17283358/17418412/70474ff0-5a66-11e6-97ae-3c1978eb4a94.png)
