### ISSUE TITLE
Communities - Fan Community - Espaciado entre user

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#585]
#### Nombre pantalla

Fan User

### Nombre de la Aplicación 

TKY-ART Versión 4.
-----

##### Reporte de error: 

En la pantalla de Fan User (Imagen 1) el borde de la imagen no se encuentra separado de las lineas divisoras, en mi opinión debería verse como esta en la pantalla Fermat Music Player (Imagen 2) .
------

![screenshot_18](https://cloud.githubusercontent.com/assets/5313335/16234465/54a15dc4-379b-11e6-82c0-305cb5c2c1bc.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16234477/5c34493e-379b-11e6-9e29-991d4fb2c54e.png)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/16234716/0b27e7f2-379c-11e6-979b-d20ecee641ae.png)

**Comment by MaviDavsa** [comment]
@darkestpriest

**Comment by darkestpriest** [comment]
@lostwood por favor, chequea eso, por favor.

**Comment by lostwood** [comment]
@Hernandezsmanu ya se solvento lo que comentas puedes probar con la nueva version v1u5, que esta en el canal del beta testing

**Comment by Hernandezsmanu** [comment]
Solucionado. Por favor cerrar.
