### ISSUE TITLE
Communities - Fan Community - Borde de imagen

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#586]
#### Nombre pantalla

Fan User - Profile

### Nombre de la Aplicación 

TKY-ART Versión 4
-----

##### Reporte de error: 

   En la pantalla de Fan user muestra la imagen con un borde de color gris (Imagen 1) y al entrar al perfil de esa persona muestra el borde de colores (Imagen 2), debería manejarse un mismo estilo para ambos casos en mi opinión debería manejarse el de color en ambas partes.
------

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16235000/0d79bc0a-379d-11e6-899d-ba24530c8911.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/16235007/108c44c6-379d-11e6-9def-276e1dfa2a15.png)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/16235021/197c2c86-379d-11e6-9cd6-ec9d262a9c23.png)

**Comment by MaviDavsa** [comment]
@Hernandezsmanu

**Comment by darkestpriest** [comment]
Saludos @Hernandezsmanu esto no es un issue, es el diseño de UX entregado por el equipo de diseñadores.

**Comment by MaviDavsa** [comment]
@darkestpriest Ya aclarado el tema, quitamos el level de error gráfico, pero te dejo el de expericia de usuario, porque visualmente para el usuario tiene más armonía que todo esté en una misma combinación de colores...

**Comment by Hernandezsmanu** [comment]
En la versión 5 quitaron el borde negro, pero si de detalla quedaron 3 puntos negros al rededor de la foto y corta la imagen un poco en la parte inferior.

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16268353/ec89b82c-3857-11e6-8a9e-7b2dfe6f5fb0.png)

**Comment by darkestpriest** [comment]
Saludos @MaviDavsa  una pregunta, ¿los dieñadores no deberían ser mencionados en estos issues, solo trabajamos con los diseños que ellos nos proporcionan y ellos son los que saben de UX, nosotros de programar lo que nos indican. Si nos dicen que las pantallas son del color #AAFF01 es amén para nosotros. Ellos deberían también estar acá para que resuelvan este tipo de detalle.

**Comment by darkestpriest** [comment]
@Hernandezsmanu Debes indicarnos más información de las condiciones en la cual hiciste la prueba, tal como lo indica @IsbetVR, por ejemplo:

    Emulador
    Google Nexus 4
    Versión de Android: 5.0.0
    320 dpi
    API 21 768x1280

Así se puede replicar y poder realizar ajustes. Gracias
@lostwood, por favor, cuando @Hernandezsmanu nos de la información, revisa esto por favor

**Comment by Hernandezsmanu** [comment]
Si me me falto subir esa capture, aquí esta la información:

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16269082/b1e59ae4-385a-11e6-8e71-6eaabf02cd08.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/5313335/16269085/b59dc210-385a-11e6-811a-d9b6b9cd49f0.png)

**Comment by darkestpriest** [comment]
@Hernandezsmanu incluye la información del DPI, por favor. Gracias.

**Comment by Hernandezsmanu** [comment]
Ahí te lo incluí en la otra imagen. De todas manereas es: 480 dpi

**Comment by lostwood** [comment]
Ya se corrigio lo que comentaron en la version V1u6, esta publicada en el canal,  pueden revisar y cerrar gracias.

**Comment by IsbetVR** [comment]
Este error está corregido en la versión v1u10
