### ISSUE TITLE
Bitcoin Wallet- cierre de la aplicacion al ingresar por primera vez y seleccionar un perfil predeterminado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#587]
#### Nombre pantalla 
Home

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *Al ingresar a la bitcoin wallet por primera vez, sin crear perfil de wallet user primero, al ingresar y seleccionar el perfil predeterminado Jane Doe o Jon Doe, inmediatamente se cierra y vuelve al Destock de fermat y al volver a ingresar ya se puede usar la aplicacion.

 CBP version 18
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16235151/a3701ef2-379d-11e6-83ea-00e25ef72a5a.png)

**Comment by maydiamc** [comment]
@nattyco Version 18 de CBP

**Comment by AdryCanonico** [comment]
@maydiamc @nattyco en la versión 18 CBP persiste el error

**Comment by dorzar1989** [comment]
En la Version 18.8 CBP persiste el error @maydiamc @nattyco

**Comment by nattyco** [comment]
@dorzar1989 que version de android tenes?

**Comment by maydiamc** [comment]
persiste el error en la version 18.8de CBP

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16530478/1cf2844e-3f92-11e6-83e5-720341b966dd.png)

**Comment by dorzar1989** [comment]
Version de Android @nattyco 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16531035/a9febc4e-3f98-11e6-8ed3-3d1847ebb5d4.png)

**Comment by maydiamc** [comment]
esto sigue sucediendo en la version 19.2 de CBP

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16567951/6ca929b8-41f2-11e6-9ce6-9e96090321f8.png)

**Comment by maydiamc** [comment]
en la vrsion 19.8 de CBP este problema se soluciono

**Comment by maydiamc** [comment]
reabrir este caso porque se esta presentando el problema en la 20.5 de cbp

**Comment by sanro14** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc verificar este caso nuevamente

**Comment by RAYMALDONADO** [comment]
En la version 20.7 CBP no siguió este problema. 
emulador
google nexus 4 -4.4.4
version android 4.44

**Comment by IsbetVR** [comment]
Closed #587
