### ISSUE TITLE
CBP-  Crypto customer-Negotiation Details: borrada  la localización

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#589]
#### Nombre pantalla

Negotiation Details
### Nombre de la Aplicación 
CBP V 18
21-06-16

##### Reporte de error: 

   *Realizando la segunda negociación, en el punto el (6) pide nuevamente que agregue la localización. Nuevamente en setting agregue la localización.Volví a la negociación y apareció la localización
![caso localizacion](https://cloud.githubusercontent.com/assets/17283358/16235241/fb8d2f44-379d-11e6-949d-33daf62c9071.png)
![caso localizacion 1](https://cloud.githubusercontent.com/assets/17283358/16235318/3ba8142c-379e-11e6-9f78-41d9abea057a.png)
[logcat localización.txt](https://github.com/Fermat-ORG/beta-testing-program/files/325951/logcat.localizacion.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![nexus 4 5 0 0](https://cloud.githubusercontent.com/assets/17283358/16235501/ead6fbde-379e-11e6-92e4-1ed27f5e625d.png)

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo @Yayotron

**Comment by abicelis** [comment]
@yolandayancel @MaviDavsa Fixeado en la version 18.1! Revisen y me dicen!

**Comment by Gabymorillo** [comment]
Solucionado en mi equipo

**Comment by abicelis** [comment]
Plz cerrar este issue

**Comment by yolandayancel** [comment]
Prueba 30-06-16
Caso 589 CBP 18.4
Nexus 4 5.0.0
Solucionado, no borra la localización.Cerrar el caso.
