### ISSUE TITLE
CBP-Community- Cryto Broker user: fondo en blanco

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#591]
#### Nombre pantalla
Cryto Broker user

### Nombre de la Aplicación 
CBP V18

-----

##### Reporte de error: 

   *Al ingresar a la crypto broker user se ve el fondo en blanco. Salgo e ingreso y sigue igual.
![community blanco](https://cloud.githubusercontent.com/assets/17283358/16236330/d1c50804-37a1-11e6-8049-7370dacbf132.png)

[logcat community.txt](https://github.com/Fermat-ORG/beta-testing-program/files/325996/logcat.community.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![nexus 4 5 0 0](https://cloud.githubusercontent.com/assets/17283358/16236364/ee22a5f6-37a1-11e6-8bfb-15fe9993954b.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  esta community no es de mi rama solo la de las wallets. consultar a Nelsoln

**Comment by yolandayancel** [comment]
Buenos días
Como es el nuevo diseño de la community, cerrar este caso

**Comment by abicelis** [comment]
Si @yolandayancel, @MaviDavsa cierra este caso plz

**Comment by yolandayancel** [comment]
Buenas Alejandro
Deje el comentario para que lo cierren en la mañana
