### ISSUE TITLE
CCP - Error en Communities

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#592]
#### Nombre Pantalla:

Conections de la Crypto Wallet Users

### Nombre de la Aplicación 

CBP Version 18
-----

##### Reporte de error: 

Al momento de entrar en la Pantalla de Connections de la Crypto Wallet Users me sale este error.
   
------

![screenshot_26](https://cloud.githubusercontent.com/assets/19670319/16235467/cfc98a50-379e-11e6-9ea0-4101c934e920.png)

Hora: 9:33am  

LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/325971/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/16235558/23794de8-379f-11e6-9ac4-eb2cd8ba184c.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo

**Comment by dorzar1989** [comment]
En la Version 18.3 de la CBP persiste este error, de vez en cuando sale,no es en todo momento.

![screenshot_61](https://cloud.githubusercontent.com/assets/19670319/16385206/e845645e-3c59-11e6-9091-99eacce43c1d.png)

Emulador
Nexus 4
Android Version 5.0

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/16385230/0177fa22-3c5a-11e6-9955-004bd0bf11f3.png)


Ojo. No me deja montar el archivo .txt por el tamaño que tiene.

**Comment by MaviDavsa** [comment]
@nattyco  chequea esto pls!

**Comment by dorzar1989** [comment]
Cerrarlo, ya no me sale este error
