### ISSUE TITLE
Bitcoin Wallet - Solicitar Addres de Contacto

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#593]
#### Nombre Pantalla

Bitcoin Wallet - Contact - Contact Detail

### Nombre De La Aplicación 

CBP Version 18
-----

##### Reporte De Error: 

Luego de realizada la conexión con el usuario "Natty S", me mantuvo en espera por mas de una hora por la actualización de la dirección (Address), a pesar de que yo hacia Click en el botón de actualizar y el me indicara que esperara al menos 2 minutos, pasaba el tiempo y nunca aparecio ningún tipo de dirección, debido a este error no logre hacer una transacción de Bitcoins con el usuario anteriormente mencionado. (Cada imagen Tiene su Hora)

------

![screenshot_30](https://cloud.githubusercontent.com/assets/19670319/16241486/b6dc6850-37b7-11e6-8d18-0b5b0846ed26.png)

![screenshot_31](https://cloud.githubusercontent.com/assets/19670319/16241496/bcbc5c44-37b7-11e6-88bb-1c2f9980f6be.png)

- Hora:

 Aproximadamente desde las 11:15am hasta las 12:35pm

- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/326294/logcat.txt)

#### Dispositivo Desde Donde Se Realizo La Prueba

Movil: Nexus 4
Android Version: 5.0

![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/16241511/d2f54e76-37b7-11e6-835a-57efdcb02431.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@MaviDavsa

**Comment by nattyco** [comment]
@MaviDavsa  ese usuario lo cree yo de testing en mi celular y puede que no estaba conectada, porque estoy haciendo pruebas, creo y borro identidades, limiten sus pruebas solo a las identidades de su grupo de testing.

**Comment by MaviDavsa** [comment]
Listo bella! Cerrado!
