### ISSUE TITLE
CBP - BANKING - NO SE PUEDE AGREGAR CUENTAS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#594]
#### Nombre pantalla

HOME

### Nombre de la Aplicación 

CBP - BANKING
-----

##### Reporte de error: 

   *No se puede agregar cuentas para hacer un deposito desde la Banking, solo se puede crear una cuenta desde la Crypto Broker y se debe acceder otra vez a laBbanking para poder hacer depósitos en la cuenta configurada en la Crypto Broker.

![screenshot_2016-06-21-18-44-58](https://cloud.githubusercontent.com/assets/18584168/16248984/afd9d784-37dc-11e6-93d1-c9457d374ac8.png)

[alogcat.2016-06-21-18-46-33-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/326740/alogcat.2016-06-21-18-46-33-0430.txt)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16248892/ff851330-37db-11e6-89ff-7f59f6ce476c.png)

**Comment by Gabymorillo** [comment]
No permite crear cuentas en la Banking

![screenshot_2016-06-21-19-06-47](https://cloud.githubusercontent.com/assets/17262077/16249608/f71d5cf2-37e0-11e6-89d0-3cd860a26aac.png)

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16249612/0000bbfc-37e1-11e6-9552-464c404b982f.png)

**Comment by RubenSem** [comment]
No deja crear cuenta desde la banking.
![screenshot_2](https://cloud.githubusercontent.com/assets/19676223/16267848/a7d958a6-3855-11e6-81e0-2b6bb042b6b1.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/19676223/16267854/b1ef548a-3855-11e6-910f-0bbd9f48dcdb.jpg)

**Comment by abicelis** [comment]
Issue duplicado, arreglado en: https://github.com/Fermat-ORG/beta-testing-program/issues/582#issuecomment-227581555
