### ISSUE TITLE
CBP- CRYPTO CUSTOMER - PIERDE CONFIGURACION EN LA LOCALIZACION AL MOMENTO DE CERRAR LA CBP

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#595]
### Nombre de la Aplicación 

CBP
-----

##### Reporte de error: 

En la versión 18 de la CBP, al establecer las negociaciones pide confirmar la localización, dicha localización ya habia sido configurada con anticipación. Debo ir a settings y colocarla de nuevo. 
Esto sucede al salir y entrar de nuevo a la aplicación.  
   

![screenshot_2016-06-21-21-19-38](https://cloud.githubusercontent.com/assets/17262077/16251901/bd25cdd2-37f3-11e6-9ea7-4d5b70cc9ed0.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16251905/c4fc0fda-37f3-11e6-8782-9e7f57e42ffe.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo
