### ISSUE TITLE
CBP- CRYPTO CUSTOMER - PIERDE CONFIGURACION EN LA BANK AL MOMENTO DE CERRAR LA CBP

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#596]
#### Nombre pantalla

Negotiations - Bank Account List 

### Nombre de la Aplicación 

CBP
-----

##### Reporte de error: 

En la versión 18  de la CBP, al establecer las negociaciones pide confirmar la Bank, dicha localización ya habia sido configurada con anticipación. Debo ir a settings y colocarla de nuevo. 
Esto sucede al salir y entrar de nuevo a la aplicación.
   
![screenshot_2016-06-21-20-28-11](https://cloud.githubusercontent.com/assets/17262077/16252066/14a62e02-37f5-11e6-9a69-75d6ff308965.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16252074/2173309e-37f5-11e6-9bb5-6fe7ca92ffd0.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by MaviDavsa** [comment]
@nelsonalfo Nosotras entendemos que los customer no tienen relacion directa con la Banking... Pero en este caso es que la cuenta que se hace al inicio no la guarda! Entonces allì es donde radica el problema por lo que veo!

**Comment by abicelis** [comment]
@Gabymorillo @AdryCanonico @MaviDavsa En la version 18.1 corregido el error, prueben a ver si les ocurre plz!

**Comment by MaviDavsa** [comment]
@abicelis las comunidades no nos permitieron llegar esta allí esperemos que en la tarde si

**Comment by Gabymorillo** [comment]
En la versión 18.4 está solucionado.

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP, este error se presenta en mi emulador, después de que se cierra al responder una negociación, cuando vuelvo entrar las cuentas desaparecieron, (no pude tomar captur de las primeras cuentas creadas). De nuevo al volver entrar por reinicio del emulador aparecen las viejas cuentas y las nuevas.

![bank](https://cloud.githubusercontent.com/assets/19353722/16933648/7b4bebf0-4d1d-11e6-955d-65342d37eccd.png)

![bank2](https://cloud.githubusercontent.com/assets/19353722/16933657/96439c50-4d1d-11e6-93f6-da8320a9aaca.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16933659/9aaced82-4d1d-11e6-87ab-6977e9c9c5a7.png)
