### ISSUE TITLE
CBP - Crypto Customer

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#597]
#### Nombre pantalla

Crypto Customer

### Nombre de la Aplicación 

CBP Version 18
-----

##### Reporte de error: 

   *Al momento de entrar en la Crypto Customer Me aparece la pantalla para crear la Cuenta y los Providers por alrededor de 3 segundos y me envía a la pantalla de mi cuenta ya creada donde ya tengo una negociación. Me sucede cada vez que quiero entrar a la Crypto Customer. (Cada imagen tiene su hora y fecha exacta del momento en que ocurrió el error)
   
![screenshot_32](https://cloud.githubusercontent.com/assets/19670319/16268004/567f705c-3856-11e6-8b36-3485207e3bd4.png)

![screenshot_33](https://cloud.githubusercontent.com/assets/19670319/16268008/5b329dcc-3856-11e6-9305-a5720e2b83c2.png)

------

- Hora:

 8:33am

- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/327930/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

Movil: Nexus 4
Android Version: 5.0

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/16267890/d10fbe0e-3855-11e6-928d-76f258dd3aac.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@MaviDavsa @sanro14

**Comment by maydiamc** [comment]
en mi dispositivo sucede lo mismo @nelsonalfo 

![screenshot_2016-06-22-08-54-52](https://cloud.githubusercontent.com/assets/17274154/16269864/f620120e-385d-11e6-9595-4fe19dc1f654.png)

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16269881/070babe6-385e-11e6-885e-ef9178a3f9c6.png)

**Comment by abicelis** [comment]
@dorzar1989 @maydiamc Listo en la version 18.1

**Comment by maydiamc** [comment]
esto se soluciono en la version 18.1 @dorzar1989 @abicelis

**Comment by dorzar1989** [comment]
Probado en la version 18.3 de la CBP y no continua este error. Se Soluciono. Por facor cerrar el caso :D  @MaviDavsa  @abicelis
