### ISSUE TITLE
Communities - Fan Community - Me borró la información del perfil creado

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#598]
### TKY-ART (Versión v1u5)

-----

##### Reporte de error: 

   *El error sucedió cuando entro en la "Fan Community" con el perfil de fan (Entré a revisar una notificación de conexión), no me aparecieron los datos del perfil creado en el menú de la community (Pantalla 1), salí de la aplicación y volví a entrar a la "Fan Community" y ahí si me salieron los datos (Pantalla 2). (Esto me ha sucedido dos veces)
   
------
#### Pantalla 1

![screenshot_21](https://cloud.githubusercontent.com/assets/19142276/16268259/ab3567a0-385b-11e6-9d8b-6837006e9588.jpg)

#### Pantalla 2

![screenshot_22](https://cloud.githubusercontent.com/assets/19142276/16268264/b3fba96c-385b-11e6-9e4a-4ebc51f46f8d.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Android: 5.0.0
- 320 dpi 
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16268291/d04158c4-385b-11e6-8e7f-535b6e8b2e42.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@darkestpriest

**Comment by darkestpriest** [comment]
Slaudos, ya @juanaso va a estar revisando.

**Comment by darkestpriest** [comment]
@IsbetVR ¿podrías revisar si en la versión 1u6 también sucede? Gracias.

**Comment by juanaso** [comment]
@IsbetVR ¿podrías revisar si en la versión 1u6 también sucede? Gracias.

**Comment by juanaso** [comment]
en la versión v1u10

**Comment by IsbetVR** [comment]
Esto no ha vuelto a suceder. ;)
