### ISSUE TITLE
CBP-CRIPTO BROKER- BANK ACCOUNTS-NÚMEROS MONTADOS EN TEXTO

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#599]
### Template issue error report

Nombre pantalla

BANK ACCOUNT

### Nombre de la Aplicación 

CBP- CRIPTO BROKER

Reporte de error: 

PROBANDO LA APLICACIÓN DESDE MI MÓVIL, LUEGO DE CREAR LA CUENTA EN LA BANKING, AL REVISAR EN LA PANTALLA DE BANK ACCOUNT EN LA CRIPTO BROKER, SE MONTAN LOS NÚMEROS DE LA CUENTA  EL TEXTO DEL NOMBRE DEL BANCO. TAL Y COMO SE SEÑALA A CONTINUACIÓN;

![image](https://cloud.githubusercontent.com/assets/18740418/16268648/081aefd8-3859-11e6-9dff-3b3447cda431.png)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [x] Teléfono Físico

![image](https://cloud.githubusercontent.com/assets/18740418/16268717/389ef7d0-3859-11e6-8b3b-b4b727e69c1e.png)

**Comment by camilavaleria** [comment]
@MaviDavsa,@abicelis,@sanro14

**Comment by abicelis** [comment]
@camilavaleria @sanro14 @MaviDavsa Fixed en version 18.1!

**Comment by maydiamc** [comment]
en la version 18.1 se soluciono el error porque se modifico el formato @camilavaleria @abicelis

**Comment by camilavaleria** [comment]
solucionado el error!!
