### ISSUE TITLE
Bitcoin Wallet_experiencia del usuario_identity manager

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#60]
#### Nombre pantalla

-----

##### Identity Manager

- [x] Pantalla principal  

##### Reporte : 

  se recomienda que la aplicacion, al ingresar por primera vez, nos obligue a crear una cuenta personalizada, y no asignarnos una cuenta por defecto, ya que esto, para nuevos usuarios que desconocen la aplicacion se hace complicado, debido a que hace parecer que es un duplicado del mismo contacto y resulta que son diferentes contactos con el mismo nombre de usuario.
![screenshot_2016-03-04-11-50-57](https://cloud.githubusercontent.com/assets/17274154/13606038/7ef54486-e51c-11e5-9baa-31d1e18991bb.png)

![screenshot_2016-03-04-18-07-41](https://cloud.githubusercontent.com/assets/17274154/13606023/67f04d26-e51c-11e5-9739-8e6076898e3f.png)

   

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: Mini s4
* Version de Android: 4.4.2 kit kat

**Comment by nattyco** [comment]
@maydiamc  esos usuarios "actorintrauser" que te parecen son todos usuarios que aceptaste desde el community? que te enviaron solicitud de conexion y vos las aceptaste?

**Comment by maydiamc** [comment]
Claro ya todas las solicitudes las acepte, esa en particular fue la unica que se duplico

**Comment by nattyco** [comment]
@maydiamc ese "actorintrauser" son todas identidades distintas, no es que se duplico, sino que estuvieron haciendo pruebas en otras areas. No hay error en este caso.

**Comment by maydiamc** [comment]
@nattyco 
Se replanteo el titulo y el caso, como sugerencia para mejorar la experiencia del usuario

**Comment by MaviDavsa** [comment]
@nattyco  Solucionado bella!
