### ISSUE TITLE
Broker Wallet- No aparecen los contratos solicitados por los Custommer.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#601]
#### Nombre pantalla

Broker Wallet
### Nombre de la Aplicación 

Cripto Broker (CBP-V18)
-----

##### Reporte de error: 

   Estando como Broker recibo una notificación de negociación de un Custommer  y al dirigirme  hacia la Broker Wallet no me aparece ningún contrato solicitado:

![nego](https://cloud.githubusercontent.com/assets/19883115/16269320/998ac716-385b-11e6-8a8e-f9bf021f742a.png)

![nego2](https://cloud.githubusercontent.com/assets/19883115/16269333/a3f0f25c-385b-11e6-9adf-21699944c127.png)
 
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16269346/b151e104-385b-11e6-89c1-7c40cb42c66a.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/328046/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 22-06-2016
Caso 601 CBP 18
Nexus 4 5.0.0
En mi emulador soy customery le envié varias negociaciones
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/16269612/d1de14b4-385c-11e6-863f-77ca0d7bb77d.png)
, las cuales no recibi respuesta
[logcat Geronimo caso.txt](https://github.com/Fermat-ORG/beta-testing-program/files/328055/logcat.Geronimo.caso.txt)

**Comment by GeronimoVierma** [comment]
En la versión 19.2 CBP si he logrado ver y acceder a los contratos solicitados por los Customers y logre culminar un contrato de manera exitosa.

![333](https://cloud.githubusercontent.com/assets/19883115/16565771/7d753a4e-41dd-11e6-91c3-de6b2d8608b2.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16565779/85488d34-41dd-11e6-8811-aa02e2ee8d55.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346579/logcat.txt)
