### ISSUE TITLE
Bitcoin Wallet_ el boton de la community no funciona

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#602]
#### Nombre pantalla
Add fermat user

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *El boton de la community funciona en algunas ocasiones.
  CBP version 18

![screenshot_2016-06-22-09-49-25](https://cloud.githubusercontent.com/assets/17274154/16269794/a94fd6a8-385d-11e6-8f1c-08e4bd6fda0f.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16269689/2bba2f7c-385d-11e6-8ade-b306214e5938.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by maydiamc** [comment]
persiste el error en la version 18.3 de CBP @nattyco

**Comment by nattyco** [comment]
@MaviDavsa  verificar en que versiones de android ocurre esto, si es solo en el celular de Maydi

**Comment by arosiopr** [comment]
@MaviDavsa el boton funciona bien en la version 18.8 de cbp

**Comment by dorzar1989** [comment]
En la version 18.8 de la CBP se corrigio este error.
Probado en un Nexus 4 Version 5.0

@MaviDavsa @nattyco

**Comment by marielis-urbina** [comment]
En la versión 18.8 de la CBP no persiste el error
Probado en Samsung Galaxy S3- 4.2.2
@MaviDavsa @nattyco

**Comment by GeronimoVierma** [comment]
En la versión 18.8 el botón me funciono sin problemas:

![012](https://cloud.githubusercontent.com/assets/19883115/16525991/e475e00c-3f78-11e6-835e-897f15d2e144.png)

![011](https://cloud.githubusercontent.com/assets/19883115/16526005/eabdaff8-3f78-11e6-807a-7e4b7c343814.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16526071/42332f92-3f79-11e6-97ef-8baaaaf4bb43.png)

**Comment by dorzar1989** [comment]
Estuve probrando de nuevo en la version 18.8 de CBP y el boton no me funciona ahora.

**Comment by maydiamc** [comment]
en la version 18.8 si funciono el boton de la community 
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16531883/6001a7d2-3f98-11e6-8e57-9c86043ed3fe.png)

**Comment by maydiamc** [comment]
esto esta sucediendo en la 19.4 de CBP

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16588625/cd52ab9e-429d-11e6-93a6-64b7f6fd1f92.png)

**Comment by maydiamc** [comment]
solucionado en la version 19.5 de CBP
