### ISSUE TITLE
CBP - Customer Wallet - Contracts

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#603]
#### Nombre pantalla

Customer Wallet - Contracts

### Nombre de la Aplicación 

CBP Version 18
-----

##### Reporte de error: 

   *Cuando se realiza una negociación y se llega a crear el Contrato, llega una notificación avisandote que el Contrato ha Expirado, pero de igual manera se sigue trabajando para realizarlo; llegamos a la conclusión de que a pesar de que la Apk te avisa que el contrato fue Expirado se puede seguir tramitándolo hasta llegar a la realización total del mismo.
   
------

![screenshot_35](https://cloud.githubusercontent.com/assets/19670319/16270008/8172c068-385e-11e6-8081-a557343a031e.png)

![screenshot_37](https://cloud.githubusercontent.com/assets/19670319/16270014/8710f85a-385e-11e6-8e21-feef26edef78.png)

![screenshot_38](https://cloud.githubusercontent.com/assets/19670319/16270070/bc822040-385e-11e6-9951-6c8469307b91.png)

- Hora:

 Aproximadamente 8:40

- LogCat:
 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/328057/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

Movil: Nexus 4
Android Version: 5.0

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/16270077/c8842320-385e-11e6-9d64-17685ffd2160.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@MaviDavsa @nelsonalfo @sanro14

**Comment by sanro14** [comment]
Chicos lo que sudedió en resumen es lo siguiente, se estaba realizando la negociación y llego una notificación de expirado (aun no habia pasado ni estaba cerca la hora estipulada para el contrato) sin embargo, luego de un rato, apareción de nuevo el contrato y se procede a seguir los pasos para culminarlo.

**Comment by MaviDavsa** [comment]
@abicelis

**Comment by yalayn** [comment]
Buenas Tardes. la app emite un mensaje que indica que el contrato esta cerca de vencer es una advertencia preventiva antes de que se llegue realmente a la fecha y hora de vencimiento. Cuando se presenta aun se puede seguir trabajando sobre la negociación y el contrato. Tal vez fue esa la notificación que les apareció. De todos modos voy a revisar este caso.

**Comment by sanro14** [comment]
no @yalayn la notificación decia "contrat expired" ...

**Comment by yalayn** [comment]
Ok @sanro14 Gracias, Entonces voy a revisar eso.

**Comment by IsbetVR** [comment]
Versión 19.5 de CBP
@yalayn la notificación es sobre que está "próximo a vencer el contrato", no que se ha vencido. Luego de llegar esa notificación pude seguir con la negociación hasta concretarlo.

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/16597854/09a11484-42c9-11e6-8a2c-f26223a89ae9.jpg)

**Comment by yalayn** [comment]
Hola @isbetVR. Ok esa notificación aparece cuando está próximo a vencer el contrato. Es sólo una advertencia. Por eso permite seguir concretando el contrato.

**Comment by IsbetVR** [comment]
Hola @yalayn. Ok, entonces resuelto el caso si esa es la notificación que debe aparecer. ;)

**Comment by IsbetVR** [comment]
Closed #603

**Comment by yalayn** [comment]
Muchas gracias @isbetVR
