### ISSUE TITLE
Bitcoin Wallet_ el tamaño de las letras Notes es distinto

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#604]
#### Nombre pantalla
Send Request to contact y Sent to contact

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *En los formularios de send request to contact y send contact, en la casilla de Notes, al colocar cualquier cosa se visualiza que las letras son de diferentes tamaños.
CBP version 18

![screenshot_2016-06-22-09-55-37](https://cloud.githubusercontent.com/assets/17274154/16270236/70b335b8-385f-11e6-9094-87c73095ca5a.png)
![screenshot_2016-06-22-09-54-57](https://cloud.githubusercontent.com/assets/17274154/16270239/7464512e-385f-11e6-8195-d884156925ea.png)

   ------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16270226/67a77560-385f-11e6-9d88-8be627e61a2a.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by maydiamc** [comment]
se mantiene el error en la version de CBP 18.3 @nattyco

**Comment by arosiopr** [comment]
mejoro en la version CBP 18.8 @MaviDavsa 

![screenshot_34](https://cloud.githubusercontent.com/assets/5313326/16524833/89f0276e-3f73-11e6-910b-8bcaab0ebd96.png)

![screenshot_35](https://cloud.githubusercontent.com/assets/5313326/16524837/8ed4de78-3f73-11e6-893f-aa6bfee3bd3b.png)

**Comment by maydiamc** [comment]
en la version 18.8 mejoro pero una se ve en negrita y la otra no, ademas cuando no hay nada escrito en la casilla, en send request dice reason y en send to contact dice notes

![screenshot_5](https://cloud.githubusercontent.com/assets/17274154/16531811/fb620948-3f97-11e6-9f9b-b20c2bed2fb5.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/17274154/16531812/fd794264-3f97-11e6-8b9c-8e6dc0bd8498.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/16531828/0eb97544-3f98-11e6-8a09-1a246677f0ee.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/16531830/110f5af2-3f98-11e6-9bf5-7c0a84039610.png)

emulador 
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16531837/1855ca76-3f98-11e6-9c60-41b2f16e9829.png)

**Comment by nattyco** [comment]
@MaviDavsa  lo de reason es para el payment request y esta bien.

**Comment by maydiamc** [comment]
me parece que si se colocara en ambas reason estaria bien tambien y estaria mas estadarizado.! es mi opinion... pero el problema grafico en si es que una esta en negrita y la otra no

**Comment by nattyco** [comment]
@maydiamc  volver a verificar el caso

**Comment by maydiamc** [comment]
sigue en negrita uno si y otro no, en la version 19.4 de CBP

![screenshot_5](https://cloud.githubusercontent.com/assets/17274154/16588194/0fb2b706-429c-11e6-872d-343e8718c01c.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/17274154/16588196/1325c73e-429c-11e6-95f0-3dbfe3f978e8.png)

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16588206/1cb004e0-429c-11e6-9105-431bad88a555.png)

**Comment by maydiamc** [comment]
en la version 20.1 de cbp se soluciono esto en mi emulador

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16697186/7ec8ed64-4516-11e6-8d07-781577c99c46.png)

**Comment by sanro14** [comment]
Solucionado.
