### ISSUE TITLE
Community_no se ven los iconos de espera de conexion

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#605]
#### Nombre pantalla
Crypto Broker User

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   *al enviar notificacion de conexion a los usuarios de mi crypto broker user y salirme a la pantalla donde se ven los usuarios conectados, no se muestra en cada imagen de perfil (a los que le enviado conexion previamente) el icono superior de espera de aceptacion de solicitud (el muñequito con el relojito), solo se muestra el icono con el ganchito, que identifica a los contactos que han aceptado la solicitud.
   CBP version 18

![screenshot_2016-06-22-11-02-01](https://cloud.githubusercontent.com/assets/17274154/16272128/61171df2-3866-11e6-846b-d35a7b2deb96.png)
![screenshot_2016-06-22-11-01-15](https://cloud.githubusercontent.com/assets/17274154/16272130/63dc454e-3866-11e6-85d8-9f855230d0aa.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16272139/6d850da6-3866-11e6-8cac-cb1702538446.png)

**Comment by maydiamc** [comment]
@nattyco @MaviDavsa

**Comment by abicelis** [comment]
@maydiamc Este feature nunca estuvo planteado en nuestras communities en CBP..

Voy a estudiar a ver si es facil implementarlo, en cualquier caso escribire aca.

**Comment by yalayn** [comment]
Buenas tardes. @maydiamc Como dice @abicelis esta funcionalidad no estaba planteada en CBP. Pero voy a estar trabajando en implementar esta característica en la medida de lo posible :).
Saludos

**Comment by yalayn** [comment]
Buenas Tardes  @maydiamc, @MaviDavsa Se agrego un icono para indicar que esta pendiente la solicitud de conexión. Como se muestra en la imagen. Debería estar disponible para la próxima versión.
Saludos.
![captura de pantalla de 2016-06-24 13 22 22](https://cloud.githubusercontent.com/assets/4664287/16346171/c22c2196-3a0f-11e6-8253-565ad10c5e34.png)

**Comment by maydiamc** [comment]
@yalayn gracias x tomar mi recomendacion en cuenta en la version 18.3 de CBP.! cerrar este caso
