### ISSUE TITLE
Bitcoin Wallet - Error en fecha de transacciones desde la Crypto Broker

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#606]
### CBP Versión v18

-----

##### Reporte de error: 

   *Cuando tengo las Wallets configuradas en el Stock Management (Crypto Broker), al pasarle montos de la Bitcoin Wallet, tal como aparece reflejada en la Pantalla 1, al revisar la "Bitcoin Wallet", en la parte inferior "SENT", donde me dice que he realizado 3 transacciones, tiene mal la fecha (Pantalla 2).
   
------
#### Pantalla 1

![screenshot_48](https://cloud.githubusercontent.com/assets/19142276/16286923/7f3cc3e4-38ad-11e6-953d-693f81f59276.jpg)

#### Pantalla 2

![screenshot_49](https://cloud.githubusercontent.com/assets/19142276/16286925/8b66c96c-38ad-11e6-91fc-2f9cf6089a6f.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16286953/c9258540-38ad-11e6-83c9-e0fa5de76c8f.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @nattyco

**Comment by nattyco** [comment]
@nelsonalfo  hay que pasarle la fecha del dia cuando manda a insertar la transaccion en la basic wallet.

**Comment by GeronimoVierma** [comment]
En la versión 18.2 me ocurre el mismo error con la fecha:

![blablabla](https://cloud.githubusercontent.com/assets/19883115/16363278/c88f22f0-3b8f-11e6-9304-0bdd12ce4131.png)


![blabla](https://cloud.githubusercontent.com/assets/19883115/16363279/ce12fd14-3b8f-11e6-8a67-827e3b02d848.png)


![issues](https://cloud.githubusercontent.com/assets/19883115/16363287/ef4f1120-3b8f-11e6-93f9-f5bcd95c4df0.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/333668/logcat.txt)

**Comment by sanro14** [comment]
@GeronimoVierma existe una versión 18.3 en el slack pineado ayer.. cuando puedas verifica en esta versión

**Comment by GeronimoVierma** [comment]
El comentario anterior que hice es un comentario del viernes que estaba en el issue incorrecto, lo cambie hoy y por eso es que estaba desactualizado con respecto a la versión de la CBP, pido disculpas.

Aquí esta la prueba con la versión 18.3

![ahora si2](https://cloud.githubusercontent.com/assets/19883115/16364549/c09c9036-3bb3-11e6-9844-cf2602084683.png)


![ahora si](https://cloud.githubusercontent.com/assets/19883115/16364550/c62a6db6-3bb3-11e6-858e-2a980076f240.png)


![issues](https://cloud.githubusercontent.com/assets/19883115/16364577/91152e1c-3bb4-11e6-9dc3-80ba989139ac.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/333792/logcat.txt)

**Comment by sanro14** [comment]
@nattyco y @nelsonalfo en la versión 18.3 de CBP continúa sucediendo..

**Comment by IsbetVR** [comment]
@nattyco @nelsonalfo persiste el error de la fecha en la CBP versión V18.8

**Comment by IsbetVR** [comment]
@nelsonalfo 
Corregido en la versión 19.2 de CBP. Ya tiene la fecha actualizada en las transacciones desde la Crypto Broker.

![screenshot_24](https://cloud.githubusercontent.com/assets/19142276/16568471/8bff89c8-41f8-11e6-9213-87eab2b5c0f3.jpg)
