### ISSUE TITLE
CBP No refleja los depositos en la Stock Management

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#607]
### Nombre de la Aplicación: CBP
-----
##### Reporte de error: 

En el momento que quiero depositar dinero de mis billeteras en la Broker Willet para negociar. En una me refleja el restante y no se deposita y en otra me lo quita y no se ve ni el retiro ni el deposito

![sm](https://cloud.githubusercontent.com/assets/19353722/16286968/ae767ea6-38a9-11e6-9d3f-d7308c460ce0.png)

![bitcoin](https://cloud.githubusercontent.com/assets/19353722/16286989/da8b1d62-38a9-11e6-850a-65ca81c507f8.png)

![fecha 3](https://cloud.githubusercontent.com/assets/19353722/16286992/e1ce15de-38a9-11e6-9bba-0d33d1caa95f.png)
------
#### Dispositivo desde donde se realizo la prueba

![samsung](https://cloud.githubusercontent.com/assets/19353722/16287024/1244ed8c-38aa-11e6-9fe5-a9a36db39d01.png)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/328934/logcat.txt)

**Comment by marielis-urbina** [comment]
En la versión de la CBP 18.2, no se sigue reflejando los depósitos de la Bank

![stockm](https://cloud.githubusercontent.com/assets/19353722/16351967/9b5150b8-3a33-11e6-8848-54c5812506cc.png)

![bank2](https://cloud.githubusercontent.com/assets/19353722/16351969/a2f5a1f2-3a33-11e6-99bd-37875c24d1a4.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16351987/c23444f6-3a33-11e6-852a-2155efe03729.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/332694/logcat.txt)

**Comment by abicelis** [comment]
@marielis-urbina no he terminado con esa pantalla, cuando lo haga te avisare por aca.

**Comment by marielis-urbina** [comment]
Perfecto, gracias

**Comment by abicelis** [comment]
@marielis-urbina Revisa la proxima version 18.4, a ver si esta todo ok plz.

**Comment by marielis-urbina** [comment]
Claro, lo haré


2016-06-28 16:13 GMT-04:30 Alejandro Bicelis <notifications@github.com>:

**Comment by marielis-urbina** [comment]
Listo en la versión 18.4, este error ya no aparece, gracias @abicelis
