### ISSUE TITLE
Banking Wallet - Error en fecha de transacciones desde la Crypto Broker

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#608]
### CBP Versión v18

-----

##### Reporte de error: 

   *Cuando tengo las Wallets configuradas en el Stock Management (Crypto Broker), al pasarle montos de la Banking Wallet, tal como aparece reflejada en la Pantalla 1, al revisar la "Banking Wallet", donde me aparece el detalle de las transacciones que he realizado (Pantalla 2), la fecha de los depósitos cuando reviso el detalle sale bien (Pantalla 3), pero las transacciones que hice desde la Crypto Broker  tiene mal la fecha (Pantalla 4).

------
#### Pantalla 1

![screenshot_48](https://cloud.githubusercontent.com/assets/19142276/16287133/eaa89bca-38ae-11e6-9e2d-1b054da6133e.jpg)

#### Pantalla 2

![screenshot_50](https://cloud.githubusercontent.com/assets/19142276/16287143/fc693cb6-38ae-11e6-9827-2d700581a5e4.jpg)

#### Pantalla 3

![screenshot_51](https://cloud.githubusercontent.com/assets/19142276/16287151/11fefa66-38af-11e6-9bac-cae07fe7ba69.jpg)

#### Pantalla 4

![screenshot_52](https://cloud.githubusercontent.com/assets/19142276/16287166/326c6892-38af-11e6-8dc0-72ac0b160eec.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16287177/4d0dee00-38af-11e6-80af-d558ee0c358b.jpg)

**Comment by IsbetVR** [comment]
@MaviDavsa @abicelis

**Comment by abicelis** [comment]
@IsbetVR ok, revisare esto

**Comment by abicelis** [comment]
Es cierto, esta arreglada la fecha en la version 18.2! @IsbetVR

**Comment by GeronimoVierma** [comment]
En la versión 18.2 al pasar 25 btc de la Cripto wallet a mi stock (imagen 1) y luego al ir a la Bitcoin Wallet a mirar el record de la transacción me sale una fecha de 1970 (imagen 2):


![blablabla](https://cloud.githubusercontent.com/assets/19883115/16339878/db715bec-39ee-11e6-893d-bfc1f6b7fb2b.png)



![blabla](https://cloud.githubusercontent.com/assets/19883115/16339849/b11697b8-39ee-11e6-86df-b47a84b70e88.png)

![issues](https://cloud.githubusercontent.com/assets/19883115/16339901/fa15fa76-39ee-11e6-9798-9921085753c7.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/331851/logcat.txt)

**Comment by IsbetVR** [comment]
@GeronimoVierma el error que comentaste aqui está reportado en el caso 606, por favor cólocalo allí

**Comment by IsbetVR** [comment]
@MaviDavsa @abicelis en la Versión v18.2 de CBP efectivamente está corregido. Se puede cerrar.

![screenshot_69](https://cloud.githubusercontent.com/assets/19142276/16351677/7cc37444-3a35-11e6-92bc-ea286234af04.jpg)

Dispositivo de prueba:
- [x] Emulador
- Google Nexus 4
- Versión de Androd: 5.0.0
