### ISSUE TITLE
Bitcoin Wallet_Error_Inicio Fermat_Contacts_Send to contact_Send request to contact

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#61]
#### Nombre pantalla

-----

##### Reporte de error:

   * Luego de la ultima actualizacion tuve que hacer alrededor de 15 intentos par ingresar a la aplicacion de fermat debido a que esta arrojaba un error.
![screenshot_2016-03-04-18-00-04](https://cloud.githubusercontent.com/assets/17274154/13556069/31657a6c-e3a3-11e5-9f18-eb513857158b.png)

------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *En la lista de contacto se muestra el contacto (actorintrauser) duplicado muchas veces.
![screenshot_2016-03-04-18-07-41](https://cloud.githubusercontent.com/assets/17274154/13556056/d9c20938-e3a2-11e5-8d53-c8ebd7aa37f8.png)
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   * Al ingresar al formulario de envio, este no muestra el formulario sino que arroja un error que no permite realizar la operacion.
![screenshot_2016-03-04-18-09-32](https://cloud.githubusercontent.com/assets/17274154/13556085/8249e40e-e3a3-11e5-97a4-29500ad7dad4.png)

   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Al ingresar al formulario de pedido de pago, este no muestra el formulario sino que arroja un error que no permite realizar la operacion.
   ![screenshot_2016-03-04-18-12-44](https://cloud.githubusercontent.com/assets/17274154/13556112/fcbd0798-e3a3-11e5-9834-d9588e831eb1.png)

   
------
#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy 
* Modelo: S4 mini
* Version de Android: 4.4.2 Kit Kat

**Comment by nattyco** [comment]
@maydiamc @augusto-ponce  Recordar reportar cada problema en un issue distinto, un issue por pantalla donde se produsca un error.

**Comment by maydiamc** [comment]
@nattyco yo hice este issue el domingo, x lo tanto no tenia el conocimiento de los nuevos lineamientos que diste el dia de hoy

**Comment by maydiamc** [comment]
@augusto-ponce 
En la ultima actualizacion los errores fueron solucionados, por favor cerrar este caso
