### ISSUE TITLE
COMMUNITY - NO PERMITE ENVIAR SOLICITUDES DE CONEXIÓN. 

### ISSUE THREAD

**Issue by LilianFlores** [Fermat-ORG/beta-testing-program#610]
#### Nombre pantalla

Crypto Broker Users

### Nombre de la Aplicación 

CBP

-----

##### Reporte de error: 

   Sucede que al querer enviar solicitud de conexión a alguno de los brokers disponibles (en este caso estaban dos) no me permite conectarme con ellos, me pide intentar de nuevo y por más que lo hago, no me deja enviar la solicitud. Esto me sucede con ambos brokers (pantalla 1 y pantalla 2)
   
![screenshot_2016-06-23-11-42-02](https://cloud.githubusercontent.com/assets/19652611/16310148/3a806732-3935-11e6-8cff-eb75268d0875.png)

![screenshot_2016-06-23-11-56-49](https://cloud.githubusercontent.com/assets/19652611/16310317/eb091b94-3935-11e6-8b3c-b9cad379c8f7.png)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16310104/ffc550f8-3934-11e6-8efa-f752b8f790d2.png)

**Comment by LilianFlores** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo

**Comment by yalayn** [comment]
Yo @yalayn. Voy a estar trabajando en este issue.

**Comment by yalayn** [comment]
Hola @MaviDavsa, @sanro14, @AdryCanonico. Ya se corrigió este bug. Debe estar disponible para la próxima versión.

**Comment by arosiopr** [comment]
@LilianFlores corregido

**Comment by LilianFlores** [comment]
Efectivamente ya no se presenta este error en la versión 18.2. Cerrar caso. @MaviDavsa
