### ISSUE TITLE
Community wallet user - ERROR EN ESCRITURA DEL NOMBRE APP

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#613]
#### Nombre pantalla

Crypto Wallet User

### Nombre de la Aplicación 

Bitcoin Wallet - CBP 18.2
-----

##### Reporte de error: 

   *En la versión 18.2 de la la CBP específicamente en las comunnities, el nombre del banner es Crypto Wallet User Community y al entrar a ella sale mal escrito como " Cripto wallet users".
   
------

![screenshot_46](https://cloud.githubusercontent.com/assets/19670319/16338312/99d74cb8-39e5-11e6-8d37-a239be9be17b.png)

![screenshot_45](https://cloud.githubusercontent.com/assets/19670319/16338316/a1cc68fe-39e5-11e6-9246-2bef4789001a.png)

#### Dispositivo desde donde se realizo la prueba

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/16338200/f7961b50-39e4-11e6-8e2c-306892f80a23.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@nattyco @MaviDavsa

**Comment by AdryCanonico** [comment]
@dorzar1989 @nattyco En la versión 18 de CBP se corrigio el error en el home de la community pero en el drawer persiste el error en la escritura. 

![commu](https://cloud.githubusercontent.com/assets/18584168/16359390/b6c3f958-3afc-11e6-860e-b356b2858864.png)

**Comment by nattyco** [comment]
@AdryCanonico  lo del drawer se me paso, ya lo corrijo para la proxima

**Comment by AdryCanonico** [comment]
ok @nattyco  estaré pendiente

**Comment by dorzar1989** [comment]
Fue corregido solo el nombre interno, pero el del Drawer persiste

**Comment by arosiopr** [comment]
en la version 18.8 se corrigio el error en el drawer

**Comment by dorzar1989** [comment]
En la Version 18.8 CBP Se corrigió el error por completo.

![screenshot_49](https://cloud.githubusercontent.com/assets/19670319/16524100/a947d82c-3f74-11e6-8001-105a4b1202b7.png)

![screenshot_50](https://cloud.githubusercontent.com/assets/19670319/16524104/ad60b834-3f74-11e6-9cf5-65291e53673c.png)


Por Favor Cerrar el Caso @MaviDavsa
