### ISSUE TITLE
BITCOIN WALLET - SIN ICONO DE FONDO CUANDO NO HAY TRANSACION EN REQUEST

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#615]
#### Nombre pantalla

REQUEST - RECEIVED 

### Nombre de la Aplicación 

BITCOIN WALLET

-----

##### Reporte de error: 

   *Sin icono de fondo que te indica que no tienes transacciones en las pestañas de Sent y Received. 
   
![sin fondo](https://cloud.githubusercontent.com/assets/18584168/16359522/97bdc6ba-3b01-11e6-90b9-22046c256b50.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/333330/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by camilavaleria** [comment]
en la versión 18.8 ya aparece el icono en el fondo de la pantalla;


![image](https://cloud.githubusercontent.com/assets/18740418/16524099/7762c078-3f70-11e6-9be7-36cafcedb389.png)

**Comment by GeronimoVierma** [comment]
En la versión 18.8 si me aparece el icono en el fondo de la pantalla:


![0](https://cloud.githubusercontent.com/assets/19883115/16524209/073e8100-3f71-11e6-841c-2a03b1e88cda.png)

![0](https://cloud.githubusercontent.com/assets/19883115/16524223/15957d08-3f71-11e6-9f5a-8233485f0287.png)
