### ISSUE TITLE
BITCOIN WALLET - FLOATING BUTTOM MEJORAS 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#616]
#### Nombre pantalla

REQUESTS

### Nombre de la Aplicación 

BITCOIN WALLET

-----

##### Reporte de error: 

   *Seria bueno mejorar este botón, ya que no se ve agradable a la vista. Tal vez colocarlo en el Accion bar con un mejor diseño. 

![sin fondo](https://cloud.githubusercontent.com/assets/18584168/16359522/97bdc6ba-3b01-11e6-90b9-22046c256b50.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/333330/logcat.txt)
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  se toma como sugerencia, este es el diseño que fue aprobado en su momento para esta app, lo de que no es agradable a la vista tenes que poner algo como "para mi" no es agrabable porque es tu opinion

**Comment by AdryCanonico** [comment]
@nattyco es un botón que no lo veo muy funcional en su ubicación porque cuando tienes muchas transacciones tiende a tapar el detalle de las mismas a pesar de que se puedan skrolear. Pienso que debe tener un rediseño porque es para pedir y con el que tiene actualmente da la información que envía.  No quise colocar para mi porque antes de colocar el caso hice la pregunta a varias personas y lo estado estudiando para poder colocar el caso. Esto a mi parecer no es sólo una experiencia de usuario también algo gráfico.

**Comment by MaviDavsa** [comment]
@AdryCanonico @nattyco en el caso... el error no seria el hecho de que este el botón en Received? , es decir en esta área solo deberían salir los pagos y aceptar o denegar, dejando así que solo salga el botón en el área de "Send"... En tal de los casos si el botón esta allí es como un acceso directo ó así lo veo yo... porque sigue teniendo la misma función que es enviar... o no!?

**Comment by IsbetVR** [comment]
Buen día, usando la versión 20.4 de CBP, tengo varios "requests" en "sent" y me está tapando el botón los detalles del "request enviado" (Pantalla 1). En mi opinión este botón (Send Request Contact) se pudiese ver mejor colocándolo en la parte superior en la esquina derecha de la pantalla, y así no afecta la visibilidad de las transacciones cuando hay varias en lista. Además creo que tenerlo también en la pantalla de "Received" es innecesario (Pantalla 2).

##### Pantalla 1

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/16769768/05cf0a10-4818-11e6-9f03-a0ba62c41a2a.jpg)

##### Pantalla 2

![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/16769778/1067833a-4818-11e6-90b9-ec46f801f00c.jpg)

#### Dispositivo de prueba
- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16769787/1c8f98be-4818-11e6-8af2-e75236f6dc6b.jpg)

**Comment by sanro14** [comment]
@arnaldos

**Comment by arnaldos** [comment]
por eso para que no tape ninguna info se dio la sugerencia de colocarlo en en actionbar.

**Comment by IsbetVR** [comment]
@nattyco 
En la versión 20.7 de CBP, persiste este detalle gráfico, el botón me está tapando los requests received

![screenshot_55](https://cloud.githubusercontent.com/assets/19142276/16875036/04fbea0e-4a6b-11e6-9626-00f1c899fef3.jpg)

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP persiste este error

![monta](https://cloud.githubusercontent.com/assets/19353722/16875090/7d11f966-4a6b-11e6-944f-749086466f58.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16875097/812ce84e-4a6b-11e6-8191-8b1efeb9de09.png)

**Comment by nattyco** [comment]
@AdryCanonico  se implemento el boton para hacer el payment request en el toolbar de la wallet

**Comment by arosiopr** [comment]
@IsbetVR se puede cerrar. Se implemento en la version 20.9

![screenshot_16](https://cloud.githubusercontent.com/assets/5313326/16997276/bc5ee140-4e82-11e6-8162-db99ce6b3f8c.png)
