### ISSUE TITLE
BITCOIN WALLET - ESTANDARIZAR LOS TAMAÑOS DE LOS BOTONES EN ACCION BAR

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#617]
#### Nombre pantalla

HOME

### Nombre de la Aplicación 

BITCOIN WALLET 

-----

##### Reporte de error: 

   *Los tamaños de los botones deberían ser iguales y con diseños similares. 

![screenshot_1](https://cloud.githubusercontent.com/assets/18584168/16359572/60e5f1c8-3b04-11e6-9b95-9e23b27564f3.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by nattyco** [comment]
@AdryCanonico a que te referis concretamente?

**Comment by maydiamc** [comment]
esto se mejoro en la version 18.8 de CBP
![screenshot_11](https://cloud.githubusercontent.com/assets/17274154/16532691/7073e1ca-3f9d-11e6-85b1-68d81aa4a9a8.png)

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16532692/717937be-3f9d-11e6-964d-1ddf3c91d920.png)
