### ISSUE TITLE
BITCOIN WALLET - COLOCAR EL BOTON DE AYUDA A LA DERECHA 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#618]
#### Nombre pantalla

HOME

### Nombre de la Aplicación 

BITCOIN WALLET 

-----

Por experiencia de usuario es mas comodo colocar los botones de ayuda de primero a la derecha

![ayuda](https://cloud.githubusercontent.com/assets/18584168/16359742/0991e876-3b0b-11e6-93a2-0acaddc54750.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/333330/logcat.txt)
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by nattyco** [comment]
@AdryCanonico  aclarar esto que no se entiende a que boton te referis

**Comment by AdryCanonico** [comment]
disculpa @nattyco monto la foto que no era. ya lo arreglo

**Comment by AdryCanonico** [comment]
Listo,, ya lo arregle. :+1:  Gracias!!

**Comment by AdryCanonico** [comment]
@nattyco  En la version 19.2 no aparece la opcion de ayuda en el home. 

![screenshot_2016-07-04-13-36-29](https://cloud.githubusercontent.com/assets/18584168/16567650/0bfc5f7a-41ef-11e6-940d-c44c38058ffb.png)

![screenshot_2016-07-04-13-50-37](https://cloud.githubusercontent.com/assets/18584168/16567662/1c7a0e38-41ef-11e6-88eb-72cde7ace76f.png)

Archivo aLogcat:

[alogcat.2016-07-04-13-55-30-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346703/alogcat.2016-07-04-13-55-30-0430.txt)

Teléfono Físico:

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16567680/4fc41586-41ef-11e6-8740-2c59c465827e.png)
