### ISSUE TITLE
BITCOIN WALLET - TEXTO EN LOS BOTONES DE FERMAT CONTACT MUY GRANDE

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#619]
#### Nombre pantalla

DIALOGO - ADD CONTACT HELP 

### Nombre de la Aplicación 

BITCOIN WALLET

-----

##### Reporte de error: 

   *El texto entro de los botones de Fermat Contact esta muy grande. Esto se visualiza en los 5.0

![screenshot_2](https://cloud.githubusercontent.com/assets/18584168/16359586/a06b9a72-3b05-11e6-8aa1-b48cf68a5be7.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by camilavaleria** [comment]
en la versión 18.8 no sigue este error, puede cerrarse.

**Comment by GeronimoVierma** [comment]
En la versión 18.8 me salen los textos de los botones en tamaño normal:

![letrass](https://cloud.githubusercontent.com/assets/19883115/16525050/5ebf60d6-3f74-11e6-9ada-6a9e0f992e35.png)

![0](https://cloud.githubusercontent.com/assets/19883115/16525244/3ca9dad4-3f75-11e6-91c9-d1b7965d0c2c.png)
