### ISSUE TITLE
Error en el Menu de busqueda de Contactos

### ISSUE THREAD

**Issue by sadigarcia** [Fermat-ORG/beta-testing-program#62]
### Bitcoin Wallet 
   
------
##### Contactos

- [] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *En el menu de lista de contactos solo siguen apareciendo el Contacto de Matias y el Externo (que nos enseño agregar Naty). Según el abecedario que aparece al lado derecho de la pantalla al darle click a cualquier letra, por ejemplo la letra "A", debería aparecer Adriana o todos los contactos que empiecen por la letra "A" y no es así, la única forma que aparezca es colocando el nombre en búsqueda.

   
![screenshot_2016-03-05-16-58-54 1](https://cloud.githubusercontent.com/assets/17260129/13571141/2e2f3d68-e445-11e5-8972-b2cb5675ab17.png)

Sin embargo cuando coloco el nombre del contacto "Adriana" por ejemplo, me aparecen todos los contactos, cuando solo debería aparecerme "Adriana" que es la única que deseo que aparezca. Por ultimo, al aparecer la lista de contactos muchos siguen saliendo duplicados. Detallo imagen a continuación:

![screenshot_2016-03-05-16-59-23 1](https://cloud.githubusercontent.com/assets/17260129/13571238/db496dfc-e445-11e5-94ec-9cc919bd1dc9.png)

   
------
##### Detalle del contacto

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Al detallar un contacto después de haber aceptado su solicitud me sale como "Desconectado"

![screenshot_2016-03-07-09-33-29 1](https://cloud.githubusercontent.com/assets/17260129/13571580/1a84237a-e448-11e5-995a-519d339abcbf.png)

   
   

#### Dispositivo desde donde se realizo la prueba

* Marca: LG
* Modelo:E977
* Version de Android: 4.4.2

**Comment by nattyco** [comment]
@sadigarcia sobre la app community, el tema de que veas contactos duplicados es porque el user por defecto se llama Jhone Doe o Jane Doe, y si no le cambiaron el nombre varios dispositivos pueden tener el mismo nombre de usuario pero pueden ser identidades distintas.

Sobre el tema de Desconectado, el boton dice Desconectar, si ya lo aceptaste al usuario lo podes quitar de tus conexiones en cualquie momento, esto no es un error.

**Comment by nattyco** [comment]
@sadigarcia en la lista de contactos que adjuntas no aparece ningun contacto Adriana, para que aparesca tenes que primero hacer la conexion en el community y despues agregar un contacto nuevo en la wallet seleccionando Fermat User y buscando a Adriana.
Recien en este punto lo veras en tu lista de contacto y podras buscarlo con los filtros.
