### ISSUE TITLE
LPW - FONDO EN LA FOTO HAY CIRCULOS QUE NO TIENEN FUNCION

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#620]
#### Nombre pantalla

DRAWER 

### Nombre de la Aplicación 

LPW

-----

##### Reporte de error: 

   *El fondo azul que esta detrás de la foto del contacto tiene unos círculos que no tienen ninguna función. 

![screenshot_6](https://cloud.githubusercontent.com/assets/18584168/16359600/0e742c00-3b06-11e6-8bb4-4f61f4d48985.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by dorzar1989** [comment]
En la Version 18.8 de la CBP se corrigio este error

![screenshot_51](https://cloud.githubusercontent.com/assets/19670319/16524498/86792416-3f76-11e6-910b-72071295ba70.png)

**Comment by nattyco** [comment]
@AdryCanonico  verificar este caso
