### ISSUE TITLE
LPW - VERIFICAR LOS TEXTOS DE LA APP

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#621]
#### Nombre pantalla

TODA LA APP

### Nombre de la Aplicación 

LPW
-----

##### Reporte de error: 

   *La app tiene algunos errores a nivel de lenguaje. Seria bueno que la mandaran a revisar con un traductor.

Ejemplo la palabra LOSTS no existe

![screenshot_8](https://cloud.githubusercontent.com/assets/18584168/16359617/95d8dfce-3b06-11e6-856f-969c66067298.png)
.
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by GeronimoVierma** [comment]
En la versión 18.8 mientras revisaba la palabra que reporto Adriana entre al menú desplegable y me encontré con la palabra "Chunck Values" según estuve revisando la palabra debería ser  "Chunk Values" en vez de "Chunck Values".

![chun](https://cloud.githubusercontent.com/assets/19883115/16526685/3123a1f2-3f7c-11e6-8f6e-f925965a7b1c.png)

**Comment by nattyco** [comment]
@GeronimoVierma  @AdryCanonico  verificar este caso

**Comment by sanro14** [comment]
en la versión 19.2 sale así @nattyco @AdryCanonico @GeronimoVierma 
![2](https://cloud.githubusercontent.com/assets/5313324/16542958/8a686e4a-408b-11e6-9633-1e9a8ba2d9c6.png)
![3](https://cloud.githubusercontent.com/assets/5313324/16542957/8a5f0be8-408b-11e6-9fe9-71c70c76d284.png)

**Comment by nattyco** [comment]
@AdryCanonico  @IsbetVR verificar en la version 3.5

**Comment by arosiopr** [comment]
@IsbetVR @AdryCanonico  solucionado en la versión 3.5 de CCP, lo poco que está en inglés es correcto

**Comment by IsbetVR** [comment]
Los textos que aún están en inglés corresponden a la parte de Android Core aún no implementado.
Lo reportado en el caso fue Solucionado.
Closed #621
