### ISSUE TITLE
LPW - ESTANDARIZAR LOS TAMAÑOS DE LOS BOTONES EN ACCION BAR

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#622]
#### Nombre pantalla

HOME

### Nombre de la Aplicación 

LPW

-----

##### Reporte de error: 

   *Los tamaños de los botones deberían ser iguales y con diseños similares.

![screenshot_8](https://cloud.githubusercontent.com/assets/18584168/16359631/1c75209c-3b07-11e6-84f4-2b79b1dad070.png)
   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320 dpi

![nexus 4](https://cloud.githubusercontent.com/assets/18584168/16359527/bbee2638-3b01-11e6-8f88-d62359719f90.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by dorzar1989** [comment]
En la Version 18.8 de CBP se corrigio este error 

![screenshot_52](https://cloud.githubusercontent.com/assets/19670319/16524763/70ec096e-3f77-11e6-9680-f1f3a3a009ab.png)
