### ISSUE TITLE
CBP - Crypto Customer - MENU DESPLEGLABLE

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#623]
#### Nombre pantalla

Menu de la Crypto Customer

### Nombre de la Aplicación 

CBP Version 18.3
-----

##### Reporte de error: 

   *En la Versión 18.3 de la CBP, específicamente en el Drawer de la Crypto Customer, cuando estas en Home. aparece remarcada la opción de la Broker List, es con la única opción que me pasa..
   

![screenshot_100](https://cloud.githubusercontent.com/assets/19670319/16380994/3f44978c-3c48-11e6-8808-aff8f6eae3c2.png)

------

- Hora:

 8:34 am

- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/334909/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/16380985/338abbd8-3c48-11e6-9b1e-455d451b73d3.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @Yayotron

**Comment by abicelis** [comment]
@dorzar1989 describe exactamente como hiciste. Me baje el mismo emulador que usaste y no veo el error. Sino, avisame por slack y nos reunimos para verlo.

**Comment by abicelis** [comment]
@dorzar1989 listo en la version 18.4, gracias @MaviDavsa !

**Comment by dorzar1989** [comment]
@abicelis @MaviDavsa El error fue solucionado en la Version 18.4 . Confirmadisiiiimo y Gracias! 

![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/16452600/52413a6c-3dd7-11e6-8569-d31652219724.png)


![screenshot_3](https://cloud.githubusercontent.com/assets/19670319/16452601/5250b226-3dd7-11e6-946f-83a334c691b7.png)

**Comment by dorzar1989** [comment]
Por Favor Cerrar Caso @MaviDavsa :*

**Comment by Hernandezsmanu** [comment]
En la bitcon Walltet de la CBP versión 18.8 sucede lo mismo. Al entrar al menú de la apliacion sale seleccionado el "Home" y el "Payment requests"

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/16533079/0bc709ca-3fa0-11e6-950c-52ba9b6e11c0.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16533095/38c43150-3fa0-11e6-97de-f7c32f9d158c.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16533097/3b4f6c00-3fa0-11e6-8f87-9d4ed0650036.png)

Hora: 3:52pm
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/344092/logcat.txt)

**Comment by MaviDavsa** [comment]
@nattyco Esto en el la Bitcoin Wallet que tenemos dentro!!! Si quieres hablar con  @abicelis que el dio con el error en la Cryto Customer!

**Comment by IsbetVR** [comment]
En la versión 19.5 de CBP, en la Bitcoin Wallet ya no está marcando la opción, sólo resalta el ícono de cada opción. El único ícono que no resalta es cuando estamos en la opción de "Payment Requests"

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16619951/7bb37928-435e-11e6-95d1-53d5f100d683.jpg)

**Comment by IsbetVR** [comment]
Este casó pasó de ser de CBP a Bitcoin Wallet, ya anteriormente reportado en el #614 
Solucionado en CBP.

**Comment by IsbetVR** [comment]
Closed #623
