### ISSUE TITLE
CBP - Crypto Customer - Error en fechas de contrato

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#624]
### CBP (v18.3)

-----

##### Reporte de error: 

   *Cuando la negociación pasa a Contrato, y se van confirmando los pasos para el cierre del mismo, en la primera sección "Payment Delivery", la fecha está errada (Pantalla 1) en mi caso de customer. Y en las confirmaciones del Broker (Pantalla 2) sucede lo mismo.

------
#### Pantalla 1

![screenshot_77](https://cloud.githubusercontent.com/assets/19142276/16381068/abc23266-3c48-11e6-82fe-d377ba62cb30.jpg)

#### Pantalla 2

![6369a475a0a3a051df07b83a0f80d980b8d25d1b4c183e6815 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/19142276/16381162/249d998c-3c49-11e6-88f9-528846213446.png)

------

#### (Pantalla 1)

- [x] Emulador
- Google Nexus 4
- Versión de Android 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16381208/594df88e-3c49-11e6-87c6-0ad942586c24.jpg)

#### (Pantalla 2)

- [x] Emulador
- Google Nexus 5
- Versión de Android 5.0.0
- 480 dpi
- API 21 1080x1920

![ffffd7294db2a7379b2087360d1afdc1e119bda281b7f76145 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/19142276/16381248/9368b0f4-3c49-11e6-9ba1-1fa86f56bb2e.png)

**Comment by IsbetVR** [comment]
@MaviDavsa

**Comment by IsbetVR** [comment]
@yalayn

**Comment by yalayn** [comment]
Buenos días. Yo trabajare en este issue.

**Comment by yalayn** [comment]
Hola @IsbetVR la fecha no se debería mostrar cuando se esta en espera de la confirmación (ficha de color verde), Se debe mostrar una vez se ha confirmado la recepción (ficha color azul.). Por tal razón ahora se vera dela siguiente manera.
![captura de pantalla de 2016-06-29 17 22 21](https://cloud.githubusercontent.com/assets/4664287/16469773/8c269a66-3e1c-11e6-98f0-56a5a19e5bb9.png)

**Comment by yalayn** [comment]
Hola @IsbetVR por fa podrías confirmar si esto esta funcionando y cerrarlo de ser asi ;) Gracias.
Saludos.

**Comment by maydiamc** [comment]
en la version 19.5 de CBP esta sucediendo este error de fechas

![screenshot_9](https://cloud.githubusercontent.com/assets/17274154/16596434/eb272a72-42c1-11e6-94f9-b717792a6cb9.png)

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16596441/f1f4eb00-42c1-11e6-99a9-912ae74d6787.png)

**Comment by yalayn** [comment]
Buenos dias @MaviDavsa, @IsbetVR, @maydiamc, Estoy intentando replicar el ultimo caso reportado por @maydiamc, pero no me ha pasado por fa si le ocurre a otra persona me podrían subir el log por acá, para revisar que puede estar pasando.

**Comment by arosiopr** [comment]
@yalayn @IsbetVR  en la ficha color verde ya no sale la fecha. version de cbp 20.1
![screenshot_65](https://cloud.githubusercontent.com/assets/5313326/16688434/158fa8f8-44ec-11e6-8bc3-e77a1b36f6a4.png)

**Comment by IsbetVR** [comment]
Solucionado @yalayn en la versión 20.1 CBP

**Comment by IsbetVR** [comment]
Closed #624
