### ISSUE TITLE
Bitcoin Wallet - Contacts - Linea Divisoria

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#625]
#### Nombre pantalla

Contacts

### Nombre de la Aplicación 

Bitcoin Wallet - CBP Version 18.3
-----

##### Reporte de error: 

   *En la Bitcoin Wallet de la CBP version 18.3, específicamente en la Pantalla de Contacts, al momento de desplazarme hacia abajo o hacia arriba existe una de las lineas divisorias que aparece dos veces y se monta sobre los nombres letras y demás caracteres que aparecen en la lista..
   

![screenshot_64](https://cloud.githubusercontent.com/assets/19670319/16383565/9de9b294-3c53-11e6-9c7c-e37554740459.png)

![screenshot_65](https://cloud.githubusercontent.com/assets/19670319/16383570/a2a9a1ea-3c53-11e6-9256-30c43aefe966.png)

![screenshot_66](https://cloud.githubusercontent.com/assets/19670319/16383574/a6d8e03c-3c53-11e6-9fb8-c0b88a91622e.png)

------

- Hora:

10:06 am

- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/335078/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/16383549/90f76932-3c53-11e6-9021-02ab8bb3ce59.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by arosiopr** [comment]
en la versión 18.8 de CBP ya no se monta las lineas @dorzar1989 @MaviDavsa 

![screenshot_36](https://cloud.githubusercontent.com/assets/5313326/16526192/c7ba6a7c-3f79-11e6-875f-2bcfd9292a18.png)

![screenshot_38](https://cloud.githubusercontent.com/assets/5313326/16526217/eb4f926e-3f79-11e6-98b2-5ef63218c0ef.png)

![screenshot_37](https://cloud.githubusercontent.com/assets/5313326/16526270/30fc38da-3f7a-11e6-8ec4-031e694a21b0.png)
