### ISSUE TITLE
BITCOIN WALLET-HOME: RETIROS EFECTUADOS (no informa su destino)

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#627]
#### Nombre pantalla
SENT

### Nombre de la Aplicación 

CBP V 18.3
-----

##### Reporte de error: 

   * Realice dos retiros de la Bitcoin Wallet (30 y de 5 BTC) desde la Crypto Broker ( Stock Management) y cuando reviso en ella (Bitcoin Wallet ) no informa de donde se descontaron los 35 BTC. Tambíen se observa que no detalla las dos transacciones (30 y de 5 BTC) solo muestra siempre la ultíma que se realizo como veran en la foto.
![no aparece donde estan los btc sacados](https://cloud.githubusercontent.com/assets/17283358/16384638/864123a2-3c53-11e6-8a43-a19082747821.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/16384707/d1af5426-3c53-11e6-88a1-d38b796ee4fb.png)

[logcat no aparece donde estan los BTC.txt](https://github.com/Fermat-ORG/beta-testing-program/files/335156/logcat.no.aparece.donde.estan.los.BTC.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![nexus 5](https://cloud.githubusercontent.com/assets/17283358/16384845/5662b208-3c54-11e6-8f45-5da50c072b73.png)

**Comment by MaviDavsa** [comment]
@nattyco @nelsonalfo @yalayn Este es el caso de lo que les había comentado!

**Comment by abicelis** [comment]
@yolandayancel se que si le das click en la transaccion en la bitcoin wallet te sale una listica de transacciones asociadas (ahi te deben salir tus transacciones de 5 y de 30 btc)

Ademas, si le das click en donde dice Available Balance, te deberia salir el Book Balance, que es el Available -  los 35 BTC que transferiste a la bitcoin wallet (Es decir, te deberia decir "Book Balance = 15 BTC")

Revisa y cualquier cosa, @nattyco

**Comment by MaviDavsa** [comment]
@abicelis Correcto amor... Lo que estabamos diciendo es el hecho de que dentro de los Recieved o los Send salga que se fue hasta alguna parte de la CBP, no se si me explico!?

**Comment by abicelis** [comment]
@MaviDavsa hmm entiendo.. dejame revisar y te digo

**Comment by yolandayancel** [comment]
Prueba 29-06-16
Caso 627 CBP 18.4
Nexus 5 5.0.0
Buenas Alejandro, te explico: Hoy  realice dos retiros de la Bitcoin Wallet (30 y de 10 BTC) desde la Crypto Broker ( Stock Management) y cuando reviso en ella (Bitcoin Wallet ) no informa de donde se descontaron los 40 BTC como expuse anteriormente. El detalle de  las dos transacciones (30 y de 10 BTC) no lo muestra. Como recomendaste  le clikeo  en la transacción en la bitcoin wallet  sale la listica de transacciones asociadas pero el punto es que no dice a donde se fue ese dinero retirado. También se observa que la fecha está equivocada.
![caso 627](https://cloud.githubusercontent.com/assets/17283358/16453002/fa0f7dba-3dd4-11e6-91b6-3a91dd9b9d64.png)
[logcat caso 627.txt](https://github.com/Fermat-ORG/beta-testing-program/files/339319/logcat.caso.627.txt)

**Comment by abicelis** [comment]
Ok @yolandayancel, reviso y te aviso

**Comment by abicelis** [comment]
@yolandayancel @MaviDavsa Revisen la version 18.10, ahi esta arreglado esto.

**Comment by yolandayancel** [comment]
Prueba 04-07-16
Caso 627 CBP 19.2
Nexus 5 5.0.0
Ya  informa de donde se descontaron  BTC. Tambíen se observa que las fechas estan correctas. Pero ahora duplica las transacciones como ves en la foto. 
![627-1](https://cloud.githubusercontent.com/assets/17283358/16570278/588a7b58-4210-11e6-8bff-c35e50c2fcb8.png)

[logcat627.zip](https://github.com/Fermat-ORG/beta-testing-program/files/346864/logcat627.zip)

**Comment by sanro14** [comment]
@abicelis

**Comment by abicelis** [comment]
@yolandayancel este issue fue reportado pues las transacciones Bitcoin, hechas desde CBP/Settings/Stock Management no decian por ningun lado que estas venian de CBP.

Esa transaccion que me muestras ahora como duplicada dice "Prestamo. Okey jaja", no veo que haya sido de CBP/Settings/Stock Management pues a ellas las configure para que dijeran "Held/Unheld funds from Broker Wallet", no un mensaje configurable "Prestamo. Okey jaja" como veo aca.

Ver el Hold de 5.99 BTC realizado desde CBP, en la Bitcoin wallet:

![image](https://cloud.githubusercontent.com/assets/9850854/16571024/49830b2e-4220-11e6-9b69-06aa1fefef4a.png)

**Comment by yolandayancel** [comment]
Buenas noches Alejandro

Te explico:
La negociación que realice cor Dorcari, se triplico la información en tres
transacciones en la Bitcoin Wallet. Como veras en la foto el regtest se
registro el 0.1 en la transacción con marielis y en la transacción de
negociación. Tres transacciones distintas con el monto que me abonaron de
la negociación.

**Comment by sanro14** [comment]
@nattyco puedes revisar esto por favor.. Gracias.. ah también verifica no se si notas que se monta el texto si logras observar el capture de alejandro.

**Comment by abicelis** [comment]
@yolandayancel en una negociacion hecha a traves de  CBP de triplico la transaccion en la bitcoin wallet??

**Comment by abicelis** [comment]
Si es asi, abre otro issue @yolandayancel  porfa, que es distinto a este issue!

**Comment by yolandayancel** [comment]
Si era una negociación que se triplico la información el la Bitcoinwallet

**Comment by yolandayancel** [comment]
Alejandro:
Esto ocurrió en el Home- pantalla de receive: En los BTC recibidos de la
regtest allí se registro los 50 Btc y los 2 de marielis y los 0.10 de
Dorcaris. En lo recibido de Marielis dentro de la misma BitcoinWallet se
muestra los 50, los 2 y los 0.10 de la negociación y en lo recibido del
customer Dorcari: se repite los 50, los 2 y los 0.10 de la negociación.
El 04/07/2016 19:33, "Yolanda Yancel" <yyancel47@gmail.com> escribió:

Si era una negociación que se triplico la información el la Bitcoinwallet

**Comment by MaviDavsa** [comment]
@nattyco
