### ISSUE TITLE
CBP-Bitcoin Wallet: los Requests no llegan a su destinatario.

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#628]
#### Nombre pantalla

Requests

### Nombre de la Aplicación 

CBP V18.3- Bitcoin Wallet
-----

##### Reporte de error: 

  Al tratar de enviar Requests a un contacto este nunca lo recibe y estatus queda en "Pending response": 

![po](https://cloud.githubusercontent.com/assets/19883115/16386805/dd6cc214-3c5b-11e6-86e4-23ac9c91268d.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![issues](https://cloud.githubusercontent.com/assets/19883115/16386813/e5436696-3c5b-11e6-814f-cf5d0de735ad.png)

**Comment by MaviDavsa** [comment]
En mi caso llegan las notificaciones...
![kjasjdf](https://cloud.githubusercontent.com/assets/17273005/16386989/adce350a-3c5c-11e6-8378-e86cdd2346da.JPG)

Pero cuando voy a revisar no hay absolutamente nada... 

![fgdfgd](https://cloud.githubusercontent.com/assets/17273005/16386999/c4060e42-3c5c-11e6-924a-2d5eecc937c4.JPG)

Dispositivo con el que se realizo la prueba

![google nexus 5 0](https://cloud.githubusercontent.com/assets/17273005/16387008/cba248c8-3c5c-11e6-9021-20f91aa66a8b.JPG)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Prueba 28-06-16
Caso 628 CBP 18.3
Nexus 4 5.0.0 320dpi
En este emulador ocurrelo lo reportado por Geronimo, los requestet  aparecen en  la notificación:
![peyment request desaparecen 1](https://cloud.githubusercontent.com/assets/17283358/16416302/619edc34-3d0b-11e6-9d98-9100f1978095.png)

Pero no aparecen en el request en RECEIVED
![peyment request desaparecen 2](https://cloud.githubusercontent.com/assets/17283358/16416362/b3ba6da8-3d0b-11e6-9618-ce40bfd8f354.png)
[logcat peyment.txt](https://github.com/Fermat-ORG/beta-testing-program/files/337044/logcat.peyment.txt)

**Comment by marielis-urbina** [comment]
En la versión 18.7 CBP ya llegan los requests y puedes aceptarlo

![req](https://cloud.githubusercontent.com/assets/19353722/16507914/966b270e-3ef7-11e6-8224-81092f3279bf.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16507919/9eebc910-3ef7-11e6-97e8-6fd7039de451.png)

**Comment by yolandayancel** [comment]
Prueba 30-06-16
Caso 628 CBP 18.7
Nexus 4 5.0.0 320dpi
En este emulador ya no ocurrelo lo reportado por Geronimo, los requestes llegan.
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/16507907/81b70c60-3ef7-11e6-9d0b-1d10ea6a66ea.png)
[logcat628.txt](https://github.com/Fermat-ORG/beta-testing-program/files/342572/logcat628.txt)

**Comment by GeronimoVierma** [comment]
En la versión 18.7 envié un Request a un contacto y lo recibió correctamente:

![request](https://cloud.githubusercontent.com/assets/19883115/16521986/79e54098-3f64-11e6-9404-dc7ea043f132.png)
 Imagen del contacto:
![screenshot_46](https://cloud.githubusercontent.com/assets/19883115/16522001/9d2145ca-3f64-11e6-95f4-a6a3839eb666.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/343478/logcat.txt)
