### ISSUE TITLE
CBP-Broker Wallet-Contracts-Error se cancela el contrato

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#629]
### Nombre de la Aplicación CBP

-----

##### Reporte de error: 

   *Estaba realizando una negociacion y me salio una notificacion "the contract has been canceled"

![screenshot_2016-06-27-11-58-11](https://cloud.githubusercontent.com/assets/5313326/16387005/c84d11bc-3c5c-11e6-9fc0-8ef333d2e9b5.png)

Me voy a la pantalla de Contracts History, al detalle del contrato y me sale en efecto el contrato cancelado

![screenshot_2016-06-27-12-01-40](https://cloud.githubusercontent.com/assets/5313326/16386902/3abe1080-3c5c-11e6-82e9-2ce7766b0473.png)

Al customer le sale waiting for you, al customer no le sale cancelado.

![1](https://cloud.githubusercontent.com/assets/5313326/16386983/a3fc9648-3c5c-11e6-860f-ae44567fd09d.jpg)

![2](https://cloud.githubusercontent.com/assets/5313326/16386991/b0710404-3c5c-11e6-9c35-3a15a35d4ed4.jpg)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![version de telefono](https://cloud.githubusercontent.com/assets/5313326/16386920/4e674ab6-3c5c-11e6-8a07-cc61094cf289.png)

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@abicelis @nelsonalfo @yalayn

**Comment by franklinmarcano1970** [comment]
Tenemos que probar y repetir este caso, porque no logramos replicar el detalle.

**Comment by GeronimoVierma** [comment]
En la versión 18.5 mientras me encontraba en plena negociación con un Customer el contrato se cancelo a pesar de seguir los pasos al detalle:

![00](https://cloud.githubusercontent.com/assets/19883115/16493453/541ce146-3eaf-11e6-9a2b-1d809f019f6d.png)


![01](https://cloud.githubusercontent.com/assets/19883115/16493455/576da0b0-3eaf-11e6-823f-e20531e57a37.png)


![chi](https://cloud.githubusercontent.com/assets/19883115/16493529/9aba9cf6-3eaf-11e6-932d-b85207dc4e54.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/341755/logcat.txt)

**Comment by sanro14** [comment]
Se solucinó
