### ISSUE TITLE
Bitcoin Wallet_Opcion para enviar btc a LPW

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#630]
#### Nombre pantalla
Setting

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *Desde la version 18.3 de CBP, en el menu setting de la bitcoin wallet no se refleja ninguna opcion para hacer el envio de bitcoin a la Loss Protected Wallet

![screenshot_2016-06-27-14-31-49](https://cloud.githubusercontent.com/assets/17274154/16394094/4dfc7c10-3c7d-11e6-926c-603eabe0c616.png)
   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16394098/57a7639c-3c7d-11e6-9f5c-0101c0fcec05.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by arosiopr** [comment]
@maydiamc la opcion ya se visualiza en la version de cbp 18.8
![screenshot_33](https://cloud.githubusercontent.com/assets/5313326/16524166/d9e534ba-3f70-11e6-9b85-fc432d8ecb98.png)

**Comment by maydiamc** [comment]
solucionado
