### ISSUE TITLE
Bitcoin Wallet_ Transacciones Desaparecen

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#631]
#### Nombre pantalla
Home

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *Version 18.3 de CBP

Despues de haber solicitado bitcoin y hacer un envio a la crypto Broker (Restock), intente solicitar de nuevo btc en la bitcoin wallet, al hacerlo desaparecieron de send y receive las transacciones realizadas, al cabo de dos horas mas o menos sin utilizar la aplicacion volvi a ingresar a la bitcoin wallet y ya habian aparecido de nuevo las transacciones en ambas pantallas.

Nota: en las dos primeras imagenes no existen transacciones, ya que habian desaparecido y no tenia capture de esas pantalla de antes de que esto sucediera, pero en los siguentes dos capture luego de aparecer de nuevo las transacciones, se observa q la fecha de la transaccion que esta en RECEIVED, es anterior a la hora del capture de la desaparicion de las transacciones

![screenshot_2016-06-27-14-57-08](https://cloud.githubusercontent.com/assets/17274154/16394320/64e3bb86-3c7e-11e6-9a82-da6053ce4e02.png)
![screenshot_2016-06-27-14-57-21](https://cloud.githubusercontent.com/assets/17274154/16394323/67427552-3c7e-11e6-8afb-6ff36e46db69.png)
![screenshot_2016-06-27-16-05-06](https://cloud.githubusercontent.com/assets/17274154/16394325/6a7bd3ee-3c7e-11e6-8001-a15fffafc01a.png)
![screenshot_2016-06-27-16-04-37](https://cloud.githubusercontent.com/assets/17274154/16394327/6cddd27c-3c7e-11e6-8071-0ecd84cbde57.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16394310/5c224d3c-3c7e-11e6-93c0-6d0e8c06e69a.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  hay que descartar si esto pasa solo al usar en conjunto con la crypto Broker (Restock)

**Comment by maydiamc** [comment]
en la 18.8 volvio a suceder, se desaparecio la transaccion recibida y no se ha echo conexion con la broker (restock)

![screenshot_12](https://cloud.githubusercontent.com/assets/17274154/16532923/049f8e70-3f9f-11e6-995b-cc8d2b3eeef0.png)

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16532932/116e75da-3f9f-11e6-8aaa-ffe5d1c51c85.png)

**Comment by IsbetVR** [comment]
@nattyco  
En la versión de CBP v19.2, probando la Bitcoin Wallet, y haciendo pruebas de transacciones sólo con usuarios de la Bitcoin Wallet, me desapareció una transacción que me enviaron (Pantalla 1), a penas me llegó la notificación de haber recibido 1 btc, me salía en la sección de "RECEIVED", pero al llegarme otra transacción, por 2 btc, me desapareció el registro (pantalla 2). 
Me llegaron 50btc de regtest, 1btc de otro usuario (la transacción que desapareció) y 2btc del usuario "yoly1" en total sería 53 btc en el available menos 0,50btc que envié a través de request, me quedan los "52,50 btc" que me salen en la pantalla 2.

#### Pantalla 1

![1](https://cloud.githubusercontent.com/assets/19142276/16567741/ed982108-41ef-11e6-8cd6-01156ebc66cf.png)

#### Pantalla 2

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/16567748/0469d7e6-41f0-11e6-8ca1-c6cd83693152.jpg)

#### Pantalla 3

![screenshot_16](https://cloud.githubusercontent.com/assets/19142276/16567784/88e09fbe-41f0-11e6-922e-d5b7fbdfd24f.jpg)

#### Dispositivo de prueba:
- [x] Emulador 
- Google Nexus 4
- Versión Android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16567852/52ca6d82-41f1-11e6-8c8a-5d07d27dbdca.jpg)

**Comment by nattyco** [comment]
@IsbetVR  la transaccion que no ve es la de transaccion de Yolanda por 3.55 verdad, pero por lo que veo lo que paso es que le esta poniendo mal el monto porque tenes de yolanda la transaccion por 2 btc, esa seria la segunda transaccion que llego? Faltaria la transaccion por 1 btc.

**Comment by IsbetVR** [comment]
@nattyco 
Me llegaron 2 transacciones, una de "1 btc" de gabymorillo y luego me llegó la de yolanda por "2 btc", al llegarme la de yolanda se desapareció el registro de "1 btc" de gabymorillo. El faltante en el balance de "0.50 btc" fue por un request que me hicieron. Las operaciones las está haciendo bien, el detalle es que me desaapreció la de "1 btc" que fue la primera que me llegó.

**Comment by maydiamc** [comment]
en la version 19.4 esto se soluciono

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16588314/83542cf8-429c-11e6-9689-e1496fcc3fbf.png)

**Comment by arosiopr** [comment]
en la version 20.1 de CBP
vuelve a suceder que se borran las transacciones, reabrir por favor @IsbetVR 

![screenshot_73](https://cloud.githubusercontent.com/assets/5313326/16692786/5f30dda6-4500-11e6-95ae-b5f2133d143a.png)

![screenshot_76](https://cloud.githubusercontent.com/assets/5313326/16692801/6c2923f6-4500-11e6-98a5-080ecb7ee773.png)

Emulador

API 19

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16692845/96d298ee-4500-11e6-8280-7cd63385e27f.png)

Logcat

Hora de transacciones depues de las 11:25 am

[Google Nexus 4 - 4.4.4 - API 19 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354606/Google.Nexus.4.-.4.4.4.-.API.19.-.768x1280-logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso     BITCOIN WALLET-  CBP V 20.1
Emulador Genymotion:
Nexus 5 5.0.0 api 21 480dpi
Hora aproximada del logcat:4:47PM
[logcat631.txt](https://github.com/Fermat-ORG/beta-testing-program/files/355099/logcat631.txt)
Despues de recibir dos payment y yo enviar BTC, estos se borraron y me reintegro todos los BTC que tenia al principio que me dio la red (100BTC)
![btc salta linea siguiente](https://cloud.githubusercontent.com/assets/17283358/16701240/7f3dc056-452c-11e6-8d5a-1a9c8ff51f26.png)
![631](https://cloud.githubusercontent.com/assets/17283358/16701247/8a767da0-452c-11e6-8b54-85da8913ca25.png)

**Comment by arosiopr** [comment]
en CBP version 20.4 persiste el error 

![screenshot_91](https://cloud.githubusercontent.com/assets/5313326/16767118/e19e3c6c-480b-11e6-8929-a6f9d4866622.png)

![screenshot_96](https://cloud.githubusercontent.com/assets/5313326/16767127/e74d2a6a-480b-11e6-8321-d0d2883c08fa.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16767131/ecdc726a-480b-11e6-8689-1621b66c8271.png)

**Comment by arosiopr** [comment]
en CBP version 20.4 persiste el error 

![screenshot_91](https://cloud.githubusercontent.com/assets/5313326/16767118/e19e3c6c-480b-11e6-8929-a6f9d4866622.png)

![screenshot_96](https://cloud.githubusercontent.com/assets/5313326/16767127/e74d2a6a-480b-11e6-8321-d0d2883c08fa.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16767131/ecdc726a-480b-11e6-8689-1621b66c8271.png)

**Comment by maydiamc** [comment]
en la vrsion 20.4 de cbp no sucede este error

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16769133/547d22e4-4815-11e6-8b6b-fec4c99a7218.png)

**Comment by maydiamc** [comment]
en la version 20.4 de cbp esta sucediendo el error

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16769203/b7b4176e-4815-11e6-8d49-ea336657f8ce.png)

**Comment by marielis-urbina** [comment]
En la versión 20.4 en la Bitcoin Wallet, se siguen desapareciendo las transacciones 

![bw0](https://cloud.githubusercontent.com/assets/19353722/16769357/64e74d34-4816-11e6-9f0a-02c48e70e188.png)

Dispositivo desde donde se realizo la prueba

 Emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/16769417/9cf4e1b4-4816-11e6-80a7-53f7bf4ac932.png)

**Comment by marielis-urbina** [comment]
En la versión 20.5 de Bitcoin Wallet se siguen desapareciendo las transacciones

Dispositivo desde donde se realizo la prueba

Emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/16819389/3816e5c6-491a-11e6-84fc-b881950adf5e.png)

**Comment by dorzar1989** [comment]
En la Version 20. 6 de la CBP no pude verificar este Issue, ya que al momento de Agregar al Contacto de Fermat, la aplicacion me da aviso de Fermat no responde al intentar hacer Click en el Check Box del Contacto.

- Screenshots:

![screenshot_43](https://cloud.githubusercontent.com/assets/19670319/16859056/c0804896-49f9-11e6-8754-1b812a980ba0.png)

![screenshot_44](https://cloud.githubusercontent.com/assets/19670319/16859063/cad377f0-49f9-11e6-9f0f-9865bf9f8379.png)

- Movil: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16859068/d33f6b24-49f9-11e6-9d06-d4c18e2d9a2d.png)

**Comment by camilavaleria** [comment]
En la version 20.7 persiste el error, se desaparecen las transacciones del send y del received tal y como se indican a continuacion;

![image](https://cloud.githubusercontent.com/assets/18740418/16875998/3ecb53f0-4a70-11e6-90ce-dd4b45e4aacc.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16876017/4bd2c290-4a70-11e6-9343-a338d0200404.png)

Emulador de prueba;

![image](https://cloud.githubusercontent.com/assets/18740418/16876031/60da6a26-4a70-11e6-9b95-7d393aa68fcb.png)

**Comment by IsbetVR** [comment]
En la versión 20.7 de CBP, persiste este error, se desaaprecen los registros de las transacciones, como se puede observar en la pantalla 1 no muestra registros, y en la pantalla 2 se muestran las que he realizado

##### Pantalla 1

![screenshot_57](https://cloud.githubusercontent.com/assets/19142276/16876028/5a102348-4a70-11e6-99dd-861574b2d51e.jpg)

##### Pantalla 2

![screenshot_58](https://cloud.githubusercontent.com/assets/19142276/16876034/61ebc9a0-4a70-11e6-8c92-e625d2ade5b6.jpg)

#### Emulador 

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16876084/90d0b00a-4a70-11e6-9fd3-f73112095505.jpg)

**Comment by camilavaleria** [comment]
En el dia de hoy 18-07-2016, se sigue probando la version 20.7 de CBP y persiste este error.

Emulador de prueba;

![image](https://cloud.githubusercontent.com/assets/18740418/16917757/efae34f0-4cd0-11e6-9643-409cb9607a9d.png)

**Comment by arosiopr** [comment]
@nattyco en la versión 20.9 persiste el error se desaparecen del home las transacciones

**Comment by camilavaleria** [comment]
En la version 20.9.1 de la bitcoin wallet no aparecen las transacciones realizadas en el Home

![image](https://cloud.githubusercontent.com/assets/18740418/17058489/b64c5b1c-4fee-11e6-9d3a-503cd239dee.png)

EMULADOR DE PRUEBA

![image](https://cloud.githubusercontent.com/assets/18740418/17058519/d2afca32-4fee-11e6-8ec1-55be7053a400.png)

**Comment by maydiamc** [comment]
en la version 20.9.1 de bitcoin wallet sigue sucediendo este problema

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/17058809/14138e4a-4ff0-11e6-8d9c-62598515dbc4.png)

**Comment by yolandayancel** [comment]
Prueba 22-07-2016
Caso 631 BITCOIN WALLET-  V 20.9.1
Emulador Genymotion:
Samsung S6 5.1.0 api 22 640dpi

1Borra las transacciones recibidas y las enviadas:

![caso 2](https://cloud.githubusercontent.com/assets/17283358/17059858/31ad7dc6-4ff5-11e6-9e7f-e924e3cc11fc.png)
2 No borro las transacciones de los requests
![caso](https://cloud.githubusercontent.com/assets/17283358/17059773/c818b5c4-4ff4-11e6-87e4-062694f62ccd.png)

**Comment by nattyco** [comment]
@maydiamc @MaviDavsa  verificar este caso nuevamente

**Comment by GeronimoVierma** [comment]
Versión CBP-20.1

Llevo aproximadamente 1 hora y 30 minutos haciendo negociaciones y no se ha presentado el error:
![screenshot_5](https://cloud.githubusercontent.com/assets/19883115/17119958/48d5c216-5297-11e6-934e-893a9a73b40a.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/17120013/92d4cfce-5297-11e6-8757-61a8c474e7ab.png)

**Comment by maydiamc** [comment]
Reabrir el caso @MaviDavsa 
En la versión 22.0 de CBP, este error se esta presentando en la pantalla de Received

Pasos 
-Se recibió una transacción de marielis, la cual se reflejo en la pantalla junto con la del faucet
-el contacto geronimo me envió BTC, llegaron al diferido
-en el momento de reflejarse en el balance actual, se mostró en la pantalla Recived
-la transacción de marielis se desapareció y solo quedo la de Geronimo y el Faucet
-el contacto dianey me hizo un envió de BTC, al pasar al balance actual
-se mostró en la pantalla de Received y se desapareció la transacción de geronimo, quedando solo la de Dianey y la del Faucet

Logcat
En cada capture se muestran las horas de las desapariciones
[log 631.zip](https://github.com/Fermat-ORG/beta-testing-program/files/418901/log.631.zip)

Capture de Pantalla
![screenshot_26](https://cloud.githubusercontent.com/assets/17274154/17678647/fdecc7de-6305-11e6-850d-0f9642c1ce9a.png)
![screenshot_28](https://cloud.githubusercontent.com/assets/17274154/17678650/fff9e5ca-6305-11e6-9b30-b45db93ff5a4.png)
![screenshot_29](https://cloud.githubusercontent.com/assets/17274154/17678653/028c23e8-6306-11e6-93c8-ff8fe17bc4cc.png)
![screenshot_30](https://cloud.githubusercontent.com/assets/17274154/17678657/05150e7c-6306-11e6-9a98-47ce3f3f097d.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17678667/0baae112-6306-11e6-9a1c-20904b836b76.png)

**Comment by nattyco** [comment]
@MaviDavsa  @maydiamc  Lo que entiendo por las capturas de pantallas es que las transacciones se agruparon mal, no desaparecieron como sucedia en el reporte original.
 Necesito saber si por ejemplo en la carptura que dice que Geronimo envio dos transacciones es asi o solo envio una.

**Comment by nattyco** [comment]
@MaviDavsa @maydiamc  se corrigio un problema con el listado de transacciones  verificar en la version 22.2 de la apk

**Comment by marielis-urbina** [comment]
En la versión 22.2 de CBP, no sucede esto en mi emulador

![sent](https://cloud.githubusercontent.com/assets/19353722/17784278/eda39826-6549-11e6-86bc-7c1b57d63322.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17784282/f2b25f64-6549-11e6-937c-c2ef1e580b1d.png)
