### ISSUE TITLE
LPW_Imgen de perfil en drawer cortada

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#632]
#### Nombre pantalla
Drawer

### Nombre de la Aplicación 
LPW

-----

##### Reporte de error: 

version 18.3 de la CBP 
    *En el drawer la imagen de perfil esta cortada por la barra superior del dispositivo
 
![screenshot_2016-06-27-14-35-48](https://cloud.githubusercontent.com/assets/17274154/16394539/97042da2-3c7f-11e6-8844-98a641b5aae1.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16394544/9d59349a-3c7f-11e6-9570-d63043ab5ade.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@IsbetVR  verificar en la version 3.5

**Comment by kmiloxvii** [comment]
Solucionado ya no sucede en la versión 3.5
![perfil_loss](https://cloud.githubusercontent.com/assets/2491042/18954997/6f6b599e-8623-11e6-9212-6259386dff1f.png)


Emulador
Android 4.4.2
Nexus 4
