### ISSUE TITLE
LPW_ Icono de codigo QR cortado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#633]
#### Nombre pantalla
Create external contact

### Nombre de la Aplicación 
LPW

-----

##### Reporte de error: 

Version 18.3 de CBP
   *Al seleccionar agregar un contacto externo, en la pantalla Create external contact, el icono del escanear codigo QR (Barcode Scanner) se ve cortado

![screenshot_2016-06-27-14-34-13](https://cloud.githubusercontent.com/assets/17274154/16394710/5c6da05a-3c80-11e6-9e9f-c9059a206d4e.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16394704/535c6262-3c80-11e6-8424-35fea9c950f9.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  verificar este caso nuevamente

**Comment by sanro14** [comment]
![d](https://cloud.githubusercontent.com/assets/5313324/16542921/5db988d0-408a-11e6-8c55-c88961746a5b.png)
@nattyco resuelto este caso, verificado
