### ISSUE TITLE
CBP_Crypto Broker_titulos pegados a barra superior

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#634]
#### Nombre pantalla
Configuracion de inicio 

### Nombre de la Aplicación 
Crypto Broker

-----

##### Reporte de error: 

Version 18.3 de CBP
   *Al momento de ingresar a la crypto broker por primera vez, se puede ver que en todas las pantallas de la configuracion de inicio, el titulo superior se encuentra pegado a la barra de notificaciones del dispositivo
   
EJEMPLO: OTHERS SETTINGS
![screenshot_2016-06-27-14-01-13](https://cloud.githubusercontent.com/assets/17274154/16394884/34f68928-3c81-11e6-9322-d45914440a91.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16394893/3db02b96-3c81-11e6-9584-afdb50416371.png)

**Comment by maydiamc** [comment]
@nelsonalfo @abicelis

**Comment by abicelis** [comment]
@maydiamc Esto te ocurre en varias / todas las pantallas en tu android? Hemos tenido errores parecidos y no han sido de CBP sino de android-upgrade.

**Comment by maydiamc** [comment]
si bueno en todas las pantalla de la configuracion de inicion de la cryptobroker xq no me sucedio en la cryto customer @abicelis

**Comment by maydiamc** [comment]
solucionado, pero probado desde emulador, de todas maneras cerrrare el caso
