### ISSUE TITLE
Community_Menu de seleccionar identidad de broker o customer

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#635]
#### Nombre pantalla
Community, Select identity

### Nombre de la Aplicación 
Community

-----

##### Reporte de error: 

Version 183 de CBP  
 *La pantalla de selccionar la identidad como broker o customer en las community, no tiene buena visibilidad y es algo confusa, se recomienda hacer un poco menos rectangular y mas cuadrada y centrada en la pantalla, con las letras mejor resaltadas y mejor ubicadas, ademas se recomienda colocar un aviso de seguridad, pensando en que el usuario pueda equivocarse y quiera rectificar

![screenshot_2016-06-27-14-49-49](https://cloud.githubusercontent.com/assets/17274154/16395308/f8d01cc8-3c82-11e6-9ea7-b6a628eac5e8.png)

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

![screenshot_2016-06-08-10-22-44](https://cloud.githubusercontent.com/assets/17274154/16395301/f12abdde-3c82-11e6-8852-b6759bff0d66.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by maydiamc** [comment]
@nelsonalfo @abicelis

**Comment by abicelis** [comment]
@maydiamc las communities se estan arreglando visualmente, pronto las veran bonitas/distintas, incluyendo este dialog negro.

**Comment by maydiamc** [comment]
ahh ok @abicelis excelente.! gracias

**Comment by abicelis** [comment]
@maydiamc revisa la version 18.5!

**Comment by maydiamc** [comment]
listo excelente el nuevo diseño de la community
