### ISSUE TITLE
DAP - Communities - Drawer de Asset Issuer Community

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#638]
#### Nombre pantalla

Drawer de la Asset Issuer Community

### Nombre de la Aplicación 

DAP Version 3
-----

##### Reporte de error: 

   *En la Versión 3 de la DAP, específicamente en el Drawer de la Asset Issuer Community, me aparece sin ningún tipo de información de que es esta Community a la que estoy ingresando. Mi perfil en ese momento es Asset User.

![screenshot_74](https://cloud.githubusercontent.com/assets/19670319/16398891/0ed6fcc6-3c9c-11e6-888e-e04e23d61c3b.png)

------

- Hora:

6:41 pm

- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/335992/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

![nexus 5](https://cloud.githubusercontent.com/assets/19670319/16399016/e4de2a2e-3c9c-11e6-9852-37d27a022b65.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by MaviDavsa** [comment]
@nindriago En algunos sale y en otros no... En mi caso sale AssetUser que es el nombre de la Communitys! aqui no sale nada! o sale en uno o no sale en ninguno...!!

**Comment by RubenSem** [comment]
Versión 3 de la DAP, Asset user Community, Perfil creado en ese momento Asset Issuer

Pasa lo mismo con la diferencia que es en la pantalla de asset user con perfil de asset issuer.

![screenshot_6](https://cloud.githubusercontent.com/assets/19676223/16399214/3693d38a-3c9a-11e6-8e7b-140694889ddd.jpg)

Especificaciones:

![screenshot_5](https://cloud.githubusercontent.com/assets/19676223/16399225/4ac2462a-3c9a-11e6-8252-1c60c7eef74c.jpg)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/336008/logcat.txt)

**Comment by AdryCanonico** [comment]
Se cierra el caso porque es igual al #423
