### ISSUE TITLE
Communities - No reconoce que ya existe una conexión establecida

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#639]
### TKY-ART (v1u7)

-----

##### Reporte de error: 

   *En la "Artist Communuty", tengo una conexión con un artista y pese a que está la conexión establecida entre los usuarios (Pantalla 1), sigue saliendo que no existen, tal como se muestra en la pantalla 2.
   
------
#### Pantalla 1

![screenshot_83](https://cloud.githubusercontent.com/assets/19142276/16422939/250862f0-3d28-11e6-8b34-2da123d0f188.jpg)

#### Pantalla 2

![screenshot_82](https://cloud.githubusercontent.com/assets/19142276/16422952/2f001942-3d28-11e6-9351-a7816136daaf.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16422996/53c78aa8-3d28-11e6-90a1-30e9e588fd29.jpg)

**Comment by darkestpriest** [comment]
@lostwood ¿podrías revisar esto?

**Comment by lostwood** [comment]
ok anotado

**Comment by Hernandezsmanu** [comment]
En la versión v1u8 persiste esto.

**Comment by IsbetVR** [comment]
En la versión v1u10 persiste el error

![screenshot_98](https://cloud.githubusercontent.com/assets/19142276/16472322/2ffa8ea4-3e31-11e6-96a8-7d897deffb27.jpg)

#### Dispositivo de prueba

- [x] Emulador
- Google Nexus 4
- Versión de android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16472346/58865d12-3e31-11e6-9726-b780bfb4144b.jpg)

**Comment by juanaso** [comment]
ahi no sale el reflejo jajaja

**Comment by MaviDavsa** [comment]
@juanaso El problema no es el reflejo acá... Si te das cuenta el problema es que no reconoce que hay una nueva conexión!

**Comment by Hernandezsmanu** [comment]
A mi me muestra lo mismo que no tenemos conexión, pero igual me muestra el reflejo. Versión v1u10 

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/16473361/4a8df512-3e36-11e6-8fd1-bf150545adea.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16473363/4d907dc0-3e36-11e6-8c53-887acfb40f29.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16473366/4fc158e4-3e36-11e6-90da-6b4e616c7c66.png)

**Comment by lostwood** [comment]
ya esta corregido pueden probar en la version 1v11 que esta en el channel

**Comment by Hernandezsmanu** [comment]
Solucionado en la versión v1u11.
