### ISSUE TITLE
Bit Coin Wallet_Settings

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#64]
### Template issue error report

Settings

#### Nombre pantalla

Network

##### Reporte de error: 

   *La ventana pop up de Network no selecciona ninguna opción solo la que esta marcada por defecto, pero no deja seleccionar ninguna otra.

![screenshot_2016-03-07-10-52-11](https://cloud.githubusercontent.com/assets/17273349/13573710/2eee0230-e453-11e5-9a94-c2e715274872.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Apex 2
* Version de Android: 4.4.2

**Comment by nattyco** [comment]
@adryx83 verificar este caso que ya se modifico el settings

**Comment by adryx83** [comment]
Si @nattyco ya este esta solucionado
