### ISSUE TITLE
BITCOIN WALLET - FALTA LINEA EN EL TOOL BAR EN ANDROID 4.1

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#641]
#### Nombre pantalla

CONTACS

### Nombre de la Aplicación 

BITCOIN WALLET 
-----

##### Reporte de error: 

   *En la version 18.3 de CBP la linea en el tool bar de la app en las versiones 4.1. que divide el Contacts de la lista no aparece.seria bueno estandarizar en las dos versiones, Ya que las app tienen que verse igual en todas las versiones de Android ya que en los 5.0 si aparece.

![screenshot_2016-06-24-09-14-49](https://cloud.githubusercontent.com/assets/18584168/16433777/b13cac22-3d55-11e6-87e4-37944eea48e2.png)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16433839/f72c4d00-3d55-11e6-828d-8040e759312b.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by AdryCanonico** [comment]
@nattyco  aun no se ha estandarizado lo que se va a mostrar en la version 20.1, turno tarde.

**Comment by GeronimoVierma** [comment]
En la versión 20.5 de CBP la linea en el tool bar que divide el Contacts de la lista sigue sin aparecer (Android 4.1.1)


![pro](https://cloud.githubusercontent.com/assets/19883115/16822297/6dda722c-4929-11e6-9850-1b3cead88b10.png)


![nexus 4-4 1 1](https://cloud.githubusercontent.com/assets/19883115/16822337/b53c2bec-4929-11e6-9c65-bec2992145c2.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.6 de CBP la linea en el tool bar que divide el Contacts de la lista sigue sin aparecer (telefono fisico): 


![screenshot_2016-07-14-18-30-12](https://cloud.githubusercontent.com/assets/19883115/16858672/87a24a9a-49f6-11e6-85e6-ed12bb5d6f96.png)

Telefono fisico:
![screenshot_2016-07-14-18-31-45](https://cloud.githubusercontent.com/assets/19883115/16858675/92d8fc7e-49f6-11e6-89d6-eeec04b40ccc.png)

**Comment by dorzar1989** [comment]
En la version 20.9.1 De la Bitcoin Wallet esto esta solucionado.

- Screenshot:

![screenshot_38](https://cloud.githubusercontent.com/assets/19670319/17037467/0ccfc2f2-4f5f-11e6-83b2-2efcca1f7c42.png)


- Emulador: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17037471/13017f26-4f5f-11e6-9a40-a1b3f2860a73.png)
