### ISSUE TITLE
BITCOIN WALLET - DESCUENTO MASIVO DE BTC

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#642]
#### Nombre pantalla

Bitcoin Wallet

### Nombre de la Aplicación 

Bitcoin Wallet - CBP Version 18.4
-----

##### Reporte de error: 

   *En la Bitcoin Wallet de la Version 18.4 de la CBP, se realizo un contrato a pesar de que fuese cancelado de un total de 0.025 BTC, en ambas partes tanto el broker como el customer se repitio solo este proceso mas de 20 veces. luego de eso la Bitcoin Wallet me siguio descontando BTC sin ninguna explicacion, se llevaba desde 0.5 btc hasta mas de 1 btc cada 3 min aproximadamente..
   
![screenshot_14](https://cloud.githubusercontent.com/assets/19670319/16459175/f40a8868-3def-11e6-90ee-30cd5082281b.png)

![screenshot_15](https://cloud.githubusercontent.com/assets/19670319/16459182/f9cafe86-3def-11e6-8488-2d53f8214f02.png)

![screenshot_16](https://cloud.githubusercontent.com/assets/19670319/16459213/1494dd9a-3df0-11e6-86eb-97f782f67988.png)

![screenshot_17](https://cloud.githubusercontent.com/assets/19670319/16459225/19807918-3df0-11e6-89f0-58c4adad19a5.png)

![screenshot_18](https://cloud.githubusercontent.com/assets/19670319/16459241/23cc3e34-3df0-11e6-82da-57c56199173b.png)

**## Una de las ultimas capturas que tome.**

![screenshot_28](https://cloud.githubusercontent.com/assets/19670319/16459268/39962568-3df0-11e6-8850-8095671d0717.png)

------

- Hora:

Me empece a dar cuenta desde las 10:30 am

- LogCat:

[Logcat Door.txt](https://github.com/Fermat-ORG/beta-testing-program/files/339636/Logcat.Door.txt)

OJO: El Logcat original pesa aproximadamente 110 MB, lo que hice, por recomendacion, fue copiar varias lineas finales del archivo para poder montar el error. 

#### Dispositivo desde donde se realizo la prueba

![screenshot_27](https://cloud.githubusercontent.com/assets/19670319/16457031/196619b8-3de8-11e6-8f3b-60b71bd759cd.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@MaviDavsa  este caso lo tienen que ver los responbles de CBP ya que las transacciones se estan haciendo en conjunto para ver donde esta el error

**Comment by MaviDavsa** [comment]
@nelsonalfo Plss chequea esto!
