### ISSUE TITLE
CBP - FERMAT NO RESPONDE AL ACEPTAR NEGOCIACION

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#643]
#### Nombre pantalla
Broker Wallet

### Nombre de la Aplicación 
CBP

-----

##### Reporte de error: 

   *Al presionar la solicitud de negociación Fermat deja de responder y luego se cierra la aplicación (pantalla 1). Cuando trato de abrir nuevamente la aplicación no me lo permite de igual forma me da la alerta de Fermat no responde   (pantalla 2)

------
Pantalla 2
![screenshot_24](https://cloud.githubusercontent.com/assets/19807906/16505931/6597900e-3eed-11e6-9bd6-6db803ed732c.png)

Pantalla 1
![screenshot_25](https://cloud.githubusercontent.com/assets/19807906/16505932/6599b6f4-3eed-11e6-8abd-30976928b400.png)
![screenshot_26](https://cloud.githubusercontent.com/assets/19807906/16506089/2d5df164-3eee-11e6-8b1a-4656396a985d.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/342483/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

**Comment by sanro14** [comment]
@abicelis

**Comment by RubenSem** [comment]
Me pasa exactamente lo mismo, al presionar la negociación se traba el apk.

![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/16508422/848af6e0-3efc-11e6-9cd8-04965f78dac6.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/19676223/16508456/e4a444f0-3efc-11e6-8d14-ff3057ffe1f2.jpg)

Especificaciones del teléfono:
![screenshot_5](https://cloud.githubusercontent.com/assets/19676223/16508447/c943340a-3efc-11e6-8a42-bebd68b9d352.jpg)

**Comment by GeronimoVierma** [comment]
En la versión 18.8 tengo el mismo problema, al entrar a la negociación a llenar los campos del contrato y darle confirmar sale mensaje de error:

![iver](https://cloud.githubusercontent.com/assets/19883115/16523395/05c67ef8-3f6d-11e6-8463-d2efa34b294d.png)

![ivers](https://cloud.githubusercontent.com/assets/19883115/16523401/0ba428f2-3f6d-11e6-8b30-5676beb54d0c.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/343568/logcat.txt)

**Comment by yalayn** [comment]
Yo trabajare en este issue.

**Comment by franklinmarcano1970** [comment]
@yalayn manuel tambien va a revisar ese caso cuadren para que el lo termine o revisen que faltan.

**Comment by yalayn** [comment]
Ya corregí este issue, debe estar disponible para la próxima version

**Comment by yalayn** [comment]
Hola @sanro14, @JeanFranco498, @RubenSem, @GeronimoVierma por fa confirmar si este issue se corrigió realmente.
Saludos.

**Comment by RubenSem** [comment]
En la versión 19.2 cbp, ya no sucede este problema. @yalayn

**Comment by yalayn** [comment]
Fino @RubenSem. Gracias.
