### ISSUE TITLE
BITCOIN WALLET - ERROR AL EDITAR LA FOTO DEL PERFIL

### ISSUE THREAD

**Issue by LilianFlores** [Fermat-ORG/beta-testing-program#644]
#### Nombre pantalla

Identity Manager

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   En la versión 18.6, al editar el usuario y querer cambiar la foto del perfil, me aparece para cortar la foto de forma rectangular (pantalla 1) y no cuadrada como debería, intenté modificar el rectángulo (cambiar el tamaño) pero no se puede. Por lo tanto, al guardar los cambios, sale estirada (pantalla 2). Quiero agregar que la foto que seleccioné ya era cuadrada, que la opción de rotar sí funciona bien y que al querer cambiarla de nuevo no me dejó, tuve que salir de la Bitcoin wallet y volver a entrar.

   **Actualización:** En la versión 18.7 también ocurre lo mismo. 

![screenshot_2016-06-30-18-00-10](https://cloud.githubusercontent.com/assets/19652611/16506267/12aec4ae-3eeb-11e6-973f-2d8673624458.png)
![screenshot_2016-06-30-18-01-44](https://cloud.githubusercontent.com/assets/19652611/16506275/1d81e03c-3eeb-11e6-8f6d-23624d32d80e.png)

------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2016-06-13-20-51-08](https://cloud.githubusercontent.com/assets/19652611/16506108/10dcdf22-3eea-11e6-9e29-1d731231b372.png)

- [x] Teléfono Físico

**Comment by LilianFlores** [comment]
@sanro14

**Comment by sanro14** [comment]
@nattyco

**Comment by LilianFlores** [comment]
En la versión 18.8 este error persiste tanto en el dispositivo anterior (Huawei) como en un Samsung Galaxy mini s3. Lo probé ahora tomando fotografía con la cámara y el error me varió un poco. Ahora la pantalla de edición sale muy pequeña y centrada (pantalla 1). El rectángulo puede disminuirse de tamaño pero no puede modificarse a cuadrado aún, entonces al guardar cambios la foto sigue saliendo estirada.

Sin embargo, cuando voy a verla en la barra de la Bitcoin Wallet, no solo sale estirada sino que también se muestra pixeleada **y esto repercute directamente en el error #590** 

![img-20160701-wa0027](https://cloud.githubusercontent.com/assets/19652611/16527008/0805e3e6-3f7e-11e6-8ff4-7a554bba4302.jpg)

**Dispositivo desde donde se realizo la prueba**

![img-20160701-wa0023](https://cloud.githubusercontent.com/assets/19652611/16526945/a7abdb72-3f7d-11e6-909e-c5c32d8f07de.jpg)

**Comment by IsbetVR** [comment]
En la versión 19.5 de CBP, ya no sucede este error, la pantalla de edición es más amplia

![screenshot_14](https://cloud.githubusercontent.com/assets/19142276/16593314/bb284748-42b2-11e6-8ba4-d8778324097d.jpg)

- [x] Emulador
- Google Nexus 4
- Versión de android 4.3
- 320 dpi
- API 18 768x1280

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16593391/1329fb12-42b3-11e6-9da2-b09a7bc8d330.jpg)

**Comment by AdryCanonico** [comment]
@LilianFlores  en la version 19.5 ya se corrigió el problema en el teléfono físico.

**Comment by IsbetVR** [comment]
Closed #644
