### ISSUE TITLE
CBP Se repite el mensaje Set Time

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#647]
### Nombre de la Aplicación: CBP
-----
##### Reporte de error: 

   *Cada vez que entro en la Broker Wallet, tengo que actualizar el Set Time

##### Screenshot o Capture de pantalla:

![time](https://cloud.githubusercontent.com/assets/19353722/16521882/d4732396-3f63-11e6-97db-6aec156eb9a5.png)

##### Pasos exactos para reproducir el error:

Al regresar de las Communities de aceptar a mis contactos, me voy a la Crypto Broker para verificar si tengo alguna negociación, cada vez que entro en la Broker Wallet, tengo que editar el Set Time

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/343483/logcat.txt)

------
#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/16522103/62b28cae-3f65-11e6-952f-003e2137cd83.png)

**Comment by abicelis** [comment]
@marielis-urbina revisa la ultima version 18.8, ahi esta corregido.

**Comment by marielis-urbina** [comment]
Efectivamente en la versión 18.8 no se repite este error, @abicelis
