### ISSUE TITLE
Communities - Muestra conexiones no establecidas entre usuarios

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#648]
### CBP (Versión v19.2) 

-----

##### Reporte de error: 

   *Al tener perfil de "Customer" y meterme en la "Crypto Broker Community" para establecer las conexiones, en "Browser" (Pantalla 1) me salen conexiones con usuarios con los cuales no he establecido ninguna, sólo a un usuario le envié connection request, el cual se puede observar en la pantalla 2.

##### Pantalla 1

![1 2](https://cloud.githubusercontent.com/assets/19142276/16542272/12fc4d4c-4070-11e6-8f42-fd74f10b7f13.jpg)

##### Pantalla 2

![2 2](https://cloud.githubusercontent.com/assets/19142276/16542274/2ccd9172-4070-11e6-9737-21a66179a80b.jpg)

##### Pasos exactos para reproducir el error:

- Hice el perfil de "Customer"
- Configuré el Crypto Customer (Wallets)
- Entré a las "Communities / Crypto Broker Community"
- Envié un connection request a un broker (Roy2, mostrado en la pantalla 1 y 2)
- Salí de las comunities para buscarlo en el "Broker List" y al ver que no aparecía me devolví a las  "Communities / Crypto Broker Community" y ahí me apareció el error reportado, mostrando que tenía más conexiones en el "browser" cuando en realidad no existen tal como se muestra en connections

##### Archivo Logcat.txt: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/344711/logcat.txt)

------

#### Dispositivo desde donde se realizó la prueba

- [x] Emulador
- Google Nexus 4
- Versión de android: 5.0.0
- 320 dpi
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16542313/86f41f30-4071-11e6-83da-a20ab3affcaa.jpg)

**Comment by IsbetVR** [comment]
@furszy

**Comment by IsbetVR** [comment]
@abicelis

**Comment by dorzar1989** [comment]
En la Versión 19.2 de la CBP aun pasa esto

Lo que hice fue:
 - Entrar a la Community de los Broker (Soy Customer)
 - Refrescar para ver si aparecen nuevos usuarios
(En ese momento es que se me actualizaron las supuestas conexiones con esos dos usuarios que yo nunca hice)

![screenshot_59](https://cloud.githubusercontent.com/assets/19670319/16564443/7a22a51e-41d5-11e6-8286-dbbf7bd1d9ba.png)

![screenshot_58](https://cloud.githubusercontent.com/assets/19670319/16564715/0a9e443a-41d7-11e6-967d-37b3395de50e.png)


![screenshot_60](https://cloud.githubusercontent.com/assets/19670319/16564447/7f4e3b02-41d5-11e6-94e1-e886db781464.png)

 

MOVIL

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16564453/8ed4f548-41d5-11e6-9e0c-2d222cfd26b5.png)


ULTIMA PARTE DEL LOGCAT : 

[Logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/346503/Logcat.txt)

**Comment by abicelis** [comment]
@IsbetVR @dorzar1989 ok, dejenme revisar esto
