### ISSUE TITLE
Communities - Notificaciones para conexión se ocultan

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#649]
### Nombre pantalla

P2P Chat Community

### Nombre de la Aplicación 

Chat
-----

##### Reporte de error: 

  Si se tiene mas de una notificación en la pantalla "notifications" al momento de aceptar cualquier connection request, vuelve a la pantalla "notifications" pero oculta las demás que tengo pendientes y debo actualizar para que salgan nuevamente, esto debo hacerlo cada vez que quiera aceptar las otras connection request.

##### Screenshot o Capture de pantalla:

![screenshot_2016-07-04-11-38-25](https://cloud.githubusercontent.com/assets/5313335/16568636/a69f23ae-41fa-11e6-804c-0accd144f6ae.jpg)

![screenshot_2016-07-04-11-38-30](https://cloud.githubusercontent.com/assets/5313335/16568637/a8c070c0-41fa-11e6-9169-2e794b395296.jpg)

![screenshot_2016-07-04-11-38-33](https://cloud.githubusercontent.com/assets/5313335/16568639/ab64aaf8-41fa-11e6-84be-06d6564196af.jpg)

##### Pasos exactos para reproducir el error:

1. Entrar a la pantalla notifications
2. Tener mas de una notificación
3. Hacer click en cualquier notificación y presionar Ok.
4. En este paso vuelve a la pantalla notifications pero se encuentra vacía, no muestra las demás.
5. Actualizar la pantalla para que me salgan las notificaciones pendientes.
6. Repetir del paso 3 al 5 hasta haber aceptado todas las notificaciones.

------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/5313335/16568643/b784532e-41fa-11e6-8723-fec20976a9ab.jpg)

**Comment by AdryCanonico** [comment]
@Hernandezsmanu  En la version 19.5 ya no sucede el error. Se va a proceder a cerrar el caso.
