### ISSUE TITLE
Bit Coin Wallet_ Home

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#65]
#### Nombre pantalla
Home

##### Reporte de error: 

   *El error que presenta la aplicación en esta oportunidad es en cuanto al botón de Balance (es la circunferencia con la cantidad de bitcoin), una vez que lo presiono aparece la pantalla de "Send to contact" en la cual no me aparece ningun contacto sino que solo me aparece el error "Ooopss! recovering from system error", posteriormente al tratar de volver al Menú de la Wallet me dio un pantallazo en la cual la única opción fue cerrar por completo la aplicación. 

![4](https://cloud.githubusercontent.com/assets/17273005/13573950/36bd76d4-e454-11e5-85a0-1ba9d57d4a9f.JPG)
![5](https://cloud.githubusercontent.com/assets/17273005/13573971/50077964-e454-11e5-887a-83c82087abd0.JPG)
![3](https://cloud.githubusercontent.com/assets/17273005/13573977/55899bb0-e454-11e5-8210-7f2fe949418f.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: Android 5.0

**Comment by nattyco** [comment]
@MaviDavsa boton de balance te referis al icono de la barra superior con el simbolo de Bitcoin?
Cuando lo tocaste directamente te mostro el error ?

**Comment by MaviDavsa** [comment]
@nattyco Si nena me mostraba error! Pero ya no! lo acabo de ver si y abre normal!
