### ISSUE TITLE
CHAT-Opción de Copiar cuando el mensaje es extenso

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#650]
#### Nombre pantalla
Mensajes de chat
### Nombre de la Aplicación 
Chat 
-----

##### Reporte de error: 

   * @RoyGF Al darle la opción de Copiar a un mensaje bien sea enviado o recibido sale una ventana modal con la información del mensaje completo, debería salir solo un resumen del mensaje, o unas lineas de el mismo seguido de repente de (...) o simplemente la palabra Copied.

##### Screenshot o Capture de pantalla:

![screenshot_3](https://cloud.githubusercontent.com/assets/5313324/16568929/236e5de8-41fe-11e6-8816-563b17963085.png)

 *Agregar las capture del error en el emulador o teléfono donde se produjo. 

##### Pasos exactos para reproducir el error:

 *Pasos:
- Entro a la pantalla de mensajes recibidos.
- Le doy para copiar el mensaje.
- Muestra el mensaje copiado pero todo el texto del mismo.

#### Dispositivo desde donde se realizo la prueba
![dispositivo](https://cloud.githubusercontent.com/assets/5313324/16568967/b0369ef2-41fe-11e6-8317-a0ae30879d31.png)
 
------
- [x] Emulador

**Comment by sanro14** [comment]
Aún persiste el error en la versión 19.5 de CBP

**Comment by josejcb** [comment]
Hoy lo tendran, ya esta solucionado

**Comment by arosiopr** [comment]
Solucionado en la 19.8
