### ISSUE TITLE
Bitcoin Wallet - balance en btc sale montado

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#651]
### CBP Versión v19.2

-----

##### Reporte de error: 

   *Cuando en el balance en btc el monto tiene más de 3 cifras en los decimales, se baja el dígito, tal como lo muestro en la pantalla 1, le doy click para ver la cifra en bits (pantalla 2) y no los monta, vuelvo a darle click para volver al formato de btc, y baja el tamaño de la cifra (pantalla 3) con respecto a cuando ingreso a la bitcoin wallet por primera vez. Salgo de la bitcoin wallet y vuelvo a ingresar y muestra nuevamente la cifra con los dígitos montados.

##### Pantalla 1

![screenshot_27](https://cloud.githubusercontent.com/assets/19142276/16569177/3fb043b0-4201-11e6-82b2-276fea7f8d57.jpg)

##### Pantalla 2

![screenshot_28](https://cloud.githubusercontent.com/assets/19142276/16569181/46bdd852-4201-11e6-80cc-da5a95e3635f.jpg)

##### Pantalla 3

![screenshot_29](https://cloud.githubusercontent.com/assets/19142276/16569187/50734256-4201-11e6-8aa6-fc708d1cb883.jpg)

-----

##### Pasos exactos para reproducir el error:

1. Inicialmente tenia en el balance de la bitcoin wallet los 50 btc que solicito a la regtest 
2. Empecé a realizar transacciones con otros usuarios para verificar como iba funcionando la bitcoin wallet
3. Al manejar cifras con varios decimales y que se empezó a sumar/restar en el balance, fue que se montaron los dígitos
4. Le doy click para que muestre en bits y no los monta
5. Vuelvo a darle click para volver al balance en btc y cambia el tamaño de la cifra con respecto a como me lo muestra cuando entro a la aplicación
6. Salgo y entro a la bitcoin wallet y vuelven a aparecer montados

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Android 5.0.0
- 320 dpi 
- API 21 768x1280

![google nexus 4 - 5 0 0](https://cloud.githubusercontent.com/assets/19142276/16569282/9fb52a04-4202-11e6-9d1b-e5db2da2b31f.jpg)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by IsbetVR** [comment]
En la versión 19.5 de CBP, ya no sucede este errior.

**Comment by IsbetVR** [comment]
Close #651

**Comment by dorzar1989** [comment]
En la version 19.5 de CBP aun sucede este error.

![screenshot_22](https://cloud.githubusercontent.com/assets/19670319/16623592/8c9ff424-436c-11e6-845d-2ec15aeb9b85.png)


- MOVIL:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16623602/9a455254-436c-11e6-99f0-90cdefe65ead.png)

**Comment by IsbetVR** [comment]
En algunos dispositvos persiste el error, se reabre el issue

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso     BITCOIN WALLET-  CBP V 20.1
Emulador Genymotion:
Nexus 5 5.0.0 api 21 480dpi
Hora aproximada del logcat: 4:32pm
[logcat BTC salta.txt](https://github.com/Fermat-ORG/beta-testing-program/files/355076/logcat.BTC.salta.txt)

Ocurre lo reportado.
![btc salta linea siguiente](https://cloud.githubusercontent.com/assets/17283358/16700923/c0565582-452a-11e6-98b3-73386cfbbbfb.png)

**Comment by arosiopr** [comment]
En la version 20.4 de CBP se soluciono el error en mi dispositivo

![screenshot_98](https://cloud.githubusercontent.com/assets/5313326/16767363/0b158dc4-480d-11e6-90a4-f339f0c01952.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16767366/1059f07c-480d-11e6-9421-bda3b3a1749e.png)

**Comment by yolandayancel** [comment]
Prueba 12-07-2016
Caso 651 BITCOIN WALLET- CBP V 20.4
Emulador Genymotion:
Nexus 5 5.0.0 api 21 480dpi
Solucionado.
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/16768526/b05c847c-4812-11e6-98dd-71ec18e2ec19.png)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #651
