### ISSUE TITLE
CHAT - NO TIENE FUNCIÓN EL BOTON EN LA FOTO DE LOS CONTACTOS 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#652]
#### Nombre pantalla

FOTOS DE CONTACTO 

### Nombre de la Aplicación 

CHAT

-----

##### Reporte de error: 

   *Al momento de pulsar el botón debajo de la foto no tiene función. 

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-07-04-16-09-40](https://cloud.githubusercontent.com/assets/18584168/16569296/c8cdff06-4202-11e6-903f-6e31b1c38492.png)

##### Pasos exactos para reproducir el error:

 *Al dejar presionado las fotos de los contactos, esta abre mas grande, debajo de ella esta un botón de mensajes pero no tiene función.

##### Inserta Archivo aLogcat: 

 *No lo tengo
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16569321/1263b8a4-4203-11e6-8280-e34dca6c43af.png)

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by AdryCanonico** [comment]
@RoyGF en la version 19.5 de CBP aun no tiene la función.

**Comment by josejcb** [comment]
Solucionado. hoy lo tendran.

**Comment by arosiopr** [comment]
Solucionado en la versión 19.8
