### ISSUE TITLE
Crypto Broker - problemas con los checkbox

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#653]
Nombre pantalla

SELECT EARNING WALLETS

Nombre de la Aplicación 

CBP version 19.2

Reporte de error: 

Al momento de configurar la crypto broker, en la pantalla SELECT EARNING WALLETS y seleccionar las diferentes wallets:

1. Al momento de seleccionar el checkbox abre la ventana para seleccionar el tipo de wallet
![select earning wallets 1](https://cloud.githubusercontent.com/assets/2491042/16570177/05fb6efe-4217-11e6-858c-15f05cf3e1a8.png)

![select earning wallets 2](https://cloud.githubusercontent.com/assets/2491042/16570181/2c8c4336-4217-11e6-924c-0a8ff1762910.png)

2. No se selecciona ninguna wallet, pero de igual manera el checkbox queda seleccionado.
 
![select earning wallets 3](https://cloud.githubusercontent.com/assets/2491042/16570204/87ac6cc8-4217-11e6-830c-bf68d3ce1b5f.png)

  

 
 

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![model phone](https://cloud.githubusercontent.com/assets/2491042/16570338/8a703456-4219-11e6-8249-37f70d60eb48.png)

**Comment by abicelis** [comment]
@kmiloxvii ok, dejame revisar

**Comment by abicelis** [comment]
@kmiloxvii listo, revisa la proxima version de CBP que salga (19.6 creo)

**Comment by RubenSem** [comment]
Me pasa algo parecido, pero a mi me marca las wallet bien, pero si quiero cambiarlas allí mismo (desmarcando y volviendo a marcar para que me deje elegir) no me salen las wallet y se marca la casilla.

![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/16634832/8d4a7062-439d-11e6-9ba2-54f7de02a40d.jpg)

Versión de cbp: 19.7

Especificaciones del emulador: 
![screenshot_2](https://cloud.githubusercontent.com/assets/19676223/16634845/9af16194-439d-11e6-9480-35a20bd065d4.jpg)

**Comment by abicelis** [comment]
@RubenSem reviso y te digo

**Comment by IsbetVR** [comment]
Este error persiste en la versión v19.8 de CBP.

**Comment by wendyduran90** [comment]
El error persiste en la version 19.9 

En un comienzo funciona perfecto, al intentar cambiar las wallets falla y queda el checkbox seleccionado pero no sale el dialog para seleccionar la wallet



![error_check_box](https://cloud.githubusercontent.com/assets/20212920/16666326/20d82740-4455-11e6-9eff-8760c5191191.png)

**Comment by kmiloxvii** [comment]
El error persiste en la version 19.9

En un comienzo funciona perfecto, luego de intentar cambiar la wallet falla queda el checkbox seleccionado pero nunca aparece el dialog para seleccionar la wallet 

![error_check_box](https://cloud.githubusercontent.com/assets/2491042/16666598/6ff8b9f6-4456-11e6-9175-88ae3a81ffd2.png)

**Comment by sanro14** [comment]
@abicelis

**Comment by abicelis** [comment]
@sanro14 @IsbetVR @kmiloxvii Ok, dejenme revisar

**Comment by MaviDavsa** [comment]
El error sigue en la versión 20.1... La prueba es desde los teléfonos físicos. 

![screenshot_2016-07-08-09-56-42](https://cloud.githubusercontent.com/assets/17273005/16689742/6c818892-44f2-11e6-91b4-2349014a7b01.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16689775/95ec0072-44f2-11e6-9505-40f6188ce282.jpg)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso      CBP V 20.1
Emulador Genymotion:
Nexus 5 6.0.0 api 23 420dpi
Hora aproximada del logcat:
[logcat 653.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354403/logcat.653.txt)

En este emulador no ocurre lo reportado.
![caso653](https://cloud.githubusercontent.com/assets/17283358/16690088/2b608a6e-44f4-11e6-8310-103b1ca157b0.png)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso 653     CBP V 20.1
Emulador Genymotion:
Nexus 5 5.1.0 api 22 480dpi
Hora aproximada del logcat: 11:41am
[logcat653 1.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354605/logcat653.1.txt)
Ocurre lo mismo reportado.No se selecciona ninguna wallet, pero de igual manera el checkbox queda seleccionado.
![caso 653 1](https://cloud.githubusercontent.com/assets/17283358/16693022/4aec0e32-4501-11e6-9c6d-8425ea1dd639.png)

**Comment by IsbetVR** [comment]
En la versión 20.2 CBP persiste el error

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16730424/ef18e75a-4740-11e6-85fe-d6d52a55fed7.jpg)

**Comment by abicelis** [comment]
@IsbetVR @yolandayancel @MaviDavsa @sanro14 Prueben la version 20.4, ahi debera estar el vis de lo ultimo que reportan, me avisan cualquier cosa!

**Comment by IsbetVR** [comment]
En la versión 20.4 de CBP corregido este error, los check no se quedan seleccionados al querer cambiar las wallets.
Gracias @abicelis ;)

![s](https://cloud.githubusercontent.com/assets/19142276/16750353/33a7b17c-479f-11e6-952a-2061d919ed64.jpg)

#### Probado en Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16750374/50a56be8-479f-11e6-934d-85615f2918aa.jpg)

**Comment by IsbetVR** [comment]
Closed #653
