### ISSUE TITLE
CBP - Crypto Broker Wallet - Crash al seleccionar una Cash Wallet en API 23

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/beta-testing-program#655]
### Nombre de la Aplicación 

Crypto Broker Wallet

-----

##### Reporte de error: 

   * La aplicacion deja de responder al seleccionar una cash wallet. el error solo ocurre en la API 23.

##### Video del Error:

 * https://youtu.be/nVBfQkPipqQ

##### Inserta Archivo aLogcat: 

 * `07-05 13:16:55.921 2452-2452/? W/System.err: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.bitdubai.fermat_android_api.layer.definition.wallet.views.FermatCheckedTextView
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:378)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.ArrayAdapter.getDropDownView(ArrayAdapter.java:448)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.Spinner$DropDownAdapter.getDropDownView(Spinner.java:963)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.Spinner$DropDownAdapter.getView(Spinner.java:959)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.Spinner.measureContentWidth(Spinner.java:833)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.Spinner$DropdownPopup.computeContentWidth(Spinner.java:1194)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.Spinner$DropdownPopup.show(Spinner.java:1220)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.Spinner.performClick(Spinner.java:758)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.support.v7.widget.AppCompatSpinner.performClick(AppCompatSpinner.java:424)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-05 13:16:55.921 2452-2452/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-05 13:16:55.921 2452-2452/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-05 13:16:55.921 2452-2452/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-05 13:16:55.921 2452-2452/? W/System.err: Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.bitdubai.fermat_android_api.layer.definition.wallet.views.FermatCheckedTextView
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-05 13:16:55.921 2452-2452/? W/System.err: 	... 18 more
07-05 13:16:55.921 2452-2452/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
07-05 13:16:55.921 2452-2452/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
07-05 13:16:55.921 2452-2452/? W/System.err: 	... 21 more
07-05 13:16:55.921 2452-2452/? W/System.err: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x3/d=0x57f "res/color/primary_text_disable_only_material_dark.xml" a=1 r=0x1060101}
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.content.res.TypedArray.getColor(TypedArray.java:447)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.TextView.<init>(TextView.java:738)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.CheckedTextView.<init>(CheckedTextView.java:83)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.CheckedTextView.<init>(CheckedTextView.java:79)
07-05 13:16:55.921 2452-2452/? W/System.err:     at android.widget.CheckedTextView.<init>(CheckedTextView.java:75)
07-05 13:16:55.921 2452-2452/? W/System.err:     at com.bitdubai.fermat_android_api.layer.definition.wallet.views.FermatCheckedTextView.<init>(FermatCheckedTextView.java:26)
07-05 13:16:55.921 2452-2452/? W/System.err: 	... 23 more
07-05 13:16:55.927 2452-2457/? I/art: Debugger is no longer active`
 
  
------

#### Dispositivo desde donde se realizo la prueba 

![screenshot from 2016-07-05 13 26 05](https://cloud.githubusercontent.com/assets/16577032/16593616/1c5c026a-42b4-11e6-9e1d-193a23a9d019.png)

![screenshot from 2016-07-05 13 27 21](https://cloud.githubusercontent.com/assets/16577032/16593636/36c8a6ee-42b4-11e6-9b3c-b86b8945aafb.png)

- [x] Emulador

**Comment by MaviDavsa** [comment]
@franklinmarcano1970 @nelsonalfo

**Comment by yolandayancel** [comment]
Prueba 07-07-16
Caso 655 CBP 19.9
Nexus 5 6.0.0 Api 23 420dpi
En este emulador ocurre lo reportado, al escoger la cash, se congela y aparece el recuadro de Fermat
![caso 655](https://cloud.githubusercontent.com/assets/17283358/16666965/f14360f0-4457-11e6-9e97-6981de4995ca.png)
[logcat caso 655.txt](https://github.com/Fermat-ORG/beta-testing-program/files/352902/logcat.caso.655.txt)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso 655     CBP V 20.1
Nexus 5 6.0.0 api23 420dpi
hora aproximada: 8:47am logcat
[logcat655.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354223/logcat655.txt)

En este emulador, corregido el  error al escoger la cash wallet.
![caso 655](https://cloud.githubusercontent.com/assets/17283358/16687829/c82b5ccc-44e8-11e6-9381-b706e70a72c7.png)

**Comment by IsbetVR** [comment]
En al versión 20.1 de CBP Está sucediendo lo mismo en la API 18

Se "cuelga" la apk cuando estoy tratando de configurar la crypto broker y me saca de una vez.

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16688117/678d1f20-44ea-11e6-9ca0-36e1252ef798.jpg)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso 655 CBP V 20.1
Nexus 5 6.0.0 api23 420dpi
hora aproximada: 9:48am logcat
[logcat no deja crear cuenta.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354372/logcat.no.deja.crear.cuenta.txt)

En este emulador deja seleccionar la cash, pero la Bank no deja agregar los datos aparece el recuadro siguente:
![no deja crear cuenta](https://cloud.githubusercontent.com/assets/17283358/16689553/7ce7259e-44f1-11e6-96f6-c6984a83b236.png)

**Comment by maydiamc** [comment]
en la version 20.1 de cbp no sucede ese problema

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16689676/167b6f94-44f2-11e6-9853-6e84a6945cce.png)

**Comment by GeronimoVierma** [comment]
Prueba 11-07-2016
CBP V 20.2
hora aproximada: 8:30 am
API22

Al seleccionar las wallets (Crypto, Cash, Bank) y pulsar Next Step la aplicación deja de responder:

![nickityy](https://cloud.githubusercontent.com/assets/19883115/16730813/f840b75c-4742-11e6-8172-e6d780e22e0d.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16730980/cab237d8-4743-11e6-8311-a6c5cf98e04c.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357088/logcat.txt)

**Comment by sanro14** [comment]
Solucionado.
