### ISSUE TITLE
CBP-CRYPTO CUSTOMER-ERROR EN TITULO DE VENTANAS EMERGENTES

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#657]
#### Nombre pantalla 

START NEGOTIATION

### Nombre de la Aplicación 

CBP

-----

##### Reporte de error: 

   *Al iniciar una nueva negociación e ingresar el monto en el paso 3 AMOUNT TO BUY, en la ventana emergente sale el nombre mal, sale la palabra Amount to pay. Igual sucede con el 4 AMOUNT TO PAY a lo que se abre la ventana emergente sale el texto Amount to Buy, están intercambiados.

##### Screenshot o Capture de pantalla:

![screenshot_53](https://cloud.githubusercontent.com/assets/5313326/16596814/976d36ae-42c3-11e6-8ecc-3d037321189c.png)

![screenshot_54](https://cloud.githubusercontent.com/assets/5313326/16596824/a08a9c7c-42c3-11e6-9146-7fc1c403d497.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a hacer una negociación
2. Dar clic en el paso 3 AMOUNT TO BUY para ingresar monto
3. Al abrir la ventana emergente sale el nombre Amount to pay
5. Dar clic en el paso 4 AMOUNT TO PAY para ingresar el monto
6. Al abrir la ventana emergente sale el nombre Amount to buy
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

320dpi

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16597220/cb364f5a-42c5-11e6-84ab-4f0c2b53d6a0.png)

**Comment by arosiopr** [comment]
@IsbetVR

**Comment by IsbetVR** [comment]
@nelsonalfo

**Comment by abicelis** [comment]
@arosiopr Dejame revisar esto y te aviso

**Comment by arosiopr** [comment]
en la versión 19.9 de cbp se mantiene el error

**Comment by marielis-urbina** [comment]
En la versión 20 ya no sucede este error 

Dispositivo desde donde se realizo la prueba

 Emulador
![samsung](https://cloud.githubusercontent.com/assets/19353722/16674357/50cf4d40-4485-11e6-8525-06561b47fae8.png)

**Comment by arosiopr** [comment]
en la version 20.1 de CBP en el paso 3 sigue saliendo en la ventanan emergente el amount to pay. en el 4 si sale correcto en la ventana emergente el titulo. @MaviDavsa  reabrir por favor

**Comment by IsbetVR** [comment]
Se reabre el caso, error persiste en versión 20.1 de CBP

**Comment by arosiopr** [comment]
se soluciono este error en la version 20.3 de CBP @IsbetVR

**Comment by IsbetVR** [comment]
Closed #657
