### ISSUE TITLE
CBP_crypto customer_ contrato en espera y expirado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#658]
#### Nombre pantalla
HOME

### Nombre de la Aplicación 
Crypto customer

----

##### Reporte de error: 

   *en el contrato aparece esperando por el broker y al broker le sale que confirmo todas las opciones, ademas se envio una notificacion de expiracion de contrato, y el contrato se mantiene en la pestaña de contrato, en stand by, pero no se puede modificar nada en el

##### Screenshot o Capture de pantalla:

 
![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/16596877/edf6d174-42c3-11e6-8e98-35f43e4661a0.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/17274154/16596891/ffd8a110-42c3-11e6-8933-88f28187e31f.png)
![manu](https://cloud.githubusercontent.com/assets/17274154/16596894/06b0951a-42c4-11e6-851d-b34814a929ae.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/16596906/18c20ff4-42c4-11e6-8abb-38afb1d1a7a2.png)

##### Pasos exactos para reproducir el error:

 *hacer una negociacion, confirmar el primer paso como customer y se quedo en espera por el broker y al broker no le sale que debe confirmar mas pasos.

  ------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16596969/666ab684-42c4-11e6-99bd-4b6205ad125c.png)

**Comment by maydiamc** [comment]
@nelsonalfo @abicelis
19.5 de CBP

**Comment by JeanFranco498** [comment]
En la versión CBP 19.9 pasa algo parecido pero esta vez se queda en la pestaña negociaciones. Y a pesar de que llego la notificación de que se ha creado un nuevo contrato, en la pestaña correspondiente no hay nada. 

 
![screenshot_2](https://cloud.githubusercontent.com/assets/19807906/16665922/4fe6055e-4453-11e6-9900-47c751ff1ebd.jpg)


![screenshot_4](https://cloud.githubusercontent.com/assets/19807906/16665991/b363148c-4453-11e6-864a-985a6c8e613f.jpg)


![screenshot_5](https://cloud.githubusercontent.com/assets/19807906/16666037/e3e128e2-4453-11e6-8443-4073557ac633.jpg)

**Comment by yalayn** [comment]
Hola @JeanFranco498 no tienes el logCat de este caso? Como quedo en el dispositivo del customer? en el mismo estado?

**Comment by JeanFranco498** [comment]
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/352923/logcat.txt)

**Comment by arosiopr** [comment]
@IsbetVR esto ya no ocurre en la versión 20.3 de CBP

**Comment by sanro14** [comment]
Solucionado.

**Comment by IsbetVR** [comment]
En la versión 20.3 de CBP. Tenía perfil de Broker. La negociación pasó a CONTRACTS, y allí se quedó en Espera por el Customer (Pantalla 1).. En el caso del Customer, confirmó el "Payment delivery", pero igual le decía "Esperando por el Customer", como si no hubiese confirmado (Pantalla 2 y 3) Hasta que expiró y desapareció el contrato.

#### Pantalla 1

![screenshot_23](https://cloud.githubusercontent.com/assets/19142276/16744377/d0b0d4ba-477e-11e6-9b8b-38a4f8d4a0b4.jpg)

#### Pantalla 2

![1](https://cloud.githubusercontent.com/assets/19142276/16744662/156191b6-4780-11e6-8c86-2d4ee9fe9e66.png)


#### Pantalla 3

![2](https://cloud.githubusercontent.com/assets/19142276/16744665/19dd49b0-4780-11e6-8742-111668399c46.png)

- [x] Emulador
- Google Nexus 4
- Android 4.3
- 320 dpi

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16744732/7491351a-4780-11e6-8b18-e7cf4d164639.jpg)

#### Archivo Logcat.txt

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357975/logcat.txt)

**Comment by JeanFranco498** [comment]
En la version 20.4 esta pasando el mismo error

![screenshot_20220200](https://cloud.githubusercontent.com/assets/19807906/16751272/18616b04-47a6-11e6-9a90-8c7ae38a4958.jpg)


![screenshot_153](https://cloud.githubusercontent.com/assets/19807906/16751273/18680ebe-47a6-11e6-9b9a-5c5c7e7e8fbd.jpg)

**Comment by sanro14** [comment]
@nelsonalfo @yalayn

**Comment by yalayn** [comment]
Buenas noches. @isbet que fecha de vencimiento tenía el contrato? Si estaba en tiempo de vencer pasaría lo que describes allí. Cerraría el contrato. Por que no se concretó a tiempo la entrega del pago.

**Comment by IsbetVR** [comment]
Hola @yalayn!! Sí, las captures las tomé cuando estaba por vencer, y efectivamente cerró sin concretarlo. Pero duramos rato allí, el customer había confirmado y aún así le salía que esperaba por él mismo, y a mi me decía que estaba esperando por él... y bueno, expiró... Pero anterior a este contrato hicimos uno perfecto! ;) Los dos iban en paralelo prácticamente el anterior si corrió bien, perfecto!

**Comment by yalayn** [comment]
Ok entiendo. Si es que no llegó el pago algo en la comunicación fallo. Log

**Comment by yalayn** [comment]
Hola @JeanFranco498. Ese estatus de Negotiation is Closing ocurre mientras la negociación espera que se apertura el contrato y debe esperar un tiempo para que eso se concreté. Nunca apareció el contrato? Cuanto tiempo aproximadamente esperaste por el contrato?

**Comment by yalayn** [comment]
Hola @JeanFranco498. Ese estatus de Negotiation is Closing ocurre mientras la negociación espera que se apertura el contrato y debe esperar un tiempo para que eso se concreté. Nunca apareció el contrato? Cuanto tiempo aproximadamente esperaste por el contrato?

**Comment by sanro14** [comment]
@yalayn eso le comente, pero se subió el caso porque nunca paso a contrato, al finalizar las pruebas volvió a revisar incluso en el historial de contratos no salia.

**Comment by IsbetVR** [comment]
@yalayn 
En la versión 20.5 de CBP que se está testeando en el bloque de la mañana, no se ha podido probar este caso por problemas con las conexiones en las Communities, no se ven los usuarios creados para esta versión de apk. 
Pendiente de chequear hasta tanto no se solvente lo de las conexiones en las communities.

**Comment by maydiamc** [comment]
fecha 18/07/16

version 20.7 de CBP
en esta version no se pudo culminar ningun contrato por problemas de la red 

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16918864/5a5915e6-4cd5-11e6-8ce8-a2d7208a52ee.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.8 de CBP el contrato se quedo enviando los 1.8 btc en el paso numero 3: "MERCHANDISE DELIVERY", luego al volver a entrar se me volvía a habilitar esa casilla y al darle confirmar me notificaba que se había enviado la mercancía y cambiaba de color pero nunca avanzo de ese paso: 

![clont](https://cloud.githubusercontent.com/assets/19883115/17006203/138e7cbc-4ead-11e6-95ee-f2e03180d9dc.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/17006335/1c10bd9a-4eae-11e6-96f5-286dc59e8c55.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.9 de CBP el contrato se quedo enviando  en el paso numero 1: "PAYMENT DELIVERY", se quedo en ese estatus y nunca avanzo de ese paso:

![screenshot_4](https://cloud.githubusercontent.com/assets/19883115/17073998/44eaecda-5044-11e6-88f6-1c4f9b7c00b7.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/17073999/4bffeac0-5044-11e6-8c35-f380104ed333.png)

**Comment by marielis-urbina** [comment]
En la versión 20.9 de la CBP,  este error persiste en mi emulador, dos contratos ya confirmados por el Broker  se quedaron en espera por mas de dos horas.

![neg](https://cloud.githubusercontent.com/assets/19353722/17074007/6ab7e04e-5044-11e6-976f-1deb5762c1cc.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17074008/6d680300-5044-11e6-8826-c87e81386cbf.png)

**Comment by marielis-urbina** [comment]
En la versión 21.0 de CBP persiste este error en mi emulador

![customer](https://cloud.githubusercontent.com/assets/19353722/17121971/88821de8-52a5-11e6-9e02-e2159938ff2b.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17121978/8d6b4e6a-52a5-11e6-87e7-1172a5251222.png)

**Comment by GeronimoVierma** [comment]
Versión 21.0-CBP

El contrato se quedo mas de 1 hora en "Negotiation is Closing" (imagen 1), luego paso a contrato y se quedo estancado en "Waiting for the customer" (imagen 2):

![screenshot_7](https://cloud.githubusercontent.com/assets/19883115/17145193/52ad5296-5327-11e6-8589-75c246c8971b.png)


![screenshot_10](https://cloud.githubusercontent.com/assets/19883115/17145289/9f67d430-5327-11e6-8c49-256b4bb97de6.png)

**Comment by JeanFranco498** [comment]
21.0 CBP sigue pasando. 

Yo como Broker confirmo todo e incluso se hace la transacción, es decir, llegan y sale el dinero de la transacción

 
![image](https://cloud.githubusercontent.com/assets/19807906/17159540/fc0bff42-536b-11e6-93fc-407ec3fc118d.png)

![image](https://cloud.githubusercontent.com/assets/19807906/17159657/e1eeeba0-536c-11e6-9dbf-ba4fd344e970.png)

Al customer le aparece que esta esperando por mi a pesar de que ya confirme el contrato 

![image](https://cloud.githubusercontent.com/assets/19807906/17159622/919a741c-536c-11e6-945e-ed031cfbc867.png)


Esto pasa hasta el punto de que el contrato esta a punto de expirar 

![image](https://cloud.githubusercontent.com/assets/19807906/17159661/efa26a06-536c-11e6-93bb-e627410e5899.png)

**Comment by GeronimoVierma** [comment]
27-07-16
21.0 CBP

Cuando la negociación paso a contrato el Customer envió el pago y el dinero me llego a mi como Broker (imagen 1), pero en la pantalla de mi contrato el estatus que tenia era el de  "Waiting for the customer" (imagen 2), al pasar aproximadamente una hora el contrato se canceló (imagen 3):

![screenshot_163](https://cloud.githubusercontent.com/assets/19883115/17177711/b725296a-53e0-11e6-91e9-de4d2fed8d63.png)

![screenshot_15](https://cloud.githubusercontent.com/assets/19883115/17177728/cdb3a83c-53e0-11e6-9ddb-a1c56acee1b0.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/17177807/0015a26c-53e1-11e6-90cb-3f82f2b5cea6.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/19883115/17177815/07c74fe2-53e1-11e6-99fa-2f8911e4620e.png)

![gero2](https://cloud.githubusercontent.com/assets/19883115/17177897/5efe4f40-53e1-11e6-84c5-af81f64e4c4e.png)

![gero3](https://cloud.githubusercontent.com/assets/19883115/17178021/cbfdec7c-53e1-11e6-97d4-b4499859c46e.png)

**Comment by GeronimoVierma** [comment]
CBP-21.0
Estando yo como Customer hacia una negociación con un Broker la cual paso a contrato y al estar en la Customer wallet entre al contrato e hice mi pago (imagen 1) y me aviso que el pago se había realizado (imagen 2), luego de aproximadamente 20 minutos vuelvo a entrar al contrato y aparece en el estatus de como si no hubiera efectuado dicho pago, envío el pago nuevamente y al cabo de un tiempo me vuelve a salir como si no hubiera efectuado el pago, y así el contrato termina expirando (imagen 3)


![screenshot_9](https://cloud.githubusercontent.com/assets/19883115/17233994/adc6af24-5502-11e6-9cca-929e7a5dc1f5.png)

![screenshot_10](https://cloud.githubusercontent.com/assets/19883115/17234077/4e924e90-5503-11e6-80ff-8d5e0de1f5cd.png)


![screenshot_13](https://cloud.githubusercontent.com/assets/19883115/17234214/ae81d194-5504-11e6-937d-344fe3595cc7.png)


![pasted image at 2016_07_28 08_48 pm](https://cloud.githubusercontent.com/assets/19883115/17234246/ea41b5dc-5504-11e6-9293-d24d22c62b3f.png)





![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17234156/35fbc414-5504-11e6-8592-61c252f211f9.png)




[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/389658/logcat.txt)

**Comment by GeronimoVierma** [comment]
CBP-21.2
Hora: 8:30 am (aproximadamente)
El error persiste, aparece en el estatus de como si no hubiera efectuado el pago, vuelvo a darle para pagar y me dice que esta enviando el pago y luego sale como si no lo hubiera hecho:

![screenshot_6](https://cloud.githubusercontent.com/assets/19883115/17329608/68bd4f86-5891-11e6-88c0-43200cb4280a.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17329641/8737740a-5891-11e6-9451-acf07e8d097e.png)
![chi](https://cloud.githubusercontent.com/assets/19883115/17329614/6ea16392-5891-11e6-9aae-fb8552266831.png)




[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/397040/logcat.txt)

**Comment by JeanFranco498** [comment]
CBP 21.7 se han realizado contratos satisfactoriamente 



![image](https://cloud.githubusercontent.com/assets/19807906/17554819/c530bc54-5eda-11e6-9ff2-61a349dd13d6.png)



![image](https://cloud.githubusercontent.com/assets/19807906/17554825/ce3e62b0-5eda-11e6-9b75-2cd91e70b885.png)


![screenshot_20](https://cloud.githubusercontent.com/assets/19807906/17554837/dc9e4618-5eda-11e6-8bb1-cebade282777.jpg)

**Comment by marielis-urbina** [comment]
En la versión 21.7 de CBP, este error no sucede en mi emulador

![1](https://cloud.githubusercontent.com/assets/19353722/17554984/b45393ec-5edb-11e6-9304-7a7139f71265.png)

![2](https://cloud.githubusercontent.com/assets/19353722/17554988/b7635ba8-5edb-11e6-8adf-21848f2ff531.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17554910/46b27466-5edb-11e6-8e22-844467978756.png)
