### ISSUE TITLE
CBP - Refleja transacción en el stock no realizada en una cuenta

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#659]
### CBP versión v19.5

-----

##### Reporte de error: 

   *Tengo dos cuentas creadas en la "Banking Wallet" una en "Bsf" y otra en "USD", la Cash la tengo configurada en "USD", en el stock cuando hice transacción de la "Cash" me los pasó a las dos wallets (Cash y Banking) que tenia con "USD" (Pantalla 1), y cuando reviso la "Cash Wallet", sólo me hizo un sólo retiro (Pantalla 2). En la Banking Wallet me muestra las dos cuentas (Pantalla 3) y en la cuenta de USD se puede observar que no tengo ningún movimiento (Pantalla 4)

##### Pantalla 1

![screenshot_19](https://cloud.githubusercontent.com/assets/19142276/16596123/7c85b97c-42c0-11e6-906f-065832b5ce60.jpg)

##### Pantalla 2

![screenshot_20](https://cloud.githubusercontent.com/assets/19142276/16596128/8272ca64-42c0-11e6-82e3-ce82d85b8692.jpg)

##### Pantalla 3

![screenshot_21](https://cloud.githubusercontent.com/assets/19142276/16596921/26bce552-42c4-11e6-9e6c-1c87e7d2f9bb.jpg)

##### Pantalla 4

![screenshot_22](https://cloud.githubusercontent.com/assets/19142276/16596925/2b6b8d24-42c4-11e6-8c78-c0045c1ef06f.jpg)

-----

##### Pasos exactos para reproducir el error:

1. Hice perfil de broker 
2. Configuré la Crypto Broker (en el stock tenia inicialmente bitcoin wallet (btc), cash (USD) y banking (USD) )
3. Luego en la banking wallet agregué otra cuenta pero en Bsf. y al revisar la cryto broker me la está listando en el stock, por tanto tengo 1 en btc, 2 en USD y 1 en Bsf.
4. En cada wallet hice los depósitos correspondientes para pasarlos al stock
5. Cuando hice la transacción de la cash, me depositó la misma cantidad en ambas wallets (la que corresponde a la cash y la de banking, ambas en USD), sin embargo no me lo descontó dos veces de la "Cash Wallet"

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de android 4.3
- 320 dpi
- API 18 768x1280

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16596564/898bbf20-42c2-11e6-955a-7c1cbc46e59f.jpg)

**Comment by IsbetVR** [comment]
@nelsonalfo

**Comment by lostwood** [comment]
buenos dias ya estamos en cuenta al solucionar avisaremos por aca

**Comment by lostwood** [comment]
en la version 19.8 se corrigio este error, ya lo pueden corroborar

**Comment by IsbetVR** [comment]
Hola!! @lostwood en la versión 19.8 de CBP, efectivamente sólo hace el traspaso a la que corresponde (En mi caso sólo probé con las cash), pero, no me está marcando en el stock la otra cuenta (Bank Wallet en USD) (Pantalla 1 y 2)

#### Pantalla 1

![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/16653131/09860f54-441d-11e6-9b8f-0511701b8849.jpg)

#### Pantalla 2

![screenshot_3](https://cloud.githubusercontent.com/assets/19142276/16653138/0fb8e798-441d-11e6-9e30-bd104a68a797.jpg)

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16653154/237144ba-441d-11e6-8107-cc49828d6547.jpg)

**Comment by IsbetVR** [comment]
@lostwood mira esta parte (Pantalla 1, si lo está reflejando :/ en ambas cuentas de USD ), la transferencia de Bs. la había hecho luego de las captures del comentario anterior.
Versión CBP 19.8 CBP

#### Pantalla 1

![screenshot_5](https://cloud.githubusercontent.com/assets/19142276/16653315/1764768c-441e-11e6-896c-7391da0605dc.jpg)

**Comment by lostwood** [comment]
-Ok @IsbetVR con lo que mencionas en la pantalla del stock, el te va a mostrar en tu stock el total de la moneda a la que le hagas el RESTOCK, no importa de donde tomastes el dinero si de cash o the bank

-Con respecto a la pantalla del navigation drawer donde te aparece los dolares repetidos ya se esta corrigiendo

Al tenerlo listo informaremos por aca

**Comment by IsbetVR** [comment]
@lostwood ok, revisaré eso en la próxima versión.
Aclarando lo del stock que me acabas de mencionar a ver si te entendí, en el stock sólo me va a reflejar tantas secciones tenga de acuerdo a las monedas, no de acuerdo a las cuentas? Si es así, entonces esta bien que se vean 3 secciones del lado del stock y 4 del lado del wallets asociadas (2 manejan la misma moneda)? ya que tengo sólo 3 monedas...

**Comment by lostwood** [comment]
@IsbetVR si, fijate en este ejemplo si haces una negociación por 1000 $ que tienes en el stock, y lo habias tomado 500 en cash y 500 en bank, y si se acordo que se los entregabas en mano tendrias que sacar 500 $ del cajero para tener los 1000 $ en efectivo, para de esta manera poder cerrar el contrato.

**Comment by IsbetVR** [comment]
@lostwood  En la versión 19.9 de CBP, efectivamente, sólo me refleja en la parte izquierda del stock tantas secciones de acuerdo a las monedas, chévere por ahí! (pantalla 1), pero en el navigation drawer persiste el detalle que muestra de acuerdo a las cuentas que tenga en las wallets (repite los montos en la misma moneda) (pantalla 2)

Queda pendiente verificar lo que me comentaste de la negociación si empleo ambas wallets para el stock (para ver el reflejo del retiro) ;)

#### Pantalla 1

![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/16667650/96258186-445b-11e6-932e-2ff6d82ce17e.jpg)

#### Pantalla 2

![screenshot_8](https://cloud.githubusercontent.com/assets/19142276/16667664/9d56b506-445b-11e6-8204-b8c41fd62fa3.jpg)

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16667704/e0170440-445b-11e6-9e74-fae2d8e14435.jpg)

**Comment by camilavaleria** [comment]
En la version 20.1 sigue reflejandose en el current stock, de  las cuentas que se tienen en las wallets, se repiten los montos de la misma moneda, en el navigation drawer.

![image](https://cloud.githubusercontent.com/assets/18740418/16691243/dcf764d2-44f9-11e6-94e9-58555475f769.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16691375/841d58ac-44fa-11e6-8ec6-9ca152687012.png)

Emulador de prueba:

![image](https://cloud.githubusercontent.com/assets/18740418/16691548/09cc85d6-44fb-11e6-8ffb-650f5072806c.png)

**Comment by IsbetVR** [comment]
En la versión 20.4 CBP corregido lo del navigation drawer, agrupa de acuerdo a las monedas con las que estoy trabajando en el stock

![screenshot_2](https://cloud.githubusercontent.com/assets/19142276/16750756/0dd05884-47a2-11e6-927c-5b98f16d1084.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/19142276/16750763/12777156-47a2-11e6-9bad-b4521fca0454.jpg)

PD: Queda pendiente verificar lo que me comentaste de la negociación si empleo ambas wallets para el stock (para ver el reflejo del retiro) ;)

Pero solucionado el error reportado en este issue

**Comment by IsbetVR** [comment]
Closed #659
