### ISSUE TITLE
Bitcoin Wallet_experiencia del usuario_barra superior

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#66]
#### Nombre pantalla
-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *En el menu principal, la barra superior del telefono se mantiene desplegada y no permite buena visibilidad de los botones superiores de la aplicacion.
![screenshot_2016-03-01-11-08-22](https://cloud.githubusercontent.com/assets/17274154/13574149/15de991a-e455-11e5-8401-986bd34b2a5f.png)

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: Mini S4
* Version de Android: 4.4.2

**Comment by MaviDavsa** [comment]
Solucionado
