### ISSUE TITLE
COMMUNITIES-CHAT- ENLACE DIRECTO QUE CONECTE LA COMMUNITIES A LA APP

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#660]
Template issue error report

Nombre pantalla

CHAT COMMUNITIES

Nombre de la Aplicación 

CHAT

Reporte de error: 

Sería excelente que en la pantalla de CHAT COMMUNITIES después que se solicite la conexión con los usuarios, en el Home   

![image](https://cloud.githubusercontent.com/assets/18740418/16600975/f3a783de-42d7-11e6-9761-87c92b2d0226.png)

Se diseñara además, un botón, enlace o menú que conecte directamente a la app , sin tener la necesidad de salir de las communities para ingresar de nuevo en la aplicación.

![image](https://cloud.githubusercontent.com/assets/18740418/16601134/d6ef339e-42d8-11e6-8ac9-e2e22ad592be.png)

Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18740418/16601244/6e2bd0be-42d9-11e6-9612-d5d5c6a7f4ab.png)

- [x] Emulador

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by josejcb** [comment]
Solved. Manana lo tendrán.

**Comment by dorzar1989** [comment]
En la Version 19.8 de la CBP esta experiencia de usuario esta resuelta. 
(Particularmente pienso que no esta muy visible u obvio el botón de vuelta al chat para un usuario ordinario, pero esta y funciona y es lo que se quiere, Gracias :+1: )

![screenshot_26](https://cloud.githubusercontent.com/assets/19670319/16638757/f0413cd6-43b7-11e6-8692-a38162a2c6a8.png)


- MOVIL:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16638763/faac0b7e-43b7-11e6-8fc1-ad93886c560d.png)
