### ISSUE TITLE
COMMUNITIES - CHAT - AVISO DE "PLEASE WAIT"

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#661]
#### Nombre pantalla

Browser  - Conections - Notifications

### Nombre de la Aplicación 

- CHAT - CBP Version 19.5 

-----

##### Reporte de error: 

   *Cada vez que hago un movimiento de Scroll del mouse ya sea hacia abajo o hacia arriba, me genera un aviso de "Please Wait...", Se que debe ser porque se actualiza la lista de contactos pero creo que aparece demasiadas veces. 

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/19670319/16601317/c80f26bc-42d9-11e6-88f0-816cd3b105c3.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19670319/16601319/cbfe6b84-42d9-11e6-940f-0c6d24bc7a63.png)

##### Pasos exactos para reproducir el error:

- Entre a la community de CHAT para poder buscar personas
- Al momento de hacer Scroll o bajar con el mouse sale el aviso de "Please Wait.."
- Sigo bajando y vuelve y sale. Esto me detiene la busqueda por segundos
- Me Muevo hacia arriba e igual sale a cada rato.

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348735/logcat.txt)

- Hora:
        Desde las 5:30 pm 

#### Dispositivo desde donde se realizo la prueba

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16601138/dd0a3166-42d8-11e6-8711-040265bd2e3b.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by dorzar1989** [comment]
@AdryCanonico

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by AdryCanonico** [comment]
persiste el error en la version 19.8 de cbp

**Comment by maydiamc** [comment]
solucionsdo en la version 20.1 de cbp
emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16697642/a46f8120-4518-11e6-99b8-ded1638c9f2b.png)

**Comment by dorzar1989** [comment]
En la Version 20.1 de la CBP este caso ya no persiste. Gracias por el boton, es mucho mas eficiente de esta manera. :+1: 

Cerrar Caso porfavor @IsbetVR  @MaviDavsa  @sanro14  @AdryCanonico

**Comment by sanro14** [comment]
Solucionado
