### ISSUE TITLE
Chat -  Se monta el # de las notificaciones de mensajes en el chat

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#662]
#### Nombre pantalla: 

 P2P Chat

### Nombre de la Aplicación 

CHAT

##### Reporte de error: 

  El numero de las notificaciones tapa el texto de los mensaje cuando este es largo.

##### Screenshot o Capture de pantalla:

![chat](https://cloud.githubusercontent.com/assets/19353722/16601556/3824369e-42db-11e6-9f6e-8f674af73d9d.png)

##### Pasos exactos para reproducir el error:

 *Al momento de verificar quien y que mensajes me mandan los contactos, cuando este es largo el número de mensaje no se corta y se monta en dicho mensaje.

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348745/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

![nexus 4-5 1](https://cloud.githubusercontent.com/assets/19353722/16601635/e1dbf3b6-42db-11e6-87a8-1a28c61eeced.png)

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by dorzar1989** [comment]
Me sucede los mismo en la version 19.5 de la CBP, en mi nexus 4 version 5.0

![screenshot_4](https://cloud.githubusercontent.com/assets/19670319/16603762/bf48cf48-42ec-11e6-8dc4-dc37cb386a61.png)


- LOGCAT:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348855/logcat.txt)


- HORA: Desde las 5y45 pm 


- MOVIL:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16603791/fb3648b4-42ec-11e6-93b4-181d76ffadad.png)

**Comment by AdryCanonico** [comment]
persiste en la version 19.8 de la CBP,

**Comment by dorzar1989** [comment]
Las Communities no han permitido probar si este error persiste en la Version 20.1 de CBP, quedara pendiente de revision.

**Comment by danielaporras** [comment]
En la version 20.1 de CBP, en la aplicacion "CHAT"  persiste este error

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.2.2

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/16698618/33d51bb4-451d-11e6-9f94-a412d0b1e035.png)

Turno: Tarde
Hora:3:00
[Google Nexus 4 - 4.2.2 - API 17 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354934/Google.Nexus.4.-.4.2.2.-.API.17.-.768x1280-logcat.txt)

@RoyGF

**Comment by marielis-urbina** [comment]
En la versión 20.3 de Chat este error persiste

![se monta](https://cloud.githubusercontent.com/assets/19353722/16747031/12524b2c-478b-11e6-832b-e50398283e06.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16747037/171bed98-478b-11e6-8bff-fd9fdb198b8d.png)

**Comment by sanro14** [comment]
@royGF

**Comment by RoyGF** [comment]
Ok, lo voy a ver. ;)

**Comment by josejcb** [comment]
Solucionado, manana lo tendran

**Comment by marielis-urbina** [comment]
Con la versión 20.4 de Chat el error persiste 

![nu](https://cloud.githubusercontent.com/assets/19353722/16773834/6c9036c0-4827-11e6-8715-0e90db787721.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16773851/7eb3a558-4827-11e6-9010-1889715fb0eb.png)

**Comment by Hernandezsmanu** [comment]
En la version 20.5 esta solucionado. (Desde emulador)

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/16813068/0278ce50-48fe-11e6-9881-85596151d248.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16813100/2448d322-48fe-11e6-8534-a4fbb7fffdc6.png)

**Comment by Gabymorillo** [comment]
En la versión 20.5 en el telefono fisico no presenta este error. 

![screenshot_2016-07-13-13-27-57](https://cloud.githubusercontent.com/assets/17262077/16813142/4d47b036-48fe-11e6-8254-7a3b2b348207.png)
![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16813145/52eab150-48fe-11e6-844f-f6efd07efa90.png)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #662
