### ISSUE TITLE
COMMUNITIES-CHAT- SE DUPLICAN LOS CONTACTOS EN LA COMMUNITY DE CHAT

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#663]
#### Nombre pantalla
 CHAT COMMUNITY - HOME

### Nombre de la Aplicación 
CHAT

-----

##### Reporte de error: 

 Al entrar a la community del chat para agregar un contacto, se visualizan todos los contactos disponibles para realizar una invitación o request, el problema es que algunos salen duplicados.

##### Screenshot o Capture de pantalla:

![chat](https://cloud.githubusercontent.com/assets/2491042/16602267/0f788764-42e9-11e6-8f0c-c601d94b043c.png)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![phone](https://cloud.githubusercontent.com/assets/2491042/16602285/38e9f6a0-42e9-11e6-807c-9c7c83b5397f.png)

Logcat

[Uploading Samsung Galaxy S4 - 4.2.2 - API 17 - 1080x1920-logcat.txt…]()

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by dorzar1989** [comment]
Me sucede lo mismo en la Version 19.5 de la CBP en el Nexus 4 version 5.0 

![screenshot_1](https://cloud.githubusercontent.com/assets/19670319/16603960/6e070562-42ee-11e6-8613-861666859bb1.png)


- LogCat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348860/logcat.txt)

- Hora: desde las 5:30 pm


- Movil: 
   
![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16603948/576ffac0-42ee-11e6-9cc8-ecf9deda01d7.png)

**Comment by AdryCanonico** [comment]
@RoyGF en la version 19.8 de cbp no se ve el problema. Se va a cerrar el caso.
