### ISSUE TITLE
CHAT- SE AGREGAN SOLOS LOS CONTACTOS

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#664]
#### Nombre pantalla

BROWSER

### Nombre de la Aplicación 

CHAT

-----

##### Reporte de error: 

   *Sale el contacto Papito y Wendy en espera para aceptar la solicitud y yo no los he agregado. Hora del error 6:25 pm

![screenshot_2016-07-05-18-25-40](https://cloud.githubusercontent.com/assets/18584168/16603504/85c7e0f8-42ea-11e6-91a3-6c29fdc69eaf.png)

Papito me agrego a las 6:30 mas o menos.

![screenshot_2016-07-05-18-32-21](https://cloud.githubusercontent.com/assets/18584168/16603558/ecaba21e-42ea-11e6-89df-e7ec7273eca8.png)

##### Pasos exactos para reproducir el error:

 *Cree el perfil y Entre a la Community para agregar mis contactos y vi el error.

##### Inserta Archivo aLogcat: 

 * [alogcat.2016-07-05-14-12-43-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348854/alogcat.2016-07-05-14-12-43-0430.txt)
 
 
  
------

#### Dispositivo desde donde se realizo la prueba

http://www.smart-gsm.com/moviles/samsung-galaxy-avant

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16603720/756b04ae-42ec-11e6-8d29-c12788ef5337.png)

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by josejcb** [comment]
Este no esta mas raro porque no se, si te vuelve a pasar me pondre alerta. Es imposible rastrear este detalle. O el user le dio y no se dio cuenta, o algo en p2p esta ocurriendo que se cruzaron notificaciones.

**Comment by AdryCanonico** [comment]
@josejcb persiste en la version 19.8 de CBP

**Comment by IsbetVR** [comment]
En la versión 20.1 de CBP persiste este error. Aparecen las solicitudes como si las hubiese enviado y no fue así.

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16695834/efc43caa-450f-11e6-8545-4dc68b4ed205.jpg)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso 664     CHAT - CBP V 20.1
Emulador Genymotion:
Nexus 5 5.0.0 api 21 480dpi
Hora aproximada del logcat: 02:21
[logcat664.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354857/logcat664.txt)
Ocurre lo reportado. aparecen connection que no se realizaron. Peny no le pedi connetions
![caso 664](https://cloud.githubusercontent.com/assets/17283358/16697617/8819fc58-4518-11e6-8ce0-d68c315ac7fe.png)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de Chat, persiste el error, aparecen conexiones que no se realizaron

![no cont](https://cloud.githubusercontent.com/assets/19353722/16697825/767a7292-4519-11e6-8ec8-21ee23dc0a64.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16697831/7cde0978-4519-11e6-943d-549d3b886983.png)

**Comment by sanro14** [comment]
Versión 20.3 no me sucedió esto

**Comment by josejcb** [comment]
Ya esto no va a suceder mas, tambien nos sucedia, pero tengo 4 dias probando y no me ha vuelto a salir, podemos cerrar este caso creo.

**Comment by sanro14** [comment]
Solucionado.
