### ISSUE TITLE
CHAT - ERROR EN HORA DE  LA FICHA DE NOTIFICACIONES 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#665]
#### Nombre pantalla

NOTIFICATIONS

### Nombre de la Aplicación 

CHAT

-----

##### Reporte de error: 

   *Todas las fichas de notificaciones dicen que llegaron hace 2 minu... y tienen mas tiempo.
 Seria bueno dejar un poco de espacio entre la palabra Request y el tiempo.

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-07-05-20-16-19](https://cloud.githubusercontent.com/assets/18584168/16604061/7b563dae-42ef-11e6-9372-c1d2bcb08885.png)

![screenshot_2016-07-05-18-32-21](https://cloud.githubusercontent.com/assets/18584168/16604060/7b5440d0-42ef-11e6-8566-7598f069e105.png)

##### Pasos exactos para reproducir el error:

 *Hice mi perfil, agregue personas en la communities y me agregaron. Al entrar en las notificaciones vi que no cambian el tiempo se quedan en 2 minutos. 

##### Inserta Archivo aLogcat: 

 *[Uploading alogcat.2016-07-05-20-18-40-0430.txt…]()

 
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16604044/5a28cd90-42ef-11e6-81ca-7acce7801873.png)

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by josejcb** [comment]
Si, en el diseno grafico se coloco que pusieramos tiempo pero realmente las notificaciones no tienen un tiempo, llegue a pensar en quitarlo mientras eso lo implementan en el servidor, pero no sera pronto porque no esta en el scope del trabajo que estan haciendo. Espero tu recomendacion. Esto se puede consultar con Arnaldo. Siempre olvide comentarle.

**Comment by AdryCanonico** [comment]
@josejcb  ok creo q seria mejor quitarlo mientras. Apoyo esa. ya etiqueto arnaldo para que lo vea
@arnaldos

**Comment by josejcb** [comment]
Done. En el proximo actualizacion lo tendran.

**Comment by marielis-urbina** [comment]
En la versión 19.8 ya no sucede este error, no aparece el tiempo de la notificación

![-2](https://cloud.githubusercontent.com/assets/19353722/16638449/6592ec94-43b5-11e6-9e1c-7f7f0ef0006a.png)

![nexus 4-5 1](https://cloud.githubusercontent.com/assets/19353722/16638454/6bc75aa0-43b5-11e6-8f71-d5591f2ab343.png)
