### ISSUE TITLE
CHAT - NO SE VISUALIZA EL STATUS DE LOS CONTACTOS 

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#666]
#### Nombre pantalla

TODA LA APP

### Nombre de la Aplicación 

CHAT

-----

##### Reporte de error: 

   *No se visualiza el Status de los contactos en la app, a pesar de ser agregado cuando se crea el perfil. 

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-07-05-20-37-55](https://cloud.githubusercontent.com/assets/18584168/16604239/357e8fbe-42f1-11e6-87f2-1c8439cf130a.png)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16604247/44f2b25e-42f1-11e6-98db-1d8a7f0ddc53.png)

**Comment by AdryCanonico** [comment]
@RoyGF

**Comment by marielis-urbina** [comment]
En la versión 20.1, de Chat aun no se visualiza el Status de los contactos en la app

Dispositivo desde donde se realizo la prueba

Emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/16696938/379d3e78-4515-11e6-9bd1-6d7dd6f72656.png)

**Comment by danielaporras** [comment]
En la version 20.1 de CBP en la aplicacion Chat sigue invisible el Status de los contactos, tomando en cuenta que se introduce al crear el perfil.

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/16696910/1c01d944-4515-11e6-881a-ce2105df1736.png)

Dispositivo desde donde se realizo la prueba

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.2.2

@RoyGF

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso   666  CHAT- CBP V 20.1
Emulador Genymotion:
Nexus 5 5.0.0 api 21 480dpi
En este emulador no ocurre lo reportado. El estatus se le agrega y permanece allí.
![666](https://cloud.githubusercontent.com/assets/17283358/16696974/65d17aca-4515-11e6-8874-85eacc91f120.png)

Hora aproximada del logcat:02:06pm
[logcat666.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354831/logcat666.txt)

**Comment by josejcb** [comment]
Correcto, quiza para una futura version podamos incluirla, invitemos a Arnaldo para que siga el caso y ubique la visual del estatus en el lugar mas adecuado a nivel grafico.

**Comment by sanro14** [comment]
@arnaldos

**Comment by arnaldos** [comment]
@josejcb @sanro14 @AdryCanonico Aquí les comparto como deben verse las notificaciones en el statusbar.

![chat_version_12-09](https://cloud.githubusercontent.com/assets/13594347/16767206/527f2680-480c-11e6-9cc8-b576aaf20a14.jpg)
----
![chat_version_12-10](https://cloud.githubusercontent.com/assets/13594347/16767207/528120de-480c-11e6-974b-890de3767f70.jpg)

**Comment by josejcb** [comment]
Esta bien, envíanos esos 2 recursos y se pone, pero este es otro tema, es el de la frase o estado del usuario. Echale un ojo a esto que dicen en beta testing

**Comment by MaviDavsa** [comment]
En la versión 20.4 de CBP sigue igual!

**Comment by yolandayancel** [comment]
Prueba 13-07-16
Caso 666 CBP 20.5
Nexus 5 5.0.0 api 21 dpi480
Persiste el error comentado.
![666](https://cloud.githubusercontent.com/assets/17283358/16815808/5baf33c8-4909-11e6-8184-145e8b5b65c7.png)

**Comment by arnaldos** [comment]
@josejcb te comparto la vista sobre el status 

![chat_version_13](https://cloud.githubusercontent.com/assets/13594347/16829648/b105d436-4967-11e6-911b-e5b6d5873270.jpg)

------
El flujo seria este una ves presiones la foto del contacto en el action bar dentro del chat te lleva al status del contacto.

![image](https://cloud.githubusercontent.com/assets/13594347/16829657/bf40f800-4967-11e6-8c2b-3febea3d588d.png)

**Comment by RoyGF** [comment]
Cuando esté listo, se los hago saber. Plse no comenten este issue hasta que termine. ^_^

**Comment by hcampos1984** [comment]
el error se mantiene en la version 21.1 con la API 19

![image](https://cloud.githubusercontent.com/assets/20233469/17266090/87dceda8-55c2-11e6-8b5f-b64ac1d9b494.png)

@MaviDavsa

**Comment by josejcb** [comment]
Este detalle del estatus no estará hasta la próxima versión de chat, recién se va agregando al diseño esta pantalla que previamente no estaba pensada. Hay que hacer un cambio grande a nivel de código para que este user phrase se vea.

**Comment by dorzar1989** [comment]
En la Version 21.7 de la CBP si se ve el Status de los Usuarios.

- Screenshot:

![screenshot_213](https://cloud.githubusercontent.com/assets/19670319/17528290/d38636b0-5e3c-11e6-8bfb-49f7419b68e3.png)

![screenshot_214](https://cloud.githubusercontent.com/assets/19670319/17528291/d3b3920e-5e3c-11e6-8173-fac2322db95e.png)


- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17528281/c9e06c7a-5e3c-11e6-86b5-31a337fbc4f1.png)

**Comment by danielaporras** [comment]
Version 21.9 El estado toma por defecto "Available" y no lo que en realidad se pone en el estado.
![screenshot_8](https://cloud.githubusercontent.com/assets/19656830/17598709/c04ba934-5fc9-11e6-921f-c5996ae1f098.png)

![dani2](https://cloud.githubusercontent.com/assets/19656830/17598878/8ced7a1c-5fca-11e6-9b4e-9fe53d5845b8.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17598895/9a67899e-5fca-11e6-8e73-fbdc1fe7dd81.png)

**Comment by nelsondb** [comment]
Sigue tomando por defecto el status "avaliable"

![screenshot_3](https://cloud.githubusercontent.com/assets/20217119/17702641/b4ab6da4-639c-11e6-81f1-e90b34442447.jpg)

**Comment by GeronimoVierma** [comment]
Versión 22.3 
Dos contactos de chat cambiaron su estatus (imagen 1 y 2), luego al revisar sus profiles sigue saliendo el status  por defecto (imagen 3 y 4): 

![pasted image at 2016_08_19 02_56 pm](https://cloud.githubusercontent.com/assets/19883115/17821302/f0d7377a-661e-11e6-958a-94278a0b8949.png)

![chat](https://cloud.githubusercontent.com/assets/19883115/17821336/1cb72ae4-661f-11e6-9d63-43d0e21f153e.PNG)


![screenshot_14](https://cloud.githubusercontent.com/assets/19883115/17821348/35cf561e-661f-11e6-8f69-93ba4dd31bd7.png)

![screenshot_15](https://cloud.githubusercontent.com/assets/19883115/17821364/49de6438-661f-11e6-8a38-60d333a14986.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17821371/52f7ef62-661f-11e6-9c69-1641bb5aac41.png)

**Comment by AdryCanonico** [comment]
Se agradece colocar en los comentarios o aclarar si la mejora sera tomada en cuenta para próximas implementaciones de la apk o  el próximo acuerdo de actualización de la misma
Si sera para la próxima  version de la apk (Ejemplo version 22.3 de CBP)  pasada a testing para probar. Para así, en futuras ocasiones no tener inconvenientes cuando se comente.  También tomando en cuenta tener la documentación completa de la app que incluya los términos, acuerdos, funciones, mockup de la misma para tener conocimiento de lo que se tiene que evaluar.                                                                               @josejcb  te recuerdo que esta apk tuvo finalizado el documento hace pocos días y no fue pasado antes de hacerle las pruebas. También que los mockup subidos en el caso #747 no son los mismos implementados en la aplicación.  Disculpen los malos entendidos.                                                                                   Grupo Beta-Testing

**Comment by josejcb** [comment]
Como se acordo en reunion, quitamos para esta version la opcion de guardar y mostrar estatus dado que actualmente solo es posible guardarlo. Para la la próxima versión, estará de nuevo completamente disponible.

**Comment by arosiopr** [comment]
@MaviDavsa  en la versión 1.5 de chat se quito el campo de status
![screenshot_2016-09-08-15-59-07](https://cloud.githubusercontent.com/assets/5313326/18364840/e9874e50-75dd-11e6-9439-051f6d7989c2.png)

![alcatel](https://cloud.githubusercontent.com/assets/5313326/18364843/ed1fb7dc-75dd-11e6-8a9e-f0c2ab0a82d6.png)

**Comment by MaviDavsa** [comment]
Solucionado!
