### ISSUE TITLE
Bitcoin Wallet - Texto que indica fecha y hora de los requests hace un salto de linea

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#667]
#### Nombre pantalla

Requests

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   * @nattyco  Cuando recibo los request y voy a la pantalla que me los muestra, se puede observar un salto de linea en la hora de la transacción, esto sucede en la versión 19.5 de la CBP.

##### tal como se muestra en la siguiente imagen
![screenshot_4](https://cloud.githubusercontent.com/assets/5313324/16604250/56fa881e-42f1-11e6-8a67-fa0d2eec34dc.png)

 *Esto sucedió en el siguiente dispositivo
![dispositivo](https://cloud.githubusercontent.com/assets/5313324/16604274/a01cc124-42f1-11e6-9054-64c84902b3e1.png)

##### Pasos exactos para reproducir el error:

1) Recibí varios request (2 especificamente).
3) Verifique la pantalla de los request y observe la forma en que se visualiza la hora.

##### Inserta Archivo aLogcat: 
 

[Google Nexus 4 - 4.4.4 - API 19 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348885/Google.Nexus.4.-.4.4.4.-.API.19.-.768x1280-logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by arosiopr** [comment]
en la version 20.4 de CBP en mi dispositivo no sale este error, sale todo en la misma linea. Es el mismo dispositivo Nexux 4 android 4.4.4

![screenshot_99](https://cloud.githubusercontent.com/assets/5313326/16767409/565cfb78-480d-11e6-9218-cdb2f667b91f.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16767413/5b69292a-480d-11e6-84a6-101df81c5458.png)

**Comment by IsbetVR** [comment]
En la versión 20.4 de CBP persiste este error, está "cortando" la hora y pasa a la parte de abajo 

![screenshot_5](https://cloud.githubusercontent.com/assets/19142276/16768807/cd2345e0-4813-11e6-8534-5cd2946d70e3.jpg)

#### Dispositivo de prueba

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16768816/da3fb826-4813-11e6-8626-6b78f4a1c852.jpg)

**Comment by yolandayancel** [comment]
Prueba 12-07-2016
Caso 667     CBP V 20.4
Nexus 5 5.0.0 api 21 480dpi
Hora del logcat 09:35 am
[667.txt](https://github.com/Fermat-ORG/beta-testing-program/files/359441/667.txt)

En este emulador, si ocurre lo reportado de forma parecida:
![667](https://cloud.githubusercontent.com/assets/17283358/16768843/08695978-4814-11e6-88d0-9a3f898032f7.png)

**Comment by danielaporras** [comment]
En la Version 20.5 persiste el error.

Dispositivo desde donde se realizo la prueba:

Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 4.2.2

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/16819470/91c059a4-491a-11e6-8ac8-110e97fcda5e.png)

**Comment by marielis-urbina** [comment]
En la versión 20.5 sigue sucediendo este error

![requessss](https://cloud.githubusercontent.com/assets/19353722/16819636/6371a624-491b-11e6-9b7b-1cc9d0964479.png)

Dispositivo desde donde se realizo la prueba:

Marca: Genymotion
Modelo: Samsung GalaxyS3
Version de Android: 4.2.2

**Comment by nattyco** [comment]
@sanro14  verificar este caso en la proxima version de la apk

**Comment by marielis-urbina** [comment]
En la versión 20.7 de la CBP persiste el error

![fecha](https://cloud.githubusercontent.com/assets/19353722/16874606/51a5bed2-4a68-11e6-8295-422de6b9c5a2.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16874610/569aef3e-4a68-11e6-9424-1e10c5a0e3a0.png)

**Comment by IsbetVR** [comment]
@nattyco  
En la versión 20.7 de CBP en "Payment Requests - Received" persiste, hace salto de línea

![screenshot_55](https://cloud.githubusercontent.com/assets/19142276/16874632/72fc5b90-4a68-11e6-81dd-1ea92c50e91c.jpg)

#### Dispositivo de prueba
- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16874660/88c0c3e4-4a68-11e6-8ecb-803b04f44c60.jpg)

**Comment by arosiopr** [comment]
En la versión 20.7 de CBP en "Payment Requests - Sent" hace salto de línea

![screenshot_138](https://cloud.githubusercontent.com/assets/5313326/16876706/f377d20e-4a72-11e6-8885-acc117c59a0f.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16876756/2ce14200-4a73-11e6-9a36-be023c11b0ef.png)

**Comment by yolandayancel** [comment]
Prueba 18-07-16
Caso 667 CBP 20.7
Nexus 5 5.0.0 api 21 480dpi
Ocurre lo reportado. Hace salto de linea
![Uploading 1.png…]()
[Uploading 1.zip…]()

**Comment by marielis-urbina** [comment]
En la versión 20.8 de CBP, persiste el error en mi emulador 

![p4](https://cloud.githubusercontent.com/assets/19353722/17006995/1c863232-4eb3-11e6-8ba8-85eb614ee88b.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17006997/21ccfece-4eb3-11e6-83c1-ea5c29acf6a8.png)

**Comment by arosiopr** [comment]
En la versión 20.9.1 de la bitcoin wallet no sale este error en el nexus 4 android 4.4.4. y se lleno el campo completo hasta lo máximo que dejo. @AdryCanonico 

![screenshot_32](https://cloud.githubusercontent.com/assets/5313326/17029742/6e6ec6ea-4f3a-11e6-8b12-9107fd50784e.png)

**Comment by GeronimoVierma** [comment]
En la versión  ccp-v3.3 ubica mas arriba la fecha y la hora sale cortada (usuario dianey wallet 8916m):
Teléfono físico:
![screenshot_2016-09-08-11-03-02](https://cloud.githubusercontent.com/assets/19883115/18354927/710eeffa-75b5-11e6-99ac-770637ef41d8.png)
![screenshot_2016-07-14-18-31-45](https://cloud.githubusercontent.com/assets/19883115/18354942/7dd8ed6c-75b5-11e6-8337-2ee6ac31cf02.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by IsbetVR** [comment]
@nattyco está sucediendo de nuevo en algunos dispositivos

**Comment by camilavaleria** [comment]
En la versión ccp-v3.3, probando desde mi telefono fisico, en la pantalla del payment request "sent" en los contactos, donde se señala la fecha, sale montada  la hora y esta se corta, tal y como se señala a continuacion:

![image](https://cloud.githubusercontent.com/assets/18740418/18355383/eaa438c4-75b6-11e6-98af-a57a5d5d3184.png)

Telefono fisico:

![image](https://cloud.githubusercontent.com/assets/18740418/18355409/fe7cbb3c-75b6-11e6-8287-e6d0f41c4766.png)

**Comment by camilavaleria** [comment]
En la version 3.3.3 de la CCP, probando desde mi dispositivo fisico, persiste este error, tal y como se indica a continuacion:

![image](https://cloud.githubusercontent.com/assets/18740418/18388522/f821591e-766f-11e6-95b9-82de8cb5e422.png)


Dispositivo de Prueba:

![image](https://cloud.githubusercontent.com/assets/18740418/18388538/0c01afd8-7670-11e6-8a31-12640bfe3109.png)

**Comment by nattyco** [comment]
@camilavaleria  verificar en la version 3.3.4 de la apk

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en la versión 3.3.4 de CCP

![screenshot_2016-09-09-15-46-09](https://cloud.githubusercontent.com/assets/5313326/18400852/aeea7baa-76a5-11e6-81e7-829c8218585e.png)

**### Teléfono Físico** 

![alcatel](https://cloud.githubusercontent.com/assets/5313326/18399640/f5df8a24-769f-11e6-9ac2-0279e586a5cd.png)

**Comment by IsbetVR** [comment]
Closed #667
