### ISSUE TITLE
BITCOIN WALLET -  TEXTO MONTADO EN LA FICHA DE RECEIVED

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#668]
#### Nombre pantalla

HOME

### Nombre de la Aplicación 

BITCOIN WALLET

-----

##### Reporte de error: 

   *Me enviaron 2 BTC con un mensaje muy largo y este se monta sobre la palabra 2 records. 
7:05 pm hora del detalle.

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-07-05-19-05-48](https://cloud.githubusercontent.com/assets/18584168/16604539/524b9440-42f4-11e6-8e21-3a2c5006eeb1.png)

##### Inserta Archivo aLogcat: 

[alogcat.2016-07-05-20-18-40-0430.txt](https://github.com/Fermat-ORG/beta-testing-program/files/348895/alogcat.2016-07-05-20-18-40-0430.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/16604561/835fadd2-42f4-11e6-9741-3517017f3ad5.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by IsbetVR** [comment]
En la versión 20.4 de CBP persiste este error, se monta el texto sobre la palabra "records"

![screenshot_4](https://cloud.githubusercontent.com/assets/19142276/16751462/c0de58f4-47a7-11e6-869b-20e4e8fd92d8.jpg)

##### Probado en Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16751468/cc2b0bda-47a7-11e6-8c55-bbd54bf1c1a1.jpg)

**Comment by nattyco** [comment]
@AdryCanonico  verificar nuevamente este caso

**Comment by yolandayancel** [comment]
Prueba 15-07-16
Caso 668 CBP 20.7 BitcoinWallet
Nexus 5 5.0.0 api 21 480dpi
Ocurre lo reportado.
![monta las notas](https://cloud.githubusercontent.com/assets/17283358/16877972/a185b4e2-4a78-11e6-82a7-8dcfcb7cfed3.png)

**Comment by Hernandezsmanu** [comment]
Prueba: 18-07-2016
Version: 20.7

Ocurre lo mismo.

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/16918858/55f7a0c6-4cd5-11e6-8b2e-045f08f95b44.png)

DPI 320

**Comment by marielis-urbina** [comment]
En la versión 20.8 de CBP, este error no pasa en mi emulador 

![p6](https://cloud.githubusercontent.com/assets/19353722/17006022/e1813a80-4eab-11e6-94ba-ad7030e1cabb.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17005991/b7785458-4eab-11e6-9ebc-37e0d1a2b2b7.png)

**Comment by marielis-urbina** [comment]
En la versión 20.9.1 de la Bitcoin Wallet en mi emulador ya no sucede 

![capt 1](https://cloud.githubusercontent.com/assets/19353722/17059002/10d85340-4ff1-11e6-8264-bff2cf3b8919.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17059008/151616a4-4ff1-11e6-82e2-76848345edc8.png)

**Comment by IsbetVR** [comment]
Closed #668

**Comment by marielis-urbina** [comment]
En la versión 21.8 de CBP, este error vuelve a parecer 

![montado](https://cloud.githubusercontent.com/assets/19353722/17566376/1b0d8b56-5f09-11e6-9027-c50e419bda4d.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17566382/208941e2-5f09-11e6-9c57-0998950cc1eb.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411867/logcat.txt)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by yolandayancel** [comment]
Prueba 10-08-16
Caso 724 CBP V21.8
Sony Xperia S 16api 320dpi
Ocurre lo reportado..
![error4](https://cloud.githubusercontent.com/assets/17283358/17566656/51eeca30-5f0a-11e6-875d-fe7efcd7d529.png)

**Comment by nattyco** [comment]
@yolandayancel  que version de android tine el sony xpeiria? es S o Z

**Comment by yolandayancel** [comment]
@nattyco 
Buenos días Natalia..
El Sony Xperia S 4.1.1 16 api 320 DPI
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17590626/6cc15852-5fa8-11e6-9a16-ee70d1baa9e9.png)
Saludos Cordiales

**Comment by IsbetVR** [comment]
El error gráfico persiste en la versión 21.9 CBP

![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/17602708/d3bc2fea-5fdb-11e6-8a9d-428e84388a74.jpg)

#### Dispositivo de prueba
- [x] Emulador 

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/17602718/e17cdbde-5fdb-11e6-882a-7477cb8a30be.jpg)

**Comment by GeronimoVierma** [comment]
En la versión 22.0 de CBP el error gráfico esta solucionado:

![screenshot_9](https://cloud.githubusercontent.com/assets/19883115/17673566/ad623c10-62ef-11e6-9094-984af6e1dfd9.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17673572/b62c86d4-62ef-11e6-9bc2-ca7f217e2ed5.png)

**Comment by marielis-urbina** [comment]
En la versión 22 de CBP, en mi emulador no pasa

![prueba](https://cloud.githubusercontent.com/assets/19353722/17675129/5be40664-62f6-11e6-81d7-35d2852abeff.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17675132/608f795a-62f6-11e6-9923-e13eb26ceadb.png)

**Comment by maydiamc** [comment]
este error se soluciono en la version 22.0 de CBP en mi emulador 

![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17677218/ca525c14-62ff-11e6-9219-ffd52b6ebb64.png)

**Comment by marielis-urbina** [comment]
En la versión 22.1 de CBP, no sucede este error en mi emulador

![668](https://cloud.githubusercontent.com/assets/19353722/17708961/3a008e7c-63b5-11e6-9ca1-bd0f8de68daa.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17708968/3e1694d4-63b5-11e6-8cf7-862ca7bb3d96.png)
