### ISSUE TITLE
Bitcoin Wallet - Duplica las transacciones en el detalle de "SENT" y "RECEIVED"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#669]
### CBP (versión 19.5)

-----

##### Reporte de error: 

   *Al hacer transacciones con la Bitcoin Wallet (Desde Crypto Broker y propiamente con Bitcoin Wallet), las transacciones recibidas (RECEIVED) las muentra repetidas en el detalle de cada una de las que estén ahí (Pantalla 1), y si observo el resumen (Pantalla 2) tengo 3 en RECEIVED, al darle click a cada una me despliega el detalle de las demás. En cambio en "SEND" no sucede eso (Pantalla 3), solo detalla a la que le doy click. Teniendo más de 3 transacciones en el RECEIVED (Pantalla 4), sólo me repite las 3 últimas según donde esté posicionada en cada una (Pantalla 5)

##### Pantalla 1

![screenshot_42](https://cloud.githubusercontent.com/assets/19142276/16621933/136cc36c-4366-11e6-90b2-c2eef6bb8786.jpg)

##### Pantalla 2

![screenshot_43](https://cloud.githubusercontent.com/assets/19142276/16621947/241408a6-4366-11e6-94c3-c5c8a03b7d53.jpg)

##### Pantalla 3

![screenshot_44](https://cloud.githubusercontent.com/assets/19142276/16621976/3fdd18de-4366-11e6-9f11-791adbfa9233.jpg)

##### Pantalla 4

![screenshot_45](https://cloud.githubusercontent.com/assets/19142276/16622434/3451943e-4368-11e6-9087-c5fef5986e66.jpg)

##### Pantalla 5

![screenshot_46](https://cloud.githubusercontent.com/assets/19142276/16622528/80a98c38-4368-11e6-824f-f44af630ae6b.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión android 4.3
- 320 dpi
- API 18 768x1280

**Comment by IsbetVR** [comment]
@nattyco

**Comment by IsbetVR** [comment]
En la versión 20.3 de CBP, persiste este error, está duplicando las transacciones en el detalle de los "RECEIVED"

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16743285/8b6d7b42-4779-11e6-96d6-f9a003d75956.jpg)

**Comment by arosiopr** [comment]
En la version 20.4 de CBP persiste el error se repite muchas veces la misma transaccion

![screenshot_104](https://cloud.githubusercontent.com/assets/5313326/16769804/317ff232-4818-11e6-8e72-6b08406d66d6.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16769821/42c95736-4818-11e6-929a-bc9e6bc3c1e4.png)

**Comment by sanro14** [comment]
@nattyco

**Comment by nattyco** [comment]
@IsbetVR  verificar nuevamente este caso

**Comment by IsbetVR** [comment]
@nattyco en la versión 20.7 de CBP no hemos podido verificar porque las transacciones se desaparecen

**Comment by arosiopr** [comment]
en la versión 20.9 persiste el error, en este caso me esta mezclando un request que me acepto francisco por 0.012 BTC y los 5 btc que llegan de la Testnet. Lo repite para ambos contactos como se puede observar en las siguientes capturas. @nattyco 

![screenshot_17](https://cloud.githubusercontent.com/assets/5313326/16998554/eff30522-4e87-11e6-8f3b-6b8a64af2f4c.png)

![screenshot_18](https://cloud.githubusercontent.com/assets/5313326/16998571/0ad4f15c-4e88-11e6-904f-0976a2d9d485.png)

Emulador

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16998621/4dd544b6-4e88-11e6-9462-f6cc227b8c06.png)

**Comment by marielis-urbina** [comment]
En la versión 20.9.1 de la Bitcoin Wallet, sigue pasando este error, en la captura la 1era. transacción la envié yo a Dianey, en la 2da es lo que el Testnet_Bitcoins me envio y en la 3ra es lo que ella me envía a mi. 

![nuevo2](https://cloud.githubusercontent.com/assets/19353722/17058212/0bf92844-4fed-11e6-83d3-4b3dbe8c4e84.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17058213/0feefb36-4fed-11e6-85d4-a22570afa7c5.png)

**Comment by yolandayancel** [comment]
Prueba 22-07-16
Caso 669 V 20.9.1 (Bitcoin Wallet)
Samsung S6 5.1.0 api 22 640dpi
logcat hora aproximada: 09:08 am
[logcatcaso669.txt](https://github.com/Fermat-ORG/beta-testing-program/files/378271/logcatcaso669.txt)

En este emulador ocurre algo parecido:
1 Duplicó a un perfil 
![caso 2 1](https://cloud.githubusercontent.com/assets/17283358/17058378/264c3a28-4fee-11e6-8d8f-80b0d63b3c63.png)
![caso2 3](https://cloud.githubusercontent.com/assets/17283358/17058488/b43edad4-4fee-11e6-82fe-d7431796d94a.png)

2 Coloco lo recibido por el fraucet en un perfil de usuario agregado:
![caso2 2](https://cloud.githubusercontent.com/assets/17283358/17058434/6afe2adc-4fee-11e6-85f5-f7d6a6c3a397.png)

**Comment by nattyco** [comment]
@IsbetVR  verificar con la Versión 20.9 CBP

**Comment by GeronimoVierma** [comment]
En la versión 20.9 CBP no me ocurre el error:

![screenshot_8](https://cloud.githubusercontent.com/assets/19883115/17073851/a506bb8c-5042-11e6-9925-7cd65d3487fb.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/17073856/b1695dc6-5042-11e6-97f9-0706342d54f2.png)

**Comment by marielis-urbina** [comment]
En la versión 20.9 de CBP, en mi emulador ya no sucede este error

![no duplica](https://cloud.githubusercontent.com/assets/19353722/17073853/aed94602-5042-11e6-90ee-fa071fd59cf2.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17073858/b33dda82-5042-11e6-9a91-dd4f581f7221.png)

**Comment by yolandayancel** [comment]
Prueba 27-07-16
Caso 669 CBP 20.1 (BITCOIN Wallet)
Nexus 5 5.0.0 api 21 480 dpi
Logcat:
[logcat669.txt](https://github.com/Fermat-ORG/beta-testing-program/files/386174/logcat669.txt)

Reporte: Al revisar las transacciones recibidas de Dianey, pude observar que una de ellas se registro en el perfil del Tesnet..
![screenshot_10](https://cloud.githubusercontent.com/assets/17283358/17177139/f5ea917e-53dd-11e6-8f15-7c15ff3d245e.png)

**Comment by IsbetVR** [comment]
Se reabre al caso

**Comment by yolandayancel** [comment]
Prueba 27-07-16
Caso 669 CBP 20.1 (BITCOIN Wallet)
Nexus 5 5.0.0 api 21 480 dpi
Logcat:

[logcat669.zip](https://github.com/Fermat-ORG/beta-testing-program/files/386261/logcat669.zip)
Prueba 27-07-16
Caso 669 CBP 20.1 (BITCOIN Wallet)
Nexus 5 5.0.0 api 21 480 dpi
Logcat:
logcat669.txt
Reporte: Al revisar las transacciones enviadas a Marielis, pude observar que una de ellas era una transacción recibida que se registro en las enviadas..
![669](https://cloud.githubusercontent.com/assets/17283358/17178250/b108f898-53e2-11e6-9d74-db3e529fa8c2.png)



Reporte: Al revisar las transacciones recibidas de Dianey, pude observar que una de ellas se registro en el perfil del Tesnet..

**Comment by IsbetVR** [comment]
@nattyco  Este error persiste en la versión 21.3 CBP, está duplicando en el received las transacciones

![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/17370224/3b4f6ed4-5969-11e6-846d-8a22ad380c64.jpg)

#### Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/17370237/4c80180c-5969-11e6-847a-458d659199b6.jpg)

**Comment by nattyco** [comment]
@IsbetVR  verificar este reporte en la nueva apk

**Comment by GeronimoVierma** [comment]
En la versión 22.0 de CBP el error esta solucionado:


![screenshot_10](https://cloud.githubusercontent.com/assets/19883115/17673656/206db5c2-62f0-11e6-98c0-379c8b9282be.png)


![4 1](https://cloud.githubusercontent.com/assets/19883115/17673641/153bdac6-62f0-11e6-9d91-04d8312dcaba.png)

**Comment by camilavaleria** [comment]
En la version 22.0 de la CBP, sigue sucediendo este error, tal y como se visualiza a continuacion;

![image](https://cloud.githubusercontent.com/assets/18740418/17676168/3cbe8e94-62fb-11e6-8331-8bb33be7cf99.png)

emulador de prueba;

![image](https://cloud.githubusercontent.com/assets/18740418/17676183/50cf7fec-62fb-11e6-9984-1e3ef4fc8293.png)

**Comment by nattyco** [comment]
@camilavaleria podrias indicarme cuales son las transacciones que estan mal en el detalle que adjuntas? serian las dos ultimas?. Necesito que me indiques quien te las envio y demas pasos para poder reproducir el error.

**Comment by camilavaleria** [comment]
@nattyco serian las transacciones correspondientes a: los 0.025 btc de rubencho, 1 btc solicitado del faucet, y 1 btc solicitado en el circulo del home de la wallet, ya q esas no corresponden a los SEND de Geronimo. El paso basico para pedir BTC seria: seleccionar el contacto en mi wallet y solicitar una cantidad de btc. Posterior a eso, deberian aparecer en mi HOME el recor de los BTC q he recibido (en este caso) y enviado en cada contacto, sin q se mezclen obviamente. NO se que mas necesitas que te explique o detalle...

**Comment by camilavaleria** [comment]
@nattyco las transacciones q NO corresponden al RECEIVED de Gero serian; los 0.025 btc de rubencho, 1 btc del faucet y 1 btc solicitado en el circulo del home.

**Comment by camilavaleria** [comment]
En la version 22.1 de la CBP, sigue pasando este error, se repiten las transacciones de un contacto en otro, tal y como se indica a continuacion:

PANTALLA 1- transacciones de Andrea: es solo la de comprar torta.

![image](https://cloud.githubusercontent.com/assets/18740418/17712216/08ed0c76-63c3-11e6-9fbf-67f171e8a405.png)

PANTALLA 2- transacciones de Camilo: es solo la de comprar pan dulce,

![image](https://cloud.githubusercontent.com/assets/18740418/17712296/53227bbe-63c3-11e6-8f67-7fa2ace4ae44.png)


PANTALLA 3- Comparativo,

![image](https://cloud.githubusercontent.com/assets/18740418/17712321/6b663dd2-63c3-11e6-8d0b-cc8c9a09e01b.png)


EMULADOR DE PRUEBA:

![image](https://cloud.githubusercontent.com/assets/18740418/17712346/8027a0da-63c3-11e6-80cb-77dbbe4e403a.png)

**Comment by nattyco** [comment]
@IsbetVR  @camilavaleria  se corrigio un problema al armar el listado de transacciones, verificar en la version 22.2 de la apk

**Comment by marielis-urbina** [comment]
En la versión 22.2 de CBP, me sucede este error en mi emulador, después de a ver hecho varias transacciones, mande un requests a uno de mis contactos de 0.002, esta vez fue a Maydi, al ella aceptar mi petición, simultáneamente e  ella me envía  0.5597 BTC, al verificar el registro en el received, me sale el contacto duplicado, en vez de aparecer las dos transacciones bajo el mismo contacto y a parte de eso el listado de las transacciones se liga.

![ojo](https://cloud.githubusercontent.com/assets/19353722/17780696/5127efba-653a-11e6-8323-bc922b5b9e3f.png)

![ojo2](https://cloud.githubusercontent.com/assets/19353722/17780712/581a877e-653a-11e6-9601-eb722da1f0ed.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17780717/5c870490-653a-11e6-986f-5bdfad1be982.png)

**Comment by yolandayancel** [comment]
Prueba 18-08-16
Caso 669 CBP 22.2 (BitcoinWallet)
Sony Xperia S 4.1.1 16 api 320dpi
No ocurre lo reportado ( en este emulador las transacciones no se repiten  de un contacto en otro.
1 contacto Maydi
![631 1](https://cloud.githubusercontent.com/assets/17283358/17787258/6452b2ac-6556-11e6-8fb4-ec06986df821.png)
2 Tesnet y Andrea
![669 2](https://cloud.githubusercontent.com/assets/17283358/17787272/738bef36-6556-11e6-8b50-d847b5678d64.png)

Emulador Genymotio
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17787287/82fe63fe-6556-11e6-9f71-e12b8f3300ab.png)

**Comment by GeronimoVierma** [comment]
Versión 22.3
En esta versión la transacción en Received no se duplica, el error esta solucionado:

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17813252/9bc1ee5e-65f8-11e6-863e-f34bc3d22467.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17813259/a21ca226-65f8-11e6-9596-c74fdb037b5b.png)

**Comment by marielis-urbina** [comment]
En la versión 22.3 de CBP, persiste este error en mi emulador, Como no tenía aun Btc, envié a varios de mis contactos requests, casi todos por la misma cantidad de Btc 0.02, me llego primero la respuesta positiva de Nelson y posteriormente, la de Yolanda, al salir del home y dirigirme al listado de Rquests para verificar un pedido que me hizo otro contacto, al regresar y revisar mi received la transacción de Nelson desapareció y aparece ligada a las transacciones de Yolanda.

![prueba 669](https://cloud.githubusercontent.com/assets/19353722/17813292/ccd734cc-65f8-11e6-9a08-8c5979212568.png)

![prueba 669](https://cloud.githubusercontent.com/assets/19353722/17813288/c9d6bba8-65f8-11e6-9c69-5b4ea101fb3a.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17813300/d4732bb4-65f8-11e6-946b-d8a29ac50bbe.png)

**Comment by IsbetVR** [comment]
Este caso se cierra porque el último comentario está haciendo referencia a otro error, diferente a lo reportado en el caso. Se abrió un nuevo caso #777

**Comment by IsbetVR** [comment]
Closed #669

**Comment by camilavaleria** [comment]
En la version 3.4 de la CCP, se duplico un transaccion en los SENT de la pantalla del HOME, tal y como se señala a continuacion;

![image](https://cloud.githubusercontent.com/assets/18740418/18678099/f4fb6344-7f28-11e6-91cb-87abcff4cdd2.png)
 
ARCHIVO LOGCAT:

[logcat trans duplicadas.zip](https://github.com/Fermat-ORG/beta-testing-program/files/483050/logcat.trans.duplicadas.zip)

HORA APROXIMADA DEL ERROR:

11:01 am

DISPOSITIVO FISICO DE PRUEBA:

![image](https://cloud.githubusercontent.com/assets/18740418/18678236/6056221e-7f29-11e6-87ee-4d0e4b43abe7.png)

**Comment by camilavaleria** [comment]
@MaviDavsa

**Comment by yolandayancel** [comment]
Prueba 20-09-16
CCP V 3.4
Pasos seguidos:
1 envió por segunda vez al contacto Geronimo a las 11:17 aprox
2 envió  nuevamente de btc al mismo contacto, este informa que solo ha recibido un solo de 0.005
3 Ingreso en el sent en el home y pude observar que una transacción por 0.0063 se duplico:
![screenshot_2016-09-20-11-39-04](https://cloud.githubusercontent.com/assets/17283358/18678101/f7465032-7f28-11e6-86e4-0a18b6bff8a4.png)

Logcat
[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/483056/logcat.zip)

Celular:
![screenshot_2016-09-20-11-54-38](https://cloud.githubusercontent.com/assets/17283358/18678268/7baac2ea-7f29-11e6-9d2a-28d8d9ca54e2.png)

**Comment by nattyco** [comment]
@IsbetVR  verificar en la version 3.4.2

**Comment by danielaporras** [comment]
Lo reportado en los ultimos comentarios de este issue no se repite en mi dispositivo. v3.5 CCP
![screenshot_2016-09-28-09-19-56](https://cloud.githubusercontent.com/assets/19656830/18917172/f036ec2e-8564-11e6-8d41-488546324e76.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18917174/f2a353e4-8564-11e6-8db2-ed76773a0e9b.png)

@MaviDavsa

**Comment by maydiamc** [comment]
En la versión de CCP 3.5 ya no sucede este error

![screenshot_7](https://cloud.githubusercontent.com/assets/17274154/18917941/32e3a7e0-8567-11e6-8255-1da6cd5e5951.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/17274154/18917946/34f69060-8567-11e6-8a3f-6c0bdc1864d6.png)

Emulador
![nexus 5-6 0](https://cloud.githubusercontent.com/assets/17274154/18917957/3bf17a2e-8567-11e6-9a61-6d684fa45e8a.png)
![nexus 5-6 0 dpi](https://cloud.githubusercontent.com/assets/17274154/18917958/3e19d12a-8567-11e6-9424-e43bcc8fa1e0.png)
