### ISSUE TITLE
Bit Coin Wallet_ Requests

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#67]
#### Nombre pantalla
Requests - Received

##### Reporte de error: 

   *El error que presenta la aplicación es que cuando voy a aceptar el pago que me han enviado me sale el siguiente error y no me deja cobrar lo que ya debería estar en mi cuenta.

![7](https://cloud.githubusercontent.com/assets/17273005/13575746/92d5f8b2-e45c-11e5-9e43-dc5593c9448f.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: Android 5.0

@augusto-ponce

**Comment by nattyco** [comment]
@MaviDavsa  Confirma si tenes balance available en la wallet, porque sino no podes hacer pagos.

**Comment by MaviDavsa** [comment]
![3](https://cloud.githubusercontent.com/assets/17273005/13575852/2141d38c-e45d-11e5-8090-62b6fba40c0b.JPG)
 @nattyco

**Comment by nattyco** [comment]
@MaviDavsa  Balance en available en la wallet, eso es tu Identidad

**Comment by MaviDavsa** [comment]
Listo @nattyco Lo tengo en Available y aun no me deja hacer realidad el pago!

**Comment by nattyco** [comment]
@MaviDavsa podes volver a probar esto ya que no puede reproducir el error.

**Comment by MaviDavsa** [comment]
@nattyco Nenaaa!! Ya probé y nada, me sale absolutamente el mismo error!

**Comment by nattyco** [comment]
@MaviDavsa por la imagen que me pasaste en slack no tenias los btc en available asi que no podias enviarlos.

**Comment by MaviDavsa** [comment]
@nattyco Ya me deja hacer las transferencias pero no envia, es decir, desde ayer yo le hice transferencias a los chicos y hasta el sol de hoy no le han llegado los bitcoins a ellos!

**Comment by MaviDavsa** [comment]
@nattyco No he podido verificar eso porque aun no me ha llegado el pago de nadie!
