### ISSUE TITLE
Bitcoin Wallet - Duplica e Incrementa Bitcoins al reversar Transaccion enviada

### ISSUE THREAD

**Issue by hcampos1984** [Fermat-ORG/beta-testing-program#670]
### Template issue error report

CBP - Duplica e Incrementa Bitcoins al reversar Transaccion enviada

#### Nombre pantalla

Bitcoins Wallet

### Nombre de la Aplicación 

CBP - Bitcoins Wallet

-----

##### Reporte de error: 

Duplica e Incrementa los bitcoins enviados reversando la transaccion. En la versión 19.5 de CBP

##### Screenshot o Capture de pantalla:

![image](https://cloud.githubusercontent.com/assets/20233469/16623387/bf8331d6-436b-11e6-940e-51fd9822bc46.png)
![image](https://cloud.githubusercontent.com/assets/20233469/16623419/d7ad0dae-436b-11e6-9d20-93eab7b2053d.png)
![image](https://cloud.githubusercontent.com/assets/20233469/16623443/f88627c2-436b-11e6-83e1-587d11993e4a.png)
![image](https://cloud.githubusercontent.com/assets/20233469/16623476/252dae8a-436c-11e6-8fb8-ead7a22f9541.png)

##### Pasos exactos para reproducir el error:

 Primero agregue los contactos en el Bitcoins Wallet, luego entre en el menu busque el usuario Adrianabtc0607 para hacer uns transaccion de envio de Bitcoins y me coloca el menu superior en rojo descontando los bitcoins enviados y justo en ese momento al actualizar me duplica el envio de los bitcoins y me los duplica en los available, eliminando el color rojo.

##### Inserta Archivo aLogcat: 

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/350224/logcat.zip)
@IsbetVR 

 
  
------

#### Dispositivo desde donde se realizo la prueba
![image](https://cloud.githubusercontent.com/assets/20233469/16623677/d329e602-436c-11e6-8018-63304fd9d2c6.png)

NEXUS 4
Version: 4.4.4
API 19
- [x] Emulador
- [] Teléfono Físico

**Comment by IsbetVR** [comment]
@nattyco

**Comment by nattyco** [comment]
@hcampos1984  @IsbetVR  verificar si esto vuelve a suceder

**Comment by yolandayancel** [comment]
Prueba 15-07-16
Caso 670 CBP 20.7 Bitcoin Wallet
Nexus 5 5.0.0 api 21 480dpi
Hora aproximada del logcat. 11:13 am
[logcat 670.zip](https://github.com/Fermat-ORG/beta-testing-program/files/366299/logcat.670.zip)
1 tenía 17,002 en el available
2 procedi a enviar al faucet
3 Notificó que lo reverso
4 Aparte de que me lo reverso, me envió 55 más.
1
![reverso](https://cloud.githubusercontent.com/assets/17283358/16879281/f09d1b88-4a7d-11e6-8b53-43f9270152bd.png)
2
![reverso 2](https://cloud.githubusercontent.com/assets/17283358/16879296/ff047536-4a7d-11e6-9ae2-6a057c610167.png)
3
![reverso 3](https://cloud.githubusercontent.com/assets/17283358/16879308/068277f4-4a7e-11e6-819a-4c076b489298.png)
4
![reverso 4](https://cloud.githubusercontent.com/assets/17283358/16879313/0d154394-4a7e-11e6-9e04-3f7860c5d267.png)
5 
![reverso5](https://cloud.githubusercontent.com/assets/17283358/16879373/58f2be72-4a7e-11e6-9870-701cd0fa84ce.png)

**Comment by yolandayancel** [comment]
@nattyco @nelsonalfo

**Comment by yolandayancel** [comment]
@franklinmarcano1970

**Comment by nattyco** [comment]
@yolandayancel  le enviaste al faucet externo verdad? al que usan desde una direccion web.

**Comment by yolandayancel** [comment]
@nattyco 
Buenas Natalia
La solicitud de los BTC los hice por el FAUCET

**Comment by nattyco** [comment]
Aclarame si los 17 btc que te reverso los retorno bien al balance o te los duplico?, fuera del tema de que el faucet te mando 55 btc mas, me interesa saber si la reversa de lo enviado si hiso bien.

**Comment by yolandayancel** [comment]
@nattyco 
Si me reverso los 17

**Comment by nattyco** [comment]
pero no los duplico a eso voy

**Comment by yolandayancel** [comment]
@nattyco 
No.. no los duplico los 17,  me retorno solo 17

**Comment by nattyco** [comment]
@IsbetVR  verificar este caso en otros dispositivos para ver si la reversa se hace bien en otros casos

**Comment by IsbetVR** [comment]
@nattyco Vale natty! vamos a verificar en otros y te avisamos

**Comment by franciscoj961** [comment]
15-07-2016
Caso CBP 20.7 Bitcoin Wallet

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/366935/logcat.txt)


**1- Tenia 35.0005 BTC en mi Bitcoin Wallet y los envie a mi external contact FAUCET** 
![ssss](https://cloud.githubusercontent.com/assets/20245988/16890028/f0742184-4ab8-11e6-949e-5172ce6b0f72.PNG)


**2- Luego me duplicaron los btc**
![sssss](https://cloud.githubusercontent.com/assets/20245988/16890139/ef1b8f06-4ab9-11e6-87f8-c80bd70975a2.PNG)


**3- A los 10 minutos aproximadamente de esto fueron retirados los BTC de mi Bitcoin Wallet**
![ssssssss](https://cloud.githubusercontent.com/assets/20245988/16890194/46cd9c58-4aba-11e6-9f50-c675730fd390.PNG)

**Comment by hcampos1984** [comment]
no he podido hacer pruebas ya que la testnet no me envia los BTC, siempre me deja en espera despues de la notificacion del Testnet BTC arrive @IsbetVR @AdryCanonico

**Comment by yolandayancel** [comment]
Prueba 18-07-16
Caso 670 CBP 20.7 (Bitcoin Wallet)
Nexus 5 5.0.0 api21 480 dpi

Se reintegraron los BTC a  Tesnet_Bitcoins, correctamente su monto
1  tenia en el disponible:
![envio de 5btc](https://cloud.githubusercontent.com/assets/17283358/16921467/ab34bdb2-4cdf-11e6-8744-60fced3f8404.png)
2 Me quedo 0.8007 ( despues del descuento de 0.0003
![envio de 5btc 14](https://cloud.githubusercontent.com/assets/17283358/16921517/dac5ab86-4cdf-11e6-9813-3a7666ca397f.png)
![envio de 5btc 2](https://cloud.githubusercontent.com/assets/17283358/16921537/e9e6f44e-4cdf-11e6-979a-06018e87c4a7.png)

**Comment by yolandayancel** [comment]
Prueba 21-07-16
Caso 670 CBP 20.8 Bitcoin Wallet
Nexus 5 5.0.0 api 21 480dpi
Ya no ocurrio lo reportado con la versión 20.7
Permitió regresar todos lod BTC que me envió el FAUCET.
Ya no me los retornó como ocurria antes.
![caso8 1](https://cloud.githubusercontent.com/assets/17283358/17027183/e5c41c36-4f30-11e6-9783-10cd4075de5e.png)
![caso8 2](https://cloud.githubusercontent.com/assets/17283358/17027200/f93035b6-4f30-11e6-8152-56197458721c.png)

**Comment by nattyco** [comment]
@IsbetVR  @hcampos1984  verificar este caso nuevamente

**Comment by hcampos1984** [comment]
@nattyco en mi caso desde que eso se me presento con los BTC  hasta la fecha no he recibido ninguno, incluso tengo 6 horas esperando lso BTC y aun no los recibo, he cambiado de emulador, he reiniciado, han pasado versiones y aun no los recibo, por lo que no puedo verificar si esto continua sucediendo, no se si sabes de este caso con otro usuario @IsbetVR

**Comment by nattyco** [comment]
@hcampos1984 probaste con la data de cero, es decir borraste data y arrancaste las pruebas de nuevo? Los btc del faucet desde la web no te llegan?

Si seguis con problemas adjuntame el log.

**Comment by nattyco** [comment]
@IsbetVR  @AdryCanonico  verificar nuevamente esto para ver si se soluciono

**Comment by maydiamc** [comment]
en la versión 21.9 de CBP, no se ha duplicado ni hecho reversa ninguna transacción, hice la prueba enviando BTC al faucet  y todo el flujo se realizo correctamente, en mi emulador esto no sucede. @IsbetVR 

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17624866/7bbbff8e-6074-11e6-9194-7008485abe94.png)

**Comment by yolandayancel** [comment]
Prueba 12-08/16
Caso 670 CBP 21.9
Sony Xperia 4.1.1
No ocurre ya lo reportado, ya no se reversan los sent..Realice varios envios hoy a Isbet y ninguno se reverso y los descontó bien..
![670](https://cloud.githubusercontent.com/assets/17283358/17625068/3622f3f0-6075-11e6-934d-83ce0af281f8.png)
