### ISSUE TITLE
CBP - IDENTITIES CUSTOMER Y BROKER NO FUNCIONA CÁMARA.

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#671]
**Template issue error report**

**Nombre pantalla**

Identities Customers - Broker

**Nombre de la Aplicación** 

CBP

-----

**Reporte de error:** 

Al momento de crear la identidad en un Customer o Broker, cuando tomo la foto y le doy para confirmarla se crashea la aplicación Ó se queda la pantalla en negro.

 **Screenshot o Capture de pantalla:**

![i34 cimgpsh_orig](https://cloud.githubusercontent.com/assets/20217119/16635284/a8905a4c-439f-11e6-81bd-df6b605a80fa.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/16635305/bc26c514-439f-11e6-8a72-0eaa2bf09e43.jpg)
 

**Pasos exactos para reproducir el error:**

Al momento de crear la identidad customer seleccionamos la cámara, tomamos la foto y luego confirmarla.

 *Detallar paso a paso la forma en  la cual se logro el error.
Irnos a las identidades de customer, abrir para crear una identidad, colocar nombre, abrimos para tomar una foto, tomamos la foto, y al momento de confirmar la foto se crashea la aplicación.

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/350974/logcat.txt)

 
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_2](https://cloud.githubusercontent.com/assets/20217119/16635707/8cbe8850-43a1-11e6-94e0-ba1f6cbf334c.jpg)

- [x] Emulador
-  Teléfono Físico

**Fermat CBP 19.7**

**Comment by nelsondb** [comment]
@sanro14 @IsbetVR @nelsonalfo

**Comment by JeanFranco498** [comment]
En el nexus 7 con 5.0.0 pasa lo mismo. Y la única forma de salir de esta pantalla es cerrando el emulador 
![screenshot_1](https://cloud.githubusercontent.com/assets/19807906/16636236/db9657ca-43a4-11e6-8047-d77ab3f634b9.jpg)

**Comment by MaviDavsa** [comment]
El error persiste desde un teléfono físico, hay que reiniciar la apk para que vuelva a fermat pero no permite montar la foto desde la cámara, sale el Fermat no Responde.

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16665790/dccfcdb6-4452-11e6-941c-a2f6d2dc1800.jpg)

**Comment by yolandayancel** [comment]
Prueba 07-07-16
Caso 671 CBP 19.9
Nexus 5 6.0.0
Hora 03:40 aproximadamente para el logcat
[logcat 671.txt](https://github.com/Fermat-ORG/beta-testing-program/files/352913/logcat.671.txt)
En este emulador ocurre lo reportado. No deja crear el perfil con la camara.
![caso 671](https://cloud.githubusercontent.com/assets/17283358/16667279/b07ca25a-4459-11e6-970c-8d0dc7773ce5.png)

**Comment by yolandayancel** [comment]
Prueba 08-07-16
Caso 671 CBP 20.1
Nexus 5 6.0.0
Hora 08:03 am aproximadamente para el logcat
[logcat671.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354154/logcat671.txt)

En este emulador persiste el error. (al tomar la foto se queda en negra y luego sale este recuadro)

![caso 671](https://cloud.githubusercontent.com/assets/17283358/16686935/78ba869a-44e3-11e6-8544-5413bd5b7bbc.png)

**Comment by wendyduran90** [comment]
Con la versión 20.1 persiste el error , al momento de tomar la foto para crear el perfil la aplicación se cuelga. Esta prueba se realizo desde un teléfono móvil Blu life one con versión de android 4.4.4.
![screenshot_2016-07-08-08-32-49](https://cloud.githubusercontent.com/assets/20212920/16687872/0f79c708-44e9-11e6-9bed-0c41421860bf.png)

**Comment by yolandayancel** [comment]
Prueba 08-07-16
Caso 671 CBP 20.1
Nexus 5 6.0.0
Hora 08:00 am aproximadamente para el logcat
[logcat672.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354240/logcat672.txt)

En este emulador no deja tomar las fotos de la galeria. sale este recuadro y se sale de la apk.
![caso672](https://cloud.githubusercontent.com/assets/17283358/16688226/092ddc34-44eb-11e6-9f13-38344c442a5e.png)

**Comment by Gabymorillo** [comment]
En la versión 20.1 en el teléfono físico, permite seleccionar la imagen de la galería y tomar la foto sin problemas.

![screenshot_2016-07-08-10-28-30](https://cloud.githubusercontent.com/assets/17262077/16690742/5eacef86-44f7-11e6-9b55-2b8f877a63c7.png)

![screenshot_2016-07-08-10-28-13](https://cloud.githubusercontent.com/assets/17262077/16690765/7316e6d4-44f7-11e6-946a-074e61bc54a8.png)


![screenshot_2016-07-08-10-27-26](https://cloud.githubusercontent.com/assets/17262077/16690769/76e05a0c-44f7-11e6-8502-5c7018d64265.png)



![screenshot_2016-06-13-21-00-45](https://cloud.githubusercontent.com/assets/17262077/16690577/a40ec85c-44f6-11e6-8427-dc58492958a2.png)

**Comment by MaviDavsa** [comment]
En la versión 20.1 en el teléfono físico, permite seleccionar la imagen de la galería y tomar la foto sin problemas.

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16690995/a5ef2192-44f8-11e6-8ce6-59595fb2f5f9.jpg)

**Comment by marielis-urbina** [comment]
En la versión 20.1 de CBP puedo utilizar tanto la camara, como la galeria

![samsung](https://cloud.githubusercontent.com/assets/19353722/16691343/5940757e-44fa-11e6-95f1-aa4ffa1c98f5.png)

**Comment by dorzar1989** [comment]
En la version 20.1 de la CBP este error persiste de la siguiente manera: 
- Cuando abrí la cámara para tomar la foto de perfil, apareció una pantalla negra que duro como 20 Segundos, pero luego me apareció la respectiva pantalla de la cámara, donde logre tomar la foto, cuando le doy al Chulito o la Palomita para aceptar y estar de acuerdo con la foto que tome y la lleve para la pantalla de perfil me da error de "Recovering System..." 

- SCREENSHOTS: 

![screenshot_47](https://cloud.githubusercontent.com/assets/19670319/16692007/0ffa7e5c-44fd-11e6-8688-9561c84343ae.png)

![screenshot_48](https://cloud.githubusercontent.com/assets/19670319/16692012/1290108c-44fd-11e6-8212-75633eff1912.png)

![screenshot_49](https://cloud.githubusercontent.com/assets/19670319/16692017/14e003e2-44fd-11e6-8e20-0e4682b8be1c.png)


- LOGCAT: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354544/logcat.txt)

- MOVIL:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16691997/06498088-44fd-11e6-9397-d1882eb672a7.png)

**Comment by yolandayancel** [comment]
PRUEBA 11-07-16
Caso 671 CBP20.2
Nexus 5  6.0.0 api23 420dpi
Hora  aproximadamente para el logcat: 10:29am
[logcat671.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357294/logcat671.txt)


Persiste el error. Entra toma la foto (para el Broker) pero se queda la pantalla en negro y sale el recuadro:
![671 1](https://cloud.githubusercontent.com/assets/17283358/16734117/578e99ae-4752-11e6-9595-e95a2f494efb.png)

**Comment by sanro14** [comment]
Solucionado.

**Comment by yolandayancel** [comment]
PRUEBA 11-07-16
Caso 671 CBP20.3
Nexus 5 6.0.0 api23 420dpi
Hora aproximadamente para el logcat: 02:59pm
[6711.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357844/6711.txt)

Persiste el error
![671 3](https://cloud.githubusercontent.com/assets/17283358/16743235/5c2633a6-4779-11e6-90a7-922c80c1d3fe.png)

**Comment by yolandayancel** [comment]
PRUEBA 12-07-16
Caso 671 CBP20.4
Nexus 5 6.0.0 api23 420dpi
Hora aproximadamente para el logcat: 01:29pm
[logcat 671...txt](https://github.com/Fermat-ORG/beta-testing-program/files/359901/logcat.671.txt)

Ahora permite ingresar a la camara y toma la foto pero luego de tomar la foto.
![671](https://cloud.githubusercontent.com/assets/17283358/16776578/00a177a0-4834-11e6-9216-023b1971f4b2.png)
pero al clikera varias veces,  sale fermat:
![1](https://cloud.githubusercontent.com/assets/17283358/16776625/373fc820-4834-11e6-8505-90c95a4a0781.png)
![2](https://cloud.githubusercontent.com/assets/17283358/16776689/86e485fa-4834-11e6-9549-48c492d929ab.png)

**Comment by yolandayancel** [comment]
PRUEBA 13-07-16
Caso 671 CBP20.5
Nexus 5 6.0.0 api23 420dpi
Persiste el error.
![671](https://cloud.githubusercontent.com/assets/17283358/16803385/12a2b5a4-48d4-11e6-9a0b-c64d43fa0189.png)

**Comment by wendyduran90** [comment]
En la versión 20.5 persiste el error al tomar la foto desde la cámara , la aplicación colapsa y se cierra automáticamente. 
Esta prueba se realizo desde un móvil android con versión de adroid 4.4.4

![screenshot_2016-07-13-08-56-33](https://cloud.githubusercontent.com/assets/20212920/16804978/2952e2bc-48dc-11e6-8d8a-51625b3ae379.png)

![screenshot_2016-07-13-09-05-21](https://cloud.githubusercontent.com/assets/20212920/16804865/bc552dd2-48db-11e6-9224-34ee30638069.png)

**Comment by sanro14** [comment]
@nelsonalfo ve esto

**Comment by RubenSem** [comment]
En la version 20.6 sigue con el mismo error.
Google nexus 4.4.4 api 19
14-07-16

**Comment by nelsondb** [comment]
En la 20.7 Persiste el error.

![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/16883264/1a1a63f4-4a91-11e6-869d-0e6eb394f284.jpg)

**Comment by yolandayancel** [comment]
Prueba 15-07-16
Caso 671 CBP 20.7
Nexus 5 6.0
Persiste el error. (deja tomar la foto pero se pone la pantalla en negro.
![671](https://cloud.githubusercontent.com/assets/17283358/16883444/02f9798e-4a92-11e6-8daa-a4d01757abac.png)

**Comment by Gabymorillo** [comment]
Prueba: 18/07/16

Desde el teléfono físico, con la versión 20.7 permite tomar fotos en ambos profiles sin problemas.

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16919102/646cd418-4cd6-11e6-9850-7932e3bb63f6.png)

**Comment by yolandayancel** [comment]
Prueba 20-07-16
Caso 671 CBP 20.8
Nexus 5 6.0.0 api 23 420dpi
Persiste el error. (deja tomar la foto pero se pone la pantalla en negro.
![caso 671](https://cloud.githubusercontent.com/assets/17283358/17002856/5c8390fe-4e9b-11e6-8e98-c6b76f265c40.png)
![671 1](https://cloud.githubusercontent.com/assets/17283358/17002862/64e0a994-4e9b-11e6-970a-e88e93931571.png)

**Comment by yolandayancel** [comment]
PRUEBA 22-07-16
Caso 671 CBP 20.9
Nexus 5 6.0.0 api23 420dpi
Persiste el error
![22223](https://cloud.githubusercontent.com/assets/17283358/17067885/ec3683ce-501b-11e6-8ebd-0cf34300db9e.png)


Ahora permite ingresar a la camara y toma la foto pero luego de tomar la foto.

**Comment by Elbamarina** [comment]
cuando inicio la camara se muestra asi 
![image](https://cloud.githubusercontent.com/assets/20233056/17119364/62660b5e-5293-11e6-98c6-14350de3586f.png)
![image](https://cloud.githubusercontent.com/assets/20233056/17119423/be6abbe8-5293-11e6-95a5-3368d2d82ab2.png)

la unica forma de salirse es cerrando emulador

**Comment by dorzar1989** [comment]
En la version 21.0 de la CBP luego de varios intentos logre utilizar la camara y modificar la foto de mi Perfil de Customer; El primer intento antes de activarse la camara se salio de la app, al segundo intento entre a modificar perfil y me salio Fermat No Responde, al cuarto intento me salio Recovering From System, y al Cuarto intento logre cambiar la foto.

- Screenshot:

![screenshot_81](https://cloud.githubusercontent.com/assets/19670319/17122262/e6673bee-52a7-11e6-8eb8-5bfb3fcdb878.png)

![screenshot_82](https://cloud.githubusercontent.com/assets/19670319/17122263/e6753e56-52a7-11e6-81a1-7aff7b858508.png)

![screenshot_83](https://cloud.githubusercontent.com/assets/19670319/17122264/e6846e08-52a7-11e6-96dc-0735193628ea.png)

- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17122276/f316bd7e-52a7-11e6-8505-75cd12b41cda.png)

**Comment by marielis-urbina** [comment]
En la versión 21.0 de CBP, este error no ocurre en mi emulador me permite editar la foto con la cámara perfectamente.

![foto 1](https://cloud.githubusercontent.com/assets/19353722/17138751/be5e005c-530f-11e6-8416-574cd29c46c8.png)

![fotoss](https://cloud.githubusercontent.com/assets/19353722/17138755/c3734ca0-530f-11e6-8eff-081476bcdb9e.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17138698/80de600a-530f-11e6-8fb2-aa93012c65c0.png)

**Comment by GeronimoVierma** [comment]
En la versión 21.0 de CBP no me da problema cuando me tomo la foto del Broker pero cuando voy a tomarme la foto del Customer me da error:


![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/17138764/cb06fa0c-530f-11e6-8ded-2a8d96d3d78f.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/17138784/e4ac5196-530f-11e6-83a3-4b115cca8bb6.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/383861/logcat.txt)

**Comment by camilavaleria** [comment]
En la versión 21.0 de CBP, este error no ocurre en el emulador con el que estoy trabajando, permite editar la foto con la cámara perfectamente, tal y como se señala a continuacion:

![image](https://cloud.githubusercontent.com/assets/18740418/17139161/464bbcb0-5311-11e6-8506-588bd9b20020.png)

![image](https://cloud.githubusercontent.com/assets/18740418/17139185/5fef25e4-5311-11e6-9bfb-87c777836c1f.png)

EMULADOR DE PRUEBA

![image](https://cloud.githubusercontent.com/assets/18740418/17139211/811706a6-5311-11e6-99d7-abb1df17c299.png)
