### ISSUE TITLE
CBP - PROFILES CUSTOMER - CARACTERES SE REINICIAN.

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#672]
#### Nombre pantalla

Identities Customers

### Nombre de la Aplicación 

CBP

-----

##### Reporte de error: 

   *Cuando escribimos nuestro nombre y nos queda cierta cantidad de caracteres y al momento que colocamos una imagen, esos caracteres se reinician pero cuando escribimos de nuevo vuelve a la cantidad restante.

##### Screenshot o Capture de pantalla:

![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/16637587/1a0a91e8-43ae-11e6-92c6-3753f2bd373c.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/20217119/16637588/1ae69bca-43ae-11e6-9a37-5c6ef2097b05.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/20217119/16637590/1bd2afba-43ae-11e6-9829-0e443cde728a.jpg)

##### Pasos exactos para reproducir el error:

 *Irnos a las identidades de customer, crear una identidad, escribimos un nombre "Jesus Duarte" con ese nombre nos quedan restantes 18 caracteres, ponemos una imagen de perfil, veremos que los caracteres se reinician a 30 pero cuando volvemos a escribir en realidad quedan los 18 caracteres ya mencionados.

##### Inserta Archivo aLogcat: 

 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/351082/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

![screenshot_5](https://cloud.githubusercontent.com/assets/20217119/16637681/da0bc778-43ae-11e6-89a8-b8afedbcb127.jpg)

- [x] Emulador

**FERMAT CBP 19.8**

**Comment by nelsondb** [comment]
@sanro14 @IsbetVR @nelsonalfo

**Comment by abicelis** [comment]
@nelsondb Te aviso cuando este arreglado

**Comment by MaviDavsa** [comment]
En la versión del CBP 19.9 Persiste el error...

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16665532/f63322ae-4451-11e6-8f3d-a05c5fbdf781.jpg)

**Comment by abicelis** [comment]
@nelsondb @MaviDavsa Revisen la proxima version, se arreglo el bug aqui y en la Broker Identity.

**Comment by nelsondb** [comment]
@abicelis Saludos Alejandro, en la versión 20.0 sigue el error.

![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/16674211/d3668482-4483-11e6-9240-4c2b6f4faf1e.jpg)

![screenshot_2](https://cloud.githubusercontent.com/assets/20217119/16674212/d53760ce-4483-11e6-9b61-8629043a8544.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/20217119/16674216/d803a8c6-4483-11e6-93a8-21f8f1469629.jpg)

**Comment by IsbetVR** [comment]
En la versión 20.1 de CBP persiste este error, no lleva el conteo de caracteres al subir o actualizar la foto de perfil. Sucede lo mismo con el perfil del broker.

**Comment by yolandayancel** [comment]
Prueba 18-06-2016
Caso 672      CBP V 20.1
Nexus 5 6.0.0
hora aproximada: 8:28am logcat
[logcat672.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354195/logcat672.txt)

En este emulador, no se puede probar el caso ya que al tratar de tomar una de las fotos de galería sale el siguente cuadro y se sale de la aplicación.
![caso672](https://cloud.githubusercontent.com/assets/17283358/16687347/183cf002-44e6-11e6-938a-abd86e7a02ff.png)

**Comment by abicelis** [comment]
Va en la 20.2 :P en la 20.0 no pudo ser incluido el fix, ni en la 20.1, 20.2!!

**Comment by MaviDavsa** [comment]
@abicelis Nada que se arregla este error...

![error 1](https://cloud.githubusercontent.com/assets/17273005/16709700/fcb2a4de-45e5-11e6-8473-1f6bedb6ffce.JPG)

Dispositivo para prueba.

![tlf google nexus 5 5 0](https://cloud.githubusercontent.com/assets/17273005/16709702/0973c1bc-45e6-11e6-9f6c-d901917ee868.JPG)

**Comment by nelsondb** [comment]
**Solucionado en la  CBP 20.3**

![image](https://cloud.githubusercontent.com/assets/20217119/16736480/162d76d4-475b-11e6-9448-c0f3614832fb.png)

**Comment by nelsondb** [comment]
El conteo de caracteres ya está bien pero el cursor lo manda al inicio luego de colocar la imagen.

![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/16736965/4eea9112-475d-11e6-8056-2d8f6636b2a4.jpg)


![screenshot_2](https://cloud.githubusercontent.com/assets/20217119/16736966/506e9e84-475d-11e6-9c02-89cb8c044b77.jpg)
