### ISSUE TITLE
CHAT - NÚMERO NOTIFICACIÓN PERMANENTE SIN TENER CHATS ABIERTOS

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#673]
#### Nombre pantalla
Home 

### Nombre de la Aplicación 
CHAT

-----

##### Reporte de error: 

   *Al abrir la aplicación chat, aparece siempre un numero uno en rojo a pesar de no poseer ningún chat abierto, ni tener ningún contacto en la aplicación 

##### Screenshot o Capture de pantalla:

![pasted_image_at_2016_07_06_07_36_pm](https://cloud.githubusercontent.com/assets/19807906/16638167/113ee4c4-43b3-11e6-84e1-db39199501a5.png)

![pasted_image_at_2016_07_06_07_37_pm](https://cloud.githubusercontent.com/assets/19807906/16638646/d5bb49a2-43b6-11e6-991e-5de3d6dc3660.png)

##### Pasos exactos para reproducir el error:

 *Abrir chat
Crear perfil
A penas estoy en la pantalla de inicio de chat 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/351117/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/19807906/16638678/246beb7e-43b7-11e6-8a2f-550904fd1963.png)

- [x] Emulador
- [] Teléfono Físico

**Comment by JeanFranco498** [comment]
@MaviDavsa @RoyGF

**Comment by JeanFranco498** [comment]
Version de chat v.19.9 
Nexus 4 android 5.1.0
![screenshot_6](https://cloud.githubusercontent.com/assets/19807906/16667202/40b7fc58-4459-11e6-9124-e0ba3591807b.jpg)


![screenshot_5](https://cloud.githubusercontent.com/assets/19807906/16667248/892527f4-4459-11e6-9b3a-43e094fbdda3.jpg)

**Comment by franciscoj961** [comment]
Versión de chat v.19.9
Google Nexus 5 - 5.1.0

![77](https://cloud.githubusercontent.com/assets/20245988/16668554/7a0e8b2e-445f-11e6-8394-7dedd137b159.PNG)

![777](https://cloud.githubusercontent.com/assets/20245988/16668558/7fa19d9c-445f-11e6-8af8-165a00c63561.PNG)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso 613     CHAT-CBP V 20.1
Emulador Genymotion:
Nexus 5 5.0.0 api 21 480dpi
Hora aproximada del logcat:01:47pm
[logcat613.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354793/logcat613.txt)
No aparece lo reportado en este emulador.
![caso 613](https://cloud.githubusercontent.com/assets/17283358/16696430/d7c4e106-4512-11e6-96c8-a1732e9ded92.png)
