### ISSUE TITLE
COMMUNITY_CBP_ EL ENVIO DE CONEXION NO QUEDA REGISTRADO 

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#674]
#### Nombre pantalla
Browser y connections

### Nombre de la Aplicación 
Crypto broker community

-----

##### Reporte de error: 

   *En la version 19.9 de CBP, al ingresar al la community y envia la solicitud a un usuario, se le coloca un ganchito gris, al salir de la community y volver a ingresar ya no lo sale nada y debo enviar la solicitud de nuevo, y acepta el envio de la solicitud de nuevo, de igual manera cuando uno de los contactos acepta la solicitud y aparece en la pantalla de conexiones, estos siguen apareciendo en la pestaña de browser sin el ganchito de color verde, sino como si nunca le hubiese enviado solicitud..

##### Screenshot o Capture de pantalla:

![screenshot_7](https://cloud.githubusercontent.com/assets/17274154/16668488/327eb914-445f-11e6-9a19-7faac7d5fe58.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/17274154/16668494/391bfb38-445f-11e6-93ce-61c674e935d1.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/17274154/16668499/3c83d8d6-445f-11e6-84ab-8abd6e78c528.png)

##### Pasos exactos para reproducir el error:

 *enviar solicitud a un contacto de la community, salir de alli y al ingresar de nuevo se presentara el error

enviar solicitud al contacto, al aceptar la solicitud, revisar la pestaña de connections y luego ingresar a la pestaña browser y alli se reflejara el error

##### Inserta Archivo aLogcat: 

 *hora aproximada: 4:06pm
 
  ------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16668593/aa6e8382-445f-11e6-88ac-5daa784297b1.png)

**Comment by AdryCanonico** [comment]
@nelsonalfo

**Comment by sanro14** [comment]
Archivo Log https://www.dropbox.com/s/0ndasdnaidh2pxf/Maydi-genymotion-log%20674.zip?dl=0

**Comment by arosiopr** [comment]
En mi caso sucede casi lo mismo que Maydi, solo que no envia la solicitud de nuevo, dice que ya ha sido enviada, pero igual no sale el chulito. hora de intento de solicitud 4:13 pm del emulador

![screenshot_62](https://cloud.githubusercontent.com/assets/5313326/16668995/47c25748-4461-11e6-8766-70dc0c36f629.png)

Emulador

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16669007/5917fdea-4461-11e6-838a-26645ac5556b.png)

Logcat
[Google Nexus 4 - 4.4.4 - API 19 - 768x1280-logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/353033/Google.Nexus.4.-.4.4.4.-.API.19.-.768x1280-logcat.zip)

**Comment by nelsonalfo** [comment]
en la siguiente version de la app debe estar solucionado

**Comment by arosiopr** [comment]
el error fue solucionado en la version 20.1 de CBP

**Comment by MaviDavsa** [comment]
Estoy probando desde un teléfono físico y el error fue solucionado! 

![screenshot_2016-07-08-09-28-52](https://cloud.githubusercontent.com/assets/17273005/16688963/975d3182-44ee-11e6-88e2-8588a6b1f39c.jpg)

![screenshot_2016-06-08-18-20-13](https://cloud.githubusercontent.com/assets/17273005/16688983/aee568b0-44ee-11e6-9681-a416af33f8f7.jpg)
