### ISSUE TITLE
CBP - NO SE REFLEJA LA NEGOCIACIÓN EN LAS WALLET 

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#675]
#### Nombre pantalla

Customer Wallet

### Nombre de la Aplicación 

CBP v19.9

-----

##### Reporte de error: 

   *Al finalizar un contrato dice que se completo con exito pero, en ninguna de mis wallet, ni en la bank se ve reflejada esa negociación. 
En cambio en al broker si se le ve reflejada la negociación
 
##### Screenshot o Capture de pantalla:

![screenshot_10](https://cloud.githubusercontent.com/assets/19807906/16669569/41046998-4464-11e6-8b49-b0e03cff3818.jpg)

![screenshot_11](https://cloud.githubusercontent.com/assets/19807906/16669581/5079eab0-4464-11e6-8f27-a9fd951d6452.jpg)

![screenshot_12](https://cloud.githubusercontent.com/assets/19807906/16669588/5c17e156-4464-11e6-865a-d3849bcd4226.jpg)

![screenshot_13](https://cloud.githubusercontent.com/assets/19807906/16669593/66d385a0-4464-11e6-9495-8c5ca5de2eb9.jpg)

![screenshot_8](https://cloud.githubusercontent.com/assets/19807906/16669612/79322422-4464-11e6-8d36-bf8ba953ef4a.jpg)

![screenshot_9](https://cloud.githubusercontent.com/assets/19807906/16669620/81dcc82a-4464-11e6-9b1b-b9306ebb0f10.jpg)

##### Pasos exactos para reproducir el error:

 * 
1. Finalizar Negociación
3. Corroborar los detalles de la negociacion 
2. Revisar cada wallet y sus movimientos
 

##### Inserta Archivo aLogcat: 

 
  
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/353046/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
-  Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_14](https://cloud.githubusercontent.com/assets/19807906/16669745/23ee4940-4465-11e6-8121-d02ed722ae18.jpg)

**Comment by JeanFranco498** [comment]
@nelsonalfo @sanro14 @IsbetVR

**Comment by JeanFranco498** [comment]
Las capturas del broker (se le hizo difícil comenzar y salio de turno)


![1](https://cloud.githubusercontent.com/assets/19807906/16670632/214ca9f8-4469-11e6-8a3d-f733fc4a4b4e.jpg)


![3](https://cloud.githubusercontent.com/assets/19807906/16670641/2843caf2-4469-11e6-9a0f-84429a5e302a.jpg)

**Comment by arosiopr** [comment]
En la versión 20.3 de CBP me descontaron el pago como customer, y al broker llego el pago. Pero a mi como customer no me llega lo que estoy comprando, y al broker no se lo descuentan.

**Comment by maydiamc** [comment]
20.7 de cbp

no se reviso este issue debido a que no se culminaron contratos por problemas de conexion

**Comment by nelsondb** [comment]
**20.8 - terminamos un contrato y al compañero le llegaron los dolares y a mi me llegaron los BTC pero mi pago jamás se desconto de la cash wallet.**

**ahi vemos que llegaron los BTC y los dolares se fueron.**

![screenshot_3](https://cloud.githubusercontent.com/assets/20217119/17007401/5c32ea1c-4eb6-11e6-8d02-74fad1577fbe.jpg)

**Y mis $$ siguen intactos.**

![screenshot_9](https://cloud.githubusercontent.com/assets/20217119/17007406/6f66791e-4eb6-11e6-8e3f-43f35b52bd1c.jpg)


**Screenshot DEL COMPAÑERO**

![screenshot](https://cloud.githubusercontent.com/assets/20217119/17007433/c38907a0-4eb6-11e6-8bd9-2c98793cffff.jpg)

**Comment by MaviDavsa** [comment]
Error en el planteamiento.
