### ISSUE TITLE
CBP_Broker Identity_ Boton de visibilidad con error

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#676]
#### Nombre pantalla
pantalla principal

### Nombre de la Aplicación 
Broker Identity

-----

##### Reporte de error: 

   *En el boton de visibilidad al cambiarlo, arroja el error de fermat no responde

##### Screenshot o Capture de pantalla:

![screenshot_10](https://cloud.githubusercontent.com/assets/17274154/16691404/a092285a-44fa-11e6-80e0-4b0312d23666.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/17274154/16691409/a54e0954-44fa-11e6-94bb-71938f45c5d4.png)

##### Pasos exactos para reproducir el error:

- ingresar en broker identity luego de crear el perfil
- cambiar de visible (predeterminado) a no visible
- se queda cargando y luego arroja el fermat no responde
- al revisar de nuevo si se hizo el cambio a no visible a pesar del error

##### Inserta Archivo aLogcat: 

hora aprox: 9:10am
subido a dropbox
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16691584/2a1c26de-44fb-11e6-8c1c-14b8b665ead5.png)

**Comment by yolandayancel** [comment]
Prueba 08-07-2016
Caso      CBP V 20.1
Emulador Genymotion:
Nexus 5 5.1.0 api 22 480dpi
Hora aproximada del logcat 9:28am
En este emulador ocurre lo reportado.
[logcat MAY.txt](https://github.com/Fermat-ORG/beta-testing-program/files/354527/logcat.MAY.txt)

![may 2](https://cloud.githubusercontent.com/assets/17283358/16691729/cde73f06-44fb-11e6-93ec-023d905681f0.png)

**Comment by wendyduran90** [comment]
En la versión 20.1, al momento de cambiar la identidad en la profiles-brokers de visible a no-visible  se queda cargando y luego se cierra la aplicación. Esta prueba se realizo desde un telefono movil Blu life one con version de android 4.4.4.
![screenshot_2016-07-08-09-15-46](https://cloud.githubusercontent.com/assets/20212920/16692379/89487100-44fe-11e6-919a-9692ca0486c6.png)

**Comment by camilavaleria** [comment]
En la versión 20.1, al momento de cambiar la identidad en la profiles-brokers de no visible a visible se queda cargando y aparece el mensaje " error trying to edit the identity" .

![image](https://cloud.githubusercontent.com/assets/18740418/16692843/95ee9874-4500-11e6-81f5-4cfc0e45c9b3.png)

Emulador de prueba:

![image](https://cloud.githubusercontent.com/assets/18740418/16692878/b68ebf8c-4500-11e6-811f-0d99b6da3514.png)

**Comment by IsbetVR** [comment]
En la versión 20.2 de CBP cambié el nombre del perfil de Broker y al darle "UPDATE" se colgó la aplicación

![screenshot_11](https://cloud.githubusercontent.com/assets/19142276/16730897/5bf347ec-4743-11e6-91ae-5a4775057487.jpg)

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16730903/66d2d312-4743-11e6-8d9d-da3efa381076.jpg)

**Comment by IsbetVR** [comment]
En la versión 20.3 de CBP, al actualizar el es "status" me sale el siguiente error:

![screenshot_21](https://cloud.githubusercontent.com/assets/19142276/16741260/7e0285b4-4770-11e6-98db-387bce9afa97.jpg)

- [x] Emulador
- Google Nexus 4
- Android 4.3
- 320 dpi

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16741285/958d075e-4770-11e6-9834-981be21adc6d.jpg)

**Comment by dorzar1989** [comment]
En la Version 20.4 de la CBP persiste este error.

Pasos: 
 - Entre a la Crypto Broker
 - Cambiel el boton de Visible a No Visible y luego de No Visible a Visible
 - Luego hice Click en el -boton Update y se quedo cargando hasta que aparecio "Fermat No Responde"

- Screenshots:

![screenshot_69](https://cloud.githubusercontent.com/assets/19670319/16748960/38155c96-4795-11e6-99f4-bfd117144bc9.png)

![screenshot_70](https://cloud.githubusercontent.com/assets/19670319/16748965/3ad16ed4-4795-11e6-8d4a-6369f40d755c.png)

![screenshot_71](https://cloud.githubusercontent.com/assets/19670319/16748971/3edc5340-4795-11e6-87ba-033701889ee9.png)


- Hora: 

6:18 pm

- LogCat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/358211/logcat.txt)

- Movil: (Emulador)

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16749087/d8900e5a-4795-11e6-88d2-cc314b36e6fd.png)

**Comment by sanro14** [comment]
@nelsonalfo

**Comment by IsbetVR** [comment]
Esto se solucionó en la versión 20.5 CBP, ya no se "cuelga" la aplicación al cambiar el "status"

#### Dispositivo de prueba

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16803682/bf2adada-48d5-11e6-9544-7290e5814676.jpg)

**Comment by maydiamc** [comment]
solucionado en la version 20.5 de cbp
