### ISSUE TITLE
BITCOIN WALLET - COMMUNITY -  ICONO DE GEOLOCALIZACIÓN SE CORTA AL AGRANDARSE EL BUSCADOR

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#677]
#### Nombre pantalla

CBP - Crypto Wallet Users

### Nombre de la Aplicación 

CBP

-----

##### Reporte de error: 

   *Cuando seleccionamos en la barra de búsqueda esta se agranda y hace que se corte el icono de geolocalización

##### Screenshot o Capture de pantalla:

![screenshot_6](https://cloud.githubusercontent.com/assets/20217119/16699896/ee92c058-4524-11e6-9180-34026e7b102b.jpg)

![screenshot_5](https://cloud.githubusercontent.com/assets/20217119/16699903/f4b5924e-4524-11e6-9b2a-3612acef1a9c.jpg)
 

##### Pasos exactos para reproducir el error:

-Entrar en la communities
-irnos a la Crypto Wallet community.
-Seleccionar para buscar a un usuario
-En ese momento se agrandara tanto la barra que se cortara la de geolocalización 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/355020/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
-  Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/20217119/16699983/71d6b5a0-4525-11e6-8b13-cd567b41dca7.jpg)

CBP 20.1

**Comment by nelsondb** [comment]
@AdryCanonico @nattyco

**Comment by nattyco** [comment]
@AdryCanonico hay que aplicar el diseño nuevo en la community y la identidad de los wallet users, asi que las pantallas van a cambiar y tendran que ser verificadas con lo nuevo

**Comment by AdryCanonico** [comment]
Ok @nattyco estaré al pendiente para probarlo.

**Comment by Gabymorillo** [comment]
En la versión 20.4 desde el teléfono físico persiste este error. 

![screenshot_2016-07-12-13-16-35](https://cloud.githubusercontent.com/assets/17262077/16776453/6a787238-4833-11e6-85ff-e5430e6efc40.png)
![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16776459/71037396-4833-11e6-8b50-5ce31d8e04e5.png)

**Comment by nelsondb** [comment]
**En la versión 20.5 Persiste el error.**

![image](https://cloud.githubusercontent.com/assets/20217119/16820691/50954be6-4920-11e6-9231-8cf5135bfa40.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.6 - CBP persiste el error:

![geo](https://cloud.githubusercontent.com/assets/19883115/16859805/f36acd70-49ff-11e6-9718-4b42db98128f.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16859812/061d6464-4a00-11e6-8e2a-403e3e209437.png)

**Comment by IsbetVR** [comment]
En la versión 20.7 de CBP, con el nuevo diseño de las communities de la Bitcoin Wallet, ya no corta el botón 

![screenshot_60](https://cloud.githubusercontent.com/assets/19142276/16876525/288829ae-4a72-11e6-8afb-e3fb1db9a8f4.jpg)

#### Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16876538/30de5376-4a72-11e6-96d5-4aeeda72dd5c.jpg)

**Comment by GeronimoVierma** [comment]
En la versión 20.7 de CBP el icono de geolocalización desaparece en la communities de la Bitcoin Wallet (teléfono físico 4.1.1)

![screenshot_2016-07-15-11-42-13](https://cloud.githubusercontent.com/assets/19883115/16880355/daccfd64-4a82-11e6-8085-ca875a228e6b.png)

Teléfono físico:

![screenshot_2016-07-14-18-31-45](https://cloud.githubusercontent.com/assets/19883115/16880374/f2bcdaac-4a82-11e6-8a60-d9fce4bb301a.png)

**Comment by nelsondb** [comment]
**Solucionado en la 20.7 - Emulador.**
![image](https://cloud.githubusercontent.com/assets/20217119/16915638/a8fd74c6-4cc6-11e6-8713-8372bebcf320.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/20217119/16915649/b60f3442-4cc6-11e6-80be-32da60457729.jpg)

**Comment by marielis-urbina** [comment]
En la versión 20.7 día 18/7/16 de CBP solucionado

![geoc](https://cloud.githubusercontent.com/assets/19353722/16917875/69b0a29c-4cd1-11e6-8801-5f7462edfb52.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16917881/6d36386e-4cd1-11e6-9658-9301eef54833.png)

**Comment by JeanFranco498** [comment]
En la version 20.8 de CCP ya no ocurre el problema 

![btc](https://cloud.githubusercontent.com/assets/19807906/16967487/315ef7ac-4dd7-11e6-93aa-64ccb145d6ab.jpg)

![no pasa](https://cloud.githubusercontent.com/assets/19807906/16967496/361d2f84-4dd7-11e6-81c5-2c4e39c727c5.jpg)
