### ISSUE TITLE
Bitcoin Wallet_External user: botones de diferentes tamaños

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#678]
#### Nombre pantalla

Create external contact

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   *En el formulario de crear contacto externo, el icono de barcode sale muy pequeño, ademas el titulo paste address no esta centrado, y esta demas a mi parecer.

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/16700930/cd8faa96-452a-11e6-9fe3-cb219abdd9d2.png)

##### Pasos exactos para reproducir el error:

 *ingresar a external user y abrir el formulario de create external contact

 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16700953/f0bee4b4-452a-11e6-8ea3-9dd328e3b5ce.png)

**Comment by maydiamc** [comment]
@nattyco version 20.1 CBP

**Comment by IsbetVR** [comment]
En la versión 20.3 de CBP, persiste la diferencia en el tamaño de los botones para External User, y en mi caso corta el segundo botón (scan)

![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/16740318/8beec86c-476c-11e6-8854-6f28e9105969.jpg)

- [x] Emulador
- Google Nexus 4
- Android 4.3
- 320 dpi
- API 18 768x1280


![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16740358/c159a026-476c-11e6-9ec1-6dfb0ee3ba6d.jpg)

**Comment by maydiamc** [comment]
En la version 20.4 sigue sucediendo el mismo problema grafico

**Comment by IsbetVR** [comment]
En la versión 20.5 de CBP persiste el detalle gráfico, diferencia de tamaño y se corta el segundo botón (scan)

**Comment by arosiopr** [comment]
En la version 20.6 de CBP se soluciono

![screenshot_116](https://cloud.githubusercontent.com/assets/5313326/16839772/dfe9949a-499e-11e6-94df-ef831ddf72e5.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16839781/ed34b5bc-499e-11e6-9b2b-ee0a7669b6d5.png)

**Comment by IsbetVR** [comment]
Corregido en la versión 20.6 CBP

![screenshot_37](https://cloud.githubusercontent.com/assets/19142276/16840224/85448ace-49a1-11e6-8bd7-760fad65a39f.jpg)

#### Probado en emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16840237/93f711a4-49a1-11e6-8c91-9605b33a22f4.jpg)

**Comment by IsbetVR** [comment]
Closed #678
