### ISSUE TITLE
Communities - Cruza los perfiles que muestra en las comunidades

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#679]
### CBP v20.2

-----

##### Reporte de error: 

   *Teniendo perfil de Broker, luego de configurar las wallets correspondientes al Broker, me metí en las communities de Customer y me salen perfiles de Broker (Pantalla 1). No debería, debería salir sólo perfiles de Customer.

##### Pantalla 1

![screenshot_13](https://cloud.githubusercontent.com/assets/19142276/16731491/5cb982ba-4746-11e6-81ad-0e99c5925e2e.jpg)

##### Pasos exactos para reproducir el error:

1. Hice el perfil de Broker
2. Configuré las wallets asociadas (Crypto Broker, Banking y Cash)
3. Me metí en las communities de Customer y me salen muchos perfiles de broker creados tanto de la semana pasada como de hoy (11/07/2016 en la mañana)

------

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357136/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Verisón de android 4.3
- 320 dpi
- API 18 - 768x1280

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16731751/cdcceaf4-4747-11e6-8dda-54ec20543244.jpg)

**Comment by yolandayancel** [comment]
PRUEBA 11-07-16
Caso 679 CBP 20.2 Community-customer
Nexus 5 5.0.0 api 21 480dpi
Logcat Hora aproximada: 09:09am
[logcatERROR HOY 2.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357169/logcatERROR.HOY.2.txt)

Revisando la comunnity de los customer, aparecian perfiles de broker de los compañeros testing (Como es el caso de Isbet) de la mañana.
![isbet](https://cloud.githubusercontent.com/assets/17283358/16732201/fc1af264-4749-11e6-869a-a52046febc52.jpg)


![error 3](https://cloud.githubusercontent.com/assets/17283358/16732124/902bd9ba-4749-11e6-88e8-9fc84b523fd0.png)

**Comment by sanro14** [comment]
Solucionado.
