### ISSUE TITLE
CBP - Borra la configuración de las Crypto 

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#680]
### CBP v20.2

-----

##### Reporte de error: 

   *Teniendo perfil de broker, configuré la Crypto Broker y demás wallets asociadas, cerré el emulador y al volver a abrir, entro a la Crypto Broker y me borró la configuración, mostrándome que volviera a seleccionar las wallets asociadas con las que deseo trabajar (Pantalla 1). Además tal como lo muestro en la Pantalla 2, la Banking Wallet refleja la transacción que hice a través de la broker wallet, e igualmente en la Pantalla 3, la Cash Wallet refleja la transacción que hice a través de la broker wallet.

##### Pantalla 1

![screenshot_15](https://cloud.githubusercontent.com/assets/19142276/16732908/4b3dc49a-474d-11e6-957f-ed29ee89eb07.jpg)

##### Pantalla 2

![screenshot_16](https://cloud.githubusercontent.com/assets/19142276/16732919/5a2f8fc4-474d-11e6-9f57-c1506698c3d3.jpg)

![screenshot_17](https://cloud.githubusercontent.com/assets/19142276/16732938/67e87ef0-474d-11e6-8c26-b336aeb94a36.jpg)

##### Pantalla 3

![screenshot_18](https://cloud.githubusercontent.com/assets/19142276/16732952/7263aa08-474d-11e6-9e2c-aec4ed4cd90c.jpg)

-----

##### Pasos exactos para reproducir el error:

1. Hice el perfil de Broker
2. Configuré la Crypto Broker y demás wallets asociadas (Banking y Cash)
3. Me metí en la banking y Cash wallet y les hice depósitos para luego a través de la Crypto Broker en el stock hacer las transacciones correspondientes para los depósitos
4. Revisé las communities para verificar conexiones que me hayan enviado
5. En varias ocasiones entré a la crypto broker
6. Cerré el emulador y volví a abrir, al revisar la Crypto Broker me sale que debía configurarla como si estuviese ingresando por primera vez a la Wallet

------

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357232/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Versión de Android 4.3
- 320 dpi
- API 18 768x1280

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16733154/554754a0-474e-11e6-9f81-b98519e60ab7.jpg)

**Comment by IsbetVR** [comment]
@nelsonalfo

**Comment by yolandayancel** [comment]
Prueba 11-07-16
Caso 680 CBP 20.2 Crypto customer
Nexus 5 5.0.0 api21 480dpi
logcat hora aproximada:10:03am
[logcatborra crypto.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357272/logcatborra.crypto.txt)

Teniendo configurada la crypto customer, esta se me congelo, le clike para salir de la crypto y se salio de la apk. Al ingresar nuevamente me borro todos los datos.
![borra crypto customer](https://cloud.githubusercontent.com/assets/17283358/16733685/8f71cff0-4750-11e6-97dd-9d8b5372b601.png)
![borra crypto customer 1](https://cloud.githubusercontent.com/assets/17283358/16733689/95c7ebdc-4750-11e6-9305-df34f82d487d.png)

**Comment by marielis-urbina** [comment]
En la versión 20.2 de CBP. Teniendo perfil de Customer, configuré la Crypto Customer al cerrar el emulador y al volver a abrir, entro a la Crypto Customer, me borra toda la configuración de esta, localización y Bank

![loc](https://cloud.githubusercontent.com/assets/19353722/16733537/f1501840-474f-11e6-8558-2da5434b6fe0.png)

![bnc](https://cloud.githubusercontent.com/assets/19353722/16733549/f9393b18-474f-11e6-9209-4fa565970b85.png)

Despues

![loc0](https://cloud.githubusercontent.com/assets/19353722/16733568/05d10f86-4750-11e6-8de6-9b6a486a5cab.png)

![banc0](https://cloud.githubusercontent.com/assets/19353722/16733575/0c3196de-4750-11e6-87cb-b31a9860384b.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16733604/2e05abb0-4750-11e6-832c-a6f163362f93.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/357274/logcat.txt)

**Comment by camilavaleria** [comment]
Probando en mi emulador la versión de la CBP 20.2,  sucede algo similar, luego de crear el perfil y configurar la cripto customer, se borran por completo los datos al reiniciarlo tal como se muestra a continuacion;

![image](https://cloud.githubusercontent.com/assets/18740418/16733850/35886cb4-4751-11e6-89a9-6e188c0f247b.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16733866/4bdc976a-4751-11e6-8a3d-738224cf9cfd.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16733879/5c530eee-4751-11e6-95de-5d03721e87f9.png)

Luego ;

![image](https://cloud.githubusercontent.com/assets/18740418/16734001/d865f244-4751-11e6-83dd-ac7690914755.png)

EMULADOR DE PRUEBA;

![image](https://cloud.githubusercontent.com/assets/18740418/16734023/f2d3d8b2-4751-11e6-9b4d-39a17b379889.png)

**Comment by arosiopr** [comment]
en la version 20.3 de CBP se soluciono esto en el caso de los customer

**Comment by RoyGF** [comment]
@arosiopr  y en el caso del broker sigue el problema?

**Comment by IsbetVR** [comment]
En la versión 20.3 CBP, para el broker ya no borra la configuración

**Comment by RubenSem** [comment]
En la versión 20.3 de CBP se soluciono en el caso de los brokers, por favor cerrar caso.

**Comment by yolandayancel** [comment]
Prueba 14-07-16
Caso 680 CBP 20.6
Nexus 5. 5.0.0 adi21 480dpi
Hola del logcat:
[logcat Borra Bancos.zip](https://github.com/Fermat-ORG/beta-testing-program/files/364087/logcat.Borra.Bancos.zip)
Despues de realizada varias negociaciones, reviso los bancos en el setting de la crypto customer y me habia borrado los bancos por segunda vez.
![borra los bancos](https://cloud.githubusercontent.com/assets/17283358/16844644/f265f964-49b3-11e6-9c67-78e30fcda9ea.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by arosiopr** [comment]
en la version 20.7 de CBP en el caso de mi emulador no se ha presentado este error

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16919070/48f14c64-4cd6-11e6-891b-b3695e06af87.png)

**Comment by dorzar1989** [comment]
En la version 20.7 de la CBP Persiste el error

- Fecha: 18/07/20016

- Screenshot:

![screenshot_96](https://cloud.githubusercontent.com/assets/19670319/16919830/2b109576-4cd9-11e6-91e4-28d7b1620553.png)

![screenshot_97](https://cloud.githubusercontent.com/assets/19670319/16919838/2e270e34-4cd9-11e6-8360-2cf10ceebbba.png)


- Movil:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16919845/3647860c-4cd9-11e6-9408-51b53abe83c7.png)

**Comment by yolandayancel** [comment]
Prueba 20-07-16
Caso 680 CBP 20.8  Crypto customer
Nexus 5 5.0.0 api21 480dpi
Ya no borra los datos..
![680](https://cloud.githubusercontent.com/assets/17283358/17005732/b4b8f38c-4ea9-11e6-87e9-af9b5c43ef98.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.8- CBP no se ha presentado el error (broker):

![wallets](https://cloud.githubusercontent.com/assets/19883115/17007450/dd375df0-4eb6-11e6-8e97-ecb7da63bc49.png)

![css](https://cloud.githubusercontent.com/assets/19883115/17007545/a57cfbee-4eb7-11e6-8ad6-f902bb461687.png)


![chi](https://cloud.githubusercontent.com/assets/19883115/17007500/54cc2454-4eb7-11e6-9554-3cc18762c4e8.png)

**Comment by MaviDavsa** [comment]
Solucionado!
