### ISSUE TITLE
CBP - Crypto Broker Community - Search bug

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/beta-testing-program#681]
### Nombre de la Aplicación 

Crypto Broker Community

-----

##### Reporte de error: 

   * La Crypto Broker Community despues de buscar un broker en el buscador, al cancelarla y cargar mas brokers, no carga la infromacion de los brokers

##### Video del Error:

 * https://youtu.be/7l-Fc0_Bbk8

##### Inserta Archivo aLogcat: 

No se lanza ninguna excepcion, carga los datos pero no los pinta en la pantalla
  
------

#### Dispositivo desde donde se realizo la prueba 

![screenshot from 2016-07-11 19 05 55](https://cloud.githubusercontent.com/assets/16577032/16749753/a49ae6b0-479a-11e6-91e9-91f82d4c4329.png)

- [x] Emulador

**Comment by sanro14** [comment]
@nelsonalfo esto sucedió en la versión 20.4

**Comment by maydiamc** [comment]
en la version 20.7 de cbp no ocurre este error en mi emulador @sanro14 

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16920029/03fb4ef8-4cda-11e6-8a21-c3ce79c33f12.png)

**Comment by nelsondb** [comment]
****Solucionado en la 20.7** 

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/20217119/16920088/492d690c-4cda-11e6-8f2f-336afb77ecdd.jpg)
