### ISSUE TITLE
Community - Bitcoin Wallet_ Las Conexiones Desaparecen

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#682]
#### Nombre pantalla
# Crypto Wallet User

### Nombre de la Aplicación 
Bitcoin Wallet

-----
##### Reporte de error: 

   *Al entrar a la Crypto Wallet User  todo desapareció, hasta los **contactos*

##### Screenshot o Capture de pantalla:

![nue1](https://cloud.githubusercontent.com/assets/19353722/16770931/ba822be6-481c-11e6-9a3b-1d1d94f9186f.png)

![nuevo](https://cloud.githubusercontent.com/assets/19353722/16770939/bf1151dc-481c-11e6-857d-f75e397bf790.png)

##### Pasos exactos para reproducir el error:

 *Después de haber establecido conexiones, con algunos contactos y realizado envíos de Send y recibido Received, me fui a la Cripto Wallet User para verificar que nuevos contactos veía y me di cuenta que todo había desaparecido, igual que los contactos ya establecidos. 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/359585/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/16771166/81bf2b78-481d-11e6-9df0-b703be0f9d7a.png)

**Comment by marielis-urbina** [comment]
@MaviDavsa

**Comment by camilavaleria** [comment]
Al probar la version 20.4 en mi emulador sucede lo mismo; a pesar de que tengo contactos en mi bitcoin wallet, dentro de las communities, la pantalla de connections se guinda y no aparece nada;

![image](https://cloud.githubusercontent.com/assets/18740418/16771420/707ca56a-481e-11e6-8b93-0fcb5a690f2c.png)

luego aparece el siguiente mensaje:

![image](https://cloud.githubusercontent.com/assets/18740418/16771456/924123ec-481e-11e6-85b5-2d143f92c6d6.png)

Y en la cripto wallet no aparece ningun contacto:

![image](https://cloud.githubusercontent.com/assets/18740418/16771642/3dd49d2e-481f-11e6-94f2-26ae8c32dbb1.png)

EMULADOR DE PRUEBA:

![image](https://cloud.githubusercontent.com/assets/18740418/16771659/4cd4c218-481f-11e6-9ef5-1d780f18b979.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by marielis-urbina** [comment]
En la versión 20.5 de Bitcoin Wallet - Community, este error sigue sucediendo 

EMULADOR DE PRUEBA:

![samsung](https://cloud.githubusercontent.com/assets/19353722/16818702/20d28ff8-4917-11e6-9c38-3e1b59157435.png)

**Comment by camilavaleria** [comment]
En la version 20.7 persiste este error, tal y como se indica a continuacion;

![image](https://cloud.githubusercontent.com/assets/18740418/16876418/d03d57ec-4a71-11e6-9499-f3fe98fcd1b6.png)


![image](https://cloud.githubusercontent.com/assets/18740418/16876431/ddd8951a-4a71-11e6-904a-3fb0bd7f7139.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16876445/e9339a68-4a71-11e6-9bb8-7218aa082017.png)


Emulador de prueba;

![image](https://cloud.githubusercontent.com/assets/18740418/16876478/fc0c2f60-4a71-11e6-9185-740f44f68f7b.png)

**Comment by yolandayancel** [comment]
Prueba 15-07-16
Caso 682 CBP 20.7 BITCOIN WALLET
Nexus 5 5.0.0 api 21 480 dpi
Ocuurio lo mismo reportado:
1 Ingreso a las community, se queda cargando
2 Aparece recuadro con:Method tooks....
3 En la CCP comunity no hay user.
4 Ingreso a connections: se queda cargando un buen rato, aparece recuadro Request user.....
5 No aparecen las conecction que tenia..Las borro todas.
![borra los user](https://cloud.githubusercontent.com/assets/17283358/16876862/b23634d8-4a73-11e6-9124-aa7336209072.png)

**Comment by IsbetVR** [comment]
@nattyco En la versión 20.7 de CBP, persiste este error, las conexiones se desaparecen en las communities (Pantalla1) y como se muestra en la pantalla 2, en la bitcoin wallet en contacts, si tengo conexiones, y ya habia reallizado negocaciones

#### Pantalla 1

![screenshot_61](https://cloud.githubusercontent.com/assets/19142276/16876880/c16d35dc-4a73-11e6-87ff-7dbc904a6583.jpg)

#### Pantalla 2

![screenshot_62](https://cloud.githubusercontent.com/assets/19142276/16876893/cab61654-4a73-11e6-9be0-0b88d29bc975.jpg)

#### Dispositivo de prueba

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16876924/ee79ad62-4a73-11e6-8501-6c38997cf9db.jpg)

**Comment by nattyco** [comment]
@IsbetVR  estoy viendo este problema. Los datos estan pero no se listan.

**Comment by IsbetVR** [comment]
@nattyco Si, eso nos dimos cuenta Natty, estaremos pendiente. Gracias

**Comment by arosiopr** [comment]
en la versión 20.8 de CBP no ha sucedido este error en mi dispositivo nexux 4. Android 4.4.4

**Comment by marielis-urbina** [comment]
En la versión 20.9 de CBP no ha sucedido este error en mi emulador 

![samsung](https://cloud.githubusercontent.com/assets/19353722/17073811/272939f6-5042-11e6-80eb-267a020c2ce4.png)
