### ISSUE TITLE
CBP - Crypto Broker - No deja bajar con el scroll para ver el listado completo de negociaciones

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#683]
### CBP (versión 20.4)

-----

##### Reporte de error: 

   *En mi caso, cuando tengo más de 5 negociaciones en la lista, la número 6 no me la deja ver completa, corta la pantalla (Pantalla 1) bajando con el scroll, y si le doy directamente con el mouse para subir (Pantalla 2), igualmente la deja cortada. El layout donde dice "bitcoin 12" (Pantalla 2) está tapando la última negociación que está en la lista.

[4:37]  
lo está tapando

##### Pantalla 1

![screenshot_20](https://cloud.githubusercontent.com/assets/19142276/16782444/9dafa7ba-484d-11e6-8e0d-67f780e09ff8.jpg)

##### Pantalla 2

![screenshot_21](https://cloud.githubusercontent.com/assets/19142276/16782450/a4bc7a06-484d-11e6-9f25-533ffd5a233e.jpg)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Android 4.3
- 320 dpi

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16782484/c5d3dc34-484d-11e6-95bc-abc5cad77022.jpg)

**Comment by IsbetVR** [comment]
@yalayn

**Comment by IsbetVR** [comment]
@yalayn En la versión 20.5 de CBP persiste el error gráfico

![screenshot_30](https://cloud.githubusercontent.com/assets/19142276/16817761/53acc25e-4912-11e6-8aee-ee88aadf7bd4.jpg)

- [x] Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16817770/5f562884-4912-11e6-9130-8cdaaa1952d2.jpg)

**Comment by abicelis** [comment]
En la version 20.6 esta arreglado. @IsbetVR

**Comment by marielis-urbina** [comment]
En la versión 20.6 este error en mi emulador no sucede

![lista](https://cloud.githubusercontent.com/assets/19353722/16845564/59d503ee-49b7-11e6-9a32-85e31efcf47a.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16845565/5d75a936-49b7-11e6-9b65-49348895aa89.png)

**Comment by GeronimoVierma** [comment]
En la versión 20.6 el error no ocurre (Broker):

![tataa](https://cloud.githubusercontent.com/assets/19883115/16845631/998e635e-49b7-11e6-9986-b52ff3e99e24.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16845652/a91b9080-49b7-11e6-89c3-05e17e293112.png)

**Comment by IsbetVR** [comment]
Closed #683
