### ISSUE TITLE
CBP - Crypto Broker - Error en el "Exchange rate reference"

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#684]
### CBP versión 20.5

-----

##### Reporte de error: 

   *Cuando me llega una negociación por parte del Customer, al abrirla y revisar la tarjeta 1 (Pantalla 1) Sale mal el "Market Exchange Rate" y "Suggested", de acuerdo a la referencia que muestra en la parte superior (al lado de la foto del customer). A pesar de eso, el "Selected rate" muestra bien el cambio.

##### Pantalla 1

![screenshot_34](https://cloud.githubusercontent.com/assets/19142276/16818250/d37ea4e6-4914-11e6-9736-94995da58766.jpg)

##### Pasos exactos para reproducir el error:

 *Teniendo perfil de broker y luego de haber aceptado la conexión a través de las communities con el customer, me llegó la negociación del customer y al abrirla en la tarjeta uno salen mal los datos del tipo de cambio entre las monedas que estoy trabajando en la negociación

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Google Nexus 4
- Android 4.3
- 320 dpi

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16818361/4bc9dce0-4915-11e6-9ceb-75d48bce9520.jpg)

**Comment by IsbetVR** [comment]
@abicelis

**Comment by IsbetVR** [comment]
@abicelis 
En la versión 20.6 de CBP, persiste este error, en este caso, teniendo el perfil del Customer, el error lo muestra en la tarjeta 1 (market exchange rate)

![screenshot_39](https://cloud.githubusercontent.com/assets/19142276/16840819/ae1d861e-49a4-11e6-9df3-ed6a0fc88cb6.jpg)

**Comment by GeronimoVierma** [comment]
En la version 20.7 de CBP me mostro bien la "Exchange Rate Reference"

![lol](https://cloud.githubusercontent.com/assets/19883115/16918518/b327fcd4-4cd3-11e6-8d42-0b8d0dc290c4.png)

**Comment by GeronimoVierma** [comment]
20-07-16

En la versión 20.8 CBP continua el error, no da la misma cifra en la barra azul del contacto que en la ficha de "Exchange Rate Reference

![mal](https://cloud.githubusercontent.com/assets/19883115/17005145/a1d683f4-4ea6-11e6-8d97-79a59f381826.png)

**Comment by nelsonalfo** [comment]
@GeronimoVierma por favor reconfirmar esto. Segun veo esta bien lo que esta mostrando la ficha, porque lo que muestra la Barra Azul es el precio de la moneda para esa negociación, en donde cualquiera de los dos lo puede modificar y que es el mismo valor que aparece en Selected Rate.

**Comment by GeronimoVierma** [comment]
Ok perfecto, aquí de todas formas tengo unas nuevas captures tomadas hoy, el error esta solucionado: 

![ll](https://cloud.githubusercontent.com/assets/19883115/17368920/1caebc46-5964-11e6-9f00-f8b47dccbb2c.png)

![l](https://cloud.githubusercontent.com/assets/19883115/17368924/23609d2a-5964-11e6-95e6-3b3039271936.png)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #684
