### ISSUE TITLE
CHAT - Mensajes llegan en diferentes chats.

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#687]
### CHAT

-----

##### Reporte de error: 

   Cuando le envie a la señora Marielys y a ruben **tuve que esperar un rato ya que la red estaba lenta**, de repente cuando comienzan a llegar todos los mensajes en la pantalla del home salen correctos pero cuando entro chat de la señora Maryelis me sale es la conversación que tuve con ruben y en otros chats paso lo mismo.

##### Screenshot o Capture de pantalla:

![screenshot_4](https://cloud.githubusercontent.com/assets/20217119/16859650/97cf432a-49fe-11e6-805e-cdc1d5c28d21.jpg)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/364936/logcat.txt)

![screenshot_5](https://cloud.githubusercontent.com/assets/20217119/16859652/9943d1da-49fe-11e6-98b6-4493fb040d65.jpg)

![screenshot_6](https://cloud.githubusercontent.com/assets/20217119/16859656/9be1a318-49fe-11e6-9207-56ed8f0fb09c.jpg)

**VIDEO REFERENCIAL**

 https://www.youtube.com/watch?v=Xd3EJIXu6Vc.

##### Pasos exactos para reproducir el error:

- Primero me cree un perfil
- Les envie request
- Cuando me aceptaron les envié
- y en este punto comenzo a ocurrir el error.
 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/364936/logcat.txt)

   
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Teléfono Físico

##### Screenshot o Capture de pantalla:

 
![nexus 4 5 0](https://cloud.githubusercontent.com/assets/20217119/16859672/c383349a-49fe-11e6-8a2a-b299ab1ab0ef.jpg)

**CBP 20.6**

**Comment by nelsondb** [comment]
@MaviDavsa  @franklinmarcano1970 @RoyGF

**Comment by GeronimoVierma** [comment]
En mi caso recibí 3 mensajes de Dianey y le envié 1 mensaje de respuesta, luego pasaron aproximadamente 10 minutos sin contestarme y cuando me contesta ese mensaje que envió (Dianey) iba dirigido a la sra Marielis (Imagen 1):


![mariii](https://cloud.githubusercontent.com/assets/19883115/16860154/5567ce3a-4a03-11e6-8e97-180439ef0562.png)

![chatiii](https://cloud.githubusercontent.com/assets/19883115/16860147/4ba9a8b4-4a03-11e6-8712-810061c68039.png)

**Comment by marielis-urbina** [comment]
En la versión 20.7 de Chat persiste el error

![chat1](https://cloud.githubusercontent.com/assets/19353722/16916106/2a4c776e-4cc9-11e6-90fb-0a272782e59f.png)

![bue](https://cloud.githubusercontent.com/assets/19353722/16916116/33e4c718-4cc9-11e6-98e6-5ed86925cf7a.png)

![chat2](https://cloud.githubusercontent.com/assets/19353722/16916121/3821eb58-4cc9-11e6-9c7e-e90e85383c98.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16916159/722f44e4-4cc9-11e6-8f99-c62a35d873a4.png)

**Comment by yolandayancel** [comment]
Prueba 22-07-16
Caso 687 CBP 20.9 (CHAT)
Nexus 5 5.0.0  api 21 480 dpi
No ocurre este error.

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #687

**Comment by Gabymorillo** [comment]
En la versión 21.0 del Chat sucede de nuevo este error.

Hice conexión con @andreagmarcano, le envié "hola"  al chat y me llego la siguiente respuesta  "pantalla 1" a lo que @andreagmarcano me comentó que nunca le llego mi mensaje y que esa respuesta era para @marielis-urbina 

Emulador:
![capture-20160728-105652](https://cloud.githubusercontent.com/assets/17262077/17218598/5328e16e-54b6-11e6-9a65-4431f6b4eba8.png)

![capture-20160728-111225](https://cloud.githubusercontent.com/assets/17262077/17218612/6263bbd6-54b6-11e6-9de0-3089f6752978.png)

![capture-20160721-175754](https://cloud.githubusercontent.com/assets/17262077/17218620/6aa41048-54b6-11e6-97f6-96938e622297.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/388735/logcat.txt)

**Comment by josejcb** [comment]
Creemos que esto ya se soluciono, en el prox apk lo tendran

**Comment by sanro14** [comment]
Solucionado en la Versión 21.2 de CBP

**Comment by JeanFranco498** [comment]
CHAT de CBP 21.3 esta pasando nuevamente 


![chatttt](https://cloud.githubusercontent.com/assets/19807906/17369183/4ad71446-5965-11e6-8fa4-7a7ad0a6c896.png)


![chattttt](https://cloud.githubusercontent.com/assets/19807906/17369198/5335c614-5965-11e6-9d87-be65e15840bf.png)


![chaaattt](https://cloud.githubusercontent.com/assets/19807906/17369206/602d3974-5965-11e6-86c1-2115db8fdbd6.png)

![datos](https://cloud.githubusercontent.com/assets/19807906/17369219/70936414-5965-11e6-93d2-33df723c846d.jpg)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by Gabymorillo** [comment]
En la versión 21.7 del Chat no sucede lo reportado.

![capture-20160808-161022](https://cloud.githubusercontent.com/assets/17262077/17496247/64d173a4-5d8a-11e6-9317-7a048a38ab40.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17496250/667a9096-5d8a-11e6-9e55-7133a4af146a.png)

**Comment by danielaporras** [comment]
En la version 21.7, ya no se repite este error en mi dispositivo.

**Comment by IsbetVR** [comment]
Closed #687
