### ISSUE TITLE
Communities - Bitcoin Wallet - Aparecen connetions no enviadas

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#688]
#### Nombre pantalla

CCP COMMUNITY

### Nombre de la Aplicación 

CBP 20.7 (BITCOIN WALLET)

-----

##### Reporte de error: 
Despues de creado el perfil, solicitado los BTc, ingrese a la CCP Community a realizar las solicitudes de connecions. Primero envie solicitud de connection a Isbet y al salir del perfil de Isbet tenia varios user como si les habia enviado solicitud de connections. Envie una connetions a Dianey y al salir de alli,  se agregaron  mas user no realizados por mi. Refreco la pantalla y aparecen nuevos user como si los selecconara y otros que aparecian seleccionados ya no estan seleccionados. Esto ocurre cada vez que refresco la pantalla.

##### Screenshot o Capture de pantalla:
1
![user no seleccionados 1](https://cloud.githubusercontent.com/assets/17283358/16874742/1177bcd8-4a69-11e6-9d33-a345566e4a4d.png)

2 Uno de los User no agregado..
![user no seleccionados 2](https://cloud.githubusercontent.com/assets/17283358/16874773/46a4f2e0-4a69-11e6-9f38-3214417680cd.png)

3Luego aparecio un nuevo usuario RJGM dirente a los demás (no agregado).
![user no seleccionados 4](https://cloud.githubusercontent.com/assets/17283358/16875068/4d25c5d4-4a6b-11e6-8867-9e0d1ce541b6.png)

##### Pasos exactos para reproducir el error:
1 Creado perfil
2 Solicitud de BTC
3 Ingreso CCP Community
4 Buscar User codigo 15-07-16 M1
5 Encontre A Isbet y le envie connections
6 Sali de su perfil, encontre varios user que no habia enviado connetions
7 Encontre a Dianey  y le envie connections
8 Sali de su perfil, encontre varios user que no habia enviado connetions
9 Refresco pantalla los que vi como que se habian enviado connections ya no estan seleccionados aparecen otros nuevos.

##### Inserta Archivo aLogcat: 
Hora aproximada:09:06am

[logcat user.txt](https://github.com/Fermat-ORG/beta-testing-program/files/365989/logcat.user.txt)

#### Dispositivo desde donde se realizo la prueba
- [x] Emulador
![nexus 5 5 0 0](https://cloud.githubusercontent.com/assets/17283358/16874538/c89acfa6-4a67-11e6-8608-d7308cc2fb55.png)

**Comment by maydiamc** [comment]
En mi emulador sucede lo mismo con la version 20.7

![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/16876606/816a9318-4a72-11e6-9bea-6210f9926c08.png)

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16876618/8bb609c4-4a72-11e6-854f-9afba4d7f3f7.png)

**Comment by nattyco** [comment]
@yolandayancel  verificar este caso nuevamente

**Comment by yolandayancel** [comment]
![Uploading error 1.png…]()
