### ISSUE TITLE
COMMUNITY_BITCOIN WALLET_POP UP DE WELCOME

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#689]
#### Nombre pantalla
Pantalla de inicio

### Nombre de la Aplicación 
Community Bitcoin Wallet

-----

##### Reporte de error: 

   *El pop up de bienvenidad en la community de la bitcoin wallet, en la version 20.7 de cbp, sigue saliendo

##### Screenshot o Capture de pantalla:

![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/16876363/95843eb8-4a71-11e6-9fbc-9f804f722721.png)

##### Pasos exactos para reproducir el error:

- Ingresar a la community de la wallet por primera vez
- Marcar la opcion de no mostrar de nuevo el aviso y darle siguiente
- Entrar a enviarle solicitud a un contacto
- Salir ala pantalla principal de nuevo
- Se le mostrara de nuevo el pop up de welcome

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16876517/200292ec-4a72-11e6-807c-a8919588d8af.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP sucede este error en mi emulador 

![s](https://cloud.githubusercontent.com/assets/19353722/16876624/92da7d8e-4a72-11e6-91da-2377da05e49c.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16876627/985e9aa6-4a72-11e6-9393-853afddfd235.png)

**Comment by arosiopr** [comment]
En mi emulador sucede lo mismo

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16876727/068650be-4a73-11e6-9914-4d8cc5f9ac4a.png)

**Comment by nattyco** [comment]
@maydiamc  verificar nuevamente en la prox version de la apk

**Comment by Gabymorillo** [comment]
En la versión 20.7 en el teléfono físico persiste el error. 

![screenshot_2016-07-15-17-52-46](https://cloud.githubusercontent.com/assets/17262077/16889628/de2cb5e8-4ab5-11e6-9b28-e935c343f729.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16889641/f00694aa-4ab5-11e6-9781-f0c7c25c75b7.png)

**Comment by arosiopr** [comment]
En la versión 20.7 en el emulador persiste el error. 
Fecha 18-07-2016 Hora de Prueba 10:15 am
Emulador

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16917593/3beefb70-4cd0-11e6-8744-cc62514f5d57.png)

**Comment by marielis-urbina** [comment]
En la versión 20.8 de la BITCOIN WALLET

**Comment by arosiopr** [comment]
este error se soluciono en mi dispositivo: nexus 4 version 4.4.4.
en la versión 20.8 de CBP

**Comment by yolandayancel** [comment]
Prueba 21-07-16
Caso 689 CBP 20.9
Nexus 5 5.0.0 api 21 480dpi
Esto no ocurre en este emulador.

**Comment by marielis-urbina** [comment]
En la versión 20.9 de la Community -Bitcoin Wallet , en mi emulador no pasa 

![samsung](https://cloud.githubusercontent.com/assets/19353722/17028945/3ccb5606-4f37-11e6-91b8-82d09d4869f0.png)

**Comment by wendyduran90** [comment]
En la versión 20.9 no ocurre el error . Esta prueba se realizo desde un móvil con versión de android 4.4.4.
