### ISSUE TITLE
Cripto wallet users-Pantalla Principal

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#69]
### Cripto wallet users

-----

##### Cripto wallet users

- [x] Pantalla Principal Cripto wallet users

##### Reporte de error: 

Al ingresar a la Cripto wallet users no me sale ningún contacto para enviar solicitud de conexión desde que actualice hoy 08-03-2016, como se puede observar en la siguiente captura
![captura de pantalla 2016-03-08 10 56 32](https://cloud.githubusercontent.com/assets/5313324/13606247/88408040-e51d-11e5-9ada-3b0ca19e9377.png)

y en mis contactos solo sale matibitcoins, no salen los que ya habia agregado anteriormente antes de la actualización de hoy.
![captura de pantalla 2016-03-08 11 05 35](https://cloud.githubusercontent.com/assets/5313324/13606359/dfb6ac00-e51d-11e5-882d-c0cf56fe0ff9.png)

Emulador Genymotion Custom Phone Android 4.4.4. API 19

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:
* Modelo:
* Version de Android:

**Comment by nattyco** [comment]
@sanro14 cuando ingresaste a la community o wallet te pidio crear la identidad de nuevo?

**Comment by sanro14** [comment]
si de nuevo @nattyco

**Comment by nattyco** [comment]
@sanro14 Cuando instalaste te elimino los datos que tenias de antes, por eso no ves los contactos ni balance anterior, puede ser un tema del emulador, instala en el genymotion otra version como un Samsung, LG o Nexus

**Comment by sanro14** [comment]
@nattyco ok instalare otra versión como me dices

**Comment by nattyco** [comment]
@sanro14 pudiste instalar otra version en el emulador? como te resultaron las pruebas?

**Comment by sanro14** [comment]
@nattyco está descargando aquí ha estado pésimo el internet

**Comment by sanro14** [comment]
@nattyco me sale un error de ip en el genymotion cuando voy a iniciar la nueva versión que descargue, estoy buscando como solucionar ese error

**Comment by nattyco** [comment]
@sanro14 Pudiste resolver los problemas que tenias? Comentame si ya te podes conectar al community.

**Comment by sanro14** [comment]
@augusto-ponce @nattyco ya salen los contactos normal ya pueden cerrar este caso

**Comment by augusto-ponce** [comment]
Listo lo cierro !
