### ISSUE TITLE
BITCOIN WALLET - PAYMENT REQUESTS- LOS RECEIVED SE DEVUELVEN

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#690]
Template issue error report 

##### PAYMENT REQUEST

Nombre pantalla

##### PAYMENT REQUEST

Nombre de la Aplicación 

##### BITCOIN WALLET

 Reporte de error: 

Luego de entrar en la pantalla del "Request Received" y aceptar un envio de otro usuario, pasado un corto tiempo,  llega una notificacion de Fermat donde dice que la recepcion de los bitcoin no fue aceptada y al entrar de nuevo en la pantalla del request received, aparece el estatus inicial, en espera de "DENY O ACCEPT", es decir que los devuelve o reintegra.

Screenshot o Capture de pantalla:

![image](https://cloud.githubusercontent.com/assets/18740418/16879543/072ebc48-4a7f-11e6-9a72-d051b9630662.png)

![image](https://cloud.githubusercontent.com/assets/18740418/16879555/15c01126-4a7f-11e6-834f-d6982ea907a9.png)

Pasos exactos para reproducir el error:

-Una vez que agrego los contactos de Fermat en mi Bitcoin Wallet, procedo a enviar, solicitar o aceptar los bitcoin de acuerdo al caso.
-En el caso de aceptar un "Request Received" presiono el boton "ACCEPT" en el usuario que me los esta enviando.
- Espero un tiempo corto y aparece en la parte superior izquierda de la pantalla; un circulo que indica notificacion de Fermat que dice que la recepcion request no fue completada (EN INGLES)
-Posteriormente me voy a la pantalla del "RECEIVED" y aparecen nuevamente los usuarios que me enviaron bitcoin en su estatus inicial, en espera de mi aceptacion "DENY O ACCEPT".

Inserta Archivo aLogcat: 

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/366364/logcat.zip)

HORA APROXIMADA DEL ERROR;

10 AM

 Dispositivo desde donde se realizo la prueba

![image](https://cloud.githubusercontent.com/assets/18740418/16880285/8cfc19b2-4a82-11e6-94d4-b8cc4fed9776.png)

**Comment by camilavaleria** [comment]
@nattyco,@adrycanonico

**Comment by IsbetVR** [comment]
En mi dispositivo sucede lo reportado

![screenshot_63](https://cloud.githubusercontent.com/assets/19142276/16880520/9ca1490e-4a83-11e6-95c6-28097e90711c.jpg)

![screenshot_66](https://cloud.githubusercontent.com/assets/19142276/16880523/9ffe2658-4a83-11e6-86fb-ed34b3ed6eb6.jpg)

#### Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16880533/afbd1414-4a83-11e6-8ffd-31ae4cc7f696.jpg)

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP en mi emulador se repite el error

![req acep](https://cloud.githubusercontent.com/assets/19353722/16880573/eaea086c-4a83-11e6-97c8-567d544ac704.png)

![acep no](https://cloud.githubusercontent.com/assets/19353722/16880559/d9d56dd2-4a83-11e6-8bcb-1728be196de9.png)

![acepta](https://cloud.githubusercontent.com/assets/19353722/16880582/efc9dc68-4a83-11e6-85a5-42b0453b012e.png)

![r3](https://cloud.githubusercontent.com/assets/19353722/16880585/f456b2f6-4a83-11e6-8b74-62300bb6742f.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16880603/07a3d30c-4a84-11e6-8785-7f0adfe1f992.png)

**Comment by marielis-urbina** [comment]
En la versión 20.7 de CBP, hoy 18/7/16, persiste este error, fue aceptado el Requests y posteriormente vuelve a pedir dicha aceptación.

![gu](https://cloud.githubusercontent.com/assets/19353722/16917480/ca2216d0-4ccf-11e6-905e-d2dbd1f93390.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/16917492/d5e40a78-4ccf-11e6-9706-cf1d91dd2e3a.png)

**Comment by marielis-urbina** [comment]
En la versión 20.8 de CBP en mi emulador no pasa este error

![listo](https://cloud.githubusercontent.com/assets/19353722/17005826/7aaabfd0-4eaa-11e6-81bc-d87707c225b1.png)

![p3](https://cloud.githubusercontent.com/assets/19353722/17005838/9a4803e8-4eaa-11e6-82d5-1061d7bf302c.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17005843/a0446430-4eaa-11e6-8aac-0a9792e98d05.png)

**Comment by marielis-urbina** [comment]
En la versión 20.9 de la Bitcoin Wallet, este error en mi emulador no pasa

![btc1](https://cloud.githubusercontent.com/assets/19353722/17029180/4014fc1c-4f38-11e6-977e-a38fe6af4297.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17029185/4471ecc0-4f38-11e6-8809-88d4c37087b4.png)

**Comment by marielis-urbina** [comment]
En la versión 21.0 de CBP, se repite este error en mi emulador

![p1](https://cloud.githubusercontent.com/assets/19353722/17177314/c30aef0a-53de-11e6-80d8-80b0ba635010.png)

![p2](https://cloud.githubusercontent.com/assets/19353722/17177324/c9beefea-53de-11e6-9e33-dddb7f88b80c.png)

![p3](https://cloud.githubusercontent.com/assets/19353722/17177326/ce3f9f56-53de-11e6-8d67-049f8bb24311.png)

![p4](https://cloud.githubusercontent.com/assets/19353722/17177328/d23052c2-53de-11e6-92fd-94369a7e9491.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17177331/d640b15e-53de-11e6-8732-6882aa5f5cb4.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/386221/logcat.txt)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by nattyco** [comment]
@IsbetVR  verificar este reporte en la nueva apk

**Comment by maydiamc** [comment]
Este error no sucede en mi emulador en la version 22.0

![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17675076/19687fb8-62f6-11e6-918d-d163ad1c601f.png)

**Comment by marielis-urbina** [comment]
En mi emulador con la versión 22 de CBP, no sucede 

![re](https://cloud.githubusercontent.com/assets/19353722/17675346/67a8d532-62f7-11e6-9aa8-41ef9ef64b5f.png)

![re2](https://cloud.githubusercontent.com/assets/19353722/17675378/9032c6b6-62f7-11e6-9044-2038184749cb.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17675388/9559098e-62f7-11e6-8047-ee4109a62bd5.png)

**Comment by camilavaleria** [comment]
En la version 22.1  de CBP este error no sucede con mi emulador;

![image](https://cloud.githubusercontent.com/assets/18740418/17710880/520b45d6-63bd-11e6-880c-2ba4bdc88bcc.png)

![image](https://cloud.githubusercontent.com/assets/18740418/17710913/77df14cc-63bd-11e6-91e0-d3371ef275a3.png)

EMULADOR DE PRUEBA:

![image](https://cloud.githubusercontent.com/assets/18740418/17710936/8929a792-63bd-11e6-8d35-0709a8459aca.png)
