### ISSUE TITLE
COMUNITY-CBP:  DESAPARECIERON LOS USER Y  LAS CONEXIONES REALIZADAS

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#692]
#### Nombre pantalla

Community

### Nombre de la Aplicación 
CBP 20.7

##### Reporte de error: 

   *Estaba realizando negociaciones con un broker y estas se quedaron enviando ( el circulito que gira cargando ). Me fuí a la Community y encontre que dice: NO USER. y en Connections: NO CONTACTS

##### Screenshot o Capture de pantalla:
![community 1](https://cloud.githubusercontent.com/assets/17283358/16886360/ca66ed8a-4aa1-11e6-8c5b-183a3c9218b8.png)
![community 2](https://cloud.githubusercontent.com/assets/17283358/16886367/d1425644-4aa1-11e6-867e-9d42e5b28b8d.png)

##### Pasos exactos para reproducir el error:
1 Envie 3 negociaciones al Broker
2 Estas quedaron cargando (Circulo que gira al lado de la negociacion: dice sending
3 Broker confirma que le llegó una y la reenvio.
4 Espere mucho rato y nunca llegó
5 Fuí a la Community a verificar la conexión
6 Los User no aparecen, las conexiones no aparecen , desaparecieron
7 Cerre la apk, el Genimotion
8 Abri Genymotion y la apk, pero no aparecen los user, ni las conexiones.

##### Inserta Archivo aLogcat: 
Hora logcat.03:21

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/366721/logcat.zip)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![nexus 5 5 0 0](https://cloud.githubusercontent.com/assets/17283358/16886525/e470e73e-4aa2-11e6-88e4-7ce252ad8be1.png)

**Comment by yolandayancel** [comment]
@nelsonalfo

**Comment by yolandayancel** [comment]
@IsbetVR

**Comment by yolandayancel** [comment]
@sanro14

**Comment by nelsondb** [comment]
**Pasa lo mismo en la customer community**

![screenshot_6](https://cloud.githubusercontent.com/assets/20217119/16886692/c3fe0738-4aa3-11e6-8ac2-588650fd3202.jpg)

![screenshot_7](https://cloud.githubusercontent.com/assets/20217119/16886694/c707656e-4aa3-11e6-9386-9ee970ee0fa1.jpg)

**Comment by yolandayancel** [comment]
18-07-2016
Caso 692 CBP-20.7
Nexus 5 5.0.0 api 21 480dp1
El error persiste:
![692](https://cloud.githubusercontent.com/assets/17283358/16920323/3a0f09de-4cdb-11e6-8944-928a2dcba6d4.png)
