### ISSUE TITLE
COMMUNITY - BITCOIN WALLET - RECTÁNGULO GRIS APARECE JUNTO A FOTOS DE PERFIL

### ISSUE THREAD

**Issue by LilianFlores** [Fermat-ORG/beta-testing-program#693]
#### Nombre pantalla

CCP Community

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   *Al entrar en la CCP Community, se puede notar que las fotografías de perfil de los usuarios aparece junto a un rectángulo gris que extiende los cuadros y da una mala presentación al usuario. 

##### Screenshot o Capture de pantalla:

![userexperience](https://cloud.githubusercontent.com/assets/19652611/16890430/8ebf62ec-4abc-11e6-8694-c16db9c57762.png)

##### Pasos exactos para reproducir el error:

 1. Ingresé a la Bitcoin wallet.
 2. Ingresé a contacts
 3. Presioné el botón de "+" para agregar contactos.
 4. Presioné la opción "Fermat Users" y luego fui a la CCP Community desde ahí.

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/366968/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![celular](https://cloud.githubusercontent.com/assets/19652611/16890440/b1292e4e-4abc-11e6-8e5e-127705d40bce.png)

**Comment by LilianFlores** [comment]
@nattyco

**Comment by nattyco** [comment]
@AdryCanonico  este no es el disrño final de la community estamos en prceso de cambio

**Comment by AdryCanonico** [comment]
@nattyco  ok Natty, apenas estén los cambios listos te aviso y cerramos esto.

**Comment by GeronimoVierma** [comment]
18-07-2016
CBP-20.7

El error persiste:

![1807](https://cloud.githubusercontent.com/assets/19883115/16918230/bca27434-4cd2-11e6-9e9e-ba53ebc77c0b.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/16918255/d1a208cc-4cd2-11e6-8b49-fba5162d8e14.png)

**Comment by yolandayancel** [comment]
18-07-2016
Caso 693 CBP-20.7
Nexus 5 5.0.0
Error persiste.
![error 1](https://cloud.githubusercontent.com/assets/17283358/16920051/19e9e026-4cda-11e6-97e8-eccc288a3b4b.png)[error 2.zip](https://github.com/Fermat-ORG/beta-testing-program/files/369416/error.2.zip)



El error persiste:

**Comment by nattyco** [comment]
@AdryCanonico no es necesario que reporten este caso porque el diseño nuevo no se ha terminado aun.

**Comment by GeronimoVierma** [comment]
La versión 20.8 tiene nuevo diseño y los rectángulos grises ya no están:

![tell](https://cloud.githubusercontent.com/assets/19883115/16966973/ff655c70-4dd4-11e6-9a04-09a252365647.png)
