### ISSUE TITLE
CHAT - BOTON "Add Contac" PIERDE SU FUNCIÓN AL SUBIR Y BAJAR EN LA COMUNITY

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#694]
#### Nombre pantalla

Comunity Chat

### Nombre de la Aplicación 

CHAT

-----

##### Reporte de error: 

   *Al añadir un contacto en la comunidad de chat con el botón "add contac" aparece el check en naranja pero al subir o bajar dentro de la misma comunidad y pasar nuevamente por el sitio donde estaba el contacto que agregue, no sale el check sino nuevamente el botón "add contac". 
Ademas de que al contacto no le llega ninguna notificación de conexión 

##### Screenshot o Capture de pantalla:

![p2p2222](https://cloud.githubusercontent.com/assets/19807906/16890891/fec16b36-4ac0-11e6-823d-9ac5a8b643f7.jpg)

![p2p222222](https://cloud.githubusercontent.com/assets/19807906/16890935/56c1f1f2-4ac1-11e6-8fbb-76d7e91b05a9.jpg)

![p222p2p2](https://cloud.githubusercontent.com/assets/19807906/16890938/5cd724fe-4ac1-11e6-9d97-0070fb0eec5d.jpg)

##### Pasos exactos para reproducir el error:

1. Abrir Chat Comunity
2. Buscar el contacto
3. Presionar "add contac"
4. Subir o bajar en la comunity dejando al contacto fuera de la vista
5. Volver a buscar el contacto 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/366980/logcat.txt)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![captura del telf](https://cloud.githubusercontent.com/assets/19807906/16890971/c6ecf9f4-4ac1-11e6-9c1b-5c48bce42e91.jpg)

**Comment by JeanFranco498** [comment]
@AdryCanonico @RoyGF

**Comment by Gabymorillo** [comment]
En el telefono fisico tambien ocurre el error.

![screenshot_2016-07-15-19-29-44](https://cloud.githubusercontent.com/assets/17262077/16891119/60ae32f0-4ac3-11e6-9180-b426b9b90a47.png)

![screenshot_2016-07-15-19-30-00](https://cloud.githubusercontent.com/assets/17262077/16891111/4e60bb40-4ac3-11e6-9f08-b9a634f3076b.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16891122/67063a8a-4ac3-11e6-89a6-a1b59ebcf0a3.png)

**Comment by RoyGF** [comment]
OK, yo reviso eso, cuando esté resuelto les aviso. ;)

**Comment by wendyduran90** [comment]
En la versión 20.7 perdiste el error , esta prueba se realizo desde un móvil con versión de android 4.4.4
![screenshot_2016-07-18-11-15-27](https://cloud.githubusercontent.com/assets/20212920/16919964/b6f937dc-4cd9-11e6-97f5-d97c8761a293.png)
![screenshot_2016-07-18-11-15-19](https://cloud.githubusercontent.com/assets/20212920/16919984/cdcb1584-4cd9-11e6-8e9f-259e1561f8e6.png)

**Comment by arosiopr** [comment]
en la versión 20.8 de CBP persiste el error en Emulador

![screenshot_20](https://cloud.githubusercontent.com/assets/5313326/17002646/499a89f8-4e9a-11e6-9b4e-eec467a1f113.png)

![screenshot_21](https://cloud.githubusercontent.com/assets/5313326/17002650/4db013aa-4e9a-11e6-8c26-9f3cfa343d0b.png)

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/17002656/521ddf76-4e9a-11e6-9987-b86f5d0b3c27.png)

**Comment by yolandayancel** [comment]
Prueba 21-07-16
Caso 694 CBP 20.8
Nexus 5 5.0.0 Api21 480dpi

Ocurre parecido a lo reportado,al añadir un contacto en la comunidad de chat con el botón "add contac" aparece el check en azul cuando se hace conexión,  pero al subir o bajar dentro de la misma comunidad y pasar nuevamente por el sitio donde estaba el contacto que agregue, no sale el check sino nuevamente el botón "add contac". Pero la conexión queda realizada porque la tengo en contactos agregado.
![caso 1](https://cloud.githubusercontent.com/assets/17283358/17022789/072ca496-4f1e-11e6-95d3-7d83e5da5b89.png)
![caso 1 1](https://cloud.githubusercontent.com/assets/17283358/17022794/0f669ff4-4f1e-11e6-972a-0c5dc62cde13.png)

**Comment by yolandayancel** [comment]
Prueba 22-07-16
Caso 694 CBP 20.9
Nexus 5 5.0.0 api 21 480dpi
ya no ocurre este error.
![694](https://cloud.githubusercontent.com/assets/17283358/17069109/d4e32946-5022-11e6-9cad-b55b5f08c30c.png)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #694

**Comment by maydiamc** [comment]
reabrir este caso, en la version 21.0 de CBP esta sucediendo este erro nuevamente 

![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/17215419/c7149c64-54aa-11e6-8c89-c33554d37c94.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/17215423/ca079c00-54aa-11e6-867a-42525fe086f2.png)

Archivo logcat
9:39am
[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/388516/logcat.zip)

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/17215493/065d9bd2-54ab-11e6-8daa-f991f1583336.png)

**Comment by josejcb** [comment]
Creemos que este fue ya solucionado, en el proximo apk lo tendran

**Comment by wendyduran90** [comment]
En la versión 21.1 persiste el error . Las pruebas se realizaron desde un móvil con versión android 4.4.4
@RoyGF 

![screenshot_2016-08-01-08-30-49](https://cloud.githubusercontent.com/assets/20212920/17294296/e95210c4-57c3-11e6-815f-74066d9034d8.png)

![screenshot_2016-08-01-08-30-56](https://cloud.githubusercontent.com/assets/20212920/17294315/02e6dc22-57c4-11e6-8253-df083323b5db.png)

**Comment by gablup** [comment]
En la versión 21.1 de CBP al chequear desde un teléfono físico persiste el error.

![screenshot_2016-08-01-10-32-02](https://cloud.githubusercontent.com/assets/17261437/17299867/fdb8faa4-57dd-11e6-8c1a-5c5bacd4f1b2.png)

![screenshot_2016-08-01-10-32-28](https://cloud.githubusercontent.com/assets/17261437/17299993/7cab4542-57de-11e6-89f8-605366011447.png)

Fecha: 01-08-16
Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB.

Nota: No se adjuntó el archivo LogCat porque desde el celular no pude hallarlo.

**Comment by yolandayancel** [comment]
Prueba 01-08-2016
Caso      CBP V 21.2
Nexus 5 5.0.0 api 21 480dpi
En este emulador, no ocurre lo reportado
![screenshot_14](https://cloud.githubusercontent.com/assets/17283358/17304534/1389a00c-57f4-11e6-810d-be95c11a6308.png)

**Comment by arosiopr** [comment]
@IsbetVR  se puede cerrar solucionado en la versión 21.2 de CBP en mi teléfono físico

**Comment by IsbetVR** [comment]
Solucionado en la versión 21.2 CBP
