### ISSUE TITLE
COMMUNITY - BITCOIN WALLET - USUARIOS EN ESPERA DE CONEXIÓN SIN SOLICITUD PREVIA

### ISSUE THREAD

**Issue by LilianFlores** [Fermat-ORG/beta-testing-program#695]
#### Nombre pantalla

CCP COMMUNITY

### Nombre de la Aplicación 

BITCOIN WALLET

-----

##### Reporte de error: 

   * En la CCP Community se muestran usuarios en espera de conexión cuando realmente no se les ha enviado solicitud. Al refrescar, estos usuarios pueden ya no presentar el icono de espera, pero el patrón se repite en otros usuarios. Cabe aclarar que a ninguno de estos usuarios (pantalla 1, 2, 3) les envié solicitud.

##### Screenshot o Capture de pantalla:

![solicitudes](https://cloud.githubusercontent.com/assets/19652611/16891927/e840d24c-4ad0-11e6-9d23-f9bf28b4720b.png)

![solicitudes2](https://cloud.githubusercontent.com/assets/19652611/16892042/286096b6-4ad4-11e6-96ae-41d178f4a804.png)

![solicitudes3](https://cloud.githubusercontent.com/assets/19652611/16892043/39496f70-4ad4-11e6-9b41-74138897ccc3.png)

##### Pasos exactos para reproducir el error:

 1. Entrar a la community desde la Bitcoin Wallet 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/367064/logcat.txt)
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:
 
![celular](https://cloud.githubusercontent.com/assets/19652611/16891941/2c16e24a-4ad1-11e6-9233-f77ba7eb6c19.png)

**Comment by LilianFlores** [comment]
@nattyco @AdryCanonico

**Comment by Gabymorillo** [comment]
En el teléfono físico de la versión 20.7 sucede este error, donde sale que envié solicitud a mi misma. 

![screenshot_2016-07-18-08-22-12](https://cloud.githubusercontent.com/assets/17262077/16915286/c4e3c4f8-4cc4-11e6-812d-25501aa6b9cd.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16915293/cdeda654-4cc4-11e6-86e1-f069fabbf4cb.png)

**Comment by AdryCanonico** [comment]
@nattyco @adrycanonico

**Comment by nattyco** [comment]
@AdryCanonico  esto esta solucionado en la proxima version que tiene que enviarles Nelson, hay varias correcciones esperando desde el jueves pasado.

**Comment by AdryCanonico** [comment]
@nattyco ok! Estaremos al pendiente

**Comment by LilianFlores** [comment]
Solucionado este error. Cerrar caso. @AdryCanonico

**Comment by LilianFlores** [comment]
Solucionado este error en la versión 20.9 de la Bitcoin Wallet. Cerrar caso. @AdryCanonico

**Comment by IsbetVR** [comment]
En la versión 20.9 de Bitcoin Wallet el diseño de las communities cambió. Y el error ya no sucede

**Comment by IsbetVR** [comment]
Closed #695
