### ISSUE TITLE
Community-Chat-Error en checkbox

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#696]
#### Nombre pantalla
Community-Browser

### Nombre de la Aplicación 
Chat

-----

##### Reporte de error: 

   *Al darle en el boton de Add Contact aparece el checkbox naranja comprimido.

##### Screenshot o Capture de pantalla:

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/16925301/91c3016a-4cf1-11e6-8c27-2ccc8c273c98.png)

 *Agregar las capture del error en el emulador o teléfono donde se produjo. 
![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/16925396/ff1f9016-4cf1-11e6-90a8-38f205fec9df.png)

##### Pasos exactos para reproducir el error:
1.Entre a la community
2.Entre a la pantalla de Browser
3.Precione sobre el boton de Add Contact
4.El checkbox naranja se ve comprimido

##### Inserta Archivo aLogcat: 
[Google Nexus 4 - 4.2.2 - API 17 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/369814/Google.Nexus.4.-.4.2.2.-.API.17.-.768x1280-logcat.txt)

Hora aproximada: 2:00pm
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

**Comment by Gabymorillo** [comment]
Prueba: 18/07/16

En el telefono fisico, en la version 20.7 pasa este error.

![screenshot_2016-07-18-13-58-44](https://cloud.githubusercontent.com/assets/17262077/16925753/af416360-4cf3-11e6-9c47-50436a54c201.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/16925770/c43d73f8-4cf3-11e6-843c-6b0dac98a5e7.png)

**Comment by AdryCanonico** [comment]
@RoyGF @MaviDavsa

**Comment by RoyGF** [comment]
Uhmmmm, a todas les pasa? Pq tal vez es un error de los gráficos del emulador. :/ voy a echarle un ojo a eso.

**Comment by dorzar1989** [comment]
En la version 20.7 de la CBP sigue, pero ya entendi de que se trata. A mi parecer este Check Naranja aparece es cuando envias una solicitud y aun la otra persona no ha aceptado. Luego de que acepta cambia de color, ya que se realiza la conexion entre usuarios. No me parece un error.

- Fecha: 18/07/2016

- Hora: 6:18 pm

- Screenshots: 

![screenshot_104](https://cloud.githubusercontent.com/assets/19670319/16932489/977b1354-4d14-11e6-8e5b-b9dfbbd2aae5.png)

![screenshot_105](https://cloud.githubusercontent.com/assets/19670319/16932493/9a1b1cee-4d14-11e6-889f-98baff7cf6d1.png)

![screenshot_106](https://cloud.githubusercontent.com/assets/19670319/16932496/9c0eabec-4d14-11e6-93f5-5fb933e1bddf.png)

---- En Azul me aparecen solo 6 personas, y en conexiones También. Mientras que en Naranja me aparecen solo las personas a las que yo les envié Conexión y aun no me han Aceptado

![screenshot_107](https://cloud.githubusercontent.com/assets/19670319/16932536/dce4e88e-4d14-11e6-849f-ba55545c39aa.png)


- Movil: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16932548/eba2161c-4d14-11e6-8240-3940ad460220.png)

@RoyGF @MaviDavsa

**Comment by danielaporras** [comment]
En la version 20.8 continua el error.
![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17003458/0e1f4f2c-4e9e-11e6-8c7b-56fcd849576d.png)


![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/17003465/1840e33a-4e9e-11e6-988b-21c77ed1b1de.png)


[Uploading Google Nexus 4 - 4.2.2 - API 17 - 768x1280-logcat.txt…]()

Hora aproximada: 5:14

**Comment by RoyGF** [comment]
Ando arreglando eso, cuando lo termine te aviso. ;)

**Comment by RoyGF** [comment]
Listo, en el sig. APK debería estar solucionado el error.

**Comment by dorzar1989** [comment]
En la version 20.9 de la CBP No sucede este error

- Screenshot:

![screenshot_62](https://cloud.githubusercontent.com/assets/19670319/17066454/1f3da6e6-5015-11e6-920c-60f599ec13b4.png)

![screenshot_63](https://cloud.githubusercontent.com/assets/19670319/17066457/22c86274-5015-11e6-81de-67497ddca161.png)

![screenshot_64](https://cloud.githubusercontent.com/assets/19670319/17066458/22fc906c-5015-11e6-9dae-f82405bb5604.png)

- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17066472/32d2c3c6-5015-11e6-840a-e3ec1110d6b6.png)

**Comment by IsbetVR** [comment]
Closed #696
