### ISSUE TITLE
CHAT_PROFILE_NO PERMITE COLOCAR IMAGEN DE GALERIA

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#697]
### Nombre de la Aplicación 
Chat Profile

-----

##### Reporte de error: 

   *Me coloca las fotos que tengo en la galeria de color claro y no me permite seleccionarlas para colocar alguna como imagen de perfil.

##### Screenshot o Capture de pantalla:

![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/16925023/3011457c-4cf0-11e6-861d-98b6dd39f829.png)

##### Pasos exactos para reproducir el error:

- Ingresar a perfil de chat por primera vez
- Seleccionar para colocar imagen de la galeria
- entrar a la carpeta pictures o download
- Seleccionar una imagen, que se ven en color claro
- No se podra colocar ninguna de las imagenes

##### Inserta Archivo aLogcat: 

Hora 2:21pm aprox
 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/16925233/3631631e-4cf1-11e6-813c-7cf4511cb868.png)

**Comment by maydiamc** [comment]
@RoyGF

**Comment by RubenSem** [comment]
Me pasa igual en diferente versión de android y api.

![screenshot_6](https://cloud.githubusercontent.com/assets/19676223/16926226/cd6c29d6-4cf5-11e6-86c3-c00d07e703ea.jpg)

Emulador:

![screenshot_1](https://cloud.githubusercontent.com/assets/19676223/16926211/bbad6d22-4cf5-11e6-96a4-d8ce36b54d5c.jpg)

**Comment by dorzar1989** [comment]
En la Version 20.7 de CBP no me aparece este error, puedo pensar que fue por RedP2P o por Internet.

- Hora: 6:10 Pm

- Fecha: 18/07/2016

- Screenshot:

![screenshot_103](https://cloud.githubusercontent.com/assets/19670319/16932245/46698974-4d13-11e6-8f90-bd24b6068c82.png)

![screenshot_102](https://cloud.githubusercontent.com/assets/19670319/16932241/437aba8a-4d13-11e6-9934-5c5a7596757d.png)


- Movil:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/16932255/4c1e65ec-4d13-11e6-9899-d1e44f12ea70.png)

**Comment by maydiamc** [comment]
en la version 20.9 de cbp sigue el error @IsbetVR 

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/17062653/ddd40460-5001-11e6-9c02-344deaec6192.png)

**Comment by sanro14** [comment]
@maydiamc es tu emulador, si quieres prueba en otro..

**Comment by maydiamc** [comment]
@sanro14 probé en el mismo emulador y con otro en la version 21.0 de CBP y sigue el error

Capture de emulador S5 4.4

![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/17216076/24fcb256-54ad-11e6-99e9-9099d123c90e.png)
![especificaciones](https://cloud.githubusercontent.com/assets/17274154/17216079/281e8824-54ad-11e6-8270-2f84be470428.png)
 
Archivo Logcat
Hora: 10:15

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/388544/logcat.zip)
