### ISSUE TITLE
BITCOIN WALLET - CONTACTS - ERROR AL CARGAR IMAGEN

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#698]
### Nombre de la Aplicación BITCOIN WALLET

-----

##### Reporte de error: 

   *Al ingresar a la sección de contactos se presento el siguiente mensaje "Image Database Problem"

##### Screenshot o Capture de pantalla:

![screenshot_15](https://cloud.githubusercontent.com/assets/5313326/16997641/4c1f1bb4-4e84-11e6-8ca4-366ff2545b4a.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a Bitcoin Wallet
2. Dar clic en la opción del menú "Contacts"

##### Inserta Archivo aLogcat: 
1:50 pm
 [Google Nexus 4 - 4.4.4 - API 19 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/374393/Google.Nexus.4.-.4.4.4.-.API.19.-.768x1280-logcat.txt)
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![nexus 4 4 4 4](https://cloud.githubusercontent.com/assets/5313326/16997695/8bdcc6c0-4e84-11e6-891e-11fd12c555b9.png)

**Comment by arosiopr** [comment]
@AdryCanonico @nattyco

**Comment by IsbetVR** [comment]
En mi dispositivo sucede lo mismo: (versión 20.9 Bitcoin Wallet)

![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/16998181/5430c526-4e86-11e6-92f0-ae12416efb34.jpg)


#### Archivo logcat.txt

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/374399/logcat.txt)

#### Emulador

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/16998085/087accda-4e86-11e6-9353-574b93977b72.jpg)

**Comment by nattyco** [comment]
@IsbetVR  habian agregado algun contacto en comun con @arosiopr ?

**Comment by arosiopr** [comment]
@nattyco yo tenia a lilian, francisco y andrea e @IsbetVR tenia a lilian

**Comment by IsbetVR** [comment]
@nattyco sólo a Lilian, es la común entre ambos dispositivos

**Comment by dorzar1989** [comment]
En la version 20.9.1 No me sucede.

- Screenshot:

![screenshot_36](https://cloud.githubusercontent.com/assets/19670319/17035772/363e8310-4f57-11e6-9256-7aa2e25375d9.png)


- Emulador: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17035774/39fe6e84-4f57-11e6-9fa5-f4359913f449.png)

**Comment by arosiopr** [comment]
@sanro14 por favor reabrir, sucede este error en mi telefono físico

![screenshot_2016-07-21-15-33-01](https://cloud.githubusercontent.com/assets/5313326/17036773/b30b444c-4f5b-11e6-9833-86cd16c4fbd2.png)

![screenshot_2016-07-21-13-38-46](https://cloud.githubusercontent.com/assets/5313326/17036678/5188593a-4f5b-11e6-864b-0492f1b1d5d7.png)

**Comment by Gabymorillo** [comment]
En la versión 20.9.1 presenta este error.

![capture-20160721-175648](https://cloud.githubusercontent.com/assets/17262077/17040461/ccf30cde-4f6d-11e6-8a9a-c6641a79ea46.png)

Emulador

![capture-20160721-175754](https://cloud.githubusercontent.com/assets/17262077/17040460/c8d48cfe-4f6d-11e6-95dc-78a61a9c9f85.png)

**Comment by marielis-urbina** [comment]
En la versión 21.0 de CBP, no me sucede esto en mi emulador

![conta](https://cloud.githubusercontent.com/assets/19353722/17121500/1fb2dbca-52a2-11e6-988a-6b74a8c56810.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17121501/24d78452-52a2-11e6-8b1c-33f3c6d0a774.png)

**Comment by arosiopr** [comment]
@IsbetVR @sanro14 @AdryCanonico este error no se ha vuelto a presentar, solucionado en la versión 21.0 de CBP
