### ISSUE TITLE
CBP - Error al tratar de Enviar Negociacion

### ISSUE THREAD

**Issue by hcampos1984** [Fermat-ORG/beta-testing-program#699]
### Template issue error report
CBP - Error al tratar de Enviar Negociacion
#### Nombre pantalla
Start Negotiation

### Nombre de la Aplicación 
CBP - Crypt Customer

-----

##### Reporte de error: 

al ingresar al Crypto Broker para iniciar una negociacion, me permite seleccionar cualquier usuario de la broker list que este haciendo transacciones de cualquier tipo, en este caso selecciones BTC, coloque el tipo de moneda a utilizar que era la Venezolana VEF, coloque un monto de 2000 VEF, coloque el monto a comprar 10 btc al colocar el monto a pagar de inmediato de 100 VEF de inmediato me elimino el monto del "Amount to Buy" y por lo que al pulsar SEND me mostro el error donde debo colocar un valor mayor a cero, hice el mismo procedimiento pero colocando primero el Amount to Pay y luego el Amount to Buy se desaparecio, entonces al pulsar "SEND" me arrojo el mismo mensaje de que debe ser un valor mayor a cero.

##### Screenshot o Capture de pantalla:
![image](https://cloud.githubusercontent.com/assets/20233469/17007695/c0cdd016-4eb8-11e6-81c4-5379a2d6467f.png)
![image](https://cloud.githubusercontent.com/assets/20233469/17007711/d42ffe90-4eb8-11e6-8b51-d105d0716de7.png)
![image](https://cloud.githubusercontent.com/assets/20233469/17007724/e4721234-4eb8-11e6-9b66-24943408d8cd.png)
![image](https://cloud.githubusercontent.com/assets/20233469/17007745/1827b584-4eb9-11e6-8f9d-cdaedffe0ab8.png)
![image](https://cloud.githubusercontent.com/assets/20233469/17007750/241d7d2e-4eb9-11e6-94d9-50bf8591ac98.png)

##### Pasos exactos para reproducir el error:
Ingreso a la Broker List
Selecciono Algun Broker de BTC
Se selecciona el metodo de Pago "Venezuelan Bolivar VEF
Coloco el Market Exchange Rate en 2000 VEF
Coloco el Amount to Buy en 10 BTC
Coloco el monto en 100 VEF y de Inmediato borra el numero que se coloco en "Amount to Buy"
Al Pulsar el Boton "SEND" aparece el mensaje "THe Buying Must be Greater Than Zero"
Nota: Sucede la mismo si coloco primeto el "Amount to Pay"  el "Amount to Buy"se borra

##### Inserta Archivo aLogcat: 

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/374949/logcat.txt)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:
![image](https://cloud.githubusercontent.com/assets/20233469/17007664/9cbff30c-4eb8-11e6-868a-b21a96274116.png)

@MaviDavsa

**Comment by MaviDavsa** [comment]
@nelsonalfo @sanro14 @franklinmarcano1970 @abicelis

**Comment by nelsondb** [comment]
**Solucionado en la 21.0**

![image](https://cloud.githubusercontent.com/assets/20217119/17122373/03981b92-52a9-11e6-8190-6f150bf6f694.png)
