### ISSUE TITLE
Bit Coin Wallet_Payment

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#70]
### Template issue error report

Bit Coin Wallet

#### Nombre pantalla

Payment

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *En la parte de Payment al querer realizar una transacción hice varios intentos y la aplicación me da un error y no me deja hacer la transacción. 

![screenshot_2016-03-09-11-05-25](https://cloud.githubusercontent.com/assets/17273349/13640493/1de6574a-e5e7-11e5-877a-2a68716257d0.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE 
* Modelo:Apex 2
* Version de Android: 4.4.2

**Comment by nattyco** [comment]
@adryx83  detallame mas el problema, completaste todos los datos del formulario? si podes pone una captura del formulario con los datos que estas tratando de enviar

**Comment by adryx83** [comment]
@nattyco No mira el problema es que no me sale ni formulario cuando le doy a el boton de Send Request to a contact que es como una moneda con un avión de papel, me sale de una vez el error que sale en la captura que te coloque.

**Comment by adryx83** [comment]
Este Issue ya esta resuelto, ya se puede cerrar @augusto-ponce

**Comment by augusto-ponce** [comment]
Listo @adryx83 ahora lo cierro
