### ISSUE TITLE
BITCOIN WALLET - CONTACTS - ADD FERMAT USER

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#701]
### Nombre de la Aplicación BITCOIN WALLET

-----

##### Reporte de error: 

   *Al ingresar a la sección Add Fermat User en Contacts y presionar sobre "Tap me to look contacts" sale una ventana emergente, en el cual se puede observar que las letras del botón de search no se encuentra centrado.

##### Screenshot o Capture de pantalla:

![screenshot_2016-07-21-15-32-08](https://cloud.githubusercontent.com/assets/5313326/17036067/a4dca63e-4f58-11e6-86ec-d3ec1488802c.png)

##### Pasos exactos para reproducir el error:

1. presionar la opcion del menu contacts
2. presionar el simbolo + 
3. presionar add fermat user
4. presionar Tap me to look contacts
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_2016-07-21-13-38-46](https://cloud.githubusercontent.com/assets/5313326/17036352/ee2a0628-4f59-11e6-8a35-3a4bf62670c5.png)

**Comment by arosiopr** [comment]
@AdryCanonico @nattyco

**Comment by dorzar1989** [comment]
En la version 20.9.1 me sucede algo parecido.

- Screenshots:

![screenshot_37](https://cloud.githubusercontent.com/assets/19670319/17036826/f067214e-4f5b-11e6-9c2d-19392ace5a0e.png)


- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17036828/f50f339e-4f5b-11e6-97a6-e2c1785ec663.png)

**Comment by Gabymorillo** [comment]
En la versión 20.10  de la Wallet  no presenta este error.

![capture-20160721-175754](https://cloud.githubusercontent.com/assets/17262077/17112934/357e66f8-5276-11e6-9b0d-a1a2b0f13d00.png)

**Comment by nattyco** [comment]
@IsbetVR  @arosiopr verificar este caso nuevamente

**Comment by JeanFranco498** [comment]
Ya no sucede este error en la version cbp 21.0

![image](https://cloud.githubusercontent.com/assets/19807906/17119896/db0af80a-5296-11e6-8779-3c8a3fae3de3.png)

![image](https://cloud.githubusercontent.com/assets/19807906/17119909/f5ebd3ba-5296-11e6-8bae-a8f258fe86e5.png)

**Comment by JeanFranco498** [comment]
Ya no sucede en cbp 21.0

![image](https://cloud.githubusercontent.com/assets/19807906/17120002/81397102-5297-11e6-8373-c588498732f6.png)
