### ISSUE TITLE
Bitcoin Wallet - Cuando salimos de la ventana "Send error report" te manda a la ventana de "Send to Contact"

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#702]
### Bitcoin Wallet

-----

##### Reporte de error: 

   Cuando entramos al settings y luego nos vamos a **send error report** y le damos "back" para ir de nuevo a las settings esta nos enviará a la ventana de "Send to Contact"

##### Screenshot o Capture de pantalla:

![2](https://cloud.githubusercontent.com/assets/20217119/17043126/b3a4e626-4f81-11e6-8118-cba1c5951f17.png)

![3](https://cloud.githubusercontent.com/assets/20217119/17043127/b4c40a5a-4f81-11e6-90e5-0c82caec2f73.png)

![1](https://cloud.githubusercontent.com/assets/20217119/17043128/b579f5fe-4f81-11e6-88c1-3e3ffe492cf3.png)

##### Pasos exactos para reproducir el error:

 * Ir a la settings de bitcoing wallet
 * Entrar en "Send error report"
 * Presionar al "back" para ir de nuevo a las settings
 * En este paso te mandará a la ventana de "Send to Contact"

##### Inserta Archivo aLogcat: 

[logcat1.txt](https://github.com/Fermat-ORG/beta-testing-program/files/377235/logcat1.txt)

  ------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Teléfono Físico

##### Screenshot o Capture de pantalla:

 
![nexus 4 5 0](https://cloud.githubusercontent.com/assets/20217119/17043388/2b7543f6-4f84-11e6-8b42-7d5e05b5f012.jpg)

**Bitcoin wallet 20.9.1**

**Comment by nelsondb** [comment]
@nattyco @AdryCanonico

**Comment by yolandayancel** [comment]
Prueba 22-07-16
Caso 702 CBP 20.9
Nexus 5 5.0.0 Api 21 480dpi
Ocurre lo reportado. alpisar back lo lleva a sent to contact:  
![702 1](https://cloud.githubusercontent.com/assets/17283358/17068835/3dcd2d6e-5021-11e6-82b0-7a479db0049b.png)

![702 2](https://cloud.githubusercontent.com/assets/
17283358/17068823/2f70480a-5021-11e6-9037-0993b4d324a0.png)

**Comment by nattyco** [comment]
@nelsonalfo  @AdryCanonico  verificar este caso nuevamente

**Comment by dorzar1989** [comment]
En la Version 21.0 de la CBP no me sucede este error, ni al darle "Atras" ni al darle "Cancel"

- Screenshot: 

![screenshot_70](https://cloud.githubusercontent.com/assets/19670319/17119782/fba52b72-5295-11e6-8e5c-6fbb09bc5865.png)

![screenshot_71](https://cloud.githubusercontent.com/assets/19670319/17119783/fba8890c-5295-11e6-9327-418f88ce4e95.png)

![screenshot_72](https://cloud.githubusercontent.com/assets/19670319/17119784/fbb0919c-5295-11e6-8d92-bfd12b1b77fa.png)


- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17119788/05135f6c-5296-11e6-98cf-cceb4a2f36bf.png)

**Comment by kmiloxvii** [comment]
En la versión 21.0 de la CBP este error ya no me sucede

![phone](https://cloud.githubusercontent.com/assets/2491042/17119808/2fba3998-5296-11e6-8d8a-8f7c42f7bbbc.png)
