### ISSUE TITLE
Bitcoin Wallet-Import Key trasladó saldo de btc errado

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#703]
#### Nombre pantalla

Bitcoin Wallet
### Nombre de la Aplicación 

Bitcoin Wallet (20.9.1)

-----

##### Reporte de error: 

Luego de realizar varias transacciones en la Bitcoin wallet (Nexus 4  5.1) y tenerlas reflejadas en SENT y RECEIVED (imagen 1), fui hacia los settings generales de la aplicación y  pulse Export Keys  y copie la clave de texto y la clave numérica (imagen 2) y luego abrí otro teléfono (Nexus 4  5.0) con la misma aplicación y me fui hacia settings generales y coloque la clave extraída del primer teléfono y me salio un mensaje de que la importación se había completado y que el dinero se confirmaba en unos minutos, luego cree un usuario con el mismo nombre en la Bitcoin Wallet (segundo teléfono) para poder ingresar a ella y estando dentro al pasar aproximadamente un minuto se cargo un monto de bitcoins mayor a la cantidad que tenia reflejada en el primer teléfono (imagen 3). En el segundo teléfono solo se reflejo en el Book y nunca paso a Current.    

Imagen 1:
![12345](https://cloud.githubusercontent.com/assets/19883115/17042717/1437347a-4f7e-11e6-8aa2-b35d765690db.png)
  
Imagen 2:
![doble5](https://cloud.githubusercontent.com/assets/19883115/17043002/b4a159a2-4f80-11e6-87df-d8f615ba4f05.png)

Imagen 3:
           Teléfono 1 (Nexus 5.1)                                                         Teléfono 2 (Nexus 5.0)

![change](https://cloud.githubusercontent.com/assets/19883115/17044071/727f4b6a-4f8a-11e6-87aa-0c5b4adad1c3.png)

  

##### Pasos exactos para reproducir el error:

1 Realizar transacciones en la Bitcoin wallet (Nexus 4 5.1)
2 Extraer clave (Nexus 4 5.1)
3 Abrir nuevo teléfono    (Nexus 4 5.0)
4 Ingresar clave en el nuevo teléfono  (Nexus 4 5.0)
5 Dirigirme a la Bitcoin Wallet del nuevo teléfono (Nexus 4 5.0)

##### Inserta Archivo aLogcat: 

Logcat telefono 1 (Nexus 4 5.1)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/377271/logcat.txt)

Logcat telefono 2 (Nexus 4 5.0)
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/377239/logcat.txt)

 

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![chi](https://cloud.githubusercontent.com/assets/19883115/17043346/c4c835aa-4f83-11e6-845f-624baefeb30e.png)
![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17043390/2d24e382-4f84-11e6-85c2-00f7a9be85dc.png)

**Comment by acostarodrigo** [comment]
sigue sin confirmarse el balance en el segundo dispositivo?

**Comment by nattyco** [comment]
@sanro14  @GeronimoVierma  Rodrigo me aclara que el traspaso de los btc de una wallet a otra, tiene el costo del fee, por lo tanto el balance que recuperen va a ser menor al que tenian. La confirmacion del balance en la nueva wallet puede tardar hasta media hora.

**Comment by GeronimoVierma** [comment]
@acostarodrigo 

El día de hoy he estado probando con la misma versión (20.9.1) y esta vez si se me reflejo el balance en el segundo dispositivo, los pasos que seguí fueron los mismos excepto porque entre en la Bitcoin Wallet con un perfil predeterminado "Jhon Doe" y en este caso si se confirmo el balance al segundo teléfono con aproximadamente 3 btc mas de lo que tenia en el primer teléfono:


![4](https://cloud.githubusercontent.com/assets/19883115/17061259/a5174c32-4ffb-11e6-960e-94b2bec9db6e.png)

**Comment by GeronimoVierma** [comment]
Prueba con la versión 20.9 CBP:

![screenshot_12](https://cloud.githubusercontent.com/assets/19883115/17074648/bbfde168-504b-11e6-8934-66a480918e6f.png)

**Comment by marielis-urbina** [comment]
Con la versión 20.9 , al hacer la importación del Key, el resultado en mi segundo emulador del balance es menor, tomando en cuenta lo que menciona @nattyco, es correcto el resultado. Pero el de Book la diferencia es mayor. Hay que evaluar si solo se tomara en cuenta el Current.

Captura del Current
![key1](https://cloud.githubusercontent.com/assets/19353722/17074640/7742cd40-504b-11e6-97ee-948d1af49635.png)

Captura del Book
![key2](https://cloud.githubusercontent.com/assets/19353722/17074642/89802110-504b-11e6-8608-83df3f49929f.png)

**Comment by acostarodrigo** [comment]
El import pasa los bitcoins  de donde se hizo el export a un nuevo dispositivo. Este pasaje tiene un pequeño costo de fee.

Es decir, si en el dispositivo A tengo 4 BTC y en el dispositivo B tengo 1 BTC, y hago un export del A y luego un import en el B, el saldo en B debería ser 1 BTC + (4 BTC - fee), es decir 1 BTC + 3.9995.

Una vez que importan en el dispositivo B, el dispositivo A no lo deben utilizar y lo tienen que reinstalar. 

El balance book es el balance que todavía no se confirmó por los mecanismos internos de la red de bitcoin. Hasta que no esté confirmado, no se puede gastar. Cuando se confirma en la red, lo correcto es que el balance book y available se igualen, indicando que todas las transacciones que se realizaron fueron confirmadas por la red.


Sugiero que hagan las siguientes pruebas:
* Obtener BTC en el dispositivo A y exportar la clave.
* Importar en un emulador B vacío, sin bitcoins. y verificar que el saldo available y book es lo que tenian en el dispositivo A menos el fee.

* Obtener BTC en el dispositivo A y exportar la clave.
* Obtener BTC en el dispositivo B
* Importar clave en dispositivo B
* Verificar que el saldo es el correcto. El saldo de B debe ser: Saldo B + Saldo A - Fee.

**Comment by marielis-urbina** [comment]
Prueba: 25-07-16
Versión 20.9 de CBP

Dispositivo B.......................................................................................................... Dispositivo A
![prueba 1](https://cloud.githubusercontent.com/assets/19353722/17104469/052d2216-5251-11e6-9410-a8264a3320cc.png)

Dispositivo B + 1 BTC solicitado
![prueba 2](https://cloud.githubusercontent.com/assets/19353722/17104474/0a558e54-5251-11e6-82a3-e8c529d32356.png)

Emulador A
![samsung](https://cloud.githubusercontent.com/assets/19353722/17104477/115c337e-5251-11e6-9747-3e8fbe678ce1.png)

Emulador B
![nexus 4-5 1](https://cloud.githubusercontent.com/assets/19353722/17104493/2c1bcf44-5251-11e6-8475-ed605c2b94fc.png)

**Comment by acostarodrigo** [comment]
looks good to me.

**Comment by GeronimoVierma** [comment]
En mi caso (20.9 de CBP):
(Nexus 4  5.1 primer dispositivo) ( Nexus 4 5.0 segundo dispositivo)

Resultado de la importación:
![screenshot_13](https://cloud.githubusercontent.com/assets/19883115/17106376/19ba6272-5259-11e6-8454-5742709d5d20.png)

Segundo dispositivo mas 1 btc solicitado:
![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17106469/6dbdc990-5259-11e6-9aa2-547c1fda3199.png)



![chi](https://cloud.githubusercontent.com/assets/19883115/17106562/cd8e8cce-5259-11e6-8982-c82fac8e66bd.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17106544/bf28ca96-5259-11e6-899d-4b5167f117a2.png)

**Comment by acostarodrigo** [comment]
perfect. son los resultados esperados.
En breve, la funcionalidad de export/import solamente estará habilitada para Producción, es decir bitcoins reales. No se podrá recuperar BTC de testnet, solamente producción.

**Comment by MaviDavsa** [comment]
Solucionado
