### ISSUE TITLE
Bitcoin Wallet-Import Key, el Dispositivo anterior queda con Saldo Activo y se pueden realizar transacciones 

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#705]
### Nombre de la Aplicación:  BTC

-----

##### Reporte de error: 

   *En el momento de la importación del Key el saldo de mi viejo emulador queda activo, dejando hacer **transacciones.*

##### Screenshot o Capture de pantalla:

Emulador Viejo
![imp3](https://cloud.githubusercontent.com/assets/19353722/17043274/130b11d4-4f83-11e6-9cb0-48dd1f91eb3b.png)

Emulador Nuevo
![nuevo](https://cloud.githubusercontent.com/assets/19353722/17043343/c03e29c2-4f83-11e6-9d76-cd7ac2611114.png)

Transacciones Posteriores
![capt 8](https://cloud.githubusercontent.com/assets/19353722/17043316/96762f36-4f83-11e6-86e3-c95d32aa2647.png)
![capt9](https://cloud.githubusercontent.com/assets/19353722/17043328/ac5d05c2-4f83-11e6-9ef3-89838a95fe47.png)

##### Pasos exactos para reproducir el error:

 *Detallar paso a paso la forma en  la cual se logro el error.

- Después de la importación del Key, al pasar tres minutos, revise la Bitcoin Wallet e intente hacer transacciones a ver si mi cuenta estaba activa. Pude realizar dos envíos de Btc a dos de los contactos existentes.

##### Inserta Archivo aLogcat: 
 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/377259/logcat.txt)

-----

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:
 
![samsung](https://cloud.githubusercontent.com/assets/19353722/17043528/7da51b28-4f85-11e6-9d5f-98a776d04672.png)

**Comment by nattyco** [comment]
@AdryCanonico  la wallet exportada va a quedar con balance, porque no hay forma de eliminarlo, ya queno se tiene aces al otro dispositivo.
No se puden hacer transacciones porque te las reversa la Crypto Network porque no hay fondos en la blockchain asociados a la wallet vieja. Hablemos y les explico como funciona.

**Comment by AdryCanonico** [comment]
ok @nattyco  mañana nos reunimos y hablamos de esto! :+1:

**Comment by nattyco** [comment]
@marielis-urbina  @AdryCanonico  comentar si despues de hacer la importacion la wallet antigua sigue funcional, o si las transacciones se reversan al querer hacerlas.

**Comment by marielis-urbina** [comment]
Despues de hacer la importacion la wallet antigua no funcional, las transacciones se reversan al querer hacerlas, dejando el saldo igual.

**Comment by MaviDavsa** [comment]
Solucionado
