### ISSUE TITLE
BITCOIN WALLET- ERROR AL MOSTRAR CONTACTOS

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#706]
Template issue error report

 Nombre pantalla

CONTACTOS

Nombre de la Aplicación 

BITCOIN WALLET

Reporte de error: 

Cuando presiono CONTACTS para seleccionar uno de los usuarios y realizar una transaccion, me aparece el mensaje de ERROR en un recuadro gris, tal y como se señala a continuación:

![image](https://cloud.githubusercontent.com/assets/18740418/17112170/eec4e096-5272-11e6-98ba-1d7b841695f2.png)

 
Pasos exactos para reproducir el error:

1. Envío o acepto conexión en la community de la  CRIPTO WALLET con los usuarios que aparecen.
2. Ingreso en la BITCOIN WALLET.
3. Presiono CONTACTS.

 Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/382201/logcat.txt)

 Emulador de prueba:

![image](https://cloud.githubusercontent.com/assets/18740418/17112565/8c3e9a3c-5274-11e6-98f8-554fbb320e16.png)

**Comment by camilavaleria** [comment]
@nattyco @AdryCanonico

**Comment by andreagmarcano** [comment]
Sale el error al entrar a contactos. 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/382307/logcat.txt)

![image](https://cloud.githubusercontent.com/assets/18452495/17114696/ff79f38a-527d-11e6-9353-d154d2dfc2b4.png)

![image](https://cloud.githubusercontent.com/assets/18452495/17114716/1a190190-527e-11e6-82a5-bcf26284f5c6.png)

**Comment by andreagmarcano** [comment]
Persiste el error en la version 20.10 de CBP

![image](https://cloud.githubusercontent.com/assets/18452495/17116154/791af62a-5284-11e6-9c90-74512ad2a282.png)

![image](https://cloud.githubusercontent.com/assets/18452495/17116203/b5842e74-5284-11e6-8ea9-a1ac87e90a52.png)

 @nattyco

**Comment by Elbamarina** [comment]
en la vesion 21.0 apk reciente sigue apareciendo el mismo error de java.lang, con la misma version de API de quien reporta el caso

**Comment by kmiloxvii** [comment]
En la version 21.0 apk sigue sucediendo 

![phone](https://cloud.githubusercontent.com/assets/2491042/17193553/a177dfcc-5421-11e6-86c2-26b2cb0bb190.png)

**Comment by wendyduran90** [comment]
En la versión 21.0 persiste el error . Esta prueba se realizo desde un móvil con versión de android 4.4.4 

![screenshot_2016-07-27-17-48-57](https://cloud.githubusercontent.com/assets/20212920/17193895/28538522-5423-11e6-8a7c-b6e97560bd5e.png)

**Comment by maydiamc** [comment]
en la versión 21.0 de CBP, sucede este error

![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/17224581/891ef98e-54cf-11e6-8b55-4659a1eb2f29.png)

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/17224579/8310fc22-54cf-11e6-8f04-b7856f307bc3.png)

**Comment by andreagmarcano** [comment]
En la version 21.1 de CBP no muestra el error 
![andrea 29](https://cloud.githubusercontent.com/assets/18452495/17250496/96d55ae8-5572-11e6-88d4-31f5914c5653.PNG)
![29](https://cloud.githubusercontent.com/assets/18452495/17250513/a304bfac-5572-11e6-9d2c-3626af20a50e.PNG)

**Comment by GeronimoVierma** [comment]
En la versión 21.1 de CBP esta solucionado el error:

![screenshot_5](https://cloud.githubusercontent.com/assets/19883115/17252697/a2ce9d7e-557b-11e6-9f45-2c0eb58582e2.png)


![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17252730/b1f459a6-557b-11e6-95d5-b0f23b883a3e.png)

**Comment by nelsondb** [comment]
Estaba agregando 5 contactos para BW, cuando culmino el proceso  fui a revisar, me salio ese error y solo 2 contactos.
Versión 21.2 
![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/17306111/3c0c581e-57fc-11e6-8123-f9451a785323.jpg)


**LOGCAT**
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/394619/logcat.txt)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by dorzar1989** [comment]
En la Version 21.2 de la CBP Continua este error:

- Screenshots:

![screenshot_121](https://cloud.githubusercontent.com/assets/19670319/17328172/33a83cea-588a-11e6-8edb-828aefc54dd9.png)

- Logcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/396951/logcat.txt)

- Hora y Fecha: 

8: 13 am --- 02/08/2016

- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17328182/3daaff0c-588a-11e6-82f1-2df748fbd98d.png)

**Comment by yolandayancel** [comment]
Prueba 02-08-16
Caso 706 CBP 21.2 (Bitcoin WALLET)
Nexus 5 5.0.0 api21 480Dpi
Ocurre lo reportado..
![screenshot_25](https://cloud.githubusercontent.com/assets/17283358/17328615/a6a0945c-588c-11e6-9a7b-1f4d238bf6c5.png)

**Comment by wendyduran90** [comment]
En la versión 21.2 sigue ocurriendo el error . Estas pruebas se realizaron desde un móvil con versión de android 4.4.4

![screenshot_2016-08-02-08-33-02 1](https://cloud.githubusercontent.com/assets/20212920/17329304/12782598-5890-11e6-8995-7ec75327d499.jpg)

**Comment by dorzar1989** [comment]
En la Version 21.3 de la CBP no me ocurre este error.

- Screenshot:

![screenshot_136](https://cloud.githubusercontent.com/assets/19670319/17366720/a9f9af48-595a-11e6-90b5-7947629fe1e9.png)

- Emulador: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17366715/9ffbb0a4-595a-11e6-9b15-5c670e8aadcf.png)

**Comment by GeronimoVierma** [comment]
CBP-21.3

El error esta solucionado:

![screenshot_11](https://cloud.githubusercontent.com/assets/19883115/17370919/f854b2ee-596b-11e6-9877-fdde2917fff1.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17370963/1e7c3d34-596c-11e6-870c-9b2c94f66ca2.png)

**Comment by IsbetVR** [comment]
Closed #706

**Comment by JeanFranco498** [comment]
Version  22.1 persiste este error 

![image](https://cloud.githubusercontent.com/assets/19807906/17736548/77a4f776-6456-11e6-870f-6915a56d3324.png)

![datos 4 1](https://cloud.githubusercontent.com/assets/19807906/17736576/9dd394a2-6456-11e6-96dd-c8687257efb6.jpg)

**Comment by nattyco** [comment]
@JeanFranco498 podrias decirme que contactos con nros en el nombre tenias? si podes decirme los nombres para reproducir el error.

**Comment by nattyco** [comment]
@AdryCanonico necesitaria mas informacion sobre este error ya que no lo puede reproducir, al parecer el problema es con los contactos con nros, si se produce de nuevo necesito saber los nombres de los contactos.

**Comment by wendyduran90** [comment]
En la versión 22.6 ya no sucede este error , se verifico con contactos que tenían números en su user. La prueba se realizo desde un teléfono físico con versión de android 4.4.4 marca BLU modelo Life One 2015.

**Comment by JeanFranco498** [comment]
En la version 22.6 ya no sucede este error... La prueba se realizo desde teléfono físico Android 4.3 Samsung S3
