### ISSUE TITLE
BITCOIN WALLET- No reconoce un usuario que esta dentro de mis contactos

### ISSUE THREAD

**Issue by Elbamarina** [Fermat-ORG/beta-testing-program#707]
#### Nombre pantalla

BITCOIN WALLET

### Nombre de la Aplicación 

BITCOIN WALLET

-----

##### Reporte de error: 

  Acepte 3 contactos en el CCP COMMUNITY, al tratar de agregarlos en mis contactos del Bitcoin Wallet, me trasladò a la ventana del CCP COMMUNITY, como si estuviese aceptando un nuevo usuario, el usuario 2507T FranciscoWallet, me envió 0,002 Btc, cuando trato de aceptarlo me mostró usuario unknown para aceptar la transacción y me mostrò un mensaje que no podía recibirlos ya que no tenia suficiente fondos, y no podía aceptar la recepción del payment.

##### Screenshot o Capture de pantalla:

![image](https://cloud.githubusercontent.com/assets/20233056/17112211/1d4b34ec-5273-11e6-9d69-893c86b265e7.png)
![image](https://cloud.githubusercontent.com/assets/20233056/17112233/38e532d4-5273-11e6-880e-8a0a6e93bf66.png)
![image](https://cloud.githubusercontent.com/assets/20233056/17112251/46d6cc5e-5273-11e6-9656-da6b8aad2721.png)
![image](https://cloud.githubusercontent.com/assets/20233056/17112285/72d856ec-5273-11e6-915d-bab1e7067032.png)

##### Pasos exactos para reproducir el error:

1.- Ingrese al CCP Community Para Aceptar las notificaciones de los contactos.
2.- Acepto los Contactos En el CCP.
3.- Ingreso a Bitocoin Wallet, la opcion de Contactos.
4.- presiono el boton "+" para ingresar en la opcion de Fermat User
5.- marcos las casillas de cada usuario aceptado en la CCP.
6.- Pulso el icono del Simbolo Agregar usuario que esta en la parte superior derecha de la pantalla y me redirecciona al CCP Community.
7.- Ingreso a Payment Request dentro del Bitcoin Wallet y aun que estaban los usuarios agregados en la CCP y pero en la Bitcoin Wallet no lo permite, me aparecen los contactos que me enviaron BTC como "Unknown" notificando el envio de los BTC.
8.- Al Tratar de aceptar los BTC aparece el mensaje "Insufficient Founds - Can't Access Receive Payments".
9.- Por ende las transacciones quedan en siempre dispoibles pero no aceptables.

##### Inserta Archivo a Logcat: 

 [logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/382186/logcat.txt)
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 *Agregar las capture de la descripción del emulador o teléfono.
![image](https://cloud.githubusercontent.com/assets/20233056/17112300/870eeb12-5273-11e6-87d4-ee6483482293.png)

@AdryCanonico

**Comment by nattyco** [comment]
@AdryCanonico @Elbamarina  necesito que me aclares un par de cosas, en tu reporte hay varias cosas mescladas, seria mejor que los separes.

No estas aceptando recibir bitcoins de un contacto, los payments request son requerimientos de pago, le vas a enviar btc a esa persona que te los solicita. Para lo cual necesitas tener fondos disponibles en tu wallet por un monto superior al monto del requerimiento de pago.

Que tengas conexiones en la community de ccp no implica que sean contactos de la wallet.
Por lo que decis en tu reporte no los pudiste agregar, entonces el requerimiento de pago no va a tener identificado el contacto.

Para agregar a los fermat user como contactos de la wallet, los marcas y apretas el boton con el + que esta en el action bar del celular.

Aclarame los pasos que seguiste porque en las capturas no puedo ver si tenias balance suficiente, y si tenias al contacto en  la lista de contactos de la wallet.

**Comment by sanro14** [comment]
@Elbamarina @nattyco voy a cerrarlo para probar en la version de CBP integrada con CCP para ver si sucede lo mismo, en tal caso se reabre
