### ISSUE TITLE
CBP - Cambia el monto del "amount to buy" a "0" cuando el broker confirma y envia al customer

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#709]
#### Nombre pantalla

Crypto Customer Home

### Nombre de la Aplicación 

Crypto Customer

1. Se procedió a realizar una negociación por el monto de 0.1 btc

2. El broker recibe la negociación y la devuelve al customer.

![geronimobroker](https://cloud.githubusercontent.com/assets/2491042/17120911/9814f210-529d-11e6-87ff-242279fbc1ac.png)

3.El customer recibe la negociación y procede a confirmarla pero el amount to buy paso de 0.1 a 0.

![amount_buy](https://cloud.githubusercontent.com/assets/2491042/17121094/03af122a-529f-11e6-8940-96d2053f3c0a.png)

se intento cambiar el **amount to buy** de nuevo a 0.1 btc u otro valor  pero al hacerlo el **amount to pay** cambia de valor a cero.
Cuando se modifica el **amount to pay**  el **amount to buy** cambia a cero por lo que no permite avanzar ya que estos montos deben ser mayor a cero.

![buy](https://cloud.githubusercontent.com/assets/2491042/17121252/6025d63c-52a0-11e6-8038-e6f39468da77.png)

![pay](https://cloud.githubusercontent.com/assets/2491042/17121259/6938dfb2-52a0-11e6-8c29-66b0b73ec85e.png)

![mensaje cero](https://cloud.githubusercontent.com/assets/2491042/17121262/743830fc-52a0-11e6-8702-d4712c033b3c.png)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![phone](https://cloud.githubusercontent.com/assets/2491042/17121216/0f9e65d0-52a0-11e6-9397-d6f4563be8fc.png)

LogCat
[Uploading Samsung Galaxy S4 - 4.2.2 - API 17 - 1080x1920-logcat.txt…]()

**Comment by sanro14** [comment]
@nelsonalfo

**Comment by GeronimoVierma** [comment]
27-07-2016
CBP-21.0
Estaba como Customer y le envié negociación a un Broker comprándole 0.1 btc (imagen 1) el cual la recibió y lleno las casillas sin modificar nada, al recibir su respuesta el monto había cambiado de 0.1 a 1btc (imagen 2):

![screenshot_6](https://cloud.githubusercontent.com/assets/19883115/17197400/8e22eb7e-543a-11e6-9eac-40f68df616da.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/19883115/17197425/a6717c72-543a-11e6-9760-583ede4b5707.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17197442/c2514724-543a-11e6-9ef0-531274d96e9c.png)

**Comment by gablup** [comment]
El error persiste en la versión 21.2 de CBP.

![screenshot_2016-08-01-16-25-49](https://cloud.githubusercontent.com/assets/17261437/17307971/a0f3c114-5805-11e6-839b-c609548432ae.png)

![screenshot_2016-08-01-16-25-29](https://cloud.githubusercontent.com/assets/17261437/17307992/c1d45d94-5805-11e6-97e8-eddc6d357b65.png)

![acerca del tlf](https://cloud.githubusercontent.com/assets/17261437/17308040/ef5a6c2c-5805-11e6-8d28-b1fa02f07d21.png)

Fecha: 01-08-16
Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB.

**Comment by arosiopr** [comment]
en la versión 21.6 de CBP no sucede este error @MaviDavsa

**Comment by GeronimoVierma** [comment]
En la versión 21.6 de CBP ya no sucede este error.

**Comment by maydiamc** [comment]
en la version 21.6 no sucede este error

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17481557/ceb34f5c-5d4b-11e6-9d0d-059cf61a96d0.png)
