### ISSUE TITLE
Bitcoin Wallet- Problemas para enviar bitcoins

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#71]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

**A pesar de tener 100 Btc no puedo enviar los mismos por que nunca los tengo Available, desde ayer que tengo Bitcoin pero nunca están disponibles, hoy cargue 50 Btc mas para ver si los podía tener disponibles y no llegue a buen puerto.**

<img width="478" alt="captura de pantalla 2016-03-09 a las 12 48 43" src="https://cloud.githubusercontent.com/assets/15804433/13640972/8e4bc30e-e5f5-11e5-8f55-cfabac781b90.png">

<img width="475" alt="captura de pantalla 2016-03-09 a las 12 43 48" src="https://cloud.githubusercontent.com/assets/15804433/13640757/af506452-e5f4-11e5-932c-80083de23642.png">

<img width="402" alt="captura de pantalla 2016-03-09 a las 12 42 32" src="https://cloud.githubusercontent.com/assets/15804433/13640752/ab7340d4-e5f4-11e5-8373-abb21377e4bc.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="477" alt="captura de pantalla 2016-03-09 a las 12 45 06" src="https://cloud.githubusercontent.com/assets/15804433/13640791/cdf0c988-e5f4-11e5-9b94-accece2288e0.png">

**Comment by furszy** [comment]
No los vas a poder gastar los btc porque no los tenes en el available balance, el que nos puede decir que pasas es @acostarodrigo . él esta manejando la regtest y nuestra conexión con la red de bitcoin.

**Comment by augusto-ponce** [comment]
Ok Mati espero respuesta de Rodrigo

**Comment by acostarodrigo** [comment]
Ya hay un fix en Develop relacionado con la notificación de bitcoins confirmados.
Por favor actualizar y volver a probar.

Si la red en la que prueban es de testing, se tarda más en confirmar un bloque debido al tamaño de transacciones y el download del blockchain. Para ello, debemos implementar el notificador de cuándo terminamos de hacer el download del blockchain.

@nattyco ya está en develop esta interfaz #5237

**Comment by maydiamc** [comment]
yo tengo el mismo problema ya que recibi BTC a traves de un payment request y solo se refleja en el book balance y nunca se hace efectivo en el available balance.

Modelo del telefono: samsung galaxy miniS4
version de android: 4.4.2 Kit Kat

**Comment by nattyco** [comment]
@augusto-ponce @maydiamc  Probar y cerrar si los btc ya se confirman.
