### ISSUE TITLE
Bitcoin Wallet_ Pop up de bienvenida se abre una y otra vez

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#712]
#### Nombre pantalla
Home 

### Nombre de la Aplicación 
Bitcoin wallet

-----

##### Reporte de error: 

   *Se repite el pop up de bienvenida cada vez que se abre la aplicacion

##### Screenshot o Capture de pantalla:

![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/17215060/9b27b312-54a9-11e6-8749-dbec1bc21f61.png)

##### Pasos exactos para reproducir el error:

- Abrir bitcoin wallet
- Darle al ganchito para que no se muestre nuevamente
- cerrar la bitcoin wallet
- ingresar de nuevo y se abrirá el pop up de bienvenida otra vez

##### Inserta Archivo aLogcat: 

Hora: 9:53am
[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/388500/logcat.zip)
 
 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/17215186/097ff98c-54aa-11e6-9bff-59770be2f5ee.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by Gabymorillo** [comment]
En la versión 21.1 de la CBP, desde el emulador no sucede este error.

![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17253522/19246e42-557f-11e6-8856-ebe9526115a1.png)

**Comment by maydiamc** [comment]
solucionado en la version 21.1 de CBP

Emulador
![especificaciones](https://cloud.githubusercontent.com/assets/17274154/17254015/15ae29ea-5581-11e6-859c-d91ba0042023.png)

**Comment by GeronimoVierma** [comment]
Solucionado el error (21.1 de CBP)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17254125/7627b9f8-5581-11e6-92e3-cf900caf2442.png)
