### ISSUE TITLE
ERROR DE SYSTEM RECOVERY

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#713]
#### Nombre pantalla

CONTACTS

### Nombre de la Aplicación 

CBP 21.0
-----

##### Reporte de error: 

   *En este caso en especifico el error se dio estando en la Bitcoin Wallet: me fui a agregar  a los usuarios que me solicitaron conexiones, pero al queren entrar en un perfil de contactos me salio el recuadro de Recovering 

Sin embargo el error se puede reproducir en cualquier pantalla, en cualquier momento.

 *Agregar las capture del error en el emulador o teléfono donde se produjo. 
Foto 1
![screenshot_11](https://cloud.githubusercontent.com/assets/17283358/17216085/2fcfb7e6-54ad-11e6-931d-54153ed9470c.png)

##### Pasos exactos para reproducir el error:

 *Detallar paso a paso la forma en  la cual se logro el error.
1 Estando en contactos de la Bitcoin Wallet. Clickee en Fermat user
2 Agregue los contactos 
3 Volvi a contactos y trate de ingresar en uno de ellos para verificar si tenia la direccion.
4 Me salio un recuadro de recovering y me saco de la apk..

##### Inserta Archivo aLogcat: 
1 Recovering
[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/388546/logcat.zip)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![sansung s6 5 1 0](https://cloud.githubusercontent.com/assets/17283358/17216359/55c135f0-54ae-11e6-8f28-d3d452a757d2.png)

**Comment by GeronimoVierma** [comment]
CBP-21.0
8:02 pm
Estando yo como Customer hacia una negociación con un Broker la cual paso a contrato y al estar en la Customer wallet  (imagen 1) y darle click en el contrato para llenar las casillas me salio el recuadro de Recovering (imagen 2) 

![screenshot_12](https://cloud.githubusercontent.com/assets/19883115/17233600/133cb2b2-54ff-11e6-930f-b48d9a5c25ed.png)

![screenshot_11](https://cloud.githubusercontent.com/assets/19883115/17233636/67b2d9c0-54ff-11e6-8d9d-d33e9c0b9bdd.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17233647/800e1c32-54ff-11e6-88c0-74f5d5c19e47.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/389649/logcat.txt)

**Comment by GeronimoVierma** [comment]
CBP-21.0
9:20 am (aproximadamente)
Estando yo como Customer hacia un contrato con un Broker el cual se finalizo con éxito y de inmediato fui a revisar la Banking Wallet (imagen 1), al darle click en el icono de la Banking Wallet me salio el recuadro de Recovering (imagen 2):



![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/17250896/5cc0b5e4-5574-11e6-8c5e-7cfd91ad5207.png)




![screenshot_2](https://cloud.githubusercontent.com/assets/19883115/17250883/4c7f53ac-5574-11e6-9b5a-e414cdd4ba12.png)






[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/390654/logcat.txt)

**Comment by Gabymorillo** [comment]
En la versión 21.1 de la CBP desde el emulador no sucede este error.

![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17253477/fc155136-557e-11e6-8fba-c9ead367324e.png)

**Comment by yolandayancel** [comment]
Prueba 29-07-16
Caso 713 CBP 21.1(BitcoinWallet)
Samsung S6 5.1.0 Api22  640dpi

Ya no ocurre lo reportado..
Detalle paso a paso:
1 Ingreso a  contactos de la Bitcoin Wallet. Clickee en Fermat user
2 Agregue los contactos 
3 Volvi a contactos e  ingrese en un ( para verificar si tenia la direccion.)
4 No  salio el  recuadro de recovering .

![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17253943/d0afa256-5580-11e6-905b-883715976792.png)

**Comment by Gabymorillo** [comment]
En la versión 21.1 de la CBP, desde el emulador, después de configurar la Crypto Customer, iba a entrar a la Broker List y dió. "Recovering from system error"


![capture-20160729-134918](https://cloud.githubusercontent.com/assets/17262077/17258232/e0e95866-5593-11e6-8dce-5231387c1000.png)

![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17258209/c379b302-5593-11e6-977b-4e9d467a25a0.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/391069/logcat.txt)

**Comment by GeronimoVierma** [comment]
CBP-21.1
8:20 am (aproximadamente)
Me encontraba configurando la Crypto Broker y cuando fui hacia los settings y luego darle click en "Stock Management" (imagen 1), me apareció el recuadro Recovering (imagen 2):

![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/17294022/0b561438-57c2-11e6-983c-4e4daa4f0060.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/19883115/17294077/63fa90e6-57c2-11e6-979b-357adb77e4df.png)


![chi](https://cloud.githubusercontent.com/assets/19883115/17294034/3097ab94-57c2-11e6-8269-ea3f7712d13f.png)





[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/393707/logcat.txt)

**Comment by GeronimoVierma** [comment]
CBP-21.1
8:50 am (aproximadamente)
Me encontraba haciendo una negociación con un Customer, luego de llenar las casillas en la ficha de la negociación (imagen 1), al darle click al botón Send me aparecio el recuadro "Recovering from system error" (imagen 2):

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17294858/4a4a6838-57c7-11e6-9ecd-7ffcf6805668.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/19883115/17294862/50189884-57c7-11e6-8811-8ffa33110e2d.png)


![chi](https://cloud.githubusercontent.com/assets/19883115/17294922/a2f5ae84-57c7-11e6-9558-93005751f5e7.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/393831/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 01-08-2016
Caso   613   CBP V 21.2
Nexus 5 5.0.0 api 21 480dpi
En este emulador, si ocurre lo reportado.
![screenshot_13](https://cloud.githubusercontent.com/assets/17283358/17304385/640ef2e4-57f3-11e6-9348-5f2eb501d162.png)

**Comment by IsbetVR** [comment]
En la versión 21.2 de CBP sucedió este error cuando entré a la Crypto Customer para verficar la Broker List

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/17304422/84c5c62a-57f3-11e6-8d30-e18df9e01a99.jpg)

#### Archivo Logcat
Hora 2.10pm

[713-logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/394476/713-logcat.zip)

#### Emulador 

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/17304476/bd670606-57f3-11e6-9d0a-c943b34a7fa8.jpg)

**Comment by Gabymorillo** [comment]
En la versión 21.3 de la CBP. Al tratar de responder la negociación con el Broker, salió "recovering from system error" y luego "fermar no responde"

![capture-20160803-084239](https://cloud.githubusercontent.com/assets/17262077/17366070/4ee938b0-5957-11e6-8a97-dd8e70716e17.png)

![capture-20160803-084503](https://cloud.githubusercontent.com/assets/17262077/17366072/526d8b58-5957-11e6-90fd-5c4c7a968504.png)

![capture-20160721-175754](https://cloud.githubusercontent.com/assets/17262077/17366080/580c3fb4-5957-11e6-8180-dd868ce277da.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/399461/logcat.txt)

**Comment by GeronimoVierma** [comment]
En la versión 21.3 de CBP sucedió este error cuando estando en la Broker Wallet (imagen 1), le di click al contrato y me salio "Recovering...." (imagen 2)

![screenshot_6](https://cloud.githubusercontent.com/assets/19883115/17365933/a78ac5c0-5956-11e6-8c9e-a047ad883699.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/19883115/17365948/b29fde14-5956-11e6-9b4c-8b2dda2a9df7.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17365962/bf7c1bc0-5956-11e6-88ed-cbad1dcf78f1.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/399467/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 03-08-16
Caso 613 CBP 21.3 
Samsung 5.1.0 api 22 640dpi
Ocurre lo reportado. (Cash Wallet)
![713](https://cloud.githubusercontent.com/assets/17283358/17377921/e92f9428-5989-11e6-9030-54190dbac995.png)

**Comment by yolandayancel** [comment]
Prueba 4

3-08-16
Caso 713 CBP 21.3
Samsung 5.1.0 api 22 640dpi
Ocurre lo reportado. (Crypto Customer)

![713](https://cloud.githubusercontent.com/assets/17283358/17401607/89128c4c-5a1c-11e6-9a25-82309f227dcb.png)

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 713 CBP21.6
Sony Xperia 4.1.1 16api 320Dpi
persiste lo reportado..
![713](https://cloud.githubusercontent.com/assets/17283358/17445410/cf2817aa-5b12-11e6-8b80-b642f778fdf4.png)

**Comment by maydiamc** [comment]
en la versión 21.6 de cbp, al intentar entrar a la pantalla fermat contact, me salio recovery varias veces y me llevaba al menú de inicio de Fermat

logcat 1:50 aprox
[log 713.zip](https://github.com/Fermat-ORG/beta-testing-program/files/404339/log.713.zip)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17446112/c8547754-5b15-11e6-83dc-a33af23f1fb1.png)

**Comment by GeronimoVierma** [comment]
En la versión 21.7 de CBP sucedió este error cuando estando en P2P Chat (imagen 1), al darle click a uno de los chat que tenia abierto me salio "Recovering...." (imagen 2) Hora: entre las 4:00pm y 4:10pm (aproximadamente)


![screenshot_6](https://cloud.githubusercontent.com/assets/19883115/17494755/1c917216-5d84-11e6-8c59-bdbdba7128d5.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19883115/17494767/29c36782-5d84-11e6-96c0-fa7a0e03b79c.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/19883115/17494787/3e1a5a92-5d84-11e6-8554-36d92f06e0c0.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/407689/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 08-08-16
Caso 713 CBP 21.7 (CHAT)
Nexus 5 6.0.0 api 23 420 dpi

logcat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/407645/logcat.txt)




Ocurrio lo reportado (Pero estando dentro de una conversación  del Chat)
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/17494254/eab4dac8-5d81-11e6-8c4b-b6593b299284.png)

**Comment by yolandayancel** [comment]
Prueba 09-08-16
Caso 726 CBP V21.7
Sony Xperia S 4.1.1 16api 320dpi
ocurre lo reportado (apareció al tratar de crear una cuenta en la Bank, apareció en recovering y se salio a la pantalla que aparece en la foto)
![screenshot_4](https://cloud.githubusercontent.com/assets/17283358/17519202/f632c468-5e18-11e6-980e-f6d32fc3e249.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 713  CBP 21.9
Sony Xperia S 4.1.1 16 api 320 dpi

Durante las pruebas en la CCP no ocurrio este caso 713, ni una sola vez..

**Comment by GeronimoVierma** [comment]
Versión 21.9 CBP
Hora: 11:00 (aproximadamente)
Me encontraba en una conversacion de chat (imagen 1), cuando al darle click para salir de esa pantalla me salio el mensaje de "Recovering...." (imagen 2):

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/415640/logcat.txt)

![chat](https://cloud.githubusercontent.com/assets/19883115/17628256/965377ce-6082-11e6-8b1e-c56e6898ae37.png)

![recovering](https://cloud.githubusercontent.com/assets/19883115/17628262/9e2e046e-6082-11e6-9ba6-ebe3acc8019d.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17628267/a685546e-6082-11e6-9cad-e3f2eb4a35ea.png)

**Comment by yolandayancel** [comment]
Prueba 12-08-16
Caso 713 CBP 21.9
Sony Xperia S 4.1.1 16 api 320 dpi
Durante las pruebas en la CCP  y chat de hoy no  ocurrió  este caso 713, ni una sola vez..

**Comment by GeronimoVierma** [comment]
Versión: 22.0-CBP
Hora: 8:25 am
Me encontraba en Chat estableciendo una conversación con otro actor y al darle click para salir de esa pantalla (imagen 1), me salio el mensaje de "Recovering from system error" (imagen 2): 

![screenshot_12](https://cloud.githubusercontent.com/assets/19883115/17698983/32f1ac98-638c-11e6-8502-eca7319f7b5b.png)
![recovering](https://cloud.githubusercontent.com/assets/19883115/17699011/4ecaad7a-638c-11e6-999c-57f8c038325a.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17699021/579da77c-638c-11e6-9d19-7f567a5c208a.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/420248/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 16-08-16
Caso 758 CBP 22.1
ocurre lo reportado (Recovering en la community agregando a un user)
![screenshot_5](https://cloud.githubusercontent.com/assets/17283358/17709375/db1a82bc-63b6-11e6-84ad-d972605f3731.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17709388/e9f36ce0-63b6-11e6-975a-e2ac8cd1a338.png)

**Comment by AdryCanonico** [comment]
Se cerrara el caso para apertura un caso por cada app. Ya que contamos con nueva Red y poder manejar mejor los casos por separado.
