### ISSUE TITLE
ERROR "Fermat No Responde"

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#714]
#### Nombre pantalla

CCP  y Settings de la Crypto Broker

### Nombre de la Aplicación 

CBP Versión 21.0

-----

##### Reporte de error: 

   *Desde muy temprano en la mañana me empezó a salir el error Fermat No Responde, me ocasiono problemas en el Emulador y hasta en la PC, Cerre y abrí el emulador, cerré y a abrí varias veces la aplicación, y hasta reinicie la pc y nunca mejoro, sin exagerar me salio como 10 veces, cuando pude buscar el logcat me sucedió algo extraño, solo me salia desde 9:47am en adelante, se me borro del logcat todo el proceso desde esta mañana a las 8am hasta ese momento. luego decidí abrir otro emulador, instale 21.0 CBP, Comencé a crear perfiles y al momento de entrar en la CCP para buscar me salio de nuevo el primer Fermat no responde. Luego al entrar de nuevo a la aplicación y querer configurar el Feed de la Crypto Broker también me salio el Fermat No Responde.

##### Screenshot o Capture de pantalla:

-  ![screenshot_94](https://cloud.githubusercontent.com/assets/19670319/17219356/168b4b18-54b9-11e6-8701-251176feb737.png)

-  ![screenshot_95](https://cloud.githubusercontent.com/assets/19670319/17219364/1f65dc76-54b9-11e6-8df7-9714201b1bfd.png)

##### Pasos exactos para reproducir el error:

- Entrar a la Apk y crear perfiles
- Entrar a la CCP y buscar usuarios
- Intentar Configurar los Settings de la Crypto Broker

##### Inserta Archivo aLogcat: 

 -  [logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/388770/logcat.txt)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 
![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17219532/b3d26672-54b9-11e6-9b28-67aa011542ec.png)

**Comment by yolandayancel** [comment]
Prueba 28-07-16
Caso 714 CBP 20.1 (Bitcoin Wallet)
Samsung S6 5.1.0 api 22 640dpi
logcat 
[logcat713.2.zip](https://github.com/Fermat-ORG/beta-testing-program/files/388963/logcat713.2.zip)
1 Ingreso a la Bitcoin Wallet
2 Fui a contactos
3 Ingreso a varios perfiles dentro de contactos
4 Sale un recuadro: error al mostrar contactos 
5 al ingresar a uno se congela la pantalla y sale fermat no responde.
![713 2](https://cloud.githubusercontent.com/assets/17283358/17222317/a358ada4-54c5-11e6-9ea1-b0775b9853b7.png)

**Comment by Hernandezsmanu** [comment]
Luego de instalar la versión 21.0 al momento de terminar de cargar el logo de fermat salio el aviso de que la aplicación no respondía e inmediatamente al presionar aceptar la cerro.

Teléfono físico:

![screenshot_2016-07-28-14-40-22](https://cloud.githubusercontent.com/assets/5313335/17227210/43009618-54db-11e6-9153-bd7a0331626d.png)

![screenshot_2016-07-28-13-46-10](https://cloud.githubusercontent.com/assets/5313335/17227211/44b017c2-54db-11e6-9fbf-4c2fbb6fdcd4.png)

**Comment by marielis-urbina** [comment]
En la version 21.0 de CBP, me sucede este error, al responder las negociaciones de los Customer, me saca de la aplicación.

![para variar](https://cloud.githubusercontent.com/assets/19353722/17248813/d236e186-556a-11e6-9684-ff5166ae2970.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17248814/d708cc1a-556a-11e6-88aa-b2a33a1e02fd.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/390543/logcat.txt)

**Comment by maydiamc** [comment]
en la version 21.1 de cbp da este error

Logcat 10:21am
[logcat 714.zip](https://github.com/Fermat-ORG/beta-testing-program/files/390720/logcat.714.zip)

emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/17251431/c7bed6c6-5576-11e6-97c5-64d9390e280e.png)

**Comment by Gabymorillo** [comment]
En la versión de CBP 21.1 de la CBP, desde el emulador no me sucede este error.


![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17253342/5a6f0dc2-557e-11e6-92e9-4957000ea840.png)

**Comment by franciscoj961** [comment]
Prueba 29-07-16
CBP 21.1
Google nexus 4.3 - API 18 - 768x1280
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/391095/logcat.txt)


Entro a configurar la Crypto Broker
Elijo las Wallets con normalidad 
Al Clickear para ir a la siguiente pantalla (o siguiente paso) me saca de la Aplicación. (Fermat no responde)

1.
![2907](https://cloud.githubusercontent.com/assets/20245988/17258796/9a457a90-5596-11e6-8290-d7f15965a4de.PNG)


2.
![fermat noresponde](https://cloud.githubusercontent.com/assets/20245988/17258805/a2061c94-5596-11e6-8055-3b6b7381b092.PNG)

**Comment by dorzar1989** [comment]
En la Version 21.1 de la CBP continua este error.

- Screenshots:

![screenshot_101](https://cloud.githubusercontent.com/assets/19670319/17294911/8b63b644-57c7-11e6-8dca-9a733c803f7c.png)

![screenshot_104](https://cloud.githubusercontent.com/assets/19670319/17294914/8f20bff2-57c7-11e6-9d2f-7bfa27b22667.png)

![screenshot_106](https://cloud.githubusercontent.com/assets/19670319/17294916/9207b400-57c7-11e6-99cf-f3db5297446e.png)


- LogCat:

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/393830/logcat.txt)

- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17294920/9e9b7ef4-57c7-11e6-9d2f-6b754510a0d9.png)

**Comment by marielis-urbina** [comment]
En la versión 21.1 de CBP, me sucede este error en mi emulador, cuando entro settings y voy al Stock Management, no me permite depositar en las billeteras, me aparece  el aviso de Fermat no responde, de igual forma responder las negociaciones.

![nr](https://cloud.githubusercontent.com/assets/19353722/17295364/cb716e6e-57c9-11e6-9b46-205121b90c6c.png)

![nr2](https://cloud.githubusercontent.com/assets/19353722/17295371/cea603c4-57c9-11e6-9e68-71c21e725bd1.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17295377/d196eeb8-57c9-11e6-94c1-2c80ffeef4d9.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/393861/logcat.txt)

**Comment by GeronimoVierma** [comment]
CBP-21.1
10.52 am (aproximadamente)
Me encontraba en la Broker Wallet (imagen 1) cuando me llego una notificación de conexión, al darle click a la notificación  me salio el aviso de "Fermat no responde" (imagen 2):

![screenshot_4](https://cloud.githubusercontent.com/assets/19883115/17298291/504b570a-57d7-11e6-8bc3-911b1f6d3640.png)


![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/17298296/5726528c-57d7-11e6-8e9f-dd2d1ca43c7a.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17298439/0ff11f04-57d8-11e6-8a50-336894a62fd4.png)



[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/394106/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 01-08-16
Caso 714 CBP 21.2 
Nexus 5 5.0.0 api21 480dpi
Persiste el error
![screenshot_9](https://cloud.githubusercontent.com/assets/17283358/17303619/74f930b4-57ef-11e6-8396-9010e37c1a4f.png)

**Comment by Gabymorillo** [comment]
Al tratar de entrar a la aplicación sale "Fermat no responde"

![capture-20160801-155434](https://cloud.githubusercontent.com/assets/17262077/17306959/a9abb1e0-5800-11e6-8db1-97b4ea8eeb73.png)

![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17306962/aab3912a-5800-11e6-9bab-eee20657b921.png)

**Comment by franciscoj961** [comment]
Prueba 02-08-16 
V21.2

Teléfono fisico
![screenshot_2016-08-02-08-18-47](https://cloud.githubusercontent.com/assets/20245988/17328166/29075b40-588a-11e6-834a-7d78de80bf3a.png)

Luego de seleccionar las Wallets del Crypto broker no me deja ir al siguiente paso (next step)

1.
![screenshot_2016-08-02-08-09-31](https://cloud.githubusercontent.com/assets/20245988/17328227/6c3268b0-588a-11e6-9b3a-cd914802209a.png)

2.
![screenshot_2016-08-02-08-10-18](https://cloud.githubusercontent.com/assets/20245988/17328234/7db5b998-588a-11e6-9a3f-f37c5a7c4d67.png)


El error persiste luego de varios intentos

NOTA: La primera vez me dejo seguir al siguiente paso, luego de escoger los proveedores y darle a Next Step me saco de la aplicación con la notificación de "Sistem error"

**Comment by Gabymorillo** [comment]
En la versión 21.2 de la CBP, al tratar de efectuar una negociación salio: Recovering From System Error , la pantalla se quedó en negro y luego le di a atrás y salió: Fermat No responde.

![capture-20160802-083040](https://cloud.githubusercontent.com/assets/17262077/17328583/7278ed46-588c-11e6-9683-820fac40d4ce.png)

![capture-20160729-104711](https://cloud.githubusercontent.com/assets/17262077/17328588/74865df8-588c-11e6-8c82-a23e51927c68.png)

**Comment by GeronimoVierma** [comment]
CBP-21.2
8:48 am (aproximadamente)
Me encontraba en la Customer Wallet (imagen 1) cuando le di click a uno de los contratos me salio el aviso de "Fermat no responde" (imagen 2):

![ggg](https://cloud.githubusercontent.com/assets/19883115/17328983/77bb40ae-588e-11e6-96f6-9cd24a286737.png)

![gg](https://cloud.githubusercontent.com/assets/19883115/17328989/7cf46b68-588e-11e6-8517-1962dc2a1777.png)

![chi](https://cloud.githubusercontent.com/assets/19883115/17328995/8bff6e5a-588e-11e6-8cff-5f26bc54350c.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/397013/logcat.txt)

**Comment by marielis-urbina** [comment]
Versión: 21.2 de CBP, este error se repite en mi emulador en todo momento.

![fermat](https://cloud.githubusercontent.com/assets/19353722/17330638/8fd96d26-5895-11e6-8f2f-2e5df8433122.png)

![ferma 1](https://cloud.githubusercontent.com/assets/19353722/17330642/9386574a-5895-11e6-9366-3e949f53554a.png)

![fermat 3](https://cloud.githubusercontent.com/assets/19353722/17330646/97eb78c4-5895-11e6-8f86-9b27d72e8f3c.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17330653/a136136c-5895-11e6-92f8-0f20bcfc5a59.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/397181/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 03-08-16
Caso 714 CBP 21.3
Samsumg S6  5.1.0 Api 22 640dpi
Ocurre lo reportado (pero en la Comunity de la Bitcoin Wallet)
![714](https://cloud.githubusercontent.com/assets/17283358/17367778/6561d180-595f-11e6-8553-76f02023ea31.png)

**Comment by GeronimoVierma** [comment]
CBP-21.3
Hora: 10:00 am (aproximadamente)
Estando en la Bitcoin Wallet y al darle click a la casilla de una transacción realizada (imagen 1), me salio el aviso de "Fermat no responde"  (imagen 2)

![tatata](https://cloud.githubusercontent.com/assets/19883115/17368839/c8467bc6-5963-11e6-9f3b-10a4467851ac.png)

![tata](https://cloud.githubusercontent.com/assets/19883115/17368842/cd31c294-5963-11e6-98f6-71cf66a7df9d.png)

![nexus 4 5 0](https://cloud.githubusercontent.com/assets/19883115/17368976/5ecfc0ac-5964-11e6-917a-7e70cfc2ba73.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/399628/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 04-08-16
Caso 714 CBP 21.4
Sony Xperia S 4.1.1 Api16 320dpi
Ocurre lo reportado. (Fermat no responde en la pantalla de Add Fermat User, se congela )
![714 1](https://cloud.githubusercontent.com/assets/17283358/17416040/68566d6e-5a5a-11e6-99de-617abd3066ab.png)

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 714 CBP 21.6 (Bitcoin Wallet)

Sony Xperia S api16 320dpi
![714](https://cloud.githubusercontent.com/assets/17283358/17441006/1d921e56-5afd-11e6-8471-429611a24a9e.png)

**Comment by GeronimoVierma** [comment]
Versión 21.6-CBP
Hora: 1:45 pm

Me encontraba en el Browser de la Crypto Wallet User Community (imagen 1), al darle sroll hacia abajo para ver mas usuarios me salio el mensaje "Fermat no responde" (imagen 2):

![screenshot_11](https://cloud.githubusercontent.com/assets/19883115/17445679/e9aea700-5b13-11e6-93ad-a7d03c3c2bde.png)

![screenshot_10](https://cloud.githubusercontent.com/assets/19883115/17445690/f66d598c-5b13-11e6-8dbc-c2f6a14a3361.png)

![s3 4 1](https://cloud.githubusercontent.com/assets/19883115/17445716/188150a0-5b14-11e6-92fa-02b99967e079.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/404321/logcat.txt)

**Comment by maydiamc** [comment]
en la version 21.6 de cbp, estaba revisando los contactos de chat y me salio fermat no responde, tambien me habia salido con anterioridad agregando los contactos en la pantalla add contact de la bitcoin wallet

logcat 2:08pm aprox
[log 714.zip](https://github.com/Fermat-ORG/beta-testing-program/files/404345/log.714.zip)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17446272/72cb6206-5b16-11e6-9273-00a80563a663.png)

**Comment by GeronimoVierma** [comment]
Versión 21.6-CBP
Hora: 8:40 am

Me encontraba en la Broker Wallet (imagen 1), al darle y al darle click para salir de esa pantalla me salio el mensaje "Fermat no responde" (imagen 2):


![screenshot_2](https://cloud.githubusercontent.com/assets/19883115/17480753/6af447c2-5d47-11e6-8874-2b5f6b3ee784.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17480757/7509c160-5d47-11e6-82d6-0699db1960c1.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/406807/logcat.txt)

**Comment by yolandayancel** [comment]
Prueba 08-08-16
Caso 714 CBP V21.6
Sony Xperia S 4.1.1  api 16 320dpi
Persiste el error(Cuando hago click sobre Fermat contact)
![screenshot_8](https://cloud.githubusercontent.com/assets/17283358/17481524/aa80a490-5d4b-11e6-9131-5647548e990a.png)

**Comment by GeronimoVierma** [comment]
Versión 21.7 CBP
Hora: 8:27 am (aproximadamente)
Me encontraba en la pantalla de P2P Chat (imagen 1), cuando al tratar de salir de esta pantalla me salio "Fermat No Responde" (imagen 2):

![ll](https://cloud.githubusercontent.com/assets/19883115/17516355/d130aa52-5e0b-11e6-804d-0d83cc04e455.png)

![screenshot_9](https://cloud.githubusercontent.com/assets/19883115/17516365/d93b2768-5e0b-11e6-8749-8e8230462f6b.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/19883115/17516381/ea1bea40-5e0b-11e6-9f72-f29ade334713.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/408889/logcat.txt)

**Comment by Gabymorillo** [comment]
En la versión 21.7 del Chat persiste el error.

![capture-20160809-161921](https://cloud.githubusercontent.com/assets/17262077/17532263/cb64c85a-5e4d-11e6-877f-8b907119f445.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17532236/a95027f0-5e4d-11e6-9867-eb15e233a061.png)

**Comment by GeronimoVierma** [comment]
Versión 21.8 CBP
Hora: 1:55 pm (aproximadamente)
Me encontraba en la pantalla "Wallets" (imagen 1), al darle click al icono de la Bitcoin Wallet me salio mensaje de "Fermat No Responde" (imagen 2):

![screenshot_12](https://cloud.githubusercontent.com/assets/19883115/17564882/00e7873c-5f03-11e6-9a31-29ff52b02ab5.png)

![screenshot_11](https://cloud.githubusercontent.com/assets/19883115/17564887/079a55aa-5f03-11e6-9539-1dccbcb5316d.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17564916/2c965fe8-5f03-11e6-8bd2-cf7d5364c539.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411781/logcat.txt)

**Comment by maydiamc** [comment]
en la version 21.8 de CBP me arrojo el aviso fermat no responde mientras estaba cambiando el feed de normal a slow en la bitcoin wallet y en el chat probando la lupita de buscar los contactos

Logcat
Bitcoin wallet 4:30pm
Chat 4:45pm
[log-714 21.8.zip](https://github.com/Fermat-ORG/beta-testing-program/files/412083/log-714.21.8.zip)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17570432/5f10c5a0-5f1a-11e6-9d7f-ac4695e8d61c.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 741 CBP 21.9 (BitcoinWallet)
Sony Xperia S 4.1.1 16 api 320 dpi

Me a pasado hoy varias veces dentro de la Bitcoin Wallet
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17593914/800a57d0-5fb5-11e6-86c1-4d68ca48b32c.png)

![fermat](https://cloud.githubusercontent.com/assets/17283358/17593987/ad1f3c2c-5fb5-11e6-9111-7d7c281c1025.png)




![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17593898/71f4374c-5fb5-11e6-96f8-daa51d5de71b.png)

**Comment by GeronimoVierma** [comment]
Versión 21.9  CBP
Hora 11:21
Me encontraba en la ficha de negociación (imagen 1) respondiendole a un customer y al tener listos los pasos le di click a "vender" y me salio "Fermat no Responde" (imagen 2):

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/413562/logcat.txt)

![fermat2](https://cloud.githubusercontent.com/assets/19883115/17594480/789af39a-5fb7-11e6-96bf-80f747ec62ea.png)
![fermat](https://cloud.githubusercontent.com/assets/19883115/17594502/8eb4fa18-5fb7-11e6-9aee-8a572d59bcd9.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17594522/9fca0550-5fb7-11e6-8a5b-7fda8d0fa32f.png)

**Comment by danielaporras** [comment]
Pasos:
1.Al entrar en la Bitcoin wallet 
2.Seleccionar un contacto para enviar o solicitar btc 
3.Presiono el boton de enviar
4.Entro a la pantalla de Send to contact
5.Desplego el menu de (configuracion avanzada)
6.En configuracion de fees quiero seleecionar Normal o Rapido
7. Aparece la pantalla, la aplicacion fermat no responde.

Hora aproximada: 8:45am / 9:00am


![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/17623105/6e3f5bb0-606c-11e6-8e76-dc6b969cf0ed.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/17623120/76da4dfc-606c-11e6-9836-bd4a13733244.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17623153/9ebb3be2-606c-11e6-88b0-4990259ccd73.png)

**Comment by yolandayancel** [comment]
Prueba 15-08-16
Caso 714 CBP 22.0
Ocurre Fermat no responde (En la community)

![screenshot_2016-08-15-13-36-02](https://cloud.githubusercontent.com/assets/17283358/17676206/71879daa-62fb-11e6-9580-29e63256acc4.png)

Telefono fisico
![1](https://cloud.githubusercontent.com/assets/17283358/17676213/7b5c59e2-62fb-11e6-8afe-72c0533f6626.png)

**Comment by AdryCanonico** [comment]
Se cerrara el caso para apertura un caso por cada app. Ya que contamos con nueva Red y poder manejar mejor los casos por separado.
