### ISSUE TITLE
CBP - BROKER WALLET -  Error en montos al hacer traspaso desde la Bitcoin Wallet al Stock Management.

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#718]
### Nombre de la Aplicación: CBP

-----

##### Reporte de error: 

   *Al trapasar Btc de la Bitcoin Wallet, a el Stock Management, el monto depositado es mayor.

##### Screenshot o Capture de pantalla:

![sm](https://cloud.githubusercontent.com/assets/19353722/17298181/eade63e4-57d6-11e6-8b91-a4a033ae42fa.png)

![bw](https://cloud.githubusercontent.com/assets/19353722/17298185/ee3f071e-57d6-11e6-867c-6491c3fd3394.png)

![bw3](https://cloud.githubusercontent.com/assets/19353722/17298258/27e13e92-57d7-11e6-9b42-0e066bbc1179.png)

![b3](https://cloud.githubusercontent.com/assets/19353722/17298190/f284e604-57d6-11e6-9db2-11581fae4830.png)

##### Pasos exactos para reproducir el error:

 *En el momento de hacer el traspaso de 1.50 Btc, de la Bitcoin Wallet al Stock management, el monto que se refleja resulta mayor (3 Btc) en la Broker Wallet. Al revisar mi Bitcoin Wallet, el monto esta correcto según traspaso.

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/17298385/c2c143da-57d7-11e6-9c6a-be21d76670b5.png)

**Comment by IsbetVR** [comment]
@nelsonalfo por favor revisa eso

**Comment by marielis-urbina** [comment]
En la versión 21.3 de CBP, verifique si este error me pasaba, efectivamente, al transferir los btc, al stock management, lo hizo, perfectamente. Pero cuando fui a transferir el monto de la Bank, lo hice por un monto superior al depositado en ella y el Stock management me lo permitió.

![stock](https://cloud.githubusercontent.com/assets/19353722/17367085/6da0fa86-595c-11e6-9e39-7a8530052e8d.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/17367089/7079ba40-595c-11e6-8d7b-75bd66db0995.png)

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/399544/logcat.txt)

**Comment by marielis-urbina** [comment]
En la versión 22.3 de CBP, este error no pasa ya en mi emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/17821225/7f286af4-661e-11e6-8844-964aa795bded.png)

**Comment by IsbetVR** [comment]
Closed #718
