### ISSUE TITLE
CHAT - CHATS - NUMERO DE NOTIFICACIÓN NO ESTA CENTRADO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#719]
### Nombre de la Aplicación CHAT

-----

##### Reporte de error: 

   *En la versión 21.1 de CBP al ingresar a la aplicación CHAT se puede observar que al llegar los mensajes de un usuario el número que sale al lado derecho dentro del circulo verde no esta centrado, en este caso con el usuario Manu Chat0108

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-01-09-34-43](https://cloud.githubusercontent.com/assets/5313326/17299265/a1f4c0a6-57db-11e6-91ef-81b2754d844c.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a CHAT
2. Que te envíen mensajes

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17299293/c10e1ffa-57db-11e6-819a-96d43ed87627.png)

**Comment by arosiopr** [comment]
@RoyGF @MaviDavsa

**Comment by josejcb** [comment]
Solucionado, en el prox apk lo tienen

**Comment by Gabymorillo** [comment]
En la versión 21.3 del Chat no sucede este error.

![capture-20160803-091317](https://cloud.githubusercontent.com/assets/17262077/17366830/3b975810-595b-11e6-8475-0ebdf5cb1315.png)

![capture-20160721-175754](https://cloud.githubusercontent.com/assets/17262077/17366837/4217ac1c-595b-11e6-8e41-9406e2ecd59b.png)

**Comment by IsbetVR** [comment]
Closed #719
