### ISSUE TITLE
Bitcoin Wallet- Problemas PAYTMENT REQUEST

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#72]
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios. 

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

**He enviado un Payment Request a MariDavsa la cual ella acepto, después de esperar una hora el Book Balance de mi cuenta no ha cambiado o sea que los bitcoins nunca ingresaron en mi cartera, sigo teniendo los mismos 100 Btc cuando debería tener 105.
   **
   
<img width="475" alt="captura de pantalla 2016-03-09 a las 13 36 36" src="https://cloud.githubusercontent.com/assets/15804433/13642864/f5c840e6-e5fc-11e5-8772-50f38b80136f.png">

<img width="424" alt="captura de pantalla 2016-03-09 a las 13 44 52" src="https://cloud.githubusercontent.com/assets/15804433/13642908/2a3f2f10-e5fd-11e5-8092-85a6a9f0df14.png">

------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="477" alt="captura de pantalla 2016-03-09 a las 12 45 06" src="https://cloud.githubusercontent.com/assets/15804433/13642922/3b778e58-e5fd-11e5-9404-a677fd04c003.png">

**Comment by augusto-ponce** [comment]
@furszy @acostarodrigo

**Comment by acostarodrigo** [comment]
@augusto-ponce no me incluyan a mi en estos issues hasta no estar seguros que es algo de la crypto network por favor

**Comment by augusto-ponce** [comment]
Ok Rodrigo !!

**Comment by nattyco** [comment]
@augusto-ponce  Probar y cerrar si los btc ya se confirman.
