### ISSUE TITLE
CBP - Elimina la foto de perfil del Customer

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#720]
### CBP v21.3

-----

##### Reporte de error: 

   *Cuando estoy creando el perfil como "Customer" y le coloco una imagen desde la galeria (Pantalla 1), confirmo los datos y salgo, entro a configurar la "Crypto Customer" y cuando reviso el drawer (Pantalla 2) me doy cuenta que la foto de perfil que he colocado no está, y al revisar el perfil (Pantalla 3) se puede observar que tampoco está la imagen.

#### Pantalla 1

![screenshot_10](https://cloud.githubusercontent.com/assets/19142276/17343932/283af9b2-58ce-11e6-9309-5e1180bae30c.jpg)

#### Pantalla 2

![screenshot_11](https://cloud.githubusercontent.com/assets/19142276/17343940/3309f320-58ce-11e6-942d-1a1440dec367.jpg)

#### Pantalla 3

![screenshot_12](https://cloud.githubusercontent.com/assets/19142276/17343952/3d20b9fc-58ce-11e6-9eb6-7b4a8c0fc40c.jpg)

##### Pasos exactos para reproducir el error:

1. Entro a Profiles y creo el perfil de customer, le coloco una imagen de galeria
2. Entro a configurar la Crypto Customer
3. Una vez termino de configurar la Crypto Customer y me dirijo al drawer para entrar a otras opciones, me doy cuenta que la foto de perfil no sale
4. Salgo de la Crypto Customer para chequear el perfil y al entrar a Profiles veo de igual manera que la imagen seleccionada no está como foto de perfil

##### Inserta Archivo aLogcat: 

Hora: 4:05pm

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/398066/logcat.zip)
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

- Google Nexus 4
- Versión de Android 4.3
- API 18 768x1280

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/17344299/91f4457e-58cf-11e6-9a98-8387f9bd94bf.jpg)

**Comment by IsbetVR** [comment]
@nelsonalfo por favor chequea esto

**Comment by LilianFlores** [comment]
Este error persiste en mi emulador. 

     - Google Nexus 4 API 19

![celular](https://cloud.githubusercontent.com/assets/19652611/17378261/3836b096-598b-11e6-9025-5eb111945c2d.png)

**Comment by dorzar1989** [comment]
en la version 21.3 de la CBP NO me sucede este error

- Screenshot:

![screenshot_154](https://cloud.githubusercontent.com/assets/19670319/17402546/d07f20fe-5a21-11e6-96aa-1f574454de2a.png)


![screenshot_153](https://cloud.githubusercontent.com/assets/19670319/17402534/bed3cf1c-5a21-11e6-89a3-6077bb335776.png)


- Emulador:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17402524/b4d3d462-5a21-11e6-8798-ba5e4155825e.png)

**Comment by LilianFlores** [comment]
En la versión 21.4, el error persiste. 

![newcelular](https://cloud.githubusercontent.com/assets/19652611/17417720/bdeda438-5a62-11e6-87a6-443e433a9143.png)

**Comment by andreagmarcano** [comment]
En la version 21.6 ya no ocurre este error.

![foto](https://cloud.githubusercontent.com/assets/18452495/17445038/06f19398-5b11-11e6-9439-52f944f4603b.PNG)

**Comment by IsbetVR** [comment]
Closed #720

**Comment by IsbetVR** [comment]
Este error persiste en la versión 21.7 CBP

![screenshot_1](https://cloud.githubusercontent.com/assets/19142276/17520323/4f581328-5e1d-11e6-8a0c-6ec3c25f6179.jpg)

#### Pasos exactos para reproducir el error:

1. Entro a Profiles y creo el perfil de customer, le coloco una imagen de galeria
2. Entro a configurar la Crypto Customer
3. Una vez termino de configurar la Crypto Customer y me dirijo al drawer para entrar a otras opciones, me doy cuenta que la foto de perfil está
4. Salgo de la Crypto Customer y entro a Profiles para cambiar la foto de perfil, coloco una nueva y guardo los cambios
5. Al regresar a la Crypto Customer, y revisar el drawer, no me sale la nueva foto de perfil 
6. Reviso en profiles y tampoco está la foto de perfil que había seleccionado

_________

#### Archivo Logcat

Hora: 10:36am

[log.zip](https://github.com/Fermat-ORG/beta-testing-program/files/409188/log.zip)

_________

#### Dispositivo de prueba

- [x] Emulador

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/17520335/600e1622-5e1d-11e6-9d81-667cfef7dff9.jpg)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by IsbetVR** [comment]
@nelsonalfo por favor chequea esto, en la versión 21.7 está otra vez el error

**Comment by yolandayancel** [comment]
Prueba 09-08-16
Caso 720 CBP V21.7
Sony Xperia S 4.1.1 16api 320dpi
logcat:
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/409176/logcat.txt)

ocurre lo reportado (Cambio la foto de perfil de customer  y guardo y al entrar de nuevo está sin la foto)
![screenshot_6](https://cloud.githubusercontent.com/assets/17283358/17520381/89b3dc14-5e1d-11e6-971c-dc34e4478448.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/17283358/17520386/8ed75d42-5e1d-11e6-9398-7a7d4e37ce15.png)

**Comment by andreagmarcano** [comment]
En la version 21.7 de CBP sigue ocurriendo este error. 
![recortes 10-08](https://cloud.githubusercontent.com/assets/18452495/17555410/7f3e1856-5edd-11e6-9367-94ddc8ac5bbc.PNG)
![recorte 10-08](https://cloud.githubusercontent.com/assets/18452495/17555418/8506d426-5edd-11e6-8e47-0780aa64afc8.PNG)

**Comment by camilavaleria** [comment]
Este error persiste en la version 21.9 de la CBP ;

![image](https://cloud.githubusercontent.com/assets/18740418/17622580/2fbf2238-6069-11e6-82cf-6de93d5d01b4.png)


EMULADOR DE PRUEBA:

![image](https://cloud.githubusercontent.com/assets/18740418/17622594/478c2ea6-6069-11e6-85f5-6be727732671.png)

**Comment by andreagmarcano** [comment]
En la version 22.3 de CBP no repite este error. 

![pantalla 1](https://cloud.githubusercontent.com/assets/18452495/17822073/f3dac2b2-6622-11e6-8dd0-507a973b45d5.PNG)
![pantalla 2](https://cloud.githubusercontent.com/assets/18452495/17822077/f86a6bca-6622-11e6-97e1-c9ba2351a1e5.PNG)
![captura1](https://cloud.githubusercontent.com/assets/18452495/17822081/fc7ff6bc-6622-11e6-8b22-c65c8e87d39b.PNG)

**Comment by IsbetVR** [comment]
Closed #720
