### ISSUE TITLE
Bitcoin Wallet-Identity Manager recorte de foto muy pequeño

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#721]
#### Nombre pantalla
Identity Manager

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *En la aplicacion Bitcoin Wallet, pantalla Identity Manager, al oprimir sobre el redondo donde se pone la foto aparece la pantalla de choose mode, y seleciono (Camera), tomo la foto, al aparecer el rectangulo de editar el tamaño de la foto este, esta mas pequeño de lo normal.

 *Agregar las capture del error en el emulador o teléfono donde se produjo. 

![screenshot_7](https://cloud.githubusercontent.com/assets/19656830/17366114/7c4ef326-5957-11e6-85d1-aafb183c3e50.png)

##### Pasos exactos para reproducir el error:

1.Entre a la Bitcoin Wallet para creer un perfil
2.Al presionar sobre el redondo de la foto y seleccionar imagen desde camara del emulador
3.El rectangulo para editar el tamaño de la foto es mas pequeño de lo normal

##### Inserta Archivo aLogcat: 
[Uploading Google Nexus 4 - 4.4.4 - API 19 - 768x1280-logcat.txt…]()

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_9](https://cloud.githubusercontent.com/assets/19656830/17367259/4f9e9fb0-595d-11e6-9094-ab99d37a5f7b.png)

  

@MaviDavsa 
@sanro14

**Comment by JeanFranco498** [comment]
En el Emulador Nexus 4 5.1 API 22 pasa exactamente lo mismo 



![foto](https://cloud.githubusercontent.com/assets/19807906/17367417/cde29728-595d-11e6-9ee8-8d28db9e7931.jpg)


![datos](https://cloud.githubusercontent.com/assets/19807906/17367478/0099ee82-595e-11e6-8d93-f6612cb9844d.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by JeanFranco498** [comment]
En el emulador Nexus 4 versión 5.10 Api 22 también ocurre lo mismo 


![foto](https://cloud.githubusercontent.com/assets/19807906/17367635/c9b26164-595e-11e6-9d92-7e15843cbd9f.jpg)

![datos](https://cloud.githubusercontent.com/assets/19807906/17367644/cd849f50-595e-11e6-9080-fdbfa25bfb19.jpg)

**Comment by yolandayancel** [comment]
PRUEBA 03-08-16
CASO 721 CBP 21.3
SAMSUNG S6 5.1.0 API22 640DPIOcurre lo reportado con la camara..
![screenshot_11](https://cloud.githubusercontent.com/assets/17283358/17376281/f5c53f82-5982-11e6-9e70-9098fcea3716.png)

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 721 CBP 21.6
Sony Xperia S 4.1.1 Api 16 320 dpi
ocurre lo reportado..
![screenshot_4](https://cloud.githubusercontent.com/assets/17283358/17442559/492faee6-5b04-11e6-9205-6fbb4bd2a6e3.png)

**Comment by danielaporras** [comment]
El error persiste en la version 21.6

![screenshot_6](https://cloud.githubusercontent.com/assets/19656830/17444429/e8b3a5c2-5b0d-11e6-825f-c8c88bb05590.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/17444436/f1130e1a-5b0d-11e6-966b-d04a736002ec.png)
@nattyco

**Comment by Gabymorillo** [comment]
En la versión 21.6 de la CBP no sucede este error.

![capture-20160805-144718](https://cloud.githubusercontent.com/assets/17262077/17447392/298066fe-5b1c-11e6-967c-2a2d4e356f74.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17447299/aa7f53c4-5b1b-11e6-8c68-6401c33dbc7d.png)

**Comment by IsbetVR** [comment]
Closed #721

**Comment by danielaporras** [comment]
En la version 21.7 este error sigue apareciendo
![screenshot_11](https://cloud.githubusercontent.com/assets/19656830/17518999/235ad2ce-5e18-11e6-8540-2d0c72292286.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/17519011/2e55d0fc-5e18-11e6-980f-d2551d1b3fea.png)

@IsbetVR

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by IsbetVR** [comment]
@nattyco por favor chequea este caso, está sucediendo cuando se trata de tomar la imagen directamente con la cámara del dispositivo

**Comment by wendyduran90** [comment]
En la version 21.7 CBP sucede este error. Esta prueba se realizo desde un teléfono móvil modelo Blu life one 2015 con versión de android 4.4.4.
Tamaño	720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop)



![screenshot_2016-08-09-10-14-52](https://cloud.githubusercontent.com/assets/20212920/17519792/6a00f9c6-5e1b-11e6-81d1-8e9700cc8397.jpg)

**Comment by marielis-urbina** [comment]
En la versión 21.8, persiste este error

![peqq](https://cloud.githubusercontent.com/assets/19353722/17564263/e071c0fa-5f00-11e6-93a7-a570e89c3f2e.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17564270/e41d9774-5f00-11e6-9d22-883625433b73.png)

**Comment by arosiopr** [comment]
Versión 21.8 de CBP persiste el error
Teléfono Físico

![screenshot_2016-08-10-13-53-08](https://cloud.githubusercontent.com/assets/5313326/17565012/95517f18-5f03-11e6-8d55-91b3bfe9e0ac.png)

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17565016/9b9bcc84-5f03-11e6-916b-36dc73e194aa.png)

**Comment by kmiloxvii** [comment]
Version 21.8 de cbp persiste el error
![error](https://cloud.githubusercontent.com/assets/2491042/17565803/df5bd380-5f06-11e6-8578-488647f759c0.png)

Emulador Android 4.1.1 
![phone](https://cloud.githubusercontent.com/assets/2491042/17565829/f04cf3ea-5f06-11e6-87ab-0f29d459c28a.png)

**Comment by danielaporras** [comment]
En la version 21.9 persiste el error.
![screenshot_6](https://cloud.githubusercontent.com/assets/19656830/17593116/d643050a-5fb2-11e6-9a36-b157a4dd2158.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17593127/dbd5f086-5fb2-11e6-8059-c52f7406d1aa.png)

**Comment by RubenSem** [comment]
En la versión 22.0 no sucede este error.

emulador :
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/17672458/77362462-62ea-11e6-805b-30aa7d26e455.jpg)

**Comment by Gabymorillo** [comment]
En la versión 22.0 de CCP en mi telefono fisico no sucede este error. 

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17672561/f8ed2e88-62ea-11e6-9ca6-1da1efc85038.png)

**Comment by JeanFranco498** [comment]
Versiop 22.1 sigue ocurriendo el error

![image](https://cloud.githubusercontent.com/assets/19807906/17735953/322d2a5e-6453-11e6-8c07-b98ecd2db61b.png)


![screenshot_20](https://cloud.githubusercontent.com/assets/19807906/17735982/4e24c8b6-6453-11e6-9131-177540233ae7.jpg)

**Comment by arosiopr** [comment]
@MaviDavsa  por favor reabrir el caso el error se presenta de nuevo en la version 22.1 de CBP

![screenshot_2016-08-17-08-18-18](https://cloud.githubusercontent.com/assets/5313326/17735964/3a967ce0-6453-11e6-8a36-6f0949eeb2bf.png)

## **Teléfono Físico**

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17735992/5a65f32a-6453-11e6-9fd2-6ceed8c03031.png)

**Comment by wendyduran90** [comment]
En la versión 22.1 de CBP persiste el error. Esta prueba se realizo desde un teléfono móvil con versión de android 4.4.4 marca Blu modelo life one 2015 Tamaño	720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop)

![screenshot_2016-08-17-09-15-05](https://cloud.githubusercontent.com/assets/20212920/17739706/f87783b6-6463-11e6-909b-bf9a2af57a18.jpg)

**Comment by nattyco** [comment]
@danielaporras verificar en la version 22.7 de la apk

**Comment by GeronimoVierma** [comment]
En la versión 27.7 ya no ocurre el error reportado en mi teléfono físico:

![screenshot_2016-08-26-09-06-17](https://cloud.githubusercontent.com/assets/19883115/18006387/45faf86a-6b6d-11e6-8e4d-479dcc6d04df.png)

![screenshot_2016-07-14-18-31-45](https://cloud.githubusercontent.com/assets/19883115/18006425/67c319f0-6b6d-11e6-9d48-b0df15ba7b69.png)

**Comment by danielaporras** [comment]
En la version 22.7 de CBP fue solucionado este error, por favor cerrarlo.

![screenshot_22](https://cloud.githubusercontent.com/assets/19656830/18006488/bab93f2c-6b6d-11e6-9b66-b53734fecd01.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/18006494/c286ee70-6b6d-11e6-8294-9ec90b348273.png)

@IsbetVR
