### ISSUE TITLE
BITCOIN WALLET- DEBITO ERRADO POR LA BROKER WALLET EN EL SENT

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#722]
## CBP 

-----

##### Reporte de error: 

   * Revisando mi saldo en la Bitcoin Wallet, me doy cuenta que tengo debitado un monto errado en el Sent, de la Broker Wallet *

##### Screenshot o Capture de pantalla:
 
![nego](https://cloud.githubusercontent.com/assets/19353722/17368258/37239356-5961-11e6-9542-8bc9fdf0b967.png)

![nneg](https://cloud.githubusercontent.com/assets/19353722/17368303/5a9d41f6-5961-11e6-9f9b-4cb93428ec03.png)

##### Pasos exactos para reproducir el error:

Al entrar a revisar el saldo de mi Bitcoin Wallet, para mandar unos Btc, me percato que tengo debitado un monto errado, de la Broker Wallet de una negociación que nunca re realizo. Ya que por fallas de la red no me llegaron nunca negociaciones.

##### Inserta Archivo aLogcat: 

------
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/399607/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![samsung](https://cloud.githubusercontent.com/assets/19353722/17368308/603d108c-5961-11e6-9314-28cad5e5da1f.png)

**Comment by MaviDavsa** [comment]
Error del Usuario!
