### ISSUE TITLE
CBP_ Se desaparecieron las negociaciones y se colgó la aplicacion

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#725]
#### Nombre pantalla
Home

### Nombre de la Aplicación 
CBP-Crypto Broker

-----

##### Reporte de error: 

   *Se desaparecieron las negociaciones y se colgó la aplicación dando fermat no responde.

##### Pasos exactos para reproducir el error:

-Estaba en el menú Home
-Minimice la aplicación
-Fui a setting del dispositivo para configurar la hora
-al maximizar la aplicación se habían desaparecido las negociaciones
-Abrí el menú y entre a contract history para verificar si se habían expirado las negociaciones
-Allí tampoco salia ningún contrato
-Al abrir el menú de nuevo este salio gris y no se veía ningún botón, ni se podía hacer nada
-Seguidamente dio Fermat no responde

##### Inserta Archivo aLogcat: 

4:20pm aproximadamente

[genymotion-log prueba.zip](https://github.com/Fermat-ORG/beta-testing-program/files/402720/genymotion-log.prueba.zip)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:
 
![nexus 4 4 2](https://cloud.githubusercontent.com/assets/17274154/17418485/caf1c9d0-5a66-11e6-99d7-819a57f7a360.png)

**Comment by maydiamc** [comment]
Version 21.5 de CBP

**Comment by wendyduran90** [comment]
En la versión 21.4 CBP al momento de pasar la negociación a contrato , aparece de inmediato una notificación de que este va a expirar  y se borra automáticamente  el contrato de la lista . Esta prueba se realizo desde un movil android modelo : Blu life one 2015 
Tamaño	720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop)

![screenshot_2016-08-04-16-36-40](https://cloud.githubusercontent.com/assets/20212920/17419335/ebcb23fa-5a6a-11e6-94c3-31a4154e4f22.jpg)

**Comment by kmiloxvii** [comment]
Me sucedio lo mismo como broker, aparecio la notificación que el contrato iba a expirar y se desaparecio


![pasted image at 2016_08_04 04_42 pm](https://cloud.githubusercontent.com/assets/2491042/17419537/eee191ae-5a6b-11e6-84e9-cf0e04663768.png)


![phone](https://cloud.githubusercontent.com/assets/2491042/17419630/499470a8-5a6c-11e6-9729-98d9658fecc4.png)

**Comment by IsbetVR** [comment]
@yalayn

**Comment by dorzar1989** [comment]
En la version 21.7 de la CBP esto no me ocurre 

- Screenshot: 

![screenshot_228](https://cloud.githubusercontent.com/assets/19670319/17554862/fc1b4504-5eda-11e6-9cd4-18f17e205673.png)

![screenshot_229](https://cloud.githubusercontent.com/assets/19670319/17554868/0465cf22-5edb-11e6-94d1-7b3499b5c88a.png)


- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17554879/0c87564e-5edb-11e6-9420-f8e8b562b29a.png)

**Comment by IsbetVR** [comment]
Closed #725
