### ISSUE TITLE
CBP - No Aparece el Boton de la Banking

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#726]
#### Nombre pantalla

Banking Wallet

### Nombre de la Aplicación 

CBP Version 21.4

-----

##### Reporte de error: 

   *Al momento de ingresar los datos de la cuenta Banking, para crearla, normalmente existe un boton para guardar la cuenta que se crea. en esta Version no aparece.

##### Screenshot o Capture de pantalla:

![screenshot_156](https://cloud.githubusercontent.com/assets/19670319/17418794/51d1b040-5a68-11e6-96e8-64743420d3f6.png)

##### Pasos exactos para reproducir el error:

- Entrar a la Banking Wallet
- Colocar Nombre del Banco
- Darle Simbolo Mas de la esquina superior derecha
- Colocar datos de la Cuenta nueva

##### Inserta Archivo aLogcat: 

 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/402754/logcat.txt)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/17418832/802e610e-5a68-11e6-8b6b-9b6c9d1fa2a5.png)

**Comment by wendyduran90** [comment]
En la versión 21.4 CBP al momento de crear la cuenta en la banking , permite ingresar todos los datos necesarios pero no hay un botón para guardar o crear dicha cuenta. Esta prueba se realizo desde un móvil android modelo Blu life one 2015 
Tamaño	720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
 Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop)
![screenshot_2016-08-04-10-25-40](https://cloud.githubusercontent.com/assets/20212920/17419719/b9db1416-5a6c-11e6-8440-23f90d9cf30b.jpg)

**Comment by IsbetVR** [comment]
@abicelis

**Comment by danielaporras** [comment]
El error persiste
![screenshot_4](https://cloud.githubusercontent.com/assets/19656830/17436993/04f801da-5ae9-11e6-9014-17edb35fed7b.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/17437024/38024e96-5ae9-11e6-9e66-cd809ffd3e7e.png)

**Comment by JeanFranco498** [comment]
CBP v 21.4 en Samsung S3 Android 4.3 tambien ocurre este erro

![screenshot_2016-08-05-08-46-35 1](https://cloud.githubusercontent.com/assets/19807906/17437198/54af6546-5aea-11e6-8913-e702ce4b4373.png)

![screenshot_2016-08-05-08-46-29 1](https://cloud.githubusercontent.com/assets/19807906/17437214/73009bb4-5aea-11e6-8c1b-f37ed46aed8f.png)

![screenshot_2016-08-01-23-59-25 2](https://cloud.githubusercontent.com/assets/19807906/17437233/8a58b1e8-5aea-11e6-812b-0b07187b78fa.png)

**Comment by RAYMALDONADO** [comment]
CBP-V21.4 apk  presenta el mismo error en el emulador google nexus 4-4.1.1

![banking](https://cloud.githubusercontent.com/assets/20222795/17439042/fdbb6b5e-5af3-11e6-9cca-517eafb3c704.jpg)

![telefono_4 1](https://cloud.githubusercontent.com/assets/20222795/17439115/63a613ce-5af4-11e6-8da0-aa3b303379eb.jpg)

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 726 CBP V21.6
Sony Xperia S 16api 320dpi
ocurre lo reportado
![726](https://cloud.githubusercontent.com/assets/17283358/17442076/08494f2e-5b02-11e6-8e05-d31eb1c6b4f6.png)

**Comment by Gabymorillo** [comment]
En la versión 21.6 ocurre lo reportado.

![capture-20160808-093939](https://cloud.githubusercontent.com/assets/17262077/17481712/822e28cc-5d4c-11e6-8e26-b6bfdcab2ac4.png)
![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17481715/8379526a-5d4c-11e6-95d0-555b047446b2.png)

**Comment by yolandayancel** [comment]
Prueba 09-08-16
Caso 726 CBP V21.7
Sony Xperia S 4.1.1 16api 320dpi
Ya aparece el boton para agregar las cuentas
![screenshot_3](https://cloud.githubusercontent.com/assets/17283358/17519101/80d16d64-5e18-11e6-8439-9bffa884b3e7.png)
