### ISSUE TITLE
CBP - APARECEN 3 PUNTOS EN LAS COMUNITIES COMO SI HUBIERAN MAS PANTALLAS

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#727]
#### Nombre pantalla

Comunities

### Nombre de la Aplicación 
CBP V. 21.4

-----

##### Reporte de error: 

   En la parte inferior de la comunity salen 3 puntos como si hubieran otras pantallas para recorrer en la comunidad. En los captures se puede apreciar con mejor facilidad 

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-08-05-09-43-26 1](https://cloud.githubusercontent.com/assets/19807906/17438765/8503d53a-5af2-11e6-8d85-05bf1fc5222a.png)

![screenshot_2016-08-05-09-51-53 1](https://cloud.githubusercontent.com/assets/19807906/17438803/a84a0014-5af2-11e6-85e6-34fb46e5ef12.png)

##### Pasos exactos para reproducir el error:

1. Abrir CBP
2. Entrar en la comunities
3. Visualizar los 3 puntos 
4. Salir y entrar nuevamente
5. Siguen los 3 puntos 

##### Inserta Archivo aLogcat: 

Teléfono Físico 
 No tengo logcat
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-01-23-59-25 1](https://cloud.githubusercontent.com/assets/19807906/17438838/e3229548-5af2-11e6-9537-1b429dffb61e.png)

**Comment by RAYMALDONADO** [comment]
se ve también en emulador Google Nexus 4-4.1.1
![punticos](https://cloud.githubusercontent.com/assets/20222795/17439301/624a37c0-5af5-11e6-8fae-5b707e7deee1.jpg)

**Comment by MaviDavsa** [comment]
@furszy

**Comment by Gabymorillo** [comment]
En la versión 21.6 desde el emulador no me sucede este error. 

![capture-20160805-143641](https://cloud.githubusercontent.com/assets/17262077/17447086/8b472d16-5b1a-11e6-91a0-81be0e99f9d2.png)

![capture-20160805-143709](https://cloud.githubusercontent.com/assets/17262077/17447087/8d2359d4-5b1a-11e6-8cc5-be9a35643605.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17447150/e47ca500-5b1a-11e6-8dfc-fb482059abe2.png)

**Comment by dorzar1989** [comment]
En la Version 21.7 de la CBP ya no sucede este error

- Screenshot:

![screenshot_211](https://cloud.githubusercontent.com/assets/19670319/17528016/9cce60f8-5e3b-11e6-81b7-aca87a72f6c2.png)

![screenshot_212](https://cloud.githubusercontent.com/assets/19670319/17528017/9cd3f8f6-5e3b-11e6-8dcc-0bddb65fa2b5.png)


- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17528025/a6a3ab24-5e3b-11e6-9665-fa06896e6e6d.png)

**Comment by IsbetVR** [comment]
Closed #727
