### ISSUE TITLE
BITCOIN WALLET - SE DUPLICAN LOS CONTACTOS DENTRO DE LA CARTERA

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#728]
#### Nombre pantalla

BITCOIN WALLET CONTACTOS

### Nombre de la Aplicación 

CBP V 21.6

-----

##### Reporte de error: 

   Los contactos al agregar mas de 2 en la bitcoin wallet se duplican, a demas de que el contacto duplicado queda en la letra "#" como si empezase por algún numero o carácter especial.

##### Screenshot o Capture de pantalla:

![se duplican los contactos](https://cloud.githubusercontent.com/assets/19807906/17441433/095ee9d0-5aff-11e6-93d3-f56c9945fbe4.jpg)

##### Pasos exactos para reproducir el error:

1. Agregar mas de un contacto en la wallet
2. Ir a la ventana contactos de la bitcoin wallet
3. Observar como se duplican
4. Visualizar donde se duplican

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/404055/logcat.txt)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![datos 4 1](https://cloud.githubusercontent.com/assets/19807906/17441600/d9599a18-5aff-11e6-848e-93412ab23982.jpg)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 728 CBP V 21.6
Sony Xperia S 16api 320dpi
ocurre lo reportado..
![screenshot_2](https://cloud.githubusercontent.com/assets/17283358/17441672/2dc2633c-5b00-11e6-865d-6efb4a817cf1.png)

**Comment by JeanFranco498** [comment]
También sucede en teléfono físico 

![screenshot_2016-08-05-11-17-40 1](https://cloud.githubusercontent.com/assets/19807906/17441784/af27773c-5b00-11e6-9c5b-884adce87af9.png)

![screenshot_2016-08-01-23-59-25 1](https://cloud.githubusercontent.com/assets/19807906/17441833/df7cb262-5b00-11e6-935b-aa44448f0aac.png)

**Comment by nattyco** [comment]
@JeanFranco498  verificar este reporte en la nueva apk

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 728 CBP 21.9
Sony Xperia S 4.1.1 16 api 320 dpi
Ya no ocurre esto( No duplica los contactos)
![screenshot_24](https://cloud.githubusercontent.com/assets/17283358/17595308/7f0afbc8-5fba-11e6-9dde-e56eb2e31133.png)

**Comment by nattyco** [comment]
@JeanFranco498  verificar este reporte en la ultima version de la apk, el error se daba con contactos cuyo nombre tiene nros

**Comment by Gabymorillo** [comment]
Desde el teléfono físico, en la versión 21.9 de la CBP no ocurre lo reportado. 

![screenshot_2016-08-12-08-23-48_720](https://cloud.githubusercontent.com/assets/17262077/17622530/ebd66e14-6068-11e6-8a10-a871781f5d76.png)
![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17622531/ec8b2912-6068-11e6-9878-9b520b806ec6.png)

**Comment by IsbetVR** [comment]
Closed #728
