### ISSUE TITLE
Bitcoin Wallet - Opciones de "Fermat Contact" y "External Contact" Quedan Fijas

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#729]
#### Nombre pantalla

Contacts - Bitcoin Wallet

### Nombre de la Aplicación 

Bitcoin Wallet - CBP Version 21.6

-----

##### Reporte de error: 

   * Las Opciones de "Fermat Contact" y "External Contact" quedan fijas en varias pantallas de la Apk luego de que uno le da click a "Fermat Contacts" para buscar los contactos.

##### Screenshot o Capture de pantalla:

![screenshot_178](https://cloud.githubusercontent.com/assets/19670319/17442647/a90991e2-5b04-11e6-94d5-1b2efcecdd93.png)

## **DIFERENTES HORAS** 

![screenshot_179](https://cloud.githubusercontent.com/assets/19670319/17442648/ab799ed6-5b04-11e6-9b4b-967453666f2e.png)

![screenshot_180](https://cloud.githubusercontent.com/assets/19670319/17442657/b264321a-5b04-11e6-86ca-e4f0682c74c6.png)

![screenshot_181](https://cloud.githubusercontent.com/assets/19670319/17442658/b28eb1d4-5b04-11e6-8cd9-20aa98ff0484.png)

##### Pasos exactos para reproducir el error:

- Entrar a la Bitcoin Wallet
- Ir a la opcion de Contactos
- Dar Click al Simbolo mas para desplegar opciones "Fermat Contact" y "External Contact"
- Dar Click a "Fermat Contact"
- Pasar a la Pagina de "Fermat Contact" pero con las opciones fijas en todas las pantallas de la Bitcoin Wallet...

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/404130/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17442640/9b235e0a-5b04-11e6-968b-62bce2fd0817.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by JeanFranco498** [comment]
Ocurre también en teléfono físico con teléfono físico Android 4.3 


![screenshot_2016-08-05-11-43-59](https://cloud.githubusercontent.com/assets/19807906/17442893/eb747618-5b05-11e6-9d78-0571adde21d2.png)


![screenshot_2016-08-05-11-46-10](https://cloud.githubusercontent.com/assets/19807906/17442896/f3a463d4-5b05-11e6-841c-a3c4094d5955.png)


![screenshot_2016-08-01-23-59-25](https://cloud.githubusercontent.com/assets/19807906/17442908/0010daa8-5b06-11e6-8d43-58ca42eac556.png)

**Comment by yolandayancel** [comment]
Prueba 05-08-16
Caso 729
Sony Xperia S 4.1.1 16 api 320dpi
Ocurre lo reportado
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/17444550/8ce27d44-5b0e-11e6-902a-699e5acd5e30.png)

**Comment by danielaporras** [comment]
Me ocurre lo mismo version 21.6
![screenshot_7](https://cloud.githubusercontent.com/assets/19656830/17444678/50d042f4-5b0f-11e6-83a7-03e60001dfd2.png)


![screenshot_5](https://cloud.githubusercontent.com/assets/19656830/17444691/5fd0e614-5b0f-11e6-8f8b-2ded543631e0.png)

**Comment by RubenSem** [comment]
No me ocurre el error en la versión 21.6:
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/17481807/df0b9a48-5d4c-11e6-8dd5-56ed7b327410.jpg)
![screenshot_5](https://cloud.githubusercontent.com/assets/19676223/17482010/cafef152-5d4d-11e6-94a0-68b4423a2a1d.jpg)

Emulador:
![screenshot_2](https://cloud.githubusercontent.com/assets/19676223/17482082/2cae4ace-5d4e-11e6-90c7-75f82f280a21.jpg)

**Comment by marielis-urbina** [comment]
En la versión 21.7 de CBP, no sucede esto en mi emulador

![conte](https://cloud.githubusercontent.com/assets/19353722/17522003/7451a670-5e23-11e6-8457-e8a1bf9183f9.png)

![contacte](https://cloud.githubusercontent.com/assets/19353722/17522007/78e63f66-5e23-11e6-95dc-6bb4f716a013.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17522020/820b59dc-5e23-11e6-9852-7eaf1af0c463.png)

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en la versión 21.7 de CBP se puede cerrar

**Comment by IsbetVR** [comment]
Closed #729
