### ISSUE TITLE
Bitcoin Wallet_experiencia del usuario_contactos

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#73]
### Bitcoin Wallet 

------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *se hace necesario incluir en esta pantalla un boton para eliminar a los usuarios, debido a que hay algunos que estan en desuso y quiero eliminarlos de mi lista de contacto para no tener duplicados de los mismos usuarios y no se puede realizar esta operacion ya que no hay forma de hacerlo. 
![screenshot_2016-03-10-11-12-54](https://cloud.githubusercontent.com/assets/17274154/13674842/42a84a82-e6b1-11e5-92fa-d310d162d730.png)

   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: MiniS4
* Version de Android: 4.4.2 kit kat

**Comment by MaviDavsa** [comment]
@nattyco Esta mejora aun no se ha implementado!

**Comment by maydiamc** [comment]
se recomienda emplear esta mejora

**Comment by maydiamc** [comment]
esta mejora no se ha implementado en la version 19.4 de CBP

**Comment by nattyco** [comment]
@MaviDavsa  @IsbetVR  en la version 3.1 de la apk se implemento una opcion para eliminar contactos en la pantalla de detalle del contacto, equina superior derecha.

**Comment by dorzar1989** [comment]
En la vesion 3.1 de la CCP ya se soluciono este error

- Pasos:

 1 Borrar Al Contacto
 2 Verificar que no aparezca

El contacto se borra en la Bitcoin Wallet, pero persiste en mis Connections en la Community. La Bitcoin Wallet me deja la opción de volver a agregar el contacto si es que fue borrado por error, o para contactarlo en un futuro. Lo deja en Add Fermat User.

- Screenshot:

 1 BORRAR CONTACTO:

![screenshot_125](https://cloud.githubusercontent.com/assets/19670319/18289909/652b614e-744f-11e6-9c89-bb5a2951aaf7.png)
![screenshot_126](https://cloud.githubusercontent.com/assets/19670319/18289910/65308782-744f-11e6-8b4c-e7f30891b437.png)
![screenshot_127](https://cloud.githubusercontent.com/assets/19670319/18289911/65519f9e-744f-11e6-9333-07e73a13b5ea.png)

 2 SE PUEDE VOLVER A AGREGAR:

![screenshot_131](https://cloud.githubusercontent.com/assets/19670319/18289939/835c746e-744f-11e6-84c7-207719b8fd81.png)


- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/18289949/8eaede1a-744f-11e6-8ca4-06d1d6cb41ab.png)

**Comment by yolandayancel** [comment]
Prueba 06-09-16
Caso 73 CCP V3.1
Celular ZTE
Detalle de pasos:
1 Ingreso en el perfil de Isbet
2 parte de contac detail arriba y a la derecha tres punticos click y aparece delete
3 le doy oke y se borra el contacto
4 Pero queda el mismo para ser agregado porteriormente..
1
![screenshot_2016-09-06-16-06-47](https://cloud.githubusercontent.com/assets/17283358/18290015/c2bfc4c6-744f-11e6-8f0b-60fe548d20d3.png)
2
![screenshot_2016-09-06-16-06-54](https://cloud.githubusercontent.com/assets/17283358/18290035/dddccbf0-744f-11e6-96a3-cae0a4bf6aab.png)
3
![screenshot_2016-09-06-16-06-59](https://cloud.githubusercontent.com/assets/17283358/18290058/00daf960-7450-11e6-9727-cf060874035f.png)

4
![screenshot_2016-09-06-16-08-56](https://cloud.githubusercontent.com/assets/17283358/18290089/18c99400-7450-11e6-9582-093f02b0339d.png)


![screenshot_2016-09-06-15-20-35](https://cloud.githubusercontent.com/assets/17283358/18289967/99e3a680-744f-11e6-8fa9-30b960a88b39.png)

**Comment by IsbetVR** [comment]
Solucionado
