### ISSUE TITLE
Community - Chat - Duplica contactos si se realiza una solicitud de conexión simultanea por ambos contactos

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#730]
#### Nombre pantalla

Community de Chat / Contactos de Chat

### Nombre de la Aplicación 

Chat - CBP Verion 21.7

-----

##### Reporte de error: 

   *Al momento de entrar a la Community y solicitarle conexion al usuario "AndreaCHAT0808T", recibo de su parte una solicitud de conexion (Casi al mismo tiempo), a lo que yo paso a la pestaña de Notification y aparece su solicitud, y le doy aceptar. Reviso de una vez la pestaña de Conections y me aparece el usuario mecionado anteriormente Duplicado. Revise los contactos en la App Chat y tambien sale Duplicado el usuario.

##### Screenshot o Capture de pantalla:

![screenshot_189](https://cloud.githubusercontent.com/assets/19670319/17494674/cd287404-5d83-11e6-88ec-e6ed24fdf6d4.png)

![screenshot_190](https://cloud.githubusercontent.com/assets/19670319/17494677/cf6ee716-5d83-11e6-8d88-e4a16b9432ad.png)

##### Pasos exactos para reproducir el error:

- Entrar a las Communities de Chat
- Buscar usuarios
- Enviar solicitud (AndreaCHAT0808T)
- Pasar a pestaña de Notifications
- Aceptar su solicitud (que llego al mismo tiempo que le envie la mia a ella)
- Revisar Conections y verificar los dos usuarios de "AndreaCHAT0808T"

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/407653/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17494668/c57cc1ec-5d83-11e6-9841-569a3858053f.png)

**Comment by MaviDavsa** [comment]
@royGF

**Comment by josejcb** [comment]
Revisen este caso hoy y manana, deberia estar solucionado en el CBP 21.8 @MaviDavsa.

**Comment by Gabymorillo** [comment]
En la versión 22.0 del Chat, desde el telefono fisico no sucede este error.

![screenshot_2016-08-16-09-18-36_720](https://cloud.githubusercontent.com/assets/17262077/17700192/b8d28066-6392-11e6-81d0-7adc2adf1ef4.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17700204/c1e57834-6392-11e6-9af8-86039c2f5f82.png)

**Comment by josejcb** [comment]
@MaviDavsa @dorzar1989 @Gabymorillo esto se solucionó hace días.

**Comment by AdryCanonico** [comment]
@josejcb  Chat ha dado bastantes errores no ha sido posible verificarlo.

**Comment by AdryCanonico** [comment]
ya no sucede el error
