### ISSUE TITLE
CHAT - Se bugea la imagen de perfil de la ultima ventana de conversación en la barra de chat

### ISSUE THREAD

**Issue by franciscoj961** [Fermat-ORG/beta-testing-program#731]
Template issue error report
#### Nombre pantalla

HOME CHAT 

#### VERSION: 
21.7

-----

#### ERROR:

La imagen de perfil de la ultima conversación se queda bugeada en la barra de chat.

#### (No pasa en el ultimo chat en que se recibió un mensaje, solo en el ultimo chat en que se envio) 

![bug08](https://cloud.githubusercontent.com/assets/20245988/17494869/9f2ad9f6-5d84-11e6-87e9-1138b271d455.PNG)

 -----

![phone08](https://cloud.githubusercontent.com/assets/20245988/17494893/afd42cd0-5d84-11e6-95d0-6e04bd9d85f6.PNG)

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/407707/logcat.zip)

**Comment by Gabymorillo** [comment]
En la versión 21.7 del Chat sucede lo reportado.

![capture-20160808-160653](https://cloud.githubusercontent.com/assets/17262077/17495892/dedc6c0a-5d88-11e6-8acf-420a80d1be8e.png)
![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17495894/e056aa46-5d88-11e6-8dde-e9fbce687072.png)

**Comment by MaviDavsa** [comment]
@royGF

**Comment by danielaporras** [comment]
En la version 21.7 persiste este error.
![screenshot_7](https://cloud.githubusercontent.com/assets/19656830/17516423/3946360c-5e0c-11e6-9779-a3a53566503e.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/17516428/3fc19328-5e0c-11e6-987d-000b2d5c4e44.png)

**Comment by dorzar1989** [comment]
En la Version 21.8 de la CBP no me sucede este error

- Screenshot:

![screenshot_251](https://cloud.githubusercontent.com/assets/19670319/17569068/9f50d782-5f14-11e6-99e0-9a39d6329327.png)

![screenshot_252](https://cloud.githubusercontent.com/assets/19670319/17569069/9f91b0ae-5f14-11e6-80a5-f37084d42bde.png)

- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17569065/972b9d1c-5f14-11e6-81cb-c6f43d588f58.png)

**Comment by arosiopr** [comment]
se soluciono este error en mi celular en la versión 21.8 de CBP @sanro14
