### ISSUE TITLE
Bitcoin Wallet - Banner de Bienvenida del Perfil Estirado

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#737]
#### Nombre pantalla

Perfil de Bitcoin Wallet

### Nombre de la Aplicación 

Bitcoin Wallet - CBP 21.7

-----

##### Reporte de error: 

   *El Banner de Bienvenida al perfil de Bitcoin Wallet sale estirado.

##### Screenshot o Capture de pantalla:

![screenshot_235](https://cloud.githubusercontent.com/assets/19670319/17561451/01a36876-5ef4-11e6-96e5-f0badedc6295.png)

##### Pasos exactos para reproducir el error:

- Entrar a Perfil
- Banner de Bienvenida

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411577/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17560655/df91d522-5ef0-11e6-9615-67639830f167.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by marielis-urbina** [comment]
En la versión 21.8 de CBP, persiste este error

![baner](https://cloud.githubusercontent.com/assets/19353722/17564031/f8a4f0c6-5eff-11e6-9774-86166b660d1b.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17564037/fdf90684-5eff-11e6-9b32-3112e7ce5481.png)

**Comment by IsbetVR** [comment]
En el HTC One X Android 4.1.1 este detalle gráfico se presenta también

![screenshot_4](https://cloud.githubusercontent.com/assets/19142276/17564573/ce89fb7c-5f01-11e6-9eb0-924f37b97cd3.jpg)

#### Dispositivo de prueba

- [x] Emulador

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/17564548/b3d084b8-5f01-11e6-803a-112ea272bde8.jpg)

**Comment by Gabymorillo** [comment]
Desde el teléfono físico, en la versión 21.8 de la CBP, presenta el error mencionado. 

![screenshot_2016-08-10-13-38-56](https://cloud.githubusercontent.com/assets/17262077/17565985/995fcfca-5f07-11e6-99f3-f5345e82a0a2.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17565990/9c303834-5f07-11e6-9811-adb5655176f9.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 737 CBP V21.8
Sony Xperia S  4.1.1 16api 320dpi
Ocurre lo reportado.. (Banner estirado en el Identity Manager

![banner](https://cloud.githubusercontent.com/assets/17283358/17591075/6b11b11c-5faa-11e6-8e9a-09448b6b7799.png)

![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17591049/54180b46-5faa-11e6-8fa8-a99e81886776.png)

**Comment by dorzar1989** [comment]
En la Version 21.9 de la CBP persiste este error

- Screenshot:

![screenshot_264](https://cloud.githubusercontent.com/assets/19670319/17592249/81493a9a-5faf-11e6-8d1c-9e8399b122a4.png)


- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17592253/8677f024-5faf-11e6-9b10-2c3225a2bc9a.png)

**Comment by AdryCanonico** [comment]
@nattyco En la Versión 21.9 de la CBP en mi teléfono físico sale estirado el banner. 


![screenshot_2016-08-11-11-15-37](https://cloud.githubusercontent.com/assets/18584168/17594093/0919c02e-5fb6-11e6-9440-8a0877bc5f6a.png)

http://www.smart-gsm.com/moviles/samsung-galaxy-avant


![samsung avant](https://cloud.githubusercontent.com/assets/18584168/17594110/1d08d174-5fb6-11e6-8dcf-ae1067adf450.png)

**Comment by GeronimoVierma** [comment]
En la versión 22.0-CBP no persiste el error:

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/17672770/fc2d3506-62eb-11e6-918c-788e0ca97dae.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17672780/0e95fd72-62ec-11e6-826f-876a2187ebe1.png)

**Comment by arosiopr** [comment]
En mi Telefono Fisico ya no se ve estirado @MaviDavsa 

![screenshot_2016-08-15-13-36-08](https://cloud.githubusercontent.com/assets/5313326/17673162/ed0349ce-62ed-11e6-8661-0de4eb4ee691.png)

**Comment by IsbetVR** [comment]
Closed #737
