### ISSUE TITLE
Community - Chat - Nombre de Usuarios No sale Centrado

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#738]
#### Nombre pantalla

Browser de la Community de Chat

### Nombre de la Aplicación 

Chat - CBP Version 21.7

-----

##### Reporte de error: 

Al momento de entrar a la Community de Chat para buscar contactos, detalle el nombre de un par de contactos muy a la izquierda.

## **- FECHA: 09/08/2016**

![screenshot_192](https://cloud.githubusercontent.com/assets/19670319/17561668/24fafe46-5ef5-11e6-85a7-19dbff615886.png)

## **- FECHA: 10/08/2016**

![screenshot_233](https://cloud.githubusercontent.com/assets/19670319/17561683/30a43384-5ef5-11e6-9ce8-0fc7f0c85f29.png)

##### Pasos exactos para reproducir el error:

- Entrar a la Community de Chat
- En el Browser buscar Contactos

##### Inserta Archivo aLogcat: 
 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411595/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17561687/376fa5ae-5ef5-11e6-90cb-276603ecefc4.png)

**Comment by IsbetVR** [comment]
@RoyGF

**Comment by dorzar1989** [comment]
En la Version 21.8 de la CBP aun persiste este error:

- Screenshot:

![screenshot_257](https://cloud.githubusercontent.com/assets/19670319/17570376/24a840b4-5f1a-11e6-8c79-2bbe65f0c71f.png)

- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17570366/1aa52a1e-5f1a-11e6-8dd0-437375c7a7bc.png)

**Comment by josejcb** [comment]
Solucionado, revisar en la próxima versión.

**Comment by josejcb** [comment]
@dorzar1989 @IsbetVR esto se soluciono hace días.

**Comment by camilavaleria** [comment]
En la version 22.3 este error no sucede en mi emulador, esta solucionado.

Emulador de prueba

![image](https://cloud.githubusercontent.com/assets/18740418/17820535/4686c3b0-661b-11e6-8bcf-dca9888af8cf.png)
