### ISSUE TITLE
BITCOIN WALLET-CONTACTS: AL HACER CLICK SOBRE BOTÓN MENÚ NO FUNCIONA

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#739]
#### Nombre pantalla

Contacts

### Nombre de la Aplicación 

CBP21.8

##### Reporte de error: 
Estando en el home y hago click sobre en menu para  entrar a contactos, luego que ingresé,  al hacer click sobre el botón del menu, arriba y a la izquierda, este no funciona, tengo que usar el botón de retroceso del emulador para poder salir de la pantalla.

##### Screenshot o Capture de pantalla:
![screenshot_19](https://cloud.githubusercontent.com/assets/17283358/17565070/def7c15e-5f03-11e6-8d69-b4f69b70a9d7.png)
 

##### Pasos exactos para reproducir el error:
1 Ingreso a la Wallet
2 Estando en el Home, solicito los BTC
3Hago click sobre el menu
4 Clickeo sobre contacts
5 Ingreso a la pantalla de contacts
6Hago click sobre el menu de arriba y a la izquierda para salir de la pantalla, pero el botón so funciona
7 Hago click sobre botón de retroceso del emulador para poder salir de la pantalla.

 *Detallar paso a paso la forma en  la cual se logro el error.

##### Inserta Archivo aLogcat: 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411791/logcat.txt)

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17565239/9ce83e1e-5f04-11e6-83d5-a8a23f22b12b.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by arosiopr** [comment]
En mi Telefono Fisico se presenta el mismo error

![screenshot_2016-08-10-13-58-57](https://cloud.githubusercontent.com/assets/5313326/17565430/723df068-5f05-11e6-9037-393c8dfcd1b7.png)

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17565435/78365442-5f05-11e6-9f43-6044a97a97d6.png)

LOGCAT

Hora aproximada 1:58pm

[Log_2016-08-10_14-20-23.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411814/Log_2016-08-10_14-20-23.txt)

**Comment by marielis-urbina** [comment]
En la versión 21.8 de CBP, en la Bitcoin Wallet, después de ver a los cantactos, al hacer click sobre el botón del menú no funciona, tengo que usar el botón de retroceso del emulador para salir.

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17565610/279c0594-5f06-11e6-96ed-59ce8f8e4f8d.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 739 CBP21.9
Sony Xperia S 4.1.1 16api 320Dpi

El botón ya funciona,,
![caso 2](https://cloud.githubusercontent.com/assets/17283358/17592312/d587b078-5faf-11e6-88bb-e6410b6fe443.png)
![caso 1](https://cloud.githubusercontent.com/assets/17283358/17592319/ddf1e4e0-5faf-11e6-8633-bad755c453e6.png)

![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17592327/e6aa563a-5faf-11e6-87c4-71ebad6851ef.png)

**Comment by arosiopr** [comment]
@IsbetVR  error solucionado en mi dispositivo personal

**Comment by IsbetVR** [comment]
Closed #739

**Comment by Gabymorillo** [comment]
En la versión 22.2 de la CCP, desde el telefono fisico, se presenta este error, el botón de menú no funciona lo que obliga  a utilizar el botón de "atrás" de mi telefono. 

![screenshot_2016-08-18-11-21-26_720](https://cloud.githubusercontent.com/assets/17262077/17779972/a922b37e-6537-11e6-9a5f-0b2d6cc7ff8d.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17779980/b0306c10-6537-11e6-87dd-83fab6649106.png)

**Comment by Hernandezsmanu** [comment]
En la version 22.2 desde el emulador el boton del Menu de Contacts no funciona, siguiendo los siguientes pasos:

1. Entrar al Home
2. Ir a contacts
3. Seleccionar icono (+) y agregar contacto Fermat
4. Seleccionar icono para ir a CCP
5. Salir de CCP 
6. Volver a la Bitcon Wallet
7. Seleccionar icono de volver atras (<--)
8. No sirve el boton de Menu

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/17780521/94037eae-6539-11e6-833f-b420a723f795.png)


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/425320/logcat.txt)

**Comment by arosiopr** [comment]
@AdryCanonico  por favor reabrir

**Comment by JeanFranco498** [comment]
CBP V 22.6 en  telefono fisico no esta sucediento este error 

En esta captura se evidencia como se despliega el menu en la pestaña contactos 

![screenshot_2016-08-24-09-03-33 1](https://cloud.githubusercontent.com/assets/19807906/17931602/5239b74a-69da-11e6-9a86-9db92e8e58d7.png)


![screenshot_2016-08-24-09-07-32 1](https://cloud.githubusercontent.com/assets/19807906/17931594/42cd7bac-69da-11e6-9640-802ccb66d97e.png)

**Comment by nelsondb** [comment]
En la versión 22.6 desde emulador no sucede lo reportado.

**Comment by maydiamc** [comment]
En la versión CCP 3.4.2 este error se presenta de nuevo, reabrir el caso.

Pasos
1-Ingresar a community a traves de la bitcoin wallet
2- Salir de la community
3- Entrar a Bitcoin Wallet y queda en pantalla add fermat
4- Dar atrás a la pantalla de contacto
5- Intentar ir al menú desde el botón del drawer

Capture
![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/18878689/8dca44d4-849f-11e6-9309-ee2b92e71e0b.png)

Emulador
![nexus 5-6 0](https://cloud.githubusercontent.com/assets/17274154/18878710/9bd0646e-849f-11e6-927b-3493e5df5b1e.png)
![nexus 5-6 0 dpi](https://cloud.githubusercontent.com/assets/17274154/18878712/9ee20a9a-849f-11e6-9fe1-ead9ba915b3a.png)

**Comment by danielaporras** [comment]
En la versión 3.4.2 CCP, se repite el siguiente error.
1. Entro a la bitcoin wallet.
2. Voy a la comunnity.
3. Salgo de la community.
4. Entro de nuevo a la bitcoin wallet.
5. Quedo en la pantalla de Add Fermar user.
6. Le doy atrás y quedo en la pantalla de Contacts
7. Presiono sobre el drawer de la apk y no, se desplega.
![screenshot_2016-09-27-10-19-02](https://cloud.githubusercontent.com/assets/19656830/18878848/262eeb8a-84a0-11e6-959c-5f30c827d7b1.png)

Huawei Ascend Y221
api 19
Dimensiones    116.5 x 60.6 x 12.3 mm
Tamaño    320 x 480 pixels, 3.5 pulgadas
http://www.gsmarena.com/huawei_ascend_y221-6908.php

**Comment by nattyco** [comment]
@sanro14  @danielaporras  corregido en la version 3.4.3

**Comment by danielaporras** [comment]
En la version 3.5 fue solucionado lo comentado en este issue.
![screenshot_2016-09-27-15-14-31](https://cloud.githubusercontent.com/assets/19656830/18889176/b9bb1bac-84c9-11e6-8bf3-2a3bf2e44912.png)
 
Cerrarlo por favor . @sanro14

**Comment by sanro14** [comment]
Solucionado
