### ISSUE TITLE
Bitcoin Wallet_Error_ Agrupacion de Transacciones recibidas

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#74]
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *en la pantalla de transacciones recibidas, no se aprecian todas las transacciones de un mismo contacto de forma clara y organizada, en cambio se agrupan las transacciones de distintos usuarios en una identificada como "uninformed", esto solo sucede si las transacciones son directamente enviadas, ya que al ser a traves de un "payment request" si se refleja de forma correcta identificando el nombre de usuario que me la envio.

nota: el usuario que me ha enviado btc a traves de los distintos medios y que aparece como "augus 10" y en ocaciones como "uninformed" SI esta agregado a mi lista de contactos

![screenshot_2016-03-10-11-42-11](https://cloud.githubusercontent.com/assets/17274154/13676051/6d036320-e6b6-11e5-9c07-ff6febdd177a.png)

![screenshot_2016-03-10-12-02-38](https://cloud.githubusercontent.com/assets/17274154/13676485/3c37c5d6-e6b8-11e5-8b79-d686e5b0e7cd.png)

![screenshot_2016-03-10-11-12-54](https://cloud.githubusercontent.com/assets/17274154/13676305/76cfc9ce-e6b7-11e5-8f29-5eef3e0661e2.png)
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: s4 mini
* Version de Android: 4.4.2 kit kat

**Comment by nattyco** [comment]
@augusto-ponce verificar nuevamente este caso con la nueva version

**Comment by nattyco** [comment]
@maydiamc  verificar este caso en la nueva version.

**Comment by maydiamc** [comment]
se soluciono el problema en la ultima actualizacion @nattyco

**Comment by augusto-ponce** [comment]
Cerrado el caso entonces

**Comment by maydiamc** [comment]
@nattyco en la nueva actualizacion volvio a aparecer el problema 

![screenshot_2016-04-12-12-05-55](https://cloud.githubusercontent.com/assets/17274154/14481145/fbbfe996-00f9-11e6-8214-65784dcf4e57.png)
