### ISSUE TITLE
Bitcoin Wallet- Tamaño de los iconos y diseño no son los adecuados para agregar los contactos

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#741]
#### Nombre pantalla

Contacts

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

El tamaño de los iconos y diseño no son los adecuados, podemos observar como el titulo de "contacto fermat" está por encima de "pulsa aquí para buscar contactos". 

##### Screenshot o Capture de pantalla:

![capture-20160810-140124](https://cloud.githubusercontent.com/assets/17262077/17565217/818a7e2a-5f04-11e6-9923-3e23477563e7.png)

##### Pasos exactos para reproducir el error:

1.  Entrar a la Bitcoin Wallet
2. Ir a Contactos
3. Pulsar botón +

##### Inserta Archivo aLogcat: 

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  
------
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411832/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17565286/d85cfd5e-5f04-11e6-8b58-0ece060e7bd2.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Prueba 10-08-16
Caso 724 CBP V21.8
Sony Xperia S 16api 320dpi
Ocurre lo 
![screenshot_18](https://cloud.githubusercontent.com/assets/17283358/17566982/7a1e73ba-5f0b-11e6-8a97-ca258c9d7436.png)
 reportado..

**Comment by maydiamc** [comment]
en la 21.8 de Cbp los botones se veen descuadrados y el color negro en las letras de contacto externo y contacto fermat no se ve bien, el diseño no va acorde con el resto de la aplicacion

![screenshot_10](https://cloud.githubusercontent.com/assets/17274154/17567012/a1992246-5f0b-11e6-841c-9ce0dda24c47.png)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17567015/a5def42a-5f0b-11e6-8016-d55a6fe21c39.png)

**Comment by Gabymorillo** [comment]
En la prueba de la versión 21.9 de la CBP desde el emulador y teléfono físico persiste el error.

Emulador
![capture-20160811-105055](https://cloud.githubusercontent.com/assets/17262077/17592920/305ce070-5fb2-11e6-87c4-a0e5831aa0bd.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17592929/32bb359c-5fb2-11e6-91fa-1e51c51797b1.png)

Teléfono físico

![screenshot_2016-08-11-10-52-40_720](https://cloud.githubusercontent.com/assets/17262077/17592950/47a14686-5fb2-11e6-96b6-c73ff3f4fd77.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17592951/49171310-5fb2-11e6-85e9-8fdd8ef377f1.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 741 CBP 21.9
Sony Xperia S 4.1.1 16 api 320 dpi

Se modificó el diseño..
![screenshot_21](https://cloud.githubusercontent.com/assets/17283358/17593363/a07a0c7e-5fb3-11e6-8c77-3dbf4787cfbd.png)

**Comment by maydiamc** [comment]
corregido en la version 21.9 de CBP

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17595405/fa38d130-5fba-11e6-80a4-e014217c25a3.png)

**Comment by Gabymorillo** [comment]
Desde el telefono fisico, en la versión 22.0 de la CCP sigue sucediendo este error. 

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17673348/a5e70d68-62ee-11e6-8979-697f4154b5a1.png)

**Comment by marielis-urbina** [comment]
En la versión 22 de CBP este error persiste

![cot](https://cloud.githubusercontent.com/assets/19353722/17676304/f24dbcf8-62fb-11e6-8df9-a7e1ae39dee7.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17676308/f6edc8e8-62fb-11e6-9dfd-cfd4d9616d53.png)

**Comment by MaviDavsa** [comment]
@nattyco Ya aquí el error es que visualmente el "Contact Fermat" Se ve muy arriba muy alejado del "Contacto Externo" y el "+"... Entonces si se puede unir para que todo quede más armónico, seria perfecto... Ese es el único error que vemos hasta los momentos con este caso en especifico!

**Comment by nattyco** [comment]
@MaviDavsa  voy  verificar si eso que indican se puede resolver

**Comment by nattyco** [comment]
@MaviDavsa  la libreria que se usa para armar el boton flotante no tiene opcion para configurar esa separacion no puedo cambiar ese aspecto del menu

**Comment by MaviDavsa** [comment]
@nattyco Bueno natty! Ni modo! Se cierra entonces! :)
