### ISSUE TITLE
Bitcoin Wallet_ Boton de imagen para contacto externo no funciona

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#743]
#### Nombre pantalla
External Contact

### Nombre de la Aplicación 
Bitcoin Wallet 21.8

-----

##### Reporte de error: 

   *el icono para colocarle imagen al contacto externo no funciona y en versiones anteriores si se podía colocar imagen allí

##### Screenshot o Capture de pantalla:

 ![screenshot_11](https://cloud.githubusercontent.com/assets/17274154/17567281/b169dbb0-5f0c-11e6-8100-9f82c024cee2.png)

##### Pasos exactos para reproducir el error:

-Ingresar a la pantalla de contactos
-Darle click a botón contacto externo
-Darle click al icono de la cámara en la esquina superior izquierda
-se sale de la pantalla automáticamente

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 ![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17567349/f12a9a14-5f0c-11e6-8c08-41aa82a62af6.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Prueba 10-08-16
Caso 743 CBP V21.8
Sony Xperia S 16api 320dpi
Ocurre  lo reportado..
![screenshot_3](https://cloud.githubusercontent.com/assets/17283358/17567449/633b5ba2-5f0d-11e6-9d77-e5db7883dfdf.png)

**Comment by andreagmarcano** [comment]
El icono de la camara no tiene ninguna funcion en esta version 21.8 de CBP 
![captura](https://cloud.githubusercontent.com/assets/18452495/17567534/c10052c4-5f0d-11e6-9af1-6ee321cf927b.PNG)
![captura1](https://cloud.githubusercontent.com/assets/18452495/17567535/c4531556-5f0d-11e6-858a-c03bbb7be745.PNG)

**Comment by maydiamc** [comment]
en la version 21.9 de CBP sigue este problema

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17592941/40b790dc-5fb2-11e6-87ca-247812d536f2.png)

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 741 CBP 21.9
Sony Xperia S 4.1.1 16 api 320 dpi

Persiste lo reportado: No funciona
![screenshot_22](https://cloud.githubusercontent.com/assets/17283358/17593491/0a11ebe8-5fb4-11e6-9082-23115a96ea71.png)

**Comment by AdryCanonico** [comment]
En la version 21.9 de CBP persiste el error

http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![samsung avant](https://cloud.githubusercontent.com/assets/18584168/17595264/49c2cb3a-5fba-11e6-8f32-d18a9cf4fadb.png)

**Comment by nattyco** [comment]
@AdryCanonico @maydiamc corregido en la proxima version de la apk

**Comment by GeronimoVierma** [comment]
En la versión 22.0 CBP el icono de imagen del perfil externo si funciona:

![screenshot_7](https://cloud.githubusercontent.com/assets/19883115/17673374/cc69cb56-62ee-11e6-92e2-e5b4a298f337.png)

![screenshot_8](https://cloud.githubusercontent.com/assets/19883115/17673383/d8f23fb6-62ee-11e6-8363-c781dc7e89e2.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17673395/df755832-62ee-11e6-8641-769ae15cb0c2.png)

**Comment by Gabymorillo** [comment]
Desde el telefono fisico, en la versión 22.0 de la CCP no se presenta el error reportado. 

![screenshot_2016-08-15-14-05-18_720](https://cloud.githubusercontent.com/assets/17262077/17674037/c6811458-62f1-11e6-92a8-073bdd84f2e0.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17673986/82b986c4-62f1-11e6-89b8-7185c32f17f6.png)

**Comment by IsbetVR** [comment]
Closed #743
