### ISSUE TITLE
Community - CCP - Tabs de Lupa e Imagen de Lupa

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#744]
#### Nombre pantalla

CCP Community

### Nombre de la Aplicación 

CCP - CBP Version 21.8 

-----

##### Reporte de error: 

Los diseños de la imagen y los tabs de la lupa de búsqueda son diferentes en las pestañas de la CCP, pienso que debería arreglarse para que se vea mejor.

##### Screenshot o Capture de pantalla:

![screenshot_243](https://cloud.githubusercontent.com/assets/19670319/17567413/3afe54e6-5f0d-11e6-9fb6-7da565e4a40c.png)

![screenshot_244](https://cloud.githubusercontent.com/assets/19670319/17567409/3ae868de-5f0d-11e6-9576-05092712068a.png)

![screenshot_245](https://cloud.githubusercontent.com/assets/19670319/17567411/3af43e20-5f0d-11e6-9a2a-bc8148a22db1.png)

![screenshot_246](https://cloud.githubusercontent.com/assets/19670319/17567412/3af88e58-5f0d-11e6-901e-d119584e34b4.png)

![screenshot_247](https://cloud.githubusercontent.com/assets/19670319/17567414/3b480f5a-5f0d-11e6-908e-089077e7310e.png)

##### Pasos exactos para reproducir el error:

No es error

##### Inserta Archivo aLogcat: 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17567448/62c3d51e-5f0d-11e6-880f-71731449b752.png)

**Comment by maydiamc** [comment]
en la version 21.8 de CBP sucede este error

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17567574/f082d922-5f0d-11e6-992c-8263f2ec0916.png)

**Comment by Gabymorillo** [comment]
En la prueba de la versión 21.8 desde el telefono fisico, ocurre lo reportado.

![screenshot_2016-08-10-15-26-33_720](https://cloud.githubusercontent.com/assets/17262077/17568013/c00673ec-5f0f-11e6-9a47-23fe7a63878f.png)
![screenshot_2016-08-10-15-26-48_720](https://cloud.githubusercontent.com/assets/17262077/17568015/c19ae0ee-5f0f-11e6-8c1b-90796781eae5.png)
![screenshot_2016-08-10-15-26-55_720](https://cloud.githubusercontent.com/assets/17262077/17568019/c3ee883c-5f0f-11e6-913e-abe11238d1a1.png)

![screenshot_2016-08-10-15-27-27](https://cloud.githubusercontent.com/assets/17262077/17567917/55d26594-5f0f-11e6-8563-215576802b55.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17567909/47216824-5f0f-11e6-9210-3663d4f50b3f.png)

**Comment by maydiamc** [comment]
el problema sigue ocurriendo en la version 21.9 de CBP

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17595496/4378d246-5fbb-11e6-8169-9dc4181ed8f6.png)

**Comment by nattyco** [comment]
@sanro14  @dorzar1989  en la pestaña de Connectios y Notifications no hay opcion de search asi que se quito el incono, verificar en la proxima apk disponible.

**Comment by andreagmarcano** [comment]
Persiste el error en la version 22.0 de CBP 
![15](https://cloud.githubusercontent.com/assets/18452495/17672435/542d164c-62ea-11e6-8c52-565283d6de87.PNG)
![captura1](https://cloud.githubusercontent.com/assets/18452495/17672441/593dd9dc-62ea-11e6-8f1f-5ad3e4a111dc.PNG)

**Comment by Gabymorillo** [comment]
En la versión 22.0 de la CCP, desde el telefono fisico, en efecto la lupa solo está en el brower, pero al seleccionarla se muestra dos veces la lupa. 

![screenshot_2016-08-15-13-27-13_720](https://cloud.githubusercontent.com/assets/17262077/17672963/e8deefd4-62ec-11e6-9397-b850f45f2a24.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17672888/9a9f5188-62ec-11e6-9532-e6ec0650033d.png)

**Comment by nattyco** [comment]
@dorzar1989 @MaviDavsa  iconos corregidos en la version 22.1 de la apk

**Comment by maydiamc** [comment]
en la version 22.1 al seleccionar la lupa se ve dos veces, se recomienda colocar solo la palabra search

![screenshot_27](https://cloud.githubusercontent.com/assets/17274154/17708528/73295cd0-63b3-11e6-96f7-7ca88ad7fa28.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17708508/547f8e12-63b3-11e6-88f5-fc5d13092407.png)

**Comment by dorzar1989** [comment]
En la Version 22.1 de la CBP ya no me sucede este error

- Screenshots: 

![screenshot_13](https://cloud.githubusercontent.com/assets/19670319/17708904/04f311f0-63b5-11e6-8f2f-716405c28eec.png)

![screenshot_14](https://cloud.githubusercontent.com/assets/19670319/17708905/04f8564c-63b5-11e6-9ab7-6e10831ed59c.png)

![screenshot_15](https://cloud.githubusercontent.com/assets/19670319/17708908/0540f974-63b5-11e6-8053-ec0bcd11ea6e.png)

- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17708925/13d35a7c-63b5-11e6-8d47-ad91bbb43a7c.png)

**Comment by arosiopr** [comment]
en la versión 22.1 de CBP se soluciono el error, solo que los iconos de lupa siguen siendo diferentes
@AdryCanonico 

![screenshot_2016-08-16-13-38-49](https://cloud.githubusercontent.com/assets/5313326/17709748/738e2bd8-63b8-11e6-885e-8533fec98bc1.png)


![screenshot_2016-08-16-13-38-36](https://cloud.githubusercontent.com/assets/5313326/17709760/78df7812-63b8-11e6-9eec-429213cd25e4.png)
