### ISSUE TITLE
PROFILES - P2P CHAT PROFILE - BOTON GUARDAR NO ESTA CENTRADO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#745]
#### Nombre pantalla

P2P CHAT PROFILE

### Nombre de la Aplicación 

CBP 21.8

-----

##### Reporte de error: 

   *Al ingresar a crear un perfil de CHAT se puede observar que el botón verde de guardar no esta centrado, sale como corrido, le sale hacia el lado izquierdo una parte blanca

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-10-14-36-19](https://cloud.githubusercontent.com/assets/5313326/17567520/b3bf1ba4-5f0d-11e6-8c98-6ed606967688.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a Profiles
2. Entrar a la Opción Chat 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17567544/d05cef48-5f0d-11e6-9403-6db55a92ffc5.png)

**Comment by arosiopr** [comment]
@sanro14

**Comment by Gabymorillo** [comment]
En la versión 21.8 del Chat, desde el emulador, ocurre lo reportado.

![capture-20160810-154650](https://cloud.githubusercontent.com/assets/17262077/17568556/51e7fa22-5f12-11e6-928f-4efa92483134.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17568558/54b0d120-5f12-11e6-9722-1cb7f15d9dff.png)

**Comment by josejcb** [comment]
Listo, en el próximo apk lo tienen.

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en versión 21.9 de CBP se puede cerrar

**Comment by IsbetVR** [comment]
Closed #745

**Comment by dorzar1989** [comment]
En al Version 21.9 de la CBP Persiste este error.. Solicito reabrirlo

- Screenshot:

![screenshot_267](https://cloud.githubusercontent.com/assets/19670319/17598834/547e3784-5fca-11e6-8708-fb4970f29a0c.png)


- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17598841/5956e7ec-5fca-11e6-8893-71d3d92a9ee6.png)

**Comment by dorzar1989** [comment]
En la Version 22.0 de la CBP persiste este error

![screenshot_6](https://cloud.githubusercontent.com/assets/19670319/17698705/9384e888-638a-11e6-8128-6024359ca542.png)


emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17698716/9d983014-638a-11e6-9ee9-04b9b0989fd3.png)

**Comment by josejcb** [comment]
Solved.

**Comment by Gabymorillo** [comment]
En la versión 22.3 del Chat, desde el emulador no sucede el error reportado.

![screenshot_1](https://cloud.githubusercontent.com/assets/17262077/17856508/e937fcfa-684b-11e6-9596-223e82521805.png)

![capture-20160804-144810](https://cloud.githubusercontent.com/assets/17262077/17856511/eb9dc754-684b-11e6-8d1f-36c8d00a7117.png)

**Comment by wendyduran90** [comment]
En la versión 22.3 no sucede este error . La prueba se realizo desde un teléfono móvil con versión de android 4.4.4 marca BLU modelo life one 2015 .

![screenshot_2016-08-22-08-52-48](https://cloud.githubusercontent.com/assets/20212920/17856613/5df1f8d4-684c-11e6-9200-5ec1b27c4a52.jpg)

**Comment by IsbetVR** [comment]
Closed #745

**Comment by JeanFranco498** [comment]
Este error esta pasando en la version de cbp 22.4 en mi telefono Samsung S3 

Espesor	8,6 milímetros
Dimensiones (anchura x altura)	70,6 x 136,6 milímetros
Tamaño (pulgadas)	4.8"
Resolución de la Pantalla	720 x 1280 píxeles

![Uploading Screenshot_2016-08-23-08-14-44.png…]()


![screenshot_2016-08-01-23-59-25 1](https://cloud.githubusercontent.com/assets/19807906/17892177/eedd06a6-690d-11e6-8270-d8a918bbdd16.png)

**Comment by wendyduran90** [comment]
En la versión 1.3 de chat no sucede este error . Esta prueba se realizo desde un teléfono móvil con versión de android 5.0.2

![screenshot_2016-09-07-09-12-16](https://cloud.githubusercontent.com/assets/20212920/18313423/bbda3046-74dc-11e6-90f3-d8bd6fcedaa1.jpg)

**Comment by JeanFranco498** [comment]
Version de Chat 1.3 En mi movil sigue pasando este error... La prueba de este caso se realizo con un movil con android 4.3 

![screenshot_2016-09-07-09-21-37 1](https://cloud.githubusercontent.com/assets/19807906/18313451/d562b916-74dc-11e6-9262-ae3b93e50efe.png)


![screenshot_2016-09-07-09-25-23 1](https://cloud.githubusercontent.com/assets/19807906/18313499/0a8a6fda-74dd-11e6-99dc-e2a9225caebe.png)

**Comment by MaviDavsa** [comment]
![dfgdfgfg](https://cloud.githubusercontent.com/assets/17273005/18325699/7009bb30-7510-11e6-9f47-a947f7406fa1.JPG)

Probado con un tlf Android de 4.3, API 18... Samsung S3 Y el error se ve solventado!
