### ISSUE TITLE
Community-CCP-Búsqueda con la Geolocalización arroja Fermat No Responde

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#746]
#### Nombre pantalla
Geolocalizacion

### Nombre de la Aplicación 
CCP Version 21.8

-----

##### Reporte de error: 

   *al ingresar al icono de geolcalizacion se arroja un aviso de que la actividad de fermat no responde

##### Screenshot o Capture de pantalla:

Prueba 1
![screenshot_12](https://cloud.githubusercontent.com/assets/17274154/17568217/d3fcfeb0-5f10-11e6-961d-3236a7a9775a.png)

Prueba 2
![screenshot_13](https://cloud.githubusercontent.com/assets/17274154/17568224/dae9a5b6-5f10-11e6-87db-55e4762a09c3.png)

##### Pasos exactos para reproducir el error:

Prueba 1:
-Ingrese a la community
-presionar icono de geolocalizacion por primera vez
-Error de la actividad de fermat no responde

Prueba 2:
-Luego de arrojar el error de la prueba 1, darle click en Wait
-esperar que reaccione la aplicación
-darle al icono de la lupa que sale en la barra superior
-se congela la pantalla unos segundos
-error de actividad de fermat no responde

##### Inserta Archivo aLogcat: 

Prueba 1: 3:28pm 
Prueba 2: 3:31pm

[log Geolocalizacion.zip](https://github.com/Fermat-ORG/beta-testing-program/files/411975/log.Geolocalizacion.zip)
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:
 
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17568358/65e3b4ae-5f11-11e6-9ce3-4c51835a26c9.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by arosiopr** [comment]
En mi celular sucede el mismo error, pero en mi caso es cuando le doy arriba en la lupa de buscar que sale al presionar el icono de GPS.

![screenshot_2016-08-10-15-34-48](https://cloud.githubusercontent.com/assets/5313326/17568586/76a76dfc-5f12-11e6-81b6-ff4974a85fd9.png)

**Teléfono Físico**
![alcatel](https://cloud.githubusercontent.com/assets/5313326/17568592/7a137cec-5f12-11e6-9916-3e7a7934449a.png)

**Archivo LOGCAT**

Hora aproximada 3:36pm

[Log_2016-08-10_15-36-17.txt](https://github.com/Fermat-ORG/beta-testing-program/files/411993/Log_2016-08-10_15-36-17.txt)

**Comment by maydiamc** [comment]
en la version 22.1 de CBP sigue sucediendo este error

LogCat
2:14pm  
[logcat 746.zip](https://github.com/Fermat-ORG/beta-testing-program/files/420997/logcat.746.zip)

![screenshot_37](https://cloud.githubusercontent.com/assets/17274154/17710608/fe56b264-63bb-11e6-9cf1-9202a3b1e2a3.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17710643/21c27972-63bc-11e6-822f-cfe05c7324c0.png)

**Comment by wendyduran90** [comment]
En la versión 22.4 persiste el error . Esta prueba se realizo desde teléfono  físico  con versión de android 4.4.4 . 
![screenshot_2016-08-23-10-17-44 1](https://cloud.githubusercontent.com/assets/20212920/17895974/ecca8a14-691c-11e6-98f2-f1bf5c63d225.jpg)

**Comment by maydiamc** [comment]
En la versión 22.6 de CCP, sigue sucediendo este error

Pasos
-entrar al icono de geolocalizacion de la community de CCP
-colocar cualquier nombre de ubicacion  
-se da click a la lupa, 
-se tarda en cargar y arroja fermat no responde

![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/17931795/23a38ce8-69db-11e6-8ed9-629c0d96d55b.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17931799/287d84d0-69db-11e6-8f85-f0378399b5e2.png)

**Comment by yolandayancel** [comment]
Prueba 24-08-16 Caso 746 
CBP 22.6
Sony Xperia S 4.1.1 16api 320dpi
Pasos seguidos para reproducir el caso:
1 Ingreso a la Community
2 Click sobre simbolo de Geolocalización
3 Entra y escribo venezuela y al hacer click en la lupa, no funciona, clickeo varias veces y aparece el desplegable pero se queda congelada, clickeo varias veces y fermat no responde.
![screenshot_8](https://cloud.githubusercontent.com/assets/17283358/17933086/c1b90ae8-69e0-11e6-8025-8224e0d06113.png)
Emulador Genymotion:
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17933103/d4ee51a4-69e0-11e6-82db-c97f7f818349.png)

**Comment by gablup** [comment]
Prueba 24-08-16 (Mañana), Versión: 22.6

Luego de probar varias veces desde mi teléfono con android 5.1 no persiste el error pero al parecer en los emuladores persiste. Favor verificar 

![screenshot_2016-08-24-09-05-00](https://cloud.githubusercontent.com/assets/17261437/17933242/e21adc7c-6a02-11e6-90d9-9d6c520a2a8f.png)

![screenshot_2016-08-24-09-57-59](https://cloud.githubusercontent.com/assets/17261437/17933362/52ff3e9c-6a03-11e6-9a3d-0e95cacbfa84.png)

Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB.

**Comment by nattyco** [comment]
@maydiamc  @yolandayancel  @AdryCanonico  en las versiones mas chicas de Android estoy viendo que tarda en traer la lista, y si le dan al boton varias veces va a dar error, voy a ver si se puede poner algo como un Loading ....

**Comment by nattyco** [comment]
@maydiamc  @arosiopr en este caso se agrego una ventana modal de loading.. para indicar al usuario que espere a que la lista de ciudades se cargue para evitar que vuelva a presionar la lupa y se proboque el error de que la app no responde.

Verificar en la version 22.8 de la apk

**Comment by danielaporras** [comment]
En la version 22.8 no persiste el error.
![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/18051800/c443895e-6dc4-11e6-995e-951a55ec0bfe.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/18051807/c87fda40-6dc4-11e6-9a79-d1a048b6fc71.png)

**Comment by arosiopr** [comment]
@IsbetVR  Solucionado en la versión 22.8 de CBP
Ahora sale un please wait y carga al momento
![screenshot_2016-08-29-08-47-37](https://cloud.githubusercontent.com/assets/5313326/18051872/2982c74e-6dc5-11e6-9623-f298073de1e7.png)

### **Telefono Fisico** 

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/18051882/377e9486-6dc5-11e6-8903-e28f8fea89b9.png)

**Comment by IsbetVR** [comment]
Closed #746
