### ISSUE TITLE
COMMUNITIES - CHAT - BARRA SUPERIOR NO MANTIENE FORMATO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#747]
#### Nombre pantalla

CHAT COMMUNITY

### Nombre de la Aplicación 

CBP 21.8

-----

##### Reporte de error: 

Al ingresar en la comunidad de chat se puede observar que sale en la parte superior: 

Estando en la pantalla BROWSER: P2P Chat Comm.., lupa, y simbolo de GPS.
Si voy a CONNECTIONS: solo sale P2P Chat Community y la Lupa.
Al ir a NOTIFICATIONS: solo sale P2P Chat Community
No mantiene el formato como en el caso de CCP.

##### Screenshot o Capture de pantalla:

BROWSER
![screenshot_2016-08-10-15-33-13](https://cloud.githubusercontent.com/assets/5313326/17568416/a6cbe0c2-5f11-11e6-8188-10200c8afe32.png)

CONNECTIONS
![screenshot_2016-08-10-15-33-29](https://cloud.githubusercontent.com/assets/5313326/17568419/a875539a-5f11-11e6-8125-cd3464e1a938.png)

NOTIFICATIONS
![screenshot_2016-08-10-15-33-40](https://cloud.githubusercontent.com/assets/5313326/17568424/ab621f52-5f11-11e6-8c38-a28e187072ab.png)

##### Pasos exactos para reproducir el error:

 Ingresar a Chat Community
 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17568563/59f9dcbc-5f12-11e6-964d-6ee5d538912c.png)

**Comment by arosiopr** [comment]
@sanro14

**Comment by yolandayancel** [comment]
Prueba 10-08-16
Caso 747  CBP V 21.6
Sony Xperia 4.1.1 16api 320dpi
ocurre lo reportado. no mantiene el formato..
![screenshot_8](https://cloud.githubusercontent.com/assets/17283358/17570148/3506f406-5f19-11e6-9dcc-945f13d06f4b.png)

**Comment by josejcb** [comment]
@yolandayancel creo que esta reportando algo muy diferente a lo que dice el issue, esto lo hacen mucho, por favor lean los issues. 
@furszy mira esto de las pestañas.

**Comment by josejcb** [comment]
@MaviDavsa unifiquen issues https://github.com/Fermat-ORG/beta-testing-program/issues/742

**Comment by furszy** [comment]
El tamaño de las letras de los tabs fue postergado por no ser prioridad en este momento. Prueben funcionamiento primero por favor.

**Comment by yolandayancel** [comment]
@josejcb 

Buenas noches Sres.

Con respecto a su comentario caso 747,
1.- Se subieron las  fotos  en las cuales se puede verificar  que en el emulador  usado  aparece lo reportado.
2.- Sobre el diseño gráfico: No se tenia conocimiento de que  estaba diseñado de esa forma..

Saludos cordiales
Yolanda Yancel

**Comment by arosiopr** [comment]
@josejcb  es una sugerencia como experriencia de usuario. Las apks por lo general mantienen un formato disculpa por comparar con CCP.

@furszy se que no es prioridad. Se reporto porque nos dijeron que como no funcionaba la red buscáramos errores Gráficos.

**Comment by josejcb** [comment]
@arosiopr ok, no hay problema, la explicación para no tomar la sugerencia es que cada pestaña tiene su menú. Que en notifications este el icono de ubicación no tiene sentido porque es una función exclusiva del browser. Asi como el buscador en notificaciones, si solo funciona en browser y connections. Esa es mi explicación desde el punto de vista funcional. Te remito también con @arnaldos para que te explique el porqué del diseño así.

**Comment by arosiopr** [comment]
@IsbetVR  por favor cerrar.  Es el diseño que hicieron.

**Comment by arnaldos** [comment]
@arosiopr @sanro14 Para los tabs browser y conections debe aparecer las funciones (search, gelocation y el menu de 3 puntitos). para notifications solo el menu de los 3 puntos. con respecto al icono los recurso fueron enviados e implementados. y en una conversación con @josejcb me comento que la lupa al ser implementada, se refleja la que estamos viendo actualmente debido a que viene por defecto con la versión del android. por esa razón no se muestra el recurso que fue enviado. si no me equivoco, el recurso se muestra como debe ser a partir del 5.0 eso fue conversado aproximadamente en unos 2 meses cuando se implementaron los recursos de chat.

Este caso es algo lo pueden resolver en la implementacion los muchachos de desarrollo.

**Comment by josejcb** [comment]
Para q no perdamos más tiempo y sigamos buscando bugs funcionales, les pongo como esta en el diseño de @arnaldos esto de los iconos arriba, connections y browser respectivamente. https://github.com/Fermat-ORG/fermat-graphic-design/issues/861
![93d19ed8-38bc-11e6-9952-f7b01be5ba88](https://cloud.githubusercontent.com/assets/7374940/17597945/bf01a6d4-5fbd-11e6-9444-fab9949571c1.jpg)
![895ff788-38bc-11e6-9f2d-8ded3554f203](https://cloud.githubusercontent.com/assets/7374940/17597948/c46ba994-5fbd-11e6-81eb-49070371f245.jpg)

**Comment by sanro14** [comment]
ok @josejcb muchas gracias por los mockups que nos pasaste, tendremos en cuenta esto, con todo respeto pero todos los issues que se suben al repositorio se hacen porque son necesarios, y no son parte de perder tiempo, si la sugerencia se hizo para que el usuario tenga la opción dentro de sus conexiones de filtrar por la localización de sus contactos, es porque sería bastante funcional que sea hecho de esa manera. este issue quedará abierto y pendiente.

**Comment by josejcb** [comment]
Excelente, se tomará en cuenta para una próxima versión de CHT, dado que, como se muestra en el issue de diseño gráfico y en los mockups adjuntos, esta funcionalidad sugerida es nueva, no estaba en lo acordado a desarrollar.

**Comment by arosiopr** [comment]
@AdryCanonico  solucionado en versión 2.1 de CHAT se puede cerrar
