### ISSUE TITLE
CHAT - CHATS - MENSAJE INFERIOR CORTADO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#749]
#### Nombre pantalla

CHATS

### Nombre de la Aplicación 

CBP 21.8
-----

##### Reporte de error: 

   *Al ingresar a CHAT en la pantalla inicial CHATS el mensaje de que sale debajo de "No hay Chats" no se logra visualizar.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-10-16-03-57](https://cloud.githubusercontent.com/assets/5313326/17569598/f7f08322-5f16-11e6-8731-a21b9bab0d5c.png)

##### Pasos exactos para reproducir el error:

Ingresar a CHAT

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17569615/0f56aae6-5f17-11e6-89c6-862c2817eaae.png)

**Comment by arosiopr** [comment]
@sanro14

**Comment by IsbetVR** [comment]
@RoyGF

**Comment by josejcb** [comment]
Solucionado, favor revisen en el próximo apk.

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en versión 21.9 de CBP se puede cerrar

**Comment by IsbetVR** [comment]
Closed #749
