### ISSUE TITLE
Bitcoin Wallet- Error de Visualisation y Falta la Fecha cuando fue hecha la transaccion 

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#75]
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

En la Pantalla de Transacciones recibidas y enviadas los datos se solapan con la Hora y el texto se ve mezclado como figura en la Foto de mas abajo. También como se puede ver solo figura la hora en la que fue hecha la transacción y no la fecha, de hecho estas transacciones fueron hechas un día anterior y no es posible saber eso .

<img width="470" alt="captura de pantalla 2016-03-11 a las 12 53 17" src="https://cloud.githubusercontent.com/assets/15804433/13707432/5b5e8e92-e788-11e5-9ed1-1e32c54c497b.png">

<img width="401" alt="captura de pantalla 2016-03-11 a las 12 53 28" src="https://cloud.githubusercontent.com/assets/15804433/13707433/5ffbf282-e788-11e5-8110-3f90fd83b1f5.png">

<img width="401" alt="captura de pantalla 2016-03-11 a las 12 53 28" src="https://cloud.githubusercontent.com/assets/15804433/13707438/6434399a-e788-11e5-99d9-15213a45c160.png">

<img width="402" alt="captura de pantalla 2016-03-11 a las 12 56 09" src="https://cloud.githubusercontent.com/assets/15804433/13707492/b4a924e4-e788-11e5-89b5-ec43d14fa6fe.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="405" alt="captura de pantalla 2016-03-11 a las 12 59 10" src="https://cloud.githubusercontent.com/assets/15804433/13707580/1ccdfcfc-e789-11e5-99fe-f4dc935f1197.png">

**Comment by nattyco** [comment]
@augusto-ponce  Se agrego la fecha completa, probar en la nueva version.
