### ISSUE TITLE
PROFILES-Selección de imagen desde camara del dispositivo no guarda la imagen en la galeria

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#751]
#### Nombre pantalla

PROFILES

### Nombre de la Aplicación 

CBP 21.8 
-----

##### Reporte de error: 

   *Al crear un perfil y seleccionar la opción de tomar foto, guardar y todo. En el dispositivo no queda guardada la imagen que se acaba de tomar.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-10-14-36-19](https://cloud.githubusercontent.com/assets/5313326/17569916/4064f678-5f18-11e6-93d7-8368b156b6f3.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a crear perfil

##### Inserta Archivo aLogcat: 

Hora aproximada 2:36pm

[Log_2016-08-10_16-26-58.txt](https://github.com/Fermat-ORG/beta-testing-program/files/412052/Log_2016-08-10_16-26-58.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17569932/509a1000-5f18-11e6-988b-50d3b4725674.png)

**Comment by arosiopr** [comment]
@sanro14

**Comment by Gabymorillo** [comment]
Desde el telefono fisico,  en la versión 21.8 ocurre lo reportado.

![screenshot_2016-08-10-16-32-11_720](https://cloud.githubusercontent.com/assets/17262077/17570247/a289b874-5f19-11e6-982d-52af12640bc5.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17570201/778fd32e-5f19-11e6-89c9-f773e36a94d1.png)

**Comment by MaviDavsa** [comment]
@RoyGF

**Comment by josejcb** [comment]
@arosiopr Lo tomamos como sugerencia (porque no es un error como lo llaman, ya que no es parte de las funciones principales de la aplicación y si no afecta los flujos ni la interacción con Fermat) y la aceptamos, en los próximos apk lo tendrán.

**Comment by AdryCanonico** [comment]
Por favor especificar en esta versión debe guardarla en la galería o no, ya que es un debate desde la primera versión de chat.

**Comment by arosiopr** [comment]
Se Solucionó este caso en la versión 22.4 de CBP, en mi dispositivo.

Teléfono Físico 

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17892253/4ae658ee-690e-11e6-9760-8b23acc3471c.png)
