### ISSUE TITLE
Bitcoin Wallet - Texto del botón de la ventana modal no se aprecia bien

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#756]
#### Nombre pantalla
Home (Noticia!)

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   *En la version 21.9 de CBP al entrar a la apk Bitcoin Wallet aparece una pantallas que dice Noticia! donde el boton "Cerrar" es poco visible.

##### Screenshot o Capture de pantalla:

![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/17593393/b635f9b0-5fb3-11e6-986b-b511635731fd.png)

##### Pasos exactos para reproducir el error:
1.Entre a la Bitcoin Wallet.
2.Me apacio una pantalla llamada (Noticia!).
3.El Boton "Cerrar" de esa pantalla es poco visible.

##### Inserta Archivo aLogcat: 

[Google Nexus 4 - 4.1.1 - API 16 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/413514/Google.Nexus.4.-.4.1.1.-.API.16.-.768x1280-logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

 
![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17593509/110b421e-5fb4-11e6-9137-0aa25e2776a9.png)

@IsbetVR

**Comment by yolandayancel** [comment]
Prueba 11-08-16
Caso 741 CBP 21.9
Sony Xperia S 4.1.1 16 api 320 dpi

Ocurre lo reportado: no se puede leer el aviso en el cuadro de abajo..
![screenshot_19](https://cloud.githubusercontent.com/assets/17283358/17593636/93b642b8-5fb4-11e6-911a-00eadaa442fd.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17593645/9cf8e092-5fb4-11e6-8ec2-91068341d3de.png)

**Comment by RAYMALDONADO** [comment]
en el emulador google nexus 4-4.1.1 tambien persiste lo comentado  
![boton_sincolor](https://cloud.githubusercontent.com/assets/20222795/17594301/dee05f2e-5fb6-11e6-928a-31491aa5c0ad.jpg)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by Gabymorillo** [comment]
En la versión 22.0 de la CCP desde mi telefono fisico ya no sucede este error. 

![screenshot_2016-08-15-13-07-28_720](https://cloud.githubusercontent.com/assets/17262077/17672313/bce5a074-62e9-11e6-812f-72417c9b23b5.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17672251/7bb8bf14-62e9-11e6-8cf7-f013c2accb72.png)

**Comment by danielaporras** [comment]
En mi dispositivo ya no se repite este error.

![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/17672983/07d4771a-62ed-11e6-9c9c-b80c32c71e95.png)


![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17672990/139ac0e0-62ed-11e6-90ee-268cd2e8974d.png)

**Comment by IsbetVR** [comment]
Closed #756
