### ISSUE TITLE
COMMUNITIES - CCP - Usuarios en la community se ven asimetricos

### ISSUE THREAD

**Issue by Glaurano** [Fermat-ORG/beta-testing-program#758]
#### Nombre pantalla

CCP Community

### Nombre de la Aplicación 

CBP 21.9

-----

##### Reporte de error: 

   *Al ingresar a la community de la Bitcoin Wallet y entrar en la pantalla de ''Browser'' los usuarios aparecen asimetricos 

##### Screenshot o Capture de pantalla:

![screenshot_1](https://cloud.githubusercontent.com/assets/20232734/17623007/da1abc68-606b-11e6-97c6-af3d51e40857.png)

##### Pasos exactos para reproducir el error:

Ingresar a la CCP Community

##### Inserta Archivo aLogcat:  
  
[HTC One X - 4.1.1 - API 16 - 720x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/415347/HTC.One.X.-.4.1.1.-.API.16.-.720x1280-logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/20232734/17623170/ba717964-606c-11e6-9c06-9d896c6b6f4d.png)

 @MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by yolandayancel** [comment]
Prueba 12-08-16
Caso 758 CBPV 21.9
Sony Xperia S
Ocurre lo reportado (contactos asimetricos)
![screenshot_1](https://cloud.githubusercontent.com/assets/17283358/17623789/d7377c58-606f-11e6-8afb-26bf52f425cd.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17623798/dda836e0-606f-11e6-90a1-6ea2d446d8e7.png)

**Comment by marielis-urbina** [comment]
En la versión 21.9 de CBP, sucede este error

![asimet](https://cloud.githubusercontent.com/assets/19353722/17623791/d9a716ce-606f-11e6-9d76-fe2811f23ceb.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17623796/dd47ad2a-606f-11e6-9032-d45243fe7cc2.png)

**Comment by arosiopr** [comment]
persiste el error 

Teléfono Físico
![screenshot_2016-08-12-09-33-19](https://cloud.githubusercontent.com/assets/5313326/17623804/e73b6d8a-606f-11e6-9351-efa916faa332.png)

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17623815/f3ebb3a0-606f-11e6-8261-fb7b6b7776a6.png)

**Comment by Gabymorillo** [comment]
Desde el teléfono físico, en a versión 21.9 sucede el error mencionado. 

![screenshot_2016-08-12-09-33-42_720](https://cloud.githubusercontent.com/assets/17262077/17623843/1cfe8466-6070-11e6-8200-3bda9a43fa37.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17623816/f428a3f0-606f-11e6-813a-9d7e983e55be.png)

**Comment by marielis-urbina** [comment]
Con la versión 22 de CBP, persiste este error

![dispares](https://cloud.githubusercontent.com/assets/19353722/17673691/4727c248-62f0-11e6-92cd-1fae2791e436.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17673677/2ff73626-62f0-11e6-8311-1320ea46caa8.png)

**Comment by yolandayancel** [comment]
Prueba 15-08-16
Caso 758 CBP 22.0
Ocurre lo reportado (los contactos no están ordenados simétricamente)
![screenshot_2016-08-15-15-26-38](https://cloud.githubusercontent.com/assets/17283358/17676497/d3445910-62fc-11e6-88a3-b90c7a87471b.png)

Telefono fisico
![1](https://cloud.githubusercontent.com/assets/17283358/17676508/e35ebc78-62fc-11e6-987e-96807f18c97d.png)

**Comment by yolandayancel** [comment]
Prueba 16-08-16
Caso 758 CBP 22.1
No ocurre lo reportado (los contactos ya se ven asimetricos)
![668](https://cloud.githubusercontent.com/assets/17283358/17709030/7338e040-63b5-11e6-9b6e-4f0729b0af53.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17709037/7e27dbc8-63b5-11e6-9d90-66d9e567da8e.png)

**Comment by arosiopr** [comment]
Solucionado en la versión 22.1 de CBP

![screenshot_2016-08-16-13-38-49](https://cloud.githubusercontent.com/assets/5313326/17709931/21954e3c-63b9-11e6-8062-baaa1988802f.png)

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17709937/2619693e-63b9-11e6-8427-52d86006043f.png)

**Comment by Glaurano** [comment]
El error reportado ya no sucede con la version 22.3 @MaviDavsa  @AdryCanonico
