### ISSUE TITLE
Bitcoin Wallet - Pop up de Ayuda no se muestra en la pantalla de Payment Request

### ISSUE THREAD

**Issue by franciscoj961** [Fermat-ORG/beta-testing-program#759]
Prueba 12-08-16
V21.9 
[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/415402/logcat.zip)

#### Nombre pantalla
Payment Request

### Nombre de la Aplicación 

Bitcoin Wallet
-----

##### Reporte de error: 
Al clickear en la Ayuda (Help) de la pantalla del Payment Request no muestra el Pop up o hace alguna otra función 

![1212](https://cloud.githubusercontent.com/assets/20245988/17623959/abea92e6-6070-11e6-9470-be146003e348.PNG)

![aboutphone](https://cloud.githubusercontent.com/assets/20245988/17623961/b2a16d26-6070-11e6-9300-b46225b3b857.PNG)

**Comment by maydiamc** [comment]
En mi emulador sucede el mismo error con la version 21.9 de CBP

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17624091/23add66c-6071-11e6-9863-301c3a7395be.png)

**Comment by Gabymorillo** [comment]
En la versión 21.9 de CBP, desde el teléfono físico sucede lo reportado. 

![screenshot_2016-08-12-09-29-37_720](https://cloud.githubusercontent.com/assets/17262077/17624139/6ded1882-6071-11e6-9171-378a22444e48.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17624117/492da25a-6071-11e6-94af-0cf64eb0a9d4.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by marielis-urbina** [comment]
En la versión 22 de CBP, en mi emulador no pasa

![he](https://cloud.githubusercontent.com/assets/19353722/17673553/a4ad68ba-62ef-11e6-802f-45d8b4a61cf1.png)

![solicitud](https://cloud.githubusercontent.com/assets/19353722/17673504/69b17364-62ef-11e6-87d0-8d6809e6e9a3.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17673508/6c954b6e-62ef-11e6-9bf4-4e6da604062b.png)

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en Teléfono físico en la versión 22 de CBP

**Comment by IsbetVR** [comment]
Closed #759
