### ISSUE TITLE
bitcoin Wallet- Error en cuando intento ver una Notificacion

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#76]
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

Cuando presiono el botón de notificacion (ubicado arriba a la izquierda del home, en la barra superior para ser mas especifico) me tira la siguiente pantalla . Y por supuesto que no puedo ver nunca las notificaciones que me envían !

<img width="419" alt="captura de pantalla 2016-03-11 a las 13 21 07" src="https://cloud.githubusercontent.com/assets/15804433/13708435/628f0700-e78d-11e5-8f9f-7a24b1f2d07f.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="405" alt="captura de pantalla 2016-03-11 a las 12 59 10" src="https://cloud.githubusercontent.com/assets/15804433/13708445/6c0491ce-e78d-11e5-8fd5-b9b91cfc5b6a.png">

**Comment by nattyco** [comment]
@augusto-ponce probar con la nueva version.

**Comment by augusto-ponce** [comment]
Resuelto esto Naty ..
