### ISSUE TITLE
Bitcoin Wallet-Configuracion de fee - No funciona la selección

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#760]
#### Nombre pantalla

Send to contact

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   *En la version 21.9 de CBP en la bitcoin wallet, en la pantalla de send to contact no funcionan las opciones Nomal ni Rapido del menu desplegado (Configuracion avanzada).

##### Screenshot o Capture de pantalla:

Capture 1
![screenshot_2](https://cloud.githubusercontent.com/assets/19656830/17623859/3f238b36-6070-11e6-8e52-56a9eb81641e.png)

Capture 2
![screenshot_3](https://cloud.githubusercontent.com/assets/19656830/17623876/490e6ae4-6070-11e6-910c-e6f78b8ea641.png)

##### Pasos exactos para reproducir el error:

1.Al entrar en la Bitcoin wallet.
2.Seleccionar un contacto para enviar o solicitar btc.
3.Presione el boton de enviar.
4.Entro a la pantalla de Send to contact.
5.Desplego el menu de (configuracion avanzada).
6.En configuracion de fees quiero seleecionar Normal o Rapido, pero no es visible ningun circulo para seleccionar, como se ve en el capture 1 .
7. Si presiono al lado derecho de (Normal) se hace una sombra gris sobre la palabra (Rapido). Capture 2.
8.Si presiono al lado derecho de (Rapido) "Fermat no responde".

 

##### Inserta Archivo aLogcat: 

Hora aproximada: 9:29am / 9:45am

[Google Nexus 4 - 4.1.1 - API 16 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/415424/Google.Nexus.4.-.4.1.1.-.API.16.-.768x1280-logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

 
![screenshot_1](https://cloud.githubusercontent.com/assets/19656830/17624359/4972f5c0-6072-11e6-9088-0c05f9ae36ff.png)

 @MaviDavsa  @IsbetVR

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by arosiopr** [comment]
Teléfono Físico sale este error
![screenshot_2016-08-12-10-11-06](https://cloud.githubusercontent.com/assets/5313326/17625083/46e451b6-6075-11e6-845c-5d16686526d7.png)

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17625089/4c621a88-6075-11e6-8f2f-b5921daf92e4.png)

**Comment by GeronimoVierma** [comment]
21.9 CBP
Hora: 10:09 am (aprox)
Me ocurre el error reportado, la opción de normal y rápido no me funcionan:


[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/415486/logcat.txt)

![screenshot_4](https://cloud.githubusercontent.com/assets/19883115/17625296/32ba2dc2-6076-11e6-99ac-4c951bb3f735.png)




![4 1](https://cloud.githubusercontent.com/assets/19883115/17625301/394ae668-6076-11e6-95b8-58ac7bfe5fc1.png)

**Comment by andreagmarcano** [comment]
En la version 22.0 de CBP no ocurre lo comentado. Selecciona sin ningun problema la configuracion de taza (Lento, normal y rapido) 

![15-1](https://cloud.githubusercontent.com/assets/18452495/17672695/a34bd4d8-62eb-11e6-8959-1b75450af4ed.PNG)
![15-2](https://cloud.githubusercontent.com/assets/18452495/17672697/a67c17f8-62eb-11e6-98f3-e05d7c712166.PNG)
![captura1](https://cloud.githubusercontent.com/assets/18452495/17672724/c98e559e-62eb-11e6-8372-1bea4c5ff2c9.PNG)

**Comment by Gabymorillo** [comment]
Desde el telefono fisico, en la versión 22.0 de la CCP no ocurre este error. 

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17673387/db5bc402-62ee-11e6-93b6-72f68351b300.png)

**Comment by IsbetVR** [comment]
Closed #760
