### ISSUE TITLE
Bitcoin Wallet - Al actualizar el nombre del user desaparece la conexión establecida con el contacto

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#761]
### CBP v21.9

-----

##### Reporte de error: 

   *El día 11/08 cree mi perfil en Bitcoin Wallet "IsbetWallet11m2", realicé varias conexiones con otros users. Para el día de hoy, 12/08 mantuve el mismo perfil de usuario (Pantalla 1), las mismas conexiones que había establecido ayer así como también establecí nuevas conexiones, pero, uno de mis contactos de ayer (Manu 0811) modificó su nombre de perfil para el día de hoy (user actualizado a ManuH 12), y a mi me lo eliminó de mis conexiones (pantalla 2) y por ende de los contactos ya en la bitcoin wallet (Pantalla 3). Como se puede observar en la pantalla 4 mi user si está en sus conexiones en la community y en el browser sale que aún tenemos conexión (pantalla 5), así como entre sus contactos en la bitcoin wallet (pantalla 6)

##### Pantalla 1 (Mi perfil)

![screenshot_16](https://cloud.githubusercontent.com/assets/19142276/17624519/f157ea52-6072-11e6-82be-2b73ee1042b0.jpg)

##### Pantalla 2 (Mis conexiones en la Community)

![screenshot_15](https://cloud.githubusercontent.com/assets/19142276/17624537/024d2476-6073-11e6-9eac-c505569c7735.jpg)

##### Pantalla 3 (Mis contactos en Bitcoin Wallet)

![screenshot_13](https://cloud.githubusercontent.com/assets/19142276/17624577/258eb9d6-6073-11e6-8645-716e5f41e996.jpg)

![screenshot_14](https://cloud.githubusercontent.com/assets/19142276/17624583/29f5e5a8-6073-11e6-83ec-6af380a3c48a.jpg)

##### Pantalla 4 (Conexiones en la Community del otro user)

![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/17624613/4d76f79c-6073-11e6-83fc-18a05e73c35d.png)

##### Pantalla 5 (Browser del otro user donde sale que tenemos conexión)

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/17624650/778e9b5c-6073-11e6-96a9-bf6db374eec0.png)

##### Pantalla 6 (Contactos en Bitcoin Wallet del otro user)

![screenshot_8](https://cloud.githubusercontent.com/assets/19142276/17624658/8821f6f8-6073-11e6-988a-f71bf2180880.png)

________

##### Pasos exactos para reproducir el error:

1. El día 11/08 cree el perfil de Bitcoin Wallet como "IsbetWallet11m2" y establecí varias conexiones 
2. El día de hoy, 12/08, yo mantengo el mismo nombre del user, pero uno de mis contactos (Manu 0811) actualizó su nombre de perfil al ManuH 12, y al yo revisar mis conexiones en la community no está su user, ni con el nombre de perfil anterior ni con el nombre actualizado, revisé los contactos en la Bitcoin Wallet y tampoco está
3. Le pregunté directamente que buscara mi user entre sus contactos y mi user si permanece en sus contactos

------

#### Archivo Log de mi dispositivo

[log.zip](https://github.com/Fermat-ORG/beta-testing-program/files/415479/log.zip)

#### Archivo Log del dispositivo del otro user (ManuH 12)

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/415590/logcat.zip)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- HTC One X
- Android 4.1.1
- API 16 720x1280
- 320 dpi

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/17625220/e1ece40c-6075-11e6-8c29-de9e69da7b77.jpg)

**Comment by IsbetVR** [comment]
@nattyco por favor chequea esto

**Comment by nattyco** [comment]
@IsbetVR  verificar esto nuevamente en la v22.1 para ver si a alquien mas le sucede.

**Comment by maydiamc** [comment]
En la versión 22.2, se hizo la prueba con ese caso y comprobó que se soluciono

Pasos
-agregue a un contacto desde la mañana AndreaW18M
-ella desde su emulador le cambio el nombre al perfil a AndreaMarcano18
-en mis contactos permaneció el usuario y la dirección de ella, a pesar de que no se actualizo el nombre, se mantuvo la conexión

Capture desde mi emulador a la lista de contacto
![screenshot_14](https://cloud.githubusercontent.com/assets/17274154/17787500/5f3aa954-6557-11e6-93c2-a15d48d4eaa7.png)

Capture de el menú de andrea para mostrar el nuevo nombre de perfil
![captura](https://cloud.githubusercontent.com/assets/17274154/17787534/8340f3ee-6557-11e6-9d00-a5b527b0a295.PNG)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17787544/91925ee2-6557-11e6-8195-a117c8e2b145.png)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #761
