### ISSUE TITLE
WIZARD DE INICIO - TEXTO CORTADO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#762]
#### Nombre pantalla

WIZARD DE INICIO

### Nombre de la Aplicación 

CBP 21.9

-----

##### Reporte de error: 

   En la pantalla número 1 del Wizard de Inicio de la aplicación la palabra "buscarclasificados" debe ir separada. Además el texto no se logra leer completamente en ninguna de las primeras 4 pantallas y no permite correr hacia abajo, la única que se lee completa es la número 5.

##### Screenshot o Capture de pantalla:

**Pantalla 1**
![screenshot_2016-08-15-08-30-07](https://cloud.githubusercontent.com/assets/5313326/17665159/16ff420e-62c7-11e6-870c-b2f182e9ab6b.png)

**Pantalla 2**
![screenshot_2016-08-15-08-30-23](https://cloud.githubusercontent.com/assets/5313326/17665161/19cee7b4-62c7-11e6-8f87-42de8548a3e7.png)

**Pantalla 3**
![screenshot_2016-08-15-08-30-28](https://cloud.githubusercontent.com/assets/5313326/17665164/1cb052e2-62c7-11e6-8260-7271f427bae2.png)

**Pantalla 4**
![screenshot_2016-08-15-08-30-33](https://cloud.githubusercontent.com/assets/5313326/17665169/205a5640-62c7-11e6-8e39-83734167be40.png)

**Pantalla 5**
![screenshot_2016-08-15-08-30-38](https://cloud.githubusercontent.com/assets/5313326/17665171/23f33f2e-62c7-11e6-872d-1376fd17d4db.png)

##### Pasos exactos para reproducir el error:

Iniciar la apk

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

API 16

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17665202/66d6a498-62c7-11e6-9348-4239f60160d0.png)

**Comment by arosiopr** [comment]
@IsbetVR

**Comment by IsbetVR** [comment]
@nattyco @furszy

**Comment by nattyco** [comment]
@IsbetVR  @arosiopr  verificar estas pantallas en la version 22.1 de la apk. No es necesario tener data de cero el wizard se puede ver desde el settings del desktop, ulima opcion Help

**Comment by arosiopr** [comment]
@IsbetVR @MaviDavsa  Solucionado en la Versión 21.2

**Comment by Gabymorillo** [comment]
En la versión 22.1 de la CBP, desde el teléfono fisico, no sucede este error. 

![screenshot_2016-08-16-14-33-03_720](https://cloud.githubusercontent.com/assets/17262077/17711315/1635e294-63bf-11e6-99b3-11819a302aa6.png)

![screenshot_2016-08-16-14-33-59_720](https://cloud.githubusercontent.com/assets/17262077/17711318/1873d7b4-63bf-11e6-8bf9-c66b7fde5d23.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17711323/2357066a-63bf-11e6-9921-167065fffa3f.png)

**Comment by MaviDavsa** [comment]
Solucionado
