### ISSUE TITLE
Community- CCP - Boton de Geolocalizacion en Notifications 

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#763]
#### Nombre pantalla

CCP Community

### Nombre de la Aplicación 

Community de la Bitcoin Wallet - CCP - CBP Version 22.0

-----

##### Reporte de error: 

Al momento de ingresar a la CCP, clickeo en la pestaña de Notifications y al revisar el botón de Geolocalizacion noto que no tiene ninguna función. Mi recomendación es que retiren el botón, ya que no le veo funcionalidad en la pantalla de Notifications. creo que no es necesario.

##### Screenshot o Capture de pantalla:

![screenshot_3](https://cloud.githubusercontent.com/assets/19670319/17675108/39299760-62f6-11e6-8bec-3aba66fb4515.png)

##### Pasos exactos para reproducir el error:

- Ingresar en la CCP
- Ir a la pestaña de Notifications
- Dar Click a botón de Geolocaclizacion

##### Inserta Archivo aLogcat: 
 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/418693/logcat.txt)
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17675102/33903278-62f6-11e6-8bd2-46714924d2a6.png)

**Comment by arosiopr** [comment]
En la versión 22.0 de CBP persiste el error reportado, el botón de geolocalización no funciona en la parte de notifications

- [x] Teléfono Físico


![alcatel](https://cloud.githubusercontent.com/assets/5313326/17675288/1f581c3e-62f7-11e6-91a3-433283aa845a.png)

**Comment by nattyco** [comment]
@dorzar1989 @MaviDavsa  se quito la opcion del menu en la version 22.1 de la apk

**Comment by arosiopr** [comment]
@MaviDavsa  solucionado en versión 22.1

**Comment by yolandayancel** [comment]
Prueba 16-08-16
CAso 763 CBP 22.1
Sony Xperia S 4.1.1
Ya el botón de geolocalización no está..
![763](https://cloud.githubusercontent.com/assets/17283358/17710144/fcbd5afe-63b9-11e6-85e5-f798b7bd8447.png)

![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17710133/ef0d1b10-63b9-11e6-9a1f-2391238324d0.png)
