### ISSUE TITLE
Bitcoin Wallet - Error en el Send Request To Contact Con el minimo de Btc para enviar.

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#764]
#### Nombre pantalla

Send Reuest To Contact - Bitcoin Wallet

### Nombre de la Aplicación 

Bitcoin Wallet - CBP 22.0

-----

##### Reporte de error: 

Intente enviar una Solicitud de Btc a un usuario por un monto de 0.000025, pero es muy bajo, la Advertencia me dice que tengo que enviar un monto mayor a 500000000 BTC, que seria demasiado, deberia decir Bits, 

##### Screenshot o Capture de pantalla:

![screenshot_1](https://cloud.githubusercontent.com/assets/19670319/17675735/08a49cf4-62f9-11e6-8dcb-2abe3be284c0.png)

##### Pasos exactos para reproducir el error:

- Ingresar a Contacts
- Buscar Usuario para enviarle el Request
- Darle Solicitar
- Colocar el monto
- Confirmar Request.

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/418732/logcat.txt)
 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17675728/fc820556-62f8-11e6-9b2c-7e2405d0bb30.png)

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@dorzar1989 @MaviDavsa  corregido en la version 22.1 de la apk

**Comment by maydiamc** [comment]
en la version 22.1 de CBP persiste el error

![screenshot_38](https://cloud.githubusercontent.com/assets/17274154/17710794/e8e09a7a-63bc-11e6-9b6f-e4ed63cd49a7.png)

emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17710799/edb0f5f4-63bc-11e6-8edf-d94bb9d5bbfe.png)

**Comment by dorzar1989** [comment]
En la version 22.1 de la cbp persiste el error

![screenshot_19](https://cloud.githubusercontent.com/assets/19670319/17710873/4ad6c362-63bd-11e6-9c15-b439cfff298a.png)

Emulador

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17710879/52006062-63bd-11e6-99bc-6979be95298c.png)

**Comment by arosiopr** [comment]
- [x] Teléfono Físico 

Persiste el error

![screenshot_2016-08-16-14-29-00](https://cloud.githubusercontent.com/assets/5313326/17711006/e5341338-63bd-11e6-980c-a350cbb7a1bc.png)



![alcatel](https://cloud.githubusercontent.com/assets/5313326/17711009/ea596e94-63bd-11e6-9800-7c8dfd9e7553.png)

**Comment by nattyco** [comment]
@dorzar1989  verificar en la version 22.2 de la apk

**Comment by maydiamc** [comment]
en la versión 22.2 persiste el problema en mi emulador

![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/17776623/59a93194-652b-11e6-9ae6-6d7fc24f47e3.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17776631/5eb2803c-652b-11e6-9896-81ec485d180e.png)

**Comment by Gabymorillo** [comment]
Desde el telefono fisico, en la version 22.2 de la CCP persiste el error. 

![screenshot_2016-08-18-10-34-43_720](https://cloud.githubusercontent.com/assets/17262077/17777798/d10d5892-652f-11e6-86eb-ebf49d4ecd44.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17777803/d6195368-652f-11e6-8788-2f1c71abd350.png)

**Comment by RubenSem** [comment]
Desde emulador, en mi caso si funciono correctamente ahora el error esta en la alert, se puede notar en las capturas.
![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/17787390/f320fd54-6556-11e6-9bb5-5ea7f0172d10.jpg)
![screenshot_5](https://cloud.githubusercontent.com/assets/19676223/17787462/3cd26b4a-6557-11e6-9225-9193af4fb9a9.jpg)

Emulador:
![screenshot_2](https://cloud.githubusercontent.com/assets/19676223/17787527/7670f83a-6557-11e6-9006-1d35ab3f42e3.jpg)

**Comment by wendyduran90** [comment]
En la versión 22.3 no sucede este error. La prueba se realizo desde un teléfono móvil con versión de andorid 4.4.4 marca BLU modelo life one 2015 Tamaño 720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop

![screenshot_2016-08-19-10-11-30](https://cloud.githubusercontent.com/assets/20212920/17812628/e584929c-65f5-11e6-91ef-720578de0bb4.jpg)

**Comment by JeanFranco498** [comment]
El error esta solucionado cbp 22.3 

Prueba realizada desde: Telefono fisico 



![screenshot_2016-08-19-10-31-00](https://cloud.githubusercontent.com/assets/19807906/17813473/7f42a13c-65f9-11e6-80e5-35493280a7b5.png)

![screenshot_2016-08-19-10-34-43](https://cloud.githubusercontent.com/assets/19807906/17813487/8ef2c346-65f9-11e6-9141-c34223b2295a.png)
