### ISSUE TITLE
BITCOIN WALLET - CONTACT DETAIL - TEXTO DE BOTONES NO ESTA CENTRADO VERTICALMENTE

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#765]
#### Nombre pantalla

CONTACT DETAIL

### Nombre de la Aplicación 

CBP 22.0

-----

##### Reporte de error: 

   *Al ingresar a Contact Detail para realizar un Send o un Request se puede observar que el texto no está centrado verticalmente, es decir, esta muy pegado a la parte de abajo.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-15-14-31-26](https://cloud.githubusercontent.com/assets/5313326/17699147/2d149208-638d-11e6-925e-3c00c1ad4fa4.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a Contacts
2. Presionar sobre uno de los contactos

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17699167/44298b92-638d-11e6-805f-8d7544c3f40b.png)

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by JeanFranco498** [comment]
CBP 22.3 Ya el texto se ve centrado telefono fisico
 
![screenshot_2016-08-19-09-40-39 1](https://cloud.githubusercontent.com/assets/19807906/17811544/43c2c98c-65f1-11e6-91ca-1997a067af3e.png)


![screenshot_2016-08-01-23-59-25 1](https://cloud.githubusercontent.com/assets/19807906/17811586/59a8e3d0-65f1-11e6-96cf-86115ee4cf67.png)

**Comment by andreagmarcano** [comment]
En la version 22.3 ya no persiste el error, el texto se ve centrado. 
![19](https://cloud.githubusercontent.com/assets/18452495/17811920/e55d9604-65f2-11e6-92d7-2681c9ca4e7f.PNG)
![captura1](https://cloud.githubusercontent.com/assets/18452495/17811928/e7e1d55c-65f2-11e6-831c-3ebdf886b2db.PNG)
