### ISSUE TITLE
CHAT - Al borrar una conversación se borro el contenido de las otras.

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#766]
#### Nombre pantalla
*Home Chat

### Nombre de la Aplicación 
*Chat

-----

##### Reporte de error: 

   *Cuando tenemos varias conversaciones abiertas y decidimos borrar alguna conversación, lo que le pasa a las otras es que se borra lo que habíamos escrito (el chat sigue abierto pero quedan todos en blanco como si nunca hubieramos hablado).

##### Screenshot o Capture de pantalla:

Aquí vemos que tenemos varios chats abiertos
![screenshot_4](https://cloud.githubusercontent.com/assets/20217119/17705278/cfcbe93e-63a5-11e6-9b1d-78b32fa5eff1.jpg)

Aquí el usuario -Manu16M- fue borrado y ya podemos observar que se borro el contenido de las otras
![screenshot_5](https://cloud.githubusercontent.com/assets/20217119/17705279/d0137470-63a5-11e6-81f7-3e064754e903.jpg)

Aquí vemos mas detalladamente que si se borro el contenido.
![screenshot_6](https://cloud.githubusercontent.com/assets/20217119/17705280/d0bf5fa6-63a5-11e6-979f-0f0852638730.jpg)

##### Pasos exactos para reproducir el error:

1- Crearse un perfil de chat
2 - Agregar personas.
3 -  Irse al chat y iniciar varias conversaciones
4 - Borrar solo una conversación y en este punto sucederá el error y  se borrara lo que habíamos hablado con las otras personas.

##### Inserta Archivo aLogcat: 
El error sucedió entre las 10:00 y las 10:30

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/420617/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 1](https://cloud.githubusercontent.com/assets/20217119/17703420/a2feb04a-639f-11e6-99c1-3ebd33939685.jpg)

**Comment by nelsondb** [comment]
@RoyGF @MaviDavsa

**Comment by franciscoj961** [comment]
En la versión 22.2 CBP persiste el error ya mencionado
Prueba desde teléfono físico.

Descripción 
![screenshot_2016-08-02-08-18-47](https://cloud.githubusercontent.com/assets/20245988/17789401/1387e090-6560-11e6-81ac-f01ab40d55d8.png)

**Comment by Gabymorillo** [comment]
En la versión 22.3 del Chat, estaba usando el chat con Francisco y Geronimo, al borrar el chat con Francisco, se borró la conversación que tenía con Geronimo. 

![screenshot_2016-08-19-13-48-56_720](https://cloud.githubusercontent.com/assets/17262077/17819228/f4ea8a10-6614-11e6-934d-5cddabf6f32e.png)


![screenshot_2016-08-19-13-50-24_720](https://cloud.githubusercontent.com/assets/17262077/17819230/f6fdd0c8-6614-11e6-843a-f1526cf8b45b.png)

![screenshot_2016-08-19-13-50-32_720](https://cloud.githubusercontent.com/assets/17262077/17819229/f5ed3926-6614-11e6-888e-a425c176eaac.png)



![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17819087/55223622-6614-11e6-9ee9-3d267e702447.png)

**Comment by franciscoj961** [comment]
En la Versión 22.3 CBP persiste el error ya comentado.

![19088](https://cloud.githubusercontent.com/assets/20245988/17820561/61dcccfe-661b-11e6-82ec-a81394cabaf5.PNG)

**Comment by franciscoj961** [comment]
En la versión 22.3 CBP persiste el error ya comentado.
PRUEBA DESDE TELÉFONO FÍSICO. 

![screenshot_2016-08-02-08-18-47](https://cloud.githubusercontent.com/assets/20245988/17855407/9e0c0d8e-6846-11e6-8e85-32e28da13b55.png)

**Comment by franciscoj961** [comment]
En la versión 22.3 CBP persiste el error ya comentado
PRUEBA DESDE TELÉFONO FÍSICO. 

![screenshot_2016-08-02-08-18-47](https://cloud.githubusercontent.com/assets/20245988/17855728/375e857e-6848-11e6-94f3-e8f59b68d129.png)

**Comment by dorzar1989** [comment]
En la Version 22.3 de la CBP persiste el error

- Screenshot:

![screenshot_23](https://cloud.githubusercontent.com/assets/19670319/17855747/55365a40-6848-11e6-8a50-abcdedbbd521.png)

![screenshot_24](https://cloud.githubusercontent.com/assets/19670319/17855748/554b89a6-6848-11e6-9c9f-8c607c900ad3.png)

![screenshot_25](https://cloud.githubusercontent.com/assets/19670319/17855749/5551d04a-6848-11e6-8bf8-85efd331a76f.png)

![screenshot_26](https://cloud.githubusercontent.com/assets/19670319/17855750/555cd95e-6848-11e6-9f93-49a58c278df5.png)

- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/17855794/8d88d5a8-6848-11e6-98ff-45a32b0cd3be.png)

**Comment by Hernandezsmanu** [comment]
En la version 22.4 desde emulador no sucede lo reportado.

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/17892877/695b9a34-6911-11e6-9885-061fbbf49c74.png)

**Comment by nelsondb** [comment]
Usando emulador en la versión 22.4 está solucionado lo reportado.

![nexus 4 1](https://cloud.githubusercontent.com/assets/20217119/17892952/c18446d4-6911-11e6-831e-47ae67b8342e.jpg)

**Comment by wendyduran90** [comment]
En la versión 22.4 ya no sucede este error . La prueba se realizo desde un teléfono móvil con versión de android 4.4.4 marca BLU modelo Life one 2015. 

![2](https://cloud.githubusercontent.com/assets/20212920/17893074/43ca6da8-6912-11e6-89e8-8200f382c78d.jpg)

![1](https://cloud.githubusercontent.com/assets/20212920/17893084/4fb1e7ea-6912-11e6-9531-3830748c7b5f.jpg)

**Comment by IsbetVR** [comment]
Closed #766
