### ISSUE TITLE
BitCoin Wallet- Se pierden las transacción (envios)

### ISSUE THREAD

**Issue by kmiloxvii** [Fermat-ORG/beta-testing-program#767]
#### Nombre pantalla

Bitcoin Wallet Home 

### Nombre de la Aplicación 

Bitcoin Wallet - CBP 22.1

-----

##### Reporte de error: 

 Se procede a realizar una transacción por el monto de 1 btc a un contacto, la transacción quedo registrada en mi wallet pero al destinatario nunca llego y los bitcoins fueron descontados.

##### Screenshot o Capture de pantalla:
![enviar](https://cloud.githubusercontent.com/assets/2491042/17709948/3747bdd2-63b9-11e6-9f0a-31380b52e626.png)

![phone](https://cloud.githubusercontent.com/assets/2491042/17710116/d7ac8636-63b9-11e6-84a7-2ff2dcaa899c.png)

 

##### Inserta Archivo aLogcat: 
[Samsung Galaxy S4 - 4.2.2 - API 17 - 1080x1920_1-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/420959/Samsung.Galaxy.S4.-.4.2.2.-.API.17.-.1080x1920_1-logcat.txt)

 
 
 

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [ ] Teléfono Físico

##### Screenshot o Capture de pantalla:

 *Agregar las capture de la descripcion del emulador o teléfono.

**Comment by kmiloxvii** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@kmiloxvii  verificar si el envio de btc llego al destinatario, que contacto es al que enviaste?

**Comment by nattyco** [comment]
@MaviDavsa  @kmiloxvii se corrigo un error al armar el listado de transacciones, verificar en la version 22.2 de la apk

**Comment by andreagmarcano** [comment]
No ocurre lo sucedido en la version 22.2 de CBP 

![18](https://cloud.githubusercontent.com/assets/18452495/17779315/3adfcac0-6535-11e6-8f41-b19556d6be31.PNG)

![captura1](https://cloud.githubusercontent.com/assets/18452495/17779323/3e076082-6535-11e6-9aae-9faea9b69036.PNG)

@nattyco

**Comment by yolandayancel** [comment]
Prueba 18-08-16
Caso 767 CBP 22.2 (Bitcoin Wallet)
Sony Xperia S 4.1.1 16 api 320dpi
No ocurre lo reportado: (en este emulador si  llegan los BTC
1- Envio de 0.0006 BTC al user (G1 May 18m) . En el Balance me registro el descuento..
![767 3](https://cloud.githubusercontent.com/assets/17283358/17779535/0126bd6a-6536-11e6-83d9-2e52656dfc6e.png)
2- El  usuario recibió los BTC como muestra una captura de su emulador:
![pasted image at 2016_08_18 11_16 am](https://cloud.githubusercontent.com/assets/17283358/17779575/1d26b27c-6536-11e6-9f31-c23627b24d00.png)

Emulador Genymotion:
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17779657/6be226da-6536-11e6-9b37-94a66f527b9a.png)

**Comment by Glaurano** [comment]
Con mi dispositivo (emuladr HTC One X 4.1.1 API 16) vesion 22.3 no sucede lo reportado
![screenshot_2](https://cloud.githubusercontent.com/assets/20232734/17813572/e067ed8c-65f9-11e6-8325-0ba89fbae76d.png)
1. Le envie btc al usuario de Nelson
![screenshot_1](https://cloud.githubusercontent.com/assets/20232734/17813596/f4bd64c4-65f9-11e6-9947-9fdcb1acfbf4.png)
2. Aqui se refleja que el usuario lo recibio(captura hecha por el usuario)
![pasted_image_at_2016_08_19_10_39_am](https://cloud.githubusercontent.com/assets/20232734/17813613/0d6f3524-65fa-11e6-8e7d-2dd91d58cad2.png)
Especificaciones del emulador:
![screenshot_3](https://cloud.githubusercontent.com/assets/20232734/17813618/15d57e8a-65fa-11e6-8ff6-5161cb0639a0.png)
