### ISSUE TITLE
BITCOIN WALLET - REQUEST RECEIVED - BOTON ACEPTAR NO SE DISTINGUE

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#768]
#### Nombre pantalla

REQUEST RECEIVED

### Nombre de la Aplicación 

CBP 22.1

-----

##### Reporte de error: 

   *Al ingresar en Request Received se puede observar que el botón de aceptar no se distingue bien, se confunde con el color de fondo.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-16-13-42-18](https://cloud.githubusercontent.com/assets/5313326/17710687/5c57d47e-63bc-11e6-832a-4d1857551faa.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a Bitcoin Wallet
2. Ingresar a la sección de Payment Request
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/17710729/8e006d06-63bc-11e6-9da3-e7726656c1fa.png)

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by danielaporras** [comment]
En mi dispositivo tambien se visualiza este error.
![screenshot_16](https://cloud.githubusercontent.com/assets/19656830/17736476/0bc77696-6456-11e6-87b9-0c657aa29d8c.png)


![screenshot_12](https://cloud.githubusercontent.com/assets/19656830/17736480/1000fd40-6456-11e6-9f2d-1176a5d19646.png)

**Comment by yolandayancel** [comment]
Prueba 17-08-16
Caso 768 CBP 22.1
Sony Xperia
Genymotion
No ocurre lo reportado en este emulador(en botón se ve bien)
![screenshot_13](https://cloud.githubusercontent.com/assets/17283358/17737704/408b17d8-645c-11e6-91b6-5e8fc237a2a3.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17737709/47f65654-645c-11e6-8562-4fde6468134b.png)

**Comment by nattyco** [comment]
@arosiopr  verificar en la version 22.2 de la apk

**Comment by maydiamc** [comment]
en la version 22.2 de CBP se soluciono este caso

![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/17776984/c4f63b62-652c-11e6-9f5d-86bbfc9bdabf.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17777047/fec85eba-652c-11e6-8b38-d2b1c686d451.png)

**Comment by JeanFranco498** [comment]
CBP 22.2 Solucionado

Telefono Fisico 

![screenshot_2016-08-18-10-29-55 1](https://cloud.githubusercontent.com/assets/19807906/17777597/16ff33ee-652f-11e6-8956-0983cfa90297.png)

**Comment by arosiopr** [comment]
@AdryCanonico  solucionado se puede cerrar
