### ISSUE TITLE
Blockchain no carga correctamente

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#769]
#### Nombre pantalla

Home Bitcon Wallet

### Nombre de la Aplicación 

CBP Versión 22.1
-----

##### Reporte de error: 

La barra roja del Blockchain aparece varias veces, es decir, al principio sale en rojo ya que esta verificando la cadena y luego de un tiempo la barra aparece en azul, pero al realizar cualquier movimiento en la aplicación vuelve a aparecer en rojo. 

##### Screenshot o Capture de pantalla:

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/17713315/411c1380-63c8-11e6-8fea-9b8531733516.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/5313335/17713319/43db7c82-63c8-11e6-801b-ffbf925c48cf.png)

##### Pasos exactos para reproducir el error:

En mi caso la verificación se ha realizado 2 veces y fue de la siguiente manera:

Caso 1:
1. Entrar a la Bitcon Wallet
2. Esperar que se verificara la Blockchain
3. Luego se verificarse, solicitar los bitcoins
4. Verificación nuevamente de la Blockchain

Caso 2:
1. Esperar que se verificara de nuevo la Blockchain
2. Luego de la verificación, revisar el balance diferido
3. Verificación nuevamente de la Blockchain

##### Inserta Archivo Logcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/421163/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/17713333/5275aefc-63c8-11e6-8e32-45a048df6bd8.png)

**Comment by maydiamc** [comment]
En mi emulador sucede lo mismo con la versión 22.1 de CBP

Logcat
3:30pm 
[log block.zip](https://github.com/Fermat-ORG/beta-testing-program/files/421177/log.block.zip)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17713726/50d1a89c-63ca-11e6-9426-e84243c7dbe7.png)

**Comment by MaviDavsa** [comment]
@nattyco @acostarodrigo

**Comment by JeanFranco498** [comment]
Sigue ocurriendo con cbp 22.2 el blockchain cambia de color al pasar de una pantalla a otra 


![screenshot_2016-08-18-10-03-50 1](https://cloud.githubusercontent.com/assets/19807906/17777065/1494cbac-652d-11e6-92c1-e33f82b3b6cc.png)



![screenshot_2016-08-18-10-16-49 1](https://cloud.githubusercontent.com/assets/19807906/17777074/1f1b7a80-652d-11e6-87aa-2d228068e29a.png)

**Comment by franciscoj961** [comment]
En la versión 22.2 de CBP persiste el error ya comentado.
Pruebas desde teléfono 

Descripcion del teléfono
![screenshot_2016-08-02-08-18-47](https://cloud.githubusercontent.com/assets/20245988/17785289/28edb57a-654e-11e6-9f61-04de0750c44f.png)

**Comment by IsbetVR** [comment]
Solucionado en la versión 3.4 CCP
Closed #769
