### ISSUE TITLE
Bitcoin Wallet- Bitcoins en Book Balance.

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#77]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla
Bit Coin Wallet

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El problema está en que una persona me transfirió BTC y los mismos llegaron al book balance, pero después de una hora seguían en el Book balance y una vez pasado ese tiempo ya los BTC deberían estar disponible es decir en el Available Balance! 

![error 11 03 16](https://cloud.githubusercontent.com/assets/17273005/13708454/e85031b4-e780-11e5-8352-bbc48807cb43.JPG)

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: 5.0

@augusto-ponce  @nattyco

**Comment by augusto-ponce** [comment]
@acostarodrigo entiendo Rodrigo q hay un retardo en las redes. Yo recibí ayer unos btc y todavía no ha pasado a mi available balance !

**Comment by maydiamc** [comment]
yo tengo el mismo problema con el book balance.

Modelo del telefono: Samsung galaxy mini s4
version del android: 4.4.2 kit kat

**Comment by acostarodrigo** [comment]
Hola, por lo que veo están usando la red de RegTest, que no soporta gran cantidad de conexiones y a veces es necesario reiniciar los clientes.

@nattyco Hoy voy a estar subiendo un cambio que hace que la sincronizacion inicial del blockchain en la red de testing sea mucho más rápido, lo cual va a mejorar la experiencia sobre la red de Testing (hasta que terminemos el progress bar del download).

Si siguen con problemas en RegTest reinicio los clientes.
