### ISSUE TITLE
Community - CCP - CRUCE DE  PERFILES ENTRE COMUNIDADES.

### ISSUE THREAD

**Issue by nelsondb** [Fermat-ORG/beta-testing-program#770]
### CCP

-----

##### Reporte de error: 

   *Cree un perfil en la Bitcoin Wallet y cuando me dirigí hacia la CCP Community a agregar pude notar que había un Perfil de chat del día de ayer "YolyChatT1608M".   

##### Screenshot o Capture de pantalla:

![screenshot_1](https://cloud.githubusercontent.com/assets/20217119/17736964/8b70ebb4-6458-11e6-9e59-0e9a440462e2.jpg)

##### Pasos exactos para reproducir el error:

1 - Crear perfil en la BTC Wallet
2 - Entrar a la CCP community
3 - En este punto veremos el perfil del chat.

 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/422643/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
-  Teléfono Físico

##### Screenshot o Capture de pantalla:

![nexus 4 1](https://cloud.githubusercontent.com/assets/20217119/17736987/a644c550-6458-11e6-926c-c9783bdc06df.jpg)

**Comment by nelsondb** [comment]
@franklinmarcano1970 @nattyco @AdryCanonico

**Comment by nattyco** [comment]
@MaviDavsa  @AdryCanonico  verificar si creando otros perfiles en chat vuelve a pasar esto, ya que no se puede comprobar que el perfil reportado haya sido creado en chat, la comunidad solo muestra lo que el servidor le envia, filtrando por los user de wallets. Hay que determinar si el perfil se envio mal desde chat o el servidor tiene algun problema con le catalogo.

**Comment by nattyco** [comment]
@AdryCanonico  como se vio en las capturas de pantallas Yolanda habia creado esa identidad al los Wallet user, desestimar este caso.
