### ISSUE TITLE
CHAT - Se desaparece configuración de pantalla y contenido

### ISSUE THREAD

**Issue by Hernandezsmanu** [Fermat-ORG/beta-testing-program#771]
#### Nombre pantalla

P2P CHAT

### Nombre de la Aplicación 

CBP Versión 22.2

##### Reporte de error: 

Tenia establecidas 3 conversaciones con los 3 usuarios que tengo en contactos, al momento de entrar a una ventana del chat para contestar y darle a la opción de regresar se quedo la pantalla en blanco.

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/17747734/229481ce-6484-11e6-84b5-36c9e89b8fd4.png)

##### Pasos exactos para reproducir el error:

**1.** Entrar a una ventana de chat para contestar
**2.** Darle en la opción de regresar
**3.** Pantalla en blanco.

##### Inserta Archivo aLogcat: 
  
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/423292/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/17747796/6b1e1036-6484-11e6-9387-1e2d6d58c0fa.png)

**Comment by kmiloxvii** [comment]
De igual manera tenia establecida 3 conversaciones, al momento de cambiar entre los chat's la aplicación comenzó a notarse lenta, al momento de ir atras para llegar al home de chat se desaparecieron las conversaciones y se colgo la aplicación.

![screenshot_2](https://cloud.githubusercontent.com/assets/2491042/17748151/0be64f14-6486-11e6-9a1b-0625fcf80aa2.png)

Emulador
![phonre](https://cloud.githubusercontent.com/assets/2491042/17748307/bd9a85b8-6486-11e6-9c2d-ae0c15c69179.png)



Archivo Logcat

[Samsung Galaxy S4 - 4.2.2 - API 17 - 1080x1920_1-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/423314/Samsung.Galaxy.S4.-.4.2.2.-.API.17.-.1080x1920_1-logcat.txt)

**Comment by IsbetVR** [comment]
@RoyGF @franklinmarcano1970

**Comment by GeronimoVierma** [comment]
En la versión 22.3 tenia establecida 4 conversaciones, al momento de cambiar entre los chat's en reiteradas ocasiones la aplicación mantuvo el rendimiento y no cambio a pantalla en blanco:


![screenshot_8](https://cloud.githubusercontent.com/assets/19883115/17819808/c5ab6d70-6617-11e6-9b32-5c4f84fe15b1.png)

![screenshot_9](https://cloud.githubusercontent.com/assets/19883115/17819818/d47d3f22-6617-11e6-9386-f1a68af41f74.png)

![4 1](https://cloud.githubusercontent.com/assets/19883115/17819824/dba27d94-6617-11e6-8d3c-11da979ef743.png)

**Comment by gablup** [comment]
En la versiòn 22.3 probado desde un dispositivo fìsico, no me ocurre el error.

Fecha: 19-08-16

![screenshot_2016-08-19-14-26-48](https://cloud.githubusercontent.com/assets/17261437/17820202/964b0854-6619-11e6-99a9-e613351e612d.png)

Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB.

**Comment by maydiamc** [comment]
En la versión 22.4 ocurrió exactamente lo mismo del caso que esta planteado, los pasos se realizaron exactamente igual.

Logcat 
9:26am [Log 771.zip](https://github.com/Fermat-ORG/beta-testing-program/files/432502/Log.771.zip)

Capture
![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/17893637/64a9c062-6914-11e6-91e9-97c9ca08054c.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17893652/78adb3de-6914-11e6-956f-1cd91d41556b.png)

**Comment by IsbetVR** [comment]
Se reabre el caso

**Comment by arosiopr** [comment]
En la versión 22.4  de CBP, ocurrió exactamente lo mismo del caso que esta planteado, los pasos se realizaron exactamente igual.

![screenshot_2016-08-23-09-36-58](https://cloud.githubusercontent.com/assets/5313326/17893935/83dc4918-6915-11e6-86e2-94a4091a67fd.png)

Teléfono Físico 

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17893942/89acb03a-6915-11e6-9a67-94e8c8774e9f.png)

Logcat
Hora aproximada: 9:36am

[Log_2016-08-23_09-42-58.txt](https://github.com/Fermat-ORG/beta-testing-program/files/432521/Log_2016-08-23_09-42-58.txt)

**Comment by danielaporras** [comment]
En la version 22.5 de CBP no se repite este error en mi dispositivo.

**Comment by arosiopr** [comment]
En la versión 22.5 de CBP se soluciono el error reportado.


Teléfono Físico 

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17905384/cd3e6b56-6940-11e6-8db1-7e72810afb0c.png)

**Comment by IsbetVR** [comment]
Closed #771
