### ISSUE TITLE
Bitcoin Wallet_Boton de Send request no funciona correctamente

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#773]
#### Nombre pantalla
Payment Request

### Nombre de la Aplicación 
Bitcoin Wallet 22.2

-----

##### Reporte de error: 

   *el botón de send request to contact de el menú de payment reques lleva al formulario equivocado, al de send to contact

##### Screenshot o Capture de pantalla:

![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/17778671/dc0f489c-6532-11e6-9539-546921ec89b0.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/17778677/de8b5598-6532-11e6-9d73-6406fde2bf4b.png)

##### Pasos exactos para reproducir el error:

-Ingresar al menú de payment request
-presionar el botón de send request to contact
-el boton lleva al formulario de Send to contact

##### Inserta Archivo aLogcat: 

10:20 aproximadamente
[log send r.zip](https://github.com/Fermat-ORG/beta-testing-program/files/425229/log.send.r.zip)

   ------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 ![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17778878/a1a93464-6533-11e6-8cb5-2dea594d03be.png)

**Comment by arosiopr** [comment]
@AdryCanonico @nattyco

**Comment by Gabymorillo** [comment]
En la versión 22.2 de la CCP, desde el telefono fisico sucede este error. 

![screenshot_2016-08-18-11-37-01_720](https://cloud.githubusercontent.com/assets/17262077/17780156/670fee92-6538-11e6-9166-083129b81fc8.png)

![screenshot_2016-08-18-11-37-54_720](https://cloud.githubusercontent.com/assets/17262077/17780128/4915f026-6538-11e6-83b5-8f43975d3650.png)


![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/17779760/d1690abe-6536-11e6-9cc6-ca2d246d45ae.png)

**Comment by danielaporras** [comment]
Este caso ya fue solucionado en la version 22.3
![screenshot_127](https://cloud.githubusercontent.com/assets/19656830/17812470/3840cf2e-65f5-11e6-9c8f-a55ddb2e84de.png)

![screenshot_128](https://cloud.githubusercontent.com/assets/19656830/17812478/3e4e3ff0-65f5-11e6-8401-da04f250c4b0.png)

![screenshot_126](https://cloud.githubusercontent.com/assets/19656830/17812488/4ee3d136-65f5-11e6-8ff0-d080d3c645dc.png)

**Comment by yolandayancel** [comment]
Prueba 19-08-16
Caso 773 CBP 22.3 (Bitcoin Wallet)
Sony Xperia 16api 320 dpi
No ocurre lo reportado..
Ingreso a la pantalla de request, cliqueo sobre el simbolo o boton para envio de solicitud de request
![773 1](https://cloud.githubusercontent.com/assets/17283358/17812480/3fd4b368-65f5-11e6-84ce-e8e0f198c153.png)

 y este desplega el formulario correcto.

![773 2](https://cloud.githubusercontent.com/assets/17283358/17812547/87bb7b58-65f5-11e6-84bf-9a1292598df1.png)
 Emulador:
![screenshot_20](https://cloud.githubusercontent.com/assets/17283358/17812566/9bd1d4d4-65f5-11e6-8bb1-30c39201f160.png)
