### ISSUE TITLE
PROFILES - WALLET USERS - GEOLOCALIZACION - HELP - RECOVERING

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#774]
#### Nombre pantalla

GEOLOCALIZACION HELP 

### Nombre de la Aplicación 

CBP 22.2

-----

##### Reporte de error: 

   *Al ingresar a profiles en la wallet users, presionar el simbolo de geolocalizacion, presionar los 3 puntos arriba a la derecha y entrar en help salio el error "Ooops recovering from system error"

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-18-14-14-24](https://cloud.githubusercontent.com/assets/5313326/17786397/a7c8711a-6552-11e6-861a-bc5392418115.png)

##### Pasos exactos para reproducir el error:

1. entrar a profiles wallets users
2. presionar icono de geolocalizacion
3. presionar 3 puntos arriba a la derecha
4. presionar help

##### Inserta Archivo aLogcat: 

[Log_2016-08-18_14-55-12.txt](https://github.com/Fermat-ORG/beta-testing-program/files/425657/Log_2016-08-18_14-55-12.txt)
 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17786504/1af2e18e-6553-11e6-96a4-6814da929e93.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by marielis-urbina** [comment]
En la versión 22.3 de CBP, no sucede este error en mi emulador

![prueba 774](https://cloud.githubusercontent.com/assets/19353722/17812009/3f477e1e-65f3-11e6-9d08-4afbfd6dd06e.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17812029/51881e76-65f3-11e6-8158-00f5ec467d15.png)

**Comment by wendyduran90** [comment]
En la versión 22.3 no sucede este error . La prueba se realizo desde un teléfono móvil con versión de andoid 4.4.4 marca BLU modelo life one 2015 Tamaño	720 x 1280 pixels, 5.0 pulgadas
1GB RAM, 8GB almacenamiento interno
Procesador Qualcomm MSM8926 Snapdragon 410 quad-core 64-bit 1.2GHz, GPU Adreno 306
Android OS, v4.4 KitKat (actualizable a Android 5.0 Lollipop

![screenshot_2016-08-19-09-54-34](https://cloud.githubusercontent.com/assets/20212920/17812094/9d515926-65f3-11e6-9374-da8e3a423b57.jpg)
