### ISSUE TITLE
Bitcoin Wallet-Home-Balance disponible no se muestra correctamente

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#775]
#### Nombre pantalla
Home

### Nombre de la Aplicación 
Bitcoin Wallet

-----

##### Reporte de error: 

   *En la version 22.2 de CBP al ingresar en la Bitcoin Wallet tengo 5.50btc en el balance diferido y 0btc en el balance disponible, al desplegar el drawer de la bitcoin wallet, selecciono cualquiera de sus opciones y regreso al home con la flecha atras aparecen 5.50btc en el balance disponible, si presiono para cambiar al balance diferido aparece el balance disponible en 0.

##### Screenshot o Capture de pantalla:
Capture 1
![screenshot_124](https://cloud.githubusercontent.com/assets/19656830/17788421/9c1c7ed4-655b-11e6-9c4f-4c92a102c6d6.png)

Capture2
![screenshot_125](https://cloud.githubusercontent.com/assets/19656830/17788430/a6475dc0-655b-11e6-87a8-6ee11edb75f4.png)

Capture 3
![screenshot_122](https://cloud.githubusercontent.com/assets/19656830/17788433/ab11381c-655b-11e6-82b4-a179c086fb3d.png)

Capture 4
![screenshot_121](https://cloud.githubusercontent.com/assets/19656830/17788436/b5df9c34-655b-11e6-8cf8-2387a62e933a.png)

Capture 5
![screenshot_123](https://cloud.githubusercontent.com/assets/19656830/17788957/0a5d699c-655e-11e6-9cc1-47918fe787ef.png)

Capture 6
![screenshot_124](https://cloud.githubusercontent.com/assets/19656830/17788961/0ffbb386-655e-11e6-8407-b8dbdbbbe004.png)

##### Pasos exactos para reproducir el error:

1.Ingreso a la bitcoin wallet. (Capture 1).
2.Tengo 5.50btc en el balance diferido y 0btc en el balance disponible. (Capture 1 y 2).
3.Despliego el drawer de la bitcoin wallet. (Capture 3).
4.Seleciono cualquier opcion del drawer de la bitcoin wallet (Contacts). (Capture 4).
5.Luego presiono en la flecha atras. 
6.Al regresar al home aparece 5.50btc en el balance disponible. (Capture 5).
7.Presiono para cambiar, el balance disponible queda en 0. (Capture 6).

##### Inserta Archivo aLogcat: 

 [Google Nexus 4 - 4.1.1 - API 16 - 768x1280-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/425851/Google.Nexus.4.-.4.1.1.-.API.16.-.768x1280-logcat.txt)
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_126](https://cloud.githubusercontent.com/assets/19656830/17790025/c3e1a2da-6562-11e6-8bd4-2f6b37e9fb43.png)

**Comment by kmiloxvii** [comment]
Me sucede el mismo caso, al solicitar los bitcoins quedan en el book, al navegar  por los menús de la aplicación y volver a la pantalla home de la bitcoin wallet, los bitcoins aparecen como disponible cuando en verdad siguen en el book.

ADJUNTO VIDEO CON LA DEMOSTRACIÓN DEL ERROR
[video.mp4.zip](https://github.com/Fermat-ORG/beta-testing-program/files/425878/video.mp4.zip)

![screenshot_2](https://cloud.githubusercontent.com/assets/2491042/17791109/90532056-6567-11e6-8e46-62f3c8019273.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/2491042/17791114/972c6496-6567-11e6-8964-5987035c3239.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/2491042/17791121/9f18f41c-6567-11e6-9779-2c7befcd249b.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/2491042/17791117/9a06f7a8-6567-11e6-956c-db1949f03f02.png)


Dispositivo de prueba.
Emulador 

![phone](https://cloud.githubusercontent.com/assets/2491042/17791133/abecbc0a-6567-11e6-8348-2900346ae103.png)

LogCat
[Samsung Galaxy S4 - 4.2.2 - API 17 - 1080x1920_1-logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/425911/Samsung.Galaxy.S4.-.4.2.2.-.API.17.-.1080x1920_1-logcat.txt)

**Comment by kmiloxvii** [comment]
@nattyco

**Comment by danielaporras** [comment]
Lo resportado en este caso fue solucionado en la version 22.3 por favor cerrarlo.
@MaviDavsa
