### ISSUE TITLE
Bitcoin Wallet - Desaparece el Contacto en el detalle de "RECEIVED"

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#777]
##### Reporte de error: 

  *Al hacer transacciones con la Bitcoin Wallet, enpecificamente mandar Requests, los contactos en el (RECEIVED) desaparecen, El nuevo contacto sustituye los anteriores, colocando todos las transacciones bajo la ultima conexión.  

##### Screenshot o Capture de pantalla:

Requests Aceptados
![prueba 6692](https://cloud.githubusercontent.com/assets/19353722/17815280/88887f70-6601-11e6-81a6-6be7a801d798.png)

Borra el primer contacto que es Nelson
![prueba 669](https://cloud.githubusercontent.com/assets/19353722/17815291/a5793bd8-6601-11e6-9168-6155a5106bca.png)

Borra el segundo contacto Yolanda
![prueba 6693](https://cloud.githubusercontent.com/assets/19353722/17815311/bc7963da-6601-11e6-830f-5ec4b96f4009.png)

##### Pasos exactos para reproducir el error:

1. Mando Requests a mis contactos.
2. Son aceptados por ellos y aparece la primera Transacción de 0.02 Btc. por Nelson.
3. Segunda Transacción aceptada igualmente por 0.02 Btc, contacto ( Yolanda).
4. Al aparecer La Transacción de Yoli, desaparece el contacto de Nelson y la Transacción de Nelson, queda bajo la figura de Yoli.
5. Tercera Transacción de Gero de 0.02 btc, de igual forma que la anterior se borra ahora el contacto de Yoli y todas las transacciones anteriores se agrupan bajo el ultimo contacto.

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/427412/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![image](https://cloud.githubusercontent.com/assets/19353722/17816030/0d3596ec-6605-11e6-98d7-86921ea255dd.png)

**Comment by IsbetVR** [comment]
@nattyco aqui está montado el caso, para que lo chequees por favor

**Comment by marielis-urbina** [comment]
En la versión 22.6 de CCP, no sucede este error en mi emulador

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/17935516/9e5d3a48-69e9-11e6-8f08-d9195c1f81af.png)
