### ISSUE TITLE
Bit Coin Wallet Settings

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#78]
### Template issue error report

Bit Coin Wallet

#### Nombre pantalla

Settings

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *En la pantalla Settings en la opcion Network al querer cambiar la red a TesNet este apunta un error y no es posible marcar la opción.

![screenshot_2016-03-15-09-53-52](https://cloud.githubusercontent.com/assets/17273349/13781345/32cee246-ea95-11e5-8c4d-7e571429d4d3.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE 
* Modelo: Apex 2
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
yo tambien tengo el mismo problema en la pantalla de settings 

Marca: Samsung Galaxy
Modelo: Mini S4
Version de android: 4.4.2

**Comment by MaviDavsa** [comment]
yo tambien tengo el mismo problema en la pantalla de settings

Emulador: BlueStarks
Version de android: 5.0

**Comment by sanro14** [comment]
yo también tengo el mismo problema en la pantalla de settings

Emulador: Genymotion
Version de android: 4.4.4.
Google Nexus 5

**Comment by augusto-ponce** [comment]
Yo tengo el mismo problema 
<img width="451" alt="captura de pantalla 2016-03-15 a las 13 01 17" src="https://cloud.githubusercontent.com/assets/15804433/13784452/15ccc44c-eaae-11e5-91e7-903a3aeb2cb5.png">

**Comment by nattyco** [comment]
@augusto-ponce  @MaviDavsa  Este error se corrigio en la nueva version, aunque los radio buttons siguen sin quedarse bien marcados, el setting lo guarda igual.

**Comment by yahdieli** [comment]
A mi también me aparece el mismo error

Emulador: BlueStacks

**Comment by adryx83** [comment]
Ya que no he podido actualizar el error se mantiene en mi version 

Android: 4.42

**Comment by sanro14** [comment]
@nattyco este error ya no aparece en la versión de la aplicación de hoy 18/03 en mi teléfono
Emulador: Genymotion
Version de android: 4.4.4.
Google Nexus 5

**Comment by adryx83** [comment]
Este error ya esta solucionado en la nueva version @augusto-ponce

**Comment by augusto-ponce** [comment]
ok Cerrado el caso entonces !! gracias @adryx83
