### ISSUE TITLE
Community_CCP_ Estatus del perfil se muestra en la ubicación de contactos 

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#781]
#### Nombre pantalla
Connections y Notifications

### Nombre de la Aplicación 
Community CCP, Version 22.4

-----

##### Reporte de error: 

   *El estatus colocado en mi perfil se ve reflejado en la ubicación de los contactos que me envían conexiones y en algunos de los que acepte como conexiones

##### Screenshot o Capture de pantalla:

Mi perfil
![screenshot_5](https://cloud.githubusercontent.com/assets/17274154/17897231/6d9d820a-6921-11e6-9468-922567de47e5.png)

Pantalla Conexiones
![screenshot_6](https://cloud.githubusercontent.com/assets/17274154/17897236/74f123d6-6921-11e6-916a-ed20d5926798.png)

Pantalla Notificaciones
![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/17897243/7e3b9a2a-6921-11e6-96b0-07de242c2d97.png)

##### Pasos exactos para reproducir el error:

-Esperar que llegue notificación de nuevo contacto
-Ir a pantalla de notificaciones para aceptar la solicitud de contacto
-Ir a pantalla de conexiones para verificar que el contacto se refleja allí

##### Inserta Archivo aLogcat: 

Hora 10:40am aproximadamente (llego notificación del contacto de la capture 3)
[los estatus.zip](https://github.com/Fermat-ORG/beta-testing-program/files/432784/los.estatus.zip)
 
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17897363/edc24a2e-6921-11e6-93e6-861301a896aa.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by JeanFranco498** [comment]
Version de CBP 22.6 Desde el teléfono físico sigue pasando con algunos usuarios 



![screenshot_2016-08-24-09-17-03_1024](https://cloud.githubusercontent.com/assets/19807906/17932180/c9ff693a-69dc-11e6-9b71-f76131298fa4.png)


![image](https://cloud.githubusercontent.com/assets/19807906/17932160/b3b67092-69dc-11e6-96e7-327217fa408c.png)

**Comment by nattyco** [comment]
@maydiamc  verificar en la version 22.7 de la apk

**Comment by dorzar1989** [comment]
En la Version 22.7 dela CCP ya no sucede este error 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/18006139/30244eb6-6b6c-11e6-8179-98ad61ad0350.png)

**Comment by JeanFranco498** [comment]
En la version 22.7 de CCP ya no se puede colocar el status por lo tanto este error no sucede
