### ISSUE TITLE
CHAT-ICONO DE NOTIFICACIÓN DE MENSAJE NUEVO ENTRANTE DESACTUALIZADO 

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#783]
#### Nombre pantalla

PANTALLA DE CHAT

### Nombre de la Aplicación 

CBP Versión 22.5 

-----

##### Reporte de error: 

Me encontraba estableciendo una conversación en chat con otro usuario cuando me llego una notificación de mensaje entrante, este icono es de color blanco y la forma del que usaba la aplicación en versiones anteriores (imagen 1):

##### Screenshot o Capture de pantalla:

![ros](https://cloud.githubusercontent.com/assets/19883115/17908162/5670054a-694d-11e6-8e24-bfd3d9fc9dcc.png)

##### Pasos exactos para reproducir el error:

 1. Establecer una conversación con otro usuario.
 2. Recibir notificación de un mensaje entrante.  

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/433482/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![5 0](https://cloud.githubusercontent.com/assets/19883115/17908389/4eb079f6-694e-11e6-921e-ae16283fe7b8.png)

**Comment by GeronimoVierma** [comment]
En la versión CHT-1.3 persiste el icono desactualizado en Nexus 5 5.0 

![screenshot_3](https://cloud.githubusercontent.com/assets/19883115/18313225/994bdc24-74db-11e6-8afd-1cbd1b07f5ee.png)


![screenshot_22](https://cloud.githubusercontent.com/assets/19883115/18313226/a318002a-74db-11e6-9ebd-d037818ce7e2.png)

**Comment by josejcb** [comment]
Esta barra de estatus no admite colores. Los iconos son en blanco y negro, todos si te fijas en las imagenes, no importa cual sea la notificación. No ocurre en todas las APIs.

**Comment by AdryCanonico** [comment]
@josejcb que te parece si lo estandarizas en blanco todas? Así queda uniforme en todas las versiones y Apis.

**Comment by josejcb** [comment]
Tendría que hacerlo @arnaldos y lo ponemos. Realmente el tema de notificaciones no era para esta versión y al final todas las apps lo implementaron, por eso gráficamente no se trabajó.

**Comment by arnaldos** [comment]
@josejcb vale perfecto !! ya te envío el recurso !

**Comment by dorzar1989** [comment]
En la Version 1.8 de Chat el icono de notificaciones sale ya Actualizado con el logo estandar.

- Screenshot:

![screenshot_234](https://cloud.githubusercontent.com/assets/19670319/18476217/2c3ea394-7997-11e6-8cdd-618e483d2025.png)


- Emulador:

![screenshot_233](https://cloud.githubusercontent.com/assets/19670319/18476222/2ea38ec4-7997-11e6-8824-31dd20a6558e.png)

**Comment by AdryCanonico** [comment]
Se probo en varios dispositivos y el diseño se visualizo estándar en todos.
