### ISSUE TITLE
Community_CCP_Al hacer reconexión con un contacto permanece el nombre de perfil anterior estando actualizado

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#784]
#### Nombre pantalla
Community

### Nombre de la Aplicación 
CCP versión 22.6

-----

##### Reporte de error: 

   *Al desconectar un contacto de la community, se borra de la pantalla conexiones pero sigue apareciendo en la lista de contactos de la bitcoin wallet, con la dirección y es posible hacerle envíos de payment request , pero al intentar hacer la reconexión con este mismo contacto la aplicación no lo permite ya que me arroja un mensaje de que el contacto esta offline a pesar de que este en linea

##### Screenshot o Capture de pantalla:

Contacto en mis conexiones  **DoorWallet248**
![screenshot_10](https://cloud.githubusercontent.com/assets/17274154/17944849/599b84fc-6a0f-11e6-8982-3faab48266db.png)

Desconexion de contacto
![screenshot_11](https://cloud.githubusercontent.com/assets/17274154/17944851/60d808e4-6a0f-11e6-8888-6dd6355a0b2b.png)
![screenshot_12](https://cloud.githubusercontent.com/assets/17274154/17944854/64fe43a2-6a0f-11e6-8f9a-3048cdb0aa16.png)

Revisión de la lista de contactos de la bitcoin wallet (contacto desconectado aun aparece)
![screenshot_13](https://cloud.githubusercontent.com/assets/17274154/17944870/7e02fdca-6a0f-11e6-86d8-c8adc3515d2e.png)

Búsqueda de contacto en Browse de la Community para hacer reconexion (muestra que no es un contacto)
![screenshot_14](https://cloud.githubusercontent.com/assets/17274154/17944921/a87724a0-6a0f-11e6-98b4-4d05d60fad72.png)

Click al contacto para reconectar (User Offline, pero el contacto esta en linea)
![screenshot_15](https://cloud.githubusercontent.com/assets/17274154/17944979/df9964a2-6a0f-11e6-88aa-b8b709ca6dea.png)

Prueba de envío de payment a contacto desconectado
![screenshot_16](https://cloud.githubusercontent.com/assets/17274154/17945002/f94f88fe-6a0f-11e6-95c8-ad4db623b8c7.png)
![screenshot_18](https://cloud.githubusercontent.com/assets/17274154/17945007/fe199564-6a0f-11e6-906b-c348ddf6b9c8.png)

Capture de la lista de contactos de DoorWallet248 (Aun salgo reflejada en su lista)
![screenshot_44](https://cloud.githubusercontent.com/assets/17274154/17945031/179131c8-6a10-11e6-9bb4-81a9db7b846c.png)
 

##### Pasos exactos para reproducir el error:

-Ir a conexiones de la community
-Desconectar el contacto
-Verificar en la lista de contactos de la bitcoin wallet (aun saldrá reflejado)
-Ir a Browse de la Community a iniciar la reconexion con el contacto desconectado
-Darle click y saldrá User Offline
-Ir a la lista de contacto de nuevo y entrar al detalle del contacto desconectado
-Solicitarle BTC por un Payment Request (se podrá enviar payment)

##### Inserta Archivo aLogcat: 

Inicio aproximado de la prueba 
3:00pm 

Envío de payment a contacto desconectado
3:22pm

Logcat
 [log desconexion.zip](https://github.com/Fermat-ORG/beta-testing-program/files/435539/log.desconexion.zip)

  ------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17945197/de8f3d60-6a10-11e6-8bfe-3c757c7fea0a.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  @sanro14  @AdryCanonico  Aclaro sobre este caso que al borrar una conexion con un wallet user si ya estaba en contactos de la wallet este no va  a desaparecer.
El resto del reporte se revisara.

**Comment by nattyco** [comment]
@maydiamc  verificar en la version 22.7 de la apk

**Comment by franciscoj961** [comment]
En la V22.7 Persiste el error ya comentado.
PRUEBA DESDE EMULADOR.

Se elimina la conexion y aun permite interactuar ya sea enviando BTC o Payment requests.

![2608](https://cloud.githubusercontent.com/assets/20245988/18006571/2484933e-6b6e-11e6-8aa9-709291715903.PNG)

![26](https://cloud.githubusercontent.com/assets/20245988/18006614/5ccae554-6b6e-11e6-8327-2cd8ec051932.PNG)

NOTA: El Usuario eliminado de conexiones no aparece en la Browser de la Comunidad de la
de CCP

**Comment by nattyco** [comment]
@franciscoj961  la conexion se elimina del community de CCP, los contactos de la wallet son otra app.

**Comment by franciscoj961** [comment]
El error comentado fue solucionado.
Luego de eliminar la conexion con un usuario permite reenviar conexion.

![error](https://cloud.githubusercontent.com/assets/20245988/18008466/35bdb86c-6b76-11e6-8187-9acfbd43ab3d.PNG)


 

![solucionado](https://cloud.githubusercontent.com/assets/20245988/18008480/46fe375a-6b76-11e6-9bb7-7c1c6c901407.PNG)

**Comment by arosiopr** [comment]
En la V22.7 Error solucionado se puede hacer reconexion con el usuario eliminado. Pero al hacer la reconexión sale con el nombre viejo Ver pantalla 4

**Pantalla 1 Eliminar conexion**
![screenshot_2016-08-26-10-14-11](https://cloud.githubusercontent.com/assets/5313326/18008841/c4864a9a-6b77-11e6-9136-29fad4ae8ef6.png)

**Pantalla 2 confirmar eliminar conexion**
![screenshot_2016-08-26-10-15-05](https://cloud.githubusercontent.com/assets/5313326/18008845/c8203abc-6b77-11e6-94d5-1c6101f95d58.png)

**Pantalla 3 sale de nuevo para agregar en browser**
![screenshot_2016-08-26-10-16-51](https://cloud.githubusercontent.com/assets/5313326/18008848/ce1ae4ee-6b77-11e6-9a0a-e60c239d6fb7.png)

**Pantalla 4 se agrego con el nombre de usuario viejo nuevamente**
![screenshot_2016-08-26-10-28-50](https://cloud.githubusercontent.com/assets/5313326/18008856/d4c017ba-6b77-11e6-91af-949e52a3a130.png)

**Teléfono Físico**

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/18007005/3201ae1e-6b70-11e6-9d20-6641a0f18c57.png)

**Comment by nattyco** [comment]
@maydiamc  @IsbetVR  Verificar en la version 22.8 de la apk

**Comment by JeanFranco498** [comment]
En CCP 22.8 Al realizar la desconexion del contacto se actualiza normalmente en la comunity en la sección de "Conexiones" pero sigue el nombre viejo en la parte de la "bitcoin Wallet"... Agrego que esto se converso en el grupo de testing y se quedo en que aun para esta versión no habían corregido tal error, pero aun así agrego captures para que no se deje pasar el mismo.

Probado desde teléfono físico Samsung Galaxy S3 4.3 Android
 
![screenshot_2016-08-29-09-44-13 1]
(https://cloud.githubusercontent.com/assets/19807906/18056710/118ca3ec-6ddb-11e6-8e21-2b42a3121b4c.png)

![screenshot_2016-08-29-09-43-38 1](https://cloud.githubusercontent.com/assets/19807906/18056720/1d82b8bc-6ddb-11e6-82ab-9d583383a8a5.png)


![screenshot_2016-08-29-09-51-52 1](https://cloud.githubusercontent.com/assets/19807906/18056727/281a8778-6ddb-11e6-9e00-abd6ff633933.png)

![screenshot_2016-08-29-10-59-39 1](https://cloud.githubusercontent.com/assets/19807906/18056748/41de03d8-6ddb-11e6-8c9b-c92ab83113ab.png)

![screenshot_2016-08-29-11-00-24 1](https://cloud.githubusercontent.com/assets/19807906/18056768/529121f6-6ddb-11e6-80ef-c0a982cfb8a6.png)

**Comment by IsbetVR** [comment]
Solucionado el problema de los nombre de los contactos en la community. El error con respecto a los contactos de la bitcon wallet se reportará en un caso nuevo

**Comment by IsbetVR** [comment]
Closed #784
