### ISSUE TITLE
BITCOIN WALLET - REQUEST RECEIVED - SALTO DE LINEA EN MONTO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#786]
#### Nombre pantalla

REQUEST RECEIVED

### Nombre de la Aplicación 

CCP 22.6

-----

##### Reporte de error: 

   *Al ingresar en request received se puede obser var que el monto 0,00025 del contacto Nelson24btc hace salto de línea.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-24-14-32-38](https://cloud.githubusercontent.com/assets/5313326/17946715/7e394940-6a17-11e6-900c-3f6b1d09feee.png)

##### Pasos exactos para reproducir el error:

1. Que un contacto envie un request con un monto con mas de 4 digitos
2. Ingresar a Request Received
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17946842/fed9c250-6a17-11e6-9307-834540057214.png)

**Comment by arosiopr** [comment]
@IsbetVR  @nattyco

**Comment by nattyco** [comment]
@arosiopr verificar en la version 3.0 de la apk

**Comment by arosiopr** [comment]
@IsbetVR  en la version 3.0 de la apk se soluciono el error

![screenshot_2016-09-05-15-37-59](https://cloud.githubusercontent.com/assets/5313326/18256180/e4a4f334-737f-11e6-90eb-ae125a08c9fe.png)

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/18256183/ebc4c6bc-737f-11e6-82a1-daee61a09bdc.png)

**Comment by kmiloxvii** [comment]
en la nueva versión 3.0 de la ccp no me sucede, se muestra bien el monto si saltarse de linea

![prueba](https://cloud.githubusercontent.com/assets/2491042/18256192/05c00bb2-7380-11e6-8c9b-c878b3205478.png)

Dispositivo de prueba 
Emulador

![phone](https://cloud.githubusercontent.com/assets/2491042/18256207/2bbff980-7380-11e6-81ea-d06bd6bf647a.png)

**Comment by IsbetVR** [comment]
Closed #786
