### ISSUE TITLE
Community_CCP_Botón delete all contact, en conexiones, no funciona

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#787]
#### Nombre pantalla
Connections

### Nombre de la Aplicación 
Community CCP Version 22.6

-----

##### Reporte de error: 

   *El botón delete all contact de la pantalla de conexiones, al ingresar arroja un aviso y al darle OK no cumple su función.

##### Screenshot o Capture de pantalla:

![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/17970932/910bb82a-6aa6-11e6-9f09-becbb016d37a.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/17970937/959154fe-6aa6-11e6-9a2c-6e21130f0008.png)

##### Pasos exactos para reproducir el error:

- Ingresar a la Community de CCP
- Ir a la pantalla de conexiones
- Darle click a los 3 puntos
- Presionar Delete all contacts
- Leer el aviso y darle OK (no funciona)
- Darle Cancelar (si funciona)

##### Inserta Archivo aLogcat: 

Hora 9:26 am aproximadamente
 [log delete all contact.zip](https://github.com/Fermat-ORG/beta-testing-program/files/437136/log.delete.all.contact.zip)

  ------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 ![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/17971030/0d5bbe3e-6aa7-11e6-86b5-0e655ffd27dc.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  verificar en la version 22.7 de la apk

**Comment by wendyduran90** [comment]
En la versión 22.7 no sucede este error , el botón funciona perfectamente . La prueba se realizo desde un móvil con versión de android 4.4.4 marca BLU modelo life one 2015.

**Comment by andreagmarcano** [comment]
En la version 22.7 no persiste el error. El boton de "Delete all contacts" funciona sin ningun problema. 
![captura1](https://cloud.githubusercontent.com/assets/18452495/18006140/323ebfba-6b6c-11e6-914b-643a4e4fbf25.PNG)

**Comment by IsbetVR** [comment]
Closed #787
