### ISSUE TITLE
COMMUNITIES - CCP - NOTIFICATIONS - TEXTO DE SOLICITUD CORTADO

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#788]
#### Nombre pantalla

NOTIFICATIONS

### Nombre de la Aplicación 

CCP 22.6

-----

##### Reporte de error: 

   *Al ingresar a CCP en notifications se puede observar que el texto que dice hace cuanto tiempo te enviaron la conexión se corta.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-25-09-15-33](https://cloud.githubusercontent.com/assets/5313326/17970682/a1bfdd28-6aa5-11e6-85a1-213f32f00ca9.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a CCP
2. Ir a la sección Notifications
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17971240/f77f0f52-6aa7-11e6-9148-8fc5493bf3da.png)

**Comment by arosiopr** [comment]
@IsbetVR @nattyco

**Comment by nattyco** [comment]
verificar en la version 3 de la apk

**Comment by arosiopr** [comment]
@IsbetVR  solucionado en la version 3 de la apk

![screenshot_2016-09-05-16-47-51](https://cloud.githubusercontent.com/assets/5313326/18256794/39adef04-7388-11e6-9e50-ce12636de459.png)

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/18256798/472edcba-7388-11e6-9963-19c2a449e729.png)

**Comment by IsbetVR** [comment]
Closed #788
