### ISSUE TITLE
PROFILES - INTRA USER IDENTITY - TEXTO CORRIDO EN POP UP DE AYUDA

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#789]
#### Nombre pantalla

INTRA USER IDENTITY

### Nombre de la Aplicación 

CCP 22.6

-----

##### Reporte de error: 

Al ingresar a crear perfil o al presionar en ayuda del perfil de wallet user se puede observar que el segundo asteriso "*" está  corrido un poco hacia la derecha.

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-25-10-15-34](https://cloud.githubusercontent.com/assets/5313326/17974496/5699d83a-6ab4-11e6-8b6f-8d8131b3a42a.png)

##### Pasos exactos para reproducir el error:

1. Entrar a Profiles wallet users
2. Observar pop up de bienvenida 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![especificaciones alcatel](https://cloud.githubusercontent.com/assets/5313326/17974537/7bf8ca78-6ab4-11e6-8250-f5da992da616.png)

**Comment by arosiopr** [comment]
@IsbetVR  @nattyco

**Comment by nattyco** [comment]
@arosiopr  verificar en la version 22.7 de la apk

**Comment by maydiamc** [comment]
en la versión 22. 7 sigue sucediendo en emulador.

![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/18006067/cbe8ed1c-6b6b-11e6-987a-5aa1ef18c90f.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/18006077/d603c132-6b6b-11e6-8aec-f68a26c3d078.png)

**Comment by wendyduran90** [comment]
En la versión 22.7 persiste el error . La prueba se realizo desde un móvil con versión de android 4.4.4 marca BLU modelo Life One 2015 .
![screenshot_2016-08-26-09-04-19](https://cloud.githubusercontent.com/assets/20212920/18006210/8ac74008-6b6c-11e6-91f8-ddbb6f9d0c9c.jpg)

**Comment by nattyco** [comment]
Verificar en la version 22.8 de la apk

**Comment by marielis-urbina** [comment]
En la versión 22,8 de CCP, este error no sucede en mi emulador

![intra](https://cloud.githubusercontent.com/assets/19353722/18051884/37e1263c-6dc5-11e6-8957-786422441527.png)

![nexus 4](https://cloud.githubusercontent.com/assets/19353722/18051892/48ce4ec0-6dc5-11e6-92da-18b228510603.png)

**Comment by JeanFranco498** [comment]
Versión CCP 22.8 solucionado 
Probado desde teléfono físico 


![screenshot_2016-08-29-08-44-17](https://cloud.githubusercontent.com/assets/19807906/18051913/d324a2ec-6dcd-11e6-9e0d-2a3656ff3a3f.png)
