### ISSUE TITLE
Bitcoin Wallet - Permite hacer transacciones con contactos desconectados por la community

### ISSUE THREAD

**Issue by franciscoj961** [Fermat-ORG/beta-testing-program#790]
#### Nombre pantalla

Contactos de BitcoinWallet

### Nombre de la Aplicación 

BitcoinWallet

-----

##### Reporte de error: 

Luego de realizar una desconexion con un usuario en la Comunidad de la Crypto Wallet sigue permitiendo interactuar con dicho contacto, ya sea enviando BTC o Payment request, en vez de dar una notificacion de que no existe conexion con ese contacto o bien no aparecer en tu lista.. 

##### Screenshot o Capture de pantalla:

 ![2608](https://cloud.githubusercontent.com/assets/20245988/18010745/d88fcc2a-6b7f-11e6-9020-55b08f784499.PNG)

![26](https://cloud.githubusercontent.com/assets/20245988/18010761/e866fc40-6b7f-11e6-86dc-7c091f15412b.PNG)

##### Pasos exactos para reproducir el error:
1) Desconectar la conexion en Comunidades
2) Buscar e interactuar con el contacto desconectado

##### Inserta Archivo aLogcat: 

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/439587/logcat.zip)

  
------

#### Dispositivo desde donde se realizo la prueba

 Emulador

##### Screenshot o Capture de pantalla:

 
![19088](https://cloud.githubusercontent.com/assets/20245988/18010925/b7637032-6b80-11e6-9c73-23615fbba7a6.PNG)

**Comment by IsbetVR** [comment]
@nattyco porfa el caso que te comentamos que se subiría, con respecto a la desconexión y las transacciones

**Comment by nattyco** [comment]
@franciscoj961  verificar en la version 3.0 de la apk

**Comment by franciscoj961** [comment]
En la versión 3.0 de CCP no persiste el error comentando.

Al quitar la conexión con un contacto este desaparece de tu lista de contactos

**Comment by wendyduran90** [comment]
En la versión 3.0 de CCP no persiste el error, el contacto desaparece de la lista de la bitcoinwallet.

![screenshot_2016-09-05-15-42-38 1](https://cloud.githubusercontent.com/assets/20212920/18256261/e27d8228-7380-11e6-8fec-438b1a3c7a03.png)




![screenshot_2016-09-05-15-52-14](https://cloud.githubusercontent.com/assets/20212920/18256277/1520d25c-7381-11e6-84dc-d8c71310d5f0.png)





Está prueba se realizo en teléfono físico con android 4.4.4

**Comment by IsbetVR** [comment]
Closed #790
