### ISSUE TITLE
Bitcoin Wallet - Contact Detail - Dirección de billetera sale cortada

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#791]
#### Nombre pantalla

Contact Detail 

### Nombre de la Aplicación 

CCP

-----

##### Reporte de error: 

Haciendo una prueba, desde el telefono fisico, en la versión 22.8 de la CCP, al seleccionar un contacto para enviar o solicitar btc, la dirección de la billetera sale cortada, no permite hacer  scroll.  

##### Screenshot o Capture de pantalla:

![screenshot_2016-08-29-08-55-05_720](https://cloud.githubusercontent.com/assets/17262077/18053524/e53a4388-6dcd-11e6-90b7-6dece0e26092.png)

##### Pasos exactos para reproducir el error:

- Abrir la Bitcoin Wallet 
- Ir a contactos y seleccionar un contacto

------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18053583/2e40dc54-6dce-11e6-8936-e7b33a9c43cb.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by nattyco** [comment]
verificar en la version 3.0 de la apk

**Comment by Gabymorillo** [comment]
Desde el telefono fisico, ya no persiste este error, se muestra completa la dirección de la billetera. 

![screenshot_2016-09-05-14-29-24_720](https://cloud.githubusercontent.com/assets/17262077/18256234/7eb0f798-7380-11e6-85e5-6b7cb4607ba3.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18256236/81f2bffe-7380-11e6-883b-e4b7c0efc014.png)

**Comment by IsbetVR** [comment]
Closed #791
