### ISSUE TITLE
Bitcoin Wallet - Contacts - No actualiza el nombre del perfil del contacto luego de haber establecido conexión

### ISSUE THREAD

**Issue by IsbetVR** [Fermat-ORG/beta-testing-program#793]
### CCP v22.8

-----

##### Reporte de error: 

   *Una vez establecida la conexión con un usuario a través de la community, si el usuario cambia el nombre del perfil, en la community actualiza el nombre en "Conections" (Pantalla 1), así como en el detalle de las transacciones del home de la bitcoin wallet, que se hizo con dicho contacto (Pantalla 2). Pero en "Contacts" no está actualizando aún el nombre del perfil del contacto (Pantalla 3). De igual manera hago envíos (Pantalla 4) y en el home muestra en el detalle de la transacción con el nombre nuevo, como se mostró en la pantalla 2

##### Pantalla 1

![screenshot_2](https://cloud.githubusercontent.com/assets/19142276/18058275/9f5f6474-6de1-11e6-85fa-b7bf2bdc3905.jpg)

##### Pantalla 2

![screenshot_7](https://cloud.githubusercontent.com/assets/19142276/18058536/d890785e-6de2-11e6-942e-a2fc7c392126.jpg)

##### Pantalla 3

![screenshot_4](https://cloud.githubusercontent.com/assets/19142276/18058311/c3939838-6de1-11e6-8a3e-661bdca0138f.jpg)

##### Pantalla 4

![screenshot_6](https://cloud.githubusercontent.com/assets/19142276/18058627/2b20b53e-6de3-11e6-8ea0-42f281ad878c.jpg)

------

##### Pasos exactos para reproducir el error:

1. El día 24/08/2016 establecí conexión con el usuario "adriWallet2408"
2. Ese mismo día le hice un envío por 0.0318 tal como se muestra en la pantalla 2
3. Para el día de hoy 29/08/2016, ella cambió el nombre del perfil a "adriWallet2908" y en la community de CCP se actualizó el nombre, así como en el detalle de las transacciones mostradas en la pantalla 2, pero en contactos el perfil permanece con el nombre viejo. 
4. Aún así le hice un envio, como se mostró en la pantalla 4, y en el detalle del "SENT" en el home muestra el nombre actualizado

------

##### Inserta Archivo aLogcat: 

[genymotion-log.zip](https://github.com/Fermat-ORG/beta-testing-program/files/442897/genymotion-log.zip)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- HTC One X
- Android 4.1.1
- API 16 - 720x1280
- 320 dpi

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/18058761/d6b82404-6de3-11e6-9073-d26a82460046.jpg)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by nattyco** [comment]
@IsbetVR  verificar en la version 3.0 de la apk

**Comment by andreagmarcano** [comment]
En la version CCP-v3.1 no persiste el error. 

Hay una transaccion registrada antes que el usuario cambiara el nombre. 
![manu](https://cloud.githubusercontent.com/assets/18452495/18288136/3015aa5c-7448-11e6-81e8-76f54773b5f0.PNG) hay una transaccion registrada antes que el usuario cambiara el nombre. 

El usuario cambio el nombre hizo un envio y aparece la transaccion con el nombre actualizado. 
![manu tarde 2](https://cloud.githubusercontent.com/assets/18452495/18288209/720368be-7448-11e6-8286-2873dc4a477f.PNG)

En las transacciones anteriores en el sent, modificó el nombre. 
![manu send](https://cloud.githubusercontent.com/assets/18452495/18288261/a73a2d38-7448-11e6-8ce0-f19fd4d3434f.PNG)

**Comment by IsbetVR** [comment]
Solucionado

**Comment by IsbetVR** [comment]
Closed #793
