### ISSUE TITLE
CHAT - ERROR DE RECOVERING FROM SYSTEM 

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#795]
#### Nombre pantalla
En cualquier pantalla de Chat (nodo nuevo)

### Nombre de la Aplicación 

Chat

##### Reporte de error: 
Probando desde un dispositivo físico desde que instalé la apk recibí mensajes constantes de "Recovering from system error". Específicamente durante las siguientes horas: 9:02am/9:10am/10:08am, lo que me dificultó la creación del perfil y la realización de las pruebas durante algún tiempo.

  

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-02-09-07-31](https://cloud.githubusercontent.com/assets/17261437/18210560/a1d5610a-7128-11e6-8b29-298bf65eb676.png)

![screenshot_2016-08-24-09-57-59](https://cloud.githubusercontent.com/assets/17261437/18210580/b4ebf48e-7128-11e6-8f55-a9d2e3b45763.png)

##### Pasos exactos para reproducir el error:

- Entrar a la aplicación inmediatamente después de instalarla.

- Disponerse a crear cualquier perfil

- Salir y entrar de nuevo en la aplicación.

- Entrar a la Community.

![screenshot_2016-08-24-09-57-59](https://cloud.githubusercontent.com/assets/17261437/18210695/52d0ff96-7129-11e6-85d8-1df56259a2dc.png)
Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB

**Comment by AdryCanonico** [comment]
@franklinmarcano1970

**Comment by josejcb** [comment]
Pasen log de este caso. parece particular de este tlf.

**Comment by josejcb** [comment]
Se puede unificar con el Fermat-ORG/beta-testing-program/issues/801, ambos son RFSE, y pensamos están relacionados, suban el log de alguno para verificarlo.

**Comment by nelsondb** [comment]
Solucionado en la versión 1.7 de chat.

**Comment by IsbetVR** [comment]
Closed #795
