### ISSUE TITLE
CHAT- ERROR EN CONEXIONES DE PERFILES DE CONTACTOS ELIMINADOS

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#796]
#### Nombre pantalla

P2P Chat Community

### Nombre de la Aplicación 

Chat - Versión 1.1 del nuevo nodo

-----

##### Reporte de error: 

Establecí conexión con un usuario (dianey ch 6916m) y luego de intercambiar mensajes me dirijo a la Community donde me desconecto de ese usuario (imagen 1), al ya haberlo eliminado de mis contactos actualizo la Community y me sale ese usuario con la opción de agregarlo nuevamente (imagen 2), al seleccionar la opción de agregarlo el sistema me dice que la solicitud ha sido enviada (imagen 3 y 4), pero el estatus de la solicitud nunca cambia y queda como si no le hubiera enviado dicha solicitud (imagen 5), al contacto en cuestión le llegan notificaciones de solicitudes de conexión pero cuando se dirije a "Notificaciones" no le sale ningún contacto para aceptarlo.

##### Screenshot o Capture de pantalla:

Imagen 1:
![screenshot_17](https://cloud.githubusercontent.com/assets/19883115/18279134/6b88c946-7422-11e6-9825-00def9e6c895.png)
Imagen 2:
![screenshot_18](https://cloud.githubusercontent.com/assets/19883115/18279175/a2c023d2-7422-11e6-9389-5fa0a85a7059.png)
Imagen 3
![screenshot_19](https://cloud.githubusercontent.com/assets/19883115/18279207/bc4bd3aa-7422-11e6-8d07-d8cd905ca367.png)
Imagen 4
![screenshot_20](https://cloud.githubusercontent.com/assets/19883115/18279238/cf731510-7422-11e6-94d5-640230960604.png)
Imagen 5:
![screenshot_21](https://cloud.githubusercontent.com/assets/19883115/18279246/d6e7af04-7422-11e6-87ab-961fc5afe613.png)

##### Pasos exactos para reproducir el error:

1 Agregar nuevo contacto en la Community.
2 Eliminar el usuario de mis contactos.
3 Volver a enviar solicitud de conexión al contacto eliminado.
4 Revisar estatus de envío de conexión.
##### Inserta Archivo aLogcat: 

 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/457030/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_22](https://cloud.githubusercontent.com/assets/19883115/18279531/e3a3c222-7423-11e6-89ce-50e0abe797cd.png)

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by maydiamc** [comment]
En la version 1.3 de Chat sigue sucediendo el error

Captures de prueba con usuario NinaChat07
![screenshot_1](https://cloud.githubusercontent.com/assets/17274154/18315872/8903fd96-74e6-11e6-9692-1dee9a4db3e2.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/18315877/8b9401aa-74e6-11e6-84fc-bcbf34b91dbc.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/18315885/944d335c-74e6-11e6-90fa-589da8a2bfc4.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/18315892/9d06e4d4-74e6-11e6-9e36-18119be24fb8.png)

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/18315917/af4b9dba-74e6-11e6-9d83-390860b08246.png)

**Comment by arosiopr** [comment]
@MaviDavsa  solucionado en la versión 1.4 de chat 

Teléfono Físico

![alcatel](https://cloud.githubusercontent.com/assets/5313326/18325808/0bb6b0e2-7511-11e6-9e6a-19dfbc0e20a5.png)

**Comment by GeronimoVierma** [comment]
En la versión 1.4 de chat el error esta solucionado:
Emulador
![4 1](https://cloud.githubusercontent.com/assets/19883115/18325836/2cb74392-7511-11e6-8569-95222c617d52.png)
