### ISSUE TITLE
CHAT - BLOQUEA CONTACTOS AL CANCELAR CONEXIÓN 

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#797]
#### Nombre pantalla

Comunity Chat 

### Nombre de la Aplicación 

CHAT 

-----

##### Reporte de error: 

   *Al cancelar una conexion en la comunity el mismo contacto al que se ha cancelado la conexión se bloquea automáticamente sin preguntar.. Es decir no puede enviar ni recibir conexiones de esa persona 

##### Screenshot o Capture de pantalla:

![prueba 1 o6](https://cloud.githubusercontent.com/assets/19807906/18280232/59d00454-7426-11e6-8790-c553d4fbda4f.jpg)

![prueba 1 o6 3](https://cloud.githubusercontent.com/assets/19807906/18280149/16d5e0ce-7426-11e6-9428-2a1c0325782d.jpg)

![asdasdsdfsdf](https://cloud.githubusercontent.com/assets/19807906/18280156/2165e69c-7426-11e6-85eb-0929f983324c.jpg)

##### Pasos exactos para reproducir el error:

1. Abrir la pestaña de notificacion
2. Dar click en la notificacion
3. Ir a la pantalla de notificaciones
4. Cancelar la solicitud de conexión
5. Ir A browser
6. Tratar de enviar nuevamente una conexion 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/457110/logcat.txt)

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![image](https://cloud.githubusercontent.com/assets/19807906/18280357/c828913c-7426-11e6-8951-780c7e5924cd.png)

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by josejcb** [comment]
Se pensó bloquear contacto al negar la conexión, así no volvería a molestar enviando de nuevo solicitudes haciendo spam. Hagamos sugerencias para irlas manejando para la próxima versión de la app. @MaviDavsa @JeanFranco498

**Comment by josejcb** [comment]
Para esta versión se quitara esta opción, para que no se bloqueen los contactos por error humano y no incomoda al usuario final. Para una próxima versión manejaremos esta opción.

**Comment by maydiamc** [comment]
En la version 1.5 de chat, esto se soluciono, al cancelar la solicitud, el contacto no se bloquea, es posible recibir una nueva conexion.! 

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/18365426/a7815426-75e0-11e6-93d6-5da5aff2b4d1.png)

**Comment by MaviDavsa** [comment]
Solucionado!
