### ISSUE TITLE
Chat - La opción de Borrar Todos las conversaciones no funciona

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#798]
##### Reporte de error: 

   * En el momento de estar en la pantalla de Chat y querer borrar todas las conversaciones, la opción no funciona.

##### Screenshot o Capture de pantalla:

![chat completo](https://cloud.githubusercontent.com/assets/19353722/18280464/1444bcbc-7427-11e6-9ebc-0cc02ad15a7b.png)

![no borra](https://cloud.githubusercontent.com/assets/19353722/18280489/27823426-7427-11e6-80ee-e1c5fdb87362.png)

##### Pasos exactos para reproducir el error:
 - En el home del Chat, busco la opción de borrar todas las conversaciones
 - Le doy Clip al botón de borrar
 - Resultado, no funciona, tengo que hacerlo uno por uno.
 
##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/457119/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![nexus 5 1](https://cloud.githubusercontent.com/assets/19353722/18280690/e8316c00-7427-11e6-8317-39cf3d03ca08.png)

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by nelsondb** [comment]
Solucionado en la versión 1.3.

**Comment by marielis-urbina** [comment]
En la versión 1.3 de Chat, no sucede este error en mi emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/18290982/b95094a2-7453-11e6-8446-192fc1fec6aa.png)
