### ISSUE TITLE
Chat - La opción de limpiar Chat, borra el Chat

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#799]
##### Reporte de error: 

   *Al limpiar la conversación de mi conexión, también borra el Chat del Home.

##### Screenshot o Capture de pantalla:

![wen](https://cloud.githubusercontent.com/assets/19353722/18280916/e925ddf2-7428-11e6-9b16-5882070b26bf.png)

![borra](https://cloud.githubusercontent.com/assets/19353722/18280872/c378308c-7428-11e6-8b03-bf8941a69b08.png)

##### Pasos exactos para reproducir el error:

- Entro en la conversación del Chat
- Le doy Clip a la opción de borrar conversación
- Al regresar no tengo el Chat del contacto.

##### Inserta Archivo aLogcat: 

 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/457154/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![nexus 5 1](https://cloud.githubusercontent.com/assets/19353722/18281065/6a85a940-7429-11e6-9655-61255e751cf9.png)

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by marielis-urbina** [comment]
En la versión 1.3 de Chat, no sucede este error en mi emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/18290795/e258075a-7452-11e6-9620-8b71711117d1.png)

**Comment by nelsondb** [comment]
Versión 1.3, el error ha sido solucionado.
