### ISSUE TITLE
Sign Up Application for Beta Tester

### ISSUE THREAD

**Issue by rubiborjas** [Fermat-ORG/beta-testing-program#8]
Hola, @beta-testing-program-team
Quiero unirme al equipo de Beta Tester Program.
Mi nombre es Rubí Andrea Borjas Sánchez, soy venezolana.
Teléfonos: 0414-6381085 / 0261-7548517
Correo electrónico: rubiborjas13@gmail.com
Maracaibo, Estado Zulia.

**Comment by augusto-ponce** [comment]
Por favor para poder distinguirnos mejor entre todas las personas que van presentando  los casos es necesario agregar una foto de perfil en este programa.
