### ISSUE TITLE
Bit Coin Wallet_ Requests

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#80]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla
Send Request to Contact

### Bitcoin Wallet 

-----

##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *El error es que cuando voy a hacer el pago, no hace absolutamente nada, por lo tanto no se si el error es a la hora de poner las cantidades o el contacto, pero no me deja hacer los pagos. 
   
![error](https://cloud.githubusercontent.com/assets/17273005/13786124/7ab7da82-eaa8-11e5-9f71-b8dae0aa0749.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: 5.0

**Comment by nattyco** [comment]
@MaviDavsa probar si se corrigio en la ultima version
