### ISSUE TITLE
CHAT - Borra el contenido de conversaciones y perfil cuando se vuelve a usar el dispositivo

### ISSUE THREAD

**Issue by gablup** [Fermat-ORG/beta-testing-program#800]
### Template issue error report
 Borra el contenido de conversaciones y perfil cuando se vuelve a usar el dispositivo

#### Nombre pantalla
P2P CHAT

### Nombre de la Aplicación 
CHAT

##### Reporte de error: 

En varias oportunidades, al permanecer en la pantalla de P2P CHAT (sin usar la app durante un tiempo hasta que se apague la pantalla del celular), cuando se accede nuevamente a una conversación con uno de los contactos, el contenido del chat no aparece y al presionar el botón de "atrás" del teléfono, salen mensajes de bienvenida para la creación de una nueva identidad, como si no se hubiese creado ninguna anteriormente.

Nota: Para que la aplicación volviera a la normalidad fue necesario salir y entrar de nuevo a la aplicación.

##### Screenshot o Capture de pantalla:
![issue 1](https://cloud.githubusercontent.com/assets/17261437/18290772/55854258-7474-11e6-82b9-2973ece524e3.png) (Pantalla 1)

![issue 2](https://cloud.githubusercontent.com/assets/17261437/18290854/9a386e02-7474-11e6-99aa-3ffbea8066f6.png) (Pantalla 2)

![issue 3](https://cloud.githubusercontent.com/assets/17261437/18290865/ac3573de-7474-11e6-892c-e57963ea9749.png) (Pantalla 3)

![issue 4](https://cloud.githubusercontent.com/assets/17261437/18290883/bfc12e52-7474-11e6-9c5b-8075c55e700c.png) (Pantalla 4)

![issue 5](https://cloud.githubusercontent.com/assets/17261437/18290905/dbd7af6c-7474-11e6-97a7-56328c25f756.png) (Pantalla 5)

##### Pasos exactos para reproducir el error:

1) Quedarse en la pantalla de P2P CHAT (donde está la lista de las conversaciones con los contactos)

2) No usar el teléfono hasta que la pantalla del dispositivo se apague.

2) Una vez apagada la pantalla, volver a usar el teléfono y entrar en una de las conversaciones del chat.

3) Al ver que el contenido de la conversación se borró por completo, darle al botón de "atrás" del teléfono, donde saldrán los respectivos mensajes para la creación de una nueva identidad, como si no se hubiese creado ninguna.
  
#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:
![screenshot_2016-08-24-09-57-59](https://cloud.githubusercontent.com/assets/17261437/18289817/899af91a-7470-11e6-848f-1584adebfea8.png)

Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,81 GB.
Memoria interna Disponible: 242 MB.

**Comment by JeanFranco498** [comment]
Probando este error sucedió 2 veces en este teléfono físico  Samsung Galaxy S3 i9300L 

Con este logcat no dejo de funcionar pero hice forzar detencion y el perfil volvio a aparecer y todo en conexiones y chats estaba normal 

[Log_2016-9-07_10-50-25[1].txt](https://github.com/Fermat-ORG/beta-testing-program/files/459555/Log_2016-9-07_10-50-25.1.txt)



a las 11:10 Fermat dejo de funcionar al tratar de cerrar el wizard de bienvenida 
Luego al entrar en la app nuevamente todo estaba normal, en conexiones y chats 

[Log_2016-9-07_11-10-26[1].txt](https://github.com/Fermat-ORG/beta-testing-program/files/459533/Log_2016-9-07_11-10-26.1.txt)

**Comment by arosiopr** [comment]
Versión 1.3 de CHAT 
El error reportado se presenta en mi dispositivo siguiendo los pasos indicados.


![screenshot_2016-09-07-11-07-00](https://cloud.githubusercontent.com/assets/5313326/18317777/16907864-74ed-11e6-9b3a-20aa8b354b4b.png)

![screenshot_2016-09-07-11-09-09](https://cloud.githubusercontent.com/assets/5313326/18317802/31031b02-74ed-11e6-9bc2-97fe81c2af00.png)

![screenshot_2016-09-07-11-10-02](https://cloud.githubusercontent.com/assets/5313326/18317830/487a8a4a-74ed-11e6-82aa-31b9ef4cd793.png)

![screenshot_2016-09-07-11-10-37](https://cloud.githubusercontent.com/assets/5313326/18317833/4c2ccc98-74ed-11e6-8b8b-3e5ca3cb4528.png)

![screenshot_2016-09-07-11-10-50](https://cloud.githubusercontent.com/assets/5313326/18317839/51efdc92-74ed-11e6-8a6f-3b37396d47ef.png)

## **Teléfono Físico**
![alcatel](https://cloud.githubusercontent.com/assets/5313326/18317729/e14a5e22-74ec-11e6-983a-f5d6e6032e0b.png)

## **LOGCAT**
[Log_2016-9-07_11-12-19.txt](https://github.com/Fermat-ORG/beta-testing-program/files/459543/Log_2016-9-07_11-12-19.txt)

**Comment by gablup** [comment]
Ya no ocurre el error en la versión de CHAT 1.6, después de verificar varias veces. Favor cerrar el caso, al comprobar que ya se solucionó por completo.

**Comment by IsbetVR** [comment]
Closed #800
