### ISSUE TITLE
 Chat-Profile-Error al tomar foto desde la cámara

### ISSUE THREAD

**Issue by wendyduran90** [Fermat-ORG/beta-testing-program#801]
#### Nombre pantalla
P2P-chat Profile

### Nombre de la Aplicación 
Chat

-----

##### Reporte de error: 

   Cuando se toma la foto directamente de la camara para crear el perfil , aparece recovering from system error y el logo de Fermat.

Hora del error 3:20 pm 
Versión 1.8 chat 

##### Screenshot o Capture de pantalla:

![1](https://cloud.githubusercontent.com/assets/20212920/18318288/256a1f5a-74ef-11e6-99c0-a7878b85e898.jpg)

![2](https://cloud.githubusercontent.com/assets/20212920/18318272/15770ebe-74ef-11e6-88d4-95f5ec42e748.jpg)

##### Pasos exactos para reproducir el error:

*Entrar a Profiles -chat
*Seleccionar cámara para tomar foto de perfil
*Tomar foto
*Darle aceptar con el símbolo de check 
*Sale el logo de fermat con el aviso de recovering from system error

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/470641/logcat.txt)

 

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:
![screenshot_2016-09-07-11-46-04](https://cloud.githubusercontent.com/assets/20212920/18318835/311ffa3e-74f1-11e6-96c2-06eeb8f5c5f4.jpg)

**Comment by josejcb** [comment]
Suban un log de este caso

**Comment by josejcb** [comment]
Revisado el logcat, no se encuentra nada de Fermat.

**Comment by AdryCanonico** [comment]
Se cerrara el caso para ser agregado el comentario al caso #795

**Comment by MaviDavsa** [comment]
@royGF En el Issues se monto el logcat! Que tu mismo sacaste con Wendy para verificar esta caso ya que sigue pasando!

**Comment by josejcb** [comment]
@furszy creo que este es el caso en que se apagan los plugins

**Comment by wendyduran90** [comment]
@furszy

**Comment by wendyduran90** [comment]
En la versión 2.0 sigue sucediendo este error . 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/472250/logcat.txt)

**Comment by wendyduran90** [comment]
En la versión 2.3 de chat. No persiste el error . Las pruebas se realizaron desde un móvil con versión de Android 5.0 marca Blu, modelo Life One 2015
