### ISSUE TITLE
BITCOIN WALLET- REQUESTS: LAS HORAS DE LOS RECEIVED NO ESTA ACTUALIZADA

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#802]
#### Nombre pantalla
Requests

### Nombre de la Aplicación 
CCP 3.2

Estando en pantalla de request, received para verificar un envio de Camilo y otro de Frank, pude observar que uno de los requests recibidos (el de camilo tenia la hora que no correspondía) eran las 3:10 aproximadamente y el request decia que se realizo en la mañana y el no realizo pruebas en la mañana con nuestro grupo.
Foto de mi celular
![screenshot_2016-09-07-15-15-29](https://cloud.githubusercontent.com/assets/17283358/18326103/3ff4f32c-7512-11e6-8081-fc3fc3ed9780.png)

Foto de camilo
![yoli](https://cloud.githubusercontent.com/assets/17283358/18326265/fead043a-7512-11e6-9621-94b93c42c29b.png)

Foto de Isbet
![is](https://cloud.githubusercontent.com/assets/17283358/18326809/a2cb455c-7515-11e6-8a54-b3e0f411fc63.png)

 *Agregar las capture del error en el emulador o teléfono donde se produjo. 

##### Pasos exactos para reproducir el error:
1 Solicitud a dos compañeros envíos de requests
2 Recibi los dos requests  Camilo y Francisco
3 El de Camilo aparece con hora que no corresponde es aproximadamente a la de Francisco, como se observa en la foto.
4 Isbet solicitó a Camilo requests.

##### Inserta Archivo aLogcat: 

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico
![screenshot_2016-09-06-15-20-35](https://cloud.githubusercontent.com/assets/17283358/18326000/daac21ca-7511-11e6-92aa-1c38dd8ef764.png)

##### Screenshot o Capture de pantalla:

 *Agregar las capture de la descripcion del emulador o teléfono.

**Comment by IsbetVR** [comment]
@nattyco

**Comment by IsbetVR** [comment]
#### CCP-v3.2

En mi caso, me llegó un payment de "CamiloWallet0709" a las 15:23 hs aproximadamente, y en los Payment Request-Received me sale las 11.22 hs (Pantalla 1), caso contrario con el contacto "GabyM T07", según la notificación (Pantalla 2) me llegó a las 15:33 hs y en el Payment Request-Received me sale las 16:02 hs (Pantalla 3)

#### Pantalla 1

![screenshot_37](https://cloud.githubusercontent.com/assets/19142276/18326742/4d258112-7515-11e6-8aca-7cd1e2a9ecbc.jpg)

#### Pantalla 2

![screenshot_39](https://cloud.githubusercontent.com/assets/19142276/18326736/43418ca4-7515-11e6-9d0c-464d0931f203.jpg)


#### Pantalla 3

![screenshot_40](https://cloud.githubusercontent.com/assets/19142276/18326725/39b102fa-7515-11e6-99f3-4d9281beffa1.jpg)

#### Archivo logcat (Mi dispositivo)

[genymotion-log802.zip](https://github.com/Fermat-ORG/beta-testing-program/files/460232/genymotion-log802.zip)

#### Archivo logcat (Dispositivo de @kmiloxvii (CamiloWallet0709) )

[Samsung Galaxy S4 - 4.2.2 - API 17 - 1080x1920-logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/460234/Samsung.Galaxy.S4.-.4.2.2.-.API.17.-.1080x1920-logcat.zip)

#### Dispositivo de prueba
- [x] Emulador
- Goolge Nexus 4
- Android 4.3
- API 18

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/18326857/bbb8b1c6-7515-11e6-82af-201387a81953.jpg)

**Comment by nattyco** [comment]
@yolandayancel  @IsbetVR  verificar en la version 3.3 de la apk

**Comment by yolandayancel** [comment]
Prueba 08-09-16
Caso 802
CCP V3.3
Solucionado lo de las horas como se aprecia en dos  Received
![screenshot_2016-09-08-11-09-20](https://cloud.githubusercontent.com/assets/17283358/18355116/2c7fd1be-75b6-11e6-92c8-a1085b86a77e.png)

![screenshot_2016-09-06-15-20-35](https://cloud.githubusercontent.com/assets/17283358/18355096/16e61d36-75b6-11e6-82ca-ff49a462a841.png)

**Comment by IsbetVR** [comment]
Con la versión CCP-v3, en mi dispositivo también solucionado. Ya muestra la hora actualizada en el payment de acuerdo a la hora del dispositivo

#### Pantalla 1

![screenshot_52](https://cloud.githubusercontent.com/assets/19142276/18355899/b0b9067e-75b8-11e6-9cc1-f24750769bf4.jpg)

#### Dispositivo de pruebas
- [x] Emulador
- Google Nexus 4
- Andoird 4.3 

![google nexus 4 - 4 3](https://cloud.githubusercontent.com/assets/19142276/18355951/e2ce9ae8-75b8-11e6-8a4b-26d6d95aaa11.jpg)

**Comment by IsbetVR** [comment]
Closed #802
