### ISSUE TITLE
Bitcoin Wallet-Identity Manager-Mensaje de inicio cortado

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#803]
#### Nombre pantalla

Identity Manager

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   *CCP versión 3.3, al entrar en la pantalla (Identity Manager) para crear el perfil el mensaje de inicio aparece cortado y no puedo crear el perfil la app no me deja, tampoco permite scrolear.

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-08-08-50-53](https://cloud.githubusercontent.com/assets/19656830/18351502/6a4ba832-75a8-11e6-92d5-19904ba29e39.png)

##### Pasos exactos para reproducir el error:

1.Ingreso en la pantalla (Identity Manager) para crear el perfil.
2.El mensaje de inicio esta cortado (como se muestra en el capture).
3.Intento scrolear pero no es posible.

 

 

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18351722/4fb45f72-75a9-11e6-9f33-9fe887a117e1.png)

@nattyco

**Comment by danielaporras** [comment]
CCP v 3.4
Pueba en telefono fisico.

- El mensaje de bienvenido sigue cortado (Capture 1)

- Permite scrolear un milimetro (Capture 2)

- Es imposible crear el perfil, la apk no lo permite.

Capture 1
![screenshot_2016-09-08-14-38-20](https://cloud.githubusercontent.com/assets/19656830/18362353/698f6a48-75d3-11e6-8832-144178cf302f.png)

Capture 2
![screenshot_2016-09-08-14-38-29](https://cloud.githubusercontent.com/assets/19656830/18362359/6f53c3f2-75d3-11e6-8ff7-544804ff114b.png)


![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18362363/72e040fe-75d3-11e6-8c41-de35eb3e544a.png)

@nattyco

**Comment by danielaporras** [comment]
Lo comentado en el utimo comentario de este error persiste aun en la version 3.3.3 

![screenshot_2016-09-08-14-38-20](https://cloud.githubusercontent.com/assets/19656830/18387794/ce60750e-766c-11e6-8f4b-7bbe02b35c88.png)


![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18387802/d2384ae4-766c-11e6-828b-05b38691f3a3.png)


 @nattyco

**Comment by Glaurano** [comment]
Persiste el error con la version 3.3.3 en mi dispositivo (Samnsung Galaxy s3 mini)
En mi tamaño de letra normal, me sale cortado el mensaje de bienvenida. No me deja deslizar la pantalla:
![screenshot_2](https://cloud.githubusercontent.com/assets/20232734/18388602/3aea4562-7670-11e6-877d-b7d1a5479d64.png)
Especificaciones del dispositivo:
![dispositivo samnsung galaxy s3 mini](https://cloud.githubusercontent.com/assets/20232734/18388695/a1fe3042-7670-11e6-9dcc-73badbe6465f.png)

**Comment by nattyco** [comment]
@camilavaleria  verificar en la version 3.3.4 de la apk

**Comment by danielaporras** [comment]
Lo comentado en este caso fue solucionado en la version 3.3.4, por favor cerrarlo 

![screenshot_2016-09-09-14-36-20](https://cloud.githubusercontent.com/assets/19656830/18398732/feeff3d2-769b-11e6-848c-66fa335def06.png)

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18398742/0acdb4c8-769c-11e6-90b7-fab7c2a0a010.png)

 @IsbetVR

**Comment by IsbetVR** [comment]
Closed #803
