### ISSUE TITLE
Bitcoin Wallet - Request - Botón para denegar payment no se actualiza.

### ISSUE THREAD

**Issue by RubenSem** [Fermat-ORG/beta-testing-program#804]
# #### Nombre pantalla

## Request

# ### Nombre de la Aplicación 

## Bitcoin Wallet CCP 3.3

-----

##### Reporte de error: 

Al momento de denegar un request y darle al botón *Deny* hace su función mas no lo actualiza por mas tiempo que esperes, la única forma de actualizarlo es haciendo swipe o pasar de pestaña.

##### Screenshot o Capture de pantalla:

![screenshot_26](https://cloud.githubusercontent.com/assets/19676223/18354287/f4067520-75b2-11e6-9206-0ff2ad751825.png)
![screenshot_27](https://cloud.githubusercontent.com/assets/19676223/18354311/0f44b7b6-75b3-11e6-9b77-61268fa2eece.png)

##### Pasos exactos para reproducir el error:

-Ir a Bitcoin Wallet.
-Desplegar menú, ir directo a payment request.
-En la pestaña received darle al botón Deny.
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![screenshot_4](https://cloud.githubusercontent.com/assets/19676223/18354300/043b4fba-75b3-11e6-9cd9-fcf9200b4d82.png)

**Comment by RubenSem** [comment]
@nattyco

**Comment by JeanFranco498** [comment]
En esta misma versión con teléfono físico pasa exactamente lo mismo, la única forma de que desaparezcan por decirlo de algún modo los botones es refrescando o pasando de una pestaña a otra como se muestra en las capturas de pantalla 

![screenshot_2016-09-08-11-06-05](https://cloud.githubusercontent.com/assets/19807906/18354804/f68e1c9c-75b4-11e6-8ada-9781b01a48eb.png)



![screenshot_2016-09-08-11-06-17](https://cloud.githubusercontent.com/assets/19807906/18354805/f6abb0e0-75b4-11e6-98db-71eed3d21693.png)



![screenshot_2016-09-08-11-06-00](https://cloud.githubusercontent.com/assets/19807906/18354803/f639798a-75b4-11e6-9406-5ca6308ed762.png)



![screenshot_2016-09-08-11-07-11](https://cloud.githubusercontent.com/assets/19807906/18354865/2be06652-75b5-11e6-84a9-8a8c24445eae.png)



![screenshot_2016-09-08-11-07-16](https://cloud.githubusercontent.com/assets/19807906/18354864/2bde78ba-75b5-11e6-9975-e39b3b08e4af.png)

**Comment by arosiopr** [comment]
Persiste en la version 3.3.3 de CCP
![screenshot_2016-09-09-09-38-02](https://cloud.githubusercontent.com/assets/5313326/18388954/a7af7040-7671-11e6-9d19-ab38493a0ac7.png)

![screenshot_2016-09-09-09-37-46](https://cloud.githubusercontent.com/assets/5313326/18388945/a2fc6332-7671-11e6-912a-84799a95c224.png)

![screenshot_2016-09-09-09-38-09](https://cloud.githubusercontent.com/assets/5313326/18388961/ace34ac8-7671-11e6-8a9a-315edf47ac64.png)

Telefono Fisico
![alcatel](https://cloud.githubusercontent.com/assets/5313326/18388968/b1f9415c-7671-11e6-8de5-d70aa6c51176.png)

**Comment by Gabymorillo** [comment]
En la versión 3.3.4 de la CCP, al llegar un requests y denegarlo, lo hace, pero sigue apareciedo, se debe cambiar de pestaña a sent y volver a requests para que se actualice. 

![screenshot_2016-09-09-15-10-13_720](https://cloud.githubusercontent.com/assets/17262077/18401345/1a1675b2-76a8-11e6-9f90-8f225672aa5f.png)

![screenshot_2016-09-09-15-10-19_720](https://cloud.githubusercontent.com/assets/17262077/18401348/1b9d8bbe-76a8-11e6-9000-8e83aa6c7d4c.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18401349/1e256cda-76a8-11e6-892f-8e1f4b281e86.png)

**Comment by maydiamc** [comment]
En la version 3.3.4 de CCP sucede el mismo error, al darle denegar o aceptar el boten permanece y es necesario refrescar para que se actualice.

Capture 
![screenshot_2](https://cloud.githubusercontent.com/assets/17274154/18401426/67dfd09a-76a8-11e6-92e7-5a980a490ed1.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/18401427/6a29e58e-76a8-11e6-961c-4bb24aaf7046.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/18401486/96499182-76a8-11e6-86a6-5af3bc48fe4a.png)

**Comment by nattyco** [comment]
@RubenSem verificar en la version 3.3.5 de la apk

**Comment by RubenSem** [comment]
En la versión 3.3.5 de ccp esta solucionado este error, por favor cerrar caso. @IsbetVR @nattyco 
![screenshot_6](https://cloud.githubusercontent.com/assets/19676223/18436609/4e5b0ea2-78c7-11e6-9fff-5a0c9b2a5bf4.png)

**Comment by JeanFranco498** [comment]
En la versión 3.3.5 esta solucionado


![screenshot_2016-09-12-09-06-00 1](https://cloud.githubusercontent.com/assets/19807906/18436949/d1b94182-78c8-11e6-9d05-ffa4dbb4492d.png)


![screenshot_2016-09-12-09-06-08 1](https://cloud.githubusercontent.com/assets/19807906/18436939/c319a040-78c8-11e6-853e-51b9f5194191.png)


![screenshot_2016-09-07-09-25-23 1](https://cloud.githubusercontent.com/assets/19807906/18436978/ebe9a9b6-78c8-11e6-9007-cde994e21b23.png)
