### ISSUE TITLE
Chat- Mensajes superpuestos en pantallas de conversación de chat

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#805]
### Chat APK Version 1.5    
*Reporte del error: Al momento de enviar varios mensajes consecutivos, se puede observar que los mensajes salen superpuestos uno sobre otro.

##### A continuación muestro los capture del error:
![1](https://cloud.githubusercontent.com/assets/5313324/18365888/7648cc0c-75e2-11e6-909e-340c0679fc19.png)
![2](https://cloud.githubusercontent.com/assets/5313324/18365889/765ef806-75e2-11e6-80e7-a570511a33cb.png)
![3](https://cloud.githubusercontent.com/assets/5313324/18365890/76762094-75e2-11e6-8889-149526940f50.png)

 *A continuación el link del vídeo del proceso llevado a cabo. 

https://www.youtube.com/watch?v=Xj1s5EwlBfU

##### Pasos exactos para reproducir el error:
1) entro a una conversación con un contacto.
2)realizamos una conversación con mensajes continuos.
3)se observa el salto en varias ocasiones y los mensajes superpuestos.

#### Dispositivo desde donde se realizo la prueba
Telefono fisico alcatel one idol android 4.4.2

**Comment by andreagmarcano** [comment]
En la version 1.7 de CHAT no persiste el error comentado. 
![f](https://cloud.githubusercontent.com/assets/18452495/18450624/c7b479b6-7901-11e6-9629-9663c4f97f2f.PNG)
![movil](https://cloud.githubusercontent.com/assets/18452495/18450722/1b13f078-7902-11e6-9479-81fa0b6a5972.PNG)
