### ISSUE TITLE
Bitcoin Wallet_ Se desaparecen transacciones al enviar mas de 10 Payment Request

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#806]
#### Nombre pantalla
Sent (Payment Request)

### Nombre de la Aplicación 
Bitcoin Wallet 3.3.4

-----

##### Reporte de error: 

   *Envie un Payment Request, y cuando revise la pantalla de send de este menú, como ya tenia 10 transacciones, se reflejo esta nueva de numero 11, pero la primera transacción se desapareció. 

##### Screenshot o Capture de pantalla:

Transaccion N° 11
![screenshot_5](https://cloud.githubusercontent.com/assets/17274154/18401064/abb4c67e-76a6-11e6-8b20-cb3a64ac3ba5.png)

Transaccion N° 2 (ya que la 1 era se elimino)
![screenshot_6](https://cloud.githubusercontent.com/assets/17274154/18401067/adf37a20-76a6-11e6-81de-7159683c74f4.png)

##### Pasos exactos para reproducir el error:

-Enviar varios payment hasta llegar a 10 en la pantalla de send
-Enviar el payment request N° 11
-Revisar la lista y ver que este ultimo se reflejo
-Revisar la lista y ver que el 1ero que se envio se borro de la lista

##### Inserta Archivo aLogcat: 

3:25pm aprox
[log payment.zip](https://github.com/Fermat-ORG/beta-testing-program/files/464732/log.payment.zip)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico

##### Screenshot o Capture de pantalla:

 ![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/18401232/842d5278-76a7-11e6-9e4e-220823380f49.png)

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@maydiamc  y no te da opcion para seguir bajando en la pantalla?

**Comment by maydiamc** [comment]
@nattyco no natty llega hasta alli, no carga ni hace mas nada

**Comment by maydiamc** [comment]
En la versión 3.3.5 de CCP, en el menu Sent de Payment Request, sucede este error, a partir de envío numero 11 de payment, se desparece una transacción, indiferentemente de cual sea, al enviar una desaparece una y al enviar otro payment nuevo, reaparece la anterior y desaparece otra.

En este caso se desapareció la transacción numero 8, y ya tenia 17 payment enviados
![screenshot_8](https://cloud.githubusercontent.com/assets/17274154/18441811/699b6a8a-78dc-11e6-883b-a661503f9bd8.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/17274154/18441815/6df620ca-78dc-11e6-9fb1-71f21ef77d7a.png)

Emulador
![htc 4 1](https://cloud.githubusercontent.com/assets/17274154/18441820/720aaf1e-78dc-11e6-8727-8f2c5a7b34fe.png)

**Comment by arosiopr** [comment]
El error reportado persiste en la versión 3.3.5 de CCP

Desapareció el Tercer envío del día 09 de Septiembre 

![screenshot_2016-09-12-11-31-48](https://cloud.githubusercontent.com/assets/5313326/18441939/d5dbf0fc-78dc-11e6-8376-29905c437cdc.png)


**Teléfono Físico**

![alcatel](https://cloud.githubusercontent.com/assets/5313326/18441906/b2e9cc2c-78dc-11e6-88e8-5588a05e7d67.png)

**Comment by nattyco** [comment]
@maydiamc verificar en la version 3.3.6

**Comment by Hernandezsmanu** [comment]
En la version ccp- 3.3.6 se soluciono esto, en la sección de Payment request / sent realice 14 envíos y no borro ninguno de los que ya estaba en la lista.

![screenshot_2](https://cloud.githubusercontent.com/assets/5313335/18478197/5595f89e-799e-11e6-99d8-ce8fa923c54f.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/5313335/18478212/68725cd2-799e-11e6-88dd-3c503eec8816.png)

**Comment by camilavaleria** [comment]
En la version 3.3.6 de la CCP, se probo desde mi telefono fisico, y no sudece este error:

 SENT:

![image](https://cloud.githubusercontent.com/assets/18740418/18478592/d2a88b8e-799f-11e6-924e-55899b51fc6a.png)

![image](https://cloud.githubusercontent.com/assets/18740418/18478618/e2c4bb82-799f-11e6-91db-7c9d5eb11e4a.png)


RECEIVED

![image](https://cloud.githubusercontent.com/assets/18740418/18478637/f63b0ffe-799f-11e6-80df-9bca7f1d57ea.png)


![image](https://cloud.githubusercontent.com/assets/18740418/18478659/07229e7c-79a0-11e6-96ad-bf5a4874fcd2.png)


DISPOSITIVO DE PRUEBA

![image](https://cloud.githubusercontent.com/assets/18740418/18478684/1e5fd6ae-79a0-11e6-988f-fa8dcd4bd290.png)

**Comment by IsbetVR** [comment]
Solucionado
Closed #806
