### ISSUE TITLE
COMMUNITY CCP - Notificaciones-  Intercambia la foto de perfil de los contactos

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#807]
#### Nombre pantalla

Notificaciones

### Nombre de la Aplicación 

Bitcoin Wallet CCP 3.3.4

-----

##### Reporte de error: 

Recibí una solicitud de conexión del usuario DaniT09bw, pero la foto de perfil corresponde al usuario yolyccp9T1 como se indica en la imagen número 2. 

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-09-15-19-50_720](https://cloud.githubusercontent.com/assets/17262077/18401598/4228fe0c-76a9-11e6-960e-4f4f0ef70f31.png)

![screenshot_2016-09-09-16-20-11_720](https://cloud.githubusercontent.com/assets/17262077/18401645/7eeba592-76a9-11e6-8aca-9518cc65a1eb.png)

![screenshot_2016-09-09-16-43-10_720](https://cloud.githubusercontent.com/assets/17262077/18402282/b8b1ad1e-76ac-11e6-919f-7cc165c34ed7.png)

##### Pasos exactos para reproducir el error:

- Abrir la apk
- Ir a la community
- Abrir las notificaciones 

 *Detallar paso a paso la forma en  la cual se logro el error.

##### Inserta Archivo aLogcat: 

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18401578/1f860be2-76a9-11e6-91a0-cd4c5f9d092a.png)

 *Agregar las capture de la descripcion del emulador o teléfono.

**Comment by nattyco** [comment]
@Gabymorillo  sabes que foto tenia Dany?

**Comment by Gabymorillo** [comment]
Si Natty, dentro del issues te agregué la imagen

**Comment by yolandayancel** [comment]
Prueba 12-06-16
Caso 807
CCP V3.3.5
Persiste lo reportado:Recibí una solicitud de conexión del usuario Nina, pero la foto de perfil corresponde al usuario Ruben como se ve en las fotos:
![screenshot_2016-09-12-09-53-48](https://cloud.githubusercontent.com/assets/17283358/18439140/2c6b32bc-78d2-11e6-95d2-24bb9456f9bc.png)
![screenshot_2016-09-12-09-55-36](https://cloud.githubusercontent.com/assets/17283358/18439161/3e538f2e-78d2-11e6-8cf3-55248a05aca8.png)
![screenshot_2016-09-06-15-20-35](https://cloud.githubusercontent.com/assets/17283358/18439180/4edcd440-78d2-11e6-91c5-0ba05c4bd4ca.png)

**Comment by Gabymorillo** [comment]
En las pruebas desde el telefono fisico con la CCP, versión 3.3.9, este error ya no sucede, las fotos de perfil de los contactos son las correctas, como observamos la solicitud de conexión de RUBENBTCC159T

![screenshot_2016-09-15-16-25-32_720](https://cloud.githubusercontent.com/assets/17262077/18566407/ce9eb824-7b61-11e6-84bd-a48d5631d81c.png)

![screenshot_2016-09-15-16-25-38_720](https://cloud.githubusercontent.com/assets/17262077/18566423/dd355532-7b61-11e6-8ba6-d0891f82ba91.png)

![screenshot_2016-09-15-16-25-46_720](https://cloud.githubusercontent.com/assets/17262077/18566443/eee03900-7b61-11e6-9dd5-33f508bdf21b.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18566450/f38feb80-7b61-11e6-9721-c70d0acd3ac1.png)

**Comment by IsbetVR** [comment]
Solucionado
#Closed #807

**Comment by danielaporras** [comment]
En la version 3.4 se repite este error en mi dispositivo.
![screenshot_2016-09-20-14-16-56](https://cloud.githubusercontent.com/assets/19656830/18684970/3171b2ae-7f44-11e6-8b49-30128d76661a.png)

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18684974/34214f1e-7f44-11e6-9f53-ec7748a4f5f7.png)
[2-15.txt](https://github.com/Fermat-ORG/beta-testing-program/files/483430/2-15.txt)

Por favor reabrir este issue.  @MaviDavsa

**Comment by JeanFranco498** [comment]
En la versión de CCP 3.4.1 en teléfonos físicos persiste el error 

La foto del usuario Door
Se repite en el usuario aro
Se repite en el usario RG


![screenshot_2016-09-23-09-23-42 1](https://cloud.githubusercontent.com/assets/19807906/18787178/af168248-816f-11e6-8228-d7e69a068497.png)


![screenshot_2016-09-23-09-06-33 1](https://cloud.githubusercontent.com/assets/19807906/18787193/c3e1bc9c-816f-11e6-9f7e-ca6a85de41f5.png)


![screenshot_2016-09-23-09-23-45 1](https://cloud.githubusercontent.com/assets/19807906/18787203/cac9c7de-816f-11e6-9191-639c434d7262.png)

**Comment by nattyco** [comment]
@JeanFranco498  al aceptar esas solicitudes las fotos siguen viendose mal?

**Comment by arosiopr** [comment]
En la versión 3.4.2 de CCP persiste el error

La foto de mari le sale a yoly en la notificación.  @nattyco 

![screenshot_2016-09-27-10-14-51](https://cloud.githubusercontent.com/assets/5313326/18879584/da3730d6-84a2-11e6-92bb-7e7c68afe46d.png)

![screenshot_2016-09-27-11-06-46](https://cloud.githubusercontent.com/assets/5313326/18879585/db6893d2-84a2-11e6-91ca-e6f3c295816d.png)

**Comment by arosiopr** [comment]
@MaviDavsa  solucionado en la versión 3.5 de CCP

**Comment by marielis-urbina** [comment]
En la versión 3.5 de ccp, no sucede este error en mi emulador 

![samsung](https://cloud.githubusercontent.com/assets/19353722/18917217/208dff2a-8565-11e6-8719-db360451249f.png)
