### ISSUE TITLE
BITCOIN WALLET - LA FOTO DEL PERFIL SE SALE DEL CONTENEDOR Y NO PERMITE HACER SCROLL

### ISSUE THREAD

**Issue by AdryCanonico** [Fermat-ORG/beta-testing-program#809]
#### Nombre pantalla
CONTACT DETAIL

### Nombre de la Aplicación 
BITCOIN WALLET

-----

##### Reporte de error: 

En el telefono fisico la foto de la ficha del contacto se sale del contenedor, y no permite hacer scroll para ver los otros detalles del contacto

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-09-09-16-50-00](https://cloud.githubusercontent.com/assets/18584168/18403984/dddf41ec-76b5-11e6-84e8-2f2a4ccdf356.png)
 

##### Pasos exactos para reproducir el error:

 Entrar a la ficha de un contacto agregado

  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

Modelo: Huawei Ascend Y221

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/18584168/18403978/d4984548-76b5-11e6-9fcd-a1dc9cc27638.png)

**Comment by AdryCanonico** [comment]
@nattyco

**Comment by danielaporras** [comment]
En la version 3.3.7 de CCP aparece cortada la imagen del contacto.
![screenshot_2016-09-13-15-03-43](https://cloud.githubusercontent.com/assets/19656830/18488250/a0951154-79c6-11e6-9fe5-ef4c28ec33ec.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18488254/a5588be4-79c6-11e6-9584-d261af33b6cd.png)

**Comment by IsbetVR** [comment]
Closed #809
