### ISSUE TITLE
Bit Coin Wallet_Send to contact

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#81]
### Template issue error report

Bit Coin wallet
#### Nombre pantalla

Send to Contact

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *En la pantalla send to contact al tratar de enviar btc con decimales no envia y saca un error en pantalla.

![screenshot_2016-03-16-10-15-18](https://cloud.githubusercontent.com/assets/17273349/13816580/1b40a034-eb61-11e5-8149-fb100dc65a1c.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo: Apex2
* Version de Android: 4.4.2

**Comment by sanro14** [comment]
a mi me pasa lo mismo 
Marca: Genymotion Google Nexus 5
Modelo: Nexus 5
Version de Android: 4.4.4

**Comment by maydiamc** [comment]
a mi me sucede lo mismo

Marca: Samsung Galaxy
Modelo: mini S4
Version de Android: 4.4.2

**Comment by MaviDavsa** [comment]
A mi me sucede lo mismo!

Emulador: BlueStarks
Version de Android: 5.0

**Comment by sanro14** [comment]
en esta versión se corrigió el error

Marca: Genymotion Google Nexus 5
Modelo: Nexus 5
Version de Android: 4.4.4

**Comment by adryx83** [comment]
Ya este problema esta solucionado en mi actualización @augusto-ponce
