### ISSUE TITLE
CHAT - Error al tomar foto desde emulador

### ISSUE THREAD

**Issue by franciscoj961** [Fermat-ORG/beta-testing-program#811]
#### Nombre pantalla

P2P Chat Profile

### Nombre de la Aplicación 

Chat v1.7

-----

##### Reporte de error: 

Al tomar la foto y confirmar para ponerla en tu perfil aparece una notificacion indicando que la imagen seleccionada es muy pequeña. 

##### Screenshot o Capture de pantalla:

![caso12](https://cloud.githubusercontent.com/assets/20245988/18449714/4aae5e76-78fe-11e6-928e-39d8d431e6ce.PNG)

##### Pasos exactos para reproducir el error:

-Ir a Chat Profile
-Tomar la foto y confirmarla como foto de perfiles

##### Inserta Archivo aLogcat: 

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/468210/logcat.zip)

 
  
------

-  Emulador

##### Screenshot o Capture de pantalla:

![sss](https://cloud.githubusercontent.com/assets/20245988/18450050/8e2152fc-78ff-11e6-9700-9c2c0aed1aec.PNG)

**Comment by yolandayancel** [comment]
Prueba 12-06-16
Caso 811
Chat 1.7
Ocurre lo reportado:Al tomar la foto y confirmar para ponerla en tu perfil aparece una notificacion indicando que la imagen seleccionada es muy pequeña.

![screenshot_2016-09-12-16-05-14](https://cloud.githubusercontent.com/assets/17283358/18451329/7604cd5c-7904-11e6-817f-0a99df4dd0ff.png)

![screenshot_2016-09-12-16-05-09](https://cloud.githubusercontent.com/assets/17283358/18451298/5983febe-7904-11e6-8d0d-4477f5f088ce.png)

![screenshot_2016-09-06-15-20-35](https://cloud.githubusercontent.com/assets/17283358/18450828/9889e742-7902-11e6-8d1f-3b15e44ba39d.png)

**Comment by dorzar1989** [comment]
En al Version 1.8 de Chat No sucede este error. Solo que el recuadro esta un poco pequeño al momento de editar la imagen.

_ Screenshot:

![screenshot_221](https://cloud.githubusercontent.com/assets/19670319/18474396/d66296bc-798f-11e6-81cc-4f940ef3d978.png)


- Emulador: 

![nexus 4](https://cloud.githubusercontent.com/assets/19670319/18474435/f1d47c08-798f-11e6-8ccf-9eeab5cfbca2.png)

**Comment by danielaporras** [comment]
Lo reportado en este issue fue solucionado en la version 1.8 Chat, por favor cerrar el caso.

![screenshot_2016-09-13-08-54-01](https://cloud.githubusercontent.com/assets/19656830/18474523/767c77f8-7990-11e6-9133-d421d86b41e5.png)

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18474525/7a805b26-7990-11e6-842a-b92a719f7ecc.png)

@AdryCanonico
