### ISSUE TITLE
CHAT - Foto de perfil se ve ovalada

### ISSUE THREAD

**Issue by franciscoj961** [Fermat-ORG/beta-testing-program#813]
#### Nombre pantalla

P2P Chat Profile 

### Nombre de la Aplicación 

Chat version 1.7

-----

##### Reporte de error: 

La foto de perfil de chat se ve ovalada cuando deberia ser circular

##### Screenshot o Capture de pantalla:

![captura122](https://cloud.githubusercontent.com/assets/20245988/18452904/cde0699a-790a-11e6-8872-350d9966bf13.PNG)

##### Pasos exactos para reproducir el error:

Tomar o elegir foto de perfil

##### Inserta Archivo aLogcat: 

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/468366/logcat.zip)

#### Dispositivo desde donde se realizo la prueba

 Emulador

##### Screenshot o Capture de pantalla:

![sss](https://cloud.githubusercontent.com/assets/20245988/18452988/18284144-790b-11e6-9e0b-df1e9059fc2a.PNG)

**Comment by josejcb** [comment]
estoy probando con un emulador con el mismo tamaño pero 320dpi y no me pasa, de cuantos dpi es este caso? @AdryCanonico

**Comment by MaviDavsa** [comment]
320dpi tambien es el del tlf en el cual se hizo la prueba @josejcb

**Comment by franciscoj961** [comment]
![martes](https://cloud.githubusercontent.com/assets/20245988/18491413/52a45316-79d4-11e6-86f2-2bbfeec982ec.PNG)



-----

![dpi](https://cloud.githubusercontent.com/assets/20245988/18491311/c074881c-79d3-11e6-8c1c-e00207358010.PNG)



Version 1.9.1 Chat
[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/470800/logcat.zip)

**Comment by wendyduran90** [comment]
Con la versión 2.0 chat no sucede este error. La prueba se realizo desde un teléfono físico con versión de android 5.0 marca BLU modelo Life One 2015 .

**Comment by andreagmarcano** [comment]
No persiste el error en la version 2.0 de Chat. 

![captura](https://cloud.githubusercontent.com/assets/18452495/18513605/28c95432-7a5c-11e6-941c-3b6b76e16a1e.PNG)
![evo](https://cloud.githubusercontent.com/assets/18452495/18513614/2cbc7358-7a5c-11e6-90c0-c511820a83cf.PNG)
![dpi evo](https://cloud.githubusercontent.com/assets/18452495/18513617/2fd8a3d6-7a5c-11e6-9861-992a05c2d521.PNG)
