### ISSUE TITLE
CHAT - Icono de búsqueda no funciona como debería al primer toque 

### ISSUE THREAD

**Issue by andreagmarcano** [Fermat-ORG/beta-testing-program#814]
Al estar en la pantalla de P2P, Chats o Contacts. Presiona el icono superior derecho (lupa) Imagen 1. Hay que presionarlo de nuevo y aparece al lado izquierdo de la pantalla para hacer la busqueda. Imagen 2. Tiene funcionalidad, pero no deberia que presionarlo dos veces para realizarla.
 
Imagen 1
![cas1](https://cloud.githubusercontent.com/assets/18452495/18475412/4dad26fc-7994-11e6-92fe-d7476d6e440c.PNG)

Imagen 2
![cas2](https://cloud.githubusercontent.com/assets/18452495/18475420/51010314-7994-11e6-91c0-ff03bba2ab21.PNG)

![movil](https://cloud.githubusercontent.com/assets/18452495/18475424/555a3836-7994-11e6-9850-a5c18f9f100e.PNG)
 
![dpi](https://cloud.githubusercontent.com/assets/18452495/18475890/2003be3a-7996-11e6-9586-cfe175fa4023.PNG)

[log andrea.zip](https://github.com/Fermat-ORG/beta-testing-program/files/469916/log.andrea.zip)

**Comment by danielaporras** [comment]
Version 1.8 Chat, lo reportado en este issue se repite en mi dispositivo.
Deberia de mostrarse el teclado con solo presionar una vez el icono de busqueda.
![screenshot_2016-09-13-09-47-59](https://cloud.githubusercontent.com/assets/19656830/18476272/62987320-7997-11e6-8438-c66f7846ad9a.png)
![screenshot_2016-09-13-09-48-05](https://cloud.githubusercontent.com/assets/19656830/18476278/64de9f1a-7997-11e6-8510-7cad51894e53.png)
![screenshot_2016-09-13-09-48-08](https://cloud.githubusercontent.com/assets/19656830/18476283/67bb7fa0-7997-11e6-81a6-9a50fad9c2e5.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18476287/6ad4a1da-7997-11e6-93cd-fd0c4a5d54dc.png)

**Comment by MaviDavsa** [comment]
Caso Solucionado en la Versión 1.9.1
