### ISSUE TITLE
Chat-Profile teclado montado

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#815]
#### Nombre pantalla
P2P Chat Profile

### Nombre de la Aplicación 

Chat

-----

##### Reporte de error: 

   *Version 1.8 Chat, al presionar para escribir el nombre del usuario el teclado esta montado sobre lo que se escribe. 

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-12-14-25-56](https://cloud.githubusercontent.com/assets/19656830/18475906/305e04a2-7996-11e6-96bb-3d685acb0713.png)

##### Pasos exactos para reproducir el error:
1.Entro a la app para crear el perfil.
2.Presiono para escribir y el teclado tapa lo que se esta escribiendo.

 

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18476353/ac73ec86-7997-11e6-90b0-4619cc7f0f9b.png)

Huawei Ascend Y221 
http://www.gsmarena.com/huawei_ascend_y221-6908.php

@MaviDavsa

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by josejcb** [comment]
@MaviDavsa Denme por favor las dimensiones del telefono y los dpi para poder emularlo  y solventarlo.

**Comment by danielaporras** [comment]
Huawei Ascend Y221
http://www.gsmarena.com/huawei_ascend_y221-6908.php

**Comment by danielaporras** [comment]
Lo reportado en este issue fue solucionado en la version 1.9.1 de chat por   favor cerrarlo.
![screenshot_2016-09-13-16-10-28](https://cloud.githubusercontent.com/assets/19656830/18489941/d57f45cc-79cd-11e6-8f9e-3f2694fece0e.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18489943/d7675c44-79cd-11e6-8256-b65eed5092f9.png)

**Comment by josejcb** [comment]
Relacionado al #155
