### ISSUE TITLE
Chat -  No se muestran mensajes nuevos dentro de la conversación

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#816]
#### Nombre pantalla

Conversación 

### Nombre de la Aplicación 

Chat 1.8 

-----

##### Reporte de error: 

Dentro de una conversación, el contacto envía un mensaje nuevo y no lo refleja en el momento, a pesar de que llega la notificación,  se debe salir de la conversación y entrar para que muestre el nuevo mensaje.  

##### Screenshot o Capture de pantalla:

 *Agregar las capture del error en el emulador o teléfono donde se produjo. 

![screenshot_2016-09-13-09-38-28_720](https://cloud.githubusercontent.com/assets/17262077/18476369/c0714562-7997-11e6-9bd8-29fc00a91dbc.png)

![screenshot_2016-09-13-09-38-21_720](https://cloud.githubusercontent.com/assets/17262077/18476358/b4ca2468-7997-11e6-8aa1-909b661346ec.png)

![screenshot_2016-09-13-09-38-39_720](https://cloud.githubusercontent.com/assets/17262077/18476388/d52057b4-7997-11e6-8c71-586c1315fe38.png)

![screenshot_2016-09-13-09-38-45_720](https://cloud.githubusercontent.com/assets/17262077/18476405/e211fd7e-7997-11e6-89c0-e331fb7c315b.png)

##### Pasos exactos para reproducir el error:

- Abrir una conversación y chatear
- Salir y entrar de nuevo para que muestre el nuevo mensaje. 

##### Inserta Archivo aLogcat: 

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

 *Agregar las capture de la descripcion del emulador o teléfono.

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18476579/a0322db0-7998-11e6-99ca-3f3aededa79a.png)

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by josejcb** [comment]
No me pasa, vamos a tener que verlo en vivo, asi descartamos que la notificaciones arriba no sea de un msj que previamente llegó. @MaviDavsa @AdryCanonico podemos hacer una call para ver el caso.

**Comment by lnacosta** [comment]
@Gabymorillo podrías también por favor, adjuntar el log?

**Comment by Gabymorillo** [comment]
En la versión 2.0 del chat no sucede este error. @MaviDavsa

**Comment by maydiamc** [comment]
en la versión 2.0 de Chat, esto ya no sucede, los mensajes llegan y se actualizan sin necesidad de salir del chat.

emulador
![nexus 5- 6 0](https://cloud.githubusercontent.com/assets/17274154/18514294/0640ec24-7a5f-11e6-9ac0-9bb68ea46527.png)
