### ISSUE TITLE
Bitcoin Wallet-Botón cortado en aviso de ayuda en "Payment Request"

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#817]
#### Nombre pantalla

Payment requests

### Nombre de la Aplicación 

Bitcoin Wallet
-----

##### Reporte de error: 

   *En la version 3.3.7 en el aviso de ayuda (payment requests) se muestra cortado el boton para cerrar y no permite scrollear.

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-13-14-18-31](https://cloud.githubusercontent.com/assets/19656830/18488700/97567dce-79c8-11e6-9c00-53c9e3f00703.png)

##### Pasos exactos para reproducir el error:

Entrar a la pantalla de Payment requests

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico
Huawei Ascend Y221
http://www.gsmarena.com/huawei_ascend_y221-6908.php

##### Screenshot o Capture de pantalla:
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18488797/021c7bcc-79c9-11e6-8414-0568483c11b1.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by danielaporras** [comment]
En la version 2.0 de CCP fue solucionado este issue.
![screenshot_2016-09-14-15-10-15](https://cloud.githubusercontent.com/assets/19656830/18526468/b53a4a52-7a8e-11e6-9ecd-8e6c57e9275c.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18526471/b7b6d2dc-7a8e-11e6-9373-279fad8bbee0.png)
   Por favor cerrar el caso @IsbetVR

**Comment by IsbetVR** [comment]
Solucionado
Closed #817
