### ISSUE TITLE
Bitcoin wallet- Logo montado en título del aviso de ayuda en "Payment request"

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#818]
#### Nombre pantalla

Payment requests

### Nombre de la Aplicación 

Bitcoin wallet

-----

##### Reporte de error: 

   *En la version 3.3.7 de CCP El título "Solicitud de pago" en el aviso de ayuda, tiene el logo de btc montado.

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-09-13-14-18-31](https://cloud.githubusercontent.com/assets/19656830/18489350/23cf6d72-79cb-11e6-9e42-0c4b0cfb6763.png)

##### Pasos exactos para reproducir el error:

entrar a la pantalla de Payment requests.

 
  
------

#### Dispositivo desde donde se realizo la prueba

Huawei Ascend Y221
http://www.gsmarena.com/huawei_ascend_y221-6908.php
- [x] Teléfono Físico

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18489406/636f22ce-79cb-11e6-8a06-66562f6d6de5.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by danielaporras** [comment]
En la version 3.3.8 se repite lo reportado en este issue.
![screenshot_2016-09-14-15-11-14](https://cloud.githubusercontent.com/assets/19656830/18526996/e823d9ae-7a90-11e6-915d-fb7ec043b819.png)
![Uploading Screenshot_2016-09-08-09-08-47.png…]()

**Comment by danielaporras** [comment]
Version 3.3.8 CCP , se repite lo comentado en este error.
![screenshot_2016-09-14-15-10-15](https://cloud.githubusercontent.com/assets/19656830/18527288/210f293e-7a92-11e6-849f-1e31ac47fe43.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18527289/2155d258-7a92-11e6-940e-131c4c2193cc.png)

**Comment by nattyco** [comment]
@IsbetVR  verificar en la version 3.3.9

**Comment by danielaporras** [comment]
En la version 3.3.9 fue solucionado este error.
![screenshot_2016-09-15-13-58-25](https://cloud.githubusercontent.com/assets/19656830/18561872/a1fe16f0-7b4f-11e6-834f-f42da1166183.png)
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18561874/a5505426-7b4f-11e6-9bb5-4db9930bac11.png)
Por favor cerrar el caso.  @IsbetVR

**Comment by IsbetVR** [comment]
Solucionado 
Closed #818
