### ISSUE TITLE
Error_Balance_No se reflejan los btc

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#82]
##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *Al enviar y recibir Btc, solo se reflejan, tanto en el book balance como en el available balance, los btc que envio, porque los que recibo, bien sea por envio directo o por payment request, no se reflejan en los balances, 

Nota: los payment request fueron acceptados por mis contactos y a ellos se les debito la cantidad de btc enviada, pero a mi no se me me reflejaron los btc en los balances.

![screenshot_2016-03-16-10-16-35](https://cloud.githubusercontent.com/assets/17274154/13816642/5f787d62-eb61-11e5-9d39-48853fee454b.png)
![screenshot_2016-03-16-10-16-50](https://cloud.githubusercontent.com/assets/17274154/13816653/657749aa-eb61-11e5-90c2-a7ea3a69a000.png)

   
------
#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini S4
* Version de Android:4.4.2

**Comment by sanro14** [comment]
Si yo hice un request a @maydiamc ella lo acepto pero nunca me llego el dinero

**Comment by nattyco** [comment]
@maydiamc tenes que esperar a ver si llegan, porque puede haber problemas con la conexion a la red

**Comment by maydiamc** [comment]
ya tienen 24hs aproximadamente de enviados, porque esos payment los hice ayer, ya tienen bastante tiempo

Marca: Samsung Galaxy
Modelo: mini S4
Version de Android:4.4.2

**Comment by maydiamc** [comment]
El error persiste en la nueva actualizacion @nattyco 

Marca: Samsung Galaxy
Modelo: mini S4
Version de Android:4.4.2

**Comment by maydiamc** [comment]
en la ultima actualizacion persiste el problema
Marca: Samsung Galaxy
Modelo: mini S4
Version de Android:4.4.2

**Comment by nattyco** [comment]
@maydiamc seguis con este problema que no te llega los btc? necesito que me aclares en que red de bitcoin estas trabajando y en que red estan las personas que te enviaron las transacciones, y que tipo de transacciones son.

Y si los btc quedaron en el book o nunca te llegaron.

Los btc que pediste al faucet de fermat tardaron en llegarte.

**Comment by maydiamc** [comment]
Si, la regtest estoy usando y en la testnet tambien es lo mismo

**Comment by nattyco** [comment]
@maydiamc  verificar este caso con la ultima version de la app

**Comment by maydiamc** [comment]
@nattyco en la ultima actualizaion se soluciono el problema
