### ISSUE TITLE
CCP - Recorte de foto diferente

### ISSUE THREAD

**Issue by franciscoj961** [Fermat-ORG/beta-testing-program#820]
#### Nombre pantalla

Identity Manager

### Nombre de la Aplicación 

CCP V 3.3.8

-----

##### Reporte de error: 

Los recortes de imagenes de Camara y Galeria son diferentes, el recuadro de recorte de camara es mas pequeño que el de Galeria

##### Screenshot o Capture de pantalla:

**1) Cuadro de recorte de la camara**
![foto](https://cloud.githubusercontent.com/assets/20245988/18524894/63ab4aa2-7a88-11e6-9ca0-c7a24b2720eb.PNG)

**2) Cuadro de recorte de la galeria**
![recorte](https://cloud.githubusercontent.com/assets/20245988/18524900/6c851496-7a88-11e6-944e-51a54b40ad5b.PNG)

##### Pasos exactos para reproducir el error:
-Ir a Identity Manager
-Tomar una foto para seleccionar la imagen tomada como foto de perfil
-Elegir una foto de Galeria

 
  
------

#### Dispositivo desde donde se realizo la prueba
EMULADOR: 
![sss](https://cloud.githubusercontent.com/assets/20245988/18524988/cb8617ce-7a88-11e6-9e8a-c9baeea12785.PNG)

Otros dispositivos en lo que se realizo la prueba 

api 17Marca ZTE Blade G V765 Pantalla 4 pulgadas 400x 800 píxeles OS Android Jelly Bean 4.2.2

Alcatel One touch mpop 5020 A 4.1.1 api 16  480 x 800 pixels, 4.0 pulgadas

**Ambos telefonos fisicos**

**Comment by IsbetVR** [comment]
@nattyco

**Comment by nattyco** [comment]
@IsbetVR  verificar en la version 3.3.9

**Comment by Gabymorillo** [comment]
En las pruebas de la CCP versión 3.3.9, desde el teléfono físico, se observa que el tamaño del cuadro del recorte de la cámara es normal. 

![screenshot_2016-09-15-14-15-24_720](https://cloud.githubusercontent.com/assets/17262077/18561976/f910728a-7b4f-11e6-92bd-ca02f9c47678.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18561980/fd069338-7b4f-11e6-96ac-0bfb172efb69.png)

**Comment by IsbetVR** [comment]
Corregido en la versión CCP-v3.3.9 (Emulador)

#### Tomada con la cámara del emulador 

![screenshot_65](https://cloud.githubusercontent.com/assets/19142276/18563096/576b2db2-7b54-11e6-98c4-43b3818b3d1a.jpg)

#### Seleccionada desde la galeria

![screenshot_66](https://cloud.githubusercontent.com/assets/19142276/18563169/9b4093a6-7b54-11e6-8a55-2736cb5cfd97.jpg)


#### Dispositivo de prueba
- [x] Emulador
- HTC One X
- Android 4.1.1
- 320 dpi
- API 16 - 720x1280

![htc one x 4 1 1](https://cloud.githubusercontent.com/assets/19142276/18563174/a0024a56-7b54-11e6-9133-f1fe6ba5dae7.jpg)

**Comment by IsbetVR** [comment]
Closed #820
