### ISSUE TITLE
CHAT - LA BARRA DEL NOMBRE DE PERFIL CUBRE LAS LETRAS 

### ISSUE THREAD

**Issue by JeanFranco498** [Fermat-ORG/beta-testing-program#822]
#### Nombre pantalla

P2P Chat Profile

### Nombre de la Aplicación 

CHAT

-----

##### Reporte de error: 

   *Al entrar en la pantalla para la creación de perfiles, la barra donde va el nombre del perfil, esta sobre las letras del nombre del perfil, en esta versión se corrigió un poco pero sigue viéndose por encima de las letras 

##### Screenshot o Capture de pantalla:

Versión de chat 2.0 (anterior)
![screenshot_2016-09-15-08-54-01 1](https://cloud.githubusercontent.com/assets/19807906/18555214/0cce2972-7b35-11e6-8f36-d83d3b9b94be.png)

Version de chat 2.1 (Nueva)
![screenshot_2016-09-15-11-00-38 1](https://cloud.githubusercontent.com/assets/19807906/18555227/1baba230-7b35-11e6-86ba-238122a71edf.png)

##### Pasos exactos para reproducir el error:

1. Abrir APP
2. Abrir wizard de perfiles
2. Entrar a perfil de Chat
3. Escribir el nombre
4. Observar la barra

##### Inserta Archivo aLogcat: 

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico
- Modelo de dispositivo: Samsung Galaxy S3 Neo 
- Versión de Android: Version 4.4.4 KitKat
- API: 19
- dpi: 306  

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-15-11-16-36 1](https://cloud.githubusercontent.com/assets/19807906/18555451/e5a953d4-7b35-11e6-82e3-cb55d55a31e0.png)

**Comment by AdryCanonico** [comment]
En mi teléfono físico sucede lo mismo 

http://www.smart-gsm.com/moviles/samsung-galaxy-avant

![screenshot_2016-09-15-10-37-06](https://cloud.githubusercontent.com/assets/18584168/18555696/c1489bf2-7b36-11e6-8041-a1cd0be3c822.png)

**Comment by danielaporras** [comment]
En mi dispositivo se repite este error.
![screenshot_2016-09-15-11-35-17](https://cloud.githubusercontent.com/assets/19656830/18556546/94277514-7b39-11e6-87bb-697215344bc9.png)

Huawei Ascend Y221
Dimensiones    116.5 x 60.6 x 12.3 mm
Tamaño    320 x 480 pixels, 3.5 pulgadas
http://www.gsmarena.com/huawei_ascend_y221-6908.php
![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18556574/aa13df66-7b39-11e6-9bb3-731055f71e76.png)

**Comment by MaviDavsa** [comment]
@josejcb

**Comment by AdryCanonico** [comment]
solucionado se puede cerrar el caso
