### ISSUE TITLE
CHAT-SE DUPLICAN LOS MENSAJES ENVIADOS

### ISSUE THREAD

**Issue by camilavaleria** [Fermat-ORG/beta-testing-program#827]
Template issue error report

 Nombre pantalla

P2P CHAT

 Nombre de la Aplicación 

CHAT

Reporte de error: 

Al iniciar una conversacion mediante chat, se repiten o duplican los mensajes que se envian, tal y como se señala a continuacion:

 Capture de pantalla 1

![image](https://cloud.githubusercontent.com/assets/18740418/18570661/ee8f0cd4-7b79-11e6-90e2-c9dc57f57aa3.png)

Capture de pantalla 2

![image](https://cloud.githubusercontent.com/assets/18740418/18570679/135ff050-7b7a-11e6-8e70-f66c3f66dac6.png)

Captured de pantalla 3

![image](https://cloud.githubusercontent.com/assets/18740418/18570782/eb123eae-7b7a-11e6-985f-fc5dbb1424ba.png)

Captured de pantalla 4

![image](https://cloud.githubusercontent.com/assets/18740418/18570792/fb67b9c8-7b7a-11e6-99be-108f5f93ae8d.png)

Pasos exactos para reproducir el error:

1. Abrir App
2. Crear perfil
3. Hacer conexiones con usuarios
4. Iniciar envio de mensajes
5. Recepcion de mensajes

 Inserta Archivo aLogcat: 

[logcat.zip](https://github.com/Fermat-ORG/beta-testing-program/files/475808/logcat.zip)

Hora Aprox: 5:48 pm

Dispositivo desde donde se realizo la prueba

Teléfono Físico

![image](https://cloud.githubusercontent.com/assets/18740418/18570917/34a53584-7b7c-11e6-94ac-28cb6b2dabf7.png)

**Comment by camilavaleria** [comment]
@sanro14 @

**Comment by sanro14** [comment]
@royGF @josejcb

**Comment by marielis-urbina** [comment]
En la versión 2.2 de Chat, sucede este error en mi emulador

![duplicar](https://cloud.githubusercontent.com/assets/19353722/18592180/b2cadb94-7c03-11e6-94fb-01c4fa13e9e0.png)

![samsung](https://cloud.githubusercontent.com/assets/19353722/18592190/c20c1c1c-7c03-11e6-9a27-cb1ac8e7aaa7.png)

**Comment by AdryCanonico** [comment]
Se soluciono en la version 2.3 de chat
