### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#83]
### Template issue error report

Error al pulsar el botón CRYTO CUSTOMER de la app FERMAT
#### Nombre pantalla

Pantalla de Inicio
### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Al pulsar el botón CRYPTO CUSTOMER de la app Fermat se lale de la aplicación. 

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca:
* Modelo:
* Version de Android:

![screenshot_2016-03-15-19-36-38](https://cloud.githubusercontent.com/assets/17283358/13820510/d1e6ce18-eb6f-11e5-9f22-e23c94bf6095.png)
![screenshot_2016-03-16-11-42-52](https://cloud.githubusercontent.com/assets/17283358/13820530/e77962f4-eb6f-11e5-8f7c-98d0c1edefdd.png)

**Comment by nattyco** [comment]
@yolandayancel tenes que probar solo las app que estan dentro de esta estapa de testing, consulta con @augusto-ponce

**Comment by yolandayancel** [comment]
Buenas tardes Srta.  Natalie Cortes

Recibida la información
Saludos  cordiales
