### ISSUE TITLE
Bitcoin Wallet - No funciona el botón para confirmar un request - Pantalla small

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#831]
##### Reporte de error: 

@nattyco al intentar realizar una solicitud de BTC a un contacto mediante un send Request To contact, el botón de "confirmar request" no funciona y no me permite realizar la operación.
ver imagen adjunta de la pantalla donde se observa la falla

![2016-09-20-11-04-34](https://cloud.githubusercontent.com/assets/5313324/18676216/d9320196-7f22-11e6-94cd-eef65c2f2011.jpg)

Pasos:
1) Entro a contactos
2) Selecciono un contacto (contact detail)
3) Le doy click al boton de "Solicitar"
4) Intentar hacer una solicitud, no funciona el botón "Confirmar Request"

La prueba se realizó e una Lg Optimus L3, pantalla 240 x 320 pixels, 3.2 pulgadas

![2016-09-15-13-05-03](https://cloud.githubusercontent.com/assets/5313324/18676526/e035e59c-7f23-11e6-97d8-228e21cbd201.jpg)

**Comment by sanro14** [comment]
Solucionado en la versión 3.4.1

**Comment by arosiopr** [comment]
En la versión 3.4.1 sucede lo reportado el botón de confirmar request no funciona en mi dispositivo
![screenshot_2016-09-23-10-07-21 1](https://cloud.githubusercontent.com/assets/5313326/18788677/d36606cc-8175-11e6-8906-6d347ab399ee.png)

- [x] Teléfono Físico
- Modelo de dispositivo: Alcatel One Touch Mpop 5020A
- Versión de Android: 4.1.1
- API: 16
- dpi: 480 x 800 pixels, 4.0 pulgadas

![alcatel](https://cloud.githubusercontent.com/assets/5313326/18788684/da41132e-8175-11e6-98f6-e0b8db60d187.png)

por favor reabrir @sanro14 @IsbetVR

**Comment by sanro14** [comment]
se reabre el caso @nattyco

**Comment by nattyco** [comment]
@arosiopr  no funciona en ningun caso?

**Comment by arosiopr** [comment]
@nattyco  no. hoy provere a ver, porque eso no habia sucedido

**Comment by arosiopr** [comment]
@sanro14  el error no se presento en la versión 3.4.2 de CCP @sanro14

**Comment by sanro14** [comment]
Solucionado!
