### ISSUE TITLE
Bitcoin Wallet - Estandarizar la cantidad de dígitos para "Send" y "Send Request" To Contact

### ISSUE THREAD

**Issue by danielaporras** [Fermat-ORG/beta-testing-program#833]
#### Nombre pantalla

Send Request To Contact

### Nombre de la Aplicación 

Bitcoin Wallet

-----

##### Reporte de error: 

   *En la versión 3.4 CCP, al momento de escribir la cantidad de btc que se van a solicitar, son infinitos los caracteres que se pueden ingresar. 

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-20-16-04-02](https://cloud.githubusercontent.com/assets/19656830/18687176/e5226070-7f4c-11e6-8d36-b32c5769816b.png)

 *Detallar paso a paso la forma en  la cual se logro el error.

1. Seleccionar uno de mis contactos para solicitar btc.
2. Entrar en la pantalla de Send Request To Contact.
3. En la cantidad (btc) son infinitos los caracteres que se pueden introducir.
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico
- Modelo de dispositivo: Huawei Ascend Y221
- Versión de Android: 4.4.2
- API: 19
- dpi: 320 x 480 pixels

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-08-09-08-47](https://cloud.githubusercontent.com/assets/19656830/18687371/c793a3ec-7f4d-11e6-8476-02ab09be0082.png)

@MaviDavsa

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by maydiamc** [comment]
en la version 3.4 de CCP, permite poner una cantidad muy larga de caracteres en el formulario de send request to contact, mientras que en el formulario de send to contact solo permite 11 caracteres.

![screenshot_3](https://cloud.githubusercontent.com/assets/17274154/18687940/54dd4a80-7f50-11e6-86df-42bc7bd668dc.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/18687942/55dec8aa-7f50-11e6-8acd-081b3b09ed72.png)

Emulador
API 23
![nexus 5-6 0](https://cloud.githubusercontent.com/assets/17274154/18687956/64b90ba6-7f50-11e6-8f84-1a7e35bd00b3.png)
![nexus 5-6 0 dpi](https://cloud.githubusercontent.com/assets/17274154/18687958/661fd13c-7f50-11e6-9a0a-e1c91d6f62c3.png)

**Comment by nattyco** [comment]
@danielaporras corregido en la version 3.4.1 se limito la cantidad de numeros a 12

**Comment by danielaporras** [comment]
En la version 3.4.1 fue solucionado este issue.
![screenshot_2016-09-23-09-09-41](https://cloud.githubusercontent.com/assets/19656830/18788585/762f3fa0-8175-11e6-9a3c-672008a20307.png)
 
Por favor cerrar el caso. @sanro14

**Comment by arosiopr** [comment]
se recomienda que la cantidad de digitos mostrados en las pantallas del "home-sent/received" así como en las de "Payments" para hacer los envíos y request respectivamente sea el mismo que los ingresados cuando se muestra la pantalla del contacto para ingresar los montos.  Que sea estándar en todas las pantallas

**Al momento de enviar son 10 caracteres incluyendo el punto "."**

![screenshot_2016-09-23-10-22-30](https://cloud.githubusercontent.com/assets/5313326/18792841/1fa52a3a-8186-11e6-97dd-491233319d13.png)

![screenshot_2016-09-23-10-22-44](https://cloud.githubusercontent.com/assets/5313326/18792885/578f85f8-8186-11e6-92d4-bbf92083444e.png)

**Lo que muestra después son 8 caracteres incluyendo la coma ","**

![screenshot_2016-09-23-10-24-46](https://cloud.githubusercontent.com/assets/5313326/18792952/9fa5e788-8186-11e6-8345-6ed668caed9b.png)


@IsbetVR

**Comment by nattyco** [comment]
@IsbetVR  se estandarizaron los digitos en la version 3.4.2

**Comment by arosiopr** [comment]
El error se soluciono en el caso de hacer un send.
En el caso de los request aun varia, en el caso del request solo deja ingresar 8 dígitos incluyendo el punto "."

![screenshot_2016-09-27-10-32-51](https://cloud.githubusercontent.com/assets/5313326/18878283/fe2b1160-849d-11e6-9340-68aac4f2b505.png)

y en el caso del send deja ingresar 10 dígitos incluyendo el punto "."
![screenshot_2016-09-27-10-34-31](https://cloud.githubusercontent.com/assets/5313326/18878321/1c6f238c-849e-11e6-817b-6161cc0efb56.png)

@sanro14

**Comment by sanro14** [comment]
@nattyco

**Comment by nattyco** [comment]
@sanro14  @MaviDavsa  corregido en la version 3.4.3

**Comment by arosiopr** [comment]
Solucionado en la version 3.5 de CCP se puede cerrar @sanro14 

![screenshot_2016-09-27-15-48-18](https://cloud.githubusercontent.com/assets/5313326/18889183/c2d9d5d4-84c9-11e6-84a5-6b5051b42ee7.png)

**Comment by sanro14** [comment]
Solucionado
