### ISSUE TITLE
BITCOIN WALLET - REQUESTS - TECLADO VISIBLE

### ISSUE THREAD

**Issue by arosiopr** [Fermat-ORG/beta-testing-program#834]
#### Nombre pantalla

requests

### Nombre de la Aplicación 

CCP 3.4

-----

##### Reporte de error: 

   *Al ingresar a la sección de Requests se visualiza el teclado automáticamente 

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-20-16-14-56](https://cloud.githubusercontent.com/assets/5313326/18687733/74a6fbbe-7f4f-11e6-9b33-1df28a5f973c.png)

##### Pasos exactos para reproducir el error:

1. Ingresar a Bitcoin Wallet 
2. Presionar opción Requests en el drawer

##### Inserta Archivo aLogcat: 

[logcat teclado.txt](https://github.com/Fermat-ORG/beta-testing-program/files/483537/logcat.teclado.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico
- Modelo de dispositivo: Alcatel One Touch Mpop 5020A
- Versión de Android: 4.1.1
- API: 16
- dpi: 480 x 800 pixels, 4.0 pulgadas

##### Screenshot o Capture de pantalla:

![alcatel](https://cloud.githubusercontent.com/assets/5313326/18687843/e2ced56c-7f4f-11e6-97f9-4651407c384b.png)

**Comment by arosiopr** [comment]
@MaviDavsa

**Comment by Gabymorillo** [comment]
Desde el teléfono físico, en la versión 3.4 de CCP, al momento de ingresar a la opción de Payment, dentro de la pantalla de requests el teclado de activa automáticamente. 

![screenshot_2016-09-20-15-58-32_720](https://cloud.githubusercontent.com/assets/17262077/18688054/b7a18424-7f50-11e6-9f56-29ea6013278b.png)

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18688061/baacfec8-7f50-11e6-809b-ce6daea6dc05.png)

**Comment by GeronimoVierma** [comment]
En la versión 3.4 de CCP, al ingresar a la opción de Payment,  el teclado de activa automáticamente:

Telefono fisico: 

![screenshot_2016-09-20-16-38-59](https://cloud.githubusercontent.com/assets/19883115/18688204/4572e5f4-7f51-11e6-8d22-ed8ca4aa42a9.png)

![screenshot_2016-07-14-18-31-45](https://cloud.githubusercontent.com/assets/19883115/18688208/4b1d77e4-7f51-11e6-9ac1-b2c1947525db.png)

**Comment by nattyco** [comment]
@arosiopr corregido en la version 3.4.1 al ingresar al listado de Payment Request ya no se ve el teclado.

**Comment by arosiopr** [comment]
@IsbetVR 
Solucionado en la versión 3.4.1 de CCP
![screenshot_2016-09-23-08-52-18](https://cloud.githubusercontent.com/assets/5313326/18786294/23a9d470-816b-11e6-9859-f97717d9e042.png)
![alcatel](https://cloud.githubusercontent.com/assets/5313326/18786296/268b421e-816b-11e6-9cba-22845a12f7cf.png)
