### ISSUE TITLE
Bitcoin Wallet- Add Fermat user -  Duplica los contactos 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#838]
#### Nombre pantalla

Add Fermat user 

### Nombre de la Aplicación 

CCP 3.4.2 

-----

##### Reporte de error: 

Al ingresar a la Bitcoin Wallet y dirigirnos a contacs para agregar un contacto fermat, vemos que el usuario MariWallet27 se duplica y permite seleccionar ambos contactos (imagen 1). Pero al revisar en la cartera de mis contactos el usuario sale una sola vez. (imagen 2).  

##### Screenshot o Capture de pantalla:

![screenshot_2016-09-27-10-23-51_720](https://cloud.githubusercontent.com/assets/17262077/18881241/98dadd08-84a8-11e6-94fc-31a4661a0352.png)

![screenshot_2016-09-27-12-18-20_720](https://cloud.githubusercontent.com/assets/17262077/18882328/b9c51660-84ac-11e6-8a05-d77ca5ddd154.png)

##### Pasos exactos para reproducir el error:

- Aceptar una solicitud de conexión
- Ir a la Bitcoin Wallet
- Entrar en contactos
- Contacto fermat

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/496053/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
- Modelo de dispositivo: Samsung GT-I9082L
- Versión de Android: 4.2.2
- API: 17
- dpi: 480 x 800 píxeles

##### Screenshot o Capture de pantalla:

![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/18881569/d10e73c8-84a9-11e6-83fe-97b840414d81.png)

**Comment by IsbetVR** [comment]
@nattyco

**Comment by dorzar1989** [comment]
En la version 3.4.2 de CCP me sucedio el mismo error

- Screenshots:

![screenshot_97](https://cloud.githubusercontent.com/assets/19670319/18884223/7e480766-84b4-11e6-8190-e4bf34cd858b.png)


- Logcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/496232/logcat.txt)


- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/18884387/31f40bc0-84b5-11e6-9a5a-f5181f788c97.png)

**Comment by nattyco** [comment]
@Gabymorillo   @MaviDavsa  vrificar en la version 3.4.3

**Comment by marielis-urbina** [comment]
En la versión 3.5 de CCP, no me sucede este error en mi emulador

![samsung](https://cloud.githubusercontent.com/assets/19353722/18889442/06cd0030-84cb-11e6-9a52-a07a3c1c6f75.png)

**Comment by RubenSem** [comment]
En la versión 3.5 no me sucede este error.
![screenshot_2016-09-27-16-18-49](https://cloud.githubusercontent.com/assets/19676223/18890572/b3fde46e-84cf-11e6-897b-043720613be8.png)
@sanro14  @nattyco

**Comment by sanro14** [comment]
Solucionado
