### ISSUE TITLE
Bitcoin Wallet-Home-Error 

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#84]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

Estaba en la pantalla de home revisando las transacciones que había enviado y de repente se cerro la aplicación, al intentar iniciarla nuevamente sale el siguiente error y luego se cierra. como se observa en la siguiente captura, ha sucedido en 2 ocasiones, la forma de que vuelva a funcionar es desinstalar todo y volver a empezar desde cero:
![captura de pantalla 2016-03-16 09 48 16 2](https://cloud.githubusercontent.com/assets/5313324/13820844/3e112844-eb71-11e5-81aa-da7e3d5323b9.png)

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo:Google Nexus 5
* Version de Android:4.4.4

**Comment by nattyco** [comment]
@sanro14  verificar si con la nueva version sigue ocurriendo este error

**Comment by sanro14** [comment]
@nattyco no ha sucedido mas creo se puede cerrar @augusto-ponce
