### ISSUE TITLE
Bitcoin Wallet-Payment Request Sent-Error

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#85]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios. 

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [] Pantalla de contactos (Lista)
- [] Pop up de ayuda
- [] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

Al hacer un request solicite un monto de 0.1223 BTC como se observa en la siguiente captura:
![captura de pantalla 2016-03-18 09 47 55](https://cloud.githubusercontent.com/assets/5313324/13880794/30a0fbbe-ecf0-11e5-8ddd-6b7a6c58694b.png)

Al darle click en confirm request lo hace normal, pero al momento de observar el request enviado el monto exacto no coincide como se puede ver en la siguiente captura, la ultima de la lista es la prueba de decimales, y sale solo 0.1200 BTC:
![captura de pantalla 2016-03-18 09 48 16](https://cloud.githubusercontent.com/assets/5313324/13880828/5d8a1a16-ecf0-11e5-94c0-331ee483c707.png)

   
   
------
##### Settings

- [] Pantalla de envio
- [] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5 
* Version de Android: 4.4.4

**Comment by nattyco** [comment]
@sanro14 Probar en la nueva version

**Comment by sanro14** [comment]
@nattyco el error en exactitud de decimales persiste

**Comment by nattyco** [comment]
@sanro14  Adjunta pantallas para ver el error. Gracias

**Comment by sanro14** [comment]
Enviando request a augusto ingreso la cantidad 0.0123 dice enviado
![captura de pantalla 2016-03-22 13 35 29](https://cloud.githubusercontent.com/assets/5313324/13962480/5d13fe76-f033-11e5-9f61-654717db51d5.png)


en request sent sale es la cantidad 0.0100 es el ultimo de la lista dice solicitud de pago rosana
![captura de pantalla 2016-03-22 13 37 28](https://cloud.githubusercontent.com/assets/5313324/13962506/7bcb8438-f033-11e5-9ab5-40fbe5ddb3c2.png)

**Comment by sanro14** [comment]
@nattyco @augusto-ponce  corregido el error, se puede cerrar este caso
