### ISSUE TITLE
IoP Wallet Android - "IoP No Responde"

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#852]
#### Nombre pantalla

IoP Wallet

### Nombre de la Aplicación 

IoP Version 1.0.2

-----

##### Reporte de error: 

Cuando se deja de usar por unos minutos la aplicacion desde mi emulador es como si se guindara y sale el aviso de "IoP No responde".

##### Screenshot o Capture de pantalla:

![screenshot_6](https://cloud.githubusercontent.com/assets/19670319/19154128/be819c50-8bc8-11e6-8065-74c81efef44c.png)

##### Pasos exactos para reproducir el error:

- Tener la Aplicacion IoP Abierta
- Dejar de usarla por varios minutos 

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/513838/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico
- Modelo de dispositivo: Google Nexus 4 
- Versión de Android: 4.1.1
- API: 16
- dpi:  320
- IoP en Windows

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/19154332/a05f6f58-8bc9-11e6-81da-7af837882632.png)

**Comment by maydiamc** [comment]
Al darle click a hacer copia de seguridad, y cancelarla apareció Iop No responde

Hora: 9:59am aprox
[iop 852.zip](https://github.com/Fermat-ORG/beta-testing-program/files/513946/iop.852.zip)

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/19155525/c7896916-8bac-11e6-8fa0-a757a273dda6.png)

**Comment by MaviDavsa** [comment]
@furszy

**Comment by wendyduran90** [comment]
Al entrar en la opción de ayuda (pantalla principal), se colgó la apk  mostrando el mensaje  "iop wallet no responde". Esta prueba se realizo desde teléfono físico con versión de android 4.4 marca BLU modelo Life One 2015.

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/514185/logcat.txt)

![caracteristicas_cel](https://cloud.githubusercontent.com/assets/20212920/19158914/6f8e2c22-8bb8-11e6-8608-fe6785ce9536.jpg)

**Comment by dorzar1989** [comment]
En la Version 1.4 de la IoPya no sucede este error.

- Screenshot:

![screenshot_25](https://cloud.githubusercontent.com/assets/19670319/19204443/6d1c72f4-8ccc-11e6-925e-c18e7f5bd201.png)

- Emulador: 

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/19204451/78aa8818-8ccc-11e6-9ab1-a0a80d1a5ded.png)
