### ISSUE TITLE
IoP Wallet Android - Desaparecen los Codigos QR de la Apk

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#856]
#### Nombre pantalla

IoP Wallet / Solicitar Bitcoins

### Nombre de la Aplicación 

IoP Wallet Android - Version 1.0.2 

-----

##### Reporte de error: 

El Codigo QR desaparacio sin mas. Se cierra y abre de nuevo la apk y no aparece.

##### Screenshot o Capture de pantalla:

- ![screenshot_9](https://cloud.githubusercontent.com/assets/19670319/19156324/08690b5c-8bd1-11e6-87e5-d6765e197ec1.png)

- ![screenshot_12](https://cloud.githubusercontent.com/assets/19670319/19156339/170b83ec-8bd1-11e6-86fc-f770f93a5785.png)

- ![screenshot_14](https://cloud.githubusercontent.com/assets/19670319/19156360/2c11d14c-8bd1-11e6-8eac-30aeb0f995bd.png)

##### Pasos exactos para reproducir el error:

- Usar la Apk

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/513983/logcat.txt)

------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico
- Modelo de dispositivo: Google Nexus 4
- Versión de Android: 4.1.1
- API: 16
- dpi:  320
- IoP de Windows

##### Screenshot o Capture de pantalla:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/19156609/0f68d026-8bd2-11e6-94c6-0fca511343f6.png)

**Comment by MaviDavsa** [comment]
@furszy

**Comment by dorzar1989** [comment]
En la Version 1.2 de la IoP Persiste el error

- Screenshots:

![screenshot_21](https://cloud.githubusercontent.com/assets/19670319/19195461/4c8b611a-8ca1-11e6-8912-4ed8e887770c.png)
![screenshot_22](https://cloud.githubusercontent.com/assets/19670319/19195462/4c93b05e-8ca1-11e6-95cd-242ab0c5eeeb.png)

- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/19195489/64d6ebf4-8ca1-11e6-882c-21dda816c86e.png)

**Comment by dorzar1989** [comment]
En la Version 1.3 de la IoP ya no sucede este error.

- Screenshot:

![screenshot_24](https://cloud.githubusercontent.com/assets/19670319/19202631/db1ff168-8cc2-11e6-9c91-db76756539f9.png)


- Emulador:

![nexus 4 4 1](https://cloud.githubusercontent.com/assets/19670319/19202640/e913cdbc-8cc2-11e6-8283-a6f1ec28688a.png)
