### ISSUE TITLE
Bit Coin Wallet_Request - Not Funds error

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#86]
### Template issue error report
Bit Coin wallet

#### Nombre pantalla
Request

### Bitcoin Wallet 

-----

##### Reporte de error: 
![error 1](https://cloud.githubusercontent.com/assets/17273005/13883611/6578e598-ecfc-11e5-88a4-978b3717371b.JPG)
![error q 1](https://cloud.githubusercontent.com/assets/17273005/13883634/76cac85c-ecfc-11e5-8f21-9c79965f267a.JPG)

   *El error radica en que como ven tengo saldo disponible y cuando le voy a aceptar el Request a X persona no me deja. El request era de 1.2000, es un monto que se podía enviar sin ningún problema. 
   
------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: 5.0

**Comment by MaviDavsa** [comment]
Trabajando en la Red... "Regtest"

**Comment by nattyco** [comment]
@MaviDavsa  te acordas el monto del payment que aceptaste?

**Comment by MaviDavsa** [comment]
@nattyco  El request era de 1.2000 ...

**Comment by nattyco** [comment]
@MaviDavsa  Probar este caso con la nueva version. Se reprodujo el error tratando de aprobar un payment enviado con red testnet a una wallet con red Regtest. Lo que se hiso es filtrar los payments por tipo de red.
El balance, transacciones y payments request de la wallet se filtran por tipo de red seteada, al igual que las address de los contactos.

**Comment by MaviDavsa** [comment]
@nattyco Probada! y hasta ahoraaa si funciona!

**Comment by MaviDavsa** [comment]
@augusto-ponce Se puede cerrar!
