### ISSUE TITLE
IoP Wallet- Error en nombres 

### ISSUE THREAD

**Issue by Gabymorillo** [Fermat-ORG/beta-testing-program#860]
#### Nombre pantalla

Home 

### Nombre de la Aplicación 

IoP Wallet

-----

##### Reporte de error: 

Al ingresar a IoP Wallet se puede apreciar que dice solicitar o enviar Bitcoins en lugar de Iop 

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-10-06-10-24-40_720](https://cloud.githubusercontent.com/assets/17262077/19157024/ebb77eb8-8bb1-11e6-8988-af7193456acf.png)

![screenshot_2016-10-06-10-24-50_720](https://cloud.githubusercontent.com/assets/17262077/19157037/f8b9a99c-8bb1-11e6-8d73-d3886aa6e136.png)

##### Pasos exactos para reproducir el error:

* Ingresar a la IoP Wallet

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/514024/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
- Modelo de dispositivo: Samsung GT-I9082L
- Versión de Android: 4.2.2
- API: 16
- dpi: 480 x 800 pixels, 5.0 pulgadas 

##### Screenshot o Capture de pantalla:

 
![screenshot_2016-07-07-15-11-28](https://cloud.githubusercontent.com/assets/17262077/19156938/978b2b28-8bb1-11e6-986f-603a8eadcaed.png)

**Comment by MaviDavsa** [comment]
@furszy

**Comment by maydiamc** [comment]
en la version 1.1 de IoP Wallet esto se soluciono

capture
![screenshot_10](https://cloud.githubusercontent.com/assets/17274154/19192601/c37f17c6-8c74-11e6-97e8-c3a8da2b766a.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/17274154/19192604/c58109b2-8c74-11e6-98a1-e6130cad8d1a.png)

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/19192619/ce469b34-8c74-11e6-8fc8-7c38333fec4f.png)
