### ISSUE TITLE
IoP Wallet Android -  En las pantallas Principales aparece la palabra "Bitcoins"

### ISSUE THREAD

**Issue by marielis-urbina** [Fermat-ORG/beta-testing-program#861]
##### Screenshot o Capture de pantalla:

![pantalla principal](https://cloud.githubusercontent.com/assets/19353722/19156989/c94e183c-8bb1-11e6-99a0-8581276d0bdf.png)

##### Pasos exactos para reproducir el error:

1.- Entro a la Wallet
2.- En la patalla principal, aparece recibir u obtener Bitcoins y no Iop

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/514051/logcat.txt)

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador

##### Screenshot o Capture de pantalla:

![nexus 5 6 0](https://cloud.githubusercontent.com/assets/19353722/19157193/81fd6b9e-8bb2-11e6-847e-7612877846ae.png)

**Comment by MaviDavsa** [comment]
@furszy

**Comment by gablup** [comment]
Probando desde un dispositivo físico, ocurre el mismo error.

![captura 1 iop](https://cloud.githubusercontent.com/assets/17261437/19158582/d49e9302-8bd8-11e6-82b1-54923134f6c1.png)

![captura 2 iop](https://cloud.githubusercontent.com/assets/17261437/19158595/dc2a7e4c-8bd8-11e6-9d25-ab927e2cecb5.png)

Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. 
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 246 MB.

**Comment by maydiamc** [comment]
En la versión 1.1 de IoP wallet esto se soluciono

Emulador
![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/19192451/479ec908-8c74-11e6-9e93-1a35ae91753f.png)
