### ISSUE TITLE
IoP Wallet Android: En el Home no aparece el Menú

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#865]
#### Nombre pantalla

Home

### Nombre de la Aplicación 

IoP Wallet

##### Reporte de error: 
   *Ingreso a la IoP Wallet al home y no se puede encontrar el menú, este no está arriba a la derecha.
Probe desde un emulador y este si aparece:

##### Screenshot o Capture de pantalla:
1 Desde el Celular:
![screenshot_2016-10-06-10-51-57](https://cloud.githubusercontent.com/assets/17283358/19158386/7e25425e-8bb6-11e6-9696-ecb4a3444e01.png)

2 desde un emulador Nexus 4 5.0.0
![no aparece el menu](https://cloud.githubusercontent.com/assets/17283358/19158329/4d0d891a-8bb6-11e6-9a81-344b5316520f.png)

##### Pasos exactos para reproducir el error:
1 Abrir la IoP Wallet
2 Estando en el home, buscar el menú, este no aparece

 *Detallar paso a paso la forma en  la cual se logro el error.

##### Inserta Archivo aLogcat: 

[logcat.1.txt](https://github.com/Fermat-ORG/beta-testing-program/files/514160/logcat.1.txt)

#### Dispositivo desde donde se realizo la prueba
- [x] Teléfono Físico
![screenshot_2016-09-20-11-54-38](https://cloud.githubusercontent.com/assets/17283358/19158175/ce7c609e-8bb5-11e6-9b04-3435104a00f6.png)

**Comment by MaviDavsa** [comment]
@furszy
