### ISSUE TITLE
IoP Wallet_ No se realiza la conversión automática en "Send" 

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#866]
#### Nombre pantalla
Send (enviar)

### Nombre de la Aplicación 
IoP Wallet Android

-----

##### Reporte de error: 

   *Al colocar un monto de monedas IoP, se debería hacer la conversión automática a moneda fiat, en la pantalla de de send esto no se realiza, sino que el monto se mantiene en 0, por lo tanto no se puede visualizar la cantidad de fiat currencies que se están enviando.

##### Screenshot o Capture de pantalla:

![screenshot_4](https://cloud.githubusercontent.com/assets/17274154/19158832/371ea538-8bb8-11e6-978d-fcd3f3627fa6.png)

##### Pasos exactos para reproducir el error:

-Ir a la pantalla Send (enviar)
-Colocar un monto en moneda IoP
-No se realizara la conversión automática 

##### Inserta Archivo aLogcat: 

11:25 am
[iop send.zip](https://github.com/Fermat-ORG/beta-testing-program/files/514186/iop.send.zip)
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- [] Teléfono Físico
- Modelo de dispositivo: nexus 4
- Versión de Android: 5.1
- API: 22
- dpi: 240

##### Screenshot o Capture de pantalla:

![nexus 4 5 1](https://cloud.githubusercontent.com/assets/17274154/19158936/8415c678-8bb8-11e6-8dba-b4a221d4422c.png)

**Comment by maydiamc** [comment]
@furszy

**Comment by wendyduran90** [comment]
En la versión  1.2 se soluciono este error . Esta prueba se realizo desde un teléfono físico con versión de android 4.4.

![image](https://cloud.githubusercontent.com/assets/20212920/19194688/7bcaf028-8c7c-11e6-8c01-bcaae60e53c7.png)

**Comment by Hernandezsmanu** [comment]
En la nueva version 1.2 se soluciono este error.

![screenshot_2016-10-07-10-56-27_720](https://cloud.githubusercontent.com/assets/5313335/19194846/2184cfac-8c7d-11e6-8170-bdf61ad0dfd5.png)

![screenshot_2016-10-07-10-56-49_720](https://cloud.githubusercontent.com/assets/5313335/19194848/24009c34-8c7d-11e6-82bb-8148cd5e2917.png)

**Comment by IsbetVR** [comment]
Closed #866
