### ISSUE TITLE
IoP WALLET ANDROID-ENVIAR BITCOINS-NO LOCALIZA CONTACTOS POR EL NOMBRE

### ISSUE THREAD

**Issue by GeronimoVierma** [Fermat-ORG/beta-testing-program#868]
#### Nombre pantalla

Enviar Bitcoins

### Nombre de la Aplicación 

IoP Version 1.0.2

-----

##### Reporte de error: 

   Al entrar en la pantalla "Enviar Bitcoins" e ingresar en la casilla "escriba dirección o nombre" (imagen 1) y colocar el nombre de un contacto agregado, este no lo reconoce por nombre sino únicamente por dirección de billetera del contacto (imagen 2 y 3), mi recomendación es que se elimine la palabra "nombre" de ese campo y dejar solo "escriba dirección" o activar la función para localizar contacto por el nombre.

##### Screenshot o Capture de pantalla:

![screenshot_4](https://cloud.githubusercontent.com/assets/19883115/19191319/eb05d528-8c6f-11e6-95e8-0721ed7ab1d7.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/19883115/19191407/4aa3ec40-8c70-11e6-81e5-cd77b14b4b64.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/19883115/19191439/72bc6216-8c70-11e6-9a0f-d0dc97a62b31.png)

##### Pasos exactos para reproducir el error:

 1 Asignar un nombre a la dirección de un contacto.
2 Ingresar en la pantalla "Enviar Bitcoins".
3 Ingresar el nombre del contacto en el campo "escriba dirección o nombre".

##### Inserta Archivo aLogcat: 

[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/516269/logcat.txt)

 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Emulador
- Modelo de dispositivo: Samsung s3
- Versión de Android: 4.1.1
- API:16
- dpi: 320

##### Screenshot o Capture de pantalla:

 *Agregar las capture de la descripcion del emulador o teléfono.
![screenshot_6](https://cloud.githubusercontent.com/assets/19883115/19192043/cbaa15ce-8c72-11e6-8a82-e2b4da0f9575.png)

**Comment by GeronimoVierma** [comment]
Version IoP 1.2
Solucionado, ya localiza los contactos por el nombre:

![screenshot_8](https://cloud.githubusercontent.com/assets/19883115/19194975/88d92b4e-8c7d-11e6-897b-f86435e2c2ef.png)

![screenshot_6](https://cloud.githubusercontent.com/assets/19883115/19194983/8fe05fde-8c7d-11e6-9c10-acd1fc907dd5.png)

**Comment by wendyduran90** [comment]
En la versión 1.2 se soluciono este error , el buscador funciona correctamente.  Esta prueba se realizo desde un teléfono físico con versión de android 4.4.

![image](https://cloud.githubusercontent.com/assets/20212920/19195028/c46d5644-8c7d-11e6-8daf-594b9c899f7d.png)

**Comment by MaviDavsa** [comment]
Solucionado
