### ISSUE TITLE
IoP Wallet Android - " Iop wallet no responde al entrar a la apk por primera vez"

### ISSUE THREAD

**Issue by wendyduran90** [Fermat-ORG/beta-testing-program#869]
#### Nombre pantalla
Iop wallet

### Nombre de la Aplicación 
Iop wallet 1.2

-----

##### Reporte de error: 

  Luego de instalar y entrar a la apk por primera vez, esta se cierra y aparece un aviso " iop wallet no responde". Al ingresar nuevamente muestra un mensaje de informe de error para reportar (capture 1)

##### Screenshot o Capture de pantalla:

![image](https://cloud.githubusercontent.com/assets/20212920/19195612/552f4118-8c80-11e6-8487-563d25565f4f.png)

  

##### Pasos exactos para reproducir el error:

- Entrar por primera vez

- Mensaje de " Iop wallet no responde"

 

##### Inserta Archivo aLogcat: 
[logcat.txt](https://github.com/Fermat-ORG/beta-testing-program/files/516516/logcat.txt)

 *Agregar el archivo alogcat del emulador o teléfono donde se produjo el error. 
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [x] Teléfono Físico
- Modelo de dispositivo: Blu Life One 2015
- Versión de Android:4.4
- API:19
- dpi: 

##### Screenshot o Capture de pantalla:

 
![caracteristicas_cel](https://cloud.githubusercontent.com/assets/20212920/19195745/c9e5f3ee-8c80-11e6-98b9-2eb0470194b3.jpg)

**Comment by IsbetVR** [comment]
@furszy

**Comment by furszy** [comment]
no me dice nada el logcat y el dialogo de envio no se encuentra activo aún.
Estoy por activarlo.

**Comment by gablup** [comment]
En las pruebas de la IoP Wallet con la versión de Play Store (en última actualización probado desde un dispositivo físico) ya no ocurre el error. 

![captura 2 iop](https://cloud.githubusercontent.com/assets/17261437/19246588/9ad39686-8f16-11e6-81ea-952500e0365e.png)

Resolución: 540 x 960 pixeles, 4.5 pulgadas
Dpi : 245
Modelo: Moto E 2da Gen. (Ya anexado en las imágenes del issue correspondiente)
ROM: de fábrica
Root: Sí
WiFi: Sí 
3G: No
GPS: Desactivado.
Memoria en SD Disponible: 1,72 GB.
Memoria interna Disponible: 236 MB.

**Comment by sanro14** [comment]
Solucionado
