### ISSUE TITLE
Bitcoin Wallet- No llegan los btc que envio

### ISSUE THREAD

**Issue by sanro14** [Fermat-ORG/beta-testing-program#87]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

Al enviar BTC se descuentan normal del book balance y del available balance, pero al contacto que se le envia no le llega nunca los BTC, solo la notificación en la parte superior, mas no se hace efectivo.
De igual forma pasa con el payment request, a la persona que se le hace la solicitud, le llega dicha solicitud ella la acepta, se descuentan de ambas partes book y available, pero a la persona que realizo el payment request no le llegan los BTC.

Esto está sucediendo en la Red Tesnet.

------

------

#### Dispositivo desde donde se realizo la prueba

* Marca: Genymotion
* Modelo: Google Nexus 5
* Version de Android: 4.4.4

**Comment by nattyco** [comment]
@sanro14  Los btc que enviaste se descontaron del book ? no te los devolvio? para saber si hubo alguna reversa de la transaccion

**Comment by sanro14** [comment]
@nattyco se descontaron de ambas partes, y no ha habido reversa de la transacción

**Comment by nattyco** [comment]
@sanro14  probar esto nuevamente con cualquiera de las redes y dame datos sobre el dispositivo al que no le llegan los btc

**Comment by nattyco** [comment]
@sanro14  verificar este caso con la ultima version de la app

**Comment by sanro14** [comment]
Cerrar..
