### ISSUE TITLE
IoP Wallet Android - No permite Enviar IoP cuando se pega la dirección en la opción "Enviar"

### ISSUE THREAD

**Issue by dorzar1989** [Fermat-ORG/beta-testing-program#870]
#### Nombre pantalla

Enviar IoPs

### Nombre de la Aplicación 

IoP Wallet Version Play Store

-----

##### Reporte de error: 

@furszy Al Copiar una direccion de cualquier fuente y pegarla en la Opcion de "Enviar" del home de la aplicacion, se procede a colocar un monto y aparece en la parte baja de la pantalla un aviso que dice "¡Direccion IoP Invalida!". 

##### Screenshot o Capture de pantalla:

![screenshot_2016-10-10-09-03-18](https://cloud.githubusercontent.com/assets/19670319/19241488/6775ed10-8efe-11e6-946c-6158236ce566.png)

##### Pasos exactos para reproducir el error:

- Copiar una Direccion
- Entrar a la aplicaicon 
- En el Home de la Wallet dar Click a la opcion "Enviar" en la parte baja de la pantalla
- Pegar la Direccion
- Ingresar Monto

##### Inserta Archivo aLogcat: 

[logcattxt.txt](https://github.com/Fermat-ORG/beta-testing-program/files/519822/logcattxt.txt)
 
  
------

#### Dispositivo desde donde se realizo la prueba

- [] Emulador
- [x] Teléfono Físico
- Modelo de dispositivo: S3 i9300
- Versión de Android: 4.3
- API: 
- dpi: 306

##### Screenshot o Capture de pantalla:

![screenshot_2016-10-10-11-22-48](https://cloud.githubusercontent.com/assets/19670319/19241481/5b923e40-8efe-11e6-937c-efb3962d2f2c.png)

**Comment by dorzar1989** [comment]
En la Version Actualizada de la Play Store este error No persiste.

- Screenshot:

![screenshot_2016-10-10-14-08-29](https://cloud.githubusercontent.com/assets/19670319/19246372/8947bdda-8f15-11e6-9a7a-5ac6bc27b28e.png)


- Movil: 

 
![screenshot_2016-10-10-11-22-48](https://cloud.githubusercontent.com/assets/19670319/19246377/8d73bddc-8f15-11e6-86aa-2dd8c3f6e779.png)

**Comment by sanro14** [comment]
Solucionado
