### ISSUE TITLE
Bitcoin Wallet- Book Balance negativo

### ISSUE THREAD

**Issue by augusto-ponce** [Fermat-ORG/beta-testing-program#88]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 
Después de hacer transacciones, en el book balance tengo una cifra negativa, al solicitar mas bitcoins me llegaron bien pero solo se reflejaron en mi saldo Disponible y no en el Book Balance !
A pesar de esta situación puedo seguir usando mis bitcoins sin problema.
Hice el intento varias veces de salir de la aplicación, cerrarla y el error persiste

<img width="401" alt="captura de pantalla 2016-03-22 a las 12 24 57" src="https://cloud.githubusercontent.com/assets/15804433/13956954/80245fa0-f029-11e5-8e6c-696033b27150.png">

<img width="399" alt="captura de pantalla 2016-03-22 a las 12 25 13" src="https://cloud.githubusercontent.com/assets/15804433/13956959/867457a2-f029-11e5-8c7c-92d0cf0f4bc1.png">

------
##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------
##### Contactos

- [x] Pantalla de contactos (Lista)
- [x] Pop up de ayuda
- [x] Pop up de agregar un contacto externo

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de envio

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Formulario de pedido de pago

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Requerimientos de pago

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible.Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
   
------
##### Settings

- [x] Pantalla de envio
- [x] Pantalla de recibiento

##### Reporte de error: 

   *Detallar el escenario de la prueba lo más completo posible. Indicando, si aplica, datos usados para las pruebas con los que se rellenaron campos de formularios.
   
------

#### Dispositivo desde donde se realizo la prueba

<img width="400" alt="captura de pantalla 2016-03-22 a las 12 29 05" src="https://cloud.githubusercontent.com/assets/15804433/13957040/c32bfc9a-f029-11e5-976f-90edfe8b4fee.png">

**Comment by nattyco** [comment]
@augusto-ponce  cuantos btc enviaste en total y cuantos tenias?

**Comment by augusto-ponce** [comment]
Te adjunto las pantallas que me pediste @nattyco 

<img width="403" alt="captura de pantalla 2016-03-22 a las 13 29 57" src="https://cloud.githubusercontent.com/assets/15804433/13959707/f535be92-f033-11e5-9658-40d084f40de6.png">


<img width="396" alt="captura de pantalla 2016-03-22 a las 13 30 15" src="https://cloud.githubusercontent.com/assets/15804433/13959717/004eb306-f034-11e5-84dd-d77b42a6dde5.png">


<img width="398" alt="captura de pantalla 2016-03-22 a las 13 30 40" src="https://cloud.githubusercontent.com/assets/15804433/13959734/0a21e0b0-f034-11e5-8301-deaf1f5e95a8.png">

<img width="402" alt="captura de pantalla 2016-03-22 a las 13 30 52" src="https://cloud.githubusercontent.com/assets/15804433/13959745/16321672-f034-11e5-9a3d-8de8ad2134a4.png">

**Comment by nattyco** [comment]
@augusto-ponce Se hicieron algunos ajustes en la nueva version,verificar si en las sucesiva pruebas este error vuelve a aparecer
