### ISSUE TITLE
Bitcoin Wallet Crashed when touch option menu

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#89]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla
Payment Request 

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *El error que se da en esta oportunidad es que estando en la opción de Payment la aplicación me corre normal, pero cuando voy a buscar una de las opciones del menú, la aplicación se queda completamente congelada y lo único que me sale es el error adjuntado. Por ende para seguir en la aplicación tuve que salirme de 0 para entrar nuevamente. 
   
![zxzxc](https://cloud.githubusercontent.com/assets/17273005/13990936/5e480610-f0e8-11e5-8cec-c1bb79559960.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: Android 6.0

**Comment by nattyco** [comment]
Adjunto captura del logcast sobre este error que pasa aveces @furszy 

Fermat Error Manager * Unexpected Exception Report
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ ========================================================================================================================================================
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Source: ACTIVITY
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Severity: UNSTABLE
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Exception Number: 1
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Exception Type: class java.lang.IllegalArgumentException
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Exception Message: Error in changeActivity
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Exception Possible Cause: N/A
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Exception Context:
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ N/A
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Exception Stack Trace:
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Class: com.bitdubai.android_core.app.AppActivity - Line: 291
03-23 13:33:03.453    4553-4553/org.fermat W/System.err﹕ Class: com.bitdubai.android_core.app.AppActivity - Line: 430
03-23 13:33:03.454    4553-4553/org.fermat W/System.err﹕ Class: com.bitdubai.android_core.app.FermatActivity - Line: 1602
03-23 13:33:03.454    4553-4553/org.fermat W/System.err﹕ Class: com.bitdubai.android_core.app.FermatActivity - Line: 142
03-23 13:33:03.454    4553-4553/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_android_api.ui.adapters.FermatAdapter$1 - Line: 50

**Comment by MaviDavsa** [comment]
@nattyco Casualmente me acaba de dar el mismo error hoy!

**Comment by furszy** [comment]
Ok, anotado

**Comment by nattyco** [comment]
@MaviDavsa  verificar en la ultima version como se comporta la app si se quedo asi congelada de nuevo.

**Comment by MaviDavsa** [comment]
@nattyco Si! Esto lo estuve verificando y si, se sigue quedando pegada en momentos... Esta captura es con el emulador de hoy... 

![error 1](https://cloud.githubusercontent.com/assets/17273005/14188150/6fd41ca2-f750-11e5-83a5-f6078426f467.JPG)

Dispositivo desde donde se realizo la prueba

Marca: Google Nexus
Modelo: 5
Version de Android: 6.0

**Comment by MaviDavsa** [comment]
![error 1](https://cloud.githubusercontent.com/assets/17273005/14323705/71253a1a-fbeb-11e5-8090-d96b509c63b7.JPG)
![error 3](https://cloud.githubusercontent.com/assets/17273005/14323706/7144eac2-fbeb-11e5-91a3-b3307c1d293b.JPG)

A la fecha de hoy los errores continuaron... 06/04/16 

Dispositivo desde donde se realizo la prueba

Marca: Google Nexus
Modelo: 5
Version de Android: 6.0

**Comment by MaviDavsa** [comment]
![error](https://cloud.githubusercontent.com/assets/17273005/14500005/2080aa20-016a-11e6-8f70-f170eced7546.JPG)

A la fecha de hoy los errores continuaron... 13/04/16, en esta oportunidad fue cuando fui a agregar a un contacto, una vez que le daba a enviar la solicitud me sale ese error, este fue la tercera vez que lo hice y las tres veces paso lo mismo! 

Dispositivo desde donde se realizo la prueba
Marca: Google Nexus
Modelo: 5
Version de Android: 6.0

**Comment by MaviDavsa** [comment]
![error 3](https://cloud.githubusercontent.com/assets/17273005/14676235/6cff047a-06d6-11e6-9358-8a5395986254.JPG)

En la ultima actualización se puede ver como el error persiste, con la diferencia que al darle hacia atrás se me congelo el Home...

![error 3b](https://cloud.githubusercontent.com/assets/17273005/14676258/87bb647a-06d6-11e6-8792-547231d46f5d.JPG)

Y quedó así como se muestra la imagen, tuve que salirme por completo, cerrar el emulador y todo para que se quitara el error...

Dispositivo desde donde se realizo la prueba
Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0

@nattyco

**Comment by MaviDavsa** [comment]
![error 1](https://cloud.githubusercontent.com/assets/17273005/14788430/99a9aada-0ad1-11e6-8ab0-373dc98fa9bc.JPG)

@nattyco A la fecha de hoy persiste el error... 

Dispositivo desde donde se realizo la prueba
Marca: Genymotion
Modelo: Google Nexus 4
Version de Android: 5.0

**Comment by sanro14** [comment]
@MaviDavsa cerrar
