### ISSUE TITLE
Bitcoin Wallet - Error al agregar un nuevo contacto de Fermat

### ISSUE THREAD

**Issue by yahdieli** [Fermat-ORG/beta-testing-program#93]
### Template issue error report

Bitcoin Wallet

#### Nombre pantalla

Agregar un contacto Fermat

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Al agregar un nuevo contacto de Fermat aparecen los contactos que pueden agregarse, pero al seleccionar uno y enviarle la solicitud de conexión se queda congelado en una pantalla negra. Aparece un mensaje indicando que se le envió la solicitud al contacto pero luego se queda congelado y no avanza.

![error contacto agregado](https://cloud.githubusercontent.com/assets/17284821/14081912/6bc6028e-f4e3-11e5-8b40-e4a28686b889.jpg)

Luego de esperar un rato largo a que la aplicación reaccione aparece el siguiente mensaje

![error contacto](https://cloud.githubusercontent.com/assets/17284821/14081922/80d9284a-f4e3-11e5-8b22-3f89cb38c348.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: Bluestacks
* Modelo: 2.0
* Version de Android: 6.0

**Comment by yahdieli** [comment]
@nattyco

**Comment by nattyco** [comment]
@furszy  la app esta dando en varios lugares este tema de que se queda como congelada esperando algo en el log cuando da error de cerrar sale esto:
org.fermat (org.fermat/com.bitdubai.android_core.app.AppActivity)
    PID: 28232
    Reason: Input dispatching timed out (Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.)

**Comment by furszy** [comment]
Vamos a hacer una revisión de todos estos temas, es probable que sea la versión del emulador bluestacks que nos esté dando problemas. Así que bajemos dicha app y probemos ahí mismo Fermat.

**Comment by nattyco** [comment]
@yahdieli pudiste intalar el genymotion? seguis probando con el bluestacks? te volvio a dar problemas la app?

**Comment by yahdieli** [comment]
@nattyco La actualización instalada el día de hoy de la app no me ha arrojado ese error esta corriendo bien, sigo en el emulador bluestack no he podido instalar el Genymotion

**Comment by nattyco** [comment]
ok lo cerramos entonces
