### ISSUE TITLE
Bit Coin Wallet_Graphic Issue botones Add Contacto

### ISSUE THREAD

**Issue by adryx83** [Fermat-ORG/beta-testing-program#94]
#### Nombre pantalla

Contactos / Payment Request / Menu Principal

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *En este caso algunos de los botones de las pantallas antes mecionadas quedan encima de los textos y el menú interrumpiendo la visibilidad y la comodidad para el usuario.

![screenshot_2016-03-28-11-33-51](https://cloud.githubusercontent.com/assets/17273349/14082514/3eeffe8a-f4da-11e5-9661-246633474e89.png)

 ![screenshot_2016-03-28-11-34-09](https://cloud.githubusercontent.com/assets/17273349/14082491/17ea6384-f4da-11e5-892a-9cdbcbec3e42.png)
![screenshot_2016-03-28-11-34-20](https://cloud.githubusercontent.com/assets/17273349/14082493/1960ad22-f4da-11e5-9b4d-790042ade77d.png)

#### Dispositivo desde donde se realizo la prueba

* Marca: ZTE
* Modelo:Apex 2
* Version de Android: 4.4.2

**Comment by adryx83** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
Solucionado!
