### ISSUE TITLE
Bitcoin Wallet- Contacts - Get Address Performance

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#95]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla
Contact Detail

### Bitcoin Wallet 

-----

##### Detalle del contacto

- [x] Pantalla del detalle del contacto

##### Reporte de error: 

   *Este contacto esta en mi lista de contactos pero no me aparece el Address de esta persona, aún cuando está persona esta Online... El mensaje que me da es que vuelva en 2 minutos... Volví 10 minutos después y me da absolutamente el mismo error. 
   
![error 1](https://cloud.githubusercontent.com/assets/17273005/14082618/d5b59d0c-f4da-11e5-9b87-70d41c5555e2.JPG)

------   
#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: 6.0

**Comment by augusto-ponce** [comment]
No te olvides de mencionarla a Natalia

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@furszy Tenemos que ver estos temas de comunicacion lenta en la capa de P2P

**Comment by furszy** [comment]
Ok si, primero Descartemos que sea un tema del addresses que se queda en algún punto y luego organicemos una reunión con Roberto y @MaviDavsa para que nos envíe el log de su aplicación y ver lo que pasa en su celular

**Comment by MaviDavsa** [comment]
@nattyco @furszy  Tarde! Pero ya llegó el Address!

**Comment by MaviDavsa** [comment]
@nattyco @furszy Me vuelve a pasar con otro contacto! Me imagino que para mana debe aparecerme el contacto como tal pero... No debería tardarse tanto!

**Comment by MaviDavsa** [comment]
![error 2](https://cloud.githubusercontent.com/assets/17273005/14149374/b905e4d4-f66d-11e5-9538-729df18e67dc.JPG)

En la nueva versión persiste el error... Desde las 9:30am tengo a este contacto en mii lista de contactos y nada que me aparece el Address! 
Y ya no es el Emulador... Porque estoy utilizando Genymotion 
Con las siguientes características... 

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: S6
* Version de Android: 6.0

**Comment by furszy** [comment]
@nattyco por favor probá esto en el S6 y avisame.

**Comment by nattyco** [comment]
@furszy  yo localmente no tengo problemas los mensajes llegan al instante practicamente, pobando con S6 Motorola, Nexus. Voy a organizar unas pruebas con Joaquin, porque hay que ver tambien el tema del ancho de banda y la conexion a internet.

**Comment by Exilum** [comment]
@furszy  @nattyco  yo probe localmente tambien y no tuve problemas al respecto, los mensajes me llegaron rapido igual que siempre.

**Comment by nattyco** [comment]
@MaviDavsa  se hicieron cambios para la version Samsung verificar esto nuevamente y comentar si mejoro

**Comment by MaviDavsa** [comment]
@nattyco Bella... lo probe contigo y con Augusto y todo fue en lineas generales rapido... Cuando lo hago con las muchachas se tarda muchisimo mas pero ya allí, no se si es problema de la app o de la red! Creo que es de la Red de internet o sea la banda ancha acá en vzla! :)

**Comment by nattyco** [comment]
@furszy  decime que hacemos con este reporte lo doy por cerrado o hay algo para ver en la red P2P,si la conexion a internet es buena el address y demas cosas llegan rapido.

**Comment by furszy** [comment]
Dalo por cerrado, si es tema de red ya no es inconveniente nuestro hasta que mejoremos el tamaño de los paquetes. Es como cuando queres bajar un archivo de internet, si no tenes buena señal obviamente se va a tardar más.
