### ISSUE TITLE
Bit Coin Wallet_ Contacts - Error on back press

### ISSUE THREAD

**Issue by MaviDavsa** [Fermat-ORG/beta-testing-program#96]
### Template issue error report
Bit Coin Wallet

#### Nombre pantalla
Contacts

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Estaba en la pantalla de Contacts Detail y cuando fui hacia atrás me salio está pantalla y allí se quedo congelada la aplicación para poder acceder de nuevo a ella tuve que cerrarla y abrirla desde 0. 
   
   
![error 2](https://cloud.githubusercontent.com/assets/17273005/14082768/986bb2b4-f4db-11e5-85de-5258230401ff.JPG)

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: Bluestarks
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by MaviDavsa** [comment]
@nattyco Persiste el error!

**Comment by nattyco** [comment]
@MaviDavsa  verificar estos problemas de cierres y demoras con la nueva version disponible

**Comment by MaviDavsa** [comment]
Solucionado! o por lo menos no ha vuelto hasta ahora! :)
