### ISSUE TITLE
Bit Coin Wallet_ Home Pantalla Freezada se cierra la App

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#97]
### Template issue error report
Bitcoin Wallet

#### Nombre pantalla
Pantalla de inicio 

### Bitcoin Wallet 

-----

##### Home

- [x] Pantalla de Transacciones recibidas (Es la de la derecha)
- [x] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [x] Pop up de bienvenida
- [x] Pop up de ayuda

##### Reporte de error: 

   *Al pulsar el botón Bitcoin Wallet se queda en negro la pantalla (congelada), piso el botón de retroceder y no funciona, luego aparareció una nota que decía: FERMAT no responde Esperar o aceptar.  Esto ocurrió varias veces hasta que logre entrar. Ahora alas 4:40pm hora de Venezuela probé nuevamente la apk y arroja el mismo error. 

   
![final_bstsnapshot_62564](https://cloud.githubusercontent.com/assets/17283358/14091175/7f7f3000-f508-11e5-90c5-76f4c0dc70a9.jpg)
   
------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BLUESTACK
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by nattyco** [comment]
@yolandayancel verificar estos problemas de cierres y demoras con la nueva version disponible

**Comment by yolandayancel** [comment]
Buenos dias Natatia Cortes

Recibido

Saludos Cordiales

2016-03-30 8:32 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> verificar estos
> problemas de cierres y demoras con la nueva version disponible
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/97#issuecomment-203421604>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by yolandayancel** [comment]
Buenas tardes Nattalia Cortes

En prueba de fecha: 30-03-2016 caso 97

Resumen:
Al iniciar la apk muy lenta, luego al hacer click en BITCOIN WALLET, ahora
la pantalla no se queda negra, sino que pasa a una pantalla que
adjunto.(pude tomar una captura con el celular) luego después de pocos
segundos, aparece otra pantalla con un recuadro que dice waitig,y comienza
una descarga y se queda así por varios minutos hasta que en  pase al
Setting, luego en restart android plugin  hice click y la reinicie.
En espera de nuevas indicaciones.
Saludos Cordiales


2016-03-30 8:32 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> verificar estos
> problemas de cierres y demoras con la nueva version disponible
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/97#issuecomment-203421604>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by nattyco** [comment]
@yolandayancel  lo que reportas es un problema con el emulador que tenes que se puso a descargar algo y se quedo tildado, por lo que entiendo.

**Comment by nattyco** [comment]
@yolandayancel  comentame si esto te volvio a pasar con las nuevas versiones

**Comment by yolandayancel** [comment]
Buenos días  Natalia

Revisado caso 125
Al realizar prueba, iniciando la aplicación fermat,  esta abrió  normal ya
no apareció  el error reportado.
Emulador Genymotion
Samsung Galaxy S6
Versión 5.1.0
A la espera de sus instrucciones
Saludos cordiales
