### ISSUE TITLE
Sub App Community Pantalla Freezada se cierra la App

### ISSUE THREAD

**Issue by yolandayancel** [Fermat-ORG/beta-testing-program#98]
### Template issue error report
Bitcoin Wallet

#### Nombre pantalla
Settings

### Bitcoin Wallet 

-----

##### Reporte de error: 

   *Cuando estoy dentro de CONNETIONS y elimino un contacto, la pantalla se congela y aparece un recuadro: FERMAT no responde,  esperar o aceptar,  y se salio de la APK.
![final_bstsnapshot_17074](https://cloud.githubusercontent.com/assets/17283358/14091842/60bd8f14-f50c-11e5-90be-1d56b56ed6e2.jpg)

------

#### Dispositivo desde donde se realizo la prueba

* Emulador: BlueStarks
* Version de Android: 6.0

**Comment by MaviDavsa** [comment]
@nattyco

**Comment by furszy** [comment]
@MaviDavsa necesito saber características del hardware del emulador que estar corriendo, memoria RAM, nucleos, etc.
Fíjate en el settings y manda me una foto por aquí por favor. Gracias.

**Comment by MaviDavsa** [comment]
@furszy  Holaaa buenos días!!! Maty, este emulador como tal no muestra esas cosas... Se que es Android 6.0 por un complemento que le activamos cuando lo descargamos! Pero especificamente la app no me deja ver esas partes de hardware! 

![sdfsdf](https://cloud.githubusercontent.com/assets/17273005/14109398/9a1d8d52-f58b-11e5-9418-08194c8b7092.JPG)

Esas son todas las opciones que me da!

**Comment by yolandayancel** [comment]
Buenos días Srta. MaviDavisa

Las características del Emulador Bluestack que estoy corriendo en mi PC son
las que aparecen en la descripcción que ofrece en el link que dejo debajo
del texto.

*Bluestacks 2016 ROOTEADO+ Laucher Android 6.0  EDICIÓN 2016.*

*Video YOUTUBE:*



https://www.youtube.com/watch?v=hZB-8YMkTEI



*Descarga Bluestacks Android 6.0 Marshmallow*

– Descargar Bluestacks v2.0 <http://www.bluestacks.com/download.html>
– Descargar Android 6.0 Marshmallow para Bluestacks (
https://mega.nz/#!rZIiCJDT!4hnGO377fEgEO7RK6Vbut7V9Ya2ut72sPwIAQDmxXyM)



*Descarga de Aplicación*

– Descargar KingRoot (APK)
<https://mega.nz/#!3ZgTlDra!ylc6rritpCjQ6CFKwRR4Ahk0E5nNT1fCYKh-EHjLaDI>
– Descargar ES File Explorer (APK)
<https://mega.nz/#!WdYj0JyC!sIZXEahTnaMzYUaApJsbKagKJozLPZXr7lxZJes2ZdE>

 Adjunto fotos del Setting

2016-03-29 8:14 GMT-04:30 furszy <notifications@github.com>:

> @MaviDavsa <https://github.com/MaviDavsa> necesito saber características
> del hardware del emulador que estar corriendo, memoria RAM, nucleos, etc.
> Fíjate en el settings y manda me una foto por aquí por favor. Gracias.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/98#issuecomment-202876301>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by MaviDavsa** [comment]
@yolandayancel Esas son características de instalación! No del hardware que utiliza el emulador!

**Comment by yolandayancel** [comment]
Buenos días

En las fotos  que adjunte en el correo anterior, en el Setting no da
detalles sobre el Hardware que tiene el Emulador.

Saludos Cordiales


2016-03-29 9:18 GMT-04:30 MaViDavsa <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> Esas son
> características de instalación! No del hardware que utiliza el emulador!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/98#issuecomment-202901064>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by nattyco** [comment]
@yolandayancel  verificar estos problemas de cierres y demoras con la nueva version disponible

**Comment by yolandayancel** [comment]
Buenos días Natalia Cortes

Te hago por aquí un resumen de lo ocurrido al descargar la nueva apk
30-03-2016:

-Procedí a la descarga
- Al iniciar el Bluestack se quedo cargando, la pantalla se puso en blanco.
-Con el mause salí de la pantalla de escritorio y me fui a la pantalla de
inicio de mi PC, estando allí trate de cerrar secion
pero esta congelada la pantalla, no puedo volver al escritorio tampoco. el
mause es el unico que funciona, pero no funcionan ninguna de las
aplicaciones instaladas en mi PC.

En este momento estoy trabajando desde otra la PC, pero no puedo
comunicarme con el grupo del Slack (al ingresar mi password no lo reconoce).

Sigo tratando de ver como ingreso al Slack, para poder comunicar
directamente al grupo esta experiencia.

Saludos


2016-03-30 8:30 GMT-04:30 Natalia Cortez <notifications@github.com>:

> @yolandayancel <https://github.com/yolandayancel> verificar estos
> problemas de cierres y demoras con la nueva version disponible
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Fermat-ORG/beta-testing-program/issues/98#issuecomment-203420964>
>



-- 
*Saludos cordiales*

*Yolanda Yancel*
Lcda. Contaduría Pública
=426-9811123
Tlf:  281-2 <281-2818262>676587
Email.yyancel47@gmail.com

**Comment by nattyco** [comment]
@yolandayancel  lo que reportas es un problema con tu PC no con la aplicacion de fermat en si

**Comment by nattyco** [comment]
@yolandayancel  comentame si esto te volvio a pasar con las nuevas versiones
