### ISSUE TITLE
Bitcoin Wallet_ Btc no se reflejan en el Available Balance

### ISSUE THREAD

**Issue by maydiamc** [Fermat-ORG/beta-testing-program#99]
### Bitcoin Wallet 

-----

##### Home

- [] Pantalla de Transacciones recibidas (Es la de la derecha)
- [] Pantalla de Transacciones enviadas (Es la de la izquierda)
- [x] Balance (es la circunferencia con la cantidad de bitcoin)
- [] Pop up de bienvenida
- [] Pop up de ayuda

##### Reporte de error: 

   Los btc enviados de mis contactos, solo se reflejan en el Book Balance, nunca se hacen efectivos en el Available Balance, ni se muestran en la pantalla de Received, cuando ya estos btc fueron debitados del Available Balance del emisor
![screenshot_2016-03-28-16-09-56](https://cloud.githubusercontent.com/assets/17274154/14110522/9518774a-f590-11e5-9123-00c520110634.png)
![screenshot_2016-03-28-16-10-05](https://cloud.githubusercontent.com/assets/17274154/14110526/9ccf641c-f590-11e5-9314-ba4d5802376f.png)

. 

#### Dispositivo desde donde se realizo la prueba

* Marca: Samsung Galaxy
* Modelo: mini s4
* Version de Android: 4.4.2

**Comment by maydiamc** [comment]
@nattyco

**Comment by nattyco** [comment]
@acostarodrigo  Rodrigo: Tenemos dos casos de usuarios de Samsung Galaxy S4 mini que tienen problemas para recibir los btc, ya sea desde envios de otros intra users como enviados desde un extra user por la red testnet. Podrias ver a que se debe esto?

**Comment by acostarodrigo** [comment]
Hi, I'm not responsible for the transactions not showing in your wallet.

Verify if the device detects the incoming crypto transactions from the bitcoin network.
They are entries in the database of the Bitcoin Network Plugin, table Transactions.

Please post a screen shot of that table.

**Comment by nattyco** [comment]
@acostarodrigo  Las transacciones llegaron porque los btc estan en el book, el problema es que no se confirman para pasar al available.

@maydiamc  Rodrigo quiere una cartura de la base de datos donde estan las transacciones, mañana antes de hacer nada hablame asi te digo como sacarla.

**Comment by maydiamc** [comment]
no se ha probado este error debido a que se esta trabajando en otra red, la regtest

**Comment by nattyco** [comment]
@maydiamc el tema de que se te confirmen los btc podes probarlo en ambas redes

**Comment by nattyco** [comment]
@maydiamc verificar este caso con la ultima version, comentame si pedis btc al faucet te llegan bien.

**Comment by maydiamc** [comment]
en la ultima actualizacion se solucionoel problema @nattyco
